Feature bjs2 6246
CorporationX/user_service pull request #1002
Opened 2024-05-03 13:42 UTC by Kayfral

2024-05-04 11:24 UTC, Demchenkov7 requested changes
В теории можно еще подумать стоит ли делегировать локигу валидации в отдельный класс валидотор

2024-05-04 11:24 UTC, Demchenkov7 commented on src/test/java/school/faang/user_service/service/service/SkillServiceTest.java
> +    private SkillMapper skillMapper;
Можно повесить @Spy на SkillMapperImpl и дальше использовать его, не создавая новый объект

2024-05-04 11:24 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        checkUserInDB(userId);
А нужна ли эта проверка? Она же автоматически выполнится на уровне БД, при запросе скилов.

2024-05-04 11:24 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        checkUserInDB(userId);
Аналогично про проверку

2024-05-04 11:24 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public Optional<SkillDto> acquireSkillFromOffers(long skillId, long userId) {
Возвращаемое значение должно быть SkillDto

2024-05-04 11:24 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public Optional<SkillDto> acquireSkillFromOffers(long skillId, long userId) {
Можно использовать методы Optional ifPresentOrElse() или ifPresentOrThrow()

2024-05-04 11:24 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        final int MIN_SKILL_OFFERS = 3;
В верхнем регистре только константы (static final) переменные.
Как раз можно вынести в поля и сделать константой

2024-05-04 11:24 UTC, Demchenkov7 commented on src/test/java/school/faang/user_service/service/controller/SkillControllerTest.java
> +    public void testCreateSkill() {
Этот и предыдущий тест фактически про одно и то же

2024-05-04 11:24 UTC, Demchenkov7 commented on src/test/java/school/faang/user_service/service/controller/SkillControllerTest.java
> +        assertEquals(expectedSkills, actualSkills);
В принцепе достаточно будет черезе verify проверить, что skillService вызывается

2024-05-04 11:24 UTC, Demchenkov7 commented on src/test/java/school/faang/user_service/service/service/SkillServiceTest.java
> +    public void testDtoToSkillMapper() {
Ну этот тест относиться не к сервису, можно сделать отдельный тест на маппер

2024-05-05 11:03 UTC, Kayfral commented on src/test/java/school/faang/user_service/service/controller/SkillControllerTest.java
> +    public void testCreateSkill() {
Перепроверив себя, я считаю, что эти два теста нужны. 1) Проверяет, что не выбрасывается exception при корректных данных. 2) Проверяет корректность взаимодействия контроллера с сервисом.

2024-05-05 12:57 UTC, Demchenkov7 requested changes

2024-05-05 12:57 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    static final int MIN_SKILL_OFFERS = 3;
Забыл модификатор доступа

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/dto/skill/SkillDto.java
> +    private long id;
«В пакете dto.skill создайте класс SkillDto, если его нет. Поля: Long id, String title».
В условии задачи нужно было создать переменную ссылочного типа «Лонг».

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/mappers/SkillMapper.java
> +    Skill DtoToSkill(SkillDto skillDto);
когда ты вызываешь SkillMapper. уже понятно что будешь мапить. скилл это сущность entitty, принято называть переменные по их действию. toEntity/ и сразу ясно SkillMapper.toEntity(...) мапишь на сущность "Skill"

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/mappers/SkillMapper.java
> +    SkillDto skillToDto(Skill skill);
проще можно обзывать) skillToDto <= toDto(....)';

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/mappers/SkillMapper.java
> +    default SkillCandidateDto skillToSkillCandidateDto(Skill skill, long offersAmount) {
Этот дефолтный метод выполняет преобразование скиллов в дто скил кандидата?
Почему сделал его дефолтным? какие преимущества дефолтных методов в интерфейсе?

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        Skill skill = skillMapper.DtoToSkill(skillDto);
заменить название переменной можно глобально. CTRL+SHFT+f6

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        Skill skill = skillMapper.DtoToSkill(skillDto);
что может произойти если другой поток сюда зайдет и тоже захочет сохранить скилы?

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        checkUserInDB(userId);
нормально, но когда уже будет существовать UserService, можно будет вызвать метод получения пользователя по Id,и соотвественно в нем уже будет обработан кейс, когда пользователя нет.

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public SkillDto acquireSkillFromOffers(long skillId, long userId) {
Можно добавить аннотацию @Transactional, чтобы обеспечить соответствие принципу ACID

2024-05-07 18:48 UTC, vang31 commented on src/main/java/school/faang/user_service/dto/skill/SkillDto.java
> +@NoArgsConstructor
можно добавить аннотацию @Builder, чтобы легче тесты писать

2024-05-07 18:48 UTC, vang31 commented on src/test/java/school/faang/user_service/service/controller/SkillControllerTest.java
> +        SkillDto skillDto = createSkillDto(null);
например с билдером, можно вынести создание дтоскила наружу. на верхний уровень, и, не создавать его в каждом тесте.

2024-05-07 18:48 UTC, vang31 commented on src/test/java/school/faang/user_service/service/controller/SkillControllerTest.java
> +        assertThrows(DataValidationException.class, () -> skillController.create(skillDto));
и тогда с билдером. () -> SkillDto.builder().id(1L).title(null).build()))

2024-05-07 18:48 UTC, vang31 commented on src/test/java/school/faang/user_service/service/mappers/SkillMapperTest.java
> +        SkillDto skillDto = createSkillDto(1L, "firstTitle");
Так как это используется в тестах не 1 раз, то можно вынести в некий степ ап до выполнения тестов.

2024-05-07 18:48 UTC, vang31 commented on src/test/java/school/faang/user_service/service/mappers/SkillMapperTest.java
> +        SkillDto skillDto = createSkillDto(1L, "firstTitle");
есть аннотации Before, BeforeEach.

2024-05-07 18:48 UTC, vang31 commented on src/test/java/school/faang/user_service/service/service/SkillServiceTest.java
> +        long userId = 1L;
То же самое, посмотри в нескольких тестах, используется один и тот же степ ап, попробуй вынести всё в сет ап с аннотацией.

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    }
хорошее правило: сначала идут публичные методы, потом приватные 

Публичные методы обычно содержат основную логику, удобно ее сразу всю видеть, а приватные содержат что-то более частное, поэтому их тащим вниз

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +        if (skillDto.getTitle() == null || skillDto.getTitle().isEmpty()) {
тут я бы вместо isEmpty использовала isBlunk, шире проверка 
Проверит на то, что в строчке не лежит последовательность пробелов

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    private void validateSkill(SkillDto skillDto) {
тебе сюда достаточно только title передать)

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/skill/SkillDto.java
> +    private long id;
Почему так: 

скиллDto может сюда прийти без айдишника, потому что, например, при создании скилла пользователь не будет айди передавать, так как это не ответственность пользователя - придумать айди, а ответственность приложения

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/mappers/SkillMapper.java
> +    Skill DtoToSkill(SkillDto skillDto);
Методы называем с маленькой буквы

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        }
Смотри, у тебя сейчас в контроллере есть метод валидации и в сервисе есть метод валидации 

Будет по SOLID, если мы создадим отдельный класс SkillValidator и туда вынесем вот эти методы валидации. Так мы реализуем принцип единой ответственности - валидатор будет отвечать за валидацию, контроллер только за прием и передачу данных, а сервис за основную логику приложения

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
Вот это - ответственность UserService  
Ты ведь идешь в таблицу user проверить существование пользователя 
Этим не должен заниматься скилл сервис 

Перенеси этот метод в userService 
Ведь во многих других местах такой метод тоже может понадобиться другим людям, и они вряд ли будут его искать по всему прилоежнию, им будет удобнее взять его из userService сразу.

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public SkillDto acquireSkillFromOffers(long skillId, long userId) {
Это на будущее, на тот случай, если сам хочешь заранее про это изучить. Мы будем позднее на Буткемпе проходить эту тему подробно, но ты уже сейчас можешь об этом почитать и пользовать

2024-05-08 09:30 UTC, InnMish commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        }
Вот этот метод подумай, как переписать и где он должен лежать 

Если ты проверяешь что-то в юзер-репозитории, это должен делать юзер сервис

2024-05-09 08:09 UTC, Kayfral commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        checkUserInDB(userId);
Хорошо, у меня вопрос. Пока нет UserService, то правильно будет сделать Mock?

2024-05-10 18:30 UTC, vang31 reviewed
нужно разрешить конфликт

2024-05-11 11:59 UTC, merged