basilisk-master-bc4-get-offered-skills
CorporationX/user_service pull request #1005
Opened 2024-05-03 18:39 UTC by AVishevsky

2024-05-05 19:33 UTC, Makaksik13 requested changes

2024-05-05 19:33 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillRepository.findSkillsOfferedToUser(userId).stream()
А если userId null? Снова нужна проверка.

2024-05-05 19:33 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .map(entry -> skillCandidateMapper.toDto(entry.getKey(), entry.getValue())).collect(Collectors.toList());
Можно просто метод toList к потоку применить, а не городить collect(Collectors.toList()) .

2024-05-06 06:49 UTC, Ethiqque reviewed
Нужно лишь убрать компонент

2024-05-06 06:49 UTC, Ethiqque commented on src/main/java/school/faang/user_service/service/SkillService.java
>  @Component
@Service уже содержит в себе @Component

2024-05-06 07:32 UTC, Ethiqque commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillRepository.findSkillsOfferedToUser(userId).stream()
Лучше в начале каждого метода делать валидацию через skillValidator

2024-05-06 18:49 UTC, AVishevsky commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillRepository.findSkillsOfferedToUser(userId).stream()
мне вроде бы не нужна валидация в этих двух методах, по заданию точно не было такого

2024-05-09 18:39 UTC, Makaksik13 requested changes

2024-05-09 18:39 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .map(entry -> skillCandidateMapper.toDto(entry.getKey(), entry.getValue())).toList();
Все терминальные/промежуточные операции должны начинаться с новой строки. Перенеси toList(). Аналогично поступи в других методах.

2024-05-09 18:39 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
Убери отступ.

2024-05-09 18:39 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/mapper/SkillCandidateMapper.java
> +
Лишний отступ.

2024-05-09 18:39 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/mapper/SkillCandidateMapper.java
> +
Убери отступ.

2024-05-12 07:32 UTC, merged