BJS2-6298
CorporationX/user_service pull request #1007
Opened 2024-05-04 03:42 UTC by nn1ck0

2024-05-04 07:29 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalServiceTest.java
> +        GoalDto goalDto = new GoalDto();
Ты же написал метод updateInit. Может стоит уменьшить повторение кода с созданием целей?

2024-05-04 07:31 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/GoalController.java
> +        if (goalDto.getTitle().isBlank()) {
А, если параметр будет null ? Может стоит добавить и эту проверку. (Это относится и к другим методам, например, createGoal)

2024-05-04 07:31 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/GoalController.java
> +            throw new DataValidationException("Goals title must exists");
Повторение текста ошибки (такой же уже есть в createGoal.)

Эта же ситуация есть в сервисе

2024-05-04 07:33 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/GoalController.java
> +package school.faang.user_service.controller;
В задании указано, что контроллер надо создать в пакете "controller.goal"

2024-05-04 07:34 UTC, NadirCianid commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +    @Query(nativeQuery = true, value = """
Id у цели должно генерироваться автоматически, а не по переданному параметру (насколько я понимаю)

Сигнатура метода из задания: Goal create(String title, String description, long parent);

2024-05-04 07:34 UTC, NadirCianid commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +    void addSkillToGoal(long skillId, long goalId);
Id у цели должно генерироваться автоматически, а не по переданному параметру (насколько я понимаю)

Сигнатура метода из задания: Goal create(String title, String description, long parent);

2024-05-04 07:35 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalService.java
> +            throw new UserGoalsValidationException("Max active goals doesnt grand then MAX_ACTIVE_GOALS");
Странный текст исключения. По идее мы здесь проверяем не будет ли новая цель создавать ситуацию, когда у пользователя привысится макс. число целей.

2024-05-04 07:36 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalService.java
> +                .forEach(skill -> goalRepository.addSkillToGoal(skill.getId(), goal.getId()));
По-хорошему ты должен использовать возвращаемый объект из репозитория, а не тот, что был передан в параметрах метода

2024-05-04 07:37 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalServiceTest.java
> +        verify(goalRepository, times(1)).create(goal.getTitle(), goal.getDescription(), goal.getId());
Mockito.times(1) можно не писать. В дефолтной версии verify по умолчанию проверяется вызов 1 раз

2024-05-04 07:43 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalService.java
> +package school.faang.user_service.service;
Надо  было сервис создать в своем пакете service.goal

2024-05-04 23:21 UTC, nn1ck0 commented on src/test/java/school/faang/user_service/service/GoalServiceTest.java
> +        verify(goalRepository, times(1)).create(goal.getTitle(), goal.getDescription(), goal.getId());
Пишу это просто для наглядности

2024-05-05 07:00 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalServiceTest.java
> +        verify(goalRepository, times(1)).create(goal.getTitle(), goal.getDescription(), goal.getId());
я также писал. Но  техлид мне посоветовала так не писать. Теперь я также советую тебе. Дело твое, как писать

2024-05-05 07:05 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        }
По-моему мнению, это можно объединить в одну проверку и в одну ошибку DataValidationException.

2024-05-05 07:16 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +                .toList();
Когда у тебя в стриме целей будет несколько, удовлетворяющих разным фильтрам, получится, что каждый из таких фильтров будет дублировать такую цель. В итоге у тебя может быть в выходном списке несколько дубликатов, так как каждому фильтру на вход подается исходный стрим целей.

2024-05-05 07:17 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private final List<GoalFilter> goalFilters;
Не вижу тестов на фильтры

2024-05-05 07:27 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +}
Не вижу тестов для skillService

2024-05-05 20:39 UTC, Sabina-Vishnya requested changes
давай резолвить те замечания, которые ты поправил, легче будет всем при ревью
поправил и зарезолвил

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/filters/GoalFilter.java
> +package school.faang.user_service.service.filters;
я сначала думала будет папка фильтров и в ней подпаки к каждому сервису, но вы реализовывать стали иначе (ты и Денис), поэтому давай сделаем в одном стиле, как начал делать Денис, добавим папку эту с фильтрами, в папку goal
в итоге у нас будет что-то типа
```
service/
├── goal/
│   ├── filter/
│   │   ├── GoalFilter
│   │   └── ...
│   └── GoalService
└── user/
    ├── filter/
    │   ├── UserFilter
    │   └── ...
    └── UserService
```

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/filters/GoalStatusFilter.java
> +public class GoalStatusFilter implements GoalFilter {
Зачем нам публичные все фильтры?)
Где-то используются?

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +    @InjectMocks
отступов нет в нескольких местах, правь форматирование и проверь, на всякий случай, неиспользуемые импорты

1. Форматирование: ⌘⌥L (macOS) / Ctrl+Alt+L (Windows/Linux) в каждом классе. 
Либо перед коммитом в idea поставить галочку на Reformat Code

2. Для импортов: Ctrl + Alt + O (Windows/Linux) или ⌘ + Option + O (macOS). 
Либо перед коммитом галочку на Optimize imports

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void createGoal(Long userId, Goal goal) {
энтити в контроллер тащишь, а зачем?
и почему в некоторых методах дто тогда?

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
Нужно ли unmappedTargetPolicy = ReportingPolicy.IGNORE? для чего? Что это делает?

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/skill/SkillServiceTest.java
> +        assertEquals(false, skillService.checkSkillsInDB(skills));
тут можно assertFalse
а ниже в методе assertTrue

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/skill/SkillServiceTest.java
> +    SkillService skillService;
почему не приватные поля и именно здесь, так задумано или нет?)

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +        verify(skillService, times(1)).assignSkillToUser(1L, 1L);
Удаляй этот times(1) это перегружает код и аргумент "чтобы наглядно было" не очень сильно тут работает. Знаю, что Денис тебе тоже подсвечивал такое, но ты оставить решил. 
Так вот смотри, ведь если будет вызов 1, то дефолтно так и есть, 
если вызовов больше, мы явно и укажем times(2), например, 
а если вызовов не будет, то на этот случай есть другие методы

сейчас же у тебя эти строки кода длиннее лишь за счет этого аргумента, который можно не писать и по сути лишняя трата твоего времени, если это прям руками бы всё писалось, без автозаполнения, а мы ведь по возможности хотим вообще меньше кода писать, не зря используем ломбок и всякие штуки + умную idea

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +class GoalControllerTest {
давай комменты сначала поправишь в мейн пакете, а к тестам вернешься, после тех правок, если что я напишу тебе просто сюда, что теперь переключись на правку тестов

попробуем такой подход, как на дейли обсуждали, начнем просто с правки комментов после мейна, а там уже дальше поглядим, как будет всем удобнее. Возможно тесты будете допиливать после правок мейн пакета или остановимся на правке замечаний уже написанных тестов, но просто после мейн

А так смотри, как тебе удобнее, если хочешь, можешь и сразу править всё)

Ну и есть замечание в целом по тестам, существует стиль именования юнит-тестов, зависит от того, как делает команда, а примеры, тут можно посмотреть https://dzone.com/articles/7-popular-unit-test-naming
Денису тоже скидывала, можете обсудить какой-то единый подход и с командой посоветоваться
Хорошо бы визуально видеть позитивные тесты и негативные
добавить @DisplayName 
и можно @Nested например использовать для этого разделения
типо тестовый @Nested  класс позитивных тестов, и @Nested  негативных
в целом тесты не самое критичное здесь, главное со стилем определиться, чтобы все +- в команде писали единообразно

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        if (goal.getTitle().isBlank() || goal == null) {
баги в методах
вот эту часть`if (goal.getTitle().isBlank() || goal == null)`
и аналогичную в другом методе, проверь и подумай, почему у тебя неверно реализованы методы и тесты к ним, соответсвенно

также, стоит вынести вместе с ошибкой и условие в твой в приватный метод throwDataValidationExceptionWithMessage, сделай параметры просто и подкидывай нужные тебе + переименуй метод, можно просто validate, он все равно тут один и приватный

2024-05-05 20:39 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public void createGoal(Long userId, Goal goal) {
давай облегчим класс, попробуй вынести всю валидацию в отдельный класс, а в этом классе потом надо инжектить класс валидатор для целей

2024-05-14 07:29 UTC, nn1ck0 commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
Чтобы игнорить несопоставленные поля. Т.к. в дто не все поля включены, которые есть в сущности

2024-05-16 23:25 UTC, Sabina-Vishnya requested changes

2024-05-16 23:25 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        //создается с parent_id 0 и кидает ошибку из-за этого
Что значит этот коммент не пойму, это ошибка у нас или что это? Кто это сможет понять вне контекста, о какой ошибки речь идет
Такие комменты понятны только тебе, тк не несут никакой внятной и полезной информации, а лишь вводят в заблуждение, сразу вопросы возникают. 

Если хочется пояснить работу какой-то части метода, то либо код должен быть проще (так, чтобы всё было понятно без комментов), либо (если все же лишний раз хочется обратить внимание на какую-то специфическую логику), формулировать иначе нужно. Примеры джава доков можно посмотреть в доке.

Итого, коммент такой вносит неопределенности, значит следует изменить формулировку, чтобы кратко и по делу, но было понятно, что ты имеешь ввиду
или код упрощать

2024-05-16 23:25 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/goal/ValidationGoalService.java
> +    public void checkMaxActiveGoals(int count) {
Можно пару вариантов:
- попробуй методы по ООП сделать, в модель Goal какие-то простые проверки вынести, булевы методы допустим просто без бросаний ошибок, возможно тогда эта валидация будет понятнее за счет того что ты у Goal вызываешь метод
- либо проще- не тащи ты флаг в валидатор метода параметром, пусть у тебя в сервисе уже будет более читаемый метод, а в параметре тогда уже сама цель. Возможно ты так разнес, чтобы не тащить модель целую, но в валидации у тебя просто бросание ошибок и не особо говорящие проверки с названиями, это не упрощает код сервиса и не сильно дает понимание класса валидации. 

Первый метод пусть ок, но два с флагами излишне + это мог быть один метод с двумя параметрами, который при втором вызове делается инверсией и такой бы метод мог быть вполне универсальным, хотя и смысла нет.

Я бы рекомендовала раздробить на более мелкие методы updateGoal из сервиса, а эти проверки в сервис перенести, чтобы еще раз посмотреть последовательность всех операций (мб так легче будет дробить логику). 
Читаемым сделать updateGoal и понять, стоит ли выносить в валидацию или приватный метод подойдет. 

Сейчас updateGoal содержит условия, а валидатор лишь флаги, которые в зависимости от тру/фолс из параметра могут кинуть ошибки. Это еще и в два метода, хотя проверка у них очень простая, при этом предшествующая часть проверки осталась в сервисе. В чем идея этого валидатора? Логичнее и понятнее было бы целое условия из сервиса, вынести в валидацию тогда уж. Да, твои методы бы содержали больше параметров, но и проверки были бы конкретнее. Непонятна идея такой реализации. Попробуй порефачить

2024-05-16 23:25 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +
нужны ли нам эти методы все новые в репозитории? корректны ли они все? чем нам jpa не подходит?

2024-12-21 21:08 UTC, closed without merging