feature-BJS2-6302
CorporationX/user_service pull request #1010
Opened 2024-05-04 19:05 UTC by VadimShibanov

2024-05-05 07:39 UTC, NadirCianid commented
Старайся давать коммитам осознанное название

2024-05-05 07:43 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    }
Слишком глубокая вложенность проверок. Можно сильно упростить код, если инвертировать проверки

2024-05-05 07:44 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                    throw new RuntimeException("There is no such inviter or invitedUser in database");
В задании явно не сказано, но бросать нужно кастомное исключение. Например, DataValidationException, как в других заданиях

2024-05-05 07:45 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                if (userRepository.existsById(goalInvitationDto.getInviterId()) && userRepository.existsById(goalInvitationDto.getInvitedUserId())) {
слишком длинная строчка. Плохо читается. Может стоит вынести в отдельный метод?

2024-05-05 07:48 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        if (goalInvitationDto.getInviterId() != null && goalInvitationDto.getInvitedUserId() != null) {
Не уверен, насколько это возможно при работе с REST, но пока это возможно, так что напишу. Если тебе на вход метода придет  null, вылетит соответствующая ошибка. Эту ситуацию тоже следует обрабатывать по-хорошему

2024-05-05 07:59 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals("InviterId == null or InvitedUserId == null", exception.getMessage());
Тут бы еще проверить, что не происходит сохранение в бд

2024-05-05 08:01 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +    void testCreateInvitationWithInviterExists() {
В названии теста ты пишешь, что приглашающий существует, а в теле проверяешь обратную ситуацию. 

Похожие проблемы с неймингом тестов не только здесь

2024-05-05 08:04 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                    goalInvitation.setGoal(goalRepository.findById(goalInvitationDto.getGoalId()).get());
использование Optional.get() в лоб. Можно сделать проще и короче с использованием .orElseThrow() или других методов

2024-05-05 08:05 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        verify(goalInvitationRepository, times(1)).save(captor.capture());
times(1) можно не писать. Метод по дефолту это проверяет

2024-05-05 08:08 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    }
Та же проблема со вложенностью

2024-05-05 08:10 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                if (setGoals.size() < 3) {
Константы надо выносить в поля класса

2024-05-05 08:11 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +    private GoalInvitation setupForAcceptAndRejectGoalInvitationAndForGetInvitations() {
замечание больше общего характера: приватные методы лучше располагать внизу класса, а не вперемешку с публичными

2024-05-05 08:14 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                        goalInvitation.getInvited().getGoals().add(goal);
А в бд эти изменения отразятся ?

2024-05-05 08:15 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals("InviterId == null or InvitedUserId == null", exception.getMessage());
повторение текста ошибки. Может стоит вынести его в отдельный класс?

Это относится ко всем негативным тестам с исключениями

2024-05-05 08:17 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals("There is no such goal in database", exception.getMessage());
Лучше разделить блок when, вызов метода и проверку, отступами

2024-05-05 08:20 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        when(goalRepository.existsById(goalInvitation.getGoal().getId())).thenReturn(true);
В нескольких тестах есть дублирование этого или похожего блока. Посмотри в сторону вложенных тестов, чтобы во вложенном тесте проверять общую для группы тестов ситуацию. Тогда ты сможешь вынести общие строки кода в один @BeforeEach для этого вложенного теста

2024-05-05 08:21 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/GoalInvitationMapper.java
> +public interface GoalInvitationMapper {
на маппер тоже нужны тесты

2024-05-05 08:24 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                goalInvitation.setStatus(RequestStatus.REJECTED);
Опять же, нет сохранения в бд

2024-05-05 08:27 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/recommendation/GoalInvitationController.java
> +package school.faang.user_service.controller.recommendation;
Я считаю, что в задании ошибка в том месте, где указан пакет для этого класса. Даже название класса то же, что и у существующего

2024-05-05 08:28 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/goal/InvitationFilterDto.java
> +
Это лишнее

2024-05-05 08:28 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/goal/InvitationFilterDto.java
> +
Можно добавить поле с самой целью

2024-05-05 08:30 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                    toList();
посмотри видео на платформе, https://faang-school.com/courses/mbvd6kz9/63zkb48d
Там Влад показывает, как фильтры написать красиво и расширяемо через паттерн

Попробуй сделать так
Будет красивее и более расширяемо

2024-05-05 17:03 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/recommendation/GoalInvitationController.java
> +package school.faang.user_service.controller.recommendation;
ок

2024-05-05 17:07 UTC, VadimShibanov commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals("There is no such goal in database", exception.getMessage());
Не везде, но там, где много строк сделал, там где в методе всего 4 - 5 строк думаю, что лишнее

2024-05-05 17:08 UTC, VadimShibanov commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +    private GoalInvitation setupForAcceptAndRejectGoalInvitationAndForGetInvitations() {
ок

2024-05-05 17:10 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                if (setGoals.size() < 3) {
ок

2024-05-05 17:12 UTC, VadimShibanov commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        verify(goalInvitationRepository, times(1)).save(captor.capture());
ок

2024-05-05 17:20 UTC, VadimShibanov commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +    void testCreateInvitationWithInviterExists() {
ok

2024-05-05 18:05 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                    goalInvitation.setGoal(goalRepository.findById(goalInvitationDto.getGoalId()).get());
ok

2024-05-05 18:09 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        if (goalInvitationDto.getInviterId() != null && goalInvitationDto.getInvitedUserId() != null) {
ok

2024-05-05 18:10 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    }
ok

2024-05-05 18:13 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                        goalInvitation.getInvited().getGoals().add(goal);
ok

2024-05-05 18:14 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                goalInvitation.setStatus(RequestStatus.REJECTED);
ok

2024-05-05 18:15 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/dto/goal/InvitationFilterDto.java
> +
буду идти по заданию

2024-05-05 18:18 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                if (userRepository.existsById(goalInvitationDto.getInviterId()) && userRepository.existsById(goalInvitationDto.getInvitedUserId())) {
ok

2024-05-05 18:49 UTC, VadimShibanov commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals("InviterId == null or InvitedUserId == null", exception.getMessage());
ok

2024-05-05 21:15 UTC, VadimShibanov commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals("There is no such goal in database", exception.getMessage());
ok

2024-05-06 12:29 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/mapper/GoalInvitationMapper.java
> +public interface GoalInvitationMapper {
ok

2024-05-07 23:16 UTC, Sabina-Vishnya commented
Делай коммиты информативными и относящимися к задаче, первый коммит, может быть с номером таски и названием, если разделяешь на коммиты, то также пиши, что реализовал.
Последние твои коммиты понятны, а вот до изменений вообще непонятно, что было сделано, кроме номера таски, который 15 раз закоммичен и ни о чем не говорит) Желательно это поправить редактировав коммиты, с помощью идеи это сделать проще, но стоит такое тебе посмотреть и в последствии вести историю коммитов ясную. 
В большинстве команд так и ведут разработку.

2024-05-09 19:49 UTC, Sabina-Vishnya requested changes
Помимо остальных замечаний, давай валидацию выносить
У каждого слоя будет своя валидация, допустим, сейчас можно для сервиса свой класс-валидатор сделать (только обрати внимание на модификатор доступа у класса)

Также, подумай, как бы можно было бы сделать один универсальный валидатор для null и пустоты у всех сущностей, необязательно реализовывать прям сейчас, просто подумай в эту сторону, плюс можешь посмотреть, что такое аннотации собственные и в целом. 
Пока что, предлагаю обойтись лишь отдельными классами-валидаторами, в твоем случае валидатор для сервис класса. Код будет более структуриированнее и читаемее

2024-05-09 19:49 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/GoalInvitationControllerTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Давайте определимся всё же внутри команды, будем ли все таки аннотацию писать или приватить методы явно и уже придерживаться единообразия. 
Сейчас есть влитый код с явным указанием модификаторов. Предлагаю такие штуки поднимать в чатиках (что быстрее) или на дейликах (что дольше), но в идеале обсуждать прям с командой подходы. Ну и если будет решение оставлять анноташки или явно модификаторы, то можно просто отдельно потом доливать, в рамках других задач или прям заводить отдельные

2024-05-09 19:49 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        return goalInvitationRepository.findAll().stream().
нет изменений по фильтрам, тебе Денис писал об этом с ссылкой на видос

2024-05-09 19:49 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/GoalInvitationMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
для чего игнор?

2024-05-09 19:49 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +            throw new RuntimeException(INPUT_IS_NULL.getMessage());
почему везде RuntimeException? Давай своё сделаем исключение или что-то подходящее пробрасывать везде

2024-05-09 19:49 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        if (setGoals.size() > SETGOALSIZE) {
есть общепринятые рекомендации по неймингу, например: https://www.oracle.com/java/technologies/javase/codeconventions-namingconventions.html
обрати внимание на константы

2024-05-12 15:59 UTC, Sabina-Vishnya requested changes
помимо замечаний ниже еще не забудь
- про аннотацию для полей, обсудили сегодня, уходи от нее
- подтяни изменения из мастер, посмотри, что влито, что-то тебе поможет в текущей задаче
- Optional.get() везде обработай, например в GoalInvitationService ты это правило игнорируешь, так делать не стоит

2024-05-12 15:59 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/ForTests.java
> +public class ForTests {
Лучше Test...что-то, например TestUtils, TestData (TestData уже есть, можно обновить ветку и в TestData тогда закинуть твои методы, имена методов подрефачим позже, в рамках возможно будущей задачки для тестов, которую я предложила Денису сделать позже, но если захочешь можешь ты сделать, только узнай у него, что за задачка тогда

2024-05-12 15:59 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/filter/InvitedIdFilter.java
> +public class InvitedIdFilter implements InvitationFilter {
все реализации фильтра инкапсулируем, они больше нигде не используются кроме тестов, а тесты правим
посмотри уже влитый код
тебе всего лишь нужно расположить тесты каждого фильтра в те же пути, но в папку тестов, т.е. в итоге твой тест на этот фильтр должен быть по такому же пути как и сам класс (school.faang.user_service.service.filter) и вообще так правильно располагать тесты, у тебя почему-то тесты в других директориях 

и в тестах надо будет удалить моки на каждый фильтр и замокать просто список фильтров (этот `List<InvitationFilter> invitationFilters;`), в тестовой методе testGetInvitationsWithNoGoalInvitations скорее всего упадет из-за того, что не нужная мока `when(goalInvitationRepository.findAll()).thenReturn(goalInvitations);` это удалять можно, но лучше все перепроверь. Идея думаю понятна

2024-05-19 13:36 UTC, Sabina-Vishnya requested changes

2024-05-19 13:36 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                filter(filter -> filter.isApplicable(filters)).
точки лучше ставить с новой строчки
```
return invitationFilters.stream()
                .filter(filter -> filter.isApplicable(filters))
```
везде поправить нужно

2024-05-19 13:36 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        List<InvitationFilter> invitationFilters = List.of(
уверен что будет работать?

советую проверить тесты и переписать
и тебе гитхаб на конфликт ругается, обнови ветку

2024-05-26 11:24 UTC, Sabina-Vishnya reviewed
правки небольшие, можешь, если хочешь щас вливать, но надо будет поправить (заведи таску под это дело)
про @ExceptionHandler посмотри и переделай
также нет аннотаций, про это тоже есть урок

2024-05-26 11:24 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/entity/Country.java
> +@Getter
чем тебе data не угодила, которая здесь и так была?)

2024-05-26 11:24 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        goalInvitation.setInvited(userRepository.findById(goalInvitationDto.getInvitedUserId())
userRepository.findById можно в метод с двумя параметрами сделать

2024-05-26 11:24 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +
лишний отступ

2024-05-26 11:24 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/GoalInvitationServiceValidator.java
> +        if (filters == null) {
почему не аннотациями?

2024-05-29 19:18 UTC, VadimShibanov commented
ok

2024-05-29 19:29 UTC, merged