Реализовал EventService, EventController, покрыл их unit тестами.
CorporationX/user_service pull request #1017
Opened 2024-05-06 17:09 UTC by Fargus74

Реализовал EventService, EventController, покрыл их unit тестами.

2024-05-07 09:34 UTC, Demchenkov7 commented
Не нашел положительного теста на updateEvent и зачем ты прописал всю реализацию маппера? Суть MapStruct в том, чтобы самому это все не прописывать, он это сгенерирует. 
Для тестов достаточно будет прописать 
@Spy
EventMapperImpl -mapStruct его и так создает, просто тебе не показывает. Но взять для тестов ты его можешь.

2024-05-07 09:37 UTC, Demchenkov7 requested changes

2024-05-07 09:37 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public EventController(EventService eventService) {
Можно не объявлять конструктор явно. Можно дабвить @RequiredArgsConstructor. Так как дополнительной логики в конструкторе нет

2024-05-07 09:37 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    public EventService(EventRepository eventRepository, EventMapper eventMapper,
То же самое про @RequiredArgsConstructor

2024-05-07 09:37 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        if (!new HashSet<>(user.getSkills()).containsAll(event.getRelatedSkills())) {
Зачем тут создавать хэш сет?

2024-05-07 09:37 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        checkNeedSkillsForEvent(user, event);
Лучше сначала проверить, что пользователь обладает необходимыми навыками, а потом уже вызывать event.setOwner

2024-05-07 09:37 UTC, Demchenkov7 commented on src/test/java/school/faang/user_service/service/EventServiceTest.java
> +        Skill skill1 = createSkill(1, "Title1");
Прочитай про аннотация @Builder в entity, упростит создание для тестов

2024-05-07 09:37 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        event.setOwner(user); // Временная реализация добавления владельца события, при преобразовании из Dto в сущность
Опять же, мне кажется сначла надо проверить обладает ли он навыками

2024-05-07 09:37 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        if (!event.getOwner().equals(user)) {
А строчкой выше ты уже назначил его автором события

2024-05-07 09:37 UTC, Demchenkov7 commented on src/test/java/school/faang/user_service/service/EventServiceTest.java
> +    public void testEventUpdateNotOwner() {
У тебя падает тест

2024-05-10 16:41 UTC, Demchenkov7 requested changes

2024-05-10 16:41 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    private void validByTitle_StartDate_Owner(EventDto eventDto) {
Переименовать бы метод, чтобы все было в одном стиле. Можно просто обобщить типо входная валидация или входных данных...

2024-05-10 16:41 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        Event event = eventMapper.toEntity(eventDto);
Это действие лучше бы выполнить после проверки пользователя, в случае если пользователя нет, мы делаем лишнии дейсвтия по преобразованию

2024-05-10 16:41 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    public List<EventDto> getEventsByFilter(EventFilterDto filters) {
Весь метод ты по сути можешь сделать в один стрим, и не будем создавать лишние объекты, да и просто будет читабельнее

2024-05-10 16:41 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        Event event = eventMapper.toEntity(eventDto);
Тоже, можно сделать это после получение пользователя

2024-05-14 07:43 UTC, vang31 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    private void validByTitleStartDateOwner(EventDto eventDto) {
валидацию лучше вынести в отдельный класс. Контроллер должен содержать только вызовы. Лучшей практикой считается, чтобы контроллеры не имели никакой логики. Но бывает когда никак нельзя вынести, то можно оставить.(Например, когда delete возвращает 204 когда уже удалили контент, или, 404 если ничего не нашли)

2024-05-14 07:43 UTC, vang31 commented on src/test/java/school/faang/user_service/controller/EventControllerTest.java
> +        user.setId(1L);
id тоже можно занести в Before

2024-05-14 07:43 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        if (!new HashSet<>(user.getSkills()).containsAll(event.getRelatedSkills())) {
"Это Idea подсказала, без него якобы производительность метода маленькая" ответ от Алексея

2024-05-14 20:37 UTC, vang31 reviewed
Добавьте тесты на фильтры, стоит учесть в тестах успешное выполнение фильтра и обратный этому случаю.

2024-05-14 20:37 UTC, vang31 commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private List<SkillDto> relatedSkills;
можно передать список айдишников, тогда джсонн будет короче. список навыков мы сможем получить по повторном запросе с фронта, с айди события, чтобы отбразить их на UI.

2024-05-14 20:37 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .map(eventMapper::toDto)
Лучше сделать method overloading в MappereStruct. List toDto(List); Не надо будет использовать stream быстрее и короче. Сразу List нужного типа возращается

2024-05-14 20:37 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        if (!event.getOwner().equals(user)) {
лучше будет вынести в отдельный класс валидатора, так будет чище код

2024-05-14 20:37 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private void checkNeedSkillsForEvent(User user, Event event) {
тоже выноси в отдельный класс.

2024-05-17 09:35 UTC, merged