BJS2-6255 Запрос рекомендаций
CorporationX/user_service pull request #1021
Opened 2024-05-07 17:44 UTC by RickHammerson

Пока без тестов
https://faang-school.atlassian.net/browse/BJS2-6255?atlOrigin=eyJpIjoiMWFjOWFhMzU4NjcwNGRiMGIwMGVhYzY5Yjc5ZWI4NmYiLCJwIjoiaiJ9

2024-05-08 07:54 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    private RecommendationRequestService recommendationRequestService;
Данное поле не попадает в конструктор. Обычно такие поля делают финальными, насколько я знаю

2024-05-08 07:57 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private List<SkillRequest> skills;
Я считаю, что SkillRequest не очень подходит для dto. Здесь скорее нужно из каждого такого объекта достать конкретный скилл

2024-05-08 08:01 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            throw new DataValidationException("Recommendation request message is empty");
Стоит вынести текст сообщения об ошибки в enum, для лучшей расширяемости

2024-05-08 08:04 UTC, NadirCianid commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +public class RecommendationRequestValidator {
Не лучше ли инкапсулировать логику валидатора? Он ведь используется только в одном классе. Также эта валидация скорее похожа на валидацию контроллера, а не сервиса.

2024-05-08 08:05 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        }
Зачем создавать одноразовые переменные boolean? Выражение и так довольно читаемое

2024-05-08 08:07 UTC, RickHammerson commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    private RecommendationRequestService recommendationRequestService;
Точн,спасибо

2024-05-08 08:08 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        );
Не лучше маппинг в id скиллов сделать при объявлении переменной skills? В таком виде немного падает читаемость.

2024-05-08 08:09 UTC, RickHammerson commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private List<SkillRequest> skills;
Я так понял, что можно несколько скиллов сразу рекомендовать. Но вынуть можно, ок

2024-05-08 08:09 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        RecommendationRequest savedRequest = recommendationRequestRepository.save(mapper.fromDto(recommendationRequest));
Может стоит вынести все проверки выше в отдельный метод валидации?

2024-05-08 08:14 UTC, RickHammerson commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private List<SkillRequest> skills;
Хотя,там для репозитория скиллов требуются SkillRequests 
![image](https://github.com/CorporationX/user_service/assets/42961541/63ff3c38-0d4b-4e7d-ba5d-d462c35559af)
 skillRequestRepository.saveAll( тута );

2024-05-08 08:34 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    }
Так как мы проходимся по списку фильтров, то они независимо друг от друга обрабатывают один и тот же стрим. А стрим можно обрабатывать только единожды. Поэтому лучше фильтровать списки. И после фильтрации, надо будет применить distinct().

2024-05-08 08:36 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/filter/RecommendationRequestCreatedAtFilter.java
> +public class RecommendationRequestCreatedAtFilter implements RecommendationRequestFilterInterface {
Сабина рекомендовала мне и я рекомендую вам. В данном случае фильтры нет смысла делать публичными, так как напрямую их некто не использует. Только лишь через список RecommendationRequestFilterInterface. В данном случае их будет разумно инкапсулировать.

2024-05-08 08:37 UTC, RickHammerson commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            throw new DataValidationException("Recommendation request message is empty");
Поправил в местах, где выбрасываются ошибки по запросу рекомендаций. Ошибки не найденных пользователей и т.д возьму позже из ПРов ребят с других задач

2024-05-08 08:39 UTC, RickHammerson commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +public class RecommendationRequestValidator {
Да,используется в одном классе, но будет расширяться для обновления запроса рекомендации. Или нет
На всякий случай сделаю его бином и внедрю как зависимость. Будет легче тестами покрыть

2024-05-08 08:40 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        }
Привык, чтобы в ifах было как можно более читаемое, без вызова цепочек методов. Регулирую читаемость названием переменной
Переделаю

2024-05-08 08:41 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        );
Да, ты прав. Валидацию сделал в начале метода, так что там точно не будет NPE

2024-05-08 08:42 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    }
Так как мы проходимся по списку фильтров, то они независимо друг от друга обрабатывают один и тот же стрим. А стрим можно обрабатывать только единожды. Поэтому лучше фильтровать списки. И после фильтрации, надо будет применить distinct().

2024-05-08 08:44 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        RecommendationRequest savedRequest = recommendationRequestRepository.save(mapper.fromDto(recommendationRequest));
Не получится именно эту проверку вынести
В валидации проверяю, что запросы на скилллы пришли не пустые. Потом проверяю, что каждый из них есть в базе, только потом надо проверить, что количество существующих совпадает с количеством пришедших в сервис

2024-05-08 10:25 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    }
Исправил на list

2024-05-08 11:54 UTC, RickHammerson commented on src/main/java/school/faang/user_service/dto/filter/RecommendationRequestCreatedAtFilter.java
> +public class RecommendationRequestCreatedAtFilter implements RecommendationRequestFilterInterface {
Сделал

2024-05-10 16:11 UTC, Sabina-Vishnya requested changes
также, твой RecommendationRequestService может содержать больше проверок, из сервиса прям есть проверки, которые можно вынести. 

еще необязательно к выполнению сейчас, но подумай в сторону общего валидатора для null и пустоты
есть еще вариант через этот общий валидатор пропускать аннотации, существующие и кастомные, тоже поразмышляй об этом, вдруг ты позже поймешь, что будет лучше такую штуку сделать

2024-05-10 16:11 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
для чего игнор?

2024-05-10 16:11 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        if (!userRepository.existsById(requesterId)) {
userRepository.existsById и ошибка - это дублирование.
- Подобные методы из других репозиториев, могут быть сервисами и иметь свои валидаторы, также как у тебя RecommendationRequestService. Тогда ты вызываешь сервисы нужные, а в них уже проверки есть. Тут можно сделать, например, UserService который будет содержать вызов этого булевского метода, проверяющего какой-то id и кидать ошибку, только сам текст ошибки лучше в енамчик, как у тебя это сделано с RecommendationRequestExceptions, только для юзера свой, тогда ты просто вызываешь метод тут. Также можно поступить и с другими репозиториями
- Либо выносить в приватный метод тут, чтобы хоть немного разделить логику и читаемость лучше сделать. Тогда ты просто выносишь в приватный булевский метод `!userRepository.existsById`и переиспользуешь его, подставляя нужный айди.
я бы исходила из того, что эти методы других репозиториев делают и тогда уже определяла им место, но пока предлагаю остановиться на приватных методах в этом классе

2024-05-10 16:11 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +            if (request.getCreatedAt().plusMonths(6).isAfter(LocalDateTime.now())) {
6 - магическое число какое-то выходит, а это ведь константа, так давай вынесем в константу

2024-05-10 16:11 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        if (StringUtils.isEmpty(recommendationRequest.getMessage())) {
isBlank не подойдет? проверка шире или нам пробелы можно?

2024-05-10 16:11 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        if (StringUtils.isEmpty(rejection.getReason())) {
эта проверка и выше, почти идентичны, могут быть одним методом с параметрами

2024-05-10 21:02 UTC, RickHammerson commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
Он при запуске приложения в логи пишет WARN левелом,что некоторые поля не замаплены. Не хочу, чтобы он нервировал кого-то. Я и сам могу нарочно сделать такую логику, чтобы некоторые поля не мапились
Так что решил поставить игнор

2024-05-10 21:11 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +            if (request.getCreatedAt().plusMonths(6).isAfter(LocalDateTime.now())) {
Ок

2024-05-10 21:15 UTC, RickHammerson commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        if (StringUtils.isEmpty(recommendationRequest.getMessage())) {
да, ты права, лучше подойдет blank

2024-05-10 21:19 UTC, RickHammerson commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        if (StringUtils.isEmpty(rejection.getReason())) {
Тоже об этом подумал, но текст сообщения ошибки должен быть разный
В одной ошибке message - сообщение к реквесту ,в другой reason - причина отклонения

2024-05-11 08:17 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        if (!userRepository.existsById(requesterId)) {
Да,я понимаю, что можно сделать UserService и так далее, но смысл, если он потом перетрется имплементацией из какого-то другого PRа? 
Выше писал Денису, что заменю позже кастомные сообщения ошибок, когда другие реализуют свои задачи. То же самое сделаю с юзер сервисом

2024-05-11 11:01 UTC, RickHammerson commented
> также, твой RecommendationRequestService может содержать больше проверок, из сервиса прям есть проверки, которые можно вынести.
> 
> еще необязательно к выполнению сейчас, но подумай в сторону общего валидатора для null и пустоты есть еще вариант через этот общий валидатор пропускать аннотации, существующие и кастомные, тоже поразмышляй об этом, вдруг ты позже решишь, что будет лучше такую штуку сделать, хоть это тогда может поменять текущий подход к валидации немного

Не до конца понимаю,что имеешь в виду. Можем обсудить на ретро в воскресенье

2024-05-11 15:17 UTC, Sabina-Vishnya commented
хе-хе, валидация могла бы быть короче за счет того, что у тебя лонг в некоторых местах проверяет и это можно было бы тоже обобщить, ну так норм)
про кастомные ошибки и сервисы поняла, но лучше бы тудуху повесить и таску завести, а то так и не догадаться, что ты уже об этом подумал) а так норм, давай вливать тогда)

2024-05-11 15:17 UTC, Sabina-Vishnya approved these changes

2024-05-11 15:33 UTC, Sabina-Vishnya commented
А про валидатор не ответила. В общем, можно сделать валидатор с параметром Object и его проверять, также и массив объектов. Проверка на null и какие-то еще добавить. Чтобы каждый раз не писать эту проверку везде - использовать общую из-за того, что валидатор сделали такой.
Или более возможно сложнее в понимании вариант, все тот же валидатор на объект и использовать класс Validator (как бин) и ConstraintViolation (из jakarta уже кажется) в этом валидаторе.
В итоге, будет валидатор проверящий объект на null и множество ConstraintViolation для объектов, которые обращаются к методу validate(object из параметра). Затем условие, если констрэинты не пусты, то собрать их в строку и кинуть ошибку. 
Погугли, я думаю в инете об этом найдешь информацию. Тут просто идея, что если мы создаем свои кастомные аннотации, можем вешать их где нам надо и их может быть много, а пропускаем через этот валидатор общий и тогда в случае ошибки, мы увидем сообщение из аннотации, а если ошибка не одна, то в этом множестве соберем не одну ошибку, довольно гибко выходит, если организовать верно. 
Так вообще можно еще придумать что-то и сделать более общим, это уже на вкус и цвет. Тут суть, чтобы каждому не писать одни и те же проверки обязательные, а делать более общие

2024-05-12 15:05 UTC, Sabina-Vishnya commented
верну тебе в туду, чтобы про тесты не забыть

2024-05-31 05:51 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/filter/RecommendationRequestStatusFilter.java
> +package school.faang.user_service.dto.filter;
дто фильтров стоит класть в подпакет рекомендаций

2024-05-31 05:52 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/filter/RecommendationRequestStatusFilter.java
> +package school.faang.user_service.dto.filter;
А это и не дто фильтров, а сами фильтры...

Их вообще здесь не должно быть

2024-05-31 05:53 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private List<SkillRequestDto> skills;
Здесь лучше подходит аннотация @NotEmpty

2024-05-31 06:02 UTC, NadirCianid commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +        verifyUserExists(receiverId);
Ты здесь делаешь запросы в бд для проверки существования пользователей, несмотря на то, что позже ты будешь делать запросы на получение пользователей, в которых уже эти проверки есть.

2024-05-31 06:06 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        List<SkillRequest> skillRequests = convertSkillsToSkillsRequest(dto.getSkills(),recommendationRequest);
Разве маппер не должен конвертировать  List<SkillRequestDto> в List<SkillRequest> ?

2024-05-31 06:09 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    //TODO: Использовать классы-сервисы для получени юзеров, скиллов и т.д
Обсудить с Сабиной это. В моем коде ей такое почему-то не понравилось ("Почему у тебя сервис возвращает в одних методах дто, а в других сущности"), хотя сама идея мне нравится

2024-05-31 06:09 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    private User findUserById(Long userId) {
приватные методы должны быть после публичных

2024-05-31 06:09 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        return userRepository.findById(userId).orElseThrow(
.orElseThrow можно с новой строки писать

2024-05-31 06:11 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestFilter.java
> +public class RecommendationRequestFilter {
Мне кажется лучше дописать в название Dto, а в интерфейсе убрать слово Interface из названия

2024-05-31 06:12 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestFilter.java
> +    private Long receiverId;
На эти поля можно повесить @Positive

2024-05-31 06:13 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/recommendation/RejectionDto.java
> +    private String reason;
Здесь не нужна валидация?

2024-05-31 06:15 UTC, NadirCianid commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +            throw new RecommendationRequestRejectionException(REJECT_REQUEST_STATUS_NOT_VALID.getMessage());
Не похоже на валидацию

2024-05-31 06:18 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private RecommendationRequestDto dto = null;
Зачем пустые строки?

2024-05-31 06:18 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private SkillRepository skillRepository;
Неиспользуемые поля

2024-05-31 06:19 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private List<RecommendationRequestFilterInterface> filters;
Тоже неиспользуемое поле. Зачем?)

2024-05-31 06:20 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private Long id = 5L;
может стоить дать более говорящее название. Например, recommendationRequestId?

2024-05-31 06:20 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        rejectionDto.setReason("Reject");
Такое лучше вынести в отдельный класс с подготовкой тестовых данных. Они тебе пригодятся и в других тестах

2024-05-31 06:22 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        void shouldCreateRecommendationRequest() {
Обсудили вчера нэйминг тестов. Мне больше нравится с @DisplayName (название тогда можно подлиннее )

2024-05-31 06:23 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +
Разделяй пожалуйста код теста на три логические части пустыми строками:
1. //before
2. //when
3. //then (ассерты и прочие проверки)

2024-05-31 06:23 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +            verify(mapper, times(1)).toDto(saved);
times(1) не имеет смысла писать. Это и так значение по умолчанию

2024-05-31 06:28 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    }
лучше сохранять логическую структуру теста, как описал в предыдущем комменте, тем более, что таким образом написанный тест падает (очень больно)

2024-05-31 06:31 UTC, NadirCianid commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +            );
Здесь и ниже надо проверить, что в базу при ошибке метод не сходил

2024-05-31 06:32 UTC, NadirCianid requested changes
Все, кроме тестов в целом норм. Проблем не вижу. 

А по тестам комментарии я оставил, а также не забудь добавить тесты на мапперы, валидацию дто и на твой валидатор

2024-05-31 07:45 UTC, NadirCianid approved these changes

2024-05-31 10:13 UTC, RickHammerson commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +        verifyUserExists(receiverId);
Есть случай, когда проверки валидации пройдут, пользователи будут в системе, потом пользователей удалят, и мне будет не к кому привязывать запрос

2024-05-31 10:15 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        List<SkillRequest> skillRequests = convertSkillsToSkillsRequest(dto.getSkills(),recommendationRequest);
Не совсем понял про что ты. Тут же и так List<SkillRequestDto> мапится на List<SkillRequest>

2024-05-31 10:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    //TODO: Использовать классы-сервисы для получени юзеров, скиллов и т.д
Тут я использую private методы для логики, используемой только в сервисе. Никуда она больше не идёт. Так что это разумное решение за неимением сервисов, которые могут возвращать сущности
+,если я буду возвращать DTO из него, мне придется обращаться ещё раз, чтобы получить сущность по Id этой DTO

2024-05-31 10:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    private User findUserById(Long userId) {
да, ты прав

2024-05-31 10:19 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        return userRepository.findById(userId).orElseThrow(
Такой подход немного дергает глаз на новую строчку, что лично мне неудобно)
![image](https://github.com/CorporationX/user_service/assets/42961541/9b491061-dddc-4ab2-b7cd-a8fec71876fd)

2024-05-31 10:21 UTC, RickHammerson commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestFilter.java
> +public class RecommendationRequestFilter {
ты прав

2024-05-31 10:22 UTC, RickHammerson commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestFilter.java
> +    private Long receiverId;
Ты прав

2024-05-31 10:22 UTC, RickHammerson commented on src/main/java/school/faang/user_service/dto/recommendation/RejectionDto.java
> +    private String reason;
Использовал валидацию в контроллере, исправлю на аннотации

2024-05-31 10:25 UTC, RickHammerson commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +            throw new RecommendationRequestRejectionException(REJECT_REQUEST_STATUS_NOT_VALID.getMessage());
Почему?

2024-05-31 10:25 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private RecommendationRequestDto dto = null;
Баловался с тестами, остались)

2024-05-31 10:26 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private SkillRepository skillRepository;
Тесты пропустил, позже допишу их

2024-05-31 10:26 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private Long id = 5L;
Йес йес

2024-05-31 10:27 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        rejectionDto.setReason("Reject");
Тесты буду писать позже, когда разберусь с другими задачами)

2024-05-31 10:32 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        void shouldCreateRecommendationRequest() {
Тесты буду писать позже, когда разберусь с другими задачами)

2024-05-31 10:33 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +
Тесты буду писать позже, когда разберусь с другими задачами)

2024-05-31 10:33 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +            verify(mapper, times(1)).toDto(saved);
Понял

2024-05-31 10:33 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    }
Ок

2024-05-31 10:33 UTC, RickHammerson commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +            );
Ок

2024-06-01 17:01 UTC, Sabina-Vishnya commented
верну тебе, чтобы не болталось на ревью)
хоть и аппрувнуто, но раз пока ты не вливал, пусть тогда на доске будет видно, как в inProgress, а когда вольешь в done кинешь уже

2024-06-03 18:19 UTC, merged