Feature bjs2 6288
CorporationX/user_service pull request #1025
Opened 2024-05-07 21:07 UTC by Sinzi-world

Реализовал первую задачу

2024-05-08 09:08 UTC, Demchenkov7 commented
Не надо делать все тесты во вложенных классах одного класса. Каждый тест должен быть в отдельном классе и путь до них должен быть как путь до класса, который ты проверяешь. Например пусть до теста сервиса должен быть /service/EventParticipationService. Т.е. создаешь дериктории как для обычных классов

2024-05-08 09:13 UTC, Demchenkov7 requested changes

2024-05-08 09:13 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/controller/Sdv.java
> +public class Sdv {
Удаляй лишний классы

2024-05-08 09:13 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    private Long user_id;
Зачем тебе тут user_id, если выше есть поле id. и используй camelCase  в названии переменных. т.е. userId

2024-05-08 09:13 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @Autowired
Не обязательно указывать явно конструктор, можно указать @RequiredArgsConstructor в классе и спринг сам создать конструктор и свяжет

2024-05-08 09:13 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/Scv.java
> +public class Scv {
Опять пустой класс

2024-05-08 09:13 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public List<User> getAllParticipantsByEventId(long eventId) {
Пользователю мы всегда возвращаем Dto любой сущьности, не надо выдавать пользователю всю информацию. Создай заглушку для маппера

2024-05-08 09:13 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/entity/User.java
> +    @Column(name = "event_id")
Не думаю, что стоит изменять готовые сущьности, так как они связаны с бд. И какой смысл несет user_id и eventId, Id ивента ты можешь получить у ивента, достав его из бд

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +}
Ты пробовал тестить через postman? У тебя просто в endpoint входят значения, но ты их никак не ловишь.

Пример как должно быть:

@PostMapping("/register/{userId}/{userId}")
public UserDto registerParticipant(@PathVariable long eventId, @PathVariable long userId) {
return eventParticipationService.registerParticipant(eventId, userId);
}

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +
У тебя нету никакой входной валидации. Без валидации мы не можем предсказать ход работы программы, так как мы можем от пользователя получить самые неожиданные данные

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public UserDto registerParticipant(long eventId, long userId) {
Мы должны принимать большой long (Long). Так как у нас может быть ситуация, что к нам приходит некорректный id. 

Абстрактный пример: 
Пользователь захотел удалить запись. Но id записи был некорректен и мы получили long = 0. Валидацию по такому значению не сделать, так как в бд может быть объект, который имеет id = 0 => мы удалим не тот объект. Нам нужен Long. Так как в случае ошибки он нам даст null, а в бд есть ограничение на поле id, что значения в нем не могут быть null. И тогда мы просто делаем валидацию на id == null и exception.

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        }
Я бы вынес проверку пользователя в отдельный private метод. Поднимет читаемость

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public UserDto registerParticipant(long eventId, long userId) {
На метод можно повесить @Transactional. 
1) Защита от многопоточности
2) Почитай, упрощает работу с бд

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +public class UserDto {
Добавь @Builder. Поможет удобнее писать тесты

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +}
Хотя есть еще лучше вариант. Используй @RequestBody и передавай все в dto. У тебя все поля для этого есть и тогда можно будет оставить такого типа: @PostMapping("/register")

2024-05-20 17:29 UTC, Kayfral commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    private Long user_id;
User_id - излишне. У тебя обычный id ответственнен за это

2024-05-20 17:29 UTC, Kayfral commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        user.setEmail("test@example.com");
Повторяющийся код можно вынести в блок:  
@BeforeEach
public void setUp(){} 

и при помощи builder заполнить данные (Висит на dto)

2024-05-20 17:29 UTC, Kayfral commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        assertEquals(expectedCount, actualCount);
Нужно избавляться от комментариев

2024-05-20 17:42 UTC, Kayfral commented
Не помню, забыл возможно написать. Не забудь про тесты Controller

2024-06-03 12:31 UTC, Kayfral approved these changes

2024-06-05 15:13 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
выноси в юзер сервис
обновись с ветки. кто-то уже выносил такое

2024-06-05 15:13 UTC, vang31 commented on src/test/java/school/faang/user_service/controller/event/EventParticipationControllerTest.java
> +public class EventParticipationControllerTest {
а остальные методы тестами не будем дергать. 
Добавляй тесты на негативные тоже. 
Тип если клиента нет. кого будем обновлять или удалять

2024-06-06 19:30 UTC, vang31 reviewed
Давай добавим валидатор, вынесем всё необходимое туда, также посмотри задачу https://faang-school.atlassian.net/browse/BJS2-6721
И сразу посмотрим куда мы можем прицепить валидатор

2024-06-06 19:30 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +            if (user.getId() == userId) {
вынести в валидатор

2024-06-06 19:30 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
Создать юзераСервис. и положить в него этот метод!

2024-06-06 19:30 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User not found"));
и потом дергать это не из репозитория, так как сервис участников, тут для репозитория пользователя не место) Каждый слой должен содержать методы, своего вида.

2024-06-06 19:30 UTC, vang31 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        if (!isRegistered) {
Вынести в класс валидатора. и потом заинжектить валидатор сюда, и чекать.

2024-07-01 19:08 UTC, merged