Phoenix bc4 feature bjs2 6264
CorporationX/user_service pull request #1027
Opened 2024-05-08 17:17 UTC by Murzin34

2024-06-09 12:59 UTC, Sabina-Vishnya requested changes
вернула, в звонке обсудили, что нужно, как поправишь, сразу кидай на меня

2024-06-09 12:59 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    // Утилитный private метод
такой коммент излишний тут

2024-06-09 12:59 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    @Transactional(readOnly = true)
на дейли обсудили, правим

2024-06-09 13:12 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    // Утилитный private метод
Убрал лишний коммент.

2024-06-09 13:12 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    @Transactional(readOnly = true)
Поставил @Transactional на методах deleteMentee и deleteMentor.

2024-06-09 13:55 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    public void deleteMentee(Long menteeId, Long mentorId) {
кстати, а почему не используешь методы jpa/crud для удаления? так по условию сказано? 
проверки на null для входных параметров тоже отсутствуют в контроллерах и сервисах
ты проверял локально ?

2024-06-09 14:10 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    public void deleteMentee(Long menteeId, Long mentorId) {
Вот моя изначальная реализация delete методов (кстати @Transactional там стояли: ))(https://github.com/CorporationX/user_service/pull/1027/commits/1ec7d35cdfce20d5811138a4841d14a9940f7d88)
 @Transactional
    public void deleteMentee(long mentorId, long menteeId) {
        User user = getUserById(mentorId);
        user.getMentees().removeIf(mentee -> mentee.getId() == menteeId);
    }

    @Transactional
    public void deleteMentor(long menteeId, long mentorId) {
        User user = getUserById(menteeId);
        user.getMentors().removeIf(mentor -> mentor.getId() == mentorId);
    }
Однако у меня не срабатывали тесты, я ошибочно решил что проблема именно в .removeIf и нашел реализацию удаления без его использования (и на всякий случай без использования .remove). Потом уже понял что тесты не срабатывали из-за очередности вызова в "@BeforeAll", но реализацию delete методов решил оставить.

2024-06-11 20:00 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    public void deleteMentee(Long menteeId, Long mentorId) {
верни делиты, они тебе тут подходят и код чище будет

2024-06-12 15:25 UTC, Sabina-Vishnya approved these changes
ок, вливай
на заметку:
для тестов писать times(1) для верифая необязательно, дефолтно и так один раз у метода
и ребята свои исключения кастомные делали, в мастере посмотри 
можно править или не править, смотри сам, но просто имей ввиду

2024-06-13 04:13 UTC, merged