Создание и настройка скиллов
CorporationX/user_service pull request #1052
Opened 2024-05-12 12:40 UTC by AlexHor230

2024-05-18 08:21 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    }
У тебя дублируются эндпоинты. К тому же ты не прописал их в принципе. Для каждого первым словом должен быть "/skill" и уже для конкретных методов нужно добавлять при необходимости idшники или доп. слова.

2024-05-18 08:21 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +        return skillService.create(skillDto);
Перед вызовом метода сервиса необходимо провести валидацию dto.

2024-05-18 08:22 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    }
Также ты не добавил аннотации к параметрам метода (@RequestBody, @PathVariable, например)

2024-05-18 08:25 UTC, NadirCianid commented on src/main/java/school/faang/user_service/exception/ExceptionMessage.java
> +    SKILL_ALREADY_EXIST("This skill already added");
небольшие грамматические ошибки. Проверь в переводчике правильный перевод на английский.

2024-05-18 08:26 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/SkillCandidateMapper.java
> +}
Ты уверен, что это будет работать?

2024-05-18 08:27 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/SkillCandidateMapper.java
> +}
Мало того, что у Skill & SkillCandidateDto нет полей с одинаковым названием, так ты еще и передал offersAmount, который маппер не сможет использовать в текущей реализации.

2024-05-18 08:29 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +}
Можно написать проще и без создания resultList.

2024-05-18 08:30 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +}
Методы стрима лучше переносить на новую строку, даже если они такие короткие.

2024-05-18 08:32 UTC, NadirCianid commented on src/main/java/school/faang/user_service/exception/DataValidationExeption.java
> +public class DataValidationExeption extends RuntimeException {
Ошибка в названии класса. Должно быть DataValidationException

2024-05-18 08:38 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        skillValidate.validateSkill(skillDto);
Странные названия. Оба метода проверяют название скилла. Но по факту первый validateSkillTitle вообще должен вызываться в контроллере.
А еще лучше повесить аннотации на dto. Почитай статьи, которые Радмир кидал в чат.

2024-05-18 08:39 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        List<Skill> skills = skillRepository.findAllByUserId(userId);
Зачем создавать для этого локальную переменную?

2024-05-18 08:40 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .map(skillMapper::skillToDto)
проще использовать метод маппера для работы со списками сущностей.

2024-05-18 08:40 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .stream()
.stream() не переносится на новую строку

2024-05-18 08:45 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .stream()
Я бы разбил эту цепочку на две операции, но это вкусовщина. Просто в таком виде хуже читается

2024-05-18 08:46 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .orElseThrow(() -> new ValidationException("The user already has the skill"));
Почему не используешь константы сообщений об ошибках ,если создал для этого класс?

2024-05-18 08:47 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .orElseThrow(() -> new ValidationException("The user already has the skill"));
И мне кажется, что  в данном случае Optional будет пустым, если у данного пользователя не будет данного скилла, а не то, что ты написал

2024-05-18 08:49 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        for (SkillOffer skillOffer : allOffersOfSkill) {
Лучше все писать через стримы, если начал их использовать

2024-05-18 08:50 UTC, NadirCianid commented on src/main/java/school/faang/user_service/validation/skill/SkillValidator.java
> +}
Методы не используются. Зачем оны нужны?

2024-05-18 08:51 UTC, NadirCianid commented on src/main/java/school/faang/user_service/validation/skill/SkillValidator.java
> +        }
Почему здесь текст исключений на русском, а везде на английском?

2024-05-18 09:03 UTC, NadirCianid requested changes
Настрой правильно эндпоинты в контроллере и перенеси валидацию дто в контроллер. 
+ провреь маппинг в SkillCandidateDto
+ исправь mergre confilcts

2024-06-12 17:07 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +@Controller
Лучше писать @RestController

2024-06-12 17:08 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +
Ненужная пустая строка

2024-06-12 17:10 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +        skillValidator.validateSkillTitle(skillDto);
По-хорошему пора уже использовать валидацию через аннотации по максимуму. Но ты здесь можешь не менять, если работает и так, чтобы уже закончить задачу. А вообще в будущем старайся все ,что можешь выносить в аннотации (имею в виду валидацию)

2024-06-12 17:11 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    @GetMapping ("/user/{userId}")
Мы договорились использовать существительные в эндпоинтах в множественном числе

2024-06-12 17:12 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    public List<SkillDto> getUserSkills(@PathVariable("userId") long userId) {
Можно не указывать имя переменной в аннотации, если параметр метода имеет такое же название

2024-06-12 17:13 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    @GetMapping ("/offered/user/{userId}")
Я считаю, что не лучшая идея для нейминга эндпоинта.

Лучше было бы оставить /users/{userId}, но добавить параметр isOffered = true, или вообще использовать фильтрацию через filterDto (но пока лучше через @RequestParam)

2024-06-12 17:14 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    @GetMapping ("/offered/user/{userId}")
+ ты так объединишь два метода в один

2024-06-12 17:18 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    @PostMapping
А, какой эндпоинт у данного метода будет? 

Ты же не указал ничего. Значит просто "/". Так не должно быть.

В твоем случае для всех методов целесообразно использовать для всех методов корнем пути "skills", а уже для конкретного метода уточнять путь.

Например: /skills/users/{userId}

2024-06-12 17:25 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +                : Collections.emptyList();
Лично мне не нравится то, как это выглядит сейчас. 
Я бы сделал так:
```
    default List<Long> convertUsersToIds (List<User> users) {
        if(users == null) {
            return List.of();
        }
        
        return users.stream()
                .map(User::getId)
                .toList();
    }
```

Но это скорее вкусовщина

2024-06-12 17:26 UTC, NadirCianid commented on src/main/java/school/faang/user_service/repository/CountryRepository.java
> +public interface  CountryRepository extends CrudRepository<Country, Long> {
Зачем?)

2024-06-12 17:26 UTC, NadirCianid commented on src/main/java/school/faang/user_service/repository/CountryRepository.java
> +public interface  CountryRepository extends CrudRepository<Country, Long> {
Зачем добавил пробел*

2024-06-12 17:27 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +    private final SkillValidator skillValidate;
Не принято называть объекты глаголами

2024-06-12 17:43 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +                .toList();
мне кажется можно было сделать проще:
```
Map<Skill, Long> skillCountMap = skillsOfferedToUser.stream()
                .collect(Collectors.groupingBy(Function.identity(), Collectors.counting()));

        return skillCountMap.entrySet().stream()
                .map(entry -> SkillCandidateDto.builder()
                        .skillDto(skillMapper.skillToDto(entry.getKey()))
                        .offersAmount(entry.getValue())
                        .build())
                .toList();
                
               ```

2024-06-12 17:44 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +
Пустая строка

2024-06-12 17:46 UTC, NadirCianid commented on src/main/java/school/faang/user_service/validation/skill/SkillValidator.java
> +
пустая строка

2024-06-12 17:47 UTC, NadirCianid commented on src/main/java/school/faang/user_service/validation/skill/SkillValidator.java
> +    }
Желательно обращения к репозиторию делать в сервисе

2024-06-12 17:48 UTC, NadirCianid requested changes
по мелочи есть замечания. В целом норм

2024-06-17 22:27 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +public class SkillController {
Ты забыл аннотацию @RequestMapping("skills/")

2024-06-17 22:36 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +                .orElseThrow(() -> new ValidationException(ExceptionMessage.USER_SKILL_NOT_FOUND.getMessage()));
Сначала ты проверяешь существование скила в валидации, а потом еще раз достаешь эту сущность и пишешь обработчик для случая отсутствия скила.

Первое - лишнее

2024-06-17 22:40 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +        skillValidator.validateSkillTitle(skillDto);
Валидатор убрал, но аннотации в дто не добавил. Так не пойдет

2024-06-17 22:43 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +}
Ты уверен, что здесь этот эндпоинт уместен?

2024-06-17 22:43 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +}
+ ты указал в параметрах @PathVariable (даже два), но в самом эндпоинте их нет

2024-06-17 22:44 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    }
+ Та же проблема ,что и ниже с параметрами

2024-06-17 22:45 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    @PostMapping("/create")
Глаголы в эндпоинтах не используем

2024-06-17 22:46 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +    private static final int MIN_SKILL_OFFERS = 3;
Константы вверху списка полей пишем

2024-06-17 22:47 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +            throw new DataValidationException("Skill with title: " + skillDto.getTitle() + " already exists.");
На будущее: есть метод String.format(). С ним удобнее делать подстановки в строку. Посмотри на примеры его использования и поймешь , о чем я

2024-06-17 22:49 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        }
.orElseThrow сюда так и просится

2024-06-17 22:54 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        return skillMapper.skillToDto(skillRepository.save(skillEntity));
В маппере ты проигнорил поле users (это правильно), но здесь забыл заполнить это поле

2024-06-17 22:57 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
>          Optional<User> user = userRepository.findById(userId);
На будущее: советую из сервиса скиллов ходить в репозиторий только скиллов (по возможности). 

В данном случае можно было бы вызвать метод UserService.getUserModel(userId) (если его нет, добавить). Но сейчас можешь не менять это

2024-06-17 22:58 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
>          }
А вот это лучше поменять. 

.orElseThrow() стоит использовать в таких случаях

2024-06-17 23:00 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
>          List<Skill> ownerSkillsList = skillRepository.findAllByUserId(userId);
А вообще, по моим познаниям"" в SQL тебе бы здесь просто вернулся пустой список, если такого пользователя не существует

2024-06-17 23:01 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +
пустая строка здесь не нужна

2024-06-17 23:04 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        Skill skillUser = skillRepository.findUserSkill(skillId, userId)
странное название

2024-06-17 23:08 UTC, NadirCianid reviewed
по мелочи есть замечания. В целом норм

2024-06-17 23:08 UTC, NadirCianid approved these changes

2024-06-17 23:10 UTC, NadirCianid reviewed
- Исправь контроллер 
- Убери лишнюю валидацию
- Добавь заполнение пользователями в сущность скилла при создании
- И мб что-то еще из того, что я написал

2024-06-18 12:14 UTC, AlexHor230 commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        return skillMapper.skillToDto(skillRepository.save(skillEntity));
Можешь прояснить пожалуйста, насколько я понял из задания _"Этот метод должен проверять, что в базе данных не существует навыка с таким названием, и если это так, создавать новую записать в бд."_  Т.е. он создается без привязки к пользователю

2024-06-18 13:09 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        return skillMapper.skillToDto(skillRepository.save(skillEntity));
В целом, да , ты прав
В данном контексте, заполнять не обязательно

2024-06-18 18:11 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    {
Скобку зря перенес

2024-06-18 18:12 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    @PostMapping("/addSkill")
Глаголы в эндпоинте не пишем

2024-06-18 18:13 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +    @PostMapping ("/offered/{userId}/{skillId}")
skillId лучше поставить в начало строки, чтобы эндпоинт был в итоге:
/skills/{skillId}/offered/{userId}

2024-06-18 18:16 UTC, NadirCianid approved these changes

2024-06-19 22:30 UTC, Sabina-Vishnya reviewed
валидации на дто не нужны?

2024-06-25 16:32 UTC, AlexHor230 commented
> валидации на дто не нужны?

Валидации добавил

2024-06-26 00:15 UTC, Sabina-Vishnya approved these changes
гуд, имена методов в маппере поправь и если тестики нужно дописать, то го

2024-06-26 00:15 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +    List<SkillDto> skillToDto(List<Skill> skills);
имена методов лучше, как в большинстве мапперов
типа: toDto, toDtoList
аналогично для моделек - toModel или toEntity (toEntity больше подходит, тк в пакете энтити)

2024-06-28 15:24 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +    List<SkillDto> skillToDto(List<Skill> skills);
и методы валидации не должны быть паблик, они у тебя только в скилл-сервисе используются

2024-12-21 21:08 UTC, closed without merging