Задача написание рекомендации
CorporationX/user_service pull request #1065
Opened 2024-05-17 09:15 UTC by p1maf

2024-05-23 20:08 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    }
Нет смысла явно объявлять конструктор. Лучше используй аннотации ломбока (@RequiredArgsConstructor @AllArgsConstructor)

2024-05-23 20:09 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    public RecommendationDto giveRecommendation(RecommendationDto recommendation) throws DataValidationException {
Зачем писать про выбрасываемое исключение?

2024-05-23 20:12 UTC, NadirCianid commented on src/main/java/school/faang/user_service/dto/RecommendationDto.java
> +}
Радмир кидал статьи про валидацию + на этой неделе на платформе про это была инфа. Попробуй применить валидацию от джакарты. Упростит код твой

2024-05-23 20:14 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    }
Когда добавишь аннотации @RequestBody у тебя не попадет в метод объект с null-ом, но в данной реализации такое может быть. 

+ Ты проверяешь конент методом isBlank, не проверив на null...
+ Я бы проверял еще наличие айдишников получателя и отправителя

2024-05-23 20:16 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +        validationRecommendation(update);
При обновлении рекомендации надо также проверить наличие id этой рекомендации, иначе там может быть null, а это можно было узнать еще на уровне контроллера

2024-05-23 20:17 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    }
такая проверка не проводится в контроллере. Такое должно быть в сервисе. Контроллер вообще не обращается к бд

2024-05-23 20:18 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    public Page<RecommendationDto> getAllUserRecommendations(long recieverId, int offset, int limit) {
Почему Page?

2024-05-23 20:20 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    public Page<RecommendationDto> getAllUserRecommendations(long recieverId, int offset, int limit) {
И для чего offset & limit ? Судя по названию метода ты возвращаешь все рекомендации, а не часть из них + по заданию такого не было

2024-05-23 20:21 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public void validationData(RecommendationDto recommendation) throws DataValidationException {
1 метод не должен быть публичным
2 название  слабо описывает происходящее внутри

2024-05-23 20:23 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        } else if (ChronoUnit.MONTHS.between(recommendation.getCreateAt(), currentDate) <= 6) {
зачем здесь else ? 

после выброса ошибки метод прерывается, так что else можно смело убирать

2024-05-23 20:23 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        } else if (ChronoUnit.MONTHS.between(recommendation.getCreateAt(), currentDate) <= 6) {
А вообще здесь надо еще проверить наличие в бд пользователей из дто

2024-05-23 20:26 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public void saveSkillOffers(Recommendation recommendation) {
Нет смысла делать его публичным методом

2024-05-23 20:26 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        for (SkillOffer skillOffer : skillOffers) {
Почему не используешь здесь стримы?

2024-05-23 20:27 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        List<Skill> userSkills = userRepository.getById(receiverId).getSkills();
getById лучше не использовать. Он устаревший

2024-05-23 20:29 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +                Skill skill = skillRepository.getById(skillId);
не лучшая идея делать эти запросы в цикле

2024-05-23 20:30 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        return recommendationMapper.toDto(recommendation);
Строки лучше разделять отступами для лучшей читаемости

2024-05-23 20:33 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        return recommendationMapper.toDto(recommendation);
Нельзя удалять каждый раз рекомендацию при обновлении. 
- у нее поменяется id
- у сущности есть поле updated_at (оно же не просто так там)

2024-05-23 20:35 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    public Page<RecommendationDto> getAllUserRecommendations(long recieverId, int offset, int limit) {
Я дошел до репозитория, поэтому вопрос снимается. Но странно, что здесь так. В других сервисах я такого не видел

2024-05-23 20:38 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    RecommendationDto toDto(Recommendation recommendation);
Почему игноришь это поле здесь?

2024-05-23 20:39 UTC, NadirCianid requested changes
Исправь валидацию и добавь эндпоинты в контроллер

2024-06-01 13:43 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    }
Get методы не могут иметь тело

2024-06-01 13:44 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    }
offset & limit надо бы передавать через @RequestParam

2024-06-01 13:47 UTC, NadirCianid commented on src/main/java/school/faang/user_service/exception/ErrorResponse.java
> +}
бессмысленный класс

2024-06-01 13:48 UTC, NadirCianid commented on src/main/java/school/faang/user_service/handler/GlobalExceptionHandler.java
> +    }
нельзя просто строку вернуть?

2024-06-01 13:49 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
а, как ты планируешь мапить пользователей из айдишников?

2024-06-01 13:51 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        Recommendation recommendation = fillRecommendation(recommendationDto);
название метода не совсем соотносится с параметром. Правильнее было бы передать в него entity, а не дто

2024-06-01 13:52 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public RecommendationDto update(RecommendationDto updated) {
не лучшее название для параметра

2024-06-01 13:55 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        if (ChronoUnit.MONTHS.between(recommendation.getCreateAt().toLocalDate(), currentDate) <= 6) {
количество месяцев выноси хотя бы в константу

2024-06-01 13:56 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +            throw new DataValidationException("Object is null");
неправильное сообщение об ошибке. Тут скорее проблема будет в том, что такая реккоменадция не найдена

2024-06-01 13:57 UTC, NadirCianid requested changes
подправь контроллер и разберись с ErrorResponse

2024-06-02 14:49 UTC, p1maf commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
а я их и не маплю, у меня в методах есть получения пользователей и я просто set-ом прописываю

2024-06-02 20:46 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
для этого надо игнорить эти поля в маппере

2024-06-02 20:50 UTC, NadirCianid approved these changes

2024-06-04 21:32 UTC, Sabina-Vishnya requested changes
упрощай код в сервисе и обновлять ветку не забывай с мастера
коммиты информативнее делай, а то фикс чего ты делал остается загадкой, пока не посмотришь в код

2024-06-04 21:32 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void saveSkillOffers(Recommendation recommendation) {
рефакторинг
дублирование обобщай
декомпозируй метод

2024-06-04 21:32 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    private void validationDataBeforeUpdate(RecommendationDto recommendationDto) {
для одного лишь метода этот приватный делается, можно было бы и оставить в основном методе, было бы тоже вполне понятно и не громоздко
но это не критикл, просто иногда всё можно не тащить в приватные метода, можно не править это

2024-06-11 19:57 UTC, Sabina-Vishnya requested changes
немного правок еще и форматирование тыкни перед пушем или прям в классе сервиса формартни, а то местами пробелы поехали

2024-06-11 19:57 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +            if (userSkills.contains(skillId) && !userSkillGuaranteeRepository.existsById(authorId)) {
contains некорректно отработает сравнивая список скиллов с лонгом, странно, если идея тебе такое не подсвятила, надо поправить

2024-06-11 19:57 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private final int FILTER_MONTH = 6;
статик

2024-06-12 15:20 UTC, Sabina-Vishnya approved these changes

2024-06-16 18:55 UTC, merged