Получить всех пользователей, которым понравился пост или комментарий
CorporationX/user_service pull request #1067
Opened 2024-05-18 22:24 UTC by NadirCianid

…их пост/комментарий

2024-05-24 18:35 UTC, p1maf commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        }
Может перенести в отдельный метод валидации, правда мелкая проверка, но все же валидация должна быть отдельно

2024-05-24 19:27 UTC, p1maf requested changes

2024-05-24 19:27 UTC, p1maf commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public List<UserDto> getUsersByIds(@NonNull @RequestBody List<Long> ids) {
с @NoNull обсудили в дс

2024-05-25 09:10 UTC, NadirCianid commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        }
прям должна быть?

2024-05-25 09:30 UTC, p1maf approved these changes

2024-12-21 21:08 UTC, closed without merging