feature-6766 Добавление аватара пользователя.
CorporationX/user_service pull request #1086
Opened 2024-05-26 18:40 UTC by Fargus74

feature-6766 Добавление аватара пользователя. Реализовал всю логику задачи(пока без unit тестов). Протестировал всё через postman.

2024-05-31 16:07 UTC, Demchenkov7 requested changes

2024-05-31 16:07 UTC, Demchenkov7 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public UserDto savePic(Long userId, MultipartFile pic) {
забыл в s3 сохранить картинку

2024-05-31 17:37 UTC, Fargus74 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public UserDto savePic(Long userId, MultipartFile pic) {
Сохранение происходит на 69,70 строке

2024-06-01 19:12 UTC, vang31 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @DeleteMapping("{userId}/pic")
лучше писать полные слова. picture/image

2024-06-01 19:12 UTC, vang31 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
EventController/ давай тогда добавим сращу аннотации RestController/ проставим им ендпоинты

2024-06-01 19:12 UTC, vang31 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public UserDto savePic(@PathVariable Long userid, @RequestParam MultipartFile pic) {
больше подойдет название uploadProfilePic... мы же кладем картинку в профиль пользователя.

2024-06-04 08:06 UTC, vang31 reviewed
Хорошая работа! и Код. замечания есть но не крит. исправлять или нет. твоё усмотрение. прочитай и если решишь не менять, переноси в ревью.

2024-06-04 08:06 UTC, vang31 commented on src/main/java/school/faang/user_service/service/amazonS3/AmazonS3Config.java
> +package school.faang.user_service.service.amazonS3;
вынести в конфиг.

2024-06-04 08:06 UTC, vang31 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/create")
конечно это не крит, но писать действие в урле не нужно. 
Для клиента не должно быть понятно че они делают. всё что они знают, это запрос пост, передается какие-то параметры, и тело запроса, и всё.

То же самое и про update

2024-06-04 08:06 UTC, vang31 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +@RequestMapping("api/v1/events")
api/v1
либо выносят в yaml/ spring: servlet : mvc.
либо вообще не писать. хорошей практикой выносят, но часто ли этот параметр изменяется? редко.

2024-06-04 08:06 UTC, vang31 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("api/v1/users")
давай тоже вынесем.
чтобы не было конфликта. 1 выносят а все остальные @RequestMapping("/users") делают такие аннотации

2024-06-04 16:20 UTC, Fargus74 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +@RequestMapping("api/v1/events")
Решил не выносить и не писать, в рамках учебного проекта не будем заострять на этом внимание

2024-06-06 19:21 UTC, vang31 approved these changes

2024-06-06 19:22 UTC, merged