Feature bjs2 6776
CorporationX/user_service pull request #1106
Opened 2024-06-07 19:38 UTC by VadimShibanov

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +public class UserController {
Не хватает контекстного пути для контроллера юзеров
@RequestMapping("users")

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return userService.saveUsers(multipartFile.getInputStream());
Почему метод в сервисе называется "сохранение пользователей ",когда ты сохраняешь именно файлы(данные)?
Тогда можно добавить,что сохраняются именно из файла

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        return iterator.readAll();
После обработки input streamов их надо закрывать. Иначе будут висеть ресурсы в системе неосвобожденные

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<Person> parser(InputStream part) throws IOException {
Оч много пробросов exception наверх, аж до самого контроллера
Можно обернуть в непроверяемое исключение,а потом ловить сверху методами CompletableFuture,которые с ошибками работают

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            allPersons.addAll(result.get());
А зачем тут переменная result? Он и без неё спокойно коллекцию тебе добавит
Просто потом жди,пока все completable future не отработают
То есть ты получишь future от executor service,а ее уже можно положить в список из future
А потом CompletableFuture.allOf(массив в список)

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<CSVPart> splitCsvFile(InputStream inputStream) throws IOException {
А для чего этот метод,если его можно заменить jackson csv парсером?
Если хочешь поделить файл перед чтением,можно посмотреть может ли jackson обрабатывать файл частями

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<User> countryAndPasswordAdderAndListOfPersonsToListOfUsersConverter(List<Person> persons) {
Огромные названия методов и много строк кода
Разбить бы немного по принципу единственной ответственности

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        String combination = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890!@#$%^&*()_+{}:<>?";
Алфавит для паролей можно вынести в константу

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        if (multipartFile.isEmpty()) {
Оч много простых проверок на null и пустые коллекции
Можно использовать валидацию через аннотации. Посмотри в других PRах, + кидал статьи в chatting насчёт валидации

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    @Mapping(target = "aboutMe", expression = "java(\" I'm from \" " +
Оч большой маппинг
Либо вынести в константу,либо в qualifiedByName метод,который строку возвращает

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    @Mapping(target = "username", expression = "java(person.getFirstName() + person.getLastName())")
То же самое,можно заменить на qualifiedByName метод,а там уже брать эти переменные

2024-06-08 06:18 UTC, RickHammerson commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        List<String> currentPartLines = new ArrayList<>();
Оч много переменных локальных
Можно выделить в отдельный класс и его уже заполнять методами
Но,как и сказал ранее, очень много логики уже могло быть реализовано в jackson маппере. Облегчишь себе жизнь

2024-06-08 06:18 UTC, RickHammerson commented
Нужно смержить феникс мастер в эту ветку,чтобы подтянуть изменения

2024-06-11 08:46 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +public class UserController {
Подтянул изменения, контексный путь добавился

2024-06-11 08:48 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return userService.saveUsers(multipartFile.getInputStream());
ok

2024-06-11 09:17 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        String combination = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890!@#$%^&*()_+{}:<>?";
ok

2024-06-11 09:19 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        return iterator.readAll();
ok

2024-06-11 09:59 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    @Mapping(target = "aboutMe", expression = "java(\" I'm from \" " +
okl

2024-06-11 09:59 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    @Mapping(target = "username", expression = "java(person.getFirstName() + person.getLastName())")
ok

2024-06-14 11:31 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<User> countryAndPasswordAdderAndListOfPersonsToListOfUsersConverter(List<Person> persons) {
ok

2024-06-14 13:20 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            allPersons.addAll(result.get());
Решил использовать более походящий подход

2024-06-14 13:23 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        List<String> currentPartLines = new ArrayList<>();
Распределил логику по классам

2024-06-16 00:14 UTC, Sabina-Vishnya requested changes

2024-06-16 00:14 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @PostMapping()
() не нужно тогда

2024-06-16 00:14 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @GetMapping()
тоже не нужно ()

2024-06-16 00:14 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
>          return goalInvitationService.createInvitation(invitation);
а точно ошибка нормальная придет, если запрос кривой кинуть, будет статус 400? ты проверял это на всех запросах?

2024-06-16 00:14 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public List<UserDto> saveUsersFromFile(InputStream inputStream) throws IOException {
так)
ты, Денис, Радмир, Андрей, Коля делают/кто-то сделал
эти задачи с файлами, разрефачьте вы эту логику, не обязательно ведь работу с файлами пихать в эти все сервисы юзеров/проектов/постов и тд, особенно, когда это очевидно разрастается все одном классе

можно выносить в отдельные сервисы, как минимум, которые будут содержать эту логику по работе с файлами

2024-06-16 00:14 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                    updatedUsers.remove(user);
removeIf не подойдет? по идее тогда не будет такой большой конструкции, немного сократим код

2024-06-16 00:14 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/Converter.java
> +    public List<CSVPart> convertToCsvList(InputStream inputStream) throws IOException {
все эти новые классы в папке сервис юзер сложные и большие, некоторые непонятно зачем 
думай над упрощением логики и хорошо бы джава доки писать иногда (хотя понятный код не нуждается в доке)
упрощение, как пример, lines().collect не подойдет тебе?
почему IOException нельзя тут ловить? зачем пробрасывать выше?
parts перед циклом может прям создать, а не сразу, не проверив даже lines? и вообще может декомпозировать на три класса? у тебя первый метод возвращает List<CSVPart>, второй List<InputStream>, третий List<User>, правда не совсем понятно, почему так сделано
и Adder какую смысловую нагрузку несет? почему он так называется?
CSVPart стоит того, чтобы выносить в отдельный класс?

если сложно понять, поищи в соседних командах решения для этой задачи, поспрашивай тех, кто сделал (и у предыдущих потоков тоже можно посмотреть) и обязательно проверь, что твои сервисы в итоге работают.

2024-06-17 17:51 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @PostMapping()
ok

2024-06-17 17:51 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @GetMapping()
ok

2024-06-17 17:57 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                    updatedUsers.remove(user);
ok

2024-06-17 18:26 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public List<UserDto> saveUsersFromFile(InputStream inputStream) throws IOException {
ok

2024-06-17 19:12 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/Converter.java
> +    public List<CSVPart> convertToCsvList(InputStream inputStream) throws IOException {
ok

2024-06-19 15:22 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
>          return goalInvitationService.createInvitation(invitation);
ok

2024-06-22 01:22 UTC, Sabina-Vishnya reviewed
ты не прорефачил основные классы с логикой)
попробуй накидать тесты на эти классы, а именно на логику вычислений всякий проверить на корректность, может так тебе будет проще подрефачить код

вот видишь что метод большой, уже признак того, что логика избыточна и ее можно подрефачить, хотя бы на логические блоки разделить
дробить на более мелкие задачи и их решать, тогда проще будет улучшать и читаемость кода

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/parse/AddCountryAndPassword.java
> +    private final String COMBINATION = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890!@#$%^&*()_+{}:<>?";
статик

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/parse/AddCountryAndPassword.java
> +    public User addCountryAndPassword(User user, Country country) {
метод passwordGenerator может быть в утилитах и называться иначе, например PasswordGenerator и метод переименовать в generate, и методу быть статиком (аннотация компонента можно будет убрать и вызывать просто этот статический метод)
а метод добавления можно унести в ToUserListConverter (класс переименовать, лучше UserConverter, хотя у тебя там мапинг с персон лист на юзер лист, можно название тогда чуть развернутее), там все равно ты мапишь как раз

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/parse/DataFromFileService.java
> +    public List<UserDto> saveUsersFromFile(InputStream inputStream) {
ты ищешь дубли и удаляешь их, если существует, почему не использовать сет, разве он тут тебе не подойдет?
и стримы использовать попробуй, будет компактнее, а для пущей читаемости разнеси на приватные методы хотя бы, у тебя парсинг, извлечение и фильтрация - могут уйти в приватные
попробуй упростить, говорили уже про рефакторинг еще по предыдущим замечаниям и на дейли

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/parse/Parser.java
> +    private List<Person> parser(InputStream part) {
parseCsv тогда уж, раз для него

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/parse/Parser.java
> +    private static final int THREAD_POOL_SIZE = 4;
в конфиг

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/parse/Parser.java
> +    public List<Person> multiParser(List<InputStream> parts) {
хорошо бы логировать ошибки такие еще

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/parse/ToCsvListConverter.java
> +    public List<CSVPart> convertToCsvList(InputStream inputStream) {
и тут не отрефачил(
int amountOfParts = 4; можно в константу
разделить этот большой методы, можно на приватные методы, немного читаемость улучшить

метод для чтения
метод разделения данных
переименовать класс ближе к тому, том что тут происходит чтение и разделение

условия верные? например if (amountOfParts == partCount && totalLines > partCount) будет фолс при 0, так и должно быть? можно вычислить кол-во строк для каждой части, учитывая, случай когда кол-во строк не делится нацело на части. И 4 так и должно быть? Если totalLines не делится на 4 без остатка, то одна из частей будет содержать меньше строк, чем остальные.

header каждый раз в цикле добавляется, он всегда разный?

2024-06-22 01:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/Converter.java
> +    public List<CSVPart> convertToCsvList(InputStream inputStream) throws IOException {
???

2024-06-22 01:24 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
>          return goalInvitationService.createInvitation(invitation);
давай-ка договоримся о более развернутых ответах на пр-ах, если есть вопросы у кого-то к твоим частям кода) а то вообще непонятно будет ничего, а держать все устные разговоры в голове мы не в силах)

2024-06-22 15:54 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
>          return goalInvitationService.createInvitation(invitation);
теперь ошибки не будет, заводил специально задачу в jira по фиксу багов в Post Service. Ошибка была не в моем коде.

2024-06-22 15:59 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/parse/AddCountryAndPassword.java
> +    private final String COMBINATION = "QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234567890!@#$%^&*()_+{}:<>?";
исправил

2024-06-22 16:54 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/parse/AddCountryAndPassword.java
> +    public User addCountryAndPassword(User user, Country country) {
Создал класс PasswordGenerator без @Component со статическим методом .generate() в пакете util. Метод добавления страны и пароля перенес в класс PersonToUserConverter.

2024-06-22 16:58 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/parse/Parser.java
> +    private List<Person> parser(InputStream part) {
Переименовал.

2024-06-22 17:52 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/parse/DataFromFileService.java
> +    public List<UserDto> saveUsersFromFile(InputStream inputStream) {
Фильтрацию вынес в отдельный приватный метод, в котором использовал сеты и стримы. Остальные методы относятся к другим классам.

2024-06-22 19:09 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/parse/Parser.java
> +    private static final int THREAD_POOL_SIZE = 4;
ok

2024-06-22 19:44 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/parse/ToCsvListConverter.java
> +    public List<CSVPart> convertToCsvList(InputStream inputStream) {
Количество частей оформил в константу, класс ToCsvListConverter переименовал в ReadAndDevide, метод convertToCsvList переименовал в toCsvPartDivider и отрефаичил, добавил приватный метод ему в помощь по чтению потока. header добавляется каждый раз, потому что он должен быть в каждой части.

2024-06-22 19:55 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/parse/Parser.java
> +    public List<Person> multiParser(List<InputStream> parts) {
Добавил логирование.

2024-06-22 21:16 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<Person> parser(InputStream part) throws IOException {
Ошибки обработал

2024-06-22 21:16 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        if (multipartFile.isEmpty()) {
Добавил аннотацию

2024-06-24 20:50 UTC, Sabina-Vishnya reviewed
не надо менять хосты в пр-ах, если это не является ошибкой)  по истории гита надо проверить какой был изначально, кажется 8080 Влад добавлял изначально, но надо убедиться, а то там перед этим этот порт меняло несколько человек кажется)

а так, по пр-у уже лучше, теперь добавляй тестики) там глядишь еще увидешь места для рефакторинга, что сложно тестировать будет например

2024-07-03 15:55 UTC, Sabina-Vishnya approved these changes
джава док впиши на классы из папки парсера

2024-07-03 15:55 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationServiceValidator.java
>          if (setGoals.contains(goal)) {
в этом классе есть контанта static final int SETGOAL_SIZE = 3;
она должна быть приватной и название можно просто GOAL_SIZE

2024-07-03 15:56 UTC, Sabina-Vishnya requested changes
падает ci

2024-07-05 06:30 UTC, VadimShibanov commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationServiceValidator.java
>          if (setGoals.contains(goal)) {
Да, просмотрел, поправил!

2024-07-06 17:27 UTC, Sabina-Vishnya commented
над методами было бы хорошо тоже доки добавить, которые из парсера
и в классе DataFromFileService у тебя док с ненужными цифрами

2024-07-06 17:27 UTC, Sabina-Vishnya approved these changes

2024-07-06 20:09 UTC, VadimShibanov commented
> над методами было бы хорошо тоже доки добавить, которые из парсера и в классе DataFromFileService у тебя док с ненужными цифрами

2024-07-06 20:29 UTC, merged