Feature bjs2 15945
CorporationX/user_service pull request #1148
Opened 2024-07-02 10:34 UTC by vanekJpeg

2024-07-02 20:11 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @GetMapping("/filter")
Если только один метод получения всех приглашений, может просто  GET сделать без дополнительного эндопоинта /filter?

2024-07-02 20:11 UTC, malkov34 commented on src/main/java/school/faang/user_service/mapper/GoalInvitationMapper.java
> +    @Mapping(source = "id", target = "id")
Если source == target, то и так смаппить должен без аннотации

2024-07-02 20:11 UTC, malkov34 commented on src/main/java/school/faang/user_service/mapper/GoalInvitationMapper.java
> +    GoalInvitationMapper INSTANCE = Mappers.getMapper(GoalInvitationMapper.class);
Не совсем понял для чего INSTANCE(
Можем обойтись только @Mapper(componentModel = "spring") для уменьшения кол-ва кода?

2024-07-02 20:11 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +            throw new NoSuchElementException("User with id:" + goalInvitationDto.getInvitedUserId() + " doesn't exist!");
В тексте ошибки вместо User Должно быть Goal, ну и goalInvitationDto.getGoalId?))

2024-07-02 20:11 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        invited.setReceivedGoalInvitations(List.of(new GoalInvitation()));
Тут точно должен быть NEW GoalInvitation?

2024-07-02 20:11 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        return goalInvitations.stream().map(goalInvitationMapper::toDto).toList();
Как рекомендация
Можно в маппере добавить для List
List<GoalInvitationDto<>> toListDto(List<GoalInvitation<>> goalInvitations);

должен автоматом на основании одиночного маппера сгенерить. 
ПС. как тут ставить нормальные <<>>  в комментах?

2024-07-03 08:15 UTC, malkov34 approved these changes

2024-07-07 13:32 UTC, pablo023 requested changes

2024-07-07 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    }
Возвращать нужно не респонс ентити, а сам дто) Если ты хочешь, чтобы возвращался ещё и статус - используй аннотацию ResponseStatus

2024-07-07 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
По всему контроллеру фиксани ResponseEntity на dto

2024-07-07 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +
Вот это всё имеет смысл вынести в отдельный класс валидатор, обозавть соотвествующим методом, а в сервисе делать только что-то в духе invitationValidator.validate(...)

2024-07-07 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    public GoalInvitationDto createInvitation(@NotNull GoalInvitationDto goalInvitationDto) {
Этот notNull должен быть в самой сущности дто, и отлетать на этапе контроллера через аннотацию @ Valid. Погугли её.

2024-07-07 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        GoalInvitation savedInvitation = goalInvitationRepository.findById(id)
Она ещё не сохранена, не надо её называть saved.

2024-07-07 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        goalInvitations = filterByInvitedNamePattern(goalInvitations, filter.getInvitedNamePattern());
Не совсем так мы делаем фильтрацию) На платформе уже есть ролик - это делается через итерфейс, и его имплементации, и списком интерфейса мы проходимся) Посмотри видео Влада на платформе, там подробно о том - как это сделать нужно)

2024-07-07 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    }
Вот это всё - отдельные имплементации интерфейса должны быть, будет гораздо удобнее, чище, и легче расширять код будет.

2024-07-07 13:32 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/service/GoalInvitationServiceTest.java
> +        // for createInvitation
Это понятно, убери комменты, пожалуйста)

2024-07-07 13:32 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/service/GoalInvitationServiceTest.java
> +    public void testGetInvitations_withInviterNamePattern() {
Это должно быть отдельным тестовым классом.

2024-07-07 13:32 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/service/GoalInvitationServiceTest.java
Посмотри аннотацию DisplayName для тестов

2024-07-10 03:45 UTC, pablo023 requested changes

2024-07-10 03:45 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
В этом интерфейсе есть какой-то смысл?)

2024-07-10 03:45 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/InvintationDtoValidatorImpl.java
Это лучше разбивать на отдельные методы. У тебя может быть здесь кейс, когда из валидаций не нужна. И придется всё равно выносить. А ещё у тебя этот метод расти будет до неприличных размеров, если новые валидации будут появляться. Разбей)

2024-07-10 03:45 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/filters/InvitationInvitedNameFilterTest.java
Убери комменты, и глянь аннотацию DisplayName

2024-07-10 07:10 UTC, vanekJpeg commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
Ну все делаю через интерфейсы, чтобы красиво, и вдруг пригодится)

2024-07-21 05:53 UTC, merged