BJS2 - 15554 - Запрос на менторство
CorporationX/user_service pull request #1149
Opened 2024-07-02 13:22 UTC by ravshanbekn

Сделал часть: Отправить запрос на менторство

2024-07-03 06:15 UTC, shade2903 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +    private void validateMentorshipRequest(long requesterId, long receiverId, LocalDateTime mentorshipCreationDate) {
Мне кажется в сервисе не должно быть реализаций отдельных методов валидаций, у тебя есть отдельный класс MentorshipRequestValidator и я бы этот метод туда перенес. А так в целом гуд

2024-07-03 07:51 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +    private void validateMentorshipRequest(long requesterId, long receiverId, LocalDateTime mentorshipCreationDate) {
Хорошо, спасибо

2024-07-05 04:39 UTC, pablo023 requested changes
Поработай над комментами.

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestValidator.validateMentorshipRequestDescription(mentorshipRequestDto.getDescription());
Вот эта валидация должна осуществляться на уровне сервиса. На уровне контроллера ты валидируешь только корректность данных, которые идут в запросе - есть ли там нуллы, и прочее.

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/mentorship/MentorshipRequestDto.java
Для лонгов можно использовать примитивы.

2024-07-05 04:39 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceTest.java
> +    @Spy
Spy - плохая практика. Знаешь об этом?

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +        } else if (description.length() > 4096) {
Чёт магией запахло)

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +            throw new IllegalArgumentException("MentorshipRequest sender is not registered in Data Base");
Database*

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +    public void validateReflection(long requesterId, long receiverId) {
Название такое себе. Reflection - это отдельная тема в Java,с которой тут создаётся ассоциация.

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        mentorshipRequestValidator.validateMentorshipRequestFrequency(requesterId, receiverId, mentorshipCreationDate);
Вот этот чейн валидаций как будто бы можно было бы в один метод запихать в валидаторе.

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        setRequestStatusAndSaveToDataBase(mentorshipRequest, RequestStatus.REJECTED);
У тебя дублируется этот код в методах

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +    public void validateMentorshipRequestReceiverAndRequesterExistence(long requesterId, long receiverId) {
validateMentorshipParticipants*

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        MentorshipRequest mentorshipRequest = getMentorshipRequestByIdOrThrowException(requestId);
Не нужно создавать уровень абстракции, который просто одну строчку с эксепшеном заворачивает.

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +                setRequestStatusAndSaveToDataBase(mentorshipRequest, RequestStatus.ACCEPTED);
Аналогично

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +        } else if (description.length() > 4096) {
Магия?)

2024-07-05 04:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +    public void validateReflection(long requesterId, long receiverId) {
Reflection в Java имеет отдельный контекст. Название метода в заблуждение вводит

2024-07-05 13:49 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestValidator.validateMentorshipRequestDescription(mentorshipRequestDto.getDescription());
Хорошо, можно еще валидировать минимальный id в контроллере? Мол id >= MIN_ID

2024-07-05 13:49 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/dto/mentorship/MentorshipRequestDto.java
Хорошо

2024-07-05 13:50 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceTest.java
> +    @Spy
После дейлика знаю

2024-07-05 13:50 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +        } else if (description.length() > 4096) {
Исправлю

2024-07-05 13:54 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +            throw new IllegalArgumentException("MentorshipRequest sender is not registered in Data Base");
Хорошо

2024-07-05 13:57 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +    public void validateMentorshipRequestReceiverAndRequesterExistence(long requesterId, long receiverId) {
Хорошо, исправил

2024-07-05 13:59 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        MentorshipRequest mentorshipRequest = getMentorshipRequestByIdOrThrowException(requestId);
Хорошо, исправил

2024-07-05 13:59 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +                setRequestStatusAndSaveToDataBase(mentorshipRequest, RequestStatus.ACCEPTED);
Исправил

2024-07-05 14:00 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +    public void validateReflection(long requesterId, long receiverId) {
Исправил

2024-07-05 15:56 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +        } else if (description.length() > 4096) {
Исправил

2024-07-05 16:25 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        mentorshipRequestValidator.validateMentorshipRequestFrequency(requesterId, receiverId, mentorshipCreationDate);
Сделал

2024-07-05 16:26 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +    public void validateReflection(long requesterId, long receiverId) {
Исправил

2024-07-05 16:48 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        setRequestStatusAndSaveToDataBase(mentorshipRequest, RequestStatus.REJECTED);
Вроде бы сделал, как то не уверен. Можешь еще раз посмотреть?

2024-07-06 23:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestValidator.validateMentorshipRequestDescription(mentorshipRequestDto.getDescription());
Нет, в контроллере не нужно валидаций каких-то, кроме как на поля, которые в классе dto аннотациями помечены. Есть момент с id интересный - там можно использовать класс-обертку, т.к. примитив если не указан, то он будет 0, а оберточный класс будет null, и это упадёт быстрее.

2024-07-07 00:06 UTC, pablo023 requested changes
В целом окей. Убери валидатор из контроллера, исправь некоторые тесты, используй в тестах аннотацию DisplayName, поправь методы сервиса, где я указал, и окей. В целом всё хорошо, но по мелочи можно доработать)

2024-07-07 00:06 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    private final MentorshipRequestValidator mentorshipRequestValidator;
Нам это здесь не нужно.

2024-07-07 00:06 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestValidator.validateMentorshipRequestDto(mentorshipRequestDto);
Валидацию из контроллера убираем, это в сервис.

2024-07-07 00:06 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +                setRequestStatusAndSaveToDataBase(mentorshipRequest, RequestStatus.ACCEPTED);
Тут очень длинные названия методов, и вот когда у тебя метод делает два каких-то действия - это не гуд. Типа setStatus и saveToDataBase. Не надо никогда объединять, если ты используешь and в названии метода - что-то ты неправильно делаешь. И не DataBase, а repository. Можно в принципе на будущее - просто save. Итак понятно, что в репозиторий.

2024-07-07 00:06 UTC, pablo023 commented on src/test/java/school/faang/user_service/controller/mentorship/MentorshipRequestControllerTest.java
> +    }
Вот этот лишний, получается, т.к. валдиацию мы убираем из контроллера.

2024-07-07 00:06 UTC, pablo023 commented on src/test/java/school/faang/user_service/controller/mentorship/MentorshipRequestControllerTest.java
> +    public void testGetRequestsServiceExecution() {
Это не очень правильно. Ты тестируешь судя по названию метод сервиса, а в тесте дергаешь контроллер. надо сервис дергать.

2024-07-07 00:06 UTC, pablo023 commented on src/test/java/school/faang/user_service/filter/mentorship/MentorshipRequestReceiverFilterTest.java
> +@ExtendWith(MockitoExtension.class)
А она тебе тут нужна? Ты не мокаешь ничего же.

2024-07-07 00:06 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceTest.java
> +    public void testRequestMentorshipMapperToDtoExecution() {
Маппер не нужно тестить, это сторонняя либа.

2024-07-07 00:06 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceTest.java
> +    }
Их куда-то в конец, либо в beforeEach / beforeAll

2024-07-07 09:55 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    private final MentorshipRequestValidator mentorshipRequestValidator;
Хорошо, исправил

2024-07-07 10:07 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +                setRequestStatusAndSaveToDataBase(mentorshipRequest, RequestStatus.ACCEPTED);
В предыдущем ревью ты отметил этот же участок кода за повторение кода. Получается, один принцип надо все таки нарушить?

2024-07-07 10:40 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/controller/mentorship/MentorshipRequestControllerTest.java
> +    }
Хорошо

2024-07-07 10:42 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/controller/mentorship/MentorshipRequestControllerTest.java
> +    public void testGetRequestsServiceExecution() {
А мне разве не нужно проверять дергается ли service внутри controller?

2024-07-07 10:53 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceTest.java
> +    public void testRequestMentorshipMapperToDtoExecution() {
Выполнение маппера тоже не нужно тестить?

2024-07-07 10:53 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/filter/mentorship/MentorshipRequestReceiverFilterTest.java
> +@ExtendWith(MockitoExtension.class)
Исправил

2024-07-07 11:02 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceTest.java
> +    }
Исправил

2024-07-07 17:45 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +                setRequestStatusAndSaveToDataBase(mentorshipRequest, RequestStatus.ACCEPTED);
А не, все, реализовал

2024-07-07 17:45 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestValidator.validateMentorshipRequestDto(mentorshipRequestDto);
Хорошо

2024-07-10 00:01 UTC, pablo023 approved these changes
Молодец) Мерджим!

2024-07-10 00:01 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/mentorship/MentorshipRequestDto.java
> +    @NotNull(message = "Description should not be null value")
NotBlank было бы еще неплохо добавить

2024-07-10 00:01 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/mentorship/RejectionDto.java
> +    @NotNull
NotBlank

2024-07-10 00:01 UTC, merged

2024-07-10 08:55 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/dto/mentorship/MentorshipRequestDto.java
> +    @NotNull(message = "Description should not be null value")
Хорошо

2024-07-10 08:55 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/dto/mentorship/RejectionDto.java
> +    @NotNull
Хорошо