BJS2-15563
CorporationX/user_service pull request #1153
Opened 2024-07-02 20:48 UTC by Caveri95

- Создал класс контроллер с методами для работы с событиями (регистрация/отмена регистрации/получения списка участников/количество участников)
- Создал класс сервис с логикой по работе со слоем репозитория событий
- Добавил тесты

2024-07-03 18:23 UTC, ravshanbekn reviewed
Думаю, в целом, нормально

2024-07-03 18:23 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/dto/EventDto.java
> +    private String location;
По моему аннотации @ Min @ Max нужны для численных типов
Для String:
@ Size(min = 1, message = "validation message")
@ Size(max = 64, message = "validation message")
Еще я бы указал сообщение в message аргумент

2024-07-03 18:23 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    private String username;
Тут тоже через аннотацию @ Size

2024-07-03 18:28 UTC, Caveri95 commented on src/main/java/school/faang/user_service/dto/EventDto.java
> +    private String location;
Да, точно, ты прав, что то забыл про нее. В Size сразу можно указать два аргумента на нижнюю и верхнюю границы

2024-07-03 18:29 UTC, Caveri95 commented on src/main/java/school/faang/user_service/dto/EventDto.java
> +    private String location;
Если провалиться в message, то там неплохие такие заготовки на описание ошибки

2024-07-07 13:38 UTC, pablo023 requested changes
Очень хорошо) Немного исправь, и едем дальше!

2024-07-07 13:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/eventService/EventParticipationServiceImpl.java
> +    }
Тут есть валидация, её лучше в отдельный класс - какой-то, в духе.. EventParticipantsValidator. И чтобы просто метод начинася примерно с такой строчки:

eventParticipantsValidator.validate(eventId, userId);

Над неймингом, конечно, подумай, чтобы название отображало суть валидации конкретной. Можно конечно сделать через перегруженный метод, чтобы был один validate для разных сценариев, но это опсано - может получиться как лучше, так и хуже, надо как следует подумать.

2024-07-07 13:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/eventService/EventParticipationServiceImpl.java
Всю валидацию надо вынести в отдельный класс, и его методы.

2024-07-07 16:48 UTC, Caveri95 commented on src/main/java/school/faang/user_service/service/eventService/EventParticipationServiceImpl.java
> +    }
Вынес валидацию в отдельный класс, но по ощущениям так стало только сложнее.
Если метод валидации делаю войд, то тестировать его уже не очень становится и в методе сервиса тест будет только на то, что у нас дернется валидация и, например, регистрация. Хотя регистрация может и не вызваться, если валидация не пройдет.
В самом классе валидации есть два метода, по сути раньше они отличались только возвращаемым значением  true/false, сейчас они войд и приходится разделять эти методы. 
В общем посмотри пожалуйста.

2024-07-08 11:25 UTC, i7rincpane commented on src/main/java/school/faang/user_service/service/eventService/EventParticipationServiceImpl.java
> +    }
Да необычно, что сценарии разные, может тогда лучше чтобы каждый сценарий свой валидатор имел и сделать типо, как с фильтром, динамическое добавление ХХХ)))))) насчет тестов, если правильно понял, вроде как verifyNoInteractions можно вызвать проверить, что регистрация не дернулась.. но вообще юнит тесты тоже смущают сильно, сам себе создаешь какие-то ситуации, и не понятно проверяешь ли вообще что то? поскорей бы интеграционные, там как то все более очевидно кажется

2024-07-10 01:08 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/eventService/EventParticipationServiceImpl.java
> +    }
> Да необычно, что сценарии разные, может тогда лучше чтобы каждый сценарий свой валидатор имел и сделать типо, как с фильтром, динамическое добавление ХХХ)))))) насчет тестов, если правильно понял, вроде как verifyNoInteractions можно вызвать проверить, что регистрация и мапер не дернулись.. но вообще юнит тесты тоже смущают сильно, сам себе создаешь какие-то ситуации, и не понятно проверяешь ли вообще что то? поскорей бы интеграционные, там как то все более очевидно кажется

Такова природа юнит-тестов. Если тебя это смущает - обрати внимание на TDD. Мне такой подход неоднократно помогал начать что-то писать, когда я не понимал - с какой стороны подступиться, и юнит-тесты обретают больше смысла.

2024-07-10 01:10 UTC, pablo023 approved these changes
Молодец)

2024-07-10 01:10 UTC, pablo023 commented on src/main/java/school/faang/user_service/Validate/EventParticipantValidator.java
Если тебя смущают тут войды, ты можешь сделать их булеанами. В целом войды не должны смущать, тестить их не так удобно, но научиться можно. Пакет переименуй на validator, форс пуш, и смерджи сам

2024-07-10 01:10 UTC, pablo023 commented
И конфликты пофиксь.

2024-07-10 16:46 UTC, merged