Подписка на других пользователей
CorporationX/user_service pull request #1154
Opened 2024-07-03 18:47 UTC by kpzxpf

2024-07-04 17:19 UTC, Caveri95 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        if (followerId != followeeId) {
Я бы убирал всю логику лишнюю из контроллера по максимуму и переносил в слой сервиса

2024-07-06 09:34 UTC, ravshanbekn reviewed
Насчет папок, кажется, у тебя userFilter лежит внутри service. Может лучше создать отдельную папку filter, затем в ней папку user?

В целом, нормально

2024-07-06 09:34 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    }
Думаю, эту часть лучше вынести в отдельный класс-валидатор. Можно сделать его Spring Bean, делать injection
там где нужно и использовать

2024-07-06 09:34 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    }
По моему, проверять входные данные на Null лучше сразу в контроллере, а в Service части содержание в БД и т.д

2024-07-06 09:34 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/service/filter/userFilter/UserAboutFilterTest.java
> +        userAboutFilter.apply(userStream, userFilterDto);
По сути, эта часть должна отфильтровать userStream. Затем, ты должен сделать из userStream -> List
И вот этот уже полученный лист сравнивать в assert

2024-07-06 09:34 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/service/filter/userFilter/UserAboutFilterTest.java
> +        userAboutFilter.apply(userStream, userFilterDto);
То же самое и в других тестах, посмотри пожалуйста, не хочу дублировать

2024-07-06 09:34 UTC, ravshanbekn commented on src/test/java/school/faang/user_service/service/filter/userFilter/UserAboutFilterTest.java
> +        when(secondUser.getAboutMe()).thenReturn("Another about");
Зачем мокать внутренние переменные? Разве мы не мокаем классы предоставляющие какую-либо логику?
Если ты не хочешь создавать класс со всеми параметрами, то в Lombok есть аннотация @ Builder, можешь посмотреть

2024-07-06 13:08 UTC, kpzxpf commented
> Насчет папок, кажется, у тебя userFilter лежит внутри service. Может лучше создать отдельную папку filter, затем в ней папку user?
> 
> В целом, нормально

2024-07-06 14:11 UTC, kpzxpf commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        if (followerId != followeeId) {
Здесь по заданию нужно было сделать проверку в контроллере

2024-07-06 14:12 UTC, kpzxpf commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    }
Хорошо, спасибо

2024-07-06 16:23 UTC, kpzxpf commented on src/test/java/school/faang/user_service/service/filter/userFilter/UserAboutFilterTest.java
> +        userAboutFilter.apply(userStream, userFilterDto);
Понял, спасибо

2024-07-06 16:25 UTC, kpzxpf commented on src/test/java/school/faang/user_service/service/filter/userFilter/UserAboutFilterTest.java
> +        when(secondUser.getAboutMe()).thenReturn("Another about");
Не знаю, правильно ли так делать, но так меньше кода получается

2024-07-07 00:23 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    }
Уместно.

2024-07-07 00:24 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/filter/userFilter/UserAboutFilterTest.java
> +        when(secondUser.getAboutMe()).thenReturn("Another about");
Не не не не. Мокито нужно использовать для того, чтобы имитировать тестируемую логику. Только то, что тебе нужно, чтобы "как будто отработало", т.е. сервисы, контроллеры, и тд - где ты логику писал, и хочешь проверить её.

2024-07-07 00:40 UTC, pablo023 requested changes
Надо исправить валидатор. Там есть лишнее. В остальном - мелочь. И хотелось бы побольше видеть assertion в тестах. Они слишком простенькие сейчас.

2024-07-07 00:40 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
Убери, пожалуйста, отсюда броски эксепшенов, и глянь аннотацию Valid.

2024-07-07 00:40 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/SubscriptionServiceValidator.java
> +    }
А зачем нам два абсолютно одинаковых метода? validateUserRelationship, к примеру, можно назвать один метод, который это делать будет.

2024-07-07 00:40 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/SubscriptionServiceValidator.java
> +    }
Ну тут одна строчка в методе. Это просто абстракция над каким-то методом, и больше ничего. Так не нужно делать никогда) Если у тебя метод не имеет какой-то логики, ничего не меняет - его не должно быть.

2024-07-07 00:40 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/SubscriptionServiceValidator.java
Тут есть лишнее. И измени везде на validate

2024-07-07 00:40 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
Глянь аннотацию DisplayName для тестов.

2024-07-07 10:49 UTC, kpzxpf commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
Убрал, но я не понимаю, как Valid можно здесь применить.

2024-07-07 10:49 UTC, kpzxpf commented on src/main/java/school/faang/user_service/validator/SubscriptionServiceValidator.java
> +    }
Понял

2024-07-07 10:50 UTC, kpzxpf commented on src/main/java/school/faang/user_service/validator/SubscriptionServiceValidator.java
> +    }
ок

2024-07-07 10:50 UTC, kpzxpf commented on src/main/java/school/faang/user_service/validator/SubscriptionServiceValidator.java
хорошо

2024-07-07 10:50 UTC, kpzxpf commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
ок

2024-07-07 13:44 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
С примитивами действительно никак, не обратил внимание. Но в любом случае, валидация на уровне АПИ - не бест практис, это нужно выполнять на уровне сервиса. Контроллеры -  они принимают запросы, разбирают, что от них хотят, и отправляют ответы. Сервисный слой – это там, где вся движуха происходит. Здесь всё крутится вокруг бизнес-логики, то есть, что и как должно происходить в приложении. Если валидации делать в сервисном слое, то ты можешь использовать их повторно в разных частях приложения. Например, если у тебя есть и REST API, и WebSocket API, то не нужно писать всё по два раза. Когда всё важное находится в сервисном слое, тебе проще следить за изменениями. Если что-то надо поменять в правилах бизнеса, ты меняешь это в одном месте, а не бегаешь по куче контроллеров. Тесты тоже писать проще, когда они касаются сервисного слоя, потому что ты тестируешь конкретные функции, а не морочишься с HTTP-штуками, которые у контроллеров. Когда валидации на уровне сервиса, ты можешь быть уверен, что они сработают вне зависимости от того, как к твоему приложению обращаются. Если бы они были только в контроллерах, новые контроллеры могли бы случайно их обойти. Когда приложение растёт, важно, чтобы основная бизнес-логика была в одном месте и не зависела от клиента. Так проще добавлять новые функции и расширяться.

2024-07-10 01:05 UTC, pablo023 approved these changes
Ну, это же просто прекрасно. Сам как считаешь?

2024-07-10 01:05 UTC, pablo023 commented
Пофикси конфликты.

2024-07-10 05:37 UTC, kpzxpf commented
> Ну, это же просто прекрасно. Сам как считаешь?

хорошо

2024-07-10 05:37 UTC, kpzxpf commented
> Пофикси конфликты.

пофиксил

2024-07-10 14:07 UTC, merged