BJS2-15555 - Стать ментором
CorporationX/user_service pull request #1159
Opened 2024-07-04 15:16 UTC by Kostahe

- Created MentorshipController
- Created MentorshipService
- Enhanced MentorshipService with @Transactional annotations
- Created  MentorshipValidator to validate mentee and mentor IDs
- Created UserDto
- Created UserMapper
- Added unit tests for MentorshipService, MentorshipController MentorshipValidator

2024-07-05 09:22 UTC, shade2903 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        log.error(errorMessage);
В целом написано все гуд кратко и без лишенего кода. Только в этом месте я бы этот метод вынес в какойнибудь отдельный класс, для последующего его переиспользования с другими сущностями и в других сервисах.

2024-07-07 00:22 UTC, pablo023 requested changes
Ты знаешь, неплохо) Но чтобы ты не скучал, пройдись по комментам, и еще - глянь аннотации:

ResposeStatus - для методов контроллера
DisplayName - для тестов
BeforeEach - для тестов
BeforeAll - для тестов

А так - молодчина!)

2024-07-07 00:22 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
Неплохо, глянь еще ResponseStatus аннотацию. Это необязательно, но я думаю, тебе будет интересно)

2024-07-07 00:22 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/UserDto.java
Для boolean лучше всегда добавлять is / are. Типа isActive. Это семантически более грамотно, и кодерам прям сразу понятно, что речь о каком-то булеан флаге.

2024-07-07 00:22 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        log.error(errorMessage);
Вот да, хороший коммент. И название метода не очень описательное. Что не нашлось то?) Надо добавить было либо user, либо что-то такое. В дальнейшем будет таска на ExceptionHandler. На данный момент ты мог бы вместо этого кидать NoSuchElementException, чтобы не морочиться с ExceptionHandler.

2024-07-07 00:22 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    }
Не то чтобы это прям не очень, но я вот так вижу:

return mentorshipRepository.findById(mentorId)
                               .map(User::getMentees)
                               .map(userMapper::usersToUserDTOs)
                               .orElseThrow(() -> notFoundException(mentorId));

2024-07-07 00:22 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    }
Это просто для раздумий, не обязательно так писать, конечно)

2024-07-07 13:36 UTC, Kostahe commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        log.error(errorMessage);
Окей

2024-07-07 13:36 UTC, Kostahe commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    }
Угу

2024-07-07 13:38 UTC, Kostahe commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
Да, посмотрел, было очень интересно

2024-07-07 13:41 UTC, Kostahe commented on src/main/java/school/faang/user_service/dto/UserDto.java
Да, поменяю. В классе User было поле 'active', и я подумал, что так будет лучше, чем использовать аннотацию `@Mapping`

2024-07-10 00:03 UTC, pablo023 approved these changes
Отличная работа, Леви Акерман

2024-07-10 00:05 UTC, merged