BJS2-15564 - "Организация события"
CorporationX/user_service pull request #1160
Opened 2024-07-04 15:59 UTC by i7rincpane

Реализовал возможность создавать событие.

2024-07-07 13:54 UTC, pablo023 requested changes
Поторопился, наверное, Паш) Надо переделать чуток)

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    }
Чет ты тут не дописал)

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
Смотри, разделение обязанностей это ключ. Контроллеры только проверяют валидность данных, через аннотацию Valid. Всю серьёзную работу по обеспечению порядка должен делать сервисный слой. Там всё и происходит: проверки, валидации ID и так далее. Это удобно, потому что ты можешь один и тот же код использовать в разных местах, не копируя его туда-сюда. Также это упрощает поддержку и обновление приложения — меняешь что-то в одном месте, а не бегаешь по всем контроллерам. Тестировать тоже легче, потому что тестируешь логику отдельно от веб-мороки. И безопаснее это, потому что ты уверен, что валидации сработают всегда, независимо от того, через что пользователь пришёл. Ну и наконец, так проще масштабировать приложение — добавляешь новые функции, расширяешься, и всё это без боли и страданий. Вот так вот все дело. Иногда в контроллерах происходит логика по работе с запросом - там контекст есть, и из него бывает нужно сформировать какие-то данные, которые отправляются на сервис. Но валидации, и исключения, которые летят с сервиса - оставь сервису.

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/SkillReadDto.java
> +}
Чет тут не дописал

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/event/EventCreateEditDto.java
> +    EventStatus eventStatus;
Чет модификаторы доступа забыл)

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/event/EventReadDto.java
> +    int maxAttendees;
Тоже забыл модификаторы)

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/Mapper.java
Маппинг делаем через MapStruct - это либа отдельная)

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/UserReadMapper.java
Про MapStruct не увидел в таске)

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
Лучше бы валидацию вынести в отдельный класс валидатор, т.к. они у нас могут добавляться существенно по мере роста приложения.

2024-07-07 13:54 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .map(eventReadMapper::map);
Ну и не просто мап, а toDto это будет)

2024-07-07 15:15 UTC, i7rincpane commented on src/main/java/school/faang/user_service/dto/event/EventCreateEditDto.java
> +    EventStatus eventStatus;
аннотация @value добавляет

2024-07-07 15:18 UTC, i7rincpane commented on src/main/java/school/faang/user_service/dto/event/EventReadDto.java
> +    int maxAttendees;
да не забыл)

2024-07-07 15:18 UTC, i7rincpane commented on src/main/java/school/faang/user_service/mapper/Mapper.java
жду решения по этому вопросу, нужно ли переписывать

2024-07-07 15:22 UTC, i7rincpane commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
жду решения по этому вопросу, нужно ли на каждый не валидный случай выкидывать исключение, или оставить реализацию где они копятся и выкидываются скоупом.. как понял, вопорос в том могут ли два пользователя использовать один экземпляр сервиса и совместно копить эти ошибки ? - мне кажется что не могут

2024-07-07 15:31 UTC, i7rincpane commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .map(eventReadMapper::map);
принял

2024-07-07 15:34 UTC, i7rincpane commented on src/main/java/school/faang/user_service/dto/SkillReadDto.java
> +}
не совсем понимаю нужно ли мне его заполнять, это вроде как не моя задача и он уже при мердже получается будет кем-то заполнен? или мне нужно найти задачу для скилов и заполнить в соответствии с этой задачей?

2024-07-07 15:37 UTC, i7rincpane commented on src/main/java/school/faang/user_service/controller/event/EventController.java
хороший комментарий, но вроде бы я так и сделал?

2024-07-07 15:43 UTC, i7rincpane commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    }
подскажи что, не пойму) я с рестом мало работал, в mvc редиректил на вьюшки .. тут тоже типо редирект нужен, или что?

2024-07-07 15:46 UTC, i7rincpane commented on src/main/java/school/faang/user_service/mapper/UserReadMapper.java
увидел, но боюсь её) + хочу контролировать процесс маппинга и иметь возможность добавлять сложную логику с подключением различных вложенностей

2024-07-10 03:17 UTC, pablo023 requested changes
Смотри, Паш, у тебя сейчас зона роста - это понимание абстракции, и её цели. Я не знаю зачем ты в целях написал, что ты хочешь джун+, или что-то такое, тебе до хорошего мидла тут осталось ничего. Давай определим хорошего мидла - одна из самых проблемных зон у мидлов, это - абстракции. У тебя сейчас есть понимание - что это такое, но нет понимания - для чего она нужна. Абстракция нужна там, где с помощью неё, ты усложнишь прямо сейчас жизнь себе, написав больше кода, но упростишь жизнь всем остальным в дальнейшем, потому что твой код будет чище, его будет легче читать, его будет легче расширять, и с ним будет проще работать другим разработчикам. На данный момент ты используешь абстракцию там, где ты видишь, что её можно использовать, просто так. Всегда, при любых обстоятельствах, твой код должен стремиться к тому, чтобы быть минималистичным, и максимально простым. Когда ты хочешь написать что-то, что угодно - подумай, как это сделать максимально просто. Когда ты понял - подумай, принесет ли такой подход проблемы прямо сейчас, либо в дальнейшем. Если принесет - подумай над тем, как сделать красиво. В любом случае, рабочий процесс в командой разработке - это условия коротких сроков, и код-ревью - это часть этого процесса. Когда ты пишешь коротко, красиво, и по делу - тебя быстро и легко ревьюить, и ты будешь получать быстрые аппрувы от старших коллег. Если ревью будет идти непросто - твой код будут либо возвращать, либо ревьюить сквозь пальцы, а потом, когда всё сломается - скандалить, что ну а как там ревьюить было. Если ты хочешь творческого простора, и прокачать свои скиллы - попроси сложную задачу, у нас есть реально сложные вещи, на которых дофига чему можно научиться. Но не усложняй простое ;-) 

Насчёт маппера - сделай с мапстрактом. Не бойся его, если надо будет - объясним. Тебе нужно, чтобы тебе было комфортно работать с любой технологией. Мапстракт, кстати, отличная. Но комфортно тебе должно быть с чем угодно, т.к. задачи - это задачи, и хоть на JS напишешь, если надо будет. Если у тебя есть желание реализовать свой мапстракт чисто из интереса - я не против, можем это отдельно обсудить.

2024-07-10 03:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
Будет тебе побольше таких, не проблема) Зачем я его написал - по методу delete. Лучше вынести валидацию во всех её видах, в сервисный слой. Это даже выглядеть будет проще и чище. А оттуда уже кидай валидаторами что хочешь)

2024-07-10 03:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/SkillReadDto.java
> +}
Если у тебя возникает ситуация, что тебе нужен какой-то класс из другой задачи, то у тебя есть такие варианты:

1) Сделать заглушку
2) Пойти к коллеге, который занимается этой функциональностью, и узнать у него статус. Если он уже написал этот код - можно попросить его этот код, например, либо подождать, пока его код будет вмерджен
3) Если на текущий момент задача, от которой зависит твой код - ни на ком, ты можешь ознакомиться с её условием, и реализовать какую-то часть функционала.

Но так или иначе, я не понял сути этого пустого класса - ты ведь нигде не применяешь его. Зачем он тебе? Я подумал, он тебе нужен, и ты его забыл заполнить, а он.. Не нужен)

2024-07-10 03:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/UserReadMapper.java
> +}
Ну Паш, это же неудобно получается. Ты вот написал логику маппинга здесь. Добавишь поле - тебе сюда идти и переписывать билдером как-то это всё придется)

2024-07-10 03:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        var validationResult = validator.validate(eventDto);
Вот этот кейс с варом не особо уместен. Чтобы понять, что validate валидатора возвращает, нужно в него идти.

2024-07-10 03:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/valitator/Error.java
В Java уже есть класс Error - подкласс Throwable. Когда ты создаешь такой класс для своих каких-то задач, ты вносишь путаницу в кодовую базу. Только ты будешь знать о том, что вот этот Error - это твой класс. Если ты на рабочем проекте будешь применять такую логику, то ты создашь проблемы тем, кто придет туда через несколько лет, и будет разбираться - что еще за Error тут кастомный.

2024-07-10 03:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/valitator/ValidationResult.java
Смотри, как у нас это будет работать. При работе приложения, будет какая-то стратегия создания этого класса. В любом случае, это сведется к трем вариантам:

1) Это будет синглтон. В таком случае, у тебя спринг-приложение будет рвать вот этот вот список, и набивать его хаотично, и лететь у тебя будет непойми что из него.

2) Он будет создваться каждый раз новый, для каждого потока. Для того, чтобы создать класс, и коллекцию вот эту - ты будешь затрачивать как процессорное время, так и память. Вопрос - для чего, какую проблему решает такой подход, жертвуя памятью и процессором?

3) Он будет создаваться и убиваться по вызову. Опять таки - для чего?) Если у тебя будет валидатор, который принимает параметры, валидирует их, и кидает эксепшен - у тебя не будет никаких жертв по памяти вообще, и  у тебя будет простой булеан метод.

2024-07-10 03:17 UTC, pablo023 commented on src/test/java/school/faang/user_service/mapper/event/EventCreateEditMapperTest.java
> +    }
Глянь аннотации BeforeEach, и BeforeAll

2024-07-10 03:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
Глянь ещё для контроллера интересные аннотации RequiredMapping, и ResponseStatus. Сейчас это необязательно, но я думаю, тебе будет интересно.

2024-07-13 02:39 UTC, pablo023 requested changes
Исправь мелочевку, и мержим)

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public void delete(Long id) {
deleteEvent*

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public EventReadDto update(Long id, EventCreateEditDto editDto) {
updateEvent

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public List<EventReadDto> getOwnedEvents(long userId) {
getEventsByUserId

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/event/EventCreateEditDto.java
Если ты хочешь разделить входные и выходные, то лучше ReadEvetDto / WriteEventDto. Это общая практика, так чаще всего называют.

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private final EventReadMapper readMapper;
eventToReadEventDtoMapper* С верхним аналогично.

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    public List<EventReadDto> findAllBy(EventFilterDto filter) {
by what?

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/filter/event/EventFilter.java
Упусил isApplicable

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
В этом методе у тебя бизнес-логика порвалась на контроллер и сервис. Пускай тут хэндлинг опшинала будет, и возвращаеся либо дто, либо исключение.

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        // пусть сервайс ошибку валидации выкидывает?
Эту ошибку пусть кидает сервис. Контроллер может кидать только ошибки, связанные с валидацией данных, такие как на нулл, либо несоотвествие типов. Когда ожидал лонг или инт, а получил строку, и тд.

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/event/EventCreateEditMapper.java
> +    public abstract Event map(EventCreateEditDto eventCreateEditDto, @MappingTarget Event event);
А зачем так? Либа позволяет писать просто:

Event toEvent(EventDto eventDto) - и всё. Это всё, что мапстракту нужно)

2024-07-13 02:39 UTC, pablo023 commented on src/main/java/school/faang/user_service/valitator/event/EventCreateEditValidator.java
> +    }
Лучше не создавать god-method, который как будто бы всё прям делает. Логика будет расти, фичи добавляться, и этот метод разжиреет до нечитаемости.

2024-07-20 17:48 UTC, pablo023 requested changes

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/event/WriteEventDtoToEventMapper.java
> +    @Mappings({
Mappings не обязательно, можешь просто вешать один маппинг за другим.

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/event/WriteEventDtoToEventMapper.java
> +    }
Не надо нуллы кидать вообще нигде и вообще никогда. То, что нулл в джаве есть - это антипаттерн на уровне языка программирования вообще. Но коль уж он есть, всегда избегай того, чтобы он откуда-то возвращался. Хэндли ситуации с нуллом, не возвращай его.

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .orElseThrow(() -> new DataValidationException("Event not found"));
Такое сообщение ни о чём не говорит, никак не поможет найти ошибку и исправить её. Хотя бы нужен айдишник. Я бы сюда добавил еще логгер, и написал бы что-то типа такого

log.error(что не нашел, с какими данными, в каком сервисе, в каком методе)

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    public List<ReadEvetDto> findAllByFilter(EventFilterDto eventFilterDto) {
Transactional, readOnly = true

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        Event entity = repository.findById(id).orElseThrow(() -> new DataValidationException("Event not found"));
Какой эвент не нашелся?

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private final EventRepository repository;
Почему просто repository? У нас когда-то может появиться тут еще один репозиторий, и надо будет идти править в каждом месте, чтобы разграничивать и понимать с каким работаем? Идея же сама предлагает назвать такой объект eventRepository

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/valitator/event/WriteEventValidator.java
> +
checkTitle*

2024-07-20 17:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/valitator/event/WriteEventValidator.java
> +        return fieldName + " не может быть пустым";
Let's try to use more of English, ok?

2024-07-23 01:01 UTC, pablo023 approved these changes
Окей, мержим)

2024-07-23 01:01 UTC, merged