Feature bjs2 15932
CorporationX/user_service pull request #1162
Opened 2024-07-05 16:48 UTC by grisatkac

2024-07-06 19:50 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    public ResponseEntity<SkillDto> create(@Validated @RequestBody SkillDto skillRequest) {
Можем ли использовать только @ Validated над классом, а @ Valid убрать?

2024-07-06 19:50 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        if (userId == null) {
Если примитив принимать, то проверку можно не делать

2024-07-06 19:50 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +    public void isUserExistsById(long id) {
Поменяем сигнатуру метода? Сейчас ничего не возвращает, больше на check похоже.
Ну или boolean возвращать

2024-07-06 19:50 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +            throw new DataValidationException(String.format("Skill with %s doesn't exist", skill.getId()));
Не совсем понял что происходит))
Проверяем существует ли скилл по title в бд. Если есть, то выбрасываем ошибку, что скилл с таким id не существует?
Как минимум в ошибке надо прописать данные, которые проверялись)

2024-07-07 16:16 UTC, vanekJpeg requested changes

2024-07-07 16:16 UTC, vanekJpeg commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +        return new ResponseEntity<>(skillResponse, HttpStatus.CREATED);
возвращай дто, а не ResponseEntity

2024-07-07 16:16 UTC, vanekJpeg commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        if (!skill.isPresent()) {
лучше используй isEmpty()

2024-07-07 16:16 UTC, vanekJpeg commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +        Optional<SkillDto> acquiredSkill = skillService.acquireSkillFromOffers(skillId, userId);
перекинь логику получения объекта из Optional в сервис, а логику обработки ошибок на ExceptionHandler, почитай про него, норм тема, или подсмотри как его реализовал  Евгений в этом пул реквесте https://github.com/CorporationX/user_service/pull/1171

2024-07-07 16:16 UTC, vanekJpeg commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +            return Optional.of(skillMapper.toSkillDto(skill.get()));
передавай дто

2024-07-08 20:56 UTC, grisatkac commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +            throw new DataValidationException(String.format("Skill with %s doesn't exist", skill.getId()));
> Не совсем понял что происходит)) Проверяем существует ли скилл по title в бд. Если есть, то выбрасываем ошибку, что скилл с таким id не существует? Как минимум в ошибке надо прописать данные, которые проверялись)

написал лог ошибки, который запутал))
Если есть, то выбрасываем ошибку, что скилл с таким id не существует - да, именно так) буду исправлять тогда текст ошибки)

2024-07-08 20:56 UTC, grisatkac commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        if (userId == null) {
спасибо)

2024-07-08 20:57 UTC, grisatkac commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +    public void isUserExistsById(long id) {
понял, согласен)
буду менять, чтобы был булевский возвращаемый тип

2024-07-08 20:58 UTC, grisatkac commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        if (!skill.isPresent()) {
принял, спасибо)

2024-07-08 22:07 UTC, grisatkac commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +            return Optional.of(skillMapper.toSkillDto(skill.get()));
принято

2024-07-08 22:08 UTC, grisatkac commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +        Optional<SkillDto> acquiredSkill = skillService.acquireSkillFromOffers(skillId, userId);
спасибо)

2024-07-10 03:47 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        if (userId == null) {
А  если не примитив, то оно отлетать будет быстро, если там вдруг нулл))

2024-07-10 03:59 UTC, pablo023 requested changes
Красиво пишите. Валидацию перенеси в отдельный класс, и пропускаю)

2024-07-10 03:59 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
Глянь аннотацию DisplayName

2024-07-10 03:59 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/skillService/UserValidation.java
does*

2024-07-10 03:59 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/skillService/SkillValidation.java
doesUserExists*

2024-07-10 03:59 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        }
Было бы лучше, если бы у нас был какой-то класс отдельный для этого. Какой-то валидатор. Сделай пакет под него validator, и туда перемести это.

2024-07-10 06:09 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        if (userId == null) {
@pablo023  но оно на этапе контроллера отлетит же)

2024-07-15 10:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/skillService/SkillServiceImpl.java
> +        if (userId == null) {
> @pablo023 но оно на этапе контроллера отлетит же)

Так я об этом и говорю - если там лонг обертка, то он на этапе контроллера отлетать будет быстрее, и это хорошо)

2024-07-15 10:41 UTC, pablo023 approved these changes
Молодец, все красиво)

2024-07-15 10:41 UTC, merged