BJS2-15937: Стать ментором
CorporationX/user_service pull request #1171
Opened 2024-07-06 15:58 UTC by malkov34

2024-07-06 22:06 UTC, DROFEL commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> + * @author Evgenii Malkov
Imho, но зачем если гит тречит?

2024-07-06 22:11 UTC, DROFEL commented on src/main/java/school/faang/user_service/exception/mentorship/MentorshipExceptionHandler.java
> +    @ExceptionHandler(MentorshipNoSuchElementException.class)
Круто, возьму на вооружение)

2024-07-06 22:11 UTC, DROFEL approved these changes
LGTM👍

2024-07-07 07:12 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> + * @author Evgenii Malkov
Какого-то глубокого смысла в этом нет. У нас в компании по дефолту принято такие метки оставлять, поэтому во все проекты тянется стиль)) Я уже просто не замечаю, что idea проставляет

2024-07-07 16:07 UTC, vanekJpeg approved these changes
Красавчик)

2024-07-17 22:30 UTC, pablo023 requested changes
Есть баг, и мелкие замечания)

2024-07-17 22:30 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/mentorship/MentorshipMapper.java
> +    MentorshipUserDto toUserDto(User user);
Так может быть тогда создать UserDto, а не MentorshipUserDto? Или название метода исправить.

2024-07-17 22:30 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/impl/MentorshipServiceImpl.java
> +        mentorshipRepository.save(mentor);
А менти ты не сохраняешь в репозиторий, проапдейтив его релейшен с ментором.

2024-07-17 22:30 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/impl/MentorshipServiceImpl.java
> +    public boolean deleteMentorshipRelations(long mentorId, long menteeId) {
А зачем нам тут булеан?

2024-07-17 22:30 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    }
Ты тут забыл сохранить проапдейченого менти

2024-07-17 22:30 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public boolean deleteMentorshipRelations(long mentorId, long menteeId) {
Зачем нам здесь булеан? Это войд операция типичная

2024-07-17 22:30 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/service/MentorshipServiceTest.java
Глянь про аннотацию DisplayName

2024-07-18 06:09 UTC, malkov34 commented
> Есть баг, и мелкие замечания)

Поправил)

2024-07-21 03:16 UTC, merged