Feature BJS2-15936
CorporationX/user_service pull request #1172
Opened 2024-07-06 22:04 UTC by DROFEL

2024-07-07 08:09 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +            List<MentorshipRequestDto> requestsDto = requests.stream()
Мне кажется, лучше перенести в сервис логику по маппингу и возвращать в контроллер уже подготовленные данные

2024-07-07 08:09 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    public ResponseEntity<?> acceptRequest(@RequestParam long id) {
На уровне контроллера не нужна валидация?

2024-07-07 08:09 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +@Transactional
имхо, использование Transactional на отдельных методах дает больше вариативности управления и улучшает читаемость кода.
Либо повесить Trabsactional(readOnly = true) на весь класс, а в методах где требуется изменение состояния бд, переопределеять транзакцию

2024-07-07 08:09 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +            throw new IllegalArgumentException("Cannot request from yourself");
Заметил, что везде используется IllegalArgumentException. Предлагаю переопределить реализацию ошибки на кастомную, и перехватывать исключение. Так можно и от try-catch избавиться в контроллерах.
https://www.baeldung.com/exception-handling-for-rest-with-spring

2024-07-07 09:24 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        MentorshipRequest request = mentorshipRequestRepository.findById(id)
findById можно вынести в отдельный метод с обработкой ошибки. В rejectRequest тоже самое повторяется

2024-07-07 16:04 UTC, vanekJpeg commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    public ResponseEntity<?> getRequests(RequestFilterDto filter) {
Возвращай не ResponseEntity, а сам дто.
В остальных эндпойнтах тоже)

2024-07-07 16:04 UTC, vanekJpeg commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +                    .body(e.getMessage());
Возвращай тут дто, а ошибку обрабатывай при помощи exceptionHandler, почитай про него

2024-07-21 05:38 UTC, pablo023 requested changes

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    @PostMapping(path = "reject")
path = "/reject/{id}"

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    public MentorshipRequestDto requestMentorship( @RequestBody MentorshipRequestDto mentorshipRequestDto) {
После открывающей скобки для параметров, пробел не нужен

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/mentorship/MentorshipRequestDto.java
> +    String description;
сюда можно NotBlank

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        }
Вот это всё лучше вынести в отдельный класс, который будет заниматься валидацией. Можно создать пакет validation, и туда его поместить. А каждая из вот этих проверок, будет отдельным его методом, которые здесь можно вызвать. Будет почище сильно, и не позволит разростаться методам.

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +            throw new NoSuchElementException("One or both users not found");
В целом это костыльный такой способ. Проще можно сделать, просто сделав два Optional, и проверив потом - пустые ли они

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +                .getId();
Я бы эти проверки на дто запускал, т.к. если отлетит - сэкономим на выполнении операции маппинга. А данные для валидации есть и в дто.

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +                .isAfter(cooldownThreshold)) {
Это костыль. Тебе нужно взять последний запрос на менторство, и проверить - прошло ли спустя даты, когда он был сделан, 3 месяца. Вот этот трюк с созданием текущей даты, отмоткой от неё трех месяцев - приходится упражнение в голове делать, чтобы понять, как работает. Давай проще сделаем) Просто получи запросы у пользователя, и проверь каждый из них - плохо, но просто. Получи отдельно запросы, вытащи самый поздний, и сравни - лучше. Вытащи сразу самый поздний - еще лучше.

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +                                                                                      .getId());
Что-то тут разъехалось.

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +                .setMentors(List.of(request.getReceiver()));
Хмм нет. Ты ему сеттишь новый лист, в котором ты размещаешь получателя запроса. Если там в реквесте уже список менторов- ты ту его затрешь.

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        return mentorshipRequestMapper.toDto(response);
Сюда бы еще добавить обновление сущностей пользователь, для менти и ментора. Засунуть ментора в менторы того, кто запрашивает, и добавить менти в список менти тому, кто запрашивает.

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        MentorshipRequest request = findMembershipById(id);
Это в валидатор

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        }
в отдельный класс валидатор.

2024-07-21 05:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        System.out.println(mentorshipRequestMapper.toDto(response));
Если ты хочешь логировать, давай делать правильно это) Почитай про аннотацию Slf4j, и логгер log4j2. С помощью него логируют сейчас везде просто. Почитай как это работает, и про уровни логирования.

2024-07-28 02:33 UTC, pablo023 requested changes

2024-07-28 02:33 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImplTest.java
> +    @BeforeEach
Уверен, что надо BeforeEach, а не BeforeAll?

2024-07-28 02:33 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImplTest.java
Ознакомься с аннотацией DisplayName

2024-07-28 02:33 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        return mentorshipRequestMapper.toDto(response);
Юзеров надо из базы вытащить кто кому ментор, кто кому менти, обновить эти состояния, и сохранить в базу.

2024-07-28 06:46 UTC, DROFEL commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        MentorshipRequest request = findMembershipById(id);
Это не валидатор, просто рапер репозитория

2024-07-28 06:46 UTC, DROFEL commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +                .getId();
у них вроде никакой валидации нету, просто геттеры

2024-07-28 06:46 UTC, DROFEL commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +                .isAfter(cooldownThreshold)) {
я тут вроде так и делаю. Беру последний реквест в дб и проверяю если он был в последние 3 месяца

2024-07-28 06:46 UTC, DROFEL commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        System.out.println(mentorshipRequestMapper.toDto(response));
Забыл убрать)

2024-07-28 06:46 UTC, DROFEL commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java
> +        return mentorshipRequestMapper.toDto(response);
Делается с 84 по 90 строки

2024-07-31 15:17 UTC, pablo023 approved these changes

2024-07-31 15:17 UTC, merged