Написание рекомендации
CorporationX/user_service pull request #1177
Opened 2024-07-07 17:05 UTC by legionerkz

Implemented all necessary classes

2024-07-08 06:44 UTC, malkov34 commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +        , unmappedTargetPolicy = ReportingPolicy.IGNORE
запятые уехали)

2024-07-08 06:44 UTC, malkov34 commented on src/main/java/school/faang/user_service/mapper/SkillOfferMapper.java
> +    //@Named("toSkillOfferDtoList")
Не должно попадать на ревью)

2024-07-08 06:44 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private int PAGEABLE_PAGE_PARAMETER;
Ну тут либо camelCase, либо как константу использовать нужно. Нечто среднее получилось))

2024-07-08 06:44 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    public void deleteRecommendation(long id) {
Уместна ли будет проверка на положительное значение id в контроллере?

2024-07-08 06:44 UTC, malkov34 commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    default SkillOfferDto skillOfferToDto (SkillOffer skillOffer) {
Если уж начали использовать SkillMapper внутри RecomendationMapper, может есть возможность объединить их в один интерфейс? Если логически и технически ничего не мешает

2024-07-21 03:15 UTC, pablo023 requested changes
Сорян, что подождать пришлось

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +    @NonNull
Можно NotBlank лучше даже. Она проверяет и на нулл, и на то, что поле не пустое.

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/RecommendationValidator.java
> +    public void validateRecommendation(RecommendationDto recommendationDto) {
Этот метод валидирует не рекомендацию, а проверяет лишь, что поле контент не пустое. Будет уместнее назвать его как-то в соответствии с тем, что он именно это и делает. К тому же, если ты в RecommendationDto поставишь над полем content аннотацию NotBlank, тебе вот эта валидация вообще не понадобится, т.к. аннотацией Valid в контроллере ты будешь сразу проверять это условие.

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private int PAGEABLE_PAGE_PARAMETER;
согласен)

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/RecommendationValidator.java
> +    public void validateBeforeAction(RecommendationDto recommendationDto) {
Это название вообще никак не отображает того, что здесь происходит. Чтобы программист другой понял примерно - ему обязательно придется идти сюда, читать, и разбираться. Названия методов должны описывать то, что они делают.

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/RecommendationValidator.java
> +    private void validateSkillRepository(RecommendationDto recommendationDto) {
метод буквально валидирует репозиторий. Это не то, что здесь происходит. Ты здесь проверяешь, есть ли у тебя скиллы в базе данных. validateSkillExistence может подойдет?

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private List<Skill> getReceiverSkills(long receiverId) {
Почему receiverSkills? Если этот метод вызывать на айдишнике реквестера, он не сработает? Сработает. Так почему у нас название про ресивера?

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/RecommendationValidator.java
> +    public void validateById(long id) {
А что validate то? К тому же, тебя этот метод - буквально existsById, который уже написан в репозитории.

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +            }
Никогда старайся не апдейтить базу данных в цикле. Если у тебя тут будет операция на тысячи, десятки тысяч, и тд. итераций, ты базу будешь нагружать, и она будет проседать по производительности. Формируй список, и разом обновляй базу. Старайся всегда следовать такому подходу.

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public RecommendationDto update(RecommendationDto recommendationDto) {
апдейт что?)

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        List<Recommendation> recommendations = pageRecommendations.getContent();
А для чего тут вообще этот Pageable? Тебе нужно по заданию взять юзера, вытащить у него полученные рекомендации, промаппить их в айдишники, которые содержит класс дто, и вернуть просто. Чет тут не очень по задаче происходит. Ты его ведь тестить хотел, и у тебя ломалось там оно постоянно? Тебе не нужен здесь этот Pageble.

2024-07-21 03:15 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        List<Recommendation> recommendations = pageRecommendations.getContent();
Аналогично

2024-08-01 03:30 UTC, legionerkz commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        List<Recommendation> recommendations = pageRecommendations.getContent();
спасибо! сделал

2024-08-01 03:30 UTC, legionerkz commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        List<Recommendation> recommendations = pageRecommendations.getContent();
спасибо! сделал

2024-08-01 03:30 UTC, legionerkz commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public RecommendationDto update(RecommendationDto recommendationDto) {
исправил

2024-08-01 03:30 UTC, legionerkz commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +            }
обновил

2024-08-01 03:30 UTC, legionerkz commented on src/main/java/school/faang/user_service/validator/RecommendationValidator.java
> +    public void validateById(long id) {
убрал

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    public RecommendationDto updateRecommendation(@PathVariable long recommendationID, @Valid RecommendationDto updatedDto) {
ну так а.. ты тестировал?) 
у тебя в маппинге recommendationId, а тут recommendationID

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    public void deleteRecommendation(long id) {
ну, это не особо важно нам проверять, потому что рекомендации с айди -5 просто не будет в бд
Соответственно, и ошибки какой-то серьезной тоже не будет

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    @GetMapping("/{recieverId}/receiver")
я бы наоборот написала тут 
сначала что это, а потом конкретно какое: /receiver/{recieverId}

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +    @NotBlank
а почему только над этим полем валидация? остальные мы не хотим отвалидировать сразу? хотя бы на то, что они заполнены

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/exception/DataValidationException.java
> +    public DataValidationException(String message) {
ну получилось вот два конструктора в одном классе 
а точно нам нужно два конструктора? 
я рекомендую привести формирование ошибок к единому стилю в репозиотрии, чтобы было легче поддерживать

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/exceptions/DataValidationException.java
> +import java.util.zip.DataFormatException;
а это что?

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/exceptions/DataValidationException.java
> +    public DataValidationException(String message, Throwable cause) {
то же, что выше 
два конструктора - сложно поддерживать

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +import org.springframework.stereotype.Service;
не используются

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +import java.util.Optional;
не используется

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public RecommendationDto createRecommendational(RecommendationDto recommendationDto) {
createRecommendation

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/RecommendationValidator.java
> +                throw new EntityNotFoundException(errorMessage);
Смотрииии)
Мы вот тут работает с каким-то конкретным скиллом - хотим пойти и узнать, а Skill такой имеется или нет.
Когда мы работаем с сущность Skill, мы должны использовать SkillService для инкапсуляции работы со скиллом именно в классе SkillService. Так мы сможем уйти от дублирования код и переиспользвоать один и тот же метод во всех местах, где нам понадобится.

Создай SkillService, если его еще нет и перетащи вот этот код туда. Вызов метода репозитория, бросание ошибки, если не найдена сущность и логирование)

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        User user = userRepository.findById(receiverId).orElseThrow(
этот код должен быть в userService 
обоснование есть в валидаторе на примере Skill

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        return user.getSkills().stream().map(Skill::getId).toList();
а вот эту логику можно уже и тут оставить, в этом классе

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        boolean authorIdIdExist = userSkillGuaranteeRepository.existsById(authorId);
Давай разберемся, как это работает 
Таблица user_skill_guarantee содержит 4 поля: id, receiverId, skillId, authorId

В JpaRepository есть дефолтный метод existsById, который ты тут используешь. Этот метод проверяет существование сущности в этой таблице по айди этой сущности. У сущности есть конкретный айдишник - это поле id. Все остальные айдишники, типа авторАйди - это ссылки на данные их других таблиц. Например, authorId - это просто айди пользователя. Но не скилл-гарантии. 

Поэтому чтобы тебе проверить, есть ли такая гарантия уже в бд, тебе надо найти в таблице user_skill_guarantee ОДНУ запись с такими ресивером, скиллом и автором, а не использовать эти айдишники по одному как айдишники сущности)

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        List<SkillOfferDto> skillOfferDtoList = recommendationDto.getSkillOffers();
Когда вот так делаешь - достаешь из объекта какой-то список и кладешь его в новый список, то в памяти создается новый массив для хранения вот этих скилл-офферов. То есть у тебя уже есть список, который лежит recommendationDto.getSkillOffers(), а ты его берешь и просто перекладываешь в новый, как будто бы просто копируя данные из одного места в другое. 

В for на 65 сразу просто пиши recommendationDto.getSkillOffers() и не выноси в отедльный список

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +                .orElseThrow(() -> new DataValidationException("Couldn't find the user in the system"));
это в юзер сервис

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +                .orElseThrow(() -> new DataValidationException("Couldn't find the skill in the system"));
это в скилл сервис

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +                .orElseThrow(() -> new DataValidationException("Couldn't find the guarantor in the system"));
это тоже вызов метода из userService просто с другим параметром

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/RecommendationValidator.java
> +            if (!skillRepository.existsById(skillOfferId)) {
это в скилл сервис переносим

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        skillOfferRepository.deleteAllByRecommendationId(recommendationId);
Почему? 
Каждый раз, когда обновляем рекомендацию, мы обязательно удаляем скилл офферс? Это странно

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        saveSkillOffers(recommendationDto);
чтобы тебе обновить SkillOffers, тебе нужно каждый из них получить из базы по id и заменить их поля на те, которые тебе пришли. Удалять ничего не нужно. Если ты удаляешь, то данные теряются и заменяются новыми.
Это неправильно с точки зрения консистентности данных. Получается, мы не обновили старое, а просто убрали старое, а на его место новое поставили. Типа, я хочу дома обои переклеить, и вместо того, чтобы убрать старые и наклеить новые, я просто снесу старую стену и новую построю))

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        recommendationValidator.recommendationExist(id);
метод репозитория deleteById удалить что-то из базы только в том случае, если такая запись там есть. Если ее нет, то ничего не произойдет. Поэтому на существование перед удалением можно не проверять - это безопасная операция

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        User user = userRepository.findById(receiverId).orElseThrow(()->
это в юзер сервис

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        User user = userRepository.findById(authorId).orElseThrow(()->
это в юзер репозиторий

2024-08-02 12:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +}
в целом замечание ко всему классу: публичные методы пишем первыми, приватные - внизу 

Основную логику должно быть видно сразу, а вспомогательную можно и спрятать поглубже

2024-08-31 00:49 UTC, pablo023 commented
Тут куча комментов, по которым нет правок, и конфликты.

2024-12-21 21:08 UTC, closed without merging