Feature bjs2 15550
CorporationX/user_service pull request #1180
Opened 2024-07-07 19:21 UTC by GevorgSogomonian

Created RecommendationRequestController
Created RecommendationRequestService

Created RecommendationRequestDto, RejectionDto, RequestFilterDto
Created RecommendationRequestMapper
Created RequestFilter interface and implementations: RequestReceiverIdFilter, RequestRequesterIdFilter, RequestSkillsFilter and RequestStatusFilter

Created unit tests for RecommendationRequestController and RecommendationRequestService

2024-07-10 03:24 UTC, pablo023 requested changes
Поправьте.

2024-07-10 03:24 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestDtoValidator.java
> +    public void validateAll(RecommendationRequestDto recommendationRequestDto) {
Так себе метод. Его постоянно дописывать надо будет, и он будет расти. Это не гуд, это - код, который подвержен изменению, потом еще тесты идти переписывать под него, ойх... Лучше такие не писать вообще)

2024-07-10 03:24 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestRepositoryValidator.java
Ты назвал этот класс, как будто он валидирует репозиторий, но по факту он валидирует айдишник, на предмет присуствтия в базе пользователя с таким айдишником. Это не одно и то же.

2024-07-10 03:33 UTC, pablo023 requested changes
В целом, хорошо, но есть пара деталей)

2024-07-10 03:33 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestDtoValidator.java
Этот класс должен быть в пакете validtor, не service

2024-07-10 03:33 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestDtoValidator.validateAll(recommendationRequestDto);
В этом методе нужна только валидация на непустое сообщение.

2024-07-10 03:33 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestDto.getSkills().forEach(skill -> skillRequestRepository.create(Id, skill.getId()));
По задаче, нужно проверить, что скиллы существуют в базе, а не добавять их туда.

2024-07-10 03:33 UTC, pablo023 commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
Глянь аннотацию для тестов DisplayName

2024-07-10 03:33 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
Глянь аннотации ResponseStatus и RequestMapping

2024-07-12 05:54 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestDtoValidator.java
> +    public void validateAll(RecommendationRequestDto recommendationRequestDto) {
Исправил

2024-07-12 05:55 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestRepositoryValidator.java
Исправил

2024-07-12 05:58 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestDtoValidator.java
Исправил

2024-07-12 06:01 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestDtoValidator.validateAll(recommendationRequestDto);
<img width="754" alt="Снимок экрана 2024-07-12 в 09 00 31" src="https://github.com/user-attachments/assets/fb57dbe0-f4f0-4acc-a5c2-91479ad1ade1">

2024-07-12 06:03 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestDtoValidator.validateAll(recommendationRequestDto);
Единственное что я исправил это не стал проверять на непустое сообщение в контроллере, а вынес всю валидацию в service

2024-07-12 06:06 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestDto.getSkills().forEach(skill -> skillRequestRepository.create(Id, skill.getId()));
<img width="662" alt="Снимок экрана 2024-07-12 в 09 06 18" src="https://github.com/user-attachments/assets/f480cdf2-1d4a-4017-9572-1fb60c96966f">

2024-07-12 06:07 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestDto.getSkills().forEach(skill -> skillRequestRepository.create(Id, skill.getId()));
Вроде как и сохранить нужно

2024-07-12 06:12 UTC, GevorgSogomonian commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
Исправил

2024-07-12 09:17 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
Добавил аннотации ResponseStatus и RequestMapping

2024-07-17 13:14 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestDtoValidator.validateAll(recommendationRequestDto);
Сори, не туда посмотрел. Ты прав.

2024-07-17 13:15 UTC, pablo023 approved these changes
Окей. Детали вижу добавил. То, что я погнал там - откомментил, сори) Молодец, мержим.

2024-07-17 13:15 UTC, merged