Feature bjs2 15567
CorporationX/user_service pull request #1192
Opened 2024-07-09 07:55 UTC by YPG0

2024-07-09 11:01 UTC, kpzxpf commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Мне кажется, что здесь для проверки длины и на пустоту названия лучше использовать аннотацию @Valid, а остальное перенести в слой сервиса

2024-07-09 11:01 UTC, kpzxpf commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +            throw new NullPointerException("Goal is null");
Если IsBlank() вернет true, то title не обязательно будет null

StringUtils.isBlank(null)      = true
StringUtils.isBlank("")        = true
StringUtils.isBlank(" ")       = true
StringUtils.isBlank("bob")     = false
StringUtils.isBlank("  bob  ") = false

2024-07-09 11:01 UTC, kpzxpf commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
Валидацию лучше вынести в отдельный класс-валидатор

2024-07-09 19:10 UTC, Kostahe commented on src/main/java/school/faang/user_service/UserServiceApplication.java
> + package school.faang.user_service;
Может, это мелочь, но всё равно зачем здесь пробел?

2024-07-09 19:10 UTC, Kostahe commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        }
Хотя можно использовать NullPointerException, но не в данном контексте. Рекомендую вместо этого использовать IllegalArgumentException

2024-07-09 19:10 UTC, Kostahe commented on src/main/java/school/faang/user_service/dto/GoalDto.java
> +    private Long parentId;
Здесь мне кажется, что нет необходимости использовать тип Long, потому что parentId не должен быть null

2024-07-09 19:10 UTC, Kostahe commented on src/test/java/school/faang/user_service/service/controller/goal/GoalControllerTest.java
> +}
Посмотри про аннотацию `@BeforeEach`

2024-07-09 19:10 UTC, Kostahe commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private final int MAX_NUMBERS_GOAL_USER = 3;
Мне кажется, здесь можно использовать `static`

2024-07-09 19:10 UTC, Kostahe commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Не надо Long с аннотацией использовать `@NonNull`, просто можно исползовать long

2024-07-09 19:10 UTC, Kostahe commented on src/test/java/school/faang/user_service/service/controller/goal/GoalServiceTest.java
> +    GoalService goalService;
Тут нету причины исползовать default видимость, поменяй на private

2024-07-09 19:10 UTC, Kostahe commented on src/test/java/school/faang/user_service/service/controller/goal/GoalControllerTest.java
> +//        assertThrows(NullPointerException.class, () -> goalController.updateGoal(goalId, goal));
Комменты не надо пушить и зачем этот метод, если тут коммент?

2024-07-10 05:34 UTC, YPG0 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Хорошо, спасибо

2024-07-10 05:44 UTC, YPG0 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +            throw new NullPointerException("Goal is null");
Перенес в валидатор там поправил

2024-07-10 05:50 UTC, YPG0 commented on src/main/java/school/faang/user_service/UserServiceApplication.java
> + package school.faang.user_service;
Даже если и мелочь то не красиво с ней. Случайно как то появился даже не увидел

2024-07-10 05:51 UTC, YPG0 commented on src/test/java/school/faang/user_service/service/controller/goal/GoalControllerTest.java
> +}
Хорошо, спасибо

2024-07-10 06:01 UTC, YPG0 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        }
Хорошо. Пошел по другому переделал метод через valid

2024-07-10 06:03 UTC, YPG0 commented on src/test/java/school/faang/user_service/service/controller/goal/GoalServiceTest.java
> +    GoalService goalService;
Поправил

2024-07-10 06:06 UTC, YPG0 commented on src/test/java/school/faang/user_service/service/controller/goal/GoalControllerTest.java
> +//        assertThrows(NullPointerException.class, () -> goalController.updateGoal(goalId, goal));
Я просто не знаю какой из вариантов оставить, кто из них уместнее будет и сработает как надо

2024-07-23 01:43 UTC, pablo023 requested changes
Надо доработать.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    private final GoalControllerValidate validate;
validate - это глагол. "Проверить" переводится. Объект не может называться глаголом, это - существительное, валидатор. И не просто какой-то там, а controllerValidator, или goalControllerValidator.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +    default List<Long> map(List<Skill> skills) {
А что мап то?) Название метода должно суть передавать, из просто map, непонятно вообще, что тут список скиллов в их айдишники маппится.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void createGoal(@NonNull Long userId, @Valid Goal goal) {
Это не совсем по REST. У нас есть требование - мы пишем в соответствии с REST, что значит, что пользователь обязательно получает какой-то ответ. В данном случае нет ни HTTP ответа, ни какой-то информации о выполнении запроса. На каждом эндпоинте повесь аннотации ResponseStatus. Также сейчас уместно добавить сюда RequestMapping. И возвращаемым значением везде должны быть дто, как с контроллера, так и из сервиса

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void updateGoal(long goalId, GoalDto goal) {
не по рест

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
Тут контроллер и сервис не рестовые. Переделай, пожалуйста. И почитай про REST.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
В этом методе нет никакого смысла. Мы просто заворачиваем в слой абстракции одну строчку - вызов репозитория. В этом нет никакого смысла, т.к. нет ни большого кода, который прячем, нет изменения каких-то данных. Не нужно так)

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/validator/GoalServiceValidate.java
> +    }
Тут непонятно из названия, что метод этот делает. Здесь надо что-то в духе создания методов атомарных, с соблюдением принципа единой ответственности, которые может быть, будет иметь смысл все добавить потом в еще один метод. И то не факт. Если там собирается цепочка из таких методов 4 и более - имеет смысл их все добавить в один метод, чтобы кода не громозить в методе сервиса. В данном случае -не имеет точно это всё засовывать в validateCreateGoal. Этот метод, кстати, если и должен существовать, то принимать он в себя должен что-то одно - только Goal. И внутри уже строить нужную логику для валидации -дергать репозиторий, и тд. Методы, которые принимают много аргументов, как 4 в данном случае - это что-то, что точно можно декомпозировать. Если ты пишешь метод, который принимает более трех аргументов - подумай, то ли ты делаешь.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void createGoal(@NonNull Long userId, @Valid Goal goal) {
И принимать мы на вход должны dto, а не сам Goal. Тоже надо переделать.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
Переделай везде на прием и отдачу дто.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        validator.validateCreateGoal(userId, goal, countActiveUser, allGoalTitles);
Это должно происходить не так - гол ты передаешь в валидацию, и там ты можешь вытащить уже goalTitles. Это - валидационная часть логики, она не должна находиться в методе сервиса.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Этот метод неправильно работает. Ты принимаешь дто, в котором содержится информация, которой надо обновить какую-то цель в базе данных. Ты должен провалидировать дто, вытащить цель из базы, обновить её инфой из дто, и сохранить в базу. У тебя нет шага вытягивания из базы - ты просто из дто создаешь гол, и всё. Дальше ты скиллы добавляешь юзерам.

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private List<GoalDto> filters(Stream<Goal> goal, GoalFilterDto filters) {
filterGoals*

2024-07-23 01:43 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Тоже лишний слой абстракции.

2024-07-23 16:16 UTC, YPG0 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    private final GoalControllerValidate validate;
Поправил на goalControllerValidator

2024-07-23 16:16 UTC, YPG0 commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +    default List<Long> map(List<Skill> skills) {
Заменил на mapSkillToSkillsId

2024-07-23 16:16 UTC, YPG0 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void createGoal(@NonNull Long userId, @Valid Goal goal) {
Добавил ResponseStatus, переделал с RequestMapping, возвращаемые значения добавил

2024-07-23 16:16 UTC, YPG0 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void updateGoal(long goalId, GoalDto goal) {
+

2024-07-23 16:17 UTC, YPG0 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
Принял

2024-07-23 16:24 UTC, YPG0 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Убрал. Скорее всего тут был какой-то план и там изначально была не 1 строчка но в ходе изменения логики она осталась одинока, а окончательно выпилить упустил

2024-07-23 16:24 UTC, YPG0 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private List<GoalDto> filters(Stream<Goal> goal, GoalFilterDto filters) {
+

2024-07-23 16:24 UTC, YPG0 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Такая же ситуация

2024-08-06 15:55 UTC, YPG0 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Переделал метод

2024-08-06 15:58 UTC, YPG0 commented on src/main/java/school/faang/user_service/validator/GoalServiceValidate.java
> +    }
Переделал

2024-08-08 01:47 UTC, merged