BJS2-15950: [Experienced] Покупка премиум доступа
CorporationX/user_service pull request #1194
Opened 2024-07-09 15:18 UTC by malkov34

2024-07-18 04:12 UTC, pablo023 requested changes
В целом, хорошо. Мне бы хотелось, чтобы работа с платежами происходила в рамках EDD. Кафку бы сюда, например..

2024-07-18 04:12 UTC, pablo023 commented on src/main/java/school/faang/user_service/client/paymentService/model/PaymentStatus.java
А чего тут один статус всего?

2024-07-18 04:12 UTC, pablo023 commented on src/main/java/school/faang/user_service/client/paymentService/CurrencyService.java
> +        return price.multiply(paymentCurrency.getExchangeRate())
А что это за getExchangeRate? Не могу понять, в модели Currency не вижу этого метода и поля.

2024-07-18 04:12 UTC, pablo023 commented on src/main/java/school/faang/user_service/client/paymentService/PaymentServiceClient.java
> +        long paymentNumber = random.nextLong(0, Long.MAX_VALUE);
Это не совсем так, как нужно, ведь.. У нас же это выступает, по сути, айдишником, либо хэшом каким-то транзакции. Кстати говоря, и аннотация соотвествующая здесь была бы уместна. Текущая имплементация не дает гарантий уникальности

2024-07-18 04:12 UTC, pablo023 commented on src/main/java/school/faang/user_service/repository/promotion/LinkEventPromotionRepository.java
А почему линк?)

2024-07-18 04:12 UTC, pablo023 commented on src/main/resources/db/changelog/changeset/user_V008__init_promotion.sql
> +    id bigserial primary key,
Нужен тут именно бигсериал для типа промоушенов?

2024-07-18 04:12 UTC, pablo023 commented on src/main/resources/db/changelog/changeset/user_V008__init_promotion.sql
> +    description varchar(100),
Тут констрейнт не нужен никакой?

2024-07-18 04:12 UTC, pablo023 commented on src/main/resources/db/changelog/changeset/user_V008__init_promotion.sql
Я бы это написал хотя бы двумя файлами. Такой большой ни к чему, лучше отдельных поменьше, и называть в соотвествии с тем, что происходит конкретно в одной миграции

2024-07-18 04:12 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        paymentClient.sendPayment(userId, period.getPrice());
Мне кажется, тут порядок не совсем правильный. У тебя метод проверяет ведь - есть ли премиум в базе, по айди юзера. Кстати, то - что он если уже есть, то отлетает метод - тоже неправильно. Если человек купил премиум, почему он еще один не может купить? Так или иначе, ты сохраняешь в репозиторий, а потом проводишь оплату. Она может свалиться, а в репу ты уже сохранил. То, что это - в рамках транзакции происходит - не значит, что так имеет смысл оставлять, имхо.

2024-07-18 04:12 UTC, pablo023 commented on src/main/java/school/faang/user_service/client/paymentService/PaymentServiceClient.java
> +    private final PaymentServiceFeignClient client;
feignClient*

2024-07-18 06:14 UTC, malkov34 commented on src/main/java/school/faang/user_service/client/paymentService/model/PaymentStatus.java
> А чего тут один статус всего?

Я это из PaymentService перетащил, чтобы ответ формировать.
Могу там тоже обновить значения статусов

2024-07-18 06:16 UTC, malkov34 commented on src/main/java/school/faang/user_service/client/paymentService/CurrencyService.java
> +        return price.multiply(paymentCurrency.getExchangeRate())
> А что это за getExchangeRate? Не могу понять, в модели Currency не вижу этого метода и поля.

А оно есть) Это обменный курс по отношению к доллару
https://github.com/CorporationX/user_service/pull/1194/files#diff-2930f0e24f5c0e6184d515655be362a3ac3b65d3d38af1d11ea1ba34c0edefddR27

2024-07-18 06:16 UTC, malkov34 commented on src/main/java/school/faang/user_service/client/paymentService/PaymentServiceClient.java
> +        long paymentNumber = random.nextLong(0, Long.MAX_VALUE);
> Это не совсем так, как нужно, ведь.. У нас же это выступает, по сути, айдишником, либо хэшом каким-то транзакции. Кстати говоря, и аннотация соотвествующая здесь была бы уместна. Текущая имплементация не дает гарантий уникальности

Согласен, к этому вопрос был в questions. Переделаю)

2024-07-18 06:22 UTC, malkov34 commented on src/main/java/school/faang/user_service/repository/promotion/LinkEventPromotionRepository.java
> А почему линк?)

Таблица связи события и промоушена.
Как-то в привычку вошло по своим проектам явно Link обозначать, для понимания что что-то линкуется)

А вообще, я с jpa не работал до этого, везде был Jooq
Как по мне, он конечно приятнее))) Сам составляешь запрос какой нужен, никакие сущности описывать не надо) DSL context заинжектил и работаешь)

2024-07-18 06:23 UTC, malkov34 commented on src/main/resources/db/changelog/changeset/user_V008__init_promotion.sql
> +    id bigserial primary key,
> Нужен тут именно бигсериал для типа промоушенов?

serial достаточно будет

2024-07-18 06:23 UTC, malkov34 commented on src/main/resources/db/changelog/changeset/user_V008__init_promotion.sql
> +    description varchar(100),
> Тут констрейнт не нужен никакой?

Не думаю, это ведь просто описание

2024-07-19 16:34 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        paymentClient.sendPayment(userId, period.getPrice());
> Мне кажется, тут порядок не совсем правильный. У тебя метод проверяет ведь - есть ли премиум в базе, по айди юзера. Кстати, то - что он если уже есть, то отлетает метод - тоже неправильно. Если человек купил премиум, почему он еще один не может купить? Так или иначе, ты сохраняешь в репозиторий, а потом проводишь оплату. Она может свалиться, а в репу ты уже сохранил. То, что это - в рамках транзакции происходит - не значит, что так имеет смысл оставлять, имхо.

Согласен, что нелогично сначала сохранять, а потом отправлять. Но если оплата свалится, то транзакция не будет закоммичена, изменений в бд не будет. 
Но, в любом случае, надо переделать

2024-07-19 16:45 UTC, malkov34 commented
> В целом, хорошо. Мне бы хотелось, чтобы работа с платежами происходила в рамках EDD. Кафку бы сюда, например..

Этот момент хотелось бы обсудить

2024-12-21 21:08 UTC, closed without merging