centaur-master-bc5-future-BJS2-15933
CorporationX/user_service pull request #1203
Opened 2024-07-10 16:33 UTC by Nikita2768

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public ResponseEntity<RecommendationRequestDto> getRecommendationRequest(long id) {
Не критично, но надо придти к общему знаменателю по возвращаемому значению.
Ребята в основном dto возвращают

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public ResponseEntity<RecommendationRequestDto> getRecommendationRequest(long id) {
И ещё отметил бы валидацию id на этапе контроллера

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    private static final String ALL_REQUESTS_FILTER = "/requests-filter";
В маппинге не обязательно filter дописывать. С учетом того, что у тебя больше нет методов, которые возвращают список всех requests без фильтра.
При наличии правильной документации фронтенд разработчик будет знать о возможности фильтрации

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public ResponseEntity<List<RecommendationRequestDto>> getRecommendationRequests(RequestFilterDto filter) {
Контроллер отработает, если вызвать без фильтров?

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +        return skillRequests.stream()
попробуй в SkillRequestMapper добавить методы для обработки to**List**Dto и to**List**EntityDto
Реализация должна автоматически сгенериться и в RecommendationRequestMapper не надо будем с стримом работать.
 
 ++ переименовал бы сам метод, добавив List для лучшего восприятия

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +            throw new NoSuchElementException("Not found RequestRecommendation for id" + id);
Какая ошибка вернется пользователю из контроллера?
Возможно, стоит обработать как кастомную ошибку +  выводить сообщение в логах через общий метод.
Дублирование строки с ошибкой - тоже дублирование и ни есть хорошо)

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +            log.error("Not found RequestRecommendation for id" + id);
Можно использовать передачу переменных в текст напрямую, для удобства:
 log.error("Not found RequestRecommendation for id: {}", id);

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public RecommendationRequestDto getRequest(@Positive long id) {
Рекомендация:
Можно поставить транзацию только для чтения, чтобы убрать лишнюю нагрузку на бд.
Но так как мы сейчас работаем с spring jpa и он сам помечает все методы как транзакции только для чтения, то не обязательно

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public RecommendationRequestDto create(RecommendationRequestDto requestDto) {
Рекомендация:
Методы, которые изменяют состояние бд, стоит помечать @ Transactional
В данном случае, save уже под капотом её содержит, так что не обязательно добавлять.
Если бы помимо save в этом методе было ещё что-то изменяющее состояние в бд то без @ Transactional мы бы не обошлись

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        var listForFilteredRecommendation = allRequest.stream()
Вынесем в отдельный фильтр по образцу видео на платформе?

2024-07-11 07:00 UTC, malkov34 commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +        saveSkillRequest(requestDto);
класс валидатора не должен содержать логику работы с репозиторием. Следует вынести в сервис

2024-07-12 15:17 UTC, Nikita2768 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public ResponseEntity<List<RecommendationRequestDto>> getRecommendationRequests(RequestFilterDto filter) {
У фильтров должны быть поля null, а в сервисе такая ситация предусмотренна. Должно отработать нормально, до другого я не могу додуматься, но если у тебя есть идеи по улучшению, то я буду только рад его узнать

2024-07-15 13:50 UTC, legionerkz commented on src/main/java/school/faang/user_service/dto/RecommendationRequestDto.java
> +    @NotNull
NotBlank это же сильнее условие чем NotNull, поэтому можно не ставить NotNull. https://www.baeldung.com/java-bean-validation-not-null-empty-blank

2024-07-15 13:55 UTC, legionerkz commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +    @Mapping(source = "skills", target = "skills")
тут может лучше хранить список skillIds?

2024-07-15 14:06 UTC, legionerkz commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +                skill -> skillRequestRepository.create(requestDto.getId(), skill.getSkillId()));
а если skillId уже есть в репозитории?

2024-07-21 02:49 UTC, pablo023 requested changes
Ты не реализовал первую часть задачи, у тебя нет метода requestRecommendation в контроллере, который зовет метод create сервиса, и тд.

2024-07-21 02:49 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    private static final String ALL_REQUESTS_FILTER = "/requests";
FILTERED_REQUESTS

2024-07-21 02:49 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public RecommendationRequestDto rejectRequest(@RequestParam Long recommendationRequestId, @RequestParam String reasonReject) {
String rejectionReason*

2024-07-21 02:49 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    private final ValidatorForRecommendationRequestService validator;
recommendationServiceValidator*

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/exeptions/DataValidationException.java
> +package school.faang.user_service.exeptions;
пакеты называем в проекте в единственном числе 
посмотри те, которые уже были созданы заранее - на них можно ориентироваться) 
Ну и опечатку правим тут - exception

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/exeptions/DataValidationException.java
> +        super(message, cause);
Этот конструктор ты у себя в коде для ошибки не используешь 
Тогда может он и не нужен?  
Вообще старайся не создавать классы, методы или что-то еще "на будущее", потому что высока вероятность того, что это в будущем все-таки никто не будет использовать) Лучше добавить по факту необходимости потом, чем продумывать заранее ситуации, которые могут и не произойти)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/exeptions/NotFoundElement.java
> +        super(message, cause);
тут тот же коммент, что и в классе DataValidationException

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/exeptions/NotFoundElement.java
> +public class NotFoundElement extends RuntimeException{
Рекомендую назвать EntityNotFoundException, потому что Element - очень широкое понятие, как будто вообще все, что угодно)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    private static final String RECIPIENT_ID_NULL_OR_NEGATIVE = "recipientID apply in getRequest method was null or negative id: ";
В целом выносить тексты ошибок в отдельные поля - хорошая практика 
Но если мы делаем это именно в сервисе, то есть вероятность засорить наш код миллионом вот таких констант, если у нас будет много разных текстов ошибок 
Поэтому я рекомендую создать отдельный enum для такого, если не хочешь текстом именно в коде сервиса писать)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +    public void validatorData(RecommendationRequestDto requestDto) {
метод - это всегда какое-то действие 
Поэтому название метода должно быть глаголом) 

validateData, а можно и просто validate

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +        if (requestDto.getRequesterId() == requestDto.getRecieverId()) {
Если в объектах у тебя ссылочные типы, а не примитивы, сравнивать их нужно через equals, потому что == не может сравнить null

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +            log.error("Exception requester user can`t be reciever");
Смотри 
log.error говорит нам о том, что в приложении произошла какая-то важная ошибка, на которую разработчики приложения должны отреагировать и пойти ее чинить. 
Когда у нас просто упала валидация, нам незачем просить разработчиков пойти разобраться с этим, потому что это всего лишь обычная ситуация - пользователь ерундой занимается) 
Error используем в том случае, если что-то важное прям ломается и нам надо пойти проверить. А если это рандайм эксепшен из-за валидации, info будет достаточно)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +            throw new DataValidationException("Exception requester user can`t be reciever");
слово Exception в тексте ошибки можно уже не писать

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +public class ValidatorForRecommendationRequestService {
RecommendationRequestValidator название дай 
Нам не нужно разделять валидаторы по классам - отедльный для контроллера, отдельный для сервиса, потому что так будет сложно поддерживать код в будущем, когда все разрастется
Лучше делать валидаторы для конкретных сущностей

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +        if (!userRepository.existsById(requestDto.getRequesterId())) {
Смотрииии) 
Мы вот тут работает с каким-то конкретным пользователем - хотим пойти и узнать, а User такой имеется или нет. 
Когда мы работает с сущность User, мы должны использовать UserService для инкапсуляции работы с пользователем именно в классе UserService. Так мы сможем уйти от дублирования код и переиспользвоать один и тот же метод во всех местах, где нам понадобится. 

Создай UserService, если его еще нет и перетащи вот этот код туда. Вызов метода репозитория, бросание ошибки, если не найдена сущность и логирование)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +            ValidatorForRecommendationRequestService.log.error("User with id :" + requestDto.getRequesterId() + " doesn't exist!");
А зачем ты через класс обращаешься к логгеру? 
просто лог и все)

И по тексту ошибки: будет чуть профессиональнее использовать параметры: "User with id :{} doesn't exist!", requestDto.getRequesterId()

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +        if (!userRepository.existsById(requestDto.getRecieverId())) {
соответственно, когда вынесешь вот этот метод в юзер сервис, здесь тебе надо будет просто дважды вызвать этот метод сервиса с разными параметрами)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +            ValidatorForRecommendationRequestService.log.error("User with id :" + requestDto.getRequesterId() + " doesn't exist!");
логирование не через класс, лог инфо, сообщение через параметр

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +        if (requestRepository.existsById(requestDto.getId())) {
Ну нееет) 
Мы в этот вот метод валидации попадаем из метода create сервиса твоего 
в метод create нам прилетает совершенно новый объект, у которого еще нет айдишника, потому что айдишник заполняет не пользователь (ты же сам никогда не решаешь при логине в каком-нибудь сервисе, например, какой у тебя будет айдишник в их бд)
Так же и тут: когда реквест дто в метод приходит, там никакого айди нет, это поле проставится на уровне базы при создании новой сущности при сохранении. 

Таким образом, вот тут мы скорее всего получим либо налпоинтер, либо всегда будет получать уведомление, что такого реквеста нет. 
Как же нам проверить, что пользователь не заправшивал рекомендацию недавно? 

Используя метод findLatestPendingRequest репозитория RecommendationRequestRepository - этот метод тебе вернет все рекомендации, которые пользователь реквестер запросил у пользователя ресивера)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/validator/ValidatorForRecommendationRequestService.java
> +                ValidatorForRecommendationRequestService.log.error("6 months have passed since the last request was not made");
лог как везде

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/RecommendationRequestDto.java
> +    private List<SkillRequestDto> skillDtos;
только не SkillDtos, а SkillRequestDtos 
потому что тут не скиллы же лежат, а именно запросы)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public RecommendationRequestDto getRequest(@Positive long id) {
я бы Positive на контроллере навесила 
Ну и проверить бы - это работает?)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        }
всю вот эту конструкцию можно написать элегантнее через лямбду

RecommendationRequest request = requestRepository.findById(id)
.orElseThrow(() -> new NotFoundElement(NOT_FOUND_REQUEST_RECOMMENDATIONS + id));
return requestMapper.toDto(request);

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public RecommendationRequestDto rejectRequest(@Positive long id, String reason) {
Positive в контроллер? 
чтобы заранее проверить и не передавать сюда невалидное всякое

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        Optional<RecommendationRequest> request = requestRepository.findById(id);
вот тут пользуйся методо getRequest  
через него получай сущность, переиспользуй код

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +                var recommendationRequest = requestRepository.save(requestMapper.toEntity(requestDto));
хе-хе-хе 
смотри 

если ты используешь Transactional над методом, надо разобраться, а почему, собсно, ты это делаешь, и что тебе это дает) 

когда мы вешаем над методом эту аннотацию, спринг и хибер начинают заниматься поддержкой транзакции. Благодаря этому хибер сам будет заниматься обеспечением гарантий ACID. Конкретно в нашем случае важно то, что данные будут оставаться в консистентом состоянии. То есть, если мы получили какую-то сущность из базы данных (58 строчка), а потом начали с ней работать, то есть как-то ее изменять (59-63 строчки), то хибер обеспечит консистентность данных, то есть гарантирует нам, что все изменения, которые мы внесли в эту сущность отразятся в базе данных. 
Это значит, что мы можем не вызывать метод save руками, потому что хибер и так сохранит все обновления)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public List<RecommendationRequestDto> getRequests(Long receiverId, RequestFilterDto filters) {
я бы назвала метод getFilteredRequests

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        if (receiverId == null || receiverId < 0) {
я бы вот это в контроллере проверяла 
А еще лучше даже аннотациями на уровне дто

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/RequestFilterDto.java
> +    private List<SkillRequestDto> skills;
skillRequests

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/RequestFilterDto.java
> +    private LocalDateTime updatedAt;
как будто бы по этим полям фильтры не особо имеют смысл 
по created еще ок, но upated прям очень вряд ли

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/repository/recommendation/RecommendationRequestRepository.java
> +    List<RecommendationRequest> findAllRecommendationRequestForReceiver(long receiverId);
а точно тебе это нужно?) 

Опять же, если мы используем хибер, то есть ты уже сейчас решаешь как-то фильтровать данные на уровне базы, а не сервиса, то используй все возможности хибера. Мы этого не требуем сейчас, и в целом я бы приняла решение с получением всех запросов, и фильтрацией на уровне сервиса, но давай сделаем через бд, раз ты уже делаешь это тут. 

Смотри, хибер умеет строить квери на основе названия твоего метод в репозитории хехе 

Таким образом, ты хиберу можешь сказать "найди все по такому айди, вот с таким статусом,  и отсортируй по created_at" и написать это так: findByReceiverIdAndStatusOrderByCreatedAtDesc(long receiverId, int status);

хехе и все 
а query писать не надо) 
потестируй)

2024-08-02 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/service/recommendation/filter/impl/RequestSkillsFilter.java
> +public class RequestSkillsFilter implements RequestFilter {
ну да, но у тебя в фильтер дто куча полей, а реализации всего две))

2024-08-02 08:47 UTC, InnMish commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    private SkillRequestRepository skillRequestRepository = Mockito.mock(SkillRequestRepository.class);
используй аннотации Mock и InjectMocks на бины вместо этого)

2024-08-07 18:36 UTC, merged