BJS2 - 15573
CorporationX/user_service pull request #1208
Opened 2024-07-11 13:57 UTC by ravshanbekn

+ Добавил классы: UserController и UserService
+ Добавил каскадные операции на User
+ Использовал Spring Boot планировщик
+ Прописал тесты

2024-07-20 17:11 UTC, pablo023 requested changes

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/entity/User.java
> +    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, orphanRemoval = true)
А зачем нам вот такая логика тут? У нас релейшен один ко многим, что значит - один юзер может иметь отношение ко многим эвентам, как владелец. Вот этот каскад тайп = олл, говорит нам о том, что если, к примеру, удалится пользователь, то удалятся все эвенты, с которыми он когда-либо был связан в качестве владельца. Была ли такая логика в условии задачи? Я не вижу в ней смысла. Предположим, в нашем приложении кто-то организует событие, там есть участники, это событие связано может быть с проектами, моментами, чем-то еще, что в итоге устанавливает связь с другими пользователями, как участниками события. Организатор события решает удалить свой профиль, и все эвенты, где он был организатором - летят из базы. Для чего это?

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/entity/User.java
У меня есть сомнения насчет уместности CascadeType.ALL на многих полях. Скажешь для чего это сделал?

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/entity/goal/Goal.java
> +    @ToString.Exclude
А это зачем тут?

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +                eventRepository.save(event);
В цикле апдейтить базу - плохая идея. Чем больше ты в неё что-то делаешь, тем меньше перформанс. Ты же можешь одной операцией произвести запись для всех вот этих эвентов разом. Вообще, на будущее тебе - в цикле не трогай базу, думай о том, как её минимум раз за операцию трогать. И метод у тебя этот должен быть транзакционным, т.к. кусок может обновиться, кусок - нет, и всё, мир разрушится)

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +    private void stopPlannedEventActivities(User user) {
Я бы сделал это в 4 строки.

1) Вытащить запланированные эвенты.
2) Поставить им статус Cancelled
3) Сохранить их разом в базу
4) Выпилить юзеру запланированные эвенты

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +        ownedEvents.removeIf(event -> event.getStatus() == EventStatus.CANCELED);
Ты в памяти коллекцию просто почистил. Если ты хотел почистить её юзеру, хибер не поймёт этого, ты просто что-то в памяти создал, изменил, метод грохнулся и эта коллекция тоже. Для того, чтобы юзеру вот это сделать, надо вызывать на юзере, чистить, а потом сохранять его в базу.

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +                .peek(mentee -> mentorshipService.deleteMentor(mentee.getId(), user.getId())).toList();
Это нужно декомпозировать. Менти без ментора это посто user.getMentees(), не нужно туда дальше логику какую-то добавлять, которую не описывает название переменной.

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
Это должно происходить в рамках транзакции. И опять таки, не надо в цикле дергать базу по сто раз. Подумай о том, как разом тут навести порядок.

2024-07-20 17:11 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
Если сильно хочется, подумай и обоснуй как тут может пригодиться executorService.

2024-07-20 22:30 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/entity/User.java
> +    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, orphanRemoval = true)
```
@ManyToOne
@JoinColumn(name = "user_id", nullable = false)
private User owner;
```
Поле owner - not null. Когда тестировал через Postman я не мог удалить пользователя так как на него ссылались вот эти event, mentorshipRequest и т.д
Какое решение ты предлагаешь? GPT сказал так нормально будет :)

2024-07-20 22:32 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/entity/User.java
Многие поля имеют constraint nullable - false. 
Ну я подумал, если user'а нет тогда незачем его goals, mentorshipRequests, mentorships

2024-07-20 23:16 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/UserService.java
> +    private void stopPlannedEventActivities(User user) {
Вроде сделал

2024-07-20 23:23 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/UserService.java
> +        ownedEvents.removeIf(event -> event.getStatus() == EventStatus.CANCELED);
```
user.getOwnedEvents().removeIf(event -> event.getStatus() == EventStatus.CANCELED);
```
Так?

2024-07-21 00:03 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
Я переписал код, так, что удаляю всех не активных пользователей разом. Нужен ли executorService теперь?

2024-07-21 00:04 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/service/UserService.java
> +                eventRepository.save(event);
Эти методы приватные и я вызываю их внутри транзакционного метода. Так можно делать?
Или все же каждый метод пометить как @ Transactional а затем использовать?

2024-07-21 00:06 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/entity/goal/Goal.java
> +    @ToString.Exclude
При сборке ругалось)
Убрал

2024-07-21 00:09 UTC, ravshanbekn commented on src/main/java/school/faang/user_service/entity/User.java
> +    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, orphanRemoval = true)
Убрать?

2024-07-21 00:21 UTC, ravshanbekn commented
Вроде исправил, но не уверен все ли верно. Проверь еще раз пожалуйста

2024-07-23 01:50 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +        ownedEvents.removeIf(event -> event.getStatus() == EventStatus.CANCELED);
Да. И сохранить юзера потом

2024-07-23 01:50 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
На твоё усмотрение. Если пишешь под логику, что там может быть удаление тысяч или десятков тысяч пользователей разом - можно и с ним.

2024-07-23 01:51 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +                eventRepository.save(event);
У тебя приватный метод тогда либо выполнится до конца, либо отвалится, поток продолжит выполнение родительского метода, т.к. он нетранзакцонный.

2024-07-23 01:57 UTC, pablo023 commented on src/main/java/school/faang/user_service/entity/User.java
> +    @OneToMany(mappedBy = "owner", cascade = CascadeType.ALL, orphanRemoval = true)
Так задача то.. Не удалить, а деактивировать)

2024-07-24 13:32 UTC, pablo023 requested changes

2024-07-24 13:32 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserService.java
> +    private void stopPlannedEventActivities(User user) {
Почти норм. Добавь аннотацию Transcational.

2024-07-25 03:13 UTC, pablo023 commented
Пофикси конфликты, и мерджим

2024-07-25 20:27 UTC, ravshanbekn commented
Пофиксил конфликты

2024-07-31 13:56 UTC, pablo023 commented
Чеки сломались, надо чинить

2024-07-31 14:50 UTC, merged