Centaur bjs2 15941
CorporationX/user_service pull request #1218
Opened 2024-07-13 13:49 UTC by KateAle

фильтры не работают, найти ошибку не смогла

2024-07-21 05:52 UTC, pablo023 requested changes
Надо много поправить) И тесты не забывай писать, пожалуйста)

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +        }
Валидацию, если тебе она нужна, нужно выносить в отдельный класс. Его кладем в пакет validator, и там создаем класс с такими методами. Но в целом, конкретно вот здесь - у тебя только проверки полей сущности EventDto, на его поля - что они не null. Чтобы вот это вообще не писать, ты можешь использовать аннотацию NotNull, или NotBlank, для строк, прямо над полями в классе EventDto. А в параметрах метода контроллера, использовать аннотацию Valid. Таким образом проверки на нулл писать не придется вообще, и невалидные данные будут сами отлетать. Почитай про это в гугле, про аннотации эти.

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    private List<EventDto> getEventsByFilter(EventFilterDto filters){
Пробелы после фигурных скобок не забывай. Либо сочетание клавиш command + ctrl + L

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/filter/EventByOwnerFilter.java
> +                event.getOwner().getId()==(filters.getOwnerIdPattern()))
не ==, а .equals(). Почитай как equals() работает, и чем отличается от двойного равно "=="

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/EventMapper.java
> +    default List<EventDto> toDto(List<Event> events) {
toDtoList*

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/EventMapper.java
> +                .collect(Collectors.toList());
Ммм нет Кать. Ты должна из списка сущностей создать список дто. А ты просто создаешь список пустых дто, которые не имеют отношения к тому списку сущностей, который был сюда передан аргументом. У тебя из сущности должно создаться дто - урезанная версия сущности, но с оригинальными данными, как в сущности. У тебя создаются просто пустые.

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/EventMapper.java
> +    }
Аналогично.

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/EventMapper.java
> +//event.getId(), event.getTitle(), event.getStartDate(), event.getEndDate(), event.getOwner().getId(), event.getDescription(), event.getRelatedSkills(),event.getLocation(),event.getMaxAttendees()
Не оставляем это.

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +                .collect(Collectors.toList());
Такой же косяк как в EventMapper

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +}
Каааать)

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
Ну во первых, если уж ты делаешь методами вот такими валидацию, они должны быть приватными. Во вторых, это надо делать не в сервисе, а в отдельном классе, который будет только валидацией заниматься. Создай пакет validator в общем каталоге, на ровне с пакетами service, controller, и тд. Там создай класс, который валидировать будет, и тут им пользуйся.

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        } else {
В валидацию. И какого - такого?) Айдишник нужно добавить сюда. И давай будем использовать логирование. Почитай, пожалуйста, про аннотацию Slf4j, и что это такое. Что такое log4j тоже почитай.

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        eventRepository.deleteById(eventId);
Здесь тоже надо валидировать, что айдишник нормальный, и что такой эвент вообще в базе есть

2024-07-21 05:52 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        eventEntity.setEndDate(event.getEndDate());
Нет, не так. Тебе нужно вытащить эвент из базы по айдишнику, который ты передала, и из дто вытащить данные, которыми его надо проапдейтить. Тут ты делаешь не то)

2024-07-22 18:45 UTC, KateAle commented on src/main/java/school/faang/user_service/filter/EventByOwnerFilter.java
> +                event.getOwner().getId()==(filters.getOwnerIdPattern()))
мне среда в этом месте не дает ставить equals из-за объектов long, поэтому и пришлось ==

2024-07-28 02:38 UTC, pablo023 approved these changes
Я тут мелочь отметил. Вообще было бы нелохо это исправить, но ладно, пора мерджить уже.

2024-07-28 02:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .orElseThrow(() -> new ResourceNotFoundException("Событие не найдено"));
Не просто событие, а событие с определенным id, который сюда надо вписать. И надо это не только в эксепшен, но и в логи. С помощью аннотации Slf4j

2024-07-28 02:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        eventEntity.setDescription(eventDto.getDescription());
Так это логика маппера. Зачем рукой то это делаешь) Используй мапер.

2024-07-28 02:38 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        eventEntity.setMaxAttendees(eventDto.getMaxAttendees());
Ну и это тоже.

2024-07-28 02:46 UTC, pablo023 commented
У тебя CI сломался на сборке, в маппере проблема. Сделай git pull, исправь маппер, проверь, что работает, и делай новый пулл-реквест.

2024-07-31 15:19 UTC, merged