BJS2-15606 - "Интеграция с генератором случайных аватаров юзера"
CorporationX/user_service pull request #1291
Opened 2024-07-29 13:29 UTC by i7rincpane

Написал генератор автара посредством DiceBear ресурса, прикрутил аватара к пользователю и загрузил на локальное хранилище minio

2024-08-04 00:26 UTC, pablo023 requested changes
Выглядит неплохо почти. Но добавь стилей пожалуйста, и покажи мне на звонке как это работает у тебя

2024-08-04 00:26 UTC, pablo023 commented on src/main/resources/application.yaml
> +    adventurer
А где же остальные)

2024-08-04 00:26 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/user/DiceBearAvatarGenerator.java
> +                .queryParam("seed", key)
Ну тут у нас магическая строка появилась

2024-08-04 00:26 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                .orElseThrow();
На самом деле, это намного сложнее читать, чем если это делать без мап. Давай лучше не будем бз надобности функционально писать) Функциональное программирование может помогать нам, когда у нас есть логика, зависящая от параметров, и нам не охота создавать 10 методов под каждый параметр. а просто так - не надо лучше)

2024-08-06 14:08 UTC, i7rincpane commented on src/main/java/school/faang/user_service/service/user/DiceBearAvatarGenerator.java
> +                .queryParam("seed", key)
да, с параметрами как-то не гибко получается..

2024-12-21 21:08 UTC, closed without merging