Deactivate user | BJS2-15949
CorporationX/user_service pull request #1300
Opened 2024-08-01 05:36 UTC by DROFEL

2024-09-09 23:48 UTC, pablo023 requested changes

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/controller/UserController.java
> +    private final MentorshipService mentorshipServiceService;
Название)

2024-09-09 23:48 UTC, pablo023 commented on src/main/resources/application.yaml
> +    url: jdbc:postgresql://localhost:5433/postgres
Зачем мы тут это меняем? У команды он же подниматься перестанет тогда

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/eventService/EventServiceImpl.java
> +@Transactional
Это не очень практика - ставить Transactional над классом, т.к. не факт, что каждый метод в нём будет нуждаться.

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorshipService/MentorshipServiceImpl.java
> +        });
Так не пойдет. Этот метод называется деактивировать менторство, при этом тут происходит что-то помимо этого. Это нужно не комментить, а как ты и отметил - выносить логику в отдельный сервис, отдельным методом.

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/mentorshipService/MentorshipServiceImpl.java
> +            }
Вот так делать не нужно, непонятный флоу. Не нужно в принципе ретурнить из войд методов - непонятно зачем это. Если у тебя тот список, по которому ты итерироваться собрался, будет пустым, у тебя дальнейший код итак пропустится. В этих строчках нет нужды

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/userService/UserServiceImpl.java
> +//        goal is done by that person and remove, otherwise just update list
У тебя код должен сам себя описывать) Если без комментов в нем не разобраться - нужно чище и понятнее писать. Если всё итак понятно без комментов - они просто не нужны

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/userService/UserServiceImpl.java
> +            }
Это не нужно

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/userService/UserServiceImpl.java
> +
Эта логика должна быть в гол сервисе. Тут ей не место. Зови юзер сервисом гол сервис, и там выполняй логику по удалению целей, если в ней нет других участников, кроме деактивируемого юзера.

2024-09-09 23:48 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/userService/UserServiceImpl.java
> +            if(goal.getUsers().isEmpty()){
Тут пробелы после иф, и перед фигурной скобкой пропустил. Привыкай писать правильно. Если пока что тяжело - пользуйся сочетанием клавиш ctrl + alt + L

2024-09-09 23:49 UTC, pablo023 commented
У тебя сборка из-за скиллмаппера не проходит. Посмотри отчет вот тут из CI, исправь по комментам, и проверяй, что проект собирается, перед ПР.

2024-09-15 02:27 UTC, DROFEL commented on src/main/resources/application.yaml
> +    url: jdbc:postgresql://localhost:5433/postgres
Я 2 конекшина к постгресу раню поэтому тут поменял и случайно закомитил

2024-09-18 19:17 UTC, pablo023 approved these changes
Вот так уже лучше, да) Тут есть маленькие огрехи. Я аппрувлю это, и перевожу в done. Если хочешь - исправь их, и вмерж. Если нет - просто вмерж, т.к. задача долго уже висит, я не хочу из-за косметики только возвращать её)

2024-09-18 19:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        User user = userRepository.findById(userId).orElseThrow();
orElseThrow - что кидаем в противном случае?)

2024-09-18 19:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        eventRepository.deleteAllById(userEvents.stream().map(Event::getId).toList());
В данном случае мне достаточно легко прочитать, но в целом - практика плохая писать гусеницей вот так. Старайся разбивать на шаги больше.

2024-09-18 19:17 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        List<Long> goalIdsToBeDeleted = new ArrayList<>();
Вот это зачем?)

2024-12-21 21:14 UTC, closed without merging