Удаление просроченных премиум доступов
CorporationX/user_service pull request #1303
Opened 2024-08-02 03:39 UTC by legionerkz

Implemented task: delete expired premiums weekly.
Refactor project structure: Moved class files into corresponding packages. Deleted non-working tests

2024-08-08 01:35 UTC, pablo023 requested changes
Возвращаю из-за нейминга пакетов с большой буквы, это может сломать проект.

2024-08-08 01:35 UTC, pablo023 commented on src/main/java/school/faang/user_service/config/ExecutionPoolPremiumRemove.java
Как бы и неплохо, но название класса) Это ж конфиг класс, назови его соответствующе)

2024-08-08 01:35 UTC, pablo023 commented on src/main/java/school/faang/user_service/filters/Invitation/InvitationInvitedIdNameFilter.java
Вот это всё, просто из-за названия с большой буквы, может не работать. Исправь все, плз.

2024-08-08 01:35 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +    public List<List<Long>>  findExpiredPremiumIds(){
лишний пробел ту тесть переж названием, но нет перед фигурной скобкой.

2024-08-08 01:35 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        List<Long> premiumIDList = premiumRepository.findAllByEndDateBefore(now).stream()
findAll это всегда так себе операция, ты можешь просто память переполнить таким. Ну списком лонгов - вряд ли, но всё же. Не надо так делать

2024-08-08 02:09 UTC, legionerkz commented on src/main/java/school/faang/user_service/config/ExecutionPoolPremiumRemove.java
ок)

2024-08-08 02:09 UTC, legionerkz commented on src/main/java/school/faang/user_service/filters/Invitation/InvitationInvitedIdNameFilter.java
исправил

2024-08-08 02:09 UTC, legionerkz commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +    public List<List<Long>>  findExpiredPremiumIds(){
исправил

2024-08-08 02:10 UTC, legionerkz commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        List<Long> premiumIDList = premiumRepository.findAllByEndDateBefore(now).stream()
тут по условию задачи так, указан был метод.

2024-08-08 02:59 UTC, pablo023 commented
Тут конфликтов...

2024-08-31 00:52 UTC, pablo023 commented
Надо пофиксить комменты, и можно вмержить

2024-12-21 21:08 UTC, closed without merging