BJS2-15642
CorporationX/user_service pull request #1305
Opened 2024-08-02 12:32 UTC by YPG0

1) Конфиг redis для топика user_ban
2) Прием из post_service id user для пометки banned

2024-08-08 02:02 UTC, pablo023 requested changes
Тут конечно не доделано много. Посмотри лекции этого спринта, многое понятнее станет. Плюс ты редис не поднимаешь даже, он должен заводиться отдельным докер контейнером, это отдельное приложение.

2024-08-08 02:02 UTC, pablo023 commented on src/main/java/school/faang/user_service/redis/RedisListenerConfig.java
> +        container.addMessageListener(redisMessageSubscriber, new ChannelTopic("user_ban"));
Название топика - в проперти, и через Value доставай оттуда

2024-08-08 02:02 UTC, pablo023 commented on src/main/java/school/faang/user_service/entity/User.java
Это, конечно, да, но а миграцию написать? У тебя же не запустится оно, в базе нет такого поля в таблице User

2024-08-08 02:02 UTC, pablo023 commented on src/main/java/school/faang/user_service/redis/RedisMessageSubscriber.java
Не не не. Это просто принимает сообщение, и создает из него BanEvent. Ты не выполняешь в onMessage логику сервиса. Подписчики и публикаторы просто создают и принимают сообщения. Публикатор из сущности его создает, а получатель, принимая JSON, из него формирует сущность. Я, конечно, не "за", но в крайнем случае, чтобы забанить юзера здесь, вынеси это в отдельный метод.

2024-08-08 02:02 UTC, pablo023 commented on src/main/java/school/faang/user_service/redis/RedisListenerConfig.java
Контейнер ты добавил, а бин для листенера эвентов на бан? Топик для банов?

2024-08-08 02:02 UTC, pablo023 commented
Плюс когда сделаешь всё, пофикси конфликты.

2024-08-08 13:55 UTC, YPG0 commented on src/main/java/school/faang/user_service/redis/RedisListenerConfig.java
> +        container.addMessageListener(redisMessageSubscriber, new ChannelTopic("user_ban"));
+

2024-08-08 13:55 UTC, YPG0 commented on src/main/java/school/faang/user_service/entity/User.java
Добавил миграцию

2024-08-08 13:56 UTC, YPG0 commented on src/main/java/school/faang/user_service/redis/RedisListenerConfig.java
Добавил бины для топика и MessageListenerAdapter

2024-08-08 17:28 UTC, YPG0 commented on src/main/java/school/faang/user_service/redis/RedisMessageSubscriber.java
Переделал на сколько понял. Тут обязательно JSON принимать или можно через jsonnode сделать раз только id передается. в post_service из-за этого странно выглядит

2024-08-08 17:34 UTC, YPG0 commented
По редис в отдельном контейнере не совсем понял. Тут уже есть контейнер с редисом в докере и в user_servise под него написан конфиг на порту 6379. Нужно отдельно еще 1 сделать под эту задачу на другом порте? А то запустил как есть метки baneed в базе у user ставятся

2024-08-08 22:53 UTC, pablo023 commented
> По редис в отдельном контейнере не совсем понял. Тут уже есть контейнер с редисом в докере и в user_servise под него написан конфиг на порту 6379. Нужно отдельно еще 1 сделать под эту задачу на другом порте? А то запустил как есть метки baneed в базе у user ставятся

Аа, есть уже. Я не видел конфига. Но если и есть, ты в пропертях должен сеттить новые топики для него, этого не увидел на том ревью. Сейчас тут посмотрим.

2024-08-08 22:55 UTC, pablo023 requested changes

2024-08-08 22:55 UTC, pablo023 commented on src/main/java/school/faang/user_service/redis/RedisMessageSubscriber.java
> +            userBanedService.banedUser(banEvent.getAuthorId());
Вот это надо из он месседж вынести. Это вообще логика юзер сервиса, мы не должны в сабскрайбере этим заниматься.

2024-08-08 22:55 UTC, pablo023 commented on src/main/java/school/faang/user_service/redis/RedisMessageSubscriber.java
> +    private final UserBanedService userBanedService;
Нам не нужен отдельный сервис для этого, это в юзер сервисе делается.

2024-08-08 22:55 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/UserBanedService.java
Это логика юзер сервиса, не нужен отдельный сервис.

2024-08-08 22:55 UTC, pablo023 commented on src/main/java/school/faang/user_service/redis/RedisListenerConfig.java
Уже похоже на правду)

2024-08-09 10:02 UTC, YPG0 commented on src/main/java/school/faang/user_service/redis/RedisMessageSubscriber.java
> +    private final UserBanedService userBanedService;
userBanedService удалил перенес в userService

2024-08-09 10:02 UTC, YPG0 commented on src/main/java/school/faang/user_service/service/UserBanedService.java
Убрал

2024-08-09 10:03 UTC, YPG0 commented on src/main/java/school/faang/user_service/redis/RedisMessageSubscriber.java
> +            userBanedService.banedUser(banEvent.getAuthorId());
+

2024-08-10 02:36 UTC, pablo023 approved these changes

2024-08-10 02:36 UTC, merged