centaur-master-bc5-BJS2-16016-delete-post-events
CorporationX/user_service pull request #1326
Opened 2024-08-13 11:59 UTC by Nikita2768

2024-08-15 22:03 UTC, pablo023 requested changes
Смотри, ты когда используешь аннотацию Scheduled - тебе надо в спринге включать сканирование этих операций, используя аннотацию EnableScheduling, на запускающем классе.

2024-08-15 22:03 UTC, pablo023 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
Смотри, у тебя метод берёт все события и делит их на части, чтобы раздать потокам для удаления. Проблема в том, как ты работаешь с методом subList(). Этот метод не возвращает новый список, а создаёт представление исходного списка. То есть, когда ты в одном потоке удаляешь элементы, другие потоки могут столкнуться с неожиданными изменениями в этом представлении. Результат — баги типа ConcurrentModificationException или вообще непредсказуемое поведение. Чтобы избежать этого трэша, нужно не просто брать подсписок через subList(), а делать его копию. Это защитит от проблем, связанных с конкурентными изменениями списка.

List<Event> partListEvent = new ArrayList<>(allEvents.subList(startIndex, Math.min(endIndex, sizeFullListEvent)));

2024-08-15 22:03 UTC, pablo023 commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
Используй аннотацию DisplayName

2024-08-17 04:12 UTC, Nikita2768 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
Спасибо, что сказал) Выяснил причину, исправил

2024-08-17 04:13 UTC, Nikita2768 commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
Понял, теперь начну использовать

2024-08-17 04:15 UTC, Nikita2768 commented
> Смотри, ты когда используешь аннотацию Scheduled - тебе надо в спринге включать сканирование этих операций, используя аннотацию EnableScheduling, на запускающем классе.

Понял

2024-08-17 05:13 UTC, pablo023 commented
Поправь пожалуйста конфликты, и можешь мержить, и переводить в done.

2024-12-21 21:14 UTC, closed without merging