Feature bjs2 15653
CorporationX/user_service pull request #1343
Opened 2024-08-21 11:32 UTC by GevorgSogomonian

2024-08-28 03:44 UTC, pablo023 requested changes

2024-08-28 03:44 UTC, pablo023 commented on src/main/java/school/faang/user_service/config/RedisConfig.java
> +    private ObjectMapper objectMapper;
https://www.baeldung.com/java-spring-field-injection-cons

2024-08-28 03:44 UTC, pablo023 commented on src/main/java/school/faang/user_service/publisher/ProfileViewEventPublisher.java
> +        }
Писал про это. Надо хотя бы так:

} catch (JsonProcessingException e) {
    throw new RuntimeException("Failed to process JSON: " + e.getMessage(), e);
}

А лучше - создать свой эксепшен для этого кейса. Давай сделаем по уму

2024-09-01 07:45 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/config/RedisConfig.java
> +    private ObjectMapper objectMapper;
Исправил

2024-09-01 08:21 UTC, GevorgSogomonian commented on src/main/java/school/faang/user_service/publisher/ProfileViewEventPublisher.java
> +        }
Сделал своё исключение

2024-09-03 14:55 UTC, merged