BJS2-27191 Реализация Подписки на пользователя
CorporationX/user_service pull request #1381
Opened 2024-09-03 13:31 UTC by musachev

BJS2-27191 Реализация Подписки на пользователя
+ Тесты

2024-09-05 09:40 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RequestMapping("/api")
может лучше subscriptions написать вместо api

2024-09-05 09:42 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +            throw new DataValidationException("Нельзя подписаться на самого себя");
На общем созвоне надо обсудить. Может договоримся всё латиницей писать, а то я, например, не смог настроить чтобы кириллица корректно отображалась в консоли

2024-09-05 09:48 UTC, Rashit86 commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    void followUser_checkDataValidationExceptionTest() {
У нас в обучении про тесты (1.5) было требование название тестовых методов начинать со слова test

2024-09-05 09:51 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
Не понял почему у тебя в контроллере и сервисе одна и та же валидация

2024-09-05 13:55 UTC, dmitridorje commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        assertThrows(DataValidationException.class, () -> subscriptionService.followUser(followerId, followeeId));
Можно ещё проверять сообщение исключения, но это, конечно, дело вкуса.

2024-09-05 18:12 UTC, vinogor commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RequestMapping("/api")
тут надо наверное нам командой обсудить и договориться как будем именовать пути)

2024-09-05 18:15 UTC, vinogor commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +            throw new DataValidationException("Нельзя подписаться на самого себя");
мне кажется можно заюзать GET вместо POST, ведь тело запроса отсутствует, всю инфу передаём в урле

2024-09-05 18:22 UTC, vinogor commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    void followUser_checkDataValidationExceptionTest() {
да, можно в идее настроить чтобы автоматически имена тестовых методов начинались с test 

![image](https://github.com/user-attachments/assets/43a99137-8cd2-4d38-b1fb-c3535ae6a132)

2024-09-05 18:23 UTC, vinogor commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    @InjectMocks
имхо нагляднее было бы вначале объявлять моки, а потом уже куда их инжектить

2024-09-07 06:21 UTC, musachev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RequestMapping("/api")
В этом месте я указал корневой путь к API - в идеале он должен быть у всех одинаковый. Обычно делают что-то типо /api/v1/
и дальше уже существительное у метода, которое обозначает что мы делаем с глаголом
POST /api/v1/subscribe

2024-09-07 06:22 UTC, musachev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +            throw new DataValidationException("Нельзя подписаться на самого себя");
@Rashit86 Да, англ лучше будет. Переделал.
@vinogor Гет - это получение данных обычно, когда мы никак не меняем состояние. В нашем же случае тут будет создание связи. Поэтому я сделал POST

2024-09-07 06:22 UTC, musachev commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    void followUser_checkDataValidationExceptionTest() {
@vinogor @Rashit86 спасибо, поправил.

2024-09-07 06:23 UTC, musachev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
@Rashit86 в контроллере проверяется, что пользователь не может подписаться сам на себя. Это запрещено логикой, поэтому проходит первичную проверку. А в сервисе проверяется, что такой подписки еще нет.

2024-09-07 06:24 UTC, musachev commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    @InjectMocks
@vinogor согласен, поправил.

2024-09-07 13:28 UTC, vinogor commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RequestMapping("/api")
вроде как то можно в yaml добавить начальный пусть всех вызовов, но пока не понял как и нужно ли так нам сделать)

2024-09-09 19:42 UTC, mikhailov26 requested changes

2024-09-09 19:42 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
Согласен с коллегой, все проверки в сервис слой

2024-09-09 19:42 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
За исключением null/empty входных данных

2024-09-11 04:10 UTC, musachev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
Поправил

2024-09-11 04:10 UTC, musachev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
Поправил

2024-09-11 16:47 UTC, merged