Solved BJS2-27377 : Стать менторов
CorporationX/user_service pull request #1384
Opened 2024-09-03 19:06 UTC by soulasphyxia

2024-09-04 00:26 UTC, SharkB38 approved these changes

2024-09-04 06:24 UTC, wmwmaks commented on src/main/java/school/faang/user_service/dto/MentorshipUserDto.java
> +@AllArgsConstructor
Есть смысл в этой аннотации? Data же включает в себя конструктор со всеми аргументами, если не ошибаюсь.

2024-09-04 06:32 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/dto/MentorshipUserDto.java
> +@AllArgsConstructor
@Data включает в себя @toString, @EqualsAndHashCode, @Getter/@Setter и @RequiredArgsConstructor, который насколько я знаю, создает конструктор только для обязательных полей (final или помеченных @NonNull

2024-09-04 06:33 UTC, SharkB38 commented on src/main/java/school/faang/user_service/dto/MentorshipUserDto.java
> +@AllArgsConstructor
Не, там @RequiredArgsConstructor
``
@Data is a convenient shortcut annotation that bundles the features of @ToString, @EqualsAndHashCode, @Getter / @Setter and @RequiredArgsConstructor together
``

2024-09-04 07:03 UTC, wmwmaks commented on src/main/java/school/faang/user_service/dto/MentorshipUserDto.java
> +@AllArgsConstructor
Понял, принял

2024-09-04 14:20 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/exception/MentorshipNotFoundException.java
> +
Хорошая идея с разными исключениями, ну на мой взгляд))) Но я бы ещё добавил класс с @ControllerAdvice))

2024-09-04 14:26 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +        if (!isRemoved) {
Мне в ревью писали стараться не писать if с отрицанием, думаю стоит подумать как реализовать этот метод по-другому или добавить доп метод, чтобы проверять есть ли ментор)

2024-09-05 03:47 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/exception/MentorshipNotFoundException.java
> +
посмотрю что это такое, спасибо!

2024-09-05 03:48 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +        if (!isRemoved) {
да, ты прав, я стараюсь думать об этом, но я застреваю на этом и пишу как обычно ). подумаю как исправить!

2024-09-05 13:18 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/exception/MentorshipNotFoundException.java
> +
да, вынес в отдельный класс, крутая штука, спасибо!

2024-09-05 13:27 UTC, ArstanSubanov approved these changes

2024-09-05 20:25 UTC, mysosnovskaya requested changes

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +@RestController
Тема будущих спринтов, но у тебя уже получился полноценный контроллер 👍

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +    public Map<String, String> deleteMentee(@PathVariable @Positive Long mentorId,
Map<String, String> - неочевидное решение. Мне как стороннему разработчику без заглядывания в реализацию метода не ясно, что в этой мапе ожидается. Лучше завести отдельный dto класс, например, SuccessResponse с полем message. Или просто void использовать, как было у Максима :) Вообще я за единообразие, но понимаю, что сейчас его сложно поддерживать. Поэтому если придерживаться твоей идеи, то всё-таки будет лучше dto. Для deleteMentor аналогично

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/MentorshipUserDto.java
> +public class MentorshipUserDto {
Поля же подразумеваются финальными? Если да, то здесь отлично подойдут record-ы (нововведение в java, по-моему с 14 версии). Рекомендую их использовать) Очень часто они подходят именно для dto классов

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    @ExceptionHandler({EntityNotFoundException.class})
Пустую строчку бы перед методом :)

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +        return ResponseEntity.ok(
Так всё-таки ok или not found? В текущем виде ResponseEntity создается как будто бы успешный (ok - статус код 200 - это успех). Я рекомендую завести отдельный dto класс, например, ErrorResponse с нужными полями (message, error, description - на твое усмотрение) и возвращать здесь объект этого класса вместо ResponseEntity

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/MentorshipNotFoundException.java
> +public class MentorshipNotFoundException extends EntityNotFoundException {
Есть ли смысл в этом исключении? И в UserNotFoundException тоже. Выглядят абсолютно одинаково, обработка одинаковая, а причину можно отличить по message. И в коде будет неудобно на каждую новую модель создавать новое исключение. По крайней мере на данный момент в этом нет никакой необходимости. EntityNotFoundException будет достаточно)

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    List<MentorshipUserDto> toMentorshipUserDtoList(List<User> userList);
Вместо userList лучше users, а вместо toMentorshipUserDtoList - toMentorshipUserDtos. Обычно коллекции выражают множественным числом, т.к. здесь суть не в том, что это List, а в том, что таких объектов много. Вместо списка мы также могли использовать и Set, например. Это не супер-строгое правило, иногда всё-таки бывает в названиях List, но намного чаще встречается множественное число

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRepository.java
> +import org.springframework.data.jpa.repository.Modifying;
Кучка лишних импортов - нужно удалить

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRepository.java
> +public interface MentorshipRepository extends JpaRepository<User, Long> {
Так, а UserRepository не подойдет разве? Он тоже extends JpaRepository<User, Long>

2024-09-05 20:25 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +            throw new MentorshipNotFoundException("Ментор и менти не могут иметь одинаковые идентификаторы");
В исключения и в логи всегда нужно добавлять какую-то идентифицирующую информацию, чаще всего это id. Чтобы потом можно было понять, у кого вообще получилось такой запрос сделать (у пользователя с каким id) и дальше разобраться с проблемой

2024-09-06 10:59 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRepository.java
> +public interface MentorshipRepository extends JpaRepository<User, Long> {
в задании указали, что можно использовать и тот, и другой

2024-09-09 19:55 UTC, mysosnovskaya requested changes
Хорошая работа с тестами, все возможные случаи покрыты 👍 Покрытие класса MentorshipServiceImpl составляет 100% - это отличный результат. Некоторые косметические изменения, а также предложение по работе с маппингом - и будем мержить)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +                    .formatted(mentorId));
Тут должен быть menteeId. Такое должны тесты отлавливать =)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +            throw new DataValidationException("Ментор не может иметь отрицательный идентификатор %d"
Получилось не единообразно с другими (выше) исключениями. И в случае равенства тоже id не добавлен. Могу предложить проверку на отрицательность идентификатора вынести в отдельный метод и возвращать чуть более общую ошибку, например, с описанием "id has incorrect value -1". Да, тут немного теряется конкретика, чей именно это id, но тот, кто отправлял запрос, сможет понять, где у него -1 стоит)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    private User userFirst;
Обычно всё-таки user1, user2 используют) Ну и наверное самый первый user тоже в эту логику вписывается, тогда у тебя должны быть user1, user2, user3

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    private final long USER_ID = 1;
Ещё static нужно добавить и вынести на самый верх класса - там константам самое место)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +        mentee = User.builder()
Почему-то стиль поменялся, до этого в одну строчку писал =)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    public void testGetMenteesPositiveEmptyTest() {
Нужно с названиями методов тестов разобраться. Во-первых, одного test в названии достаточно. Обычно это в самом начале test... (глагол - тестировать что-то). Во-вторых, Positive и Negative обычно не пишут. Просто testGetEmptyMentees - тестировать случай с получением пустого списка менти.

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +        assertEquals(user.getMentees().size(), result.size());
Совет: код теста можно логически разделить на следующие блоки: подготовка данных (создание объектов, прописывание when), вызов тестируемого метода, проверка результата. Между этими блоками обычно оставляют пустые строки. Если тест небольшой, то можно всё без пустых строк написать. У тебя в целом тесты не особо большие, поэтому настаивать на исправлении не буду, но тогда просто учти это на будущее)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +        user.setMentees(List.of());
А нельзя сразу при создании пустой список положить? И setMentors тоже

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    private final long NON_EXIST_ID_SECOND = 8;
Это поле не используется, нужно удалить

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    private User userSecond;
Идея говорит "Field can be converted to a local variable". Так что как поле класса этот юзер не нужен, допускается создать его в одном тесте

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +        verify(mentorshipRepository).findById(USER_ID);
Можно ещё verify на маппер сделать

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    public void testGetMenteesPositiveTest() {
testGetMentees

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +        assertTrue(result.containsAll(userMapper.toMentorshipUserDtos(mentor.getMentees())));
Я предлагаю в этой строке сравнить только id. Из result делаешь список id и проверяешь, что этот список содержит только нужные элементы. Так будет проще)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +        verify(mentorshipRepository).findById(MENTOR_ID);
С учетом предыдущего комментария можно написать verify для маппера

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    public void testGetMenteesWithNegativeId() {
Вот тут хорошее название)

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +
Пустых строчек подвезли?) Нужен единообразный стиль тестов

2024-09-09 19:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +
Эти пустые строчки тоже нужно удалить

2024-09-10 06:56 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +                    .formatted(mentorId));
🤦 какой ужас хорошо что Вы заметили

2024-09-10 12:53 UTC, mysosnovskaya requested changes

2024-09-10 12:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +        System.out.println(userId);
Ой, это откуда здесь?) Нужно удалить

2024-09-10 12:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +    private void validateNegativeId(Long id) {
Будет лучше validateId - валидируем (проверяем) id, а у тебя сейчас "валидируем отрицательный id"

2024-09-10 12:53 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +        user1.setMentors(List.of());
Это можно было в beforeEach сделать?

2024-09-10 12:53 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    public void testDeleteMentorshipPositive() {
testDeleteMentorship или если хочется подчеркнуть успешность, то можно testSuccessDeleteMentorship

2024-09-10 12:53 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    public void testGetMentorsPositiveTest() {
Нужно переименовать тест

2024-09-10 12:53 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceTest.java
> +    public void testGetMentorsPositiveEmptyTest() {
Нужно переименовать тест

2024-09-10 15:27 UTC, mysosnovskaya approved these changes

2024-09-10 15:28 UTC, merged