Task solution BJS2-27382: Участвовать в событии
CorporationX/user_service pull request #1385
Opened 2024-09-04 06:08 UTC by wmwmaks

2024-09-04 07:11 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
а как ты тестировал контроллер, откуда ты вызывал все эти методы, чтобы проверить, что все работает? в тестах? их просто нет в коммите

2024-09-04 07:12 UTC, soulasphyxia approved these changes
макс легенда отличная работа

2024-09-04 07:14 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
Мы же договорились тесты после ревью делать. Пока без них

2024-09-04 07:15 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
мне кажется, что в следующий раз лучше сделать отдельный интерфейс для сервиса, с методами, которые ты хочешь использовать, а затем сделать конкретную реализацию этого сервиса, тогда классы, которые зависят от этого сервиса будут зависеть от интерфейса, а не от конкретной реализации, что сделает код более гибким

2024-09-04 07:16 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
а как ты тогда проверял, что твой код работает, если у тебя нет никаких ендпоинтов в контроллере?

2024-09-04 09:18 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
Пока никак. Дальше проверю через тесты)
По форме должно работать, на тестах узнаю есть ли баги. Если будут, буду фиксить)
Пока непонятно есть ли смысл проверять руками без тестов. Это сейчас у нас 1 контроллер и 4 метода, а если таких контроллеров станет 5 и в каждом по 10 методов. Вручную будто бы долго и муторно это будет все

2024-09-04 13:36 UTC, SharkB38 requested changes

2024-09-04 13:36 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        }
Может вынести все это в отдельный метод validateEvent?

2024-09-04 15:45 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        }
Да, действительно, можно. Сделал так с проверкой на наличие зарегистрированных участников, а тут пропустил, что тоже проверка дублируется одинаково. Сделаю, если техлид одобрит такие выносы в отдельные методы)

2024-09-04 15:49 UTC, SharkB38 approved these changes

2024-09-04 20:57 UTC, mysosnovskaya requested changes
Прошу не пугаться большого количества комментариев :) Всё нормально, архитектура верная, классы правильно взаимодействуют друг с другом, но ещё есть, что улучшать, и время на это тоже есть - ещё больше половины недели) Поэтому стараюсь ревьювить максимально подробно, чтобы код выглядел как можно лучше) Также на следующее ревью жду тестов!)

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +public class EventParticipationController {
Контроллер сейчас не работает, это нужно исправить. Для себя можно написать несколько тестов, чтобы убедиться в работоспособности своего кода. На планнинге я говорила, что необязательно писать все тесты (покрывать тестами все возможные сценарии и краевые случае), но лучше всё-таки минимально протестировать самостоятельно. Так что контроллер отправляю на доработку)

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public Integer getParticipantsCount(@Positive long eventId) {
Лучше вернуть dto класс здесь. Т.е. создаешь отдельный класс, делаешь в нем поле count и возвращаешь объект этого класса. Это необходимо, чтобы все ответы были в формате json. Одно целое число (как сейчас) превратить в json нельзя.

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    EventUserDto EventUserToDto(User user);
Все методы должны начинаться с маленькой буквы

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    EventUserDto EventUserToDto(User user);
Метод лучше назвать userToEventUserDto (кого во что этот метод превращает). Остальные методы аналогично, т.к. Entity (в следующем методе) это что-то очень абстрактное, хотя метод превращает переданный объект именно в объект класса User и ни в какой другой

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +public class EventParticipationService {
В классе необходимо поправить стиль

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                System.out.println("User " + userId + " has been unregistered with event " + eventId);
Будет здорово, если вместо `System.out.println` будут настоящие логи :) Это делается совсем просто: над классом вешается аннотация Slf4j (от ломбока) и дальше у тебя автоматически появляется поле log. Чтобы сделать вывод в лог, делаешь log.info("User " + ....). Для остальных методов аналогично

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                throw new IllegalArgumentException("User is already registered");
В ошибке, как и в логах, лучше всегда указывать какой-то идентификатор, чтобы было понятно, с какими данными эта ошибка произошла. Здесь можно добавить userId, а в следующее исключение - eventId. Для остальных методов аналогично

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                throw new IllegalArgumentException("User is already registered");
Я думаю, лучше своё собственное исключение завести. IllegalArgumentException о другом: это когда в метод передали аргументы, которые не соответствуют спецификации метода (null, когда параметр помечен как notnull, отрицательное, когда параметр обязан быть положительным и так далее). В твоей ситуации с самими значениями всё нормально, они корректные. Для остальных методов аналогично

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        } throw new IllegalArgumentException("Event does not exist");
Сейчас у тебя это исключение генерируется всегда, даже если удалось успешно зарегистрировать пользователя) Для следующего метода аналогично

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +            List<EventUserDto> userDtoList = userMapper.EventUserListToDto(eventParticipationRepository.findAllParticipantsByEventId(eventId));
Ответ от репозитория лучше выделить в отдельную локальную переменную для повышения читаемости кода

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                return null;
Такие ответы лучше не возвращать. Тот, кто сделает запрос к нам на сервер, увидит null и статус ответа 200 (успешный) и ничего не поймет) То ли всё корректно, то ли в чем-то ошибка. Обычно когда запрашивается список каких-то объектов по какому-то критерию (у нас по eventId), то в случае отсутствия таких объектов логично вернуть пустой список. Мы как бы говорим: вот смотри, сколько мы по этому eventId нашли :) Пустой список - значит ничего не нашли. Ну и надо убедиться, возможна ли вообще ситуация, когда у тебя userDtoList будет равен null? Если да, обязательно напиши на это отдельный тест. Если нет, то удали эту проверку, достаточно будет сразу вернуть userDtoList

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    private boolean isRegisteredParticipant(long eventId, long userId) {
Метод лучше назвать isParticipantRegistered - так корректнее с точки зрения английского языка :)

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        User userForEventById = eventParticipationRepository.findParticipantById(eventId, userId);
Переменную можно назвать просто participant, тут логика всего на две строчки и не предполагает никаких расширений. Так что всем всё понятно будет :)

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        }
Согласна) Отличное предложение!

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
Супер 👍 Это один из принципов SOLID. Полностью согласна, выделить интерфейс - отличная идея. Предлагаю это сделать. Кидаю ссылку, как в IDEA это сделать быстро:
https://www.jetbrains.com/help/idea/extract-interface.html#-9p987i_54

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/event/EventParticipationRepository.java
> +    @Query(nativeQuery = true, value = """
Ого, ты уже запросы к базе пишешь 👍 Только нужно соблюдать стиль) Смотри, как запросы оформлены выше, и сделай также

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/event/EventParticipationRepository.java
> +    boolean eventExistsById(@Param("eventId") long eventId);
А зачем понадобился Param? Выше как-то без этого обходились)

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/event/EventParticipationRepository.java
> +    User findParticipantById(long eventId, long userId);
Метод (его имя) лучше уточнить (у тебя не просто ById, а ещё и по eventId).

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/EventUserDto.java
> +    private long id;
Поля могут быть финальными? Ведь мы используем объекты этого класса только чтобы сформировать ответ, один раз создаем объект и его возвращаем из контроллера. Изменений полей здесь быть не может. Также рекомендую обратить внимание на java records - они часто (не всегда) хорошо подходят для dto классов

2024-09-04 20:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +
Лишняя пустая строка

2024-09-05 05:48 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +public class EventParticipationController {
Про такое я знаю. По программе  только на следующем спринте расскажут про рест, поэтому решил не бежать впереди паровоза

2024-09-08 23:46 UTC, SharkB38 commented on src/main/java/school/faang/user_service/exception/EventExistsException.java
> +}
Я бы поменял название на что-то типо EventDoesNotExistException

2024-09-08 23:46 UTC, SharkB38 commented on src/main/java/school/faang/user_service/exception/UserExistsException.java
> +}
И тут тоже другое название сделал бы

2024-09-09 22:22 UTC, mysosnovskaya requested changes

2024-09-09 22:22 UTC, mysosnovskaya commented on build.gradle.kts
Эти изменения нужно откатить, они не относятся к задаче текущего ПР

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/EventUserDto.java
> +public record EventUserDto(long id, String username, String email){
Пробела не хватает)

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/EntityNotFoundException.java
> +public class EntityNotFoundException extends RuntimeException{
Тоже пробела не хватает)

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    List<EventUserDto> usersToUsersDto(List<User> userList);
usersToUserDtos (s переехала)

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    List<User> usersDtoToUsers(List<EventUserDto> eventUserDtoList);
eventUserDtoList -> eventUserDtos и ниже userList -> users

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationServiceImpl.java
> +        log.info("Participant count of event {}:", eventId);
И количество тоже можно в лог добавить

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationServiceImpl.java
> +    public void registerParticipant(long eventId, long userId) {
Над методами обязательно нужна аннотация Override

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventParticipationServiceImpl.java
> +        log.info("User {} has been registered with event {}", userId, eventId);
Логи на английском это хорошо)

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/event/EventParticipationValidator.java
> +    private EventParticipationRepository eventParticipationRepository;
final?

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/event/EventParticipationValidator.java
> +    private static final String USER_ALREADY_REGISTERED_MESSAGE = "User %d already registered on event %d";
Константы лучше в начале класса писать, так принято) После них уже все остальные поля

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/event/EventParticipationValidator.java
> +@Slf4j
Логи в классе не используются, поэтому эта аннотация не нужна

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/event/EventParticipationValidator.java
> +    public boolean validateParticipationRegistered(long eventId, long userId) {
У тебя сейчас намешано и boolean, и исключения. Это два разных подхода:
1. Можно вернуть true, если валидация пройдена успешно, и false иначе
2. Можно сгенерировать исключение, если валидация не пройдена, и промолчать (void) иначе
Выбери один из подходов и реализуй только его) Сейчас нет никакого смысла в возвращаемом false - это очевидно, что если исключения не случилось, то будет false. Поэтому ты результатом метода даже нигде не пользуешься)

2024-09-09 22:22 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/event/EventParticipationValidator.java
> +        return true;
А почему здесь true возвращается, а в методах выше - false?)

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +    private static final String EVENT_NOT_EXISTS_EXCEPTION_MESSAGE = "Event not exist";
Константы нужно переместить в самый верх класса

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        when(eventParticipationValidator.checkEventExists(eventId)).thenThrow(new EntityNotFoundException(EVENT_NOT_EXISTS_EXCEPTION_MESSAGE));
Напишу то же, что и Валере:
Честно говоря, я бы не мокала валидатор. Потому что потом получаются вот такие странные тесты, которые не несут в себе особой логики. Валидация - это часть сервисной логики и чаще всего вообще отдельный класс не выделяется.
Этот тест проверяет, что когда у сервиса вызывают registerParticipant, он вызывает checkEventExists. И всё) Небольшой смысл в этом есть, но полезнее было бы проверить, что если в registerParticipant передать id несуществующего события, то выпадет исключение DataValidationException с определенным описанием ошибки - такой тест уже имеет смысл

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        verify(eventParticipationRepository, times(1)).register(eventId, userId);
times(1) можно не писать, оно по умолчанию так

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +    @DisplayName("testUnregisterParticipant_Success")
В DisplayName нет смысла дублировать название теста. Если эту аннотацию не писать, то как раз название теста и будет отображаться. Поэтому если не хочешь писать более человекочитаемое описание теста, то эти DisplayName лучше вообще удалить) По-хорошему лучше, что DisplayName были и были с понятным описанием, но такое на реальных проектах бывает далеко не всегда

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        assertEquals(participantsDto, result);
Предлагаю сравнить только id. Из result достаешь только id и проверяешь, что там есть только те, которые нужны. Тогда и с маппером проблем не будет. Он будет вызываться один раз и его можно проверить через verify

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        verifyGetParticipants();
Понимаю твоё желание вынести дублирующийся код в отдельный метод, но вот в тестах это работает немного по-другому) Создания объектов и прочую инициализацию выносят, да. А вот подобного рода проверки очень редко, только если их действительно будет очень много одинаковых (штук 10-15). Дело в том, что потом сервис будет развиваться, методы будут становиться всё более непохожими друг на друга и тесты придется адаптировать соответствующим образом. Очень вероятно, что вот этот общий код в методах станет не таким уж и общим. Поэтому обычно assert и verify никуда не выносят. Тем более у тебя всё это сделано ради двух тестов. Оно того не стоит =) И читать тесты будет легче, и модифицировать в будущем - тоже. Аналогично и для verifyGetParticipantsCount

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +    private void setUpEventValidator(boolean isValid) {
Мне потребовалась пара минут, чтобы осознать =) В целом выделение этой логики в отдельный метод тоже выглядит избыточным (тем более здесь объединены сразу два случая) и я бы предпочла не выделять этот метод. Но здесь пусть остается, как будто более оправдано выглядит) Я бы переименовала так:
setUpCheckEventExistsResult(boolean generateException)
Или может у тебя ещё какие-то идеи будут.
Кстати, первый признак лишнего выделения кода в методы/классы - проблемы с понятным названием. Поэтому если сложно придумать название, то стоит задуматься, а нужен ли вообще этот метод

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/validator/event/EventParticipationValidatorTest.java
> +    long eventId = 1L;
Куда-то модификаторы убежали

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/validator/event/EventParticipationValidatorTest.java
> +    private User setUpCreateUser() {
createUser лучше подойдет) setUp здесь не при чем

2024-09-09 22:22 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/validator/event/EventParticipationValidatorTest.java
> +        User user = new User();
return new User();

2024-09-10 10:12 UTC, wmwmaks commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    List<EventUserDto> usersToUsersDto(List<User> userList);
Почему так? Мы же много юзеров делаем в много юзер дто

2024-09-10 10:17 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        when(eventParticipationValidator.checkEventExists(eventId)).thenThrow(new EntityNotFoundException(EVENT_NOT_EXISTS_EXCEPTION_MESSAGE));
Немного не понял. "но полезнее было бы проверить, что если в registerParticipant передать id несуществующего события, то выпадет исключение DataValidationException с определенным описанием ошибки" У меня же так и получается, что в тест якобы передается eventId ивента, который не существует, из-за чего вызывается ошибка.
Если я правильно понял суть when.

2024-09-10 10:17 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        verify(eventParticipationRepository, times(1)).register(eventId, userId);
Это мы перенимаем практику Влада) Он говорил, что оно там по умолчанию так, но он прописывает, чтобы точно знать, что 1.

2024-09-10 10:19 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +    private void setUpEventValidator(boolean isValid) {
Похожую штуку Влад делал в воркшопе, поэтому я тоже постарался.

2024-09-10 10:20 UTC, wmwmaks commented on src/test/java/school/faang/user_service/validator/event/EventParticipationValidatorTest.java
> +    private User setUpCreateUser() {
сначала оно так и было, но потом я увидел, что используется setUp и подумал, что это общая приписка к тем методам, где что-то генерируется для тестов

2024-09-10 16:21 UTC, wmwmaks commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    List<EventUserDto> usersToUsersDto(List<User> userList);
А, мы s к dto добавляем, увидел, понял

2024-09-10 16:32 UTC, wmwmaks commented on src/main/java/school/faang/user_service/validator/event/EventParticipationValidator.java
> +    public boolean validateParticipationRegistered(long eventId, long userId) {
Изначально они были void, но в тестах в when ожидается, чтобы метод что-то возвращает, поэтому так сделал. Но я узнал про doThrow().when, сделаю методы валидатора void

2024-09-10 16:42 UTC, wmwmaks commented on src/test/java/school/faang/user_service/validator/event/EventParticipationValidatorTest.java
> +    private User setUpCreateUser() {
И, видимо, потом я сам к этому пришел, потому что смотрю сейчас в проект и тут createUsers без setUp 🙄

2024-09-10 18:19 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        when(eventParticipationValidator.checkEventExists(eventId)).thenThrow(new EntityNotFoundException(EVENT_NOT_EXISTS_EXCEPTION_MESSAGE));
Я попробовал не мокать валидатор, а через @BeforeEach создавать его для каждого теста. Тоже заработало, но под это нужно переписывать много тестов. В этот раз оставлю так.. В следующих задачах попробую реализовать в другом виде.

2024-09-10 18:20 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +        verify(eventParticipationRepository, times(1)).register(eventId, userId);
Тоже, думаю, оставлю так для наглядности. Оно не мешает, как мне кажется

2024-09-10 18:21 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceImplTest.java
> +    @DisplayName("testUnregisterParticipant_Success")
Пока уберу, обдумывать формулировку 20 тестов сегодня не хочется, если честно 😅. Пока они достаточно простые, думаю, из их названий понятно, что они делают.)

2024-09-10 20:26 UTC, mysosnovskaya approved these changes

2024-09-10 20:31 UTC, merged