BJS2-27005   Организация события
CorporationX/user_service pull request #1393
Opened 2024-09-04 20:24 UTC by ilu23ilu23

2024-09-04 20:58 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +@RequestMapping("/event")
вроде принято во множественном числе именовать эндпоинты сущностей
типа events

2024-09-04 21:00 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/create")
тоже вроде надо глаголы избегать в api, где это можно
Тут у тебя метод Post используется для создания, метод Put ниже - для апдейта. Это и так понятно из найминга Http методов, поэтому можно оставить 2 эндпоинта вида localhost/events на 2 разных Http метода
ИМХО

2024-09-04 21:03 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/exception/event/exceptions/DataValidationException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
Какой тут смысл этой аннотации? Выше ты хэндлишь эти эксепшены и в ResponseEntity вручную вставляешь HttpStatus такой же. В аннотации к классу она зачем? Спрашиваю, потому что интересно

2024-09-04 21:04 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private User loadUserByIds(Long id) {
loadUsersByIds - типа загрузить юзеров по списку айдишников подразумевается из нэйминга как будто, а передается один id

2024-09-04 21:04 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/event/filters/EventStartDateFilter.java
> +        return eventStream.filter(event -> event.getStartDate().isAfter(eventFilterDto.getStartDate()) || event.getStartDate().isEqual(eventFilterDto.getStartDate()));
поехала строка куда-то

2024-09-04 21:22 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +
Лишняя пустая строка

2024-09-04 21:42 UTC, IvanTsegelnyuk commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +    @Mock
Зачем мокировать юзера?

2024-09-04 22:00 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/create")
Да, тут "/create" можно убрать

2024-09-04 22:01 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/create")
Ещё можно
@ResponseStatus(CREATED)
добавить.
Но ни на что не влияет. Просто я где-о увидел, мне понравилось и я использую.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private LocalDateTime startDate;
Тут нам дата нужна или дата+время.
Если просто дата то LocalDate startDate
Если дата+время то LocalDateTime startDateTime (типа того)

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +public class EventDto {
Найди
CREATE TABLE event
и посмотри ограничения на длину стринга в sql скрипте
можешь добавить сюда

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private String status;
Обычно статусы всякие - это енамы.
Можешь EventStatus вставлять.
Спринг сконвертит строку из джейсона в енам.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private String type;
Енам сделай EventType

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +        return eventService.create(eventDto);
eventService.createEvent(eventDto);
чтобы однообразно с updateEvent

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        List<Skill> relatedSkills = loadSkillsByIds(eventDto.getRelatedSkillsIds());
load обычно используется, если файл какой-то тащишь или типа того
для сущностей либо get либо find

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        List<Skill> relatedSkills = loadSkillsByIds(eventDto.getRelatedSkillsIds());
как вариант
getEventSkillsFromDbByIds(EventDto eventDto)
но не настаиваю
думаю у коого-нибудь лучше вариант родится

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        return skillRepository.findAllById(skillIds);
Проверь постманом если сюда null придет, что будет.
На самой EventDto там нет валидации на null.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        return userRepository.findById(id).orElseThrow();
Я так делаю:
В скобках бросаю осознанную ошибку типа
.orElseThrow(() -> new ResourceNotFoundException("Employee %s not found", id));
и в @ControllerAdvice отлавливаю ошибку и логирую экзепшн

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        EventStatus eventStatus = EventStatus.valueOf(eventDto.getStatus().toUpperCase());
Когда в dto сделаешь енамы, тут конвертит не нужно будет.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        event.setStatus(eventStatus);
И тут в маппер красиво лягут.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        return eventMapper.toDto(eventRepository.save(event));
Не знаю как вам, мне не нравятся такие конструкции.
делаю
Event createdEvent = eventRepository.save(event);
return eventMapper.toDto(createdEvent);

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        return userRepository.findById(id).orElseThrow();
А всё, вижу
ты так и делаешь
в другом месте
new EntityNotFoundException("Событие с ID " + eventId + " не найдено."));
претензия снимается)

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                        new EntityNotFoundException("Событие с ID " + eventId + " не найдено."));
По опыту могу сказать, что вот эта конструкция будет встречаться часто в других местах (но не факт).
я выношу в приватный (или потом если понадобится публичный) метод
private  EventDto findById(Long id) {
    return eventRepository.findById(eventId)
                .orElseThrow(() ->
                        new EntityNotFoundException("Событие с ID " + eventId + " не найдено."));
}

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .reduce(eventStream, (stream, filter) -> filter.apply(stream, eventFilterDto), (s1, s2) -> s1);
красивое
если работает то огонь

я через combine предикатов делал
у тебя круче

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .orElseThrow(() -> new EntityNotFoundException("Событие с ID " + eventDto.getId() + " не найдено."));
Ага, оно самое private EventDto findById(Long id)

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        }
Можно убрать.
null , он же Optional.empty, на предыдущем шаге обработался уже

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        }
Второй раз вижу уже
вынеси просто в 
void checkUserSkills(user, relatedSkills){
...
}

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        updateEventFields(existingEvent, eventDto, relatedSkills, user);
В mapstract не только мапить можно, но и апдейтить сущности.
Погугли, наверное в этом месте поможет.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        int subscribersCount = user.getFollowers().size();
В клин коде рекомендуют скукоживать в один метод
getFollowersSize()

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +
строка

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        }
ещё можно так
eventRepository.findById(eventId)
        .ifPresentOrElse(
            event -> eventRepository.delete(event),
            () -> { throw new EntityNotFoundException("Event with ID " + eventId + " not found."); }
        );
        
или так
try {
        eventRepository.deleteById(eventId);
    } catch (EmptyResultDataAccessException e) {
        throw new EntityNotFoundException("Event with ID " + eventId + " not found.");
    }

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +            @RequestParam(value = "ownerUsername", required = false) String ownerUsername) {
Тут надо у сарших справшивать обязательно ли Get запрос через параметры задавать или можно через requestBody.
Я через requestBody делал.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PutMapping("/update")
update можно убрать

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        Event existingEvent = eventRepository.findById(eventDto.getId())
В dto нет валидации на id == null
в findById будет NPE

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @GetMapping("/ownedEvents/{userId}")
owned-events

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/event/EventWithSubscribersDto.java
> +public class EventWithSubscribersDto {
Если практически все поля такие же как в EventDto
и если эта сущность используется только как response dto
то попробуй пошаманить с таким вариантом 
EventWithSubscribersDto extends EventDto

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/exception/event/exceptions/DataValidationException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
Аннотация актуальна если сразу в респонс бросаешь ошибку

Но поскольку ты её перехыватывешь и потом
return new ResponseEntity<>(responseBody, HttpStatus.BAD_REQUEST);
то тут аннотация не нужна

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/event/EventMapper.java
> +    @Mapping(source = "relatedSkills", target = "relatedSkillsIds", qualifiedByName = "mapIdsSkills")
строчка

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/event/EventMapper.java
> +public interface EventMapper {
Дискуссионный вопрос, но мне привычнее target слева, source справа
типа в том же прядке что и классы в методе

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/event/EventMapper.java
> +    @Named("eventTypeToString")
строчка

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/event/EventMapper.java
> +        return skills.stream().map(Skill::getId).toList();
skills.stream()
    .map(Skill::getId)
    .toList();

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/event/EventMapper.java
> +        return skills.stream().map(Skill::getId).toList();
если null

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/filters/EventFilter.java
> +
.

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/filters/EventUsernameFilter.java
> +        return eventStream.filter(event -> event.getOwner().getUsername().equals(eventFilterDto.getOwnerUsername()));
если owner == null?

2024-09-04 23:32 UTC, amilosh commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +    private EventService eventService;
опусти после моков

2024-09-04 23:32 UTC, amilosh commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +        eventService = new EventService(eventRepository, userRepository, skillRepository, eventMapper, filters);
моки итак заинжектятся
в EventService
new EventService делать не надо

2024-09-04 23:32 UTC, amilosh commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +    public void testGetEventsByFilter() {
public

2024-09-04 23:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +            eventRepository.deleteById(eventId);
Если так сделать, то автоматически удаляются и строчки из event_skill и user_event?

2024-09-05 06:30 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private String status;
Я пробовал так делать, и удивился прочему не работает, потом сделал как есть и заработало, странно..

2024-09-05 06:30 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private String type;
С енамом не работает, нор работает таким образом

2024-09-05 06:45 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        EventStatus eventStatus = EventStatus.valueOf(eventDto.getStatus().toUpperCase());
Пробовал, не получилось

2024-09-05 08:14 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        return eventMapper.toDto(eventRepository.save(event));
Меньше кода зато

2024-09-05 11:26 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        updateEventFields(existingEvent, eventDto, relatedSkills, user);
Таким образом нарушаем принцип единой ответственности, лучше отдельным классом

2024-09-05 11:31 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +            @RequestParam(value = "ownerUsername", required = false) String ownerUsername) {
Я пока оставлю, посмотри что Дима скажет

2024-09-05 11:40 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/filters/EventUsernameFilter.java
> +        return eventStream.filter(event -> event.getOwner().getUsername().equals(eventFilterDto.getOwnerUsername()));
owner валидируется, нул к фильтрам не подойдет

2024-09-05 11:58 UTC, ilu23ilu23 commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +        eventService = new EventService(eventRepository, userRepository, skillRepository, eventMapper, filters);
Тут я список фильтров вручную создаю и евент сервис без этой строчки не знает о существовании этой коллекции, пробовал по другому - не получилось, только так работает) Если кто подскажет как это сделать - поправлю.

2024-09-05 12:03 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private String status;
Да, поправил, всё получилось, спасибо

2024-09-05 12:03 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private String type;
Да, поправил, всё получилось, спасибо

2024-09-05 12:29 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
Не знаю что из этого гуд практис, но я бы добавил отступы между переменными, когда все в куче сложнее воспринимается, имхо

2024-09-05 12:44 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +        return eventService.create(eventDto);
'+'

2024-09-05 19:18 UTC, 20cognosce requested changes

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private List<Long> relatedSkillsIds;
List<SkillDto> relatedSkills
По условию тебя просят отдавать не просто id, а именно скиллы

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +    public EventDto create(EventDto eventDto) {
Давайте делать в сервисах всё на сущностях.
Если другой сервис захочет использовать твой сервис, зачем ему DTO передавать, если это не слой представления уже

Все маппинги вынеси в мапперы

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        List<Skill> relatedSkills = getEventSkillsFromDbByIds(eventDto.getRelatedSkillsIds());
getEventSkillsFromDbByIds
Что за нейминг? FromDb, а откуда еще можно?

Тебе нужно разные EventDto на каждое действие, в каждом только нужное.

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +    }
Объединить с validateUserSkills
Разве список может быть null? Тут я не уверен, но вроде просто пустой должен вернуться

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        return eventMapper.toDto(eventRepository.save(event));
Mapper в контроллер

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +public class EventServiceImpl implements EventService {
Логируй свои ключевые действия, как ты будешь баги свои потом искать

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/exception/event/exceptions/DataValidationException.java
> +public class DataValidationException extends RuntimeException {
Скажи, а где оно у тебя будет выбратываться? ты ообработчик на него сделал, но нигде не кидаешь
@Valid другой эксепшен кинет, ты проверял?

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PutMapping()
Patch

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PutMapping()
Мне кажется, что ты обновляешь ивент по id, стоит это как /{id} вынести в URI

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +            @RequestParam(value = "ownerUsername", required = false) String ownerUsername) {
Да уж это многовато
И это поля специфичное сущности, а не общие asc/desc, page и проч

Лучше вынести в отдельный FilterDto

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +            @RequestParam(value = "ownerUsername", required = false) String ownerUsername) {
Тогда у тебя возникнет проблема, что Get по спецификации не имеет тела, и придется метод на Post переделать

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Неподходящий статус код
Оставь дефолтный 200
И там где у тебя выше OK - он тоже лишний

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/event/EventFilterDto.java
> +@Data
Убрать эту аннотацию, она генерирует лишнее

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/event/EventWithSubscribersDto.java
> +public class EventWithSubscribersDto {
Не рекомендую писать в DTO хоть какую-либо логику, как и наследование тоже не рекомендую здесь, оставь как есть

@Data убрать

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/event/EventWithSubscribersDto.java
> +    private int subscribersCount;
Пиши единообразно - либо всё примитивами, либо всё обертками

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    EventWithSubscribersDto updateEvent(EventDto eventDto);
Порядок поменяй, get к get))

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +@RequiredArgsConstructor
Сначала Service как более важная аннотация

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +    }
Вот и еще  поэтому Dto из сервиса убирай, и эти все микрометоды тоже убирай
вместо findById вызывай 
public Event getEvent(Long eventId)

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        return user.getFollowers().size();
Не оптимально

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        return user.getFollowers().size();
Сразу размер бери из базы

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        Stream<Event> eventStream = eventRepository.findAll().stream();
Так
Ну мы будем считать, что на данном этапе на проекте это норм

Но в реальности никогда не тащи в рантайме всю базу через findAll

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        eventStream = eventFilters.stream()
Сразу в список собирай
Не объявляйте Stream, это не коллекция

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +    }
Кажется, что это задача для маппера

2024-09-05 19:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/util/EventUpdater.java
> +    }
Вот это всё убираем
@Builder применяем

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/event/EventMapperTest.java
> +        assertEquals(1L, eventWithSubscribersDto.getRelatedSkillsIds().get(0));
Assertions.assertThat(objActual)
                .usingRecursiveComparison()
                .ignoringFields("uniqueId", "otherId")
                .ignoringFieldsMatchingRegexes(".*someId")
                .ignoringOverriddenEqualsForTypes(MyData.class, MyDataItem.class)
                .isEqualTo(objExpected);

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/event/EventMapperTest.java
> +        assertEquals(1L, eventWithSubscribersDto.getRelatedSkillsIds().get(0));
10 строк assertEquals оптимизируй

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventServiceImplTest.java
> +    private EventFilter eventFilter2;
Маппер ты протестил, ладно
Но почему фильтры замокал
Ты их не тестируешь никак

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventServiceImplTest.java
> +    private EventFilter eventFilter2;
Часть замокай, часть проинициализируй сам и передай всё через конструктор

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventServiceImplTest.java
> +        when(userRepository.findById(eventDto.getOwnerId())).thenReturn(Optional.of(user));
Тут тоже в одну строчку можно не писать
.thenReturn

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventServiceImplTest.java
> +        });
Вот за моканье фильтров - бан

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventServiceImplTest.java
> +        when(eventMapper.toFilterDto(anyList())).thenReturn(expectedEventDtos);
Да и маппер тоже нафиг мокать? Он же не имеет зависимостей

2024-09-05 19:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventServiceImplTest.java
> +        assertEquals(expectedEventDtos.size(), actualEventDtos.size());
Просто size - это халтура

2024-09-06 07:08 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private List<Long> relatedSkillsIds;
По лекции Влада - он говорил, что в дто чтобы не дергать сущности, лучше передавать пока только айдишники, и в маппере у меня есть вспомогательный метод, который из скилов делает их айдишники, а уже в сервисном слое я превращаю эти айдишники в сущности.

2024-09-06 07:30 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/exception/event/exceptions/DataValidationException.java
> +public class DataValidationException extends RuntimeException {
Да, у меня есть эксепшн хэндер, который это обрабатывает и при ошибке валидации бросается DataValidationException

2024-09-06 07:33 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        Stream<Event> eventStream = eventRepository.findAll().stream();
По условию задачи написано так и делать, не я придумал)

2024-09-06 07:35 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +    }
У меня этот метод есть, приватным методом findById я сократил повторяющийся код в методах

2024-09-06 17:23 UTC, 20cognosce requested changes

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +        return eventMapper.toEventWithSubscribersDto(updatedEvent, eventServiceImpl.getSubscribersCount(updatedEvent));
Переменную subscribersCount объявить

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/event/EventWithSubscribersDto.java
> +    private EventStatus status;
Так, стоп
у тебя EventDto хранит все те же поля, разница в одном поле private Integer subscribersCount?

И на create EventDto принимает реально все эти поля?
Сомневаюсь.

Создавай несколько DTO под каждый метод. Ничего не должно оставаться не использующимся, и если у тебя такое больше пересечение общих полей - чет не то

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/mapper/event/EventMapper.java
> +    @Mapping(target = "owner", ignore = true)
Вот ты тут что-то игноришь к тому же

Наведи порядок - чтобы ничего не было лишнего, создай отдельное DTO под каждую ситуацию

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/exception/event/exceptions/DataValidationException.java
> +public class DataValidationException extends RuntimeException {
> Да, у меня есть эксепшн хэндер, который это обрабатывает и при ошибке валидации бросается DataValidationException

Бросается именно school.faang.user_service.exception.event.exceptions.DataValidationException?
Или другой с таким же именем?

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +@Transactional
Зачем на класс навесил...

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        eventMapper.updateEventFromDto(existingEvent, event);
Это что такое, зачем тебе маппер?
Тут, в сервисе, руками все поля обновляй, какие надо

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +    public Event updateEvent(Event event) {
Где надо @Transactional нет

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        return event.getOwner().getFollowers().size();
Плохо...
Если бы это в маппере было, я бы закрыл глаза, ну раз мы тут репозитории имеем - отправь запрос, который вернет только количество

К тому же у тебя Event который на входе - он не связан ни с какой транзакцией, его состояние могло измениться уже. В getFollowers по-любому заглушка из-за FetchType.LAZY и у тебя ошибка вылетит вообще

Ты проверял это реальным запросом?

sql запрос на count отдельный создай

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +    public void deleteEvent(Long eventId) {
@Transactional

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        Event existingEvent = findById(event.getId());
Зачем тебе findById если у тебя есть метод getEvent?
Такой же
логику из findById перенеси в getEvent

2024-09-06 17:23 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/event/EventMapperTest.java
> +        event.setStatus(EventStatus.PLANNED);
@builder bruh...

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/filter")
наверно лучше "search"

2024-09-06 17:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PatchMapping()
пустые скобки можно убирать

2024-09-06 17:33 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/event/EventWithSubscribersDto.java
> +    private EventStatus status;
Там всё по условию так, и апдейт только одной переменной и отличаются. На апдейт и на креейт у меня отдельные дто,

2024-09-06 17:34 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/event/EventWithSubscribersDto.java
> +    private EventStatus status;
В апдейт нужно обновить текущую сущность и дополнительно передать количество подписчиков юзера

2024-09-06 17:42 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/exception/event/exceptions/DataValidationException.java
> +public class DataValidationException extends RuntimeException {
school.faang.user_service.exception.event.exceptions.DataValidationException: Ошибка валидации

2024-09-06 17:46 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        eventMapper.updateEventFromDto(existingEvent, event);
![2024-09-06_20-45-23](https://github.com/user-attachments/assets/2d458500-6b3b-45ab-838d-79d17b55c211)
Ты же сказал так и сделать)

2024-09-06 19:23 UTC, 20cognosce requested changes

2024-09-06 19:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    @Query(nativeQuery = true, value = """
Можно использовать JPQL
Немного более удобным станет синтаксис

2024-09-06 19:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +                .reduce(eventRepository.findAll().stream(),
Не прячь так вызов findAll, объяви переменную отдельную, чтобы видно было

2024-09-06 19:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        validateUserSkills(user, relatedSkills);
И мне кажется, это дублирование кода, в create то же самое
может в метод вынести отдельный

2024-09-06 19:23 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        return userRepository.countFollowersByUserId(event.getOwner().getId());
event.getOwner().getId() - переменная

2024-09-06 19:23 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/event/EventMapperTest.java
> +                .relatedSkillsIds(event.getRelatedSkills().stream().map(Skill::getId).collect(Collectors.toList()))
не жести

2024-09-06 19:23 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/event/EventMapperTest.java
> +                        .relatedSkillsIds(e.getRelatedSkills().stream().map(Skill::getId).collect(Collectors.toList()))
.

2024-09-06 19:40 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    @Query(nativeQuery = true, value = """
Я подумал, раз тут всё нейтив, также и написал

2024-09-06 19:40 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +                .reduce(eventRepository.findAll().stream(),
Меньше кода - больше кислорода)

2024-09-06 20:15 UTC, 20cognosce requested changes

2024-09-06 20:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    @Query("SELECT COUNT(f) FROM User u JOIN u.followers f WHERE u.id = :userId")
Не в одну строчку

2024-09-06 20:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        event.setRelatedSkills(relatedSkills);
Нет, валидация не предполагает, что ты чет тут будешь изменять
Это сайд-эффект получается

2024-09-06 20:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        validateUserSkills(user, relatedSkills);
Зачем тебе тогда метод validateUserSkills
Один метод валидации сделай

2024-09-06 20:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +
Пустое место сжимаем

2024-09-06 20:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        validateEventOwnerAndSkills(event);
Почему бы не делать это первым действием?

2024-09-07 19:49 UTC, 20cognosce approved these changes

2024-09-07 19:51 UTC, merged