BJS2-26818 Организация события
CorporationX/user_service pull request #1400
Opened 2024-09-05 16:03 UTC by Murzin34

2024-09-11 09:25 UTC, Alginin commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/filters")
Может быть  должен использоваться @GetMapping ?

2024-09-11 11:43 UTC, Alginin commented on src/test/java/school/faang/user_service/validation/event/EventValidatorTest.java
> +        public void testEventExistByIdValidation_NotFound_throwDataValidationException() {
В лекциях говорилось что использовать snake case в названиях методов не лучшая практика, а так же перемешивание camelCase + snake_case.

2024-09-11 11:50 UTC, Peregruzochka reviewed
Мне не совсем понятно, является ли это хорошей практикой, когда мы для работы с конкретным классом репозитория, работаем только с соответствующим сервисом:
Например: `UserRepository` <-> `UserService`
Могу ли я инжектить в класс UserService другие Repository (например GoalRepository, SkillRepository)?

2024-09-11 11:50 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/validation/event/EventValidator.java
> +        if (!new HashSet<>(ownerSkills).containsAll(eventDto.getRelatedSkills())) {
Можно создать HashSet ранее, для повышения читаемости

2024-09-11 11:50 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +            verify(eventRepository, atLeastOnce()).save(event);
Как будто нет смысла вызвать verify для всех методов. Можно оставить verify для save, т.к. он он отработает только в том случае, если все предыдущие методы будут вызваны.

2024-09-11 11:50 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private List<SkillDto> relatedSkills;
Я бы использовал List<Long> relatedSkillIds, т.к. мы можем передавать сюда только те скиллы, которые есть в базе данных. (Ты как раз проверяешь существуют ли эти скиллы при создании нового евента)

2024-09-11 11:50 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +        }
Я бы добавил when(findEventById(eventId)).thenReturn(true), т.к. необходимо, чтобы внутри delete метода валидация прошла успешно

2024-09-11 11:50 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
Тут не реализована логика, которую нужно было сделать по заданию:
![image](https://github.com/user-attachments/assets/fc5c8b54-38bf-41f8-ad5e-b7285083d519)

2024-09-11 11:50 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/validation/event/EventValidator.java
> +    }
Произошло дублирование кода. Возможно стоит подумать как использовать этот метод в разных ситуациях.

2024-09-11 11:50 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    }
Имеет смысл использовать не `@PathVariable`, а `@RequestParam`, который будет задается в Http-запросе.
Таким образом, нет необходимости прописывать urls в данных мапперах.
Пример того как это делал я в Postman:
![image](https://github.com/user-attachments/assets/a476c40f-6a55-40e8-af05-3d2dc0a186e5)

Скорее всего валидация `@Positive` избыточна. (этот код будут использовать другие разработчики, а не users)
@mrkorolev

2024-09-11 12:13 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private final EventValidator eventValidator;
Как по мне, избыточно выносить логику валидации за рамки сервиса по нескольким причинам:
- сервису нужно поднимать еще один бин на стадии поднятия контекста 
- валидатор использует те же зависимости, что и сервис (одни и те же зависимости разнесены по двум разным бинам)
- логика сервиса разнесена по разным местам (а валидации - бизнес логика твоего сервиса)
- это не удобно читать и тестировать (постоянно перепрыгивать из одного файла в другой)

2024-09-12 13:50 UTC, Murzin34 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/filters")
По опыту предыдущего буткемпа помню, что при использование фильтров нужно ставить `@PostMapping`.

2024-09-12 13:52 UTC, Murzin34 commented on src/test/java/school/faang/user_service/validation/event/EventValidatorTest.java
> +        public void testEventExistByIdValidation_NotFound_throwDataValidationException() {
Именование тестов вопрос холиварный) надо на созвоне спросить и тогда переименую.

2024-09-12 13:55 UTC, Murzin34 commented on src/main/java/school/faang/user_service/validation/event/EventValidator.java
> +        if (!new HashSet<>(ownerSkills).containsAll(eventDto.getRelatedSkills())) {
Поправил.

2024-09-12 13:57 UTC, Murzin34 commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +            verify(eventRepository, atLeastOnce()).save(event);
Надо спросить, но в целом ты прав. Если в указанные в verify методы не отработают тест упадет раньше.

2024-09-12 14:04 UTC, Murzin34 commented on src/main/java/school/faang/user_service/dto/event/EventDto.java
> +    private List<SkillDto> relatedSkills;
Передаю всю сущность SkillDto т.к. в фильтрах использую проверку по имени скилла, а не id. Хотя в целом стоит пожалуй сделать как ты говоришь когда добью маппинг в контроллере.

2024-09-12 14:04 UTC, Murzin34 commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +        }
Косяк, валидацию добавил в последний момент и про тест забыл. Поправил.

2024-09-12 14:24 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
Конкретно эта валидация реализована в `relatedSkillsValidation()`, но я помню, что мы с тобой говорили о какой-то упущенной мной валидации.

2024-09-12 15:14 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    }
Я помню мы с тобой говорили про упущенную мной валидацию, но конкретно здесь валидация реализована в `relatedSkillsValidation() `,а в п.3 таски валидация происходит на уровне ДТО.

2024-09-12 15:17 UTC, Murzin34 commented on src/main/java/school/faang/user_service/validation/event/EventValidator.java
> +    }
Поправил. Оставил `eventExistByIdValidation()`

2024-09-12 15:34 UTC, Murzin34 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    }
Заменил на @RequestParam. По поводу избыточной валидации хорошо или плохо надо спросить на созвоне.

2024-09-12 15:43 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private final EventValidator eventValidator;
Да, по сути валидация в отдельном классе идет как дополнение к сервису, но вопрос все равно спорный, надо будет спросить на созвоне.

2024-09-12 20:03 UTC, 20cognosce requested changes
Скажу больную для тебя вещь - но миллион фильтров и тележка тестов к ним в придачу были напрасны

Использование чужих сервисов убирай. Либо свяжись с ними и зафиксируй общие интерфейсы, а они потом свою реализацию сделают.

Ну и фильтры... 
Если у тебя душа за них болит - ладно, пусть будут

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    @PostMapping("/filters")
Get по смыслу конечно лучше, но  у него не должно быть тела по спецификации
Когда много фильтров, то их передаем в теле, так что уж да, нужен Post

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    }
Почему аннотации @Positive в методе? Валидация должна быть не здесь

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/mapper/event/EventCustomMapper.java
> +public class EventCustomMapper {
Норм, я на работе так же всё руками делаю

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public List<SkillDto> getUserSkillDtoList(Long userId) {
Для чего существует этот метод? Почему такое название

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
Я не понял, почему ты не используешь готовые сервисы других разработчиков, а пишешь свои? Твоя задача по ивентам

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/filters/EventStartDateAfterFilter.java
> +public class EventStartDateAfterFilter implements EventFilter {
Что за жесть с фильтрами, сколько их? Зачем?

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validation/event/EventValidator.java
> +public class EventValidator {
Он неотделимая часть сервиса, рядом в структуре их положи что ли

2024-09-12 20:03 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/event/EventControllerTest.java
> +        verify(eventService, atLeastOnce()).createEvent(eventDto);
почему atLeastOnce
а если будет 2?

2024-09-12 20:03 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/event/EventCustomMapperTest.java
> +        assertEquals(event.getStatus(), eventDto.getStatus());
assertThat().recursiveComparison()

2024-09-12 20:03 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/filters/EventMaxAttendeesLargerFilterTest.java
> +class EventMaxAttendeesLargerFilterTest {
Ты для каждого фильтра тест писал - это безумие

2024-09-12 20:03 UTC, 20cognosce commented on src/test/java/school/faang/user_service/validation/event/EventValidatorTest.java
> +        public void testEventExistByIdValidation_NotFound_throwDataValidationException() {
Это не snake_case, это 3 стадии, описывающие тест
что делаем
что получаем
как реагируем

2024-09-12 20:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        event.setOwner(newEventOwner);
Вот ты юзаешь чужой сервис, реализовав его по-своему
Я вмерджу - а у другого чела конфликт будет

2024-09-12 20:18 UTC, Murzin34 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    }
Убрал `@positive` в контролере. Вот хотели спросить на созвоне про валидацию и в контролере и в ДТО да забыли) ну вообщем теперь понятно что это излишне.

2024-09-12 20:20 UTC, Murzin34 commented on src/main/java/school/faang/user_service/mapper/event/EventCustomMapper.java
> +public class EventCustomMapper {
Спасибо) но я сделал только потому что ошибочно подумал что проблема мапинга в контроллерах именно в MapStruct.

2024-09-12 20:43 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public List<SkillDto> getUserSkillDtoList(Long userId) {
Метод использую для валидации методов EventService `createEvent()` и `updateEvent()`. 
В таске это пункты 1.6 и 5.5:  "Здесь нужно проверить, что пользователь, который создает событие, имеет навыки, связанные с событием." 
Называние Идея подсказала через ctrl+пробел "SkillDtoList" я дополнил дописав "getUser".

2024-09-12 21:08 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/filters/EventStartDateAfterFilter.java
> +public class EventStartDateAfterFilter implements EventFilter {
Нуу на каждое поле в ДТО по фильтру или по два) кроме owner, потому что под него отдельный контролер пишем (п.6 в таске). Это же все равно мое будущее CV, мое будущее резюме, хотя да, ты говорил что фильтры надо писать через нативный SQL, я все равно доволен собой что разобрался в вопросе)
В общем то тут 4 вида фильтров: 
1. Фильтры на поля сущности String
2. Фильтры на поля сущности LocalDateTime
3. Фильтры на поля сущности int
4. Фильтры на поля сущности enum
Что функционал, что тесты для этих видов одинаковый, главное не напутать с вызовами методов.

2024-09-12 21:16 UTC, Murzin34 commented on src/test/java/school/faang/user_service/service/event/filters/EventMaxAttendeesLargerFilterTest.java
> +class EventMaxAttendeesLargerFilterTest {
В общем то тут 4 вида фильтров: 
1. Фильтры на поля сущности String
2. Фильтры на поля сущности LocalDateTime
3. Фильтры на поля сущности int
4. Фильтры на поля сущности enum

Функционал и тесты для одних и тех же видов одинаковый, главное не напутать с вызовами методов.

2024-09-12 21:33 UTC, Murzin34 commented on src/main/java/school/faang/user_service/validation/event/EventValidator.java
> +public class EventValidator {
EventValidator положил в "service.event", пакедж "validation.event" удалил.

2024-09-12 22:09 UTC, Murzin34 commented on src/test/java/school/faang/user_service/controller/event/EventControllerTest.java
> +        verify(eventService, atLeastOnce()).createEvent(eventDto);
Вроде часто используют в VerificationMode=times(1), хотя вроде можно вообще обойтись без него. Писать на манер `verify(eventService).createEvent(eventDto);`, но я на всякий случай пишу atLeastOnce(). 
В некоторых случаях пишу times(*что-то*.size()) как например в EventServiceTest в тесте фильтров.

2024-09-12 22:39 UTC, Murzin34 commented on src/test/java/school/faang/user_service/mapper/event/EventCustomMapperTest.java
> +        assertEquals(event.getStatus(), eventDto.getStatus());
Спасибо! Поправил тесты.

2024-09-13 13:57 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
На данный момент в мастер-ветке нет функционала других ребят. По опыту предыдущего потока, нас, наоборот, пытались столкнуть лбами при мердже файлов, чтобы мы, взаимодействуя друг с другом, решали эту проблему.
Попробовал реализовать интерфейсы, как ты сказал, для фиксирования методов в "сторонних" сервисах, которые использую в своем "профильном" сервисе. Надеюсь, такая реализация устроит. Если нет, то поправлю.

2024-09-13 13:57 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        event.setOwner(newEventOwner);
На данный момент в мастер-ветке нет функционала других ребят. По опыту предыдущего потока, нас, наоборот, пытались столкнуть лбами при мердже файлов, чтобы мы, взаимодействуя друг с другом, решали эту проблему.
Попробовал реализовать интерфейсы, как ты сказал, для фиксирования методов в "сторонних" сервисах, которые использую в своем "профильном" сервисе. Надеюсь, такая реализация устроит. Если нет, то поправлю.

2024-09-13 16:11 UTC, 20cognosce requested changes

2024-09-13 16:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public List<SkillDto> getUserSkillDtoList(Long userId) {
То что сервис отдает DTO для другого сервиса может создать кучу неудобств

2024-09-13 16:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public List<SkillDto> getUserSkillDtoList(Long userId) {
Мне не нравится нейминг
Почему в нейминге ты пишешь и тип возвращаемых данных и коллекцию, какой смысл? Это итак есть в сигнатуре

2024-09-13 16:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private final UserService userService;
Используй UserRepository
UserService полностью удали

2024-09-13 16:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventValidator.java
> +    private final SkillService skillService;
Используй SkillRepository
SkillService полностью удали

2024-09-13 16:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventValidator.java
> +public class EventValidator {
Назови его EventServiceHelper

2024-09-13 16:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/filters/EventDescriptionFilter.java
> +public class EventDescriptionFilter implements EventFilter {
Фильтры убрать из сервиса, вынести их к репозиториям

2024-09-13 16:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/mapper/SkillCustomMapper.java
> +public class SkillCustomMapper {
Почему SkillMapper в package school.faang.user_service.mapper;
а EventMapper в package school.faang.user_service.mapper.event?

Custom тоже лишнее слово

2024-09-13 19:09 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private final UserService userService;
Удалил

2024-09-13 19:09 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventValidator.java
> +    private final SkillService skillService;
Удалил

2024-09-13 19:14 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/filters/EventDescriptionFilter.java
> +public class EventDescriptionFilter implements EventFilter {
Убрал.

2024-09-13 19:14 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventValidator.java
> +public class EventValidator {
Переименовал.

2024-09-13 19:30 UTC, Murzin34 commented on src/main/java/school/faang/user_service/mapper/SkillCustomMapper.java
> +public class SkillCustomMapper {
Сущность Skill лежит в school.faang.user_service.entity, а сущность Event school.faang.user_service.entity.event; 
С репозиториями также. Custom в имени убрал.

2024-09-13 19:45 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public List<SkillDto> getUserSkillDtoList(Long userId) {
Переименовал в getUserSkills и положил в EventService.

2024-09-15 10:23 UTC, 20cognosce approved these changes

2024-09-15 10:23 UTC, merged