BJS2-27008
CorporationX/user_service pull request #1401
Opened 2024-09-05 16:42 UTC by amilosh

- add CRUD endpoints to operate Goals
- add 'find goals' end-points with filters

2024-09-05 19:26 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/goal/GoalValidator.java
> +    private void validate(GoalDto goalDto) {
private методы всегда же ниже публичных? ну либо приватный сразу ниже за публичным, в котором он используется. Или нет?

2024-09-06 00:45 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalValidator.java
> +    private void validate(GoalDto goalDto) {
Исправил.

2024-09-06 06:37 UTC, ilu23ilu23 reviewed
Что нашел - указал)

2024-09-06 06:37 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +import com.fasterxml.jackson.annotation.Nulls;
Серые иморты остались

2024-09-06 06:37 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Гет по спецификации не имеет тела, может Post тогда сделать?

2024-09-06 06:37 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Тоже самое про Post

2024-09-06 06:37 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            }
foreach вместо цикла можно

2024-09-06 06:37 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +    @Size(max = 128, message = "Description cannot be longer than 64 characters", groups = {Create.class, Update.class})
Максимальный размер 128, а в сообщении указано только 64

2024-09-06 19:19 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +import com.fasterxml.jackson.annotation.Nulls;
Исправил.

2024-09-06 19:20 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +    @Size(max = 128, message = "Description cannot be longer than 64 characters", groups = {Create.class, Update.class})
Исправил.

2024-09-06 19:22 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            }
Исправил.

2024-09-06 19:33 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Убрал @RequestBody. Спринг умеет скукоживать параметры из url в объект.

2024-09-08 17:07 UTC, 20cognosce requested changes

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalValidator.java
> +    private final SkillRepository skillRepository;
Нет. 
Валидатор не должен ни в какую базу ходить и что-то из неё тащить для проверки, эта вся логика должна быть в сервисах.

Валидация - проверка полей на смысловую корректность относительно доменной области.

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void createGoal(@RequestBody @Validated(Create.class) GoalDto goalDto) {
@Validated(Create.class) - что это?

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/validation/group/Create.java
> +public interface Create {
?

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/validation/group/Update.java
> +public interface Update {
?

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void updateGoal(@RequestBody @Validated(Update.class) GoalDto goalDto) {
Что это за маркерные интерфейсы для круда, зачем они?

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        var goal = goalMapper.toEntity(goalDto);
Прошу максимально редко юзать var

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void updateGoal(@RequestBody @Validated(Update.class) GoalDto goalDto) {
@PatchMapping

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public List<GoalDto> findSubGoalsByParentGoalId(@PathVariable Long parentGoalId, GoalFilterDto filter) {
Сейчас у тебя 3 параметра фильтрации, а потом будет 23
И это всё будет в урле?
Давай в тело класть и через Post-запрос делать

В урле я за то чтобы передавать только общеизвестные параметры страницы - number, asc/desc

Всё что относится к доменной области лучше прятать от юзера

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public List<GoalDto> findGoalsByUser(@PathVariable long userId, GoalFilterDto filter) {
Аналогично

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/mapping/GoalMapper.java
> +    protected SkillRepository skillRepository;
1. @Autowired - может никак не предупредить если бин окажется null, лучше конструктор для надежности
2. Почему твой маппер общается с репозиториями? Это разный логический уровень приложения.
Маппер DTOшек это уровень представления
Репозитории это уровень данных

protected Goal mapGoalIdToGoal(Long id) - такого тут вообще не должно быть

Что может смапить - мапь, что не можешь, например id - передавай их в сервис

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +    int update(Long goalId, String title, String description, Long parent, int status);
Почему ты все CRUDы переписал на нативные запросы??
Используй готовые методы JpaRepository, свои собственные запросы надо писать когда есть тонкая логика какая-то, а такой апдейта - это громоздко и избыточно

Другие методы тоже упростить и использовать готовое

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            goal.getTitle(), goal.getDescription(), goal.getParent() == null ? null : goal.getParent().getId());
.create(goal);

переделать

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        goalRepository.update(goal.getId(), goal.getTitle(), goal.getDescription(),
update(goal);

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        }
Что тут происходит?
Ты обновил цель, и потом что-то происходит, совсем не очевидное что

+Транзакция нужна, если это связанные действия

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        }
Аналогично, что всё это?
Проще должно быть и понятнее

Если связанные действия - транзакция 
@Transactional

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    }
Должен быть публичный метод поиска цели

2024-09-08 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    }
По максимуму это вынести в публичные методы чтобы не было так, что у тебя 3 публичных метода по одной строчке

и 23 приватных метода которые переворачивают всё с вверх головой, что ничего не разобрать, что происходит

2024-09-08 17:07 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        verify(skillRepository, times(0)).assignSkillToUser(anyLong(), anyLong());
Что это за проверки?
Ты должен тестировать метод как черный ящик - только сравнение выходного значения с ожидаемым результатом, да, на crud'ах тут нет почти никакой логики, но тем не менее - times(0) - это то, что мне не нравится.

Зачем проверять, что что-то не вызывалось? Это нелогично

2024-09-09 00:31 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalValidator.java
> +    private final SkillRepository skillRepository;
Перенес в сервисы.

2024-09-09 00:35 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        var goal = goalMapper.toEntity(goalDto);
убрал

2024-09-09 00:38 UTC, amilosh commented on src/main/java/school/faang/user_service/mapping/GoalMapper.java
> +    protected SkillRepository skillRepository;
Сделал.

2024-09-09 00:38 UTC, amilosh commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +    int update(Long goalId, String title, String description, Long parent, int status);
Сделал.

2024-09-09 00:39 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            goal.getTitle(), goal.getDescription(), goal.getParent() == null ? null : goal.getParent().getId());
сделал через save(goal)

2024-09-09 00:39 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        goalRepository.update(goal.getId(), goal.getTitle(), goal.getDescription(),
сделал через findById
потом save

2024-09-09 00:40 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        }
переделал

2024-09-09 00:40 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        }
переделал

2024-09-09 00:41 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    }
сделал

2024-09-09 00:41 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    }
вынес

2024-09-09 00:41 UTC, amilosh commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        verify(skillRepository, times(0)).assignSkillToUser(anyLong(), anyLong());
убрал

2024-09-10 18:47 UTC, 20cognosce requested changes

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        Goal createdGoal = goalService.createGoal(goal, dto.getUserId(), dto.getParentGoalId(), dto.getSkillIds());
Лучше объявлять переменные

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/entity/goal/Goal.java
> +import static school.faang.user_service.entity.goal.GoalStatus.ACTIVE;
?

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/exception/constants/ErrorMessage.java
> +    }
@UtilityClass

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/exception/handler/RestExceptionHandler.java
> +        var errorResponse = ErrorResponse.builder()
var - лучше избегать и писать полностью класс

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        }
Почему у тебя в этом классе есть еще метод findById, не находишь это дублированием кода?

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        Goal parentGoal = parentGoalId != null ? findById(parentGoalId) : null;
Ты это уже проверял

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        List<Skill> skills = skillIds != null ? skillRepository.findByIds(skillIds) : null;
Почему в валидации нельзя все null проверить и очистить метод этот этого?

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        goalMapper.update(goal, existedGoal);
Не понял. Почему маппер управляет обновлением сущностей?
Делай всё тут руками

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    public Goal updateGoal(Goal goal, List<Long> skillIds) {
Можно порефакторить эти методы? сделать более компактными и структурированными

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    public Goal updateGoal(Goal goal, List<Long> skillIds) {
Транзакция нужна -  @Transactional

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    public void deleteGoal(Long goalId) {
Транзакция

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            .forEach(goal -> goalRepository.deleteById(goal.getId()));
Интересно, а если у детей этой goalId есть свои дети?
Кажется тут нужна неограниченная вложенность, пока у родителя есть дети

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        Stream<Goal> subGoalsByParentGoal = goalRepository.findByParent(parentGoalId);
Почему репозиторий возвращает стрим? Это зачем

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        Stream<Goal> subGoalsByParentGoal = goalRepository.findByParent(parentGoalId);
Лучше на список переделать и только тут брать стрим

2024-09-10 18:47 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        assertEquals("Skills from request are not presented in DB", exception.getMessage());
Сообщение можно не проверять мне кажется, просто класс исключения

2024-09-10 18:47 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        assertEquals(createdGoal.getId(), result.getId());
А почему только id?
AssertThat() recursive comparison
по всем полям попробуй

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +@Transactional
А, ты на весь класс навесил
Это не хорошо - любой публичный метод в транзакцию пихать автоматически, ну такое

2024-09-10 18:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    private final GoalMapper goalMapper;
Вообще не должно быть зависимости на маппер у сервиса
Это разные логические слои

2024-09-10 22:01 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        Goal createdGoal = goalService.createGoal(goal, dto.getUserId(), dto.getParentGoalId(), dto.getSkillIds());
Вынес.

2024-09-10 22:03 UTC, amilosh commented on src/main/java/school/faang/user_service/entity/goal/Goal.java
> +import static school.faang.user_service.entity.goal.GoalStatus.ACTIVE;
Экспериментировал.
Не доглядел убрать.

2024-09-10 22:04 UTC, amilosh commented on src/main/java/school/faang/user_service/exception/constants/ErrorMessage.java
> +    }
Заюзал.

2024-09-10 22:05 UTC, amilosh commented on src/main/java/school/faang/user_service/exception/handler/RestExceptionHandler.java
> +        var errorResponse = ErrorResponse.builder()
Убрал.
Больше не буду.

2024-09-10 22:10 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        }
Да, есть такой метод. Но ошибка "Goal not found". Я хочу бросить. что именно "Parent Goal not found".
Создал ещё один метод со вторым String параметром.

2024-09-10 22:16 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        Goal parentGoal = parentGoalId != null ? findById(parentGoalId) : null;
Вынес засечивание parentGoal и его проверку в одно место.
Стало красивше.

2024-09-10 22:19 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        List<Skill> skills = skillIds != null ? skillRepository.findByIds(skillIds) : null;
Для skillIds не надо на null валидировать. Там только существование килов в базе проверка. skillIds могут быть как null так какие-то значения.
И если skillIds - null, то и в Gaol set skills тоже null подставлять.

2024-09-10 22:36 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +@Transactional
Перенес только на методы, которые вызываются в конроллере.

2024-09-10 22:39 UTC, amilosh commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        assertEquals("Skills from request are not presented in DB", exception.getMessage());
Убрал сообщения про Skills.
Где фигурирует Goal id - оставил.

2024-09-10 22:53 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            .forEach(goal -> goalRepository.deleteById(goal.getId()));
Я это на потом оставил.
Мне надо день потратить, чтобы понять как по рекурсии все удалить.

2024-09-10 23:12 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        Stream<Goal> subGoalsByParentGoal = goalRepository.findByParent(parentGoalId);
Добавил методы в репозиторий, чтобы вернуть List.

2024-09-10 23:27 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            .forEach(goal -> goalRepository.deleteById(goal.getId()));
А всё, нашел. У нас уже есть готовые запросы с рекурсией.

2024-09-10 23:42 UTC, amilosh commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        assertEquals(createdGoal.getId(), result.getId());
Прикольная штука. Буду знать.

2024-09-11 17:14 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    private final GoalMapper goalMapper;
Убрал.

2024-09-11 17:14 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    public Goal updateGoal(Goal goal, List<Long> skillIds) {
Не понимаю как.

2024-09-11 17:15 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +        goalMapper.update(goal, existedGoal);
Поменял на сеттеры.

2024-09-12 13:53 UTC, 20cognosce approved these changes

2024-09-12 13:53 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +            """)
Выглядит жестко
Надеюсь работает как задумано

2024-09-12 13:53 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +            orElseThrow(() -> new ResourceNotFoundException("User", userId));
. со следующей строки

2024-09-12 13:53 UTC, merged