BJS2-27385 Совместная работа над целью
CorporationX/user_service pull request #1409
Opened 2024-09-06 19:17 UTC by ArstanSubanov

2024-09-06 21:16 UTC, SharkB38 commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +    @PositiveOrZero(message = "inviterId must be a positive number or zero")
А почему @PositiveOrZero, вроде идшники идут с 1?

2024-09-06 21:24 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private static final int MAX_ACTIVE_GOALS = 3;
Может это в конфиг вынести или типо того?

2024-09-06 21:32 UTC, SharkB38 requested changes

2024-09-06 21:32 UTC, SharkB38 commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    }
Разве BAD_REQUEST не лучше сюда подходит?

2024-09-06 21:38 UTC, SharkB38 commented
Хорош, много нового узнал из твоего кода

2024-09-06 22:34 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +@Slf4j
Для чего тут аннотация Slf4j? Тут же нигде log не используется или это где-то неявно происходит?

2024-09-06 22:35 UTC, wmwmaks commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +
пустая строка, если я понял, две подряд не надо делать)

2024-09-07 12:37 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +@Slf4j
Да, не заметил оказывается, спасибо, уберу

2024-09-07 12:38 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +
Хорошо, спасибо)

2024-09-07 12:45 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +    @PositiveOrZero(message = "inviterId must be a positive number or zero")
Да, я думал об этом, хотел сначала поставить аннотацию @Positive, но потом подумал, что хотя автоинкримент начинается с 1, в таблице 0 может быть айдишником, поэтому поставил эту аннотацию) Редко, но  я видел пару раз небольшие таблицы, где id начинались с нуля. Не в этом проекте конечно)

2024-09-07 12:45 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    }
Да, спасибо, исправлю)

2024-09-07 12:49 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private static final int MAX_ACTIVE_GOALS = 3;
Я подумал что в конфиг лучше вынести константы, которые могу использоваться в нескольких местах, а эту переменную я использую только в этом классе. Я ещё подумаю над этим, скорее всего вынесу в следующем ПР, спасибо)

2024-09-07 14:11 UTC, SharkB38 approved these changes

2024-09-07 14:21 UTC, wmwmaks approved these changes
Прикольно сделал валидацию в Dto через Pattern👍 У нас еще такого не видел) Интересно, что Маша на это скажет)

2024-09-09 23:06 UTC, mysosnovskaya requested changes
Хорошая работа получилась) Только обрати внимание на излишнюю декомпозицию на методы. Такой код становится тяжелее понимать, методы слишком маленькие и далеко не всегда понятная необходимость их выделять

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +@Slf4j
Ещё актуально)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +
Лишняя пустая строчка =)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public GoalInvitationDto acceptGoalInvitation(@RequestParam long id) {
Интересно, почему здесь и в следующем методе ты выбрал RequestParam, а не PathVariable? Мы эту тему ещё не проходили, поэтому изменений не ожидаю, но в целом PathVariable здесь лучше подходит на мой взгляд

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +
Да, две подряд не делаем, для отделения блоков кода одной достаточно)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +    @PositiveOrZero(message = "inviterId must be a positive number or zero")
Согласна, что id всегда с 1. С нуля - это какой-то очень экзотичный случай, я такого на практике не видела)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +    @NotNull(message = "inviterId can't be null")
Круто, что ты знаком с такой валидацией 👍

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/goal/InvitationFilterDto.java
> +    @Pattern(regexp = "^$|\\S+", message = "inviterNamePattern must not be empty, but can be null")
С паттерном классно придумал, но по-моему тут что-то не то) У тебя в паттерне написано "пустая строка или строка из символов" - т.е. пустая строка это ок. А в описании ошибки написано, что строка не должна быть пустой. Или это я не поняла?

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    }
Тоже согласна

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +        final List<Violation> violations = e.getConstraintViolations().stream()
Круто 👍

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Куда-то единообразие потерялось. Я бы предпочла везде через ResponseStatus делать, а ResponseEntity вообще не использовать. Не вижу в нем необходимости, только код усложняет)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/goal/GoalInvitationMapper.java
> +    @Mapping(source = "inviter.id", target = "inviterId")
Я бы пустую строчку оставила перед аннотацией, чтобы визуально отделить начало кода этого метода

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    GoalInvitationDto acceptGoalInvitation(@PositiveOrZero long id);
Может быть просто acceptInvitation и rejectInvitation? В двух других методах ты не пишешь Goal

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/invitation_filter/InvitationInvitedFilter.java
> +    @Override
Я рекомендую оставлять пустые строчки между перед первым методом в классе, когда полей нет. И визуально отделить, и в будущем будет удобнее, если понадобится поля добавить.

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/invitation_filter/InvitationInviterFilter.java
> +public class InvitationInviterFilter implements InvitationFilter {
InvitationInviterNameFilter?

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private static final int MAX_ACTIVE_GOALS = 3;
Да, обычно любые такие конфигурационные параметры выносят в конфиг, чтобы можно было обновить значения без пересборки приложения (значения обычно берутся извне, даже не из ресурсов). Поэтому соглашусь с комментарием, но отмечу, что это пока очень сильно забегая вперед =) Поэтому настаивать на исправлении не буду, для текущего этапа константы тоже подойдут

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +public class GoalInvitationServiceImpl implements GoalInvitationService {
В классе не хватает логов

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +        User invited = goalInvitation.getInvited();
invitedUser будет лучше

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +                .reduce(
Попробуй через flatMap - посимпатичнее будет)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private List<GoalInvitation> getAllGoalInvitations() {
Не думаю, что нужен отдельный метод для одной строчки. Я не вижу в нем смысла на данный момент)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private GoalInvitation createRejectedGoalInvitation(long id) {
Тоже не понимаю, почему нельзя эту логику оставить в основном публичном методе? Метод rejectGoalInvitation совсем небольшой, сейчас в нем три строчки. Ещё три не сделают его сложным. Ты сейчас пишешь код, забегая вперед, пытаясь предсказать будущее. Но мы не пытаемся улучшить код, пока это не понадобилось. Если сейчас нет явного преимущества выделения кода в отдельный метод, то не нужно этого делать, нужно оставить так, как есть. Когда метод rejectGoalInvitation будет из 15-20 строчек кода состоять, тогда и подумаем, какую часть в какой метод будет лучше вынести)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private GoalInvitation saveAcceptedGoalInvitation(GoalInvitation goalInvitation) {
Аналогично предыдущему

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private boolean isGoalAvailable(long goalId) {
Здесь тоже. Согласилась бы, если бы эта логика много где была бы нужна, но сейчас метод вызывается всего лишь в одном месте. Как будто бы даже не упрощение, а усложнение происходит)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private void addUserToGoal(Goal goal, User user) {
Аналогично

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private boolean checkIsGoalSuitableToAdd(User user, Goal goal) {
Вместо Is правильно будет If

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +        return !user.getGoals().contains(goal) && user.getGoals().size() < MAX_ACTIVE_GOALS;
Вот с этим методом соглашусь. Оставлять такую сложную строчку кода в основном методе было бы не читаемо, а так ты вынес логику в отдельный метод с понятным названием, тем самым упростив код основного метода. Так что этот метод оправдан)

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private GoalInvitation getGoalInvitation(GoalInvitationDto goalInvitationDto) {
Этот тоже не стала бы выделять

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +    private void checkUsersIdEquality(Long invitedId, Long inviterId) {
checkIfUsersIdEqual

2024-09-09 23:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/GoalInvitationServiceImpl.java
> +
Лишняя пустая строчка)

2024-09-13 18:40 UTC, mysosnovskaya requested changes
Совсем чуть-чуть и будем мержить)

2024-09-13 18:40 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/invitation/GoalInvitationServiceImpl.java
> +    private boolean checkIsGoalSuitableToAdd(User user, Goal goal) {
checkIfGoalSuitableToAdd

2024-09-13 18:40 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/invitation/GoalInvitationServiceImpl.java
> +@Validated
Точно ли нужно дублировать эту аннотацию, если она уже есть в интерфейсе? И остальные аннотации для валидации тоже?

2024-09-13 18:40 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/invitation/GoalInvitationDtoValidationTest.java
> +    private Validator validator;
Отличное решение для тестирования аннотаций 👍

2024-09-13 18:40 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/invitation/GoalInvitationDtoValidationTest.java
> +    }
Для полноты картины ещё хотелось бы увидеть тест, где сразу несколько нарушений присутствует

2024-09-13 18:40 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/invitation/GoalInvitationServiceImplTest.java
> +    @Mock
Думаю, через Spy будет лучше, так ещё и маппер протестируем по пути)

2024-09-14 20:07 UTC, mysosnovskaya approved these changes

2024-09-14 20:07 UTC, merged