Solution task BJS2-27193 (Participate in the event), subtask - Get th…
CorporationX/user_service pull request #1411
Opened 2024-09-06 19:59 UTC by ALEH-BIAHUN

…e number of event participants.

2024-09-07 08:16 UTC, dmitridorje commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +@Component
@Controller или @RestController

2024-09-07 08:20 UTC, dmitridorje commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +@Component
Для сервиса также принята "собственная" аннотация "@ Service".

2024-09-07 08:56 UTC, dmitridorje commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +}
Наверное, на метод сервиса тоже нужен тест.

2024-09-07 09:03 UTC, dmitridorje commented on src/test/java/school/faang/user_service/service/EventParticipationControllerTest.java
> +}
Обычно еще пишется тест, в котором проверяется какой-либо отрицательный сценарий работы методы.

2024-09-09 19:49 UTC, mikhailov26 requested changes

2024-09-09 19:49 UTC, mikhailov26 commented on src/test/java/school/faang/user_service/service/EventParticipationControllerTest.java
> +}
Абсолютно согласен с Дмитрием, написать пару тестов на негативный сценирий работы

2024-09-09 19:49 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +}
Абсолютно верно, нужен тест

2024-09-09 19:49 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
Добавить валидацию на входящие данные @NonNull и подобные аннотации Lombok'а помогут

2024-09-11 16:51 UTC, merged