Фича "Подписка на других пользователей"
CorporationX/user_service pull request #1412
Opened 2024-09-06 20:10 UTC by RuslanIovlev

Пункты Получить всех подписчиков и Просмотреть свои подписки находятся в доработке.

2024-09-09 15:38 UTC, dossymbekov approved these changes

2024-09-09 15:47 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/dto/filter/ExperienceMaxFilter.java
> +        return filter.getExperienceMax() <= 0;
ту же может быть null вроде

2024-09-09 15:47 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/dto/filter/ExperienceMinFilter.java
> +    }
тут тоже может быть null вроде

2024-09-09 15:55 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/dto/filter/NameFilter.java
> +    }
мне кажется здесь можно было к регистру одинаковому привести

2024-09-09 15:57 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/dto/filter/CountryFilter.java
> +    }
Мне кажется здесь к регистру одинаковому можно привести

2024-09-09 16:02 UTC, DankeVilletti reviewed
Оставил коменты впервые, если все правильно, то их будет видно:)

2024-09-09 23:08 UTC, mysosnovskaya commented
> Оставил коменты впервые, если все правильно, то их будет видно:)

Да, всё видно) Молодец! Начало положено)

2024-09-09 23:44 UTC, mysosnovskaya requested changes

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        if (!(followerId == followeeId)) {
Вообще за валидацию входных данных отвечает сервис. Я вижу, что в задаче написано про валидацию в контроллере, но скорее всего это ошибка. Поэтому предлагаю перенести логику в сервис, так будет правильнее)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        if (!(followerId == followeeId)) {
С точки зрения читаемости лучше написать followerId != followeeId

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    public void getFollowersCount(long followerId) {
Тут должен быть не void, а количество =) Рекомендую сделать отдельный dto класс с одним полем count и вернуть его здесь. В будущем станет понятнее, почему именно так, но если коротко: нам важно, чтобы методы нашего сервера на фронтенд возвращали данные в одинаковом формате (json), а это возможно только тогда, когда все методы будут возвращать объекты (не примитивы и их обертки типа int и Integer, а именно объекты обычных классов). Также допустимо использовать void в методах, которые по логике ничего не должны возвращать (как у тебя followUser и unfollowUser)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +public class UserDto {
Давай используем java records здесь?) Они очень часто подходят именно для dto классов

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/filter/AboutFilter.java
> +public class AboutFilter implements UserFilter{
Пробела не хватает)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/filter/ContactFilter.java
> +        return users.filter(user -> String.valueOf(user.getContacts()).contains(filter.getContactPattern()));
Оригинально через String.valueOf делать такое =) Обычно через stream()...anyMatch() делают. Если честно, даже не хочется исправлять, хотя в реальном проекте такое решение не увидишь, т.к. результат фильтрации может быть неожиданным: если в `filter.getContactPattern()` будет, например, такая строчка: "1, 2", а `String.valueOf(user.getContacts())` выдаст "[11, 22]". Поэтому исправить всё-таки нужно)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/filter/CountryFilter.java
> +    }
Да, такой вопрос нужно задавать аналитику, но в целом звучит логично, что регистр имеет значение в этой ситуации

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/filter/ExperienceMaxFilter.java
> +        return filter.getExperienceMax() <= 0;
В данной ситуации getExperienceMax не может вернуть null, т.к. в UserFilterDto это поле типа int. Но! По требованиям задачи это поле (и все другие) из UserFilterDto должны иметь возможность быть null. Поэтому, во-первых, нужно обновить UserFilterDto так, чтобы все поля могли быть null, а во-вторых, здесь необходимо это учесть. Это отличный комментарий, Данил)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/filter/ExperienceMinFilter.java
> +    }
Тут аналогично experienceMax

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/filter/NameFilter.java
> +    }
Зависит от требований, бывает по-разному) Выглядит логичным использовать один регистр

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        } else {
else можно не писать, чтобы не повышать уровень вложенности кода

```
        if (subscriptionRepository.existsByFollowerIdAndFolloweeId(followerId, followeeId)) {
            throw new DataValidationException("Validation exception");
        }
        subscriptionRepository.followUser(followerId, followeeId);
```

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public List<UserDto> getFollowers(long followeeId, UserFilterDto filters) {
Метод нужно протестировать, в текущем виде он не будет работать)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        return users.map(user -> new UserDto(user.getId(), user.getUsername(), user.getEmail()))
А mapstruct не захотел использовать? Очень рекомендую, т.к. на реальных проектах маппинг руками почти никогда не делают)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +public class SubscriptionControllerTest {
Тесты в этом классе практически не несут никакой практической значимости. Особенно если ты вынесешь валидацию в сервис (как я писала выше), то все эти тесты потеряют смысл =( Контроллеры крайне редко тестируют юнит тестами (как у тебя сейчас), для них есть другой вид тестирования, который мы здесь ещё не проходили. Поэтому я думаю, что эти тесты можно удалить полностью. Но ты не расстраивайся, в любом случае попрактиковался тесты писать) Нам важно развить этот навык до автоматизма, и этот класс - это один шаг в нужную сторону =)

2024-09-09 23:44 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +    private NameFilter nameFilter;
Кажется, сейчас это работает не так, как ты ожидаешь) В subscriptionService не будет этого мока, там поле userFilters будет равно null

2024-09-09 23:44 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        subscriptionService.unFollowUser(followerId, followeeId);
Можно использовать assertDoesNotThrow и verify, чтобы в тесте были какие-то проверки

2024-09-09 23:44 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        assertEquals("Ruslan", followers.get(0).getUsername());
Обычно по id сравнивают, т.к. имя в теории может измениться, а id - никогда

2024-09-09 23:44 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(nameFilter.apply(any(), any())).thenAnswer(invocation -> {
Круто с thenAnswer сделал 👍 Только лучше это дело не мокать, а заставить работать по-настоящему. Т.е. в subscriptionService подставить настоящий NameFilter и пусть он отфильтрует, как умеет

2024-09-09 23:44 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        assertEquals(0, result.size());
Лучше, конечно, чтобы что-то осталось) Так можно будет проверить код, а то вдруг сейчас он вообще всех отфильтровывает))

2024-09-13 09:17 UTC, RuslanIovlev commented on src/main/java/school/faang/user_service/dto/filter/ContactFilter.java
> +        return users.filter(user -> String.valueOf(user.getContacts()).contains(filter.getContactPattern()));
не могу понять как через anymatch делать

2024-09-13 09:34 UTC, RuslanIovlev commented on src/main/java/school/faang/user_service/dto/filter/ExperienceMaxFilter.java
> +        return filter.getExperienceMax() <= 0;
Так в условии же написано что они примитивы

2024-09-13 12:00 UTC, RuslanIovlev commented on src/main/java/school/faang/user_service/dto/filter/ContactFilter.java
> +        return users.filter(user -> String.valueOf(user.getContacts()).contains(filter.getContactPattern()));
Я понял, ура

2024-09-15 16:00 UTC, RuslanIovlev commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(nameFilter.apply(any(), any())).thenAnswer(invocation -> {
Я не понимаю, как заставить это метод работать, вест день с ним мучаюсь

2024-09-15 16:10 UTC, RuslanIovlev commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +    }
Я не понимаю как заставить его работать, я уже запутался

2024-09-16 09:17 UTC, mysosnovskaya requested changes
В целом всё хорошо, отличные тесты на фильтры, молодец 👍  Но фильтрацию в сервисе нужно заставить работать. Комментарий об этом написала, но если не получится, то приходи с вопросом в чат, будем разбираться)

2024-09-16 09:17 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/filter/ContactFilterTest.java
> +        UserFilterDto filter = mock(UserFilterDto.class);
Как будто бы мок делать необязательно, ты же можешь создать фильтр со всеми полями = null или с каким-то одним заданным полем. Но давай чтобы всё не переделывать, оставим так)

2024-09-16 09:17 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +    }
У тебя ошибка в сервисе, а не в тесте) Рекомендую освежить знания по стримам (в частности про терминальные операторы и результат стрима)

2024-09-16 12:35 UTC, RuslanIovlev commented
Подсмотрел немного, но я бы сам не додумался бы

2024-09-16 17:55 UTC, mysosnovskaya requested changes
Написала один маленький комментарий в тестах) После него - точно будем мержить

2024-09-16 17:55 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        assertEquals(2, followers.size());
Лучше всё-таки убедиться, что вернулись именно те два пользователя, которых мы ожидали. Для этого нужно сравнить id из followers с ожидаемыми

2024-09-17 08:58 UTC, mysosnovskaya approved these changes

2024-09-17 08:58 UTC, merged