Стать ментором
CorporationX/user_service pull request #1419
Opened 2024-09-07 16:09 UTC by IvanTsegelnyuk

mentorship get/delete methods

2024-09-08 07:39 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +                .toList();
Мне кажется .stream()
                .toList(); можно упустить, потому что метод гетМенис уже возвращает коллекцию.

2024-09-08 07:39 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +                .toList();
Точно так же, стрим ту лист можно убрать.

2024-09-08 07:39 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipServiceImpl.java
> +                );
Тут дублирование кода получается с методом ниже, может вынести в приватный метод(условие поставить какое-нибудь и в зависимости от условия фильтровать и выбрасывать стринг.формат ошибки)?

2024-09-08 16:33 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +@RequestMapping("mentorship")
@RequestMapping("/mentorship")

2024-09-08 16:40 UTC, amilosh commented on src/main/java/school/faang/user_service/exception/UserNotFoundException.java
> +public class UserNotFoundException extends RuntimeException{
пробел скобка

2024-09-08 16:47 UTC, amilosh commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceImplTest.java
> +    private final Long notExistingId = 20L;
я в статические константы переносил

2024-09-08 16:49 UTC, amilosh commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceImplTest.java
> +        assertThrows(
ещё message ошибки можно проверить

2024-09-13 18:19 UTC, 20cognosce requested changes

2024-09-13 18:19 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +        return userMentorshipMapper.toDtos(mentorshipService.getMentees(userId));
Не в одну строку, объявляй переменную

2024-09-13 18:19 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/mentorship/UserMentorshipDto.java
> +    private Integer experience;
Валидации нет?

2024-09-13 18:19 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceImplTest.java
> +                && user.getMentees().containsAll(result)
Лучше как две assert'a

2024-09-13 18:19 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/mentorship/MentorshipServiceImplTest.java
> +        );
сообщение проверять смысла большого нет
но тут ты id прям знаешь, это хорошо

2024-09-13 18:19 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/mentorship/UserMentorshipDto.java
> +    private Integer experience;
Должна быть

2024-09-13 23:01 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/dto/mentorship/UserMentorshipDto.java
> +    private Integer experience;
Это Дто на респонз. На респонз же не нужна валидация, если я правильно понимаю?

2024-09-18 19:02 UTC, 20cognosce approved these changes

2024-09-18 19:02 UTC, merged