chimera-6-participate-in-event-BJS2-27006
CorporationX/user_service pull request #1421
Opened 2024-09-07 17:25 UTC by natalia-dch

- **register**
- **unregister**
- **getParticipants**
- **getParticipantsCount**
- **to REST**
- **tests**

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +        eventParticipationService.registerParticipant(eventId, userDto.getId());
В контроллер приходит дто, но дальше в сервис передается только id из всего дто, без валидаций каких-либо на дто. Проще вместо дто принимать просто id

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +        eventParticipationService.unregisterParticipant(eventId, userDto.getId());
то же самое

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @GetMapping(path = "/{eventId}/getParticipants")
/participants

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @GetMapping(path = "/{eventId}/getParticipantsCount")
/participants-count

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +@AllArgsConstructor
RequiredArgsConstructor принято

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                eventRepository.findAllParticipantsByEventId(eventId).stream().anyMatch(e -> userId == e.getId());
в приватный метод isRgistered(), и его использовать ниже в условии 
if (isRegistered()) {}

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                eventRepository.findAllParticipantsByEventId(eventId).stream().anyMatch(e -> userId == e.getId());
if (!isRegistered()) {}

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +            throw new IllegalArgumentException("user is already registered");
IllegalArgumentException понимается, как недопустимое значение аргумента. типа отрицательный ид, или строка вместо числа и т.п.  Тут  лучше наверно кидать свое какое-то

2024-09-07 19:43 UTC, IvanTsegelnyuk commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
импорты без *

2024-09-08 08:04 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +import jakarta.transaction.Transactional;
Если мы работаем в спринг бут, то лучше аннотацию использовать спрингбутовскую(импорт лучше поменять)

2024-09-08 08:04 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                eventRepository.findAllParticipantsByEventId(eventId).stream().anyMatch(e -> userId == e.getId());
после .stream()
лучше переносить строку ниже для лучшей читаемости

2024-09-08 08:04 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                eventRepository.findAllParticipantsByEventId(eventId).stream().anyMatch(e -> userId == e.getId());
Точно так же после стрим перенос строки

2024-09-08 13:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +import jakarta.transaction.Transactional;
'+'

2024-09-08 13:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +        eventParticipationService.registerParticipant(eventId, userDto.getId());
'+'

2024-09-08 13:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @GetMapping(path = "/{eventId}/getParticipants")
'+'

2024-09-08 13:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public List<User> getParticipants(long eventId) {
Можно добавить `@Transactional(readOnly = true)`, что бы явно обозначить что метод только получает данные, и как раз комент выше от Ивана, о том что лучше импортировать спринговый `@Transactional` в помощь, в не сприноговом такого метода нет

2024-09-08 13:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        return eventRepository.countParticipants(eventId);
`@Transactional(readOnly = true)`

2024-09-08 13:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +@AllArgsConstructor
'+'

2024-09-08 13:31 UTC, sultan-inked commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Если оно так автоматически происходит, то на платформе есть инструкция как настроить:
https://faang-school.com/courses/g89z8bzp/xjz7r9xd

2024-09-08 13:31 UTC, sultan-inked commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +    static final int COUNT = 1;
Я бы вынес константы на самый верх, вроде так принято

2024-09-08 16:22 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +public class EventParticipationController {
Если задача стоит про работу именно с event participations то сделай /event-participations
А то ("/events") - это REST для Event сущности

2024-09-08 16:24 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public void registerParticipant(@PathVariable("eventId") long eventId, @RequestBody UserDto userDto) {
UserDto - это для crud операций я юзером.
Тут наверное переименуй, чтобы было связано с event participation

2024-09-08 16:30 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +        eventParticipationService.registerParticipant(eventId, userDto.getId());
@PostMapping(path = "/{eventId}/register/{userId}")

2024-09-12 05:57 UTC, natalia-dch commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public void registerParticipant(@PathVariable("eventId") long eventId, @RequestBody UserDto userDto) {
В методах регистрации вообще убрала и не использую Dto, но переименовывать пока не стала — «в задании так было написано»🙃
Подожду контрольного выстрела от Димы.

2024-09-13 17:26 UTC, 20cognosce requested changes

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +package school.faang.user_service.controller.event;
ci.yaml в этом ПРе быть не должно

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public void registerParticipant(@PathVariable("eventId") long eventId, @PathVariable("userId") long userId) {
2 @PathVariable - не гуд
юзерИд передавай как query

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public void registerParticipant(@PathVariable("eventId") long eventId, @PathVariable("userId") long userId) {
Ну и регистрации по смыслу ближе к Put

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @PostMapping(path = "/{eventId}/unregister/{userId}")
Зачем писать path?

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @PostMapping(path = "/{eventId}/unregister/{userId}")
PutMapping

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public int getParticipantsCount(@PathVariable("eventId") long eventId) {
Ну можно в json формате отдавать ответ?)

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    private String email;
Валидации нужны?

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/event/EventRepository.java
> +}
Что поменялось?_

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +@Component
@Service, в след лекции расскажут

2024-09-13 17:26 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        return eventRepository.findAllParticipantsByEventId(eventId).stream().anyMatch(e -> userId == e.getId());
А можно прям одним запросов из базы получить ответ, без ручного прохождения по стриму

2024-09-13 17:26 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        assertDoesNotThrow(() -> eventParticipationService.registerParticipant(EVENT_ID, NEW_USER_ID));
А можно проверить что что-то делается по существу?

2024-09-13 17:26 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        assertDoesNotThrow(() -> eventParticipationService.registerParticipant(EVENT_ID, NEW_USER_ID));
verify может хотя бы

2024-09-13 17:26 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +    }
Это не мок, это просто объект
Почему не вынести как поле класса?

2024-09-16 06:28 UTC, natalia-dch commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +package school.faang.user_service.controller.event;
Случайно. Убрала

2024-09-16 06:35 UTC, natalia-dch commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    private String email;
Какие валидации? Где их писать?

2024-09-23 19:11 UTC, 20cognosce commented
Ну ты же видишь, что ПР падает, зачем его на ревью кидать?

Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'userMapperImpl' for bean class [school.faang.user_service.mapping.UserMapperImpl] conflicts with existing, non-compatible bean definition of same name and class [school.faang.user_service.mappers.UserMapperImpl]

2024-09-25 15:56 UTC, 20cognosce approved these changes

2024-09-25 15:56 UTC, 20cognosce commented on src/main/java/school/faang/user_service/mappers/UserMapper.java
> +public interface UserMapper {
Caused by: org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'userMapperImpl' for bean class [school.faang.user_service.mapping.UserMapperImpl] conflicts with existing, non-compatible bean definition of same name and class

2024-09-25 15:56 UTC, merged