BJS2-26997 Запрос рекомендации
CorporationX/user_service pull request #1422
Opened 2024-09-07 17:34 UTC by cemeh666

2024-09-08 08:58 UTC, IvanTsegelnyuk reviewed
Отступы, переносы везде поправить нужно

2024-09-08 08:58 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public CreateRecommendationResponseDto createRequestRecommendation(
В CreateRecommendationResponseDto только одно поле id. Может вместо dto отдавать Long? и это дто удалить, если оно только для этого ответа использовалось.

2024-09-08 08:58 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    }
как-то не читаемо.
лучше так:

    public CreateRecommendationResponseDto createRequestRecommendation(
            @Valid @RequestBody CreateRecommendationRequestDto createRecommendationRequest) {
        var entity = mapper.toEntity(createRecommendationRequest);
        var skills = recommendationRequest.getSkills();
        Long recommendationRequestId = recommendationRequestService.create(entity, skills);

        return new CreateRecommendationResponseDto(recommendationRequestId);
    }
А если дто удалить, то еще лучше

2024-09-08 08:58 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        @ModelAttribute
зачем ModelAttribute в rest контроллере?

2024-09-08 08:58 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        var result = this.recommendationRequestService.getRecommendationRequests(filterRecommendationRequestsDto);
this при обращении к своим полям не нужно

2024-09-08 08:58 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/repository/recommendation/SkillRequestRepository.java
> +    /** @TODO Modifying queries can only use void or int/Integer as return type*/
todo убрать

2024-09-08 08:58 UTC, IvanTsegelnyuk commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +import static org.mockito.Mockito.*;
импорты без *

2024-09-08 09:21 UTC, kripersh27 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        @ModelAttribute
В гет запросах лучше использовать @RequestParam

2024-09-08 09:21 UTC, kripersh27 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            this.mapper.toEntity(createRecommendationRequest),
this, мне кажется, можно не писать, она не добавляет функциональности, зато читаемость лучше становится(ниже в коде тоже есть, выделять их не буду)

2024-09-08 09:21 UTC, kripersh27 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @PutMapping("{id}/reject")
Тут лучше сделать @PatchMapping, потому что ресурс будет частично обновляться, а не полностью.

2024-09-08 09:21 UTC, kripersh27 commented on src/main/java/school/faang/user_service/dto/recomendation/CreateRecommendationRequestDto.java
> +@Data
Дату лучше не писать, она добавляет излишние ненужные методы, лучше вместо неё @Getter и @Setter добавить

2024-09-08 09:21 UTC, kripersh27 commented on src/main/java/school/faang/user_service/dto/recomendation/CreateRecommendationResponseDto.java
> +}
Мне кажется, что в ответ на запрос рекомендации можно вернуть чуть больше информации, а не только id, но это лучше уточнить, и убрать дату

2024-09-08 09:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        return result.stream().map(this.mapper::toDto).toList();
Чтоб не писать логику преобразования данных в методе контроллера, лучше в маппере создать метод, который это делает и в контроллере вызывать его

2024-09-08 09:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestMapper.java
> +public interface RecommendationRequestMapper {
Маппер лучше вынести из сервисного слоя в отдельный пакет

2024-09-08 09:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestMapper.java
> +        return skills != null ? skills.stream().map(s -> s.getSkill().getId()).toList() : new ArrayList<>();
Для лучшей читаемости после .stream() 
.лучше переносить методы
.в отдельную строчку

2024-09-08 09:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +@Component
Для сервисов есть свою компонент-аннотация @Service, лучше использовать её

2024-09-08 09:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +@Data
@Data в JPA лучше не использовать

2024-09-08 09:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +}
У тебя уже есть метод RecommendationRequest findRequestById(Long id), который ищет по айди, можно эту логику перенести туда, его же и использовать в других методах, приватный метод тут не нужен)
И вместо if можно использовать .orElseThrow, лучше читаемость будет

2024-09-08 09:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +public class RecommendationRequestService {
Можно еще логирование добавить @SLF4J и в каждом методе писать логи

2024-09-08 13:45 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public CreateRecommendationResponseDto createRequestRecommendation(
Это общее ДТО планируется для ответа на создание других сущностей

2024-09-08 13:48 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    }
зачем выносить entity и skills  в переменные если они используются ровно 1 раз?

2024-09-08 13:48 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        @ModelAttribute
собирает query параметры в ДТО

2024-09-08 13:49 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        var result = this.recommendationRequestService.getRecommendationRequests(filterRecommendationRequestsDto);
this для читабельности, что это переменная класса, а не метода

2024-09-08 13:50 UTC, cemeh666 commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +import static org.mockito.Mockito.*;
скажи почему со * плохо?

2024-09-08 13:57 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        @ModelAttribute
@RequestParam собирает параметры по одному, а @ModelAttribute сразу в ДТО

2024-09-08 14:03 UTC, cemeh666 commented on src/main/java/school/faang/user_service/dto/recomendation/CreateRecommendationResponseDto.java
> +}
обычно возвращается только id созданной записи.
@Data убрал

2024-09-08 14:06 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    }
Согласен с Иваном, лучше в одну строку

2024-09-08 14:06 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/recomendation/CreateRecommendationRequestDto.java
> +@Data
А лучше просто использовать `record`, ничего лишнего не придется писать, имхо

2024-09-08 14:06 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +    public List<RecommendationRequest> getRecommendationRequests(
Можно аннотировать `@Transactional(readOnly = true)`, улучшает восприятие, и однозначно говорит хиберу что метод только получает данные

2024-09-08 14:06 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +    public RecommendationRequest findRequestById(Long id) {
`@Transactional(readOnly = true)`

2024-09-08 14:06 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/recomendation/filters/RecommendationRequestMessageFilter.java
> +        FilterRecommendationRequestsDto filter
Параметры лучше в одну строку, так сложно читать, например:
```
@Override
public Stream<RecommendationRequest> apply(Stream<RecommendationRequest> requestStream,
                                          FilterRecommendationRequestsDto filter) {
    return requestStream.filter(
        recommendationRequest -> recommendationRequest.getMessage().contains(filter.getMessage())
    );
}
```

2024-09-08 14:06 UTC, sultan-inked commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +import static org.mockito.Mockito.*;
Если оно так автоматически происходит, то на платформе есть инструкция как настроить:
https://faang-school.com/courses/g89z8bzp/xjz7r9xd

2024-09-08 14:17 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +}
вынес логику в **findRequestById**

2024-09-08 14:20 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/recomendation/filters/RecommendationRequestMessageFilter.java
> +        FilterRecommendationRequestsDto filter
ох. что-то в одну строку мне совсем не нравится и не читается. Думаю Дима рассудит)

2024-09-08 14:24 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    }
@sultan-inked мне вот совсем не нравится как выглядит в одну строку(

2024-09-08 14:24 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            this.mapper.toEntity(createRecommendationRequest),
this для читабельности, что это переменная класса, а не метода

2024-09-08 14:25 UTC, cemeh666 commented on src/main/java/school/faang/user_service/dto/recomendation/CreateRecommendationRequestDto.java
> +@Data
@sultan-inked что за **record**? не нашёл такой аннотации

2024-09-08 15:39 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            this.mapper.toEntity(createRecommendationRequest),
Я никогда this не использую.

Только когда есть параметр метода или переменная внутри метода с таким же названием как поле класса.

2024-09-08 15:46 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    }
Очень тяжело чужой код читается
когда есть метод и в качестве пареметров - вызовы других методов

2024-09-08 15:48 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        @ModelAttribute
Спринг без @ModelAttribute сбирает.
Можно убрать.

2024-09-08 15:49 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        var result = this.recommendationRequestService.getRecommendationRequests(filterRecommendationRequestsDto);
Создай голосовалку в чате.

2024-09-08 15:52 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        RejectRecommendationRequestDto rejectionDto
А почему так сделал?

2024-09-08 15:53 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        var result = this.recommendationRequestService.getRecommendationRequests(filterRecommendationRequestsDto);
я думаю победит без использования this, так как похоже только я так пишу...

2024-09-08 15:53 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/recomendation/CreateRecommendationRequestDto.java
> +    @Length(max = 4096, message = "Maximum number of characters")
В message добавь 4096, чтобы клиент знал.

2024-09-08 15:55 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/recomendation/RecommendationRequestDto.java
> +    @NotNull(message = "Requester Id can't be empty")
Requester Id can't be **null**

2024-09-08 15:56 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        RejectRecommendationRequestDto rejectionDto
что именно?

2024-09-08 15:56 UTC, amilosh commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    public ResponseEntity<Object> handleValidationException(RuntimeException ex) {
ValidationException

2024-09-08 15:59 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +                : new ArrayList<>();
Я использую паттерн: сначала все исключительные ситауации, а потом нормальное выполнение.
if (skills == null) {
    return new ArrayList<>();
}

return skills.stream()
                .map(s -> s.getSkill().getId())
                .toList()

2024-09-08 16:01 UTC, cemeh666 commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +                : new ArrayList<>();
переделал по твоему примеру. так читабельнее будет

2024-09-08 16:04 UTC, amilosh commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +    @Transactional(readOnly = true)
Тут наверное если мы вызываем этот метод из другого метода, то новая транзакция не создается.
Чтобы применилась readOnly = true нужно propagation RequiredNew
но мы будем это ещё изучать

2024-09-08 16:06 UTC, amilosh commented on src/main/java/school/faang/user_service/service/recomendation/filters/RecommendationRequestMessageFilter.java
> +        return filter.getMessage() != null && !filter.getMessage().isBlank();
а если я создал recomendation с двумя пробелами
и потом хочу найти и исправить

2024-09-08 16:07 UTC, amilosh commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +        Long receiverId = recommendationRequest.getReceiver().getId();
В клин коде рекомендуют тройные вызовы скукоживать в один метод.

2024-09-08 16:23 UTC, cemeh666 commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +        Long receiverId = recommendationRequest.getReceiver().getId();
что имеешь в виду не совсем понял?

2024-09-10 19:15 UTC, 20cognosce requested changes

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +@RequestMapping("recommendation/request")
1. Можно покороче?
2. recommendations (множественное)
3. помимо request другие действия планируются?

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public CreateRecommendationResponseDto createRequestRecommendation(
Короче назови метод - просто create

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    ) {
Это в одну строку всё
Название dto можно тоже сделать коротким именем, и всё влезет

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            this.mapper.toEntity(createRecommendationRequest),
Результат вызова маппера - отдельная переменная
this - лишнее

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        return new CreateRecommendationResponseDto(recommendationRequestId);
Почему ты отдаешь только id? Заставляешь фронт тебе на поиск еще отправить сразу же?
Отдавай DTO созданной сущности со всеми полями.

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            createRecommendationRequest.getSkills()
Тоже в переменную, мне непонятно, какой это тип данных

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @GetMapping("search")
/search
По спецификации Open API у гет запросов нет тела - юзай пост

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        var result = this.recommendationRequestService.getRecommendationRequests(filterRecommendationRequestsDto);
var убираем
this убираем
filterRecommendationRequestsDto укорачиваем

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @GetMapping("{id}")
/{id}

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        return this.mapper.toDto(
Объявить переменную на результат вызова сервиса

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @PatchMapping("{id}/reject")
reject - комплексное действие, а не просто обновление
лучше Put

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        RejectRecommendationRequestDto rejectionDto
В одну строчку пожалуйста

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        rejectionDto.setId(id);
?

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        );
переменная

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        );
В сервис сущность, не dto

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    ) {
Зачем ты сгенерировал 3 строчки вместо 1

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +        return requests.stream().map(this::toDto).toList();
не в одну строку

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/recommendation/SkillRequestRepository.java
> +    int create(long requestId, long skillId);
Не, это легкий путь
Сущность отдавай

ищи способ

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +    public Long create(RecommendationRequest recommendationRequest, List<Long> skillIds) {
Request - это DTO или сущность? Пиши у DTO постфикс, чтобы понятно было

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +@Data
Зачем эта аннотация?

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +    public void validateCreateRecommendationRequest(RecommendationRequest recommendationRequest, List<Long> skills) {
skills - это id, не сущности
skillIds

2024-09-10 19:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +        }
Зачем ты второй раз ходишь в базу, если выше проверял уже isExist
Сразу достань сущность и смотри, в Optional, есть она или нет
Если есть - дальше проверяй

2024-09-10 19:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +        verify(this.recommendationRequestRepository).save(recommendationEntity);
нужно 3 блока кода:
Arrange - создаешь все что надо сразу, прописываешь моки
Act - один вызов
Assert - сравнение

2024-09-10 19:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +        verify(this.recommendationRequestRepository).save(recommendationEntity);
Сейчас тут нет структуры

2024-09-10 19:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +        verify(this.recommendationRequestRepository, times(0)).save(any(RecommendationRequest.class));
достаточно ошибку проверить

2024-09-10 19:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +        );
оууу как плохо...
Что ты проверяешь в этом тесте?
То что сам тут же и замокал)))))))

2024-09-10 19:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +        verify(this.recommendationRequestRepository).save(recommendationRequest);
Попробуй проверять не просто вызов, а последствия этого вызова
что вернулось
что-то обновилось

Если это возможно, такие тесты что проверяют?

2024-09-10 19:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +        verify(this.recommendationRequestRepository).save(recommendationRequest);
аааа, стоп
ты статус обновляешь

то-то я не различил сразу.

РАЗНЫЕ сущности заводи на arrange и assert, не надо модифицировать один объект

2024-09-10 19:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +                                .build()
Можно эти сущности проинициализировать заранее в конструкторе теста, статическом блоке или в @Before методе?
И переиспользовать для каждого теста, а не создавать в каждом тесте

2024-09-10 19:16 UTC, 20cognosce commented
Кодстайл пожалуйста

2024-09-11 06:37 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +@RequestMapping("recommendation/request")
В бд есть сущность recommendation, а тут именно запрос на эту сущность. в БД recommendation_request.
Поэтому так

2024-09-11 06:47 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @GetMapping("search")
зачем мне POST? я в ДТО собераю query параметры из запроса

2024-09-11 07:55 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +    public Long create(RecommendationRequest recommendationRequest, List<Long> skillIds) {
recommendationRequest это сущность. не ДТО

2024-09-11 08:24 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        rejectionDto.setId(id);
чтобы проще в entity перегнать

2024-09-11 12:34 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/recomendation/CreateRecommendationRequestDto.java
> +@Data
Вот так выглядит:
```java
public record CreateRecommendationRequestDto(
    @NotBlank(message = "Message can't be blank or empty")
    @Length(max = 4096, message = "Maximum number of characters")
    private String message,
    @NotEmpty(message = "Skills can't be empty")
    private List<Long> skills,
    @NotNull(message = "Requester Id can't be empty")
    private Long requesterId,
    @NotNull(message = "Receiver Id can't be empty")
    private Long receiverId) {
}
```

2024-09-11 13:13 UTC, cemeh666 commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +        );
вынес проверку валидатора отдельно

2024-09-12 14:11 UTC, 20cognosce approved these changes
Про валидатор сомнительно, ну окей
Рядом с сервисом его переложи и переименуй

Кодстайл местами корёжит

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    ) {
Пиши в одну строчку

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    ) {
Тут окей, очень длинный параметр
но ) { я бы оставил на 62

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/recomendation/RecommendationRequestService.java
> +    ) {
bruh
filterRecommendationRequestsDto -> reqFilter

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/recomendation/filters/RecommendationRequestIdFilter.java
> +    ) {
Aoaoaoaoaoaoaoaoaaaaaa
Прекрати

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +    private final RecommendationRequestRepository recommendationRequestRepository;
Validator проверяет поля на смысловую корректность

он не должен ни в какую базу ходить

Тогда это не валидатор - Helper, Service или как-нибудь еще

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +        this.checkSkillsExists(skillIds);
Смысл ты это тут делаешь, если сразу после вызова этих методов состояние базы могло измениться

Значит это должно только в транзакции вызываться, тогда этот метод - не самостоятелен

Тогда почему он не часть сервиса

2024-09-12 14:11 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/recommendation_request/RecommendationRequestServiceTest.java
> +    private RecommendationRequestValidator validator;
Ты мокаешь часть кода, которая отвечает за бизнес-логику сервиса

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +                );
Почему такой кодстайл...

2024-09-12 14:11 UTC, 20cognosce commented on src/main/java/school/faang/user_service/validator/RecommendationRequestValidator.java
> +        this.checkSkillsExists(skillIds);
@Transactional(Mandatory)

2024-09-12 14:12 UTC, merged