Запрос на менторство BJS2-27001
CorporationX/user_service pull request #1424
Opened 2024-09-08 07:46 UTC by vestmen

Реализовал:
- Отправить запрос на менторство
- Получить все запросы на менторство по фильтрам
- Принять запрос на менторство
- Отклонить запрос на менторство

2024-09-08 08:20 UTC, natalia-dch commented
Вроде как пакеты/директории обычно пишутся в snake_case.
ref https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html

2024-09-08 09:06 UTC, natalia-dch commented on src/test/java/school/faang/user_service/service/mentorshipRequest/MentorshipRequestServiceTest.java
> +    void testRequestByIdNotFound() {
А почему у rejectRequest это не проверяешь?

2024-09-08 10:38 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/mentorshipRequest/MentorshipRequestController.java
> +        mentorshipRequestService.rejectRequest(id, rejection.getReason());
В задании написано "Внутри метода нужно вызвать метод rejectRequest(id, rejection) класса MentorshipRequestService". Ты передаешь просто одно поле String

2024-09-08 15:08 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/mentorshipRequest/MentorshipRequestController.java
> +@RequestMapping("mentorship_requests")
mentorship-requests

Вроде через дефисы говорилось писать.

2024-09-08 15:26 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/mentorshipRequest/MentorshipRequestController.java
> +    public void rejectRequest(@PathVariable long id, @RequestBody RejectionDto rejection) {
Наверное полное название дай для 
RejectionDto
а то для других сущностей тоже вероятно есть реджекшены
чтобы не путаться

2024-09-08 15:27 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/mentorshipRequest/MentorshipRequestMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = org.mapstruct.ReportingPolicy.IGNORE)
org.mapstruct.ReportingPolicy.IGNORE
static import

2024-09-08 15:30 UTC, amilosh commented on src/main/java/school/faang/user_service/service/mentorshipRequest/MentorshipRequestService.java
> +        mentorshipRequest.setStatus(RequestStatus.REJECTED);
я на енамы статические импорты всегда использую

кроме случаев, когда два енама имеют одинаковой значение

2024-09-08 15:32 UTC, amilosh commented on src/main/java/school/faang/user_service/service/mentorshipRequest/MentorshipRequestService.java
> +                });
Я тут пододи использую с ReourceNotFoundException
и логированием в @ControllerAdvice
можешь посмотреть в моём репозитории
может быть понравится

2024-09-09 07:56 UTC, vestmen commented on src/main/java/school/faang/user_service/controller/mentorshipRequest/MentorshipRequestController.java
> +        mentorshipRequestService.rejectRequest(id, rejection.getReason());
RejectionDto содержит в себе только поле String reason, в сервисе я его в метод передаю и id, а в контроллере - id и RejectionDto

2024-09-09 08:02 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorshipRequest/MentorshipRequestService.java
> +        mentorshipRequest.setStatus(RequestStatus.REJECTED);
Да, я в других местах так и сделал, тут пропустил, спасибо

2024-09-10 19:45 UTC, 20cognosce requested changes
Вполне чистый код

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/mentorship_request/MentorshipRequestController.java
> +    @GetMapping
Post, потому что у гет нет тела по спецификации open api

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/mentorship_request/MentorshipRequestController.java
> +                mentorshipRequestDto.getDescription());
Почему только 3 поля, для кого в ДТО есть все остальные?

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +        if (mentorshipRequestRepository.existAcceptedRequest(requesterId, receiverId)) {
Так внутри if не делать, переменную объяви

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +public class MentorshipRequestParametersChecker {
Helper
не Validator как ты его назвал в service

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +        log.info("Mentorship request from user with id {} to user with id {} created", requesterId, receiverId);
Бро, много логов
Реально перебор...

Не логируй каждую строчку, и в checker тоже
Только нужное

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +        log.info("Request with id {} accepted", id);
Жесть с логами

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +    public void acceptRequest(long id) {
А ты проверил работу этого метода?
Ты изменил
requester.getMentors().add(receiver);
mentorshipRequest.setStatus(ACCEPTED); 

Но в базу нифига не сохранил

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +    public void acceptRequest(long id) {
вместо void возвращай результат из БД

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +    public void rejectRequest(long id, String reason) {
Аналогично, ты ничего не сделал

2024-09-10 19:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/error_messages/MentorshipRequestErrorMessages.java
> +public class MentorshipRequestErrorMessages {
@UtilityClass

2024-09-10 19:45 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/mentorship_request/MentorshipRequestMapperTest.java
> +        assertEquals(mentorshipRequestDto.getUpdatedAt(), mentorshipRequest.getUpdatedAt());
AssertThat()
recursive comparison

2024-09-10 19:48 UTC, 20cognosce requested changes

2024-09-10 19:48 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +        }
if else для лога - это очень неоправданно

2024-09-10 19:48 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/mentorship_request/MentorshipRequestServiceTest.java
> +        assertEquals(mentorshipRequest.getRejectionReason(), reason);
проверяй что в базу сохраняется обновленная сущность

2024-09-11 09:40 UTC, vestmen commented on src/main/java/school/faang/user_service/controller/mentorship_request/MentorshipRequestController.java
> +                mentorshipRequestDto.getDescription());
Для создания запроса пользователь передает только 3 параметра, статус и время генерируются сами, а для запроса по фильтрам пользователю необходимо отдать все параметры запроса, включая статус и время

2024-09-11 09:41 UTC, vestmen commented on src/main/java/school/faang/user_service/controller/mentorship_request/MentorshipRequestController.java
> +    @GetMapping
переделал

2024-09-11 09:41 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +        log.info("Request with id {} accepted", id);
убрал часть

2024-09-11 09:43 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +    public void acceptRequest(long id) {
вернул запрос, и использовал метод save, но я проверял через Postman запрос меняется и без его явного сохранения в БД, так же и у юзера появляется связь меторства

2024-09-11 09:44 UTC, vestmen commented on src/test/java/school/faang/user_service/mapper/mentorship_request/MentorshipRequestMapperTest.java
> +        assertEquals(mentorshipRequestDto.getUpdatedAt(), mentorshipRequest.getUpdatedAt());
Переделал

2024-09-11 09:46 UTC, vestmen commented on src/test/java/school/faang/user_service/service/mentorship_request/MentorshipRequestServiceTest.java
> +        assertEquals(mentorshipRequest.getRejectionReason(), reason);
переделал

2024-09-11 09:51 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
> +        log.info("Mentorship request from user with id {} to user with id {} created", requesterId, receiverId);
исправил

2024-09-11 09:52 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +public class MentorshipRequestParametersChecker {
исправил

2024-09-11 09:54 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +        }
Переделал

2024-09-11 09:54 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +        if (mentorshipRequestRepository.existAcceptedRequest(requesterId, receiverId)) {
переделал

2024-09-11 09:57 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/error_messages/MentorshipRequestErrorMessages.java
> +public class MentorshipRequestErrorMessages {
переделал

2024-09-12 14:30 UTC, 20cognosce approved these changes

2024-09-12 14:30 UTC, 20cognosce commented on src/test/java/school/faang/user_service/mapper/mentorship_request/MentorshipRequestMapperTest.java
> +        MentorshipRequestDto mentorshipRequestDto = mentorshipRequestMapper.toDto(mentorshipRequest);
Про Builder не забывай

2024-09-12 14:30 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/mentorship_request/MentorshipRequestServiceTest.java
> +    private void verifySaveRequest(MentorshipRequest mentorshipRequest) {
Зачем плодить отдельный метод на одну строчку?

2024-09-12 14:30 UTC, merged