BJS2-27009 task perform
CorporationX/user_service pull request #1426
Opened 2024-09-08 11:12 UTC by sultan-inked

2024-09-08 13:09 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/SkillRepository.java
Не мои изменения, после мержа появились, не понял почему

2024-09-08 13:09 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/event/EventParticipationRepository.java
Это тоже не мое

2024-09-08 13:10 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
И это не мое

2024-09-08 14:24 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +@RequestMapping("goal/invitations")
Без первых слэшей работает? ("/goal/invitations")
Если да, то наверное спринг подставляет.
Но мне привычней, когда слэш стоит.

2024-09-08 14:26 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public ResponseEntity<GoalInvitationDto> createInvitation(@Valid @RequestBody GoalInvitationDto invitationDto) {
Можно просто GoalInvitationDto возвращать. Современный спринг по дефолту конвертит в Json.

А created можно аннотацией вернуть
@ResponseStatus(CREATED)

2024-09-08 14:29 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public ResponseEntity<List<GoalInvitationDto>> getInvitations(@RequestBody InvitationFilterDto filter) {
Тут надо обсуждать.
Но вроде по конвенции, если делаешь get, то все параметры через url надо передавать, а не через боди. Если убрать @RequestBody то спринг скукоживает эти параметры в объект.

А если оставлять @RequestBody то тогда post нужно.

2024-09-08 14:32 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationControllerAdvice.java
> +    @ExceptionHandler(InvitationEntityNotFoundException.class)
Пусть пока так будет.
Но в будущем у меня есть предложение ипользовать общий экзепшн типа ResourceNotFoundException.
Когда будем мержить в общую ветку нужно будет обсудить.

2024-09-08 14:43 UTC, amilosh commented on src/main/java/school/faang/user_service/entity/User.java
> +    @ManyToMany(mappedBy = "users"/*, cascade = CascadeType.ALL, fetch = FetchType.EAGER*/)
А ты тестировал, что будет, если мы удалим юзера с помощью CrudRepository.delete(T entity);

Удалятся только записи из user_goal?
Или все Goals (на которые подписан юзер) по каскаду удалятся?

2024-09-08 14:50 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationControllerAdvice.java
> +    @ExceptionHandler(InvitationEntityNotFoundException.class)
Да, согласен, надо общую делать

2024-09-08 14:54 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +    public static final int USER_GOALS_LIMIT = 3;
Эта пропертя выглядит как общая для всего приложения.
Лучше вынести в константы.

Я вынес её в applicatio.yaml, чтобы можно было быстро изменить просто рестартом приложения без изменения кода.

2024-09-08 14:58 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +        invitationEntity.setInviter(userRepository.findById(inviterId).orElseThrow(() ->
Не знаю что Дима и коллеги скажут, но мне неудобно так читать код.

Я всегда делаю:
var inviter = userRepository.findById...
invitationEntity.setInviter(iviter);

2024-09-08 14:59 UTC, amilosh commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +                new InvitationEntityNotFoundException(INVITED_USER_NOT_FOUND_MESSAGE_FORMAT, invitedUserId)));
userRepository.findById(invitedUserId).orElseThrow(() ->
                new InvitationEntityNotFoundException(INVITED_USER_NOT_FOUND_MESSAGE_FORMAT, invitedUserId)));

Я вынес в приватный метод
User findById(Long id) {
    return userRepository.findById(invitedUserId).orElseThrow(() ->
                new InvitationEntityNotFoundException(INVITED_USER_NOT_FOUND_MESSAGE_FORMAT, invitedUserId)));
}

2024-09-08 16:13 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/User.java
> +    @ManyToMany(mappedBy = "users"/*, cascade = CascadeType.ALL, fetch = FetchType.EAGER*/)
Не удаляет

2024-09-08 16:13 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public ResponseEntity<GoalInvitationDto> createInvitation(@Valid @RequestBody GoalInvitationDto invitationDto) {
Изменил, спасибо

2024-09-08 16:14 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public ResponseEntity<List<GoalInvitationDto>> getInvitations(@RequestBody InvitationFilterDto filter) {
Согласен, так лучше

2024-09-08 16:17 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +    public static final int USER_GOALS_LIMIT = 3;
Сделаю

2024-09-08 16:21 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +        invitationEntity.setInviter(userRepository.findById(inviterId).orElseThrow(() ->
Спасибо, да, так лучше читается

2024-09-08 16:25 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +                new InvitationEntityNotFoundException(INVITED_USER_NOT_FOUND_MESSAGE_FORMAT, invitedUserId)));
'+'

2024-09-08 16:41 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +@RequestMapping("goal/invitations")
Работает, но все же изменил, теперь буду ставить

2024-09-10 20:17 UTC, 20cognosce requested changes

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +        var goalInvitation = goalInvitationService.createInvitation(goalInvitationMapper.toEntity(invitationDto),
var стараться не использовать, непонятно, какой тип данных

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +        var goalInvitation = goalInvitationService.createInvitation(goalInvitationMapper.toEntity(invitationDto),
toEntity - результат в переменную

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @PatchMapping("/accept/{id}")
По смыслу accept/reject - комплексное действие, не просто апдейт
Лучше Put

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @ResponseStatus(HttpStatus.FOUND)
Что за статус? 
302 FOUND
Redirection messages (300 – 399)

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +    }
private методы - вниз

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +        invitationEntity.setGoal(goal);
логов больше чем действий, почему всё слеплено?

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +        var goal = invitation.getGoal();
var убирай

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +        invitation.setStatus(RequestStatus.ACCEPTED);
Ты ничего в базу не сохранил, этот метод ничего не сделал

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
> +        invitation.setStatus(RequestStatus.REJECTED);
Аналогично

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/filter/invitation/InvitedNamePatternFilter.java
> +                invitation.getInvited().getUsername().toLowerCase().contains(filters.invitedNamePattern().toLowerCase()));
Не жести

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/filter/invitation/InviterNamePatternFilter.java
> +                invitation.getInviter().getUsername().toLowerCase().contains(filters.inviterNamePattern().toLowerCase()));
Рефактори

2024-09-10 20:17 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/util/GoalInvitationErrorMessages.java
> +public class GoalInvitationErrorMessages {
@UtilityClass

2024-09-10 20:17 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/goal/GoalInvitationControllerAdviceTest.java
> +    private AutoCloseable closeable;
Зачем ты мокаешь исключения
И что ты делаешь в @InjectMocks?
AutoCloseable зачем в тесте понадобился...

2024-09-10 20:17 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/goal/GoalInvitationControllerAdviceTest.java
> +        var response = goalInvitationControllerAdvice
var ((((

2024-09-10 20:17 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/goal/GoalInvitationControllerAdviceTest.java
> +    }
Объясни, что ты делаешь

2024-09-10 20:17 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/goal/GoalInvitationControllerTest.java
> +    }
?

2024-09-10 20:17 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/goal/GoalInvitationControllerTest.java
> +        assertThat(goalInvitationController.createInvitation(invitationDto)).isNotNull()
Можно было поля проверять?

2024-09-10 20:17 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalInvitationServiceTest.java
> +        assertThat(invitation.getStatus()).isEqualTo(RequestStatus.REJECTED);
Ты проверил, что изменил поле объекта
Но в базу ты ничего не засейвил

2024-09-11 10:11 UTC, sultan-inked commented
Все замечания исправил

2024-09-13 17:40 UTC, 20cognosce approved these changes

2024-09-13 17:40 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public List<GoalInvitationDto> getInvitations(InvitationFilterDto filter) {
filter - @RequestBody
Post, потому что у Get по спеке нет тела

2024-09-13 17:40 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/goal/GoalInvitationControllerTest.java
> +    private GoalInvitationController goalInvitationController;
Контроллер мало смысла тестировать юнит тестами
Он тестируется интеграционными

2024-09-13 17:41 UTC, merged