feature-BJS2-27186 recommendations
CorporationX/user_service pull request #1427
Opened 2024-09-08 12:16 UTC by Rashit86

2024-09-08 13:00 UTC, musachev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    //FIXME: по задаче этот метод обрабатывает запрос и предоставляет кол-во подписчиков (что за кол-во подписчиков?)
Что это значит? Это где такое?

2024-09-08 13:02 UTC, musachev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +//FIXME: предложения скилла не является обязательным (это странно, т.к метод нужен, чтобы добавить в список
Судя по всему это 2 отдельные процедуры. Я могу дать тебе рекомендацию. А могу стать гарантом к скилу. Потому 2 репозитория участвует в процессе.

2024-09-08 13:08 UTC, musachev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    private static void checkIfContentEmpty(RecommendationDto recommendationDto) {
А зачем этот метод статический?

2024-09-08 13:09 UTC, musachev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +            throw new DataValidationException("Mismatched id in the URL and the body");
Этот блок не покрыт тестами. А надо бы, чтобы красиво было)

2024-09-08 13:18 UTC, musachev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void checkIfAcceptableTimeForRecommendation(RecommendationDto recommendationDto) {
А что будет, если я никогда не оставлял рекомендацию? Я пройду проверку или получу исключение?

2024-09-08 13:33 UTC, musachev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void addSkillOffersAndGuarantee(RecommendationDto recommendationDto) {
Фух, 7 раз перечитал! А может как-то разбить метод на части, чтобы было нагляднее,  что происходит, а то итератор, в нем обращения к бд, выведение булевых, сборка билетером в зависимости от условий. И он кстати не покрыт полностью тестами, видимо какие-то части упустил. Короче, я бы разбил, так как очень сложно читать и понимать.

2024-09-08 13:39 UTC, musachev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        Recommendation recommendation = recommendationRepository.findById(recommendationDto.getId()).orElseThrow(() -> new NoSuchElementException(
А вот тут я не понял. А может быть такое, что не будет в бд рекомендации, которую мы только что создали?

2024-09-08 16:24 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    //FIXME: по задаче этот метод обрабатывает запрос и предоставляет кол-во подписчиков (что за кол-во подписчиков?)
FIXME - это такой вид комментария-вопроса к лиду. Еще есть TODO это для себя коммент. Такие комменты идея подсвечивает синим. В прод они попадать не должны конечно

2024-09-08 16:26 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +//FIXME: предложения скилла не является обязательным (это странно, т.к метод нужен, чтобы добавить в список
Не понял что ты имеешь ввиду

2024-09-08 16:29 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +            throw new DataValidationException("Mismatched id in the URL and the body");
Да, там на самом деле все искличетельные ситуации не покрыты, и их много)

2024-09-08 16:31 UTC, musachev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    //FIXME: по задаче этот метод обрабатывает запрос и предоставляет кол-во подписчиков (что за кол-во подписчиков?)
Да не. я имел ввиду где в задаче ты увидел условие про количество подписчиков?

2024-09-08 16:33 UTC, musachev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +//FIXME: предложения скилла не является обязательным (это странно, т.к метод нужен, чтобы добавить в список
В твоем методе создания рекомендации есть 3 параметра: кто оставляет, кому, и текст. Это обязательные поля для создания рекомендации. 
В случае со скилом, мы делаем проверку - есть указание на скил? Если нет, то это просто рекомендация юзеру.

2024-09-08 16:54 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        Recommendation recommendation = recommendationRepository.findById(recommendationDto.getId()).orElseThrow(() -> new NoSuchElementException(
Мало ли, вдруг БД глюканет или еще что. Пусть будет думаю

2024-09-08 16:57 UTC, musachev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        Recommendation recommendation = recommendationRepository.findById(recommendationDto.getId()).orElseThrow(() -> new NoSuchElementException(
В таком случае кажется лучше try catch на блок навернуть. Потому что она может и при сохранении глюкануть. Получается разорванная логика

2024-09-09 13:45 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    //FIXME: по задаче этот метод обрабатывает запрос и предоставляет кол-во подписчиков (что за кол-во подписчиков?)
В 5-м пункте вроде, или 10-м, поиском находится по слову "подписч" )) Вчера подсветил Владу, он сказал, что копипаста по ошибке попала

2024-09-09 13:47 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        Recommendation recommendation = recommendationRepository.findById(recommendationDto.getId()).orElseThrow(() -> new NoSuchElementException(
На созвоне обсуждали, что пока хендлеры не вешаем, исключения выбрасываем, но не обрабатываем

2024-09-09 19:27 UTC, mikhailov26 requested changes

2024-09-09 19:27 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    }
Нарушение принципа единой ответственности, контроллер нужен чтобы по ендпоинтам дёргать те или иные сервисы с передаваемыми данными, проведи рефакторинг. Можно в методах контроллера использовать аннотации @NonNull/ @NotBlank и тд.

2024-09-09 19:27 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void checkIfAcceptableTimeForRecommendation(RecommendationDto recommendationDto) {
Согласен с Максимом

2024-09-11 07:26 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +            throw new DataValidationException("Mismatched id in the URL and the body");
всё покрыл

2024-09-11 07:26 UTC, Rashit86 commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    }
исправил

2024-09-11 07:27 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void addSkillOffersAndGuarantee(RecommendationDto recommendationDto) {
отрефакторил

2024-09-11 07:33 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void checkIfAcceptableTimeForRecommendation(RecommendationDto recommendationDto) {
Я исправил сразу после того как Максим подсветил. Получется, если optional.isPresent, то мы заходим в блок, который проверяет условие про 6 месяцев. Т.е если автор рекомендации до этого этому пользователю рекомендаций не оставлял, то optional будет empty и мы вообще не зайдём в блок кода с проверкой на 6 месяцев. Поэтому, если автор никогда не оставлял рекомендацию, то эксепшен тут не выкинется

2024-09-11 16:46 UTC, mikhailov26 commented
реши конфликт и можешь мержить

2024-10-10 16:33 UTC, merged