Cerberus master stream6 bjs2 26625 запрос на менторство
CorporationX/user_service pull request #1430
Opened 2024-09-08 16:10 UTC by NurseyitTursunkulov

2024-09-09 19:58 UTC, mikhailov26 requested changes

2024-09-09 19:58 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +
Проведи рефакторинг аннотация Transactional 1, а вызова репозитория 2, не пойдёт, либо проведи рефакторинг с использованием аннотации @Transactional, либо прочитай как можно это сделать не декларативно (аннотацией), а программно и рекомендую ознакомиться с нюансами работы @Transactional, в каких случаях она работает, когда не совсем, а когда вообще не работает

2024-09-09 19:58 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        } else {
Странная конструкция, проведи рефакторинг

2024-09-10 17:21 UTC, ostermal7 reviewed
Я пока не смотрел условие задачи, но тут очень много кода, который очень лишний, тот же класс предиката и тд. Посмотри у коллег в пулл реквестах как они делали, чтобы понять общую картину

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestController.java
> +public class MentorshipRequestController {
Почему этот класс в папке сервис, если это контроллер?

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestController.java
> +     void getRequests(RequestFilterDto filter){
почему не private?

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +    private final Predicates predicates = new Predicates();
Зачем это? У тебя спринг должен инжектить.

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestController.java
> +    void acceptRequest(long id) throws Exception {
почему default доступ?

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestController.java
> +    void rejectRequest(long id, RejectionDto rejection){
почему default

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        val response = mentorshipRequestValidator.validate(mentorshipRequestDto, List.of(predicates.userExistsPredicate, predicates.sameUserPredicate, predicates.requestTimeExceededPredicate));
зачем тебе тут предикаты? Почему не просто передать дто, а внутри проверить?

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
Что делает класс Validated, зачем такая запутанная логика? Что ты тут пытаешься сделать?

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        Optional<List<MentorshipRequest>> mentorshipRequestList = repository.getRequests();
Зачем ты создаешь свой getrequests? у тебя findAll тоже самое же делает, по-моему

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
У влада было видео про фильтры и как это правильно реализовать. Посмотри как надо правильно

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +    void acceptRequest(long id) throws Exception {
модификатор доступа

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +public class MentorshipRequestValidator implements Validator<MentorshipRequestDto,MentorshipRequestRepository, PredicateResult> {
для чего такая сложная логика для простой валидации?

2024-09-10 17:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/validator/Predicates.java
> +}
не понимаю для чего существует класс

2024-09-10 17:21 UTC, ostermal7 commented on src/test/java/school/faang/user_service/RequestFilterPredicatesTest.java
> +class RequestFilterPredicatesTest {
модификатор доступа

2024-09-10 20:25 UTC, mikhailov26 commented
Полностью согласен с коллегой, надо поправить

2024-09-11 04:12 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestController.java
> +     void getRequests(RequestFilterDto filter){
сделал все паблик, наверное эти методы должны гдето вызываться

2024-09-11 04:14 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestController.java
> +    void acceptRequest(long id) throws Exception {
сделал все паблик, наверное эти методы должны гдето вызываться

2024-09-11 04:14 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestController.java
> +    void rejectRequest(long id, RejectionDto rejection){
сделал все паблик, наверное эти методы должны гдето вызываться

2024-09-11 04:25 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        val response = mentorshipRequestValidator.validate(mentorshipRequestDto, List.of(predicates.userExistsPredicate, predicates.sameUserPredicate, predicates.requestTimeExceededPredicate));
я думал что когда ты видишь что именно ты проверяешь это лучше, но ты наверно прав щас уберу

2024-09-11 06:35 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
этот просто для ясности валидация прошла успешно

2024-09-11 06:39 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        Optional<List<MentorshipRequest>> mentorshipRequestList = repository.getRequests();
findAll() у меня выделяется красным.

2024-09-11 07:01 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
Это не нужно. У тебя валидация либо ошибку должна выбрасывать, либо ничего не делать

2024-09-12 07:56 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
выбрасывать исключение это спорный вопрос, https://anthony-trad.medium.com/why-you-shouldnt-throw-exceptions-in-your-code-c816680f970f

2024-09-12 07:57 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
немного подправил, похожее решение но меньше кода

2024-09-12 08:00 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/validator/MentorshipRequestValidator.java
> +public class MentorshipRequestValidator implements Validator<MentorshipRequestDto,MentorshipRequestRepository, PredicateResult> {
убрал интерфейс но логика осталась таже.

2024-09-12 08:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
Одна статья от какого-то человека не то, чтобы показатель. Как ты уведомишь юзера, если он ввел ошибочные данные?

2024-09-12 08:03 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/validator/Predicates.java
> +}
Влад в своем видео делал на каждое поле ДТОшки создавал класс который наследовался от UserFilter. Это подход порождает кучу классов. Но если использовать фукциональные интерфейсы то мы можем добится того же самого результата но все будет как здесь в одном классе.

2024-09-12 08:05 UTC, NurseyitTursunkulov commented on src/test/java/school/faang/user_service/RequestFilterPredicatesTest.java
> +class RequestFilterPredicatesTest {
для тестовых класов по моему модификатор не нужен, поправь если ошибаюсь

2024-09-12 08:11 UTC, ostermal7 commented on src/main/java/school/faang/user_service/validator/Predicates.java
> +}
Разница в том, что, если у тебя будет добавляться новый фильтр какой-то, то ты полезешь в код делать исправления, делать новые строчки кода в методе с предикатами, добавлять предикат и тд. Ты уже нарушаешь этим несколько принципов. В методе, который описал влад, ты просто добавишь новые класс, реализующий интерфейс, и все. Никаких изменений в методе делать не надо. У такого подхода прекрасная расширяемость, поэтому его и рекомендую сделать

2024-09-12 08:18 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
если if (!(response instanceof Validated)) тру то надо какойто респонс обратно отправить, только я пока не знаю как

2024-09-12 08:32 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/validator/Predicates.java
> +}
тут не согласен, у меня все тоже самое что делает Влад только в функциональном стиле. Смотри, у Влада интерфейс UserFilter c функциями isApplicable и apply которые принимают User и фильтр ДТО возвращает boolean. У меня функциональный интерфейс BiFunction ,  который делает тоже самое. Если мне нужно добавить еще один фильтр то я просто добавлю еще один BiFunction. Существующий метод изменять не нужно, они все изолированы друг от друга. Чтобы было нагляднее представь что каждый BiFunction лежит в отдельном классе результат будет одинаковым.

2024-09-12 08:45 UTC, VitoS1C commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    private final MentorshipRequestValidator mentorshipRequestValidator;
Поле  объявлено но не используется.

2024-09-12 08:52 UTC, VitoS1C commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        val response = mentorshipRequestValidator.validate(mentorshipRequestDto);
Можно использовать стандартную var от Java, а не val lombok.
````java
 var response = mentorshipRequestValidator.validate(mentorshipRequestDto);

2024-09-12 10:40 UTC, VitoS1C commented on src/main/java/school/faang/user_service/dto/MentorshipRequestMapper.java
> +public interface MentorshipRequestMapper {
Маппер не должен лежать в пакете dto, создай пакет mapper.mentorship

2024-09-12 10:44 UTC, VitoS1C commented on src/main/java/school/faang/user_service/dto/MentorshipRequestMapper.java
> +    @Mapping(source = "receiverId", target = "receiver.id")
Аналогично

2024-09-12 10:45 UTC, ostermal7 reviewed
что увидел еще из спорного отметил

2024-09-12 10:45 UTC, ostermal7 commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRequestRepository.java
>      boolean existAcceptedRequest(long requesterId, long receiverId);
зачем создавать свой собственный нэйтив квери, если он у тебя не сложный  и его может выполнить spring data?
boolean existsByRequesterIdAndReceiverIdAndStatus(long requesterId, long receiverId, RequestStatus status);

2024-09-12 10:45 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
Ошибку?) Которую обработает global exception handler?)

2024-09-12 10:45 UTC, ostermal7 commented on src/main/java/school/faang/user_service/util/predicate/PredicateFalse.java
> +}
насколько нужны эти классы? Для кого они выведут текст, который ты в них передаешь?

2024-09-12 10:45 UTC, ostermal7 commented on src/main/java/school/faang/user_service/validator/Predicates.java
> +            return new PredicateFalse(USERS_NOT_EXIST_IN_DATABASE);
мне кажется, что вся эта логика с дополнительными интерфейсами и тд лишь для фильтрации безумно перегружает код

2024-09-12 10:45 UTC, ostermal7 commented on src/test/java/school/faang/user_service/RequestFilterPredicatesTest.java
> +class RequestFilterPredicatesTest {
По-моему на класс правильно писать. Во всяком случае не наблюдал, чтобы в объявлении класса не писали модификатор доступа

2024-09-12 10:45 UTC, ostermal7 commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +    @Spy
разрыв

2024-09-12 10:45 UTC, ostermal7 commented on src/test/java/school/faang/user_service/service/MentroshipReqSerGetRequestTest.java
> +    MentorshipRequestService service;
мок?

2024-09-12 10:45 UTC, ostermal7 commented on src/test/java/school/faang/user_service/service/MentroshipReqSerGetRequestTest.java
> +        service = new MentorshipRequestService(mentorshipRequestValidator, repository, predicates);
почему ты так пишешь? моки сами инжектятся

2024-09-12 12:25 UTC, NurseyitTursunkulov commented on src/test/java/school/faang/user_service/service/MentroshipReqSerGetRequestTest.java
> +        service = new MentorshipRequestService(mentorshipRequestValidator, repository, predicates);
в этом случае они почему не инжектятся

2024-09-12 12:39 UTC, NurseyitTursunkulov commented on src/test/java/school/faang/user_service/service/MentroshipReqSerGetRequestTest.java
> +    MentorshipRequestService service;
нет, service это реальный обьект который мы тестируем

2024-09-12 12:44 UTC, ostermal7 commented on src/test/java/school/faang/user_service/service/MentroshipReqSerGetRequestTest.java
> +        service = new MentorshipRequestService(mentorshipRequestValidator, repository, predicates);
Надо разобраться почему

2024-09-12 12:45 UTC, ostermal7 commented on src/test/java/school/faang/user_service/service/MentroshipReqSerGetRequestTest.java
> +    MentorshipRequestService service;
Тебе в него моки инжектить надо тогда

2024-09-12 12:46 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/util/predicate/PredicateFalse.java
> +}
PredicateResult это универсальный респонс который может прийти BiFunction. NotApplicable значит что поле в дто пустое или нулл, аналог у Влада - isApplicable. PredicateTrue значит что фильтр вернул тру , PredicateFalse - false

2024-09-12 12:47 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/util/predicate/PredicateFalse.java
> +}
текст может пригодится в будущем когда надо будет пользователю сообщить причину почему фильтр не прошел.

2024-09-12 12:50 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRequestRepository.java
>      boolean existAcceptedRequest(long requesterId, long receiverId);
existsByRequesterIdAndReceiverIdAndStatus - у меня почему такой метод отсуствует

2024-09-12 12:51 UTC, NurseyitTursunkulov commented
> что увидел еще из спорного отметил. Также мы обсуждали, что реализация сервисов должна быть едина - через интерфейс сервис + его имплементация.

извини я не понял тебя, можешь подробнее написать?

2024-09-12 12:58 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRequestRepository.java
>      boolean existAcceptedRequest(long requesterId, long receiverId);
внизу та написал:
"Ошибку?) Которую обработает global exception handler?)"
но я думаю что подход выкидывать ошибку не совсем верно, если можно на месте решить и вернуть какоето сообщение будет более читабельно.

2024-09-12 13:30 UTC, ostermal7 commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRequestRepository.java
>      boolean existAcceptedRequest(long requesterId, long receiverId);
Так твоя ошибка несет нужную информацию, что именно тебе в подходе этом не нравится, но факт в том, что твое решение не делает ничего с неправильными данными, так?

2024-09-12 13:32 UTC, ostermal7 commented
Почитай про service + serviceImpl. Если коротко, то в интерфейсе описываешь просто схему метода, а реализуешь уже через impl всю логику

2024-09-13 16:28 UTC, mikhailov26 commented
Посмотреть про то как делаются сервис классы в связке с их интерфейсами, и прочитать принцыпы SOLID, а именно принцип D

2024-09-16 16:24 UTC, merged