BJS2-26820 - Совместная работа над целью
CorporationX/user_service pull request #1439
Opened 2024-09-09 10:04 UTC by mrkorolev

Особого внимания требует фильтр приглашений: есть два варианта метода сервиса, по канону из условия и с использованием Specification и JPA Criteria API. Использование последнего повышает читаемость всей фильтрации путем программной манипуляции SQL запроса (для проверки нужно писать интеграционные тесты, но при желании можно посмотреть в Postman).

2024-09-09 23:17 UTC, Murzin34 commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    }
Можешь воспользоваться аннотациями `@ResponseStatus(HttpStatus.OK)`, `@ResponseStatus(HttpStatus.CREATED)` и `@ResponseStatus(HttpStatus.NO_CONTENT)`  вместо использования ResponseEntity, это сделает код почище.

2024-09-09 23:44 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    }
@Murzin34 Спасибо! Пересмотрел возвращаемый тип этого метода - читаемость страдает, согласен

2024-09-11 14:01 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        GoalInvitation result = goalInvitationService.createInvitation(testInvitation);
нужно ли здесь делать проверку verify для метода `goalInvitationRepository.save(testInvitation)`

2024-09-11 14:01 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals(GoalInvitationService.GOAL_MISSING, e1.getMessage());
А использование публичных констант это хорошая практика или нет?

2024-09-11 14:01 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        }
Вроде бы это нарушает принцип Open/Closed

2024-09-12 19:25 UTC, 20cognosce requested changes

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +@RestController("${controller.goalInvitation.baseUrl}")
Из пропертей убирай это
Можешь в константы вынести

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +//        List<GoalInvitation> filteredInvitations = goalInvitationService.getInvitationsBySpec(filter);
кому захоронения оставляем, археологам

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @GetMapping
Get запросов должен быть без тела
Юзай Post

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +        GoalInvitation savedInvitation = goalInvitationService.createInvitation(mapper.toEntity(dto));
В переменную вынести

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @PatchMapping("/{id}/accept")
По смыслу ближе Put
Patch - это просто обновление

а тут у тебя принятие или отклонение, кажется что может быть более комплексная логика

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    @PatchMapping("/{id}/reject")
same

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/goal/specification/GoalInvitationSpecification.java
> +    }
В первый раз такую самодеятельность вижу, сразу не понял, что тут происходит
А это ты CriteriaBuilder собираешь для запросов так...

Ну... Мне кажется это не оправдано в данной задаче

Давай на SQL как мужики напишем всё через Query
Либо используй встроенные в SpringData конструкторы методов по имени
findAllByNameAndIdNotLike и прочее

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    public static final String INVITED_MAX_ACTIVE_GOALS = "Invited user reached max active goals: " + MAX_ACTIVE_GOALS;
Отдельный @UtilityClass

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    public GoalInvitation createInvitation(GoalInvitation invitation) {
@Transactional

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    }
Я листаю, а конца методу нет

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        if (userRepository.findAllById(List.of(inviterId, invitedId)).size() != 2) {
в if нельзя так писать

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                .toList());
Что ты творишь...

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                .toList());
Пощади логи

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    public GoalInvitation createInvitation(GoalInvitation invitation) {
Укоротить метод в 3 раза
Мусор выкинуть
Где надо декомпозировать

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    public void acceptGoalInvitation(long id) {
Транзакция

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        }
Можно отдельно валидации все проводить?

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +    public void acceptGoalInvitation(long id) {
В 3 раза короче сделать

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                }
Можно это просто удалить
orElseThrow и не парься
Выше по стеку все залогируется в ControllerAdvice

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        }
Что это за вызов сатаны

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        }
Переделать по-нормальному...

2024-09-12 19:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                .and(hasStatus(filter.getStatus()));
sql

2024-09-12 19:25 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals(RequestStatus.PENDING, result.getStatus());
Чего так мало проверок?
assertThat().recursiveComparison() и погнали

2024-09-12 19:25 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        GoalInvitation result = goalInvitationService.createInvitation(testInvitation);
можно, но одной её мало

2024-09-12 19:25 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +        assertEquals(GoalInvitationService.GOAL_MISSING, e1.getMessage());
Смотря для чего, для описания ошибок - норм
Но в тесте ты не описание ошибки должен проверить, а просто что она вылетает

2024-09-12 21:05 UTC, mrkorolev commented on src/main/java/school/faang/user_service/repository/goal/specification/GoalInvitationSpecification.java
> +    }
@20cognosce Почему не оправдано? Если поле отвечающее за фильтр не пришло (null), то в WHERE clause он включаться не будет - как раз то, что нужно. Тогда почему не оправдано?

2024-09-12 21:11 UTC, mrkorolev commented on src/main/java/school/faang/user_service/repository/goal/specification/GoalInvitationSpecification.java
> +    }
А если я напишу sql запрос и передам туда фильтр, который может прийти как null, то в моем запросе все равно упоминание этого параметра:

SELECT *
FROM goal_invitation
WHERE inviter_id = <null> AND invited_id = 3

Иными словами, если даже inviterId (из InvitationFilterDto) прийдет как null, его упоминание в WHERE никуда не денется - именно эту проблему решает criteria builder.

Как по мне это в разы лучше, чем внедрять "бины-фильтры" в список сервиса.

2024-09-13 09:56 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    }
Супер гуд

2024-09-15 10:30 UTC, 20cognosce approved these changes

2024-09-15 10:30 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/advice/ApiControllerAdvice.java
> +//                "Something wrong on our end, contact IT support immediately."
Не писать бесполезные комментарии

2024-09-15 10:30 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                () -> new IllegalArgumentException(INVITED_MISSING));
getId в переменную

2024-09-15 10:30 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/specification/GoalInvitationSpecification.java
> +                predicate = criteriaBuilder.and(predicate, criteriaBuilder.equal(root.get("invited").get("id"), invitedId));
if (Objects.nonNull(inviterId)) {
                predicate = criteriaBuilder.and(predicate, criteriaBuilder.equal(
Это дублирование кода, мог консьюмер-функцию создать

2024-09-15 10:31 UTC, merged

2024-09-15 10:36 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/advice/ApiControllerAdvice.java
> +//                "Something wrong on our end, contact IT support immediately."
Забыл убрать