skillOffer and RecommendationController
CorporationX/user_service pull request #1440
Opened 2024-09-09 12:34 UTC by aassylkhan

2024-09-09 12:42 UTC, aassylkhan commented on build.gradle.kts
lombok не работает на версии 26. только 36 почему то

2024-09-09 14:28 UTC, SharkB38 commented
Еще не увидел реализации вот этих двух задач Получить все рекомендации пользователя, Получить все данные рекомендации

2024-09-09 14:38 UTC, SharkB38 requested changes

2024-09-09 14:38 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +    public RecommendationDto createOrUpdate(RecommendationDto recommendationDto) {
Ну про этот метод уже поговорили на ретро, но может еще валидацию повыносить в отдельные методы?

2024-09-09 14:38 UTC, SharkB38 commented on src/test/java/school/faang/user_service/service/RecommendationServiceImplTest.java
> +    @Autowired
Вот тут надо пустую строчку вставить

2024-09-09 14:38 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +@Slf4j
Не используется аннотация

2024-09-09 19:46 UTC, SharkB38 commented on src/main/java/school/faang/user_service/dto/SkillOfferDto.java
> +public class SkillOfferDto {
Забыл написать, Dto всем рекомендуют сделать record

2024-09-09 19:49 UTC, wmwmaks commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
Лучше назвать toRecommendation или типа того. Цитирую Машу из ревью моего кода " т.к. Entity это что-то очень абстрактное, хотя метод превращает переданный объект именно в объект класса User и ни в какой другой"
У тебя соответственно именно в Recommendation превращаем, а не в что-то другое)

2024-09-09 19:50 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/RecommendationServiceImplTest.java
> +
лишняя пустая строка)

2024-09-09 19:52 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/RecommendationServiceImplTest.java
> +    @MockBean
Перед аннотациями, возможно, надо вставлять пустые строки для читаемости, но я не уверен, насколько это критично.
Это ко всем @Mock комментарий

2024-09-09 20:46 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +                .orElseThrow(() -> new DataValidationException("Author not found"));
Как вариант, вынести тест ошибок в константы или в Enum класс, чтобы не "хардкодить")
Что думаешь?

2024-09-09 20:50 UTC, wmwmaks commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
Лучше назвать toRecommendation или типа того. Цитирую слова Маши из ревью моего кода " т.к. Entity это что-то очень абстрактное, хотя метод превращает переданный объект именно в объект класса User и ни в какой другой"
У тебя соответственно именно в Recommendation превращаем, а не в что-то другое)

2024-09-11 14:48 UTC, SharkB38 approved these changes

2024-09-11 14:51 UTC, SharkB38 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +    public ResponseEntity<RecommendationDto> createRecommendation(
Использование ResponseEntity спорный вопрос, неплохо было бы убрать для единообразия в проекте, но это уже как Маша скажет

2024-09-11 14:57 UTC, aassylkhan commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +    public ResponseEntity<RecommendationDto> createRecommendation(
согласен. тоже не хотел писать через Response, но прошлом ретро был поднят вопрос про ResponseEntity и я подумал что надо через него писать)

2024-09-11 14:58 UTC, aassylkhan commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
а toDto тоже наверно надо поменять или только toEntity?

2024-09-11 15:00 UTC, aassylkhan commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +                .orElseThrow(() -> new DataValidationException("Author not found"));
типа как DataValidationException("Author not found", ValidationErrorCode.AUTHOR_NOT_FOUND)? или ты имел ввиду что то другое)

2024-09-11 15:11 UTC, SharkB38 commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
Да, лучше все поменять

2024-09-11 15:28 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationServiceImplTest.java
> +
лишняя пустая строка)

2024-09-11 15:31 UTC, wmwmaks commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
toDto можно поменять на toRecommendationDto
так тоже будет понятнее, что во что превращается

2024-09-11 15:34 UTC, wmwmaks commented on build.gradle.kts
> -
Не очень понимаю зачем этот перенос блока кода в JaCoCo. Оно работает и так, как было изначально)

2024-09-11 15:36 UTC, wmwmaks commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +@Mapper(componentModel = "spring")
В скобки к @Mapper Влад говорил добавлять еще "unmappedTargetPolicy = ReportingPolicy.IGNORE", пока мы еще не умеем тонкой настройкой Мапперов заниматься

2024-09-11 15:39 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +    public RecommendationDto create(RecommendationDto recommendationDto) {
Не уверен, насколько название create корректно. Таких методов create в разных классах может быть много и, вдруг, это где-то может путаницу вызвать. Аналогично с delete и update. Может, лучше явно прописать createRecommendation, updateRecommendation и deleteRecommendation. Что думаешь?

2024-09-11 15:43 UTC, wmwmaks approved these changes
👍

2024-09-11 15:46 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +                .orElseThrow(() -> new DataValidationException("Author not found"));
Создать переменную private final static String AUTHOR_NOT_FOUND_MESSAGE = "Author not found";
И передавать в "new DataValidationException("Author not found"))" не текст напрямую, а эту переменную с сообщением ошибки -> new DataValidationException(AUTHOR_NOT_FOUND_MESSAGE)); 
С остальными подобным аналогично)

2024-09-12 03:32 UTC, ArstanSubanov approved these changes

2024-09-12 17:33 UTC, mysosnovskaya commented
Ветка называется неверно. Должно быть `feature-BJS2-27373`

2024-09-12 17:38 UTC, mysosnovskaya requested changes

2024-09-12 17:38 UTC, mysosnovskaya commented on build.gradle.kts
> -
Комментарий помечен как resolved, но изменения я не увидела. Согласна, что переносить не нужно

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +            @RequestParam(defaultValue = "0") int page,
Круто сделано с RequestParam и Pageable 👍

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +                receiverId, pageable);
Я бы перенос строки не делала (и в других методах тоже). Она не такой уж длинной выходит)

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/DataValidationException.java
> +        super( message );
Это зачем?)

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/DataValidationException.java
> +@ResponseStatus(value = HttpStatus.NOT_FOUND)
Мы на проекте уже приняли подход в ExceptionHandler (в мастер ветке уже есть), поэтому эта аннотация не нужна

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/DataValidationException.java
> +@ResponseStatus(value = HttpStatus.NOT_FOUND)
К тому же здесь должен быть BAD_REQUEST, а не NOT_FOUND - ошибка валидации это проблема, связанная с данными от пользователя)

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/recommendation/SkillOfferRepository.java
> +    boolean existsBySkillIdAndRecommendationId(long id, long id1);
Параметры нужно переименовать соответствующим образом. А вообще круто, что ты знаком с запросными методами 👍

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +@RequiredArgsConstructor
Не хватает логов

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +    private final static String AUTHOR_NOT_FOUND_MESSAGE = "Author not found";
Про константы писала комментарий у Витали в ПРе, рекомендую ознакомиться:
https://github.com/CorporationX/project_service/pull/600#discussion_r1755396134

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +    private final static String AUTHOR_NOT_FOUND_MESSAGE = "Author not found";
В сообщения об ошибках нужно добавлять идентификаторы (автор с каким id не найден?)

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +            Skill skill = skillRepository.findById(skillOfferDto.skillId())
Тема одного из будущих спринтов, но напишу уже сейчас:
вместо того, чтобы ходить в базу данных за каждым скиллом отдельно, лучше вытащить сразу все за один запрос. Вообще количество запросов к бд нужно стараться минимизировать, т.к. это долгая операция. Тебе поможет метод findAllById, который уже есть в skillRepository. Затем можешь в коде посмотреть, все ли скиллы нашлись, и если нет, то вернуть ошибку

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +                .collect(Collectors.toList());
Можно просто `.toList()`

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +    RecommendationDto createRecommendation(RecommendationDto recommendationDto);
Чаще всего между методами оставляют пустые строки. Но это не строгое правило, даже вообще не правило) Встречается и такой вариант. Мне больше нравится, когда пустые строки есть, но ты можешь оставить так

2024-09-12 17:38 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationServiceImplTest.java
> +        verifyNoMoreInteractions(recommendationRepository, skillOfferRepository);
Супер 👍

2024-09-12 17:38 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationServiceImplTest.java
> +    void testCreateRecommendationWithInvalidReceiver() {
Обычно в тестах выделяют логические блоки с помощью пустых строк: сначала подготовка данных, затем настройка моков, дальше вызов тестируемого метода и в конце проверки (можно разделить assert-ы и verify). Т.е. у тебя этот тест мог бы выглядеть так:
```
when(userRepository.findById(recommendationDto.authorId())).thenReturn(Optional.of(author));
when(userRepository.findById(recommendationDto.receiverId())).thenReturn(Optional.empty());

assertThrows(DataValidationException.class,
                () -> recommendationService.createRecommendation(recommendationDto));

verify(userRepository).findById(recommendationDto.authorId());
verify(userRepository).findById(recommendationDto.receiverId());
verifyNoMoreInteractions(recommendationRepository, skillOfferRepository);
```

2024-09-12 17:38 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationServiceImplTest.java
> +public class RecommendationServiceImplTest {
Тестов не хватает. Нужны ещё позитивные сценарии и тесты на гет-методы

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +    public ResponseEntity<RecommendationDto> createRecommendation(
> но прошлом ретро был поднят вопрос про ResponseEntity и я подумал что надо через него писать

Не должна была я такого сказать =)) Считаю, что он не нужен, только лишнего кода прибавляет, а пользы от него никакой в данной ситуации) Редко бывает, когда нужно более тонко настроить респонс, тогда ResponseEntity может пригодиться. А когда просто отправляем тело ответа со статусом 200, то он не нужен

2024-09-12 17:38 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/impl/RecommendationServiceImpl.java
> +    public RecommendationDto create(RecommendationDto recommendationDto) {
Писала про это Витале совсем недавно, рекомендую ознакомиться:
https://github.com/CorporationX/project_service/pull/600#discussion_r1755382139

2024-09-13 05:31 UTC, aassylkhan commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +    public ResponseEntity<RecommendationDto> createRecommendation(
> > но прошлом ретро был поднят вопрос про ResponseEntity и я подумал что надо через него писать
> 
> Не должна была я такого сказать =)) Считаю, что он не нужен, только лишнего кода прибавляет, а пользы от него никакой в данной ситуации) Редко бывает, когда нужно более тонко настроить респонс, тогда ResponseEntity может пригодиться. А когда просто отправляем тело ответа со статусом 200, то он не нужен

у меня тогда плохо интернет работал и я не расслышал( подумал что надо добавить response =)

2024-09-13 05:32 UTC, aassylkhan commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +            @RequestParam(defaultValue = "0") int page,
> Круто сделано с RequestParam и Pageable 👍

я увидел в репо что использует Pageable и думал что надо через него писать)

2024-09-13 08:37 UTC, closed without merging