Subscription feature fixed
CorporationX/user_service pull request #1443
Opened 2024-09-09 15:37 UTC by MamadjonovKO

2024-09-10 16:21 UTC, Murzin34 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    }
Можешь воспользоваться аннотацией @ResponseStatus(HttpStatus.OK) вместо использования ResponseEntity, это сделает код почище.

2024-09-10 20:21 UTC, mrkorolev reviewed
Крутое решение! 

Есть (на мой взгляд) один недочет: если вдруг UserFilterDto пополнится полями, тебе снова придется создавать целый компонент (файл) для этого фильтра. 

Когда я думал на эту тему нашел подход через Spring Data JPA Specifications. Он позволяет создать один класс, в котором ты определяешь методы обработки фильтра, и дальше программно создаешь запрос. И если UserFilterDto пополнится полями, тебе придется добавить один метод для его обработки. Вот мой PR (папка specification): 

https://github.com/CorporationX/user_service/pull/1439

 Да, у нас разные задачи, но важен именно подход.

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        }
Суть контроллера в том, чтобы получить запрос, а вот бизнес логику принято писать в сервисе. Будет лучше перенести эти проверки в SubscriptionService - так тебе придется тестировать всю логику всего в одном классе (включая ту, в которой ты бросаешь исключения).

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        }
Хорошо, что ты разделяешь взаимоисключающие действия (либо одно, либо другое). Однако лично мне кажется, что более читаемо было сделать следующим образом: если подписка есть - кинуть исключение, не писать else вообще и дальше вызвать followUser

А может быть я душню, Дима скажет как лучше в любом случае)

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        }
Тот же самый point, что и комментарием выше

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    }
Про следующее я сам узнал, когда меня ревьюили. Хорошо, что используешь ResponseEntity, но когда возвращаемое методом значение становится сложным (List<UserDto>), то страдает читаемость. В этом месте (и в других, где тебе не нужно руками проставлять заголовок HTTP запроса) следующий код сделает читаемость гораздо лучше:

@ GetMapping("/followers/{followeeId}")
@ResponseStatus(HttpStatus.OK)
public List<UserDto> getFollowers(...){
...
}

Ещё я бы вынес subscriptionService.getFollowers в отдельную переменную и передал бы её в userMapper - тоже в целях читаемости.

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        }
Тот же point, что и выше

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    }
Я вижу, что метод findByFolloweeId возвращает стрим - однако я бы переписал его (или написал похожий) который возвращал бы List. Как то раз я пытался передать стрим в качестве аргумента в метод - Дима мне сказал, что делать так не лучшая идея (работать лучше с объектами, а не с потоками). Может контекст твоей задачи отличается от моего случая, посмотрим что он скажет.

Ну и в 46 строчке можно просто вернуть filter(userStream, filters).toList();

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/filters/UserNameFilter.java
> +    }
Немного подушню: где-то прочитал, что лучше для проверки на null использовать класс готовые служебные классы:
Objects.nonNull(userFilterDto.getNamePattern())

В принципе внутри он делает то же самое, что и твой код - но так мне кажется код выглядит чище)

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/filters/UserFilter.java
> +}
Посмотрел все твои фильтры - очень много где повторяется внутри реализаций apply фильтр contains. Его можно было бы сюда вынести и сделать default методом и дальше использовать его внутри apply:

default boolean stringContainsFilter(String userField, String dtoField) {
    return userField.contains(dtoField);
}

Например, в UserNameFilter:

    @Override
     public Stream<User> apply(Stream<User> userStream, UserFilterDto filterDto) {
         return userStream.filter(user -> stringContainsFilter(user.getUsername(), filterDto.getNamePattern()));
     }

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    private final List<UserFilter> userFilters = new ArrayList<>();
Внедряешь бины в список через конструктор, круто

2024-09-10 20:21 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void followUser(long followerId, long followeeId) {
Расскажи вкратце, пожалуйста, почему ты в этих методах используешь Transactional?

2024-09-10 21:47 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +    }
Этот метод полностью дублирует предыдущий. Не совсем понятно, что он должен проверить

Для повышения читаемости можно применить статический импорт к методу assertThrows

2024-09-10 21:47 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @PostMapping("/unfollow")
Ты работаешь с подписками: методы followUser и unfollowUser добавляют и удаляют подписку соответственно (@PostMapping и @DeleteMapping). Тебе также ничего не нужно писать в скобках у этих аннотаций (тип маппинга уже описывает действие, которое ты хочешь сделать).

2024-09-12 13:11 UTC, MamadjonovKO commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void followUser(long followerId, long followeeId) {
Конкретно в этом методе она, скорее всего, не обязательна (у меня просто была ошибка, когда я тестировал через Postman, и я повесил её как вариант :) ). Но она точно не помешает: сама аннотация гарантирует, что все операции внутри метода будут выполнены как единое целое. Если что-то пойдёт не так (например, выбросится исключение), все изменения откатятся, и база данных останется в согласованном состоянии. Если не ошибаюсь, при использовании аннотации на методе, Spring берёт на себя управление транзакцией. Если метод выполняется успешно, транзакция будет зафиксирована (committed), а если происходит исключение, транзакция автоматически откатывается (rollback). Я сам только изучаю это всё, но из-за неё не мог протестировать через Postman почему-то.

2024-09-13 16:25 UTC, 20cognosce requested changes

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @DeleteMapping("/unfollow")
unfollow != delete
Put

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @PostMapping("/follow")
follow != create
Put

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @ResponseStatus(HttpStatus.OK)
По дефолту итак ОК

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        return userMapper.toDto(subscriptionService.getFollowers(followeeId, filter));
Не в одну строчку, выдели переменную

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +
Аналогично

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    private String email;
Где валидации?

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    private final List<UserFilter> userFilters = new ArrayList<>();
new можно не использовать ведь?

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    @Transactional
readOnly = true

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        userExistence(followeeId);
verifyUserExist

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    @Transactional
readOnly

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    }
Это не DataValidation, это проверка условий подписки
SubscriptionRequirementsException, как-нибудь

DataValidation - в DTO

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    }
А почему тут не в транзакции? между 61 и 62 строчкой удалили подписчика и всё

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/filters/UserEmailFilter.java
> +        return userStream.filter(user -> user.getEmail().contains(filterDto.getEmailPattern()));
Pattern не так проверяется

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/filters/UserCountryPattern.java
> +        return userStream.filter(user -> user.getCountry().getTitle().contains(filterDto.getCountryPattern()));
почему в одну строчку такая длинная цепочка вызовов?
а если title null?

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/filters/UserPageFilter.java
> +        return userStream.skip(page * size);
а ты отсортировал стрим?

2024-09-13 16:25 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +import static org.mockito.Mockito.*;
не сворачивать импорты

2024-09-13 16:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/UserFilterDto.java
> +    private int pageSize;
Валидации

2024-09-15 10:39 UTC, 20cognosce requested changes

2024-09-15 10:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +import org.springframework.web.bind.annotation.*;
не сворачивать импорты

2024-09-15 10:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    public List<UserDto> getFollowers(@PathVariable long followeeId, @RequestBody UserFilterDto filter) {
Post, у Get не должно быть тела по спеке

2024-09-15 10:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    public List<UserDto> getFollowing(@PathVariable long followerId, UserFilterDto filter) {
same

2024-09-15 10:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    @Transactional
readOnly = true

2024-09-15 10:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    @Transactional
readOnly = true

2024-09-15 10:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +import jakarta.transaction.Transactional;
Не тот @Transactional, используй спринговый

2024-09-15 10:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/filters/UserPageFilter.java
> +        return userStream.sorted(Comparator.comparing(User::getId))
id - не имеет никакого смысла на уровне приложения, это просто идентификатор
По дате какой-нибудь надо сортировать, дате регистрации пользователя может

2024-09-15 10:39 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +import static org.mockito.Mockito.*;
не сворачивать импорты

2024-09-16 17:47 UTC, 20cognosce approved these changes

2024-09-16 17:48 UTC, 20cognosce commented
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/CorporationX/user_service/pull/1443/conflicts) or the  to resolve conflicts.
Conflicting files

2024-09-18 05:16 UTC, merged