BJS2-27026
CorporationX/user_service pull request #1444
Opened 2024-09-09 16:43 UTC by ilu23ilu23

Создание OpenApiConfig для настройки инфо о User_service, установлены аннотации OpenApi в контроллере EventController, создан файл SwaggerAnnotationsInfo.md с описанием возможных аннотаций и их описанием.

2024-09-09 17:17 UTC, amilosh commented on src/main/java/school/faang/user_service/config/openApi/OpenApiConfig.java
> +                );
Можно вот так
@Bean
    public OpenAPI openAPI() {
        return new OpenAPI()
            .info(info());
    }

    private Info info() {
        return new Info()
            .title("...")
            .description("...")
            .version("...");
    }

Но это на вкус и цвет.

2024-09-09 17:30 UTC, amilosh commented on SwaggerAnnotationsInfo.md
> +Тут буду отображаться все эндпоинты контроллеров с описанием их работы.
В application.yaml ещё можно прописать кастомный путь и в какой порядке будут отсортированы тэги и операции
springdoc.api-docs.path=/swagger
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha

2024-09-09 17:34 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    )
Я когда игрался со сваггером ещё пробовал request и response body подабавлять.
Вот так это выглядело:
```
    @Operation(
        summary = "Create new Employee.",
        description = "Create new Employee with unique email.",
        requestBody = @RequestBody(
            description = "Employee",
            required = true,
            content = {
                @Content(
                    mediaType = APPLICATION_JSON_VALUE,
                    schema = @Schema(
                        implementation = EmployeeDto.class
                    )
                )
            }
        )
    )
    @ApiResponses(
        value = {
            @ApiResponse(
                responseCode = "201",
                description = "Employee is created",
                content = {
                    @Content(
                        mediaType = APPLICATION_JSON_VALUE,
                        schema = @Schema(
                            implementation = EmployeeDto.class
                        )
                    )
                }
            ),
            @ApiResponse(
                responseCode = "400",
                description = "Bad request"
            ),
            @ApiResponse(
                responseCode = "500",
                description = "Internal server error"
            )
        }
    )
```

2024-09-09 17:35 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +            @Parameter(description = "ID of the event to retrieve") Long eventId) {
А тут так пробовал
```
        @Parameter(
            in = ParameterIn.PATH,
            name = "id",
            description = "Employee id",
            required = true,
            schema = @Schema(
                type = "Integer"
            )
        )
```

2024-09-09 17:54 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +            @Parameter(description = "ID of the event to delete") Long eventId) {
Почему переносы не ставишь в конце?
```
    public void deleteEvent(
            @PathVariable("id")
            @Parameter(description = "ID of the event to delete") Long eventId
    ) {
```
так выглядело бы гораздо лучше и практичнее со стороны добавления или удаления параметров

2024-09-09 17:55 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
Лишний отступ

2024-09-09 18:00 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +            @Parameter(description = "ID of the event to retrieve") Long eventId) {
По моей практике такие общие элементы (id в url строке) лучше выносить в отдельные классы, чтобы переиспользовать, а то код контроллера разрастается нереально.
у тебя уже строки кода контроллера выросли в х2 раза

2024-09-13 17:13 UTC, 20cognosce requested changes

2024-09-13 17:13 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> -    public EventDto create(@Valid @RequestBody EventDto eventDto) {
Не понял, почему контроллер поломал?

2024-09-13 17:13 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventControllerApi.java
> +    );
bruh, нет
Спека отдельно - реализация отдельно
Не надо было контроллер трогать вообще

Отдельный пакет для API сделай
Часть аннотаций можешь прямо в контроллере добавить

2024-09-13 17:13 UTC, 20cognosce commented on src/main/resources/application.yaml
> +  port: 9080
Ну и в этом файле конфликт на ПРе
Обнови ветку

2024-09-15 10:20 UTC, 20cognosce approved these changes

2024-09-15 10:20 UTC, merged