BJS2-27564 добавлено решение задачи
CorporationX/user_service pull request #1446
Opened 2024-09-09 18:03 UTC by KarabbasBarabas

2024-09-10 19:37 UTC, mysosnovskaya commented
Название ветки должно быть feature-BJS2-27564, теперь ник в дискорде добавлять не нужно)

2024-09-10 20:00 UTC, mysosnovskaya requested changes
У тебя получилась очень хорошая работа 👍 Очень круто пишешь тесты) Критичных исправлений не требуется, но разные предложения по улучшению написала)

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @Autowired
Можно попросить ломбок сгенерировать конструктор, чтобы самому не писать) Autowire он тоже умеет

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            throw new RuntimeException("Сообщение не может быть пустым");
Думаю, своё собственное исключение здесь лучше подойдет. RuntimeException это когда какая-то ошибка в коде случилась (типа NullPointerException), а здесь ситуация другая. Нам просто нужно пользователю сказать, что он в запросе передал ерунду =)

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/RecommendationRequestDto.java
> +    Long id;
Модификаторов не хватает. И посмотри на java records - кажется, это может здесь подойти. В остальных dto классах скорее всего тоже

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE, uses = SkillRequestMapper.class)
Классная работа с мапперами 👍 Очень много возможностей mapstruct задействовано, молодец!

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        for (RequestFilter filter: requestFilters) {
А давай через стрим это сделаем?)

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +public class RecommendationRequestService {
Как правило, на уровне сервисов происходит логгирование. Предлагаю добавить его сюда (используя аннотацию Slf4j от ломбока)

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        System.out.println(requestFilters);
Похоже, это информация с дебага осталась? Нужно удалить

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +            throw new RuntimeException("Запрашиваемого запроса нет в базе данных");
Вместо RuntimeException лучше подобрать более подходящие исключения. Например, свои создать) Касается всего кода

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        if(lastRequest.isPresent() && LocalDateTime.now().isBefore(lastRequest.get().getCreatedAt().plusMonths(6))) {
Пробела не хватает перед скобкой =)

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        if(lastRequest.isPresent() && LocalDateTime.now().isBefore(lastRequest.get().getCreatedAt().plusMonths(6))) {
6 сейчас является магическим числом. Давай вынесем его в константы? Можно назвать хотя бы HALF_YEAR, но лучше подумать над названием, которое бы говорило, что это период, как часто можно отправлять запросы. Вот так было бы вообще идеально (и в перспективе в будущем этот параметр можно будет настраивать извне, через специальный конфигурационный файл)

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/filter/recommendation/RequestFilter.java
> +public interface RequestFilter {
Отлично реализована логика фильтров 👍

2024-09-10 20:00 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/filter/recommendation/RequestFilterDto.java
> +public record RequestFilterDto(RequestStatus status, String messagePattern) {}
Здорово, что используешь java records 👍 Только этот класс лучше переместить в пакет с dto

2024-09-10 20:00 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
> +    Long expectedId;
Модификатор потерялся)

2024-09-10 20:00 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
> +        // Arrange
Комментарии можно не подписывать, благодаря пустой строке эти два блока хорошо отделяются и визуально отличимы друг от друга

2024-09-10 20:00 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/RecommendationRequestServiceTest.java
> +    @InjectMocks
Если ты сам в setup создаешь сервис, то здесь InjectMocks можно не писать

2024-09-10 20:00 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/RecommendationRequestServiceTest.java
> +        Exception exception = Assertions.assertThrows(RuntimeException.class, () -> {service.create(dto);});
`() -> service.create(dto)`

2024-09-10 20:00 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/RecommendationRequestServiceTest.java
> +        when(userRepository.findById(dto.getRequesterId())).thenReturn(Optional.of(User.builder().id(dto.getRequesterId()).build()));
Я бы юзера в отдельную переменную сохранила, код полегче будет. Или может быть стоит юзеру добавить конструктор с одним параметром - id?

2024-09-11 15:14 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        for (RequestFilter filter: requestFilters) {
ошибки будут лететь с Cuncurrent

2024-09-14 15:26 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @Autowired
поправил

2024-09-14 16:24 UTC, KarabbasBarabas commented on src/test/java/school/faang/user_service/service/RecommendationRequestServiceTest.java
> +        when(userRepository.findById(dto.getRequesterId())).thenReturn(Optional.of(User.builder().id(dto.getRequesterId()).build()));
поправил

2024-09-14 16:24 UTC, KarabbasBarabas commented on src/test/java/school/faang/user_service/service/RecommendationRequestServiceTest.java
> +        Exception exception = Assertions.assertThrows(RuntimeException.class, () -> {service.create(dto);});
поправил

2024-09-14 16:24 UTC, KarabbasBarabas commented on src/test/java/school/faang/user_service/service/RecommendationRequestServiceTest.java
> +    @InjectMocks
поправил

2024-09-14 16:24 UTC, KarabbasBarabas commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
> +        // Arrange
понял, то так понятней что где

2024-09-14 16:24 UTC, KarabbasBarabas commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
> +    Long expectedId;
поправил

2024-09-14 16:25 UTC, KarabbasBarabas commented
> Название ветки должно быть feature-BJS2-27564, теперь ник в дискорде добавлять не нужно)

понял, если у этой удалённой ветки поменяю наименование, то все комментарии удалятся?

2024-09-14 20:55 UTC, mysosnovskaya commented
> > Название ветки должно быть feature-BJS2-27564, теперь ник в дискорде добавлять не нужно)
> 
> понял, если у этой удалённой ветки поменяю наименование, то все комментарии удалятся?

Проще всего от твоей ветки создать новую ветку с верным названием и сделать новый ПР. Этот ПР можно закрыть, комментарии останутся здесь. Я их здесь посмотрю)

2024-09-14 20:57 UTC, mysosnovskaya requested changes
1. Не все комментарии исправлены (или аргументированно не исправлены)
2. В гитхабе не прошла проверка с тестами. Это нам Данил в рамках своей задачи добавил, на дейлике рассказывал) Теперь без зеленой галочки с тестами ПР не проверяю

2024-09-16 15:23 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +            throw new RuntimeException("Сообщение не может быть пустым");
поправил

2024-09-16 15:23 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/dto/RecommendationRequestDto.java
> +    Long id;
поправил

2024-09-16 16:59 UTC, KarabbasBarabas commented
> 1. Не все комментарии исправлены (или аргументированно не исправлены)
> 2. В гитхабе не прошла проверка с тестами. Это нам Данил в рамках своей задачи добавил, на дейлике рассказывал) Теперь без зеленой галочки с тестами ПР не проверяю

поправил

2024-09-16 17:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        for (RequestFilter filter: requestFilters) {
Не будет) Посмотри, как у Руслана сделано (как раз обсуждали это на встрече)

2024-09-16 17:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +public class RecommendationRequestService {
Логов так и нет

2024-09-16 17:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        System.out.println(requestFilters);
Не исправлено

2024-09-16 17:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        if(lastRequest.isPresent() && LocalDateTime.now().isBefore(lastRequest.get().getCreatedAt().plusMonths(6))) {
Не исправлено

2024-09-16 17:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        if(lastRequest.isPresent() && LocalDateTime.now().isBefore(lastRequest.get().getCreatedAt().plusMonths(6))) {
Не исправлено

2024-09-16 17:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/filter/recommendation/RequestFilterDto.java
> +public record RequestFilterDto(RequestStatus status, String messagePattern) {}
Не исправлено

2024-09-16 17:44 UTC, mysosnovskaya requested changes
Когда комментариев много, то гитхаб их сворачивает и видно только первые и последние. Возможно из-за этого ты не заметил комментарии в середине) Написала подо всеми "не исправлено". Новых не добавляла

2024-09-17 17:44 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        for (RequestFilter filter: requestFilters) {
действительно, спасибо, поправил

2024-09-17 18:04 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +public class RecommendationRequestService {
добавил

2024-09-17 18:04 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        System.out.println(requestFilters);
поправил

2024-09-17 18:05 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        if(lastRequest.isPresent() && LocalDateTime.now().isBefore(lastRequest.get().getCreatedAt().plusMonths(6))) {
поправил

2024-09-17 18:06 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        if(lastRequest.isPresent() && LocalDateTime.now().isBefore(lastRequest.get().getCreatedAt().plusMonths(6))) {
поправил, в будущем буду делать через конфиг

2024-09-17 18:07 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/filter/recommendation/RequestFilterDto.java
> +public record RequestFilterDto(RequestStatus status, String messagePattern) {}
поправил

2024-09-17 18:09 UTC, KarabbasBarabas commented
да, не все комментарии сразу увидел
сейчас вроде всё исправил

2024-09-17 18:30 UTC, mysosnovskaya requested changes
Нужно немного доработать логи, а также разрешить конфликт в ПР (я смержила ветку Данилы, поэтому нужно подтянуть изменения из ветки hippogriff-master-stream6). После этого будем мержить)

2024-09-17 18:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("create - " + request);
Полностью объект нельзя логгировать, вдруг там какие-то конфиденциальные данные? Можно записать его id и какую-то часть информации, например requesterId и receiverId
Также нужно как-то человекопонятно написать сообщение в логи: например, "Created request with id = 2, requesterId = 7, receiverId = 28"

2024-09-17 18:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("getRequests - " + requests);
Здесь достаточно только id реквестов залоггировать. Также логи должны содержать человекопонятное пояснение "Returning filtered requests: 1, 5, 18"

2024-09-17 18:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("getRequest - " + request);
Аналогично про логи

2024-09-17 18:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("rejectRequest - " + request);
Аналогично про логи

2024-09-17 20:01 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("create - " + request);
поправил

2024-09-17 20:01 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("getRequests - " + requests);
поправил

2024-09-17 20:01 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("getRequest - " + request);
поправил

2024-09-17 20:01 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/RecommendationRequestService.java
> +        log.info("rejectRequest - " + request);
поправил

2024-09-17 20:02 UTC, KarabbasBarabas commented
конфликт разрешил

2024-09-18 17:50 UTC, mysosnovskaya approved these changes

2024-09-18 17:50 UTC, merged