Feature bjs2-26808 - Создание и настройка скиллов
CorporationX/user_service pull request #1453
Opened 2024-09-10 07:54 UTC by Alginin

Ссылка на Jira
https://faang-school.atlassian.net/jira/software/c/projects/BJS2/boards/59?selectedIssue=BJS2-26808

2024-09-10 14:24 UTC, mrkorolev reviewed
Хорошая работа!

2024-09-10 14:24 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +public class SkillController {
У нас проект будет содержать разные микросервисы (программы), которые будут общаться между собой. Соответственно, они будут обмениться сообщениями через JSON - для этих целей лучше использовать @ RestController.

Также тут не хватает аннотации @ RequestMapping - без нее нельзя будет отправить запрос на контроллер через url. Этот маппинг должен описывать то, с чем ты работаешь: 
@ RequestMapping("/skills"). Полезная инфа:

https://tproger.ru/translations/luchshie-praktiki-razrabotki-rest-api-20-sovetov

2024-09-10 14:24 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    }
Логика валидации данных - это часть бизнес логика твоего приложения (поэтому ее лучше поместить в сервис). В идеале сделать этот метод private (чтобы его было видно только в текущем классе).

Также лучше использовать готовые классы для проверки на null:
Objects.isNull(skill.getTitle())

2024-09-10 14:24 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    public void testCreateExistsByTitle() {
Если тест проверяет некорректное поведение, будет лучше его называть соответствующим образом: testCreateSkillFailingValidation (если придумаешь короче, то можно короче :))

2024-09-10 14:24 UTC, mrkorolev commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +    List<SkillDto> toDtoList(List<Skill> entityList);
Хорошечно)

2024-09-10 14:24 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        List<Skill> returnedSkill = skillService.getUserSkills(userId);
Ты уже описал ожидаемое поведение заглушки, можно сразу здесь получить элемент в списке через .get(0) и сравнить его с ожидаемым

2024-09-10 14:24 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
Почитал задание - в курсе, что там нет проверки на id юзера, но лучше все равно ее сделать (хорошая практика)

2024-09-10 14:24 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        SkillMapper mapper = Mappers.getMapper(SkillMapper.class);
У тебя уже есть @ Spy skillMapper, можешь не писать эту строчку

2024-09-10 14:24 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        resultList.sort(Comparator.comparingLong(skill -> skill.getSkillDto().getId()));
Дим, мы этот метод вместе писали - когда в resultList клали mapper.toCandidateDtoList и пытались ее сортировать получали UnsupportedOperationException. Почему?)

2024-09-10 14:24 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                .distinct()
Защищаешься тут от повторяющихся гарантов (тот же скилл, автор и юзер), но думаю это было продумано в другой задаче на создание рекомендаций (нельзя создать две одинаковые рекомендации). Все равно ты это проконтролировал, молодец.

2024-09-10 14:24 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +                    r.setReceiver(receiver);
Забыл проставить id рекомендациям (на всякий случай если бы они использовались)

2024-09-10 14:24 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    public SkillDto create(SkillDto skill) {
На методы контроллера нужно вешать аннотации маппинга, в зависимости от типа HTTP метода. Пример для этого метода: 
@PostMapping, еще хорошо на него повесить статус код при успешном выполнении @ResponseStatus(HttpStatus.OK)

Также будет полезно почитать про ResponseEntity и @ResponseStatus:
https://www.baeldung.com/spring-response-entity

2024-09-11 05:10 UTC, MamadjonovKO commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    }
+ к комменту выше, я также добавлял валидацию в контроллере, так как в задаче прямо указывалось сделать это на уровне контроллера. Однако, возможно, это была небольшая ошибка в требованиях задачи.
Кстати, можно использовать аннотации для валидации Java Bean прямо в DTO. Например, над полем title в SkillDto можно добавить аннотации @NotNull, @NotBlank и другие. Недавно сам это обнаружил, и это значительно упрощает валидацию.

2024-09-11 05:18 UTC, MamadjonovKO commented on src/main/java/school/faang/user_service/service/SkillService.java
> +}
Возможно стоить добавить аннотацию @Transactional на этот метод(но это не точно :) ), так как операции с базой данных требуют завершенности транзакции.  А @Transactional вроде как обеспечивает атомарность выполнения метода, откатывая изменения в случае исключений. Но я сам только начал изучать как это работает, возможно не ошибаюсь

2024-09-11 05:19 UTC, MamadjonovKO commented on src/main/java/school/faang/user_service/service/SkillService.java
> +}
Возможно стоить добавить аннотацию Transactional на этот метод(но это не точно :) ), так как операции с базой данных требуют завершенности транзакции. А Transactional вроде как обеспечивает атомарность выполнения метода, откатывая изменения в случае исключений. Но я сам только начал изучать как это работает, возможно не ошибаюсь

2024-09-15 15:55 UTC, 20cognosce requested changes

2024-09-15 15:55 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/SkillCandidateDto.java
> +@Data
equals и hashcode нам нужен?

2024-09-15 15:55 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public Skill createSkill(Skill skill) {
@Transactional
org.springframework

2024-09-15 15:55 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
Почему приватные методы выше публичных

2024-09-15 15:55 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +import jakarta.transaction.Transactional;
Спринговую используй

2024-09-15 15:55 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
@Transactional(readOnly=true)

2024-09-15 15:55 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        resultList.sort(Comparator.comparingLong(skill -> skill.getSkillDto().getId()));
?

2024-09-15 15:55 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        assertEquals(skill.getId(), skill1.getId());
Одного id мало для проверки
assertThat()
recursiveComparison()

по всем полям кроме дат

2024-09-16 09:24 UTC, Alginin commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        assertEquals(skill.getId(), skill1.getId());
Исправил, с помощью ПП

2024-09-16 11:00 UTC, Alginin commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
Исправил

2024-09-16 11:01 UTC, Alginin commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        resultList.sort(Comparator.comparingLong(skill -> skill.getSkillDto().getId()));
Здесь выполнена сортировка списка для дальнейшего сравнения assertIterableEquals они должны быть в одном порядке

2024-09-16 11:02 UTC, Alginin commented on src/main/java/school/faang/user_service/dto/SkillCandidateDto.java
> +@Data
Без аннотации Data не работает тест, буду разбираться в этом вопросе.

2024-09-16 17:45 UTC, 20cognosce requested changes

2024-09-16 17:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +import jakarta.transaction.Transactional;
Ну и где ты это исправил)

2024-09-16 17:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public Skill createSkill(Skill skill) {
Где транзакция?

2024-09-16 17:45 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
???

2024-09-19 08:22 UTC, Alginin reviewed
Исправил замечания.

2024-09-19 08:22 UTC, Alginin commented on src/main/java/school/faang/user_service/service/SkillService.java
> +import jakarta.transaction.Transactional;
Исправил. Извиняюсь трижды наперед, как то проглядел замечания)

2024-09-19 08:22 UTC, Alginin commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public Skill createSkill(Skill skill) {
Добавил транзакции

2024-09-19 08:22 UTC, Alginin commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
Добавил транзакции

2024-09-19 18:33 UTC, 20cognosce approved these changes

2024-09-19 18:34 UTC, merged