BJS2-26633 - Постановка целей
CorporationX/user_service pull request #1457
Opened 2024-09-10 09:19 UTC by fragmatik-top

2024-09-10 10:39 UTC, fragmatik-top commented
Чуть позже перезалью. Чутка не так сделал

2024-09-10 14:49 UTC, ostermal7 reviewed
Нет теста контроллера, замени везде в аргументах мин на positive, также в идеале подправь сервис, чтобы он был по принципу интерфейс сервис + класс Impl, который будет его имплементировать, чтобы потом не пришлось это делать

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +@Service
У контроллера правильно ставить либо @Controller, либо @RestController в зависимости от условий (у нас будет 2е)

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void createGoal(@Min(value = 0, message = "UserID must be at least 0") long userId,
корректно использовать @positive, если хочешь делать такую проверку

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/validator/goal/GoalValidator.java
> +        userRepository.findById(userId).orElseThrow(() ->
Если тебе не надо вытягивать объект, то использую existsById

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/validator/goal/GoalValidator.java
> +
пустая строка

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void update(@Min(value = 0, message = "GoalID must be at least 0") long goalId,
@positive

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +public class GoalService {
В идеале уже сейчас переписать в интерфейс сервис + его имплементация

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +@Component
Здесь лучше @Service

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +                goalDto.parentId() == null ? null : goalDto.parentId());
Эта проверка не имеет смысла

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public void createGoal(long userId, GoalDto goalDto) {
мне кажется, что создание объекта должно возвращаться энтити, а не воид

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        Goal goal = goalValidator.validateUpdate(goalId, goalDto);
у тебя в валидации гоалдто не юзается, значит надо убрать

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        goalValidator.validateGoalId(goalId);
Зачем тут валидация? Если передадут неправильное айди, то у тебя просто ничего не удалится из базы, ничего страшного в этом нет.

2024-09-10 14:49 UTC, ostermal7 commented on src/main/java/school/faang/user_service/exception/RestResponseExceptionHandler.java
> +    @ExceptionHandler(ResourceNotFoundException.class)
Здесь можно не указывать класс, он сам поймет по аргументу

2024-09-11 10:29 UTC, fragmatik-top commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +@Service
+

2024-09-11 10:30 UTC, fragmatik-top commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void createGoal(@Min(value = 0, message = "UserID must be at least 0") long userId,
+

2024-09-11 10:30 UTC, fragmatik-top commented on src/main/java/school/faang/user_service/validator/goal/GoalValidator.java
> +        userRepository.findById(userId).orElseThrow(() ->
+

2024-09-11 10:30 UTC, fragmatik-top commented on src/main/java/school/faang/user_service/validator/goal/GoalValidator.java
> +
+

2024-09-11 10:30 UTC, fragmatik-top commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public void update(@Min(value = 0, message = "GoalID must be at least 0") long goalId,
+

2024-09-11 10:30 UTC, fragmatik-top commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +@Component
+

2024-09-12 07:41 UTC, VitoS1C commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public void createGoal(long userId, GoalDto goalDto) {
````java
    public GoalDto createGoal(long userId, GoalDto goalDto) {
        goalValidator.validateCreationGoal(userId, MAX_NUMBER_ACTIVE_GOALS);

        Goal saveGoal = goalRepository.create(goalDto.tittle(),
                goalDto.description(),
                goalDto.parentId() == null ? null : goalRepository.findById(goalDto.parentId()).get().getId());

        List<Skill> skills = skillService.getSkillsByTitle(goalDto.titleSkills());
        saveGoal.setSkillsToAchieve(skills);
        return goalMapper.toDto(goalRepository.save(saveGoal));
    }
    
    Возможно так лучше сделать, чтоб на фронт прилетал созданный объект

2024-09-12 07:44 UTC, VitoS1C commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
````java
public GoalDto createGoal(@Positive long userId, @Validated GoalDto goalDto) {
        goalValidator.validateUserId(userId);
        return goalService.createGoal(userId, goalDto);
    }
    И в контроллерах отправлять ответом созданную сущность.

2024-09-13 16:44 UTC, mikhailov26 requested changes

2024-09-13 16:44 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Полностью согласен с коллегой, рефакторим

2024-09-13 16:44 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +public class GoalService {
Абсолютно верно. Рефакторим

2024-09-13 16:44 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public void createGoal(long userId, GoalDto goalDto) {
Верно, на созвоне я точно помню проговаривал подобный момент, если создаём то это обязательно возвращаем

2024-09-13 16:44 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
Интерфейс + его имплементация

2024-10-02 15:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @PostMapping("userId/{userId}")
у тебя везде слэши в начале потерялся

2024-10-02 15:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +                      @NotNull(message = "Title cannot be null")
NotBlank содержит в себе Notnull, зачем это дублирование

2024-10-02 15:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +                      @NotNull(message = "Description cannot be null")
везде так, думаю стоит убрать нулл

2024-10-02 15:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/dto/goal/GoalFilterDto.java
> +}
почему не рекорд?

2024-10-02 15:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/dto/goal/GoalFilterDto.java
> +
пробел убери

2024-10-02 15:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/filter/goal/GoalTitleFilter.java
> +
Аннотация компонент на всех фильтрах

2024-10-02 15:02 UTC, ostermal7 commented on src/main/java/school/faang/user_service/exception/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends RuntimeException {
еще бы в globalexceptionhandler все внести, если не будет ()не помню к какому спринту эта задача относится, мб тогда не надо было, но витя рефактор делал уже)

2024-10-02 16:26 UTC, VitoS1C commented on src/main/java/school/faang/user_service/exception/ResourceNotFoundException.java
> +public class ResourceNotFoundException extends RuntimeException {
В принципе есть EntityNotFoundException, и к нему уже есть обработчик

2024-10-02 16:44 UTC, mikhailov26 commented
![image](https://github.com/user-attachments/assets/d49047c1-e075-4b35-b223-c78d67eb70c4)

2024-10-02 16:45 UTC, mikhailov26 commented
Исправить

2024-10-02 21:25 UTC, ostermal7 commented
У тебя все ок с коммитами? Тут +1300 строк кода стало

2024-10-07 16:25 UTC, merged