Покупка премиум доступа BJS2-27015
CorporationX/user_service pull request #1464
Opened 2024-09-10 18:13 UTC by sultan-inked

Первая часть задачи, покупка премиум доступа, вторая покупка промоушена ещё не готова

2024-09-10 18:42 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +                period.getCurrency());
напрашивается Builder. билдер работает с рекордами?

2024-09-10 18:42 UTC, IvanTsegelnyuk commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +                .body(ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST, exception.getMessage()));
ты пробовал поймать так ошибку? по-моему у  feignException просто так не ловится читаемое сообщение ошибки, потому что там перехватывается json и его надо парсить objectMapper'ом. Но может ошибаюсь

2024-09-10 19:51 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +                .body(ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST, exception.getMessage()));
Да ты прав, в detail не только сообщение а весь json, исправил, теперь только сообщение, тесты переделаю и залью, спасибо!

2024-09-10 20:42 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +                period.getCurrency());
Да, оказывается можно с рекордом билдер юзать, спасибо, исправил

2024-09-15 07:32 UTC, sultan-inked commented
Вторая часть задания

2024-09-15 07:38 UTC, sultan-inked commented on src/main/resources/db/changelog/db.changelog-master.yaml
Сюда пока не добавял, на случай если придется менять таблицу, после ревью добавлю

2024-09-15 10:49 UTC, kripersh27 commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    }
Может этот метод в сервисный слой вынести?

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/event/Event.java
>      @Temporal(TemporalType.TIMESTAMP)
На сколько я помню, что для ЛокалДейтТайм - аннотация не нужна, jpa понимает как маппить эту переменную.

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/payment/Currency.java
> +    USD, EURO, RUB
Лучше тремя буквами обозначать, то есть EUR

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +@Data
ДАта c jpa лучше не использовать

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    @Temporal(TemporalType.TIMESTAMP)
Темпорал можно убрать

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    @Enumerated(EnumType.ORDINAL)
На мой взгляд лучше использовать EnumType.STRING, чтобы в бд были строковые значения, а не цифры(порядковый номер енума), так проще не запутаться.

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/PromotionTariff.java
> +        this.coefficient = audienceReach;
А тут не ошибка? коэффициенту присваивается аудиенс рич

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +@Data
Дата в jpa

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +    @Enumerated(EnumType.ORDINAL)
EnumType.STRING

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +    @Temporal(TemporalType.TIMESTAMP)
Можно без @Темпорал

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/promotion/ResponseEventDto.java
> +        String promotionTariff,
ПромоушенТариф - это енум, так пусть он и будет в дто, маппером он автоматически мапится и не надо отдельным метод в маппере для конфертации.

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/dto/promotion/ResponseUserDto.java
> +        String promotionTariff,
Можно писать енум сюда, и не конверитировать в стринг

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        var premium = new Premium(null, user, LocalDateTime.now(), LocalDateTime.now().plusDays(period.getDays()));
можно билдер использовать

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +    }
Методы очень похожие, может общую логику вынести в приватный метод и сократить код?

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +@Slf4j
логирование поставил, но не используешь

2024-09-15 10:49 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +    }
Эти два метода очень кодом похожи на два следующих метода, вынеси общую логику в приватный метод

2024-09-15 14:01 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/payment/Currency.java
> +    USD, EURO, RUB
Да, согласен, это в пэймент-сервисе так было, тогда здесь сделаю EUR, но потом в пэйменте надо будет сменить когда до него доберёмся

2024-09-15 14:02 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +@Data
Да, согласен, но у нас в пректе во всех сущностях он указан, решил не выделяться, тогда надо везде менять?

2024-09-15 14:03 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    @Enumerated(EnumType.ORDINAL)
Ок

2024-09-15 14:04 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    @Temporal(TemporalType.TIMESTAMP)
Чем аргументировано? Просто интересно, я не разбираюсь, сделал как в других сущностях

2024-09-15 14:05 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/PromotionTariff.java
> +        this.coefficient = audienceReach;
Строку коэфицент добавил для гибкости, если надо будет в дальнейшем добавить какую то сложную логику по сортировке, пока просто кто за больший охват оплатил, тот выше в списке

2024-09-15 14:06 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +@Data
Да, у нас во всех сущностях они, надо вынести на обсуждение наверно

2024-09-15 14:06 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +    @Enumerated(EnumType.ORDINAL)
Ок, но в проекте везде ординал

2024-09-15 14:08 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        var premium = new Premium(null, user, LocalDateTime.now(), LocalDateTime.now().plusDays(period.getDays()));
Согласен, но с билдером код растягивается в объёме вниз, если это ок, то переделаю

2024-09-15 14:08 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +@Slf4j
Точно, спасибо, забыл добавить

2024-09-15 14:10 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +    }
Дженериками можно следать?

2024-09-15 14:11 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +    }
Согласен, постараюсь что нибудь придумать

2024-09-15 14:11 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    }
Да, ты прав, вынесу

2024-09-15 14:30 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/promotion/ResponseEventDto.java
> +        String promotionTariff,
У меня не получилось, может покажешь, возможно не понял как, мне просто название тарифа требуется =(

2024-09-15 14:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/promotion/ResponseEventDto.java
> +        String promotionTariff,
null выдает:
```
{
    "id": 3,
    "title": "Test event 2",
    "ownerId": 2,
    "promotionTariff": null,
    "numberOfViews": 9947
}
```

2024-09-15 14:31 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/promotion/ResponseEventDto.java
> +        String promotionTariff,
Поэтому в мапере то стринг делаю

2024-09-15 14:35 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/promotion/ResponseEventDto.java
> +        String promotionTariff,
У меня есть предположение почему так, в сущности нет самого енама, еман в другой сущности, он в сущности промоушен, может поэтому налл выдал

2024-09-15 15:17 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/event/Event.java
>      @Temporal(TemporalType.TIMESTAMP)
Но я не создавал эти поля, только промоушен добавил

2024-09-15 15:28 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    @Temporal(TemporalType.TIMESTAMP)
То что jpa знает как мапить эту переменную в бд, и не обязательна эта аннотация

2024-09-15 15:28 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    @Temporal(TemporalType.TIMESTAMP)
аннотация Темпорал предназначена для java.util.Date и java.util.Calendar

2024-09-16 08:45 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    @Temporal(TemporalType.TIMESTAMP)
Хоршо, уберу

2024-09-16 08:45 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        var premium = new Premium(null, user, LocalDateTime.now(), LocalDateTime.now().plusDays(period.getDays()));
С билдером лучше, переделал

2024-09-16 08:57 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +    @Temporal(TemporalType.TIMESTAMP)
Убрал

2024-09-16 16:17 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public ResponsePremiumDto buyPremium(@RequestParam(name = "days") int days) {
Пишут, что не рекомендовано с Post использовать параметры.
Предпочтительней все данные запихивать в body запроса.

2024-09-16 16:37 UTC, amilosh commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriodValues.java
> +    public static final double COST_YEAR = 80.0;
Такие значения, которые будут часто меняться в процессе эксплуатации приложения, лучше держать в properties.
Если нужно будет поменять значение, то просто в файлике меняется значение и делается рестарт приложения.

Но это минорная задача. Пока можно не делать, ни на что не влияет.

2024-09-16 16:38 UTC, amilosh commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriodValues.java
> +    public static final int DAYS_THREE_MOTH = 62;
93

2024-09-16 16:40 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/util/PremiumErrorMessages.java
> +    public static final String PREMIUM_PERIOD_NOT_FOUND = "Premium period in %s days not found, please select between: %s";
between: -> among

2024-09-16 16:45 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserContextService.java
> +            throw new PremiumCheckFailureException(exception.getMessage());
UserContextService ничего не знает, кто его вызывает и как использует.
И он может быть использован в разных местах.
Тут надо что-то общее бросить. Что для всего аплика.

2024-09-16 16:50 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/premium/ResponsePremiumDto.java
> +public record ResponsePremiumDto(
мне больше нравится PremiumResponseDto
чтобы по первому слову было понятно что за dto, а уже дальше подробности

типа если будет
ResponsePremiumDto
ResponseUserDto
ResponseEventDto - тяжело читать

PremiumResponseDto
UserResponseDto
EventResponseDto - мне кажется легче воспринимается

2024-09-16 16:51 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/premium/ResponsePremiumMapper.java
> +public interface ResponsePremiumMapper {
просто PremiumMapper

2024-09-16 16:51 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/premium/ResponsePremiumMapper.java
> +    ResponsePremiumDto toDto(Premium premium);
toPremiumResponseDto

2024-09-16 16:59 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumCheckService.java
> +                new PremiumNotFoundException(USER_NOT_FOUND, userId));
Наверное надо сообщение более подробное отправить. Типа: юзер не был найдет во время покупки премиума.

А то немного смущает запись PremiumNotFoundException(USER_NOT_FOUND

2024-09-16 17:16 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/util/PremiumErrorMessages.java
> +    public static final String USER_ALREADY_HAS_PREMIUM = "The user already has a premium subscription before: %s";
userId ещё добавь

2024-09-16 17:19 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumCheckService.java
> +public class PremiumCheckService {
PremiumValidationService

2024-09-16 17:21 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        User user = premiumCheckService.checkUserForSubPeriod(userId);
Я бы разделил.
Сначала просто бы нашел юзера в репозитории (с бросанием user not found)
А потом вызвал бы void premiumValidationService.validate(User user)

2024-09-16 17:25 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriodValues.java
> +    public static final double COST_YEAR = 80.0;
Да, я начал так делать, но потом передумал, ок, тогда пока оставлю так

2024-09-16 17:28 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public ResponsePremiumDto buyPremium(@RequestParam(name = "days") int days) {
Хорошо, сделаю дто, занчит нормально делать дто с одним полем?

2024-09-16 17:28 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriodValues.java
> +    public static final int DAYS_THREE_MOTH = 62;
Точно, спасибо, не заметил

2024-09-16 17:28 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/util/PremiumErrorMessages.java
> +    public static final String PREMIUM_PERIOD_NOT_FOUND = "Premium period in %s days not found, please select between: %s";
Ок

2024-09-16 17:29 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/premium/ResponsePremiumDto.java
> +public record ResponsePremiumDto(
Согласен, переименую

2024-09-16 17:30 UTC, sultan-inked commented on src/main/java/school/faang/user_service/mapper/premium/ResponsePremiumMapper.java
> +public interface ResponsePremiumMapper {
Ок

2024-09-16 17:30 UTC, sultan-inked commented on src/main/java/school/faang/user_service/mapper/premium/ResponsePremiumMapper.java
> +    ResponsePremiumDto toDto(Premium premium);
Хорошшо

2024-09-16 17:30 UTC, amilosh commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClient.java
> +@FeignClient(name = "payment-service", url = "${payment-service.host}:${payment-service.port}")
payment-service:
  host: localhost
  port: 9080
  url: ${localhost}:${port}   (тут точный синтаксис не помню - погуглишь)

url = "${payment-service.url}

2024-09-16 17:30 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/PremiumCheckService.java
> +                new PremiumNotFoundException(USER_NOT_FOUND, userId));
Хорошо, дополню

2024-09-16 17:31 UTC, amilosh commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClient.java
> +    @PostMapping("/api/payment")
/api - можно добавить в 

url: ${localhost}:${port}/api

2024-09-16 17:32 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        User user = premiumCheckService.checkUserForSubPeriod(userId);
Переделаю, спасибо

2024-09-16 17:33 UTC, sultan-inked commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClient.java
> +    @PostMapping("/api/payment")
Да, точно, спасбо

2024-09-16 17:37 UTC, amilosh commented on src/main/java/school/faang/user_service/entity/payment/PaymentStatus.java
> +    SUCCESS, NOT_SUCCESS
NOT_SUCCESS -> FAILD

+ я люблю когда енамы вертикально

2024-09-16 17:40 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumCheckService.java
> +        if (paymentResponse.status().equals(PaymentStatus.NOT_SUCCESS)) {
через == енамы можно сравнивать

плюс в статик импорт можно перенести

2024-09-16 17:43 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        premiumCheckService.checkPaymentResponse(paymentResponse, userId, period);
валидацию в отдельный класс перенесли

а тут я думаю пока приватным методом можно обойтись

2024-09-16 17:48 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumCheckService.java
> +        if (paymentResponse.status().equals(PaymentStatus.NOT_SUCCESS)) {
not equals sucsess

2024-09-16 17:49 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/util/PremiumBuilder.java
> +
.

2024-09-16 17:50 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/util/PremiumBuilder.java
> +    public Premium getPremium(User user, PremiumPeriod period) {
buildPremium

2024-09-16 17:52 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        Premium premium = premiumBuilder.getPremium(user, period);
getPremium - как будто откуда-то берем, типа из базы
лучше buildPremium

2024-09-16 17:52 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/util/PremiumBuilder.java
> +public class PremiumBuilder {
Наверное не component
просто util class

2024-09-16 17:55 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        }
Можно не удалять - сохранится история его покпок.
Всё равно у нас все premium для конкретного юзера будут по датам отсортированы, без пересечений tart и end.
Просто нужно будет добавить метод getLastPremium.

2024-09-16 17:58 UTC, amilosh commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        premiumCheckService.checkPaymentResponse(paymentResponse, userId, period);
две строчки в отдельный метод, чтобы выглядела как атомарная операция
типа
private void completePaymentForPremium()

2024-09-16 18:02 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +public class PremiumControllerAdvice {
по-английски advice - это совет, не знаю, почему они так назвали
я бы переименовал PremiumControllerExceptionHandler

2024-09-16 18:02 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +        log.info(exception.getMessage());
error

2024-09-16 18:03 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +                .body(ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST, exception.getMessage()));
ProblemDetail - это как удалось нагуглить такое?

2024-09-16 18:04 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +    public ResponseEntity<ProblemDetail> premiumCheckFailureExceptionHandler(PremiumCheckFailureException exception) {
handlePremiumCheckFailureException

2024-09-16 18:05 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +    public ResponseEntity<ProblemDetail> feignExceptionHandler(FeignException exception) {
А это наверное лучше в какой-то общий app exception handler

2024-09-16 18:07 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +            log.info("Json processing exception: {}", exc.getMessage());
тут наверное надо что-то бросить типа
а то если feign упадет, то код дойдёт досюда и просто залогируется
а на фронт никакого сообщения об ошибке не вернется

2024-09-16 18:09 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +    public ResponseEntity<ProblemDetail> feignExceptionHandler(FeignException exception) {
Хотя по правде можно эту не отлавливать.
А отлавливать все RunTimeException, которые не вошли в список, которые мы указали

2024-09-16 18:12 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/promotion/PromotionController.java
> +    private final ResponseEventMapper responseEventMapper;
Так же как и для PremiumMapper, я расписывал.

2024-09-16 18:18 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public ResponsePremiumDto buyPremium(@RequestParam(name = "days") int days) {
да

2024-09-17 07:22 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/user/UserContextService.java
> +            throw new PremiumCheckFailureException(exception.getMessage());
Сделал общий ексепнш

2024-09-17 07:39 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/promotion/PromotionController.java
> +    private final ResponseEventMapper responseEventMapper;
Спасибо, поменял

2024-09-17 08:57 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/util/PremiumBuilder.java
> +public class PremiumBuilder {
UtilClass создает бины? Если только его прописываю не инжектится

2024-09-17 09:00 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/util/PremiumBuilder.java
> +public class PremiumBuilder {
А, наверно ты имеешь в виду что статик метод сделать

2024-09-17 10:02 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +    public ResponseEntity<ProblemDetail> feignExceptionHandler(FeignException exception) {
В общий вынем, тут именно FiegnExceptiion требуется обработать, что бы ошибки из другого сервиса клиенту перенаправлять, например если payment-servuce не доступен
```
{
    "type": "about:blank",
    "title": "Bad Request",
    "status": 400,
    "detail": "Connection refused executing POST http://localhost:9080/api/payment",
    "instance": "/premiums/buy",
    "properties": null
}
```

2024-09-17 10:03 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/premium/PremiumControllerAdvice.java
> +            log.info("Json processing exception: {}", exc.getMessage());
Да, ты прав, сделал обработку, что бы клиент получал ответ

2024-09-17 19:24 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/promotion/UserMapperPromotion.java
> +public interface UserMapperPromotion {
Выглядит как просто UserMapper

у нас тут только один мап метод из User в UserResponseDto

2024-09-17 19:25 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/promotion/UserMapperPromotion.java
> +            return "Don't have promotion";
думаю можно null

2024-09-17 19:26 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/promotion/UserMapperPromotion.java
> +        return userPromotion.getPromotionTariff().toString();
userPromotion.getPromotionTariff() - каким-либо образом может быть null?

2024-09-17 19:28 UTC, amilosh commented on src/main/java/school/faang/user_service/mapper/promotion/EventMapperPromotion.java
> +public interface EventMapperPromotion {
EventMapper

2024-09-17 19:51 UTC, amilosh commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        executorService.execute(() -> promotionTaskService.decrementUserPromotionViews(users));
Как я понял, мы используем executorService чтобы текущий поток разбить на подпотоки (распараллелить).
А здесь - getPromotedUsersBeforeAllPerPage вызывается каждым юзером по отдельности из своих браузеров. То есть этот метод и так будет в разных потоках. Каждый поток на каждый реквест.

Думаю тут можно не использовать.

Но для надежности у Димы спроси.

2024-09-17 19:54 UTC, amilosh commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +    @Transactional(propagation = Propagation.REQUIRES_NEW)
ещё не проходили, но вроде Ваня говорил, что если в одном и том же классе, то REQUIRES_NEW не будет срабатывать

тут тоже у Димы надо спрашивать

2024-09-17 19:57 UTC, amilosh commented on src/main/java/school/faang/user_service/repository/promotion/EventPromotionRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
Тут мои полномочия всё)

2024-09-17 20:57 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/promotion/EventPromotionRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
Это говорит что бд не будет никому давать разрешения менять конкретную запись пока не закончится транзакция, если правильно понял

2024-09-17 21:00 UTC, sultan-inked commented on src/main/java/school/faang/user_service/mapper/promotion/UserMapperPromotion.java
> +        return userPromotion.getPromotionTariff().toString();
Да, если у пользователя нет промоушена, на данный момент не действительный промоушен удаляется

2024-09-18 16:57 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        }
Сделал так что бы не удалялись, просто дабавляется новая если нет активных премиумов

2024-09-18 17:00 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        executorService.execute(() -> promotionTaskService.decrementUserPromotionViews(users));
Я запускаю второй поток что бы клиент не ждал пока я сделаю декремент показов каждого промоушена, и сразу отдать список, и уже потом доделывать декремент, ну задумка была такая, если я правильно понял подсказку Димы

2024-09-18 20:21 UTC, sultan-inked commented on src/main/java/school/faang/user_service/mapper/promotion/UserMapperPromotion.java
> +public interface UserMapperPromotion {
Да, переименовал

2024-09-18 20:22 UTC, sultan-inked commented on src/main/java/school/faang/user_service/mapper/promotion/UserMapperPromotion.java
> +            return "Don't have promotion";
+

2024-09-21 19:22 UTC, 20cognosce requested changes

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/entity/promotion/EventPromotion.java
> +    }
Почему не аннотациями?

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +}
/

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/entity/promotion/UserPromotion.java
> +@Table(name = "user_promotion")
Соблюдай порядок аннотаций
Сначала важные - JPA
потом lombok'овские

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +                CASE WHEN up.coefficient IS NULL THEN 1 ELSE 0 END,
Не понял, почему ты проверяешь только наличие промоушена
Коэффициент - должен быть полем внутри проумеша

Если его нет - то 0, если есть - то берем коэф из промоушена, самый дешевый дает промоушен 1, средний - 2, самый дорогой - 3

Ты уверен, что у тебя корректный порядок? Если промоушена нет, то 1
И у тебя по убыванию стоит, то есть те, у которых промоушена нет, первыми будут выдаваться?

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/event/EventRepository.java
> +            """)
same

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/EventPromotionRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
Почему ты используешь локи на уровне БД?

Тебе нужна синхронизация только при асинхронном декременте, чтобы два потока не сделали -1 вместо -2, делай на уровне приложения им синхронизацию на методе decrementPromotionViews

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/EventPromotionRepository.java
> +                    SET number_of_views = number_of_views -1
минус 1 пробел

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/EventPromotionRepository.java
> +    void decrementPromotionViews(@Param("id") long id);
И почему на каждый чих-пых ты делаешь декремент и грузишь базу, это не круто

Либо жди какой-нибудь интервал и сбрасывай в БД сразу -50, -100 
Пусть сколько угодно потоков в приложении увеличат счетчик просмотров, и раз в 10 секунд сбрось его один раз в БД

и тогда конкуренции за декремент не будет

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/UserPromotionRepository.java
> +    @Lock(LockModeType.PESSIMISTIC_WRITE)
Не нравится мне это

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        Premium premium = buildPremium(user, period);
Не импортируй так
Почему билдер не часть класса Premium?

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +                eventPromotionRepository.delete(eventPromotion);
Можно не удалять, а помечать, что кончилось

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        executorService.execute(() -> promotionTaskService.decrementUserPromotionViews(users));
Да, моя идея была в том чтобы списывать просмотры в фоне, а не на каждый показ

Но реализовывать это надо оптимально, а не так, что ты блочишь всю базу и миллиард транзакций создаешь отдельно под КАЖДЫЙ ПРОСМОТР

Это большой косяк, полный оверхед по всему

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +        users.stream()
Все методы переделать

ОДИН ЗАПРОС на апдейт всех просмотров пользователей
А ЕЩЕ ждать какое-то время / какое-то количество просмотров и в этом одном запросе СРАЗУ БАТЧЕМ задекрементить кучу премиумов на -50, -100, и так далее, каждого на сколько надо

Если превышен лимит - выставить статус премиуму - КОНЧИЛСЯ

В таком стиле, а не такой генератор транзакций

2024-09-21 19:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +                up.creation_date ASC
Мутная тема в этом запросе сейчас написана, декомпозируй его пожалуйста

2024-09-21 19:22 UTC, 20cognosce commented
Conflicting files
src/main/resources/application.yaml

2024-09-27 12:34 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/UserRepository.java
Я правда старался сделать нормальный запрос:
1) Сначала сливает пользовтелей и промошены, промоушены только те у которых есть просмотры
2) Далее делит список на две группы, первая (0) те у кого есть промоушн, вторая (1) те у кого нет (null)
3) После сортирует по коефиценту промоушена, те у кого выше в начале списка,
    если коефицент одинаковый, то по дате покупки, сначала старые,
4) И в конце сортировка по дате созднаия пользователей, сначала новые

2024-09-27 12:36 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +            LIMIT :limit
Я правда старался сделать нормальный запрос:
1) Сначала сливает пользовтелей и промошены, промоушены только те у которых есть показы
2) Далее делит список на две группы, первая (0) те у кого есть промоушн, вторая (1) те у кого нет (null)
3) После сортирует по коефиценту промоушена, те у кого выше в начале списка,
    если коефицент одинаковый, то по дате покупки, сначала старые,
4) И в конце сортировка по дате созднаия пользователей, сначала новые
Если это тоже не то, покажи пожалуйста как правильно, а то я не понимаю (

2024-09-27 20:16 UTC, 20cognosce requested changes
Ретраи убрать
И другие доработки

2024-09-27 20:16 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/EventPromotionRepositoryBatch.java
> +    )
Зачем тебе ретраи???

2024-09-27 20:16 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +            LIMIT :limit
![image](https://github.com/user-attachments/assets/d4086fce-1e16-4875-a501-51ba5494a702)

```
SELECT *
            FROM users u
            LEFT JOIN user_promotion up ON u.id = up.user_id
            ORDER BY
                up.coefficient DESC NULLS LAST, -- primary sorting by coef
                up.creation_date ASC, -- secondary sorting for equal coefs
                u.id DESC -- final sorting those, which have no promotion
            OFFSET 0
            LIMIT 5
```

2024-09-27 20:16 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +        }
Где у тебя тут триггер по таймингу или threshold'y для запуска декремента в базе???

2024-09-27 20:16 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +            userPromotionViews.clear();
Это не потокобезопасно нифига
Между 61 и 62 строчкой тебе добавили новый декремент в мапу.

На время копирования и очистки лочь всю мапу тогда

2024-09-27 20:16 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/UserPromotionRepositoryBatch.java
> +    }
Выглядит работоспособно, но sql запрос куда-то в более подходящее место вынеси, или если можно, не через String его задай

2024-09-27 20:16 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/UserPromotionRepositoryBatch.java
> +    }
Сделай короче весь этот метод красивее

2024-09-27 20:16 UTC, 20cognosce commented
Конфликт опять

2024-10-01 14:19 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +            LEFT JOIN user_promotion up ON u.id = up.user_id AND up.number_of_views > 0
Добавил `AND up.number_of_views > 0` иначе те кто купил промоушн раньше и показов не осталось, показваются выше тех у кого еще есть показы

2024-10-01 14:20 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +            LIMIT :limit
Спасибо, так лучше

2024-10-01 14:22 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/promotion/batch/util/PromotionBatchPreparedStatementSetter.java
Сделал реализацию, подумал лучше так, чем одинаковый код писать, но я не понял как сделать это в репозитории, который интерфейс

2024-10-01 14:39 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
Сделал откат обратно в список в случает SQLExceptiion, и по синхронизации все верно?

2024-10-02 11:29 UTC, 20cognosce requested changes
почти готово
билд фейл пофикси

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +                u.id DESC
Ну тут не по id надо было у тебя сортировать не премиумных пользователей

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/event/EventRepository.java
> +                e.id DESC
и тут

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +            decrementUserPromotionView();
путают такие нейминги view - views, вся разница

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +        if (!userPromotionViews.isEmpty() && isUserViewsDecrementRunning.compareAndSet(false, true)) {
isUserViewsDecrementRunning.compareAndSet(false, true)
что это за условие

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +            log.info("Event promotion views batch decrement: {}", eventPromotionViews);
лог внутрь блока синк

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +                eventPromotionViews.putAll(eventPromotionViewsCopy);
не понял
если у тебя было
id 1 : -100

ты стер и после запроса в бд ошибка
делаешь пут в мапу а там уже лежит 
id 1 : -10

что у тебя получится тут -110? сомневаюсь

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +    private void decrementEventPromotionViews() {
дай нормальные имена методов
почему на 6 методов 2 имени

2024-10-02 11:29 UTC, 20cognosce commented on src/main/java/school/faang/user_service/repository/promotion/batch/UserPromotionRepositoryBatch.java
> +public class UserPromotionRepositoryBatch {
нет интерфейса никакого в спринге:?

2024-10-03 06:55 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +                eventPromotionViews.putAll(eventPromotionViewsCopy);
Да, точно, спасибо, снова кринж)

2024-10-04 17:42 UTC, 20cognosce approved these changes

2024-10-04 17:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +            synchronized (eventPromotionViews) {
Можно было бы и локи юзать

2024-10-04 17:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/promotion/PromotionTaskService.java
> +    private void batchDecrementUserPromotionView() {
Для user и event фактически одинаковые методы, нельзя было это дублирование обойти каким-нибудь обобщением

2024-10-04 17:43 UTC, merged