Постановка целей BJS2-26821
CorporationX/user_service pull request #1468
Opened 2024-09-10 19:58 UTC by Peregruzochka

2024-09-10 20:17 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public List<Goal> findSubtaskByGoalId(Long goalId) {
Не реализовал этот метод через фильтр, потому что в GoalRepository был готовый метод с нативным SQL-запросов, что вроде как является лучшей практикой
Реализовал функционал фильтров в методе findGoalsByUser()

2024-09-11 01:04 UTC, mrkorolev reviewed
Круто. Единственный момент - я чуть не сломал голову, пока пытался понять как работает метод updateGoal (в основном когда прыгал из самого метода в валидации и обратно, запутался). Может быть я его не понял - ведь я ночью делаю ревью.

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +@Slf4j
Ты убрал все логи из контроллера - допустим, что позже ты их добавишь снова, раз оставил аннотацию)

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (goal.getTitle() == null || goal.getTitle().isBlank()) {
Objects.isNull(goal.getTitle())

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Круто, что вызываешь existsById. Однако каждый вызов existsById делает запрос и проверяет присутствие entity по этому id в базе. На мой взгляд лучше получить список всех entity по их id и сравнить длину первоначального списка с тем, что вернет бд:

List<Long> skillIds = skills.stream().map(Skill::getId).toList();
if (skillRepository.findAllById(skillIds).size() != skills.size()) {
// logging and throwing exception logic...
}

С другой стороны exists проверяет только наличие entity, и если entity большая ему не нужно ее тянуть целиком. Дим, как лучше?

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        validateGoalSkillsExist(goal);
Круто, что вынес в отдельные методы, т.к. некоторая валидация переиспользуется в других методах сервиса. Только вот когда ты будешь писать тесты на эту валидацию ты будешь проверять "кусочек метода сервиса", а не сам метод целиком.

Чисто моя точка зрения, я так чувствую) Может быть Дима меня пошлет куда подальше))

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        goal.setUsers(List.of(user));
А юзеру в его цели (user.getGoals) не нужно её сохранять? Или я чего то не понял? Попробуй в таблице user_goal посмотреть кол-во записей до и сопле действия (без правок) и отпиши.

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Вроде как(!) тут можно Patch использовать. Но не уверен.

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +                .orElseThrow();
Тут выбрасывается NoSuchElementException - будешь его в тестах проверять? Или другой тип укажи (свой или из тех, что мы обычно кидаем)?

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (goal.getStatus() == GoalStatus.COMPLETED) {
.equals()

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public List<Goal> findSubtaskByGoalId(Long goalId) {
Да, Дима говорил, что так и надо)

В задании написано, что goalId - id цели-родителя, но с неймингом они решили не заморачиваться. Поэтому лучше назвал бы параметр parentGoalId.

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private final List<GoalFilter> goalFilters;
На мой взгляд лучше будет задать тут конкретную коллекцию через new - так ты всегда будешь знать, в какую конкретно реализацию List у тебя происходит внедрение.

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        List<Goal> userGoal = user.getGoals();
userGoals

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +                );
Жестко)

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +    List<GoalDto> toDtoList(List<Goal> subtasks);
Good

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +                    return skill;
Можно builder использовать, так будет чище.

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +        }
Не нужно else - у тебя и так метод вернется если parentId null. Ну и builder.

2024-09-11 01:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +
А каждому юзеру не нужно добавить скиллы из завершенной цели?

2024-09-13 08:13 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private final List<GoalFilter> goalFilters;
А spring будет, инжектить данные в список, который уже инициализирован?
Мб есть смысл использовать реализацию List в методах?

2024-09-13 17:02 UTC, 20cognosce requested changes

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    ) {
В одну строчку, места хватает

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @ResponseStatus(HttpStatus.OK)
Итак дефолтный статус

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
?

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    ) {
Post, потому что у Get нет тела по спецификации
Статус лишний
Параметры в одну строку

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +    private GoalStatus status;
Валидация где

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public Goal createGoal(Long userId, Goal goal) {
Транзакция

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        goal.setUsers(List.of(user));
Нужно структура таблиц смотреть
если в связную таблицу many-to-many добавляется связь, то не надо с другой стороны её снова добавлять

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public Goal updateGoal(Goal goal) {
Транзакция

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +            existingGoal.setStatus(GoalStatus.COMPLETED);
Не понял

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        }
Можно без таких больших блоков if else

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    public void deleteGoal(Long goalId) {
Транзакция

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    @Transactional
А тут добавил)
readOnly

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +                    if (!skillRepository.existsById(skillId)) {
А нельзя одним запросов все проверить?

2024-09-13 17:02 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Можно возвращать true / false что все из них есть в таблице

2024-09-13 17:02 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +    private List<GoalFilter> goalFilters;
Почему замокал фильтры, где на них проверки

2024-09-13 17:02 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +                .build();
А можно заранее их пересоздавать в @BeforeEach и в каждом методе юзать

2024-09-13 17:02 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +        assertEquals(expectedMessage, resultMessage);
Сообщение не надо проверять, достаточно наличие ошибки

2024-09-13 17:09 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +        assertEquals(expectedMessage, resultMessage);
@20cognosce Потому что этот метод может кидать один и тот же тип ошибки при разных условиях. Потому и проверяется сообщение (причина, по которой она выпала).

2024-09-13 17:36 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
DeleteMapping может no_content возвращать, почему это плохо?

2024-09-14 07:24 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Отталкивался от этого
![image](https://github.com/user-attachments/assets/35584058-4086-44cc-a85c-6d22ca7ace35)
https://httpwg.org/specs/rfc9110.html#DELETE

2024-09-14 07:53 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        goal.setUsers(List.of(user));
Все добавляется самостоятельно, я проверил

2024-09-14 08:43 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +            existingGoal.setStatus(GoalStatus.COMPLETED);
Когда пользователь хочет обновить статус цели, то изменяется ее статус в БД

2024-09-14 09:26 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +                .build();
Мне они были необходимы только для этой проверки. Или лучше так сделать для улучшения читаемости?

2024-09-14 10:43 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +    private List<GoalFilter> goalFilters;
Чтобы положить это вовнутрь сервиса

2024-09-14 10:58 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/goal/GoalServiceTest.java
> +    private List<GoalFilter> goalFilters;
Чтобы внедрить список в goalService.
Тесты на фильтры в методе testFindUserGoalByFilter()

2024-09-15 10:53 UTC, 20cognosce approved these changes

2024-09-15 10:53 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
Чисто для разнообразия балуемся разными статусами, я понял

2024-09-15 10:53 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @ResponseStatus(HttpStatus.OK)
Зачем указывать дефолтный

2024-09-15 10:53 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @ResponseStatus(HttpStatus.NO_CONTENT)
А фронт потом всех их будет перебирать

2024-09-15 10:53 UTC, merged