Feature/mentorship~DankeVilletti~BJS2-27569
CorporationX/user_service pull request #1473
Opened 2024-09-11 08:19 UTC by DankeVilletti

2024-09-11 18:42 UTC, mysosnovskaya requested changes

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +    public ResponseEntity<List<UserDto>> getMentees(
ResponseEntity не нужно, просто `public List<UserDto>`, а в теле `return mentees;`

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +    @ResponseStatus
Тут в скобочках нужен хттп статус указать (201 - no content), как у тебя было с ResponseEntity

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/entity/Mentorship.java
> +public class Mentorship {
В прошлом ПРе писала, что класс не нужен, его можно User заменить

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +    UserDto toDTO(User user);
Здесь DTO -> Dto и в методе ниже тоже

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +@Setter
А сеттер точно нужен? Можно ли сделать поля финальными и проставлять значения через конструктор?

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +public class MentorshipService {
Не хватает логгирования

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +        List<User> mentees = mentorshipRepository.findMentorsByMenteeId(menteeId);
Название переменной неверное

2024-09-11 18:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +        List<User> mentees = mentorshipRepository.findMenteesByMentorId(mentorId);
Было бы хорошо вернуть ошибку, если пользователя с id = mentorId вообще нет у нас в базе. В других методах аналогично

2024-09-11 18:42 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/MentorshipServiceTest.java
> +        assertTrue(resultWithZeroID.isEmpty(), "Результат должен быть пустым, если menteeId равен 0");
Исключение должно быть по-хорошему)

2024-09-11 18:42 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/MentorshipServiceTest.java
> +
Не хватает тестов на удаление

2024-09-16 11:38 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +        List<User> mentees = mentorshipRepository.findMenteesByMentorId(mentorId);
Ну для этого же будет отправлен отдельный запрос
Оно того стоит?
у меня вернется пустой список если пользователя нет

2024-09-16 14:24 UTC, closed without merging

2024-09-16 17:48 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +        List<User> mentees = mentorshipRepository.findMenteesByMentorId(mentorId);
Нет, в данной ситуации это некорректное поведение. Пустой список означает, что такой пользователь есть, но у него просто нет mentees. А вот когда пользователь не найден, то должна быть именно 404