BJS2-27011 Деактивация пользователя
CorporationX/user_service pull request #1481
Opened 2024-09-11 14:35 UTC by cemeh666

2024-09-11 15:16 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/user")
Я бы сделал `/users`, во множественном числе, вроде так принято

2024-09-11 15:16 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/User.java
> +    }
Ох, не знаю, сомнительным решением кажется, может в в сервисе это делать?

2024-09-11 15:19 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +package school.faang.user_service.controller.user;
vvvv

2024-09-11 17:23 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/user")
+

2024-09-11 17:26 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping("/{userId}/deactivated")
deactivate

2024-09-11 17:29 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<Void> deactivatedUser(@PathVariable("userId") Long userId) {
("userId") - я у себя не писал
если имя параметра полностью совпадает с url-параемром, о можно не писать ("userId")

2024-09-11 17:31 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +@AllArgsConstructor
@RequiredArgsConstructor

2024-09-11 17:39 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        User user = userRepository.findById(userId).orElseThrow(UserNotFoundException::new);
Я обычно сразу же выношу в отдельный метод, даже если дублирующего кода нету.
Но ты пока не делай.

2024-09-11 17:40 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        if (!user.isActive()) {
Я обычно делаю isNotActive()
Но ты точно так не делай.

2024-09-12 08:46 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/user")
обычно `/users` ендпоинт используется для вывода пользователей
а `/user/{id}` уже какое-то действие с конкретным пользователем (в единтсвеном числе)

2024-09-12 09:46 UTC, cemeh666 commented on src/main/java/school/faang/user_service/entity/User.java
> +    }
сделал это в сервисе

2024-09-12 10:32 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/user")
Не знаю, есть ли стандарт какой-то.
Но на моей практике всегда во множественном писали. Даже '/users/{id}'

2024-09-12 10:34 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/user")
Спроси у Димы в чате. Либо договориться как-то, чтобы у все по образцу было.

2024-09-12 10:40 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            throw new UserDeactivatedException();
В идеале все экзепшены логировать. Чтобы потом можно было смотреть, почему не работает.
И передавать id юзера в в этот лог.

Я сделал, что логирую экзепшены не в сервисе, а в хэндлере.

2024-09-12 10:49 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                .filter(event -> event.getStatus().equals(EventStatus.PLANNED))
а IN_PROGRESS не надо канцелять?

2024-09-12 10:51 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            eventRepository.delete(event);
После delete он с концами удаляестя из базы?
Если да, то зачем ты канцеляешь и сораняешь?

2024-09-12 10:54 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        user.getGoals().clear();
А можешь проверить гипотезу, что если у сущности Goal
```
    @ManyToMany
    @JoinTable(
            name = "user_goal",
            joinColumns = @JoinColumn(name = "goal_id"),
            inverseJoinColumns = @JoinColumn(name = "user_id")
    )
    private List<User> users;
```
сделать 
goal.getUsers().remove(user);

то потом 
user.getGoals().clear();
делать не надо
ибернейт и так удалит все записи из таблицы `user_goal`

2024-09-12 10:56 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                goalRepository.delete(goal);
У Goal есть 
private Goal parent;

Можешь проверить удалится ли Goal, у которого есть наследник?

2024-09-12 10:58 UTC, amilosh commented on src/main/java/school/faang/user_service/exception/user/UserDeactivatedException.java
> +        super(MESSAGE, HttpStatus.CONFLICT);
HttpStatus.CONFLICT - красиво
надо будет у себя заиспользовать

2024-09-12 11:00 UTC, amilosh commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    public void deleteMentorFromMentees(long mentorId, List<User> mentees) {
Может Long, чтобы лишний раз анбоксинг не делать.
user.getId() - Long возвращает

2024-09-12 11:04 UTC, amilosh commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +            mentee.getMentors().removeIf(mentor -> mentor.getId() == mentorId);
mentor.getId() == mentorId

У меня помню баг был, что я из разны мест Integer id брал, и нужно было сравнить и что-то сделать.
И код не работал. Хотя значения одинаковые были.

Оказалось что Integer - это ссылочный тип, и он сравнивал объекты по ссылке, а не по значению.
Пришлось делать `user.getId().equals(theSameUser.getId())`

Надо будет на мите спросить.

2024-09-12 11:08 UTC, amilosh commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +                    .filter(goal -> goal.getMentor().getId() == mentorId)
goal.getMentor()
вроде как у цели могут быть юзера, но ментора может ещё не быть
но я не уверен, нужно в требованиях копаться

я к тому, что 
goal.getMentor()
на null проверить

2024-09-12 11:09 UTC, amilosh commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +                    .forEach(goal -> goal.setMentor(mentee));
Это в требованиях так?

2024-09-12 11:37 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/user")
Согласен, что какого-то стандарта нет, но я руководствовался практикой и логикой, что `/user/{id}` действие над конкретным пользователем

2024-09-12 11:39 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                .filter(event -> event.getStatus().equals(EventStatus.PLANNED))
>  Все события, запланированные пользователем должны быть остановлены и удалены.
по задаче **запланированные**

2024-09-12 11:42 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            eventRepository.delete(event);
Как по задаче

> Все события, запланированные пользователем должны быть остановлены и удалены.

есть предположение, что при переводе статуса, сработает нотификейшен пользователям которые подписались на событие, что оно отменено и произойдёт удаление, но это лишь догадки)

2024-09-12 11:45 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                goalRepository.delete(goal);
нет. удаление не пройдёт. щас буду исправлять

2024-09-12 11:51 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +                    .filter(goal -> goal.getMentor().getId() == mentorId)
тут как бы передаются **mentees** пользователя, и это предполагает, что в списке `getMentor()` точно будет минимум этот пользователь

2024-09-12 11:52 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +                    .forEach(goal -> goal.setMentor(mentee));
да

> теперь они выглядят так, как будто менти поставил их себе сам.

2024-09-12 12:13 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +                    .filter(goal -> goal.getMentor().getId() == mentorId)
и кстати, если каких-то связей нету в БД в сущности приходит пустой список, а не **null**, так что проблемы могут быть только в тестах, если метод не замокато, то вернётся **null**

2024-09-12 12:28 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +            mentee.getMentors().removeIf(mentor -> mentor.getId() == mentorId);
поменял на equals

2024-09-12 12:28 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +    public void deleteMentorFromMentees(long mentorId, List<User> mentees) {
поменял на Long

2024-09-12 12:28 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                goalRepository.delete(goal);
доработал

2024-09-12 17:14 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        user.getGoals().clear();
я в принципе так и делаю
![image](https://github.com/user-attachments/assets/1507bb56-d068-4184-9771-122a0f730e79)

2024-09-15 11:05 UTC, 20cognosce requested changes

2024-09-15 11:05 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping("/{userId}/deactivate")
Put

2024-09-15 11:05 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    @Transactional
@Transactional из пакета 
import org.springframework ?

2024-09-15 11:05 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +import jakarta.transaction.Transactional;
Спринговую используй

2024-09-15 11:05 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +import org.springframework.transaction.annotation.Transactional;
Здесь правильная

2024-09-15 11:05 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        for (Goal goal : user.getGoals()) {
forEach

2024-09-15 11:05 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        for (Event event : plannedEvents) {
forEach

2024-09-15 11:18 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    @Transactional
от сюда
`import org.springframework.transaction.annotation.Transactional;`

2024-09-15 11:27 UTC, 20cognosce approved these changes

2024-09-15 11:27 UTC, merged