Дописаны тесты, проверена логика работы через запросы Postman
CorporationX/user_service pull request #1484
Opened 2024-09-11 17:39 UTC by lexus-74

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +@RequestMapping("api/mentors")
На проекте мы пишем несколько микросервисов, а не REST API (одно приложение). Поэтому более уместно просто указать название коллекции, с которой работаем (mentorships или mentorship-requests).

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    }
Методы класса контроллера должны только принимать и обрабатывать запрос, а вся бизнес логика (валидация и работа с исключениями) должна быть в сервисе. Также обрати внимание на то, что ранее Дима писал в дискорде: сервисы должны принимать и возвращать только entity (не dto). Таким образом когда микросервисы будут общаться между собой не нужно будет постоянно переводить dto в entity и наоборот.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
Одной проверки на isBlank может быть недостаточно; тебе тут также может прийти null (если в MentorshipRequestDto отсутствует значение в поле description) - тогда ты тут словишь NullPointerException. Лучше всего будет это проверить аннотацией `@NotNull`, прочитай как это правильно сделать)

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
Хорошо, что проверяешь с помощью Objects.equal, но есть проблема: что если оба поля null? Потому Objects.equals(null, null) вернет true. Как я написал раньше, также проверяй на уровне dto что они оба не null.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                .orElseThrow(() -> new RuntimeException("User receiver not found"));
Ты перед этой логикой уже проверил, что юзеры разные и они есть в базе. Разве маппер MapStruct тебе не проставит обоих пользователей внутри mentorshipRequest? Мог бы сразу достать их из mentorshipRequest, только в маппере нужно поля указать (а ты их игноришь зачем то).

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        return mapper.toDto(requestRepository.save(mentorshipRequest));
Лучше не сохранять и маппить  на dto в одной строчке, от этого страдает читаемость. Плюс, может быть ты потом захочешь логировать то, что пришло из базы данных.

2024-09-11 21:49 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +    }
А что ты тут решил протестировать? Ты тестируешь класс MentorshipRequestService, а не его зависимости (зависимости ты просто мокаешь).

2024-09-11 21:49 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        Mockito.verify(repository, Mockito.times(1))
То же самое что и Assert - статический импорт.

2024-09-11 21:49 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        Assert.assertThrows(RuntimeException.class, () -> service.requestMentorship(dto));
Можно импортировать статические методы класса Assert - посмотри на начальных лекциях буткемпа как это делать (чтобы импортировать только статические методы, а не весь класс Assert).

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +    public List<RequestFilterDto> getRequests(RequestFilterDto dto) {
Ты не понял условие - тебе нужно вернуть из метода getRequests отфильтрованный список List<MentorshipRequest>, а не список фильтров List<RequestFilterDto>

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                .forEach(filter -> filter.apply(requests, dto));
В этом куске кода не происходит фильтрации запросов на менторство. Ты фильтруешь список requestFilters, и каждый из них применяешь к списку MentorshipRequests (при этом requests не меняется). Каждый раз тут возращаются все запросы на менторство, без фильтрации.

2024-09-11 21:49 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        Mockito.when(repository.findAll()).thenReturn(List.of(mentorshipRequest));
Тест надо переписать - ты не можешь фильтровать один элемент, это концептуально неверно  (фильтруют как правило списки более чем с одним элементом).

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    @PatchMapping(value = "/accept")
Тип маппинга ты выбрал на этот раз правильный (Patch - частичное обновление), но сам path (accept) и AcceptationDto неверные. AcceptationDto тут вообще не нужен - ты принимаешь запрос на менторство по его id (а не в теле запроса). 
Тогда полный маппинг будет следующий: PATCH /mentorships/{id}/accept. Почитай как писать path для эндпоинтов вот тут: 
https://tproger.ru/translations/luchshie-praktiki-razrabotki-rest-api-20-sovetov

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    @PostMapping(value = "/filters")
1) Если у твоей аннотации только один параметр, то value = можно не указывать (и так понятно, что это значения параметра value). 
2) В данном контексте path твоего маппинга вообще не нужно указывать - ты получаешь 
3) Тут должен быть `@GetMapping`, потому что ты ничего получаешь данные, а не создаешь их.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +
Именно в контроллер ты должен инжектить маппер - и в каждом методе контроллера передавать в сервис уже entity, а не dto.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +        return null;
Логику в сервис - в методе контроллера rejectRequest тоже самое.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    }
Те же проблемы, что и в методе acceptRequest.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        }
Проще проверить с `@NotNull` на уровне dto.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        return mapper.toRejectDto(requestRepository.save(request));
Не в одну строчку.

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        request.setRejectionReason("I don't like you!");
Ты не указал причину отклонения - проверь в задании, пункт №4 (поле reason внутри dto).

2024-09-11 21:49 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +
Тут ты забыл проверить, что ментора в список менторов отправителя (и не проверяешь условие на его присутствие в списке), пункт №4.

2024-09-12 09:17 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +        }
У тебя код сначала выбрасывает исключение в сервисе, а потом обрабатывает его уже в контроллере. Такой подход выглядит странно, так как при отправке запроса с невалидными данными (например, через Postman), сервер вместо ошибки отвечает, что всё в порядке. Хотя правильнее было бы вернуть Response с кодом 500, чтобы другие разработчики, которые будут пользоваться приложением, сразу понимали, что произошла ошибка.
Идеально, если в ответе будет указана информация о том, какое именно исключение было выброшено, а также его сообщение. Недавно нам скидывали статью на эту тему, где хорошо объясняется, как можно реализовать это с помощью Spring:
https://habr.com/ru/articles/528116/.

В проекте для логирования используем не вывод в консоль через `System.out.println(ex.getMessage())`, а специальный логгер. Можно упростить логирование с помощью аннотации Lombok `@Slf4j`:
https://projectlombok.org/features/log.

2024-09-12 09:17 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                .orElseThrow(() -> new RuntimeException("User requester not found"));
Хорошей практикой будет использование не `RuntimeException`, а исключения которое наследуется от него. В данном случае подходит `IllegalArgumentException`. Это помогает при отладке кода:
Тут есть список исключений, которые наследуются от RuntimeException:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/RuntimeException.html

Также ты можешь создать свое исключение, которое будет наследоваться от RuntimeException, но лучше использовать уже существующие

2024-09-12 09:17 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +    }
Метод `service.requestMentorship(dto))` может выбросить 7 разных RuntimeException
B данном тесте не понятно, что был выброшено исключение, которые связано с тем, что поле description null or empty. 
Мне кажется, что помимо `assertThrows`, необходимо еще реализовать проверку сообщения exception с помощью `assertEquals`, вот пример того как это сделано у меня:
![image](https://github.com/user-attachments/assets/2b4dd560-dcbc-4e8b-8ad3-77943cf42b6f)

А то получается, что если ты добавишь в dto валидное значение description, то данный метод все равно выбросит исключение и тест будет пройден, хотя так не должно быть

2024-09-15 11:22 UTC, 20cognosce requested changes

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +        return mapper.toDto(service.requestMentorship(mentorshipRequest));
service.requestMentorship в переменную

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    public List<MentorshipRequestDto> getRequests(@RequestBody RequestFilterDto filter) {
Get конечно самое правильное, но у него по спецификации Open API не должно быть тела
Раз в теле несем фильтр - то Post

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    @PatchMapping("/{requestId}/accept")
Put

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    public void acceptRequest(@PathVariable @Validated Long requestId) {
А что мы валидируем?

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    @PatchMapping("/{requestId}/reject")
Put

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/MentorshipRequestDto.java
> +@Data
equals hashcode нам нужен?

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/MentorshipRequestDto.java
> +    private LocalDateTime updatedAt;
?
На вход и на выход разные DTO

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +    public MentorshipRequest requestMentorship(MentorshipRequest request) {
@Transactional
org.springframework

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +            }
Переусложненный блок кода, декомпозировать

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +    public List<MentorshipRequest> getRequests(RequestFilterDto dto) {
@Transactional(readOnly = true)

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +    public void acceptRequest(Long requestId) {
Транзакция

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +    public void rejectRequest(Long requestId, String reason) {
Транзакция

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/filters/RequestFilterByReceiver.java
> +        return requests.filter(request -> request.getReceiver().getId().equals(filterDto.getReceiverId()));
Не писать в одну строчку длинную цепочку вызовов

2024-09-15 11:22 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/filters/RequestFilterByStatus.java
> +        return requests.filter(request -> request.getStatus().toString().equals(filterDto.getStatus()));
Декомпозиция

2024-09-15 11:22 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        Assert.assertEquals(requestsByFilter.get(0).getDescription(), "test description");
Этого мало проверить, проверяй все поля
assertThat()
.recursiveComparison()

2024-09-15 11:45 UTC, lexus-74 commented on src/main/java/school/faang/user_service/dto/MentorshipRequestDto.java
> +    private LocalDateTime updatedAt;
Не понял. Не нужен private LocalDateTime updatedAt поскольку я его не использую?

2024-09-15 15:48 UTC, 20cognosce approved these changes

2024-09-15 15:48 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Не сворачивать импорты

2024-09-15 15:48 UTC, merged