BJS2-27003 - Подписка на других пользователей
CorporationX/user_service pull request #1493
Opened 2024-09-12 15:19 UTC by evgenywork

2024-09-12 19:21 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +
.

2024-09-12 19:24 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@CustomExceptionHandler
Это чтобы, если у нас есть два controller advice, чтобы от одного контроллера прилелтало в один эдвайс, а для другого  - в другой.
Для нас будет достаточно одного controller advice, куда будут прилетать экзепшены со всех конроллеров.
Так что можно убрать.

Но я не знал, что так можно.

2024-09-12 19:32 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +                .body(new ResponseDto(SuccessMessages.SUBSCRIBE_SUCCESS));
Так в принципе можно.

Но вроде обычно просто либо ResponseEntity<Void> возвращают. Либо public void followUser.
То есть спринг сам всё вернет в нужном формате.

А само сообщение для клиента SuccessMessages.SUBSCRIBE_SUCCESS излишне - ему главное, что HttpStatus.CREATED вернется.

Если будешь убирать к void, можешь заиспользовать @ResponseStatus(HttpStatus.CREATED)

2024-09-12 19:35 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        return ResponseEntity.ok(new ResponseDto(SuccessMessages.UNSUBSCRIBE_SUCCESS));
Та же история. Можно написать void, а спринг по умолчанию ok вернет, если не было исключения.

2024-09-12 19:36 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @GetMapping("/{followeeId}/followers")
Тут мы договорились, если есть @RequestBody UserFilterDto filter  использовать Post

2024-09-12 19:37 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        List<User> users = subscriptionService.getFollowers(followeeId, filter);
List<User> followers

2024-09-12 19:40 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    public int getFollowersCount(@PathVariable long followeeId) {
Вот тут не знаю, можно ли так int возвращать.
Обычно - какой--то объект, который в json переводится.

Спроси у Димы в чате, если одобрит то ок.

2024-09-12 19:44 UTC, amilosh commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +
.

2024-09-12 19:45 UTC, amilosh commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +
.

2024-09-12 19:53 UTC, amilosh commented on src/main/java/school/faang/user_service/constant/ErrorMessages.java
> +public final class ErrorMessages {
Это утилитный класс. Он должен быть final, как ты указал. А ещё должен быть приватный консттруктро.
Более подробно можешь загуглить java utility class.

Можно использовать lombok.experimental.UtilityClass;
final в классе тогда можно убрать

2024-09-12 19:53 UTC, amilosh commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    private void checkNotToFollowUnfollowToSelf(long followerId, long followeeId) {
checkNotToFollowOrUnfollowToSelf

2024-09-12 19:54 UTC, amilosh commented on src/main/java/school/faang/user_service/constant/ErrorMessages.java
> +    public static final String CANNOT_SUBSCRIBE_TO_SELF = "You cannot subscribe / unsubscribe to yourself.";
CANNOT_SUBSCRIBE_OR_UNSUBSCRIBE_TO_SELF

2024-09-12 19:54 UTC, amilosh commented on src/main/java/school/faang/user_service/constant/ErrorMessages.java
> +    public static final String CANNOT_UNSUBSCRIBE_TO_SELF = "You cannot unsubscribe to yourself.";
эту получается можно удалить

2024-09-12 19:56 UTC, amilosh commented on src/main/java/school/faang/user_service/constant/ErrorMessages.java
> +    public static final String USER_NOT_SUBSCRIBED = "You don't subscribed to the following user";
You are not subscribed to the following user

2024-09-12 19:57 UTC, amilosh commented on src/main/java/school/faang/user_service/constant/ErrorMessages.java
> +    public static final String ALREADY_SUBSCRIBE = "You have already subscribe to the following user";
You have already subscribed to the following user

2024-09-12 19:59 UTC, amilosh commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    @Transactional
В метода, где есть только get запросы - @Transactional(readOnly = true)

2024-09-12 20:01 UTC, amilosh commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        Stream<User> users = subscriptionRepository.findByFolloweeId(followeeId);
Не знаю почему, Дима скала мне и ещё кому-то сделать запрос в БД, который возвращает List. А потом его сделать .stream() в методе.

Stream<User> findByFolloweeId(long followeeId); -> List<User> findByFolloweeId(long followeeId);

2024-09-12 20:04 UTC, amilosh commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        return users.filter(userFilterPredicate);
Если работает - то огонь.
Значит это третий способ.

Можешь ещё глянуть как у Ильи и у меня мы это реализовали.

2024-09-12 20:06 UTC, amilosh commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +            throw new DataValidationException(ErrorMessages.CANNOT_SUBSCRIBE_TO_SELF);
Я обычно енамы в статический импорт переношу.
alt + enter -> add static import

2024-09-12 20:09 UTC, amilosh commented on src/main/java/school/faang/user_service/advice/CustomAdvice.java
> +public class CustomAdvice {
Про CustomExceptionHandler там ниже в SubscriptionController я написал.

Переименуй этот класс в что0то типа AppExceptionHandler

2024-09-12 20:10 UTC, amilosh commented on src/main/java/school/faang/user_service/advice/CustomAdvice.java
> +        return new ResponseEntity<>(response, HttpStatus.BAD_REQUEST);
log.error(e.getMessage());

2024-09-12 20:18 UTC, amilosh commented on src/main/java/school/faang/user_service/dto/UserFilterDto.java
> +    private int pageSize;
Спроси у Димы в чате, будет ли ok сделать
UserFilterDto extends PageableDto

    public static final int DEFAULT_PAGE_SIZE = 10;

    protected int page;
    protected int pageSize;

2024-09-12 20:22 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/filter/UserAboutFilter.java
> +        return user -> user.getAboutMe().contains(filters.getAboutPattern());
user.getAboutMe() - если null

2024-09-12 20:25 UTC, amilosh commented on src/main/java/school/faang/user_service/service/user/filter/UserCountryFilter.java
> +        return user -> user.getCountry().getTitle().contains(filters.getCountryPattern());
тут даже двойная проверка на налл

2024-09-12 20:30 UTC, amilosh commented on src/test/java/school/faang/user_service/service/subscription/SubscriptionServiceTest.java
> +
.

2024-09-12 20:33 UTC, amilosh commented on src/test/java/school/faang/user_service/service/subscription/SubscriptionServiceTest.java
> +
..

2024-09-12 20:33 UTC, amilosh commented on src/test/java/school/faang/user_service/service/user/filter/UserAboutFilterTest.java
> +
.

2024-09-12 20:34 UTC, amilosh commented on src/test/java/school/faang/user_service/service/user/filter/UserContactFilterTest.java
> +
.

2024-09-13 16:17 UTC, evgenywork commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@CustomExceptionHandler
Да, все верно . Сделал так пока что , когда все сольем и договоримся на счет этого тогда наверное уберу

2024-09-13 16:28 UTC, evgenywork commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +                .body(new ResponseDto(SuccessMessages.SUBSCRIBE_SUCCESS));
Я пока что так сделал. в принципе думал , что фронт может сообщения просто пользователю передавать .

надо просто сделать созвон и договориться , как делаем

@ResponseStatus(HttpStatus.CREATED)  - запомнил

2024-09-13 16:29 UTC, evgenywork commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @GetMapping("/{followeeId}/followers")
Понял! исправлю

2024-09-13 16:33 UTC, evgenywork commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        List<User> users = subscriptionService.getFollowers(followeeId, filter);
Не очень понял, что ты здесь  имел ввиду

2024-09-13 16:35 UTC, evgenywork commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    public int getFollowersCount(@PathVariable long followeeId) {
Может ты и прав , как то не подумал. переделаю под DTO

2024-09-13 17:18 UTC, evgenywork commented on src/main/java/school/faang/user_service/constant/ErrorMessages.java
> +public final class ErrorMessages {
Спасибо, не знал, что так надо.

2024-09-13 17:35 UTC, evgenywork commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        return users.filter(userFilterPredicate);
да, работает , пришлось поискать даже линк сохранил
https://www.baeldung.com/java-predicate-chain (6. Combining a Collection of Predicates)

2024-09-13 18:19 UTC, evgenywork commented on src/main/java/school/faang/user_service/service/user/filter/UserAboutFilter.java
> +        return user -> user.getAboutMe().contains(filters.getAboutPattern());
он просто не применится. isApplicable сначала фильтрует все что не null , а потом уже применяет предикаты

2024-09-13 18:38 UTC, evgenywork commented on src/main/java/school/faang/user_service/service/user/filter/UserAboutFilter.java
> +        return user -> user.getAboutMe().contains(filters.getAboutPattern());
Спасибо! не подумал

2024-09-15 08:26 UTC, sultan-inked commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +                .body(new ResponseDto(SuccessMessages.SUBSCRIBE_SUCCESS));
Согласен с Александром, так банально меньше кода, что всегда плюс, имхо

2024-09-15 08:26 UTC, sultan-inked commented on src/main/java/school/faang/user_service/dto/ResponseDto.java
Я бы во всех дто использовал рекорды
*"Если DTO предназначен только для передачи данных и не требует расширенной логики или изменяемости, record — идеальный выбор благодаря своей краткости и безопасности."*

2024-09-15 08:26 UTC, sultan-inked commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        Stream<User> users = subscriptionRepository.findByFolloweeId(followeeId);
Незнаю, чем аргументировано, что лучше лист а не стрим из репозитория, возможно так принято, но я бы тоже не стал возвращать стрим из репозитория, из бд в любом случае сначала возаращается лист, наврено так надо что бы логика была в сервисе, хз

2024-09-15 08:26 UTC, sultan-inked commented on src/test/java/school/faang/user_service/service/subscription/SubscriptionServiceTest.java
> +        user1.setEmail(email);
Для тестовых классов можно использовать утилитный класс, с статическими методами, укоторые возвращают, наример того же пользователя создавая его через билдер, а список пользоватлей можно получить при помощи `LongStream` и билдера:
```java
public static User getUser(long id, String username, String email) {
    return User
            .builder()
            .id(id)
            .username(username)
            .email(email)
            .build();
}

public static List<User> getUsersWithIdUsernameEmail(int number) {
    return LongStream
            .rangeClosed(1, number)
            .mapToObj(i -> getUser(i, "Username " + i, i + "test@mail.com"))
            .toList();
}
```
Таким образом в дальнейшем переиспользовать в других тестах

2024-09-15 08:26 UTC, sultan-inked commented on src/test/java/school/faang/user_service/service/subscription/SubscriptionServiceTest.java
> +        Stream<User> userStream = Stream.of(user1, user2, user3, user4, user5, user6);
Утилитный класс, `userStream = Stream.of(getUsers(NUMBER_OF_USERS));`

2024-09-16 17:37 UTC, 20cognosce requested changes

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/constant/ErrorMessages.java
> +public final class ErrorMessages {
@UtilityClass

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@AppExceptionHandler
Зачем ты свою аннотацию используешь

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +                .body(new ResponseDto(SuccessMessages.SUBSCRIBE_SUCCESS));
Смысл отдавать сообщение? Отдавай созданный объект в теле

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @DeleteMapping("/{followerId}/unfollow/{followeeId}")
Не Delete точно
Put, и follow - Put

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        List<User> users = subscriptionService.getFollowers(followeeId, filter);
не users, а followers он имел в виду

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/ResponseDto.java
> +@Data
Посмотри содержимое этой аннотации, всё ли оно тебе надо

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/user/UserDto.java
> +}
Валидации?

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        Stream<User> users = subscriptionRepository.findByFolloweeId(followeeId);
Потому что стрим - не структура данных
А последовательность манипуляций над коллекцией
Как база может вернуть последовательность операций над данными, а не сами данные?

А если тебе не нужны никакие фильтры и прочее, ты просто toList() будешь вызывать? Зачем тогда двойное преобразование

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    @Transactional
readOnly добавь

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        Stream<User> paginatedUsers = applyPagination(filteredUsers, filters);
Не принимайте и не отдавайте стримы, это не коллекция, стрим - это набор функций

2024-09-16 17:37 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        return users
сортировка перед skip?

2024-09-21 18:32 UTC, 20cognosce commented
161 tests completed, 6 failed
https://github.com/CorporationX/user_service/actions/runs/10973768003/job/30471506045

2024-09-24 15:54 UTC, 20cognosce approved these changes

2024-09-24 15:54 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@AppExceptionHandler
Снова повторю, что мне неясен смысл применения своей аннотации

2024-09-24 15:54 UTC, merged