Приоритет поиска для премиум-пользователей BJS2-26827
CorporationX/user_service pull request #1494
Opened 2024-09-12 15:34 UTC by Peregruzochka

2024-09-12 15:38 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +        skillDtoOne.setTitle(skillOne.getTitle());
Мем в том, что на Dto нельзя вешать аннотацию lombok `@Builder` потому что она делает конструктор данного приватным, а без конструктора Jackson не может произвести преобразование из json в dto

2024-09-12 19:10 UTC, mrkorolev reviewed
Никита: Крутяк!)
Денис: Супер-пупер!)

2024-09-12 19:10 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/users")
Можно базовый маппинг указать так: `@RestController("/users")`.
Сам только что узнал)))

2024-09-12 19:10 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private boolean isUserMatchesFilters(User user, List<UserFilter> filters, UserFilterDto filterDto) {
Начинается духота: нейминг - userMatchesFilters (пользователь "подходит" по фильтрам).

2024-09-12 19:10 UTC, mrkorolev commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +        skillDtoOne.setTitle(skillOne.getTitle());
Я не понял. Если бы `@Builder` создавал приватный конструктор, ты бы не смог им пользоваться по определению. Дима, памаги)

2024-09-13 09:00 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@RequestMapping("/users")
Я правильно тебя понял, что мы можем не использовать аннотацию @RequestMapping?
Прост если так, то при отправке запроса через postman я получаю 404

2024-09-13 09:11 UTC, Peregruzochka commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +        skillDtoOne.setTitle(skillOne.getTitle());
Поч? ты можешь им пользоваться, но только внутри класса, тип чтоб создать объект тебе нужен отдельный статический метод)

2024-09-16 17:51 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +        skillDtoOne.setTitle(skillOne.getTitle());
Доп аннотаций на конструкторы навесьте и будет вам счастье
Он не делает приватный конструктор, ему нужен конструктор со всеми параметрами

2024-09-16 18:00 UTC, 20cognosce requested changes

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/premium")
Post, потому что тело запроса есть

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @ResponseStatus(HttpStatus.OK)
Это итак дефолтный статус

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/dto/user/UserFilterDto.java
> +    private List<SkillDto> skills;
как твой фильтр может принимать список дтошек?
Это сколько всего должен фронт знать? почему не просто айди

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    @Transactional
readOnly

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/filter/UserFilterByCities.java
> +    public boolean test(User user, UserFilterDto filterDto) {
Никакое DTO фильтр не должен принимать

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/filter/UserFilterByCities.java
> +public class UserFilterByCities implements UserFilter{
скукожился класс чет

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    }
Не оч нравятся мне эти 3 блока кода
из DTO доставай тут конкретные параметры и дальше с ними работай

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/filter/UserFilterBySkills.java
> +public class UserFilterBySkills implements UserFilter{
пробел

2024-09-16 18:00 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/filter/UserFilterBySkills.java
> +        Set<Long> filterSkillIds = filterDto.getSkills().stream()
Нормально ты придумал, пусть фронт всю простыню выдаст
а ты только айдишник будешь из нее брать

2024-09-16 18:00 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +    private List<UserFilter> userFilter = new ArrayList<>();
Почему ты фильтр замокал? Где тесты на фильтры

2024-09-16 18:00 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +        ));
А, мы мокаем чтобы создать потом руками, ясно

2024-09-16 18:00 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +        assertEquals(expectedUserName, premiumUser.get(0).getUsername());
Одного имени мало для проверки
assertThat()
.recursiveComparison()

2024-09-16 18:00 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +        int expectedPremiumUsersSize = 1;
Не надо это так писать
userOne.getUserName()

2024-09-16 18:04 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    @Transactional
@20cognosce А вообще есть смысл кидать в этом месте Transactional? Никакой записи же нет.

2024-09-19 18:27 UTC, 20cognosce approved these changes

2024-09-19 18:27 UTC, merged