Feature: Getting Lists of Goals with filters
CorporationX/user_service pull request #15
Opened 2023-07-11 20:19 UTC by Ne0nYa

Tried to make task BC-3791 "Get a list of goals with filters"

2023-07-11 21:30 UTC, czar777 reviewed
комменты

2023-07-12 13:30 UTC, czar777 approved these changes
можешь исправить и отправить Инне

2023-07-12 15:23 UTC, InnMish requested changes

2023-07-19 11:23 UTC, InnMish requested changes

2023-07-22 10:36 UTC, merged