BJS2-26068 Постановка целей
CorporationX/user_service pull request #1500
Opened 2024-09-12 18:30 UTC by badasscoding

2024-09-12 20:23 UTC, GusevVrn reviewed
- Название ветки проверь.
- Отступы везде добавь после объявления класса
- С эндпоинтами контроллера пошамань, ты чет перемудрил.
- Все числа в тестах вынести в переменные 
- По названиям методов вроде решили что идем к единой стилистике whenЧтоThenОжидаемыйРезультат
- Можешь попробовать посмотреть в сторону @Nested

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    private final GoalService goalService;
отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @PostMapping("/{userID}")
У тебя запрос получается /v1/goals/55 - вроде как цель 55, но ты сюда вкладываешь юзера. 
Проще /create, а userId через RequestParam

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @PutMapping("/{goalId}")
А тут тот же самый /v1/goals/55 но 55 уже цель. 
И разница в методах только в типе запроса, надо api в таком случае делать очень аккуратно и надеяться на то что человек который с этим будет работать, будет очень дотошный и не перепутает.

Put целенаправленно использовал? Может лучше Patch рассмотреть?

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +                              @RequestBody @Valid GoalDto goalDto) {
а к чему тут valid, если в Dto нет ни одной аннотации

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @GetMapping("/filter/{userId}")
ты через postman проверял? этот и предыдущий метод

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +                                             @RequestBody GoalFilterDto filter) {
В некой общей практике body не передается с GetMapping

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/filter/goal/GoalFilter.java
> +    Stream<Goal> apply(Stream<Goal> goals, GoalFilterDto filter);
отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/filter/goal/GoalStatusFilter.java
> +public class GoalStatusFilter implements GoalFilter {
все фильтры не public

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/filter/goal/GoalTitleFilter.java
> +public class GoalTitleFilter implements GoalFilter {
тоже не public

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +    @Mapping(source = "parent.id", target = "parentId")
отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +
лишний отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private final GoalRepository goalRepository;
а тут нужен отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        skillService.create(goalMapper.toGoal(goalDto).getSkillsToAchieve(), userId);
тут и маппер и сразу get, мб лучше разбить для читаемости?

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/goal/SkillService.java
> +    private final SkillRepository skillRepository;
отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/main/java/school/faang/user_service/validator/GoalServiceValidator.java
> +    private static final int MAX_USER_GOALS_LIMIT = 3;
отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +    private static final String TITLE = "Test Goal";
отступ

2024-09-12 20:23 UTC, GusevVrn commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        DataValidationException exception = assertThrows(DataValidationException.class, () -> goalController.createGoal(userId, invalidGoalDto));
залез за 80 символов

2024-09-12 20:23 UTC, GusevVrn commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        verify(goalService, times(1)).createGoal(userId, goalDto);
решили что times(1) не указываем

2024-09-12 20:23 UTC, GusevVrn commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        NotFoundException exception = assertThrows(NotFoundException.class, () -> goalController.updateGoal(goalId, goalDto));
и тут

2024-09-13 19:05 UTC, badasscoding commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        verify(goalService, times(1)).createGoal(userId, goalDto);
имеешь ввиду не пишем такие тесты?

2024-09-13 19:16 UTC, badasscoding commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        verify(goalService, times(1)).createGoal(userId, goalDto);
> решили что times(1) не указываем

имеешь ввиду не пишем такие тесты?

2024-09-13 19:16 UTC, badasscoding commented on src/main/java/school/faang/user_service/filter/goal/GoalStatusFilter.java
> +public class GoalStatusFilter implements GoalFilter {
> все фильтры не public

а тесты на них тогда как?

2024-09-13 19:22 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @PostMapping("/{userID}")
согласен что как-то не очень

/create не по restful 

сделаю так:

POST /users/{userId}/goals
GET /users/{userId}/goals

PUT /goals/{goalId}
DELETE /goals/{goalId}
GET /goals/{goalId}/subtasks

но первые два вынести бы из GoalController в UserController хочется тогда

2024-09-13 19:27 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @PutMapping("/{goalId}")
Хороший вопрос

PUT специально, так как нельзя обновить поля по отдельности
PATCH был бы если отдельные поля менялись

Но по заданию непонятно как надо, обсужу с Сабиной

2024-09-13 19:29 UTC, badasscoding commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        NotFoundException exception = assertThrows(NotFoundException.class, () -> goalController.updateGoal(goalId, goalDto));
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        DataValidationException exception = assertThrows(DataValidationException.class, () -> goalController.createGoal(userId, invalidGoalDto));
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/validator/GoalServiceValidator.java
> +    private static final int MAX_USER_GOALS_LIMIT = 3;
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/goal/SkillService.java
> +    private final SkillRepository skillRepository;
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        skillService.create(goalMapper.toGoal(goalDto).getSkillsToAchieve(), userId);
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private final GoalRepository goalRepository;
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/mapper/GoalMapper.java
> +    @Mapping(source = "parent.id", target = "parentId")
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/filter/goal/GoalFilter.java
> +    Stream<Goal> apply(Stream<Goal> goals, GoalFilterDto filter);
поправил

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +                              @RequestBody @Valid GoalDto goalDto) {
убрал

2024-09-13 19:29 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    private final GoalService goalService;
поправил

2024-09-13 19:33 UTC, badasscoding commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +    private static final String TITLE = "Test Goal";
поправил

2024-09-13 19:33 UTC, badasscoding commented on src/main/java/school/faang/user_service/filter/goal/GoalTitleFilter.java
> +public class GoalTitleFilter implements GoalFilter {
> тоже не public

а тесты на них тогда как?

2024-09-13 19:39 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +                                             @RequestBody GoalFilterDto filter) {
согласен

но по заданию звучит так, как будто надо в body

2024-09-15 03:22 UTC, Sabina-Vishnya requested changes, later dismissed
в целом код выглядит неплохо, но ты его не проверил, это почему так? есть опыт/нет опыта - код должен быть работоспособным, ты визуально можешь не всегда увидеть проблем и также на ревью коллеги твои что-то могут пропустить и в итоге не заметить критических ошибок
проверяем всегда
думаю увидишь о чем речь, а если потестишь через постман еще обнаружишь что-то 
возьми за привычку свой код тестировать, когда тем более возможность такая есть

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/filter/goal/GoalStatusFilter.java
> +public class GoalStatusFilter implements GoalFilter {
также как и на другие не публичные классы) на каждый фильтр свой тест, ты так и сделал, это видимо не актуальное сообщение) не забывай резолвить то, что поправил

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/GoalControllerTest.java
> +        @DisplayName("whenValidInputThenCreateGoalSuccessfully")
тут нужно описать уже нормально, что быть должно, а не просто копировать название метода

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +}
а почему ты гет с телом делаешь?
да технически можно, но не лучшая практика ведь, нарушает семантику в итоге. Можно поступить вот как:
1 - оставляй гет, но объект заполняй в контроллере через сеттеры, а поля объекта выноси в квери, но тогда проверь ограничения по длине для запроса (кол-во полей, длина полей и тд). У томката дефолтно 8кб кажись, у браузеров иначе - можно переопределить или оставить, но учесть совместимость. Поресерч этот вопрос и проверь. А опционально, после того как изучишь/проверишь, можно прикрутить фильтр проверяющий каждый запрос на корректность длины. Это на немного подзаморочиться, но необязательно
2 - меняешь на пост, но это слишком просто, поэтому советую немного запариться для начала с 1-м вариантом

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +@RequestMapping("/v1")
если эндпоинты относятся к управлению целями, было бы хорошо цели добавить в общий путь
так будет более консистентнее
а если тут присутствуют еще и юзер, и он является основным ресурсом, а цель лишь подресурс, то можно унести(создать, если нет) в контроллер для юзера
в зависимости от контекста короче, если цели тут главные у тебя по тз, а остальное связанные сущности, можно цели задать тут

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/GoalServiceTest.java
> +            verify(goalRepository, times(1)).create(goalDto.getTitle(), goalDto.getDescription(), goalDto.getParentId());
дефолтно и так 1, поэтому не нужно писать

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/GoalServiceTest.java
> +            verify(goalRepository, times(0)).save(any(Goal.class));
без times(0)
есть методы для проверок, когда вызова не должно быть, например verify с never, verifyNoInteractions

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/validator/GoalServiceValidator.java
> +    public void validateSkillsExistByTitle(final List<Skill> skills) {
скиллы в свою валидацию выноси

2024-09-15 03:22 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        goalRepository.create(goalDto.getTitle(), goalDto.getDescription(), goalDto.getParentId());
прикольно, а если у тебя что-то из этих полей налл?
у тебя кратность полей необязательная

2024-09-15 03:26 UTC, Sabina-Vishnya commented
и почему тут цели, если таска привязана к подписке на других пользователей?

2024-09-15 03:32 UTC, Sabina-Vishnya commented
@GusevVrn @badasscoding у вас всё склеилось, разберитесь с пр-ом
1 задача = 1 пр и коммиты к этому пр-у
не смешивайте

2024-09-15 10:03 UTC, badasscoding commented
> @GusevVrn @badasscoding у вас всё склеилось, разберитесь с пр-ом 1 задача = 1 пр и коммиты к этому пр-у не смешивайте

это я промахнулся как-то

предлагаю сейчас уже так оставить и не пересоздавать PR
название ветки я поменял
но в PR он не обновится

2024-09-15 11:32 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +@RequestMapping("/v1")
сделаю /v1/goals

POST /v1/goals/users/:id
GET /v1/goals/users/:id

PUT /v1/goals/:id
DELETE /v1/goals/:id
GET /v1/goals/:id/subtasks

пока не понимаю надо ли выносить юзер отдельно, поэтому оставлю так, если что потом поправлю

2024-09-15 13:40 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        goalRepository.create(goalDto.getTitle(), goalDto.getDescription(), goalDto.getParentId());
через @Valid сделал и @NonNull

2024-09-17 17:00 UTC, merged