feature-BJS2-27373
CorporationX/user_service pull request #1505
Opened 2024-09-13 07:25 UTC by aassylkhan

2024-09-13 18:57 UTC, mysosnovskaya requested changes
Некоторые комментарии переехали с прошлого ПР, в целом осталось совсем чуть-чуть и будем мержить)

2024-09-13 18:57 UTC, mysosnovskaya commented on build.gradle.kts
> -tasks.withType<Test> {
Куда эти строчки убежали и почему?) Нужно вернуть на место. Эти изменения к твоему ПР отношения не имеют

2024-09-13 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +                receiverId, pageable);
Я бы не делала здесь перенос на новую строчку. Без него тоже всё отлично читается) В остальных методах тоже

2024-09-13 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/DataValidationException.java
> +
Зачем?)

2024-09-13 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/recommendation/SkillOfferRepository.java
> +    boolean existsBySkillIdAndRecommendationId(long id, long id1);
Нужно переименовать параметры

2024-09-13 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +public class RecommendationServiceImpl implements RecommendationService {
Нужны логи

2024-09-13 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +                .collect(Collectors.toList());
Можно просто `.toList();`

2024-09-13 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +            skillOfferRepository.save(skillOffer);
Лучше через findAllById и saveAll сделать - так запросов к базе данных будет сильно меньше, соответственно нагрузка на неё снизится и бонусом ещё и всё быстрее будет работать)

2024-09-13 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +    // TODO в Util перенести? видел что в других классах тоже есть
1. Такие валидации можно проводить с помощью аннотации Positive в dto
2. А в твоей ситуации null вообще не может быть, т.к. во всех методах сервиса у тебя примитивный тип long. В RecommendationDto тоже можно long сделать
3. Такая проверка в целом не особо нужна. Ты когда будешь делать findById, тогда и узнаешь, корректный id тебе передали или нет. Нет разницы, искать по id = -100 или id = 1_000_000 - по обоим из них объект в базе не найдется и нужно будет вернуть NOT_FOUND. Так что на мой взгляд этот метод вообще можно удалить)

2024-09-13 18:57 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationServiceImplTest.java
> +}
Не хватает тестов:
update с ошибкой
getAllGivenRecommendations c непустым ответом
getAllUserRecommendations c непустым ответом

2024-09-16 09:23 UTC, mysosnovskaya requested changes

2024-09-16 09:23 UTC, mysosnovskaya commented on build.gradle.kts
Откати изменения в этом файле, они к твоему ПР не относятся

2024-09-16 09:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +                authorId, pageable);
В этом и следующем методе новые строчки для параметров также не нужны

2024-09-16 09:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +public class RecommendationServiceImpl implements RecommendationService {
Логи по-прежнему нужны

2024-09-16 09:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +                .collect(toList());
Я имела в виду без .collect, в новой джаве такое работает: `stream().map(...).toList()`

2024-09-16 09:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +    private void handleSkillOffers(Recommendation recommendation, List<SkillOfferDto> skillOffers) {
Круто получилось с findAllById и saveAll

2024-09-16 09:23 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationServiceImplTest.java
> +        assertFalse(result.isEmpty());
Эту проверку можно не делать, т.к. есть следующая (на размер списка)

2024-09-16 12:24 UTC, aassylkhan commented on build.gradle.kts
я скопировал весь файл у других ребят из команды. Ничего не менял. При merge решу конфликты

2024-09-18 20:06 UTC, mysosnovskaya requested changes

2024-09-18 20:06 UTC, mysosnovskaya commented on build.gradle.kts
Нет, конфликты здесь не при чем. В ПРе должны быть изменения только по твоей задаче. Ничего лишнего быть не должно. При копировании IDEA решила отформатировать стиль, из-за этого вылезли изменения. Их нужно откатить

2024-09-18 20:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +        log.debug("Рекомендация с id {} успешно сохранена", recommendation.getId());
Уровень info здесь лучше подойдет

2024-09-18 20:06 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +        log.debug("Найдено {} рекомендаций для пользователя с id {}", recommendations.size(), receiverId);
Вот для get запросов debug лучше подходит, т.к. get запросы происходят очень часто. А для модифицирующих методов (create/update/delete) можно всё в инфо писать

2024-09-19 18:27 UTC, mysosnovskaya requested changes

2024-09-19 18:27 UTC, mysosnovskaya commented on build.gradle.kts
Изменения в файле нужно откатить. После этого буду готова мержить)

2024-09-22 15:55 UTC, mysosnovskaya approved these changes

2024-09-22 15:55 UTC, merged