Участвовать в событии : bjs2 26817
CorporationX/user_service pull request #1516
Opened 2024-09-14 18:21 UTC by GaribAghayev

2024-09-15 09:51 UTC, Alginin reviewed
Тесты обязательно должны быть написанный.

2024-09-15 10:32 UTC, Alginin commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @PostMapping("/{eventId}/unregister")
По смыслу метода я думаю @PutMapping или @DeleteMapping больше подходит?

2024-09-15 11:39 UTC, Peregruzochka reviewed
В целом все хорошо) ожидаем тесты)

2024-09-15 11:39 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +            throw new RuntimeException("Event does not exist");
Хорошей практикой будет использование не RuntimeException, а исключения которое наследуется от него. В данном случае подходит IllegalArgumentException. Это помогает при отладке кода:
Тут есть список исключений, которые наследуются от RuntimeException:
https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/RuntimeException.html

Также ты можешь создать свое исключение, которое будет наследоваться от RuntimeException, но лучше использовать уже существующие

2024-09-15 11:39 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        User user = userRepository.findById(userId).orElseThrow(() -> new RuntimeException("User does not exist"));
Дублирование кода
Все проверки лучше вынести в отдельные методы

2024-09-18 18:57 UTC, 20cognosce requested changes

2024-09-18 18:57 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @PostMapping("/{eventId}/unregister")
Put

2024-09-18 18:57 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @PostMapping("/{eventId}/register")
Put

2024-09-18 18:57 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public List<User> getParticipant(Long eventId) {
@Transactional(readOnly=true)

2024-09-18 18:57 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public long getParticipantsCount(Long eventId) {
@transactional(readOnly=true)

2024-09-18 18:57 UTC, 20cognosce commented
This branch has conflicts that must be resolved
Use the [web editor](https://github.com/CorporationX/user_service/pull/1516/conflicts) or the  to resolve conflicts.
Conflicting files
src/main/java/school/faang/user_service/dto/UserDto.java

All checks have failed
1 failing check

2024-09-21 18:17 UTC, 20cognosce approved these changes

2024-09-21 18:17 UTC, merged