Добавление функциональности управления целями с CRUD операциями и фил…
CorporationX/user_service pull request #1517
Opened 2024-09-14 20:23 UTC by Suragany98

…ьтрацией

- Реализован `GoalController` с эндпоинтами для создания, обновления и удаления целей.
- Добавлены методы для получения подзадач цели и списка целей пользователя с опциональными фильтрами.
- Разработан `GoalService`, содержащий бизнес-логику для операций с целями.
- Созданы DTO: `GoalDto` и `GoalFilterDto`.
- Обеспечена валидация данных цели, включая проверку названия и существования навыков.
- Обработка обновлений статуса цели, особенно при пометке целей как завершенных.

2024-09-16 16:49 UTC, RuslanIovlev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (activeGoals >= 3) {
имеет ли смысл максимальное количество целей в константу вынести?

2024-09-16 16:53 UTC, RuslanIovlev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (activeGoals >= 3) {
судя по условию, нужно поставить только >

2024-09-16 17:06 UTC, RuslanIovlev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
А почему ты не используешь этот метод Goal create(String title, String description, long parent);

2024-09-16 17:15 UTC, RuslanIovlev commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    }
Не увидел удаления списка старых навыков, перед обновлением.

2024-09-16 17:26 UTC, RuslanIovlev approved these changes

2024-09-18 15:07 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("Цель успешно создана");
я бы вернул goal 
чтобы была возможность сразу получить созданный объект

2024-09-18 15:12 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Я так понял что можно не возвращать везде responseEn...
а можно сразу вернуть требуемый объект
а сверху повесить аннотацию 
@ResponseStatus(HttpStatus.#свой статус)
если удаление то no-content вроде

2024-09-18 15:15 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public ResponseEntity<List<GoalDto>> getGoalsByUser(
getGoalsByUser(Long userId, GoalFilterDto filter)

2024-09-18 15:17 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +}
https://github.com/CorporationX/project_service/pull/616#discussion_r1761624255

2024-09-18 15:21 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (skillIds != null && !skillIds.isEmpty()) {
чтобы не делать двойное вложение if 
после первого выбрось исключение

2024-09-18 15:22 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +                throw new IllegalArgumentException("Некоторые навыки не существуют");
двойной if 
нужно исключение после первого

2024-09-18 15:25 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +            }
стримом для каждого user установи что нужно а потом выполни сохранение все сразу saveAll

2024-09-18 15:25 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (activeGoals >= 3) {
думаю нужна константа

2024-09-18 15:25 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (effectiveFilter.getTitle() != null) {
это лучше в отдельные классы-фильтры вынести как в видео

2024-09-18 15:27 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        goal.getUsers().clear();
а эта строка зачем?
я не проверял
 но там же вроде не каскадное удаление
 пользователи не должны исчезнуть

2024-09-18 15:30 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        Stream<Goal> subTasksStream = goalRepository.findByParent(goalId);
titlefilter не факт что это строка
впринципе фильтры это определенные требования о которых должны как-то узнать и понимать что для них делать
поэтому надо создать классы 
предварительно использовав либо абстракцию, либо интерфейс

2024-09-18 15:32 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +
елси filter не придет, то effectiveFilter всегда будет с полями null 
это порождает много лишних проверок снизу

2024-09-18 15:33 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +
либо вынести отдельный метод который обработает все связанное с фильтрами
либо один раз сказать что фильтр пуст и выполнить все действия без него

2024-09-18 15:36 UTC, DankeVilletti reviewed
👆

2024-09-19 20:25 UTC, Suragany98 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("Цель успешно создана");
Спасибо за ваше предложение. Согласно требованиям задания, метод createGoal должен обрабатывать запрос, сохранять новую сущность в базе данных и проверять наличие названия у цели. В задании не указано, что мы должны возвращать созданный объект цели в ответе. Поэтому я реализовал метод таким образом, чтобы он возвращал сообщение об успешном создании с кодом статуса 201 Created.

2024-09-19 20:28 UTC, Suragany98 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        if (activeGoals >= 3) {
Согласно заданию, пользователь может иметь только 3 активные цели. Это означает, что если у пользователя уже 3 активные цели, он не может создать новую. Поэтому условие >= корректно отражает это требование. Если я поставлю только >, то пользователь сможет иметь 3 активные цели и создать четвертую, что противоречит заданию.

2024-09-21 17:13 UTC, mysosnovskaya requested changes
Я очень прошу на каждый комментарий от твоих сокомандников отвечать: либо вносить исправления, либо аргументировать, почему не согласен. Т.к. сейчас я некоторые из их комментариев продублировала) 
На следующую итерацию жду тестов)

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).body("Цель успешно создана");
Тому, кто запрашивал создание объекта, как-то нужно узнать, с каким id объект создался, чтобы затем запрашивать его по этому id, поэтому Данил совершенно верно написал и обосновал)
Ещё добавлю, что мы не используем ResponseEntity, т.к. в этом нет необходимости. Статус CREATED будет по умолчанию. Вернуть можно просто:
return goalDto; - спринг сам проставит всё остальное в респонс.
Ну и напишу на будущее: мы никогда не возвращаем строки, потому что их нельзя преобразовать в json формат (так же как и почти все остальные стандартные типы в java: int, Integer, long, Long и так далее). Поэтому возвращаем либо void, либо объект (GoalDto).
Это актуально для всех методов контроллера

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    }
Верно. @Suragany98 почему пометил комментарий как resolved, но не внес изменений и не ответил?) Я с комментарием согласна.

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @GetMapping("/{userId}/goals")
В целом очень правильно сделал урлы, но только здесь получается /goals/{userId}/goals - странновато) Можно просто  /goals/{userId}

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +}
@Suragany98 что скажешь?)

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +public class GoalDto {
На мой взгляд, здесь подойдет java records. Рекомендую их использовать везде, где можно

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/goal/GoalFilterDto.java
> +public class GoalFilterDto {
Тоже думаю, что java record здесь отлично подойдет

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/goal/GoalMapperHelper.java
> +        return skillRepository.findAllById(skillIds);
Маппер не должен ходить в базу данных, он не про это. Он просто преобразовывает одни данные в другие, но больше ничего делать не может. Все общения с репозиториями (и базой данных) происходят в сервисах

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/goal/GoalMapper.java
> +@Mapper(componentModel = "spring", uses = GoalMapperHelper.class)
Круто, что решил использовать mapstruct и отлично его используешь 👍

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +    @Query(value = """
Стиль нужно поправить, добавить табуляций (как было раньше)

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/goal/GoalRepository.java
> +    List<Goal> findGoalsByUserId(@Param("userId") Long userId);
А без Param не работает?

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/goal/GoalValidator.java
> +    public void validateGoal(GoalDto goalDto) {
Не думаю, что для этой логики нужен отдельный класс. В целом такая логика обычно валидируется с помощью аннотаций, тебе об этом Данил в комментарии писал. Я бы просто оставила этот метод приватным в сервисе

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private static final int MAX_ACTIVE_GOALS_PER_USER = 3;
Константы обычно располагаются первыми в классе, после них идут все остальные поля

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        // Проверка на максимальное количество активных целей
Комментарии не нужны. Если хочется как-то пояснить код, то вынеси эту часть в отдельный приватный метод с понятным названием (checkMaxActiveGoals или даже checkActiveGoalsCount)

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        // Проверка существования навыков
Аналогично. Код должен быть самодокументируемым, это как раз достигается благодаря верному разбиению на методы. Комментарии в коде являются признаком переусложненой логики, которая требует декомпозиции на методы

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private boolean applyFilter(Goal goal, GoalFilterDto filter) {
Посмотри, как Руслан организовал работу с фильтрами в своей задаче
https://github.com/CorporationX/user_service/pull/1412
Во-первых, так рекомендовал сделать Влад в лекции, а во-вторых, нам нужен единообразный подход.

2024-09-21 17:13 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    @Transactional(readOnly = true)
Не хватает пустой строчки перед аннотацией

2024-09-23 15:02 UTC, Suragany98 commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @GetMapping("/{userId}/goals")
изменил

2024-09-23 15:08 UTC, Suragany98 commented on src/main/java/school/faang/user_service/dto/goal/GoalDto.java
> +public class GoalDto {
Спасибо за рекомендацию!  Я заменил классы с DTO на `records`,

2024-09-23 15:08 UTC, Suragany98 commented on src/main/java/school/faang/user_service/dto/goal/GoalFilterDto.java
> +public class GoalFilterDto {
также изменил

2024-09-23 15:10 UTC, Suragany98 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private static final int MAX_ACTIVE_GOALS_PER_USER = 3;
Спасибо за замечание! Я исправил расположение констант, теперь они находятся в начале класса, перед другими полями

2024-09-23 15:11 UTC, Suragany98 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        // Проверка на максимальное количество активных целей
ок создал приватный метод checkMaxActiveGoals

2024-09-23 15:11 UTC, Suragany98 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +        // Проверка существования навыков
убрал коментарий

2024-09-23 15:12 UTC, Suragany98 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    @Transactional(readOnly = true)
добавил

2024-09-23 15:13 UTC, Suragany98 commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +    private boolean applyFilter(Goal goal, GoalFilterDto filter) {
Спасибо за рекомендацию! Я ознакомился с задачей Руслана и применил аналогичный подход для работы с фильтрами

2024-09-23 16:07 UTC, mysosnovskaya requested changes
Нужны тесты и ещё обрати внимание, что в ПРе возник конфликт, нужно его разрешить, иначе я не смогу его смержить

2024-09-23 16:07 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public ResponseEntity<String> createGoal(@RequestParam Long userId, @Valid @RequestBody GoalDto goalDto) {
В прошлом ревью писала, что мы не используем ResponseEntity и не возвращаем String. Всегда возвращаем dto или void. Вот этого исправления не хватает)

2024-09-30 20:47 UTC, mysosnovskaya requested changes

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public ResponseEntity<String> updateGoal(@PathVariable Long goalId, @Valid @RequestBody GoalDto goalDto) {
`public GoalDto  updateGoal....`

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        return ResponseEntity.ok("Цель успешно обновлена");
`return updatedGoalDto;`

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public ResponseEntity<String> deleteGoal(@PathVariable long goalId) {
`public void deleteGoal....`

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        return ResponseEntity.ok("Цель успешно удалена");
Эта строчка не нужна

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public ResponseEntity<List<GoalDto>> findSubtasksByGoalId(
` public List<GoalDto> findSubtasksByGoalId...`

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        return ResponseEntity.ok(subtasks);
`return goalService.findSubtasksByGoalId(goalId, titleFilter);`

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    public ResponseEntity<List<GoalDto>> getGoalsByUser(
`public List<GoalDto> getGoalsByUser...`

2024-09-30 20:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        List<GoalDto> goals = goalService.findGoalsByUserId(userId, filter);
`return goalService.findGoalsByUserId(userId, filter);`

2024-10-01 08:45 UTC, mysosnovskaya approved these changes

2024-10-01 08:46 UTC, merged