BJS2-27199 - [Experienced] Покупка премиум доступа
CorporationX/user_service pull request #1522
Opened 2024-09-15 15:46 UTC by dmitridorje

Реализован функционал премиум-подписки (согласно описанию в задаче) и промоушн-подписки. В текущей реализации промоушн работает следующим образом. У пользователя есть возможность приобрести три варианта подписки: GENERAL (на 100 просмотров, приоритет 1), ADVANCED (на 500 просмотров, приоритет 2) и PREMIUM (на 750 просмотров, приоритет 3). Каждый вариант продвижения может быть доступен для поднятия либо профиля, либо событий, принадлежащих пользователю. При варианте PREMIUM также активируется таргетирование, при котором поднятие профиля или события будет происходить в том случае, если страна запрашивающего совпадает со страной того, кто приобрел промоушн. "Высота" подъёма также определяется приоритетом подписки - чем выше приоритет, тем выше профиль или событие будут в поиске.

2024-09-17 14:22 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        payPremium(premiumPeriod);
Если платеж не прошел, то все равно идет сохранение премиума?

2024-09-17 14:23 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/PromotionService.java
> +        payPromotion(type);
promoition сохраняется даже если не прошел платеж?

2024-09-17 14:29 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private List<Event> getPriorityFilteredEvents(List<Event> filteredEvents, User callingUser) {
Лучше отрефакторить, примерно так
private List<Event> getPriorityFilteredEvents(List<Event> filteredEvents, User callingUser) {
        return filteredEvents.stream()
                .sorted(Comparator
                        .comparing((Event event) -> calculateCountryPriority(event, callingUser))
                        .thenComparing(event -> calculatePriorityLevel(event)))
                .toList();
    }

    private int calculateCountryPriority(Event event, User callingUser) {
        User eventOwner = event.getOwner();
        if (eventOwner.getPromotions() == null || eventOwner.getPromotions().isEmpty()) {
            return 1;
        }

        Promotion targetPromotion = getTargetPromotion(event);
        if (targetPromotion == null || (targetPromotion.getPriorityLevel() == 3
                && !eventOwner.getCountry().equals(callingUser.getCountry()))) {
            return 1;
        }

        return 0;
    }

    private int calculatePriorityLevel(Event event) {
        User eventOwner = event.getOwner();
        if (eventOwner.getPromotions() == null || eventOwner.getPromotions().isEmpty()) {
            return 0;
        }

        Promotion targetPromotion = getTargetPromotion(event);
        return targetPromotion != null ? -targetPromotion.getPriorityLevel() : 0;
    }

2024-09-17 14:30 UTC, Rashit86 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<User> getPriorityFilteredUsers(List<User> filteredUsers, User callingUser) {
Тоже лучше отрефакторить

2024-09-17 14:32 UTC, Rashit86 commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +    private List<EventFilter> eventFilters;
можно было мокнуть конкретные реализации фильтров, и из моков собрать List, как в видео Влада

2024-09-17 17:29 UTC, mikhailov26 approved these changes

2024-09-17 17:35 UTC, mikhailov26 commented
В целом ок, задачка прям большая, очень хороший ПР получился, в данном случае согласен с комментариями Рашита, но прям особое внимание обратить на вариант, когда платёж не прошёл и в видео на платформе рекомендую ознакомиться с роликом с названием Покупка премиум доступа - дизайн (дополнительно)

2024-09-17 17:38 UTC, mikhailov26 requested changes

2024-09-17 17:38 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        payPremium(premiumPeriod);
+

2024-09-17 17:38 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<User> getPriorityFilteredUsers(List<User> filteredUsers, User callingUser) {
+

2024-09-17 17:38 UTC, mikhailov26 commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +    private List<EventFilter> eventFilters;
+

2024-09-18 06:54 UTC, dmitridorje commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        payPremium(premiumPeriod);
Добавил соответствующие проверки, исключения и тесты

2024-09-18 06:54 UTC, dmitridorje commented on src/main/java/school/faang/user_service/service/PromotionService.java
> +        payPromotion(type);
Добавил соответствующие проверки, исключения и тесты.

2024-09-18 07:30 UTC, dmitridorje commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    private List<Event> getPriorityFilteredEvents(List<Event> filteredEvents, User callingUser) {
Done!

2024-09-18 07:31 UTC, dmitridorje commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private List<User> getPriorityFilteredUsers(List<User> filteredUsers, User callingUser) {
Done!

2024-09-18 10:20 UTC, dmitridorje commented on src/test/java/school/faang/user_service/service/event/EventServiceTest.java
> +    private List<EventFilter> eventFilters;
Done!

2024-09-18 16:55 UTC, mikhailov26 commented
Реши крнфликты и можешь мержить

2024-09-18 16:56 UTC, mikhailov26 approved these changes

2024-09-18 20:48 UTC, merged