Feature/mentorship bjs2 27569 danke villetti
CorporationX/user_service pull request #1531
Opened 2024-09-16 14:24 UTC by DankeVilletti

2024-09-16 17:48 UTC, mysosnovskaya requested changes

2024-09-16 17:48 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRepository.java
> +    @Query("SELECT m.mentee FROM Mentorship m WHERE m.mentor.id = :mentorId")
Не получилось Mentorship на User заменить?

2024-09-16 17:48 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipService.java
> +public class MentorshipService {
Логов так и не вижу)

2024-09-17 06:57 UTC, DankeVilletti commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRepository.java
> +    @Query("SELECT m.mentee FROM Mentorship m WHERE m.mentor.id = :mentorId")
На удаление только не сработает

2024-09-17 09:04 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/mentorship/MentorshipRepository.java
> +    @Query("SELECT m.mentee FROM Mentorship m WHERE m.mentor.id = :mentorId")
У класса User есть такие поля:
```
    private List<User> mentees;
    private List<User> mentors;
```
Если нужно удалить ментора, то тебе нужно из списка mentors удалить User с заданным id. Модель Mentorship не нужна, т.к. она дублирует то, что уже есть в модели User, и очень сильно запутывает в понимании кода.

2024-09-17 09:05 UTC, mysosnovskaya commented
Т.к. я смержила ПР Руслана, то тебе нужно подтянуть изменения из ветки hippogriff-master-stream6 к себе и разрешить конфликты. Если у тебя особо нет опыта в разрешении конфликтов, то обязательно сделай копию своей работы, чтобы не потерять.

2024-09-17 18:16 UTC, mysosnovskaya approved these changes

2024-09-17 18:16 UTC, merged