BJS2-27047   Интеграция с генератором случайных аватаров юзера
CorporationX/user_service pull request #1543
Opened 2024-09-17 19:45 UTC by ilu23ilu23

-в application.yaml добавил настройки MinIO
-добавил MinioConfig, RestTemplateConfig
-в UserController добавил пост метод registerUser
-создал UserDto, UserMapper, AvatarStyle, exceptions
-в сервисном слое классы MinioService, AvatarService для генерации аватарок с DiceBear, и их сохранение в бд и в MinIo
-в UserService создал метод регистрации пользователя и создании аватарок(большой и малой)

Описание фичи - при регистрации юзеру устанавливается стандартная аватарка, загружаемая с сайта DiceDear, так же миниаватар(для отображения в сообщениях, например), при этом в бд к юзеру сохраняется ключи аватарок в ембедабл сущность UserProfilePic, а сами аватарки сохраняются в MinIO.

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/config/minio/MinioConfig.java
> +
лишний пробел

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return ResponseEntity.ok(responseDto);
можно же просто `responseDto` вернуть и будет тоже самое

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/dto/user/UserDto.java
> +    @NotBlank(message = "Email is mandatory")
обычно пишется **required**

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/entity/AvatarStyle.java
> +    PIXEL_ART("pixel-art");
обычно значения пишутся тоже заглавными и через _

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +    private String saveAvatar(AvatarStyle style, int size, String contentType) {
наверное лучше не **saveAvatar**, а **uploadAvatar**
save как-то ассоциируется с сохранением в БД

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        } else {
else тут не нужно. если в if попали, то дальше не пойдёт, там return

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/minio/MinioService.java
> +
лишняя строка

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/minio/MinioService.java
> +        try (InputStream inputStream = new ByteArrayInputStream(data)) {
интересная конструкция

2024-09-18 07:41 UTC, cemeh666 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private void validateUser(User user) {
тут нужно уточнение. **validateUser** слишком общее понятие. нужно обозначить, что валидация для/перед регистрации пользователя

2024-09-18 11:12 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return ResponseEntity.ok(responseDto);
У тебя ниже метод был написан таким образом, я так сделал, чтобы в одном стиле всё было

2024-09-18 11:14 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/AvatarStyle.java
> +    PIXEL_ART("pixel-art");
Тут таким образом написано, чтобы эти строки подставлять в урл для запроса аватарки с DiceBear

2024-09-18 11:26 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/minio/MinioService.java
> +        try (InputStream inputStream = new ByteArrayInputStream(data)) {
Это "try with resources"

2024-09-18 11:55 UTC, cemeh666 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return ResponseEntity.ok(responseDto);
я писал ResponseEntity, чтобы 204 статус отдать с пустым контентом

2024-09-18 16:28 UTC, sultan-inked commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    boolean existsByEmail(String email);
Я бы разделил строкой

2024-09-22 19:42 UTC, 20cognosce requested changes
Почему нет Success CI Build'а? Переоткрой ПР, чтобы CI прогнал тесты

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/entity/AvatarStyle.java
> +    BOTTTTS("bottts"),
У них реально такие имена?

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/mapper/user/UserMapper.java
> +public interface UserMapper {
Не будет еще одно конфликта? Сколько у нас этих мапперов для юзера

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        String url = String.format("https://api.dicebear.com/9.x/%s/%s", style.getStyleName(), format);
В конфигурацию вынести

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        ResponseEntity<byte[]> response = restTemplate.getForEntity(uriBuilder.toUriString(), byte[].class);
Нельзя получать Multipart? Только массив байт?

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/minio/MinioService.java
> +            );
Хорошо

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        String url = String.format("https://api.dicebear.com/9.x/%s/%s", style.getStyleName(), format);
И как-нибудь более читаемо собирать URL

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
>      }
Где пробел

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        userProfilePic.setFileId(largeAvatarFileName);
Большой не надо гененировать
Большой аватар пользователь загружает сам, это в текущем спринте задача

2024-09-22 19:42 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        userProfilePic.setSmallFileId(smallAvatarFileName);
И почему у тебя id является имя? Имя может быть не уникально
Сервис не отдает мета-инфу по аватару, как его можно идентифицировать?

Можешь свой uuid генерировать и с минио его связывать, так не пойдет

2024-09-23 17:59 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/entity/AvatarStyle.java
> +    BOTTTTS("bottts"),
Да, на сайте DiceBear

2024-09-23 18:00 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/mapper/user/UserMapper.java
> +public interface UserMapper {
Все конфликты, которые были - разрешил

2024-09-23 18:01 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        String url = String.format("https://api.dicebear.com/9.x/%s/%s", style.getStyleName(), format);
Я пробовал, но тут мне надо вставить вид аватара и размер аватара, этот вариант самый удобный и читаемый

2024-09-23 18:09 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        ResponseEntity<byte[]> response = restTemplate.getForEntity(uriBuilder.toUriString(), byte[].class);
Можно и так и так, в следующей задаче сделаю через мультипарт
Просто сейчас переписывать много, но код работает, всё здорово

2024-09-23 18:11 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/user/UserService.java
>      }
А это не моё)
Но поправил

2024-09-23 18:15 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        userProfilePic.setFileId(largeAvatarFileName);
Суть в том, что большой - это основной аватар, а маленький - его уменьшенная копия, например, для сообщений, и надо, чтобы стандартный аватар был везде, и тут Embedable класс UserProfilePic, у которого два поля как раз для ключей большого и малого аватара, если только малый оставить - туда нулл придется писать, а смысл так делать? Пользователь потом сам свой аватар и большой и малый заменит, а стандартные должны быть сразу и везде.

2024-09-23 18:21 UTC, ilu23ilu23 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        userProfilePic.setSmallFileId(smallAvatarFileName);
Я же в приватном методе uploadAvatar так и делаю - генерирую uuid и загружаю в минио, а тут я использую  результат этого метода, а именно uuid`ы и сетаю в объект UserProfilePic, потом всё это с юзером идет в базу.

2024-09-23 20:24 UTC, 20cognosce approved these changes

2024-09-23 20:24 UTC, merged