BJS2-26843 - Swagger integration for user-service
CorporationX/user_service pull request #1566
Opened 2024-09-20 01:58 UTC by mrkorolev

2024-09-20 07:12 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/UserServiceApplication.java
> +                license = @License(name = "Proprietary License")))
Круто

2024-09-20 17:18 UTC, 20cognosce requested changes
Исправить импорты
+Закинуть патч на корректный билд CI

2024-09-20 17:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/UserServiceApplicationTest.java
> +import school.faang.user_service.repository.event.filters.*;
Страшное преступление

2024-09-20 17:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalInvitationServiceTest.java
>  import static org.junit.jupiter.api.Assertions.*;
So bad

2024-09-20 17:18 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/goal/GoalInvitationServiceTest.java
>  import static org.mockito.Mockito.*;
Disappointing

2024-09-20 17:18 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
>  import static school.faang.user_service.service.util.GoalInvitationUtil.*;
Ну сколько можно?

2024-09-20 18:27 UTC, mrkorolev commented on src/test/java/school/faang/user_service/UserServiceApplicationTest.java
> +import school.faang.user_service.repository.event.filters.*;
Правда? Почему?) Он и так их импортировал все из этого пакета, я же не целую либу здесь импортирую

2024-09-20 18:34 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/goal/GoalInvitationService.java
>  import static school.faang.user_service.service.util.GoalInvitationUtil.*;
Тот же самый вопрос - все элементы из этого класса (поголовно) используются внутри сервиса

2024-09-21 18:16 UTC, 20cognosce approved these changes

2024-09-21 18:16 UTC, merged