task BJS2-27412 solution
CorporationX/user_service pull request #1568
Opened 2024-09-20 21:25 UTC by wmwmaks

2024-09-21 02:34 UTC, SharkB38 approved these changes

2024-09-21 02:34 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }
FindAll возвращает тех кого нашел, а тех кого не нашел пропускает(ауф). Ну то есть отдал список из 10 id, одного в базе нету, метод вернет 9 сущностей. Поэтому такая проверка не подойдет, нужно сравнивать id тех кого вернул метод с теми id которые отдал в метод.

2024-09-21 04:45 UTC, soulasphyxia requested changes

2024-09-21 04:45 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
Максим, сделай пожалуйста названия контроллеров в соответствии с заданием 
![image](https://github.com/user-attachments/assets/79184c1c-94f5-41b5-92a6-fcfa8606185d)
, потому что они совпадают с тем, что тут в клиенте, который надо использовать для юзеров, и мне кажется это не с проста.. 
![image](https://github.com/user-attachments/assets/28547c21-65ac-42a4-9adf-2e55aaebe6ac)

2024-09-21 05:57 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }
Почему? Если он найдет 5 из 10, значит, есть 5 из 10. Это не ошибка же

2024-09-21 06:03 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }
Ну с такой точки зрения и пустой список не является ошибкой как по мне. Тогда думаю если ошибку не кидать, то нужно по хорошему сообщить кого не нашли в базе

2024-09-21 06:05 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }
Логирование можно изменить. Сделать второй лог с id, которые удалось найти. Чтобы было видно что запросили - что получили

2024-09-21 06:07 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
Почему тут метод getUsersByIds - Post

2024-09-21 06:11 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }
Можно в log.warn засунуть тех кого не нашел и оставить лог с теми кого нашел как есть

2024-09-21 06:16 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
Где найти этот класс, который ты скинул скриншотом?

2024-09-21 07:00 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
это в пакете client в post_service, с POST все непонятно) погуглил, но так и не понял ничего (https://stackoverflow.com/questions/67889232/get-request-with-body-vs-post-for-retrieving-a-large-resource)

2024-09-21 07:01 UTC, soulasphyxia approved these changes

2024-09-21 07:03 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
возможно буду нести бред, но GET мы используем, чтобы получить ресурс, и нам должно хватать параметров из строки(типа эндпоинта + query params), а если нам нужно получить ресурс, отправив Request Body, то это уже POST... вообще, я не понимаю, разве спринг не умеет собирать в лист элементы из запроса, по типу ?userIds=5&userIds=6&userIds=7 => [5,6,7] интересно, почему так было сделано...

2024-09-21 07:08 UTC, SharkB38 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
Типо по правилам для Request Body нужен POST запрос? Я просто фигачил в GET все работало

2024-09-21 07:41 UTC, ArstanSubanov approved these changes

2024-09-21 07:54 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
Сложно

2024-09-21 08:13 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
так оно все всегда будет работать, ты можешь сделать POST запрос, в котором будешь удалять сущности, тебе это никто не запрещает, но насколько это вот семантически правильно

2024-09-21 08:30 UTC, SharkB38 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
Понял, принял, осознал. Если что-то в теле передаём это POST

2024-09-21 09:06 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
нееет, я не это хотел сказать, я сам не особо понимаю почему так тут сделали... я говорил о том, что мы как разработчики сами решаем как будут вести наши методы при POST,GET и т.д. запросах, и что все будет работать и так, тут вопрос семантики и где логика в том, чтобы возвращать сущность при POST запросе...

2024-09-21 09:07 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
предлагаю это оставить как тут, но вынести на ретро спросить у Маши...

2024-09-21 09:25 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }
Пустой список будто бы и правда тоже не ошибка, да. Наверное, стоит убрать это. Подождем, что Маша скажет

2024-09-21 17:43 UTC, mysosnovskaya requested changes

2024-09-21 17:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }
Обычно пустой список не ошибка. Если нас просят, например, отдать всех друзей Васи, а у Васи друзей нет, то мы отдаем пустой список и все понимают, что запрос был корректным, просто вот такая ситуация, что друзей нет) Это не какая-то исключительная ситуация, а самое главное - что в самом запросе ошибок нет, он корректный.
Что касается именно этой ситуации, то поступать можно по-разному в зависимости от требований. Можно даже прислать список найденных пользователей и список айди ненайденных пользователей) Однако best practice в этом вопросе (если нет явного обратного требования) это возвращать 200 даже если удалось найти не всех.

2024-09-21 17:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        log.debug("Users with ids %s found"
Я бы скорее в лог записала тех, кого не нашли. Это более информативно. Потом можно распутывать клубок и выяснять, почему вообще их искали и с чего взяли, что они у нас есть. Может быть кто-то где-то хранит неактуальную информацию и с этим стоит поработать

2024-09-21 17:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        List<UserDto> userDtos = userMapper.usersToUserDtos(users);
return userMapper.usersToUserDtos(users);

2024-09-21 17:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +public class UserController {
Чтобы аннотации валидации заработали, нужно добавить аннотацию Validated над классом

2024-09-21 17:49 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}")
Я тут отвечу, но если будет желание - поговорим ещё на ретро)
Строгого правила на этот счет нет и вполне допустимо сделать GET запрос с телом. Однако многие разработчики такое не любят (мне нормально =)) как раз из-за того, что GET по логике своей не подразумевает тела. Поэтому выбираем из двух вариантов: POST + RequestBody или GET + query params. Я обычно за второй вариант, только если нет какой-то супер-сложной логики, вложенных друг в друга объектов и так далее. 
У спринга есть отличная возможность: сделать GetMapping, параметром этого метода сделать какой-то dto объект, но не помечать его RequestBody. Тогда он будет интерпретироваться как query param. Я как раз об этом кидала статью Арстану, дублирую ссылочку:
https://medium.com/@pandaniel/spring-boot-controllers-getmapping-and-complex-objects-bd182ec99f54

В общем дела обстоят так. Но если у вас в требованиях явное POST + RequestBody, то так и нужно делать.

2024-09-21 17:52 UTC, mysosnovskaya commented
@wmwmaks вроде бы небольшая задачка, а какие два интересных вопроса обсудили! Назначаю тебя хранителем знания по поводу GET/POST + QueryParam/RequestBody и по поводу статус кода 200 для частично успешных запросов. На кросс-ревью обязательно обращай на это внимание) 
И пожалуйста, напомни мне об этом на ретро, если я забуду. Хочу ещё голосом под запись это проговорить.

2024-09-22 15:57 UTC, mysosnovskaya approved these changes

2024-09-22 15:57 UTC, merged