BJS2-26107 - Интеграция с генератором случайных аватаров юзера
CorporationX/user_service pull request #1574
Opened 2024-09-21 18:06 UTC by GusevVrn

2024-09-23 20:39 UTC, Silencemess1ah reviewed
**_Паш ну я добрую половину не выкупаю, как смог в общем..._** 
![vpAvMA1DT-D5dZABSogrWmFalas-1920](https://github.com/user-attachments/assets/22a8644a-b3ff-4248-8b96-2772c18ed7fe)

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/config/s3Config/S3Config.java
> +public class S3Config {
_Первый коммент, сразу оговорюсь мало что понимаю, чисто визуально больше ну и чтоб кросс пройти, Паш прости вчера вообще из башки вылетело..._  здесь отступ

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/controller/user/UserController.java
>      private final UserService userService;
Отступ

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        log.info("Registration user {} completed", userDto);
может id юзера сюда в лог подвязать? Юзер с таким Id начал\закончил регистрацию, не знаю просто короче отчет будет найдем потом его если что

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +
лишний отступ

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/dto/user/UserDto.java
> +    private String userProfilePicId;
Это типо Id картинки юзера? А надо String-ой его ?

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/entity/UserProfilePic.java
>      private String smallFileId;
Ну это к теме выше про стринг айДи,  видимо так задумано

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    }
Не через идею смотрю, а надо в методе эксепшн кидать если ты весь метод в трай кэтч обернул и ловишь ее (RTE)?

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +
2 лишние строки

2024-09-23 20:39 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/validator/user/UserValidator.java
> +    }
можно private, ты ж их потом в общий метод собираешь или все нужны для вызова где то еще?

2024-09-23 20:39 UTC, Silencemess1ah commented on src/test/java/school/faang/user_service/service/user/UserServiceTest.java
> +            }
Ни одного Asserta все ОК? ) просто странно столько логики вроде

2024-09-23 21:27 UTC, GusevVrn commented on src/test/java/school/faang/user_service/service/user/UserServiceTest.java
> +            }
Дык у меня же сервис вызывает другие сервисы и все.

2024-09-23 21:27 UTC, GusevVrn commented on src/main/java/school/faang/user_service/validator/user/UserValidator.java
> +    }
Я сделал public чтоб потом ими можно было по отдельности пользоваться, это же валидатор.
У меня по задаче эти 3 надо дернуть, может у кого-то будет другая задача где надо проверить чисто телефон

2024-09-23 21:27 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    }
Да, тут просто хз что ловить. new ByteArrayInputStream с одной ошибкой валится, amazonS3 с другой, ну и еще возможно в каких-то местах отвалится.

2024-09-23 21:28 UTC, GusevVrn commented on src/main/java/school/faang/user_service/dto/user/UserDto.java
> +    private String userProfilePicId;
Ага, он id называется но там не цифра а может быть вот такое значение 131111054profilePic1727124634569avatar.png

2024-09-23 21:28 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        log.info("Registration user {} completed", userDto);
Так тут же регистрация, ты не знаешь ID изначально. Показываю чтоб можно было потом в логах найти по любому полю

2024-09-24 19:19 UTC, mysosnovskaya requested changes
Хорошая работа, молодец!)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/client/FeignUserInterceptor.java
> +        if (!shouldSkipInterceptor(template.feignTarget().url())) {
Круто, что ты это учел 👍

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/client/RemoteImageClient.java
> +public interface RemoteImageClient {
Может быть лучше назвать ImageGeneratorClient, что думаешь? Моя мотивация такая: во-первых, когда мы пишем Client, то подразумеваем, что он обращается к какому-то сервису, описываемому существительным (ProjectServiceClient, MinioClient). Во-вторых, Client уже говорит о том, что это remote.

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/s3Config/S3Config.java
> +                .withConnectionTimeout(10_000)
Почему бы эти таймауты тоже не вынести в параметры?

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        log.info("Registration user {} started", userRegistrationDto);
Логи уже есть в метод registerUser в юзер сервисе, причем по смыслу такие же. Зачем их здесь дублировать? И в целом логи всегда пишутся на уровне сервисов)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PutMapping("/registration")
Интересно, почему выбрал Put, а не Post?

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/user/UserRegistrationDto.java
> +        return "UserRegistrationDto{" +
Молодец, что подумал об этом 👍 А то когда увидела логирование полностью всего объекта UserRegistrationDto, хотела комментарий писать)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    Optional<User> findByPhone(String email);
Имя параметра неверное)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    Optional<User> findByUsername(String email);
Имя параметра неверное)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    Optional<User> findByEmail(String email);
Молодец, что уже используешь запросные методы, хотя по программе ещё этого не проходили 👍

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/image/RemoteImageService.java
> +            log.info("Successfully got response");
По-моему ещё рано писать об успешности получения) А если строчкой ниже getUserProfileImage вернет ошибку? Тогда в логах будет: 
```
Successfully got response
Failed to fetch image...
```

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/image/RemoteImageService.java
> +            throw new IOException("Failed to fetch image");
Я бы не стала оборачивать всё в непроверяемое исключение. Да и IOException здесь не подходит, т.к. обычно оно применяется для низкоуровневых операций ввода-вывода, а у тебя речь идёт о взаимодействии с удалённым сервисом через HTTP. Создай своё собственное исключение и оберни всё в него)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    public String uploadHttpData(ResponseEntity<byte[]> data, String folder) throws RuntimeException {
А зачем "throws RuntimeException"? По идее любой метод может такое исключение генерировать, и т.к. оно непроверяемое, то нет нужды о нём всем сообщать =)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            return true;
А если doesBucketExistV2 вернул false?

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            log.error("Error while creating new bucket");
Нужно как-то в метод uploadHttpData тоже сообщить, что бакет не создался. Иначе там продолжится выполнение остального кода (в частности `s3Client.putObject(putObjectRequest);`), что выглядит некорректным

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            log.info("Bucket with name {} doesn't exists", bucketName);
На мой взгляд, странно делать вывод о том, что бакет не существует, из-за AmazonS3Exception. Из документации к этому методу: 
`AmazonServiceException – If any errors occurred in Amazon S3 while processing the request.`
т.е. тут может быть абсолютно любая ошибка

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        String filename = "pic.png";
В этом методе используется много констант.

1. "pic.png" - это лучше вообще вынести в параметры (в application.yaml)
2. "Content-Disposition" повторяет аж три раза. Определенно нужно вынести в константы. При этом заметь, что это можно взять уже из готовых констант (например, com.amazonaws.services.s3.Headers)
3. `Pattern pattern = Pattern.compile("filename=\"?([^\"]+)\"?");` тоже может быть константой класса. Нет смысла создавать этот объект каждый раз при вызове метода

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +                    filename = matcher.group(1);
Молодец, что применяешь регулярные выражения, ещё и на таком продвинутом уровне (с группами). Круто 👍

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        setUserDefaultAvatar(user);
А сохранить этого юзера после назначения аватарки? Тут видимо всё работает из-за Transactional (т.к. фактическое сохранение юзера происходит только после завершения метода), но код очень не очевидный. Давай сначала назначим пользователю аватар, а потом сделаем save этого пользователя в базу данных

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            if (s3Service.isDefaultPictureExistsOnCloud()) {
Классно придумал с дефолтной аватаркой)

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        String pictureKey;
Не нужно выделять отдельную переменную pictureKey, можно так:
```
    private String assignUserRemoteRandomPicture(User user) {
        log.info("Trying to assign random picture for user {}", user);
        try {
            ResponseEntity<byte[]> pictureContent = remoteImageService.getUserProfileImageFromRemoteService();

            String s3Folder = user.getUsername() + user.getId() + "profilePic";
            return s3Service.uploadHttpData(pictureContent, s3Folder);
        } catch (IOException e) {
            log.error(e.getMessage());
            throw new RuntimeException(e);
        }
    }
```

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    bucketDefaultAvatarsName: usersdefaultavatars #should be lowerCase
За комментарий спасибо, это действительно важно подписать 👍

2024-09-24 19:19 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +      externalUrl: https://external.api #example how to add external url
Это не понимаю, зачем здесь это нужно? 
Мне в целом не очень нравится идея объединить все внешние апи под одни настройки (external apis). Обычно для других сервисов работает такая же логика, как для s3 выше:
```
services:
  s3:
    endpoint: http://localhost:9000
    ....
  imagegenerator:
    endpoint: http://localhost:9000
    ...timeout....
```

2024-09-25 09:35 UTC, GusevVrn commented on src/main/resources/application.yaml
> +      externalUrl: https://external.api #example how to add external url
Я понимаю твою логику, у меня вопрос тогда, я сильно долго мучался с обходом добавления хедера, чтоб там не просто втупую зашиты адресы или префиксы я сейчас все внешние ссылки собираю через 
```
@ConfigurationProperties(prefix = "external.apis")
public class ExternalApisProperties {
    private Map<String, String> urls;
}
```
Если я по твоей структуре сделаю и кто-то захочет добавить url, то придется строго соблюдать такую же структуру.
Может есть какой-то более правильный подход?

Короче сейчас сделал как получилось. Не могу собрать все сервисы в мапу, чтоб потом по аналогии вытащить эндпоинты для проверки. Подскажи как это сделать. Я так понял что в ExternalApisProperties название мапы должно совпадать с yml, короче запутался, всячески пробовал, ничего не получается.

2024-09-25 09:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +                    filename = matcher.group(1);
Это gpt) Я ненавижу регулярки)

2024-09-25 09:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            return true;
Я когда дебажил, он мне никогда false не возвращал. Вместо этого выбрасывалось исключение.
Щас пробую, нормально false возвращает. Странно. 
Переделал

2024-09-25 09:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    public String uploadHttpData(ResponseEntity<byte[]> data, String folder) throws RuntimeException {
У меня прошлая реализация была по стариковски, через HttpConnection, там надо было явно его выкинуть, идея ругалась.
Когда поправил на feign, не убрал(

2024-09-25 09:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PutMapping("/registration")
Подумал про идемпотентность, т.к. мы не сможем из-за ограничений создать еще одного такого же пользователя. 
Может и не к месту.

2024-09-25 09:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        log.info("Registration user {} started", userRegistrationDto);
Попробуем через дебаг)

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        log.debug("createUserAccount() - start, suerRegistrationDto: {}", userRegistrationDto);
А можешь пояснить, почему ты вообще решил здесь логи добавить? Чем не хватает тех, которые в сервисном методе?

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<UserDto> createUserAccount(@RequestBody @Valid UserRegistrationDto userRegistrationDto) {
Зачем ResponseEntity появился?) Без него хорошо было. А так только лишний код, а смысла не прибавляет. Лучше вернуть просто UserDto

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PutMapping("/registration")
Тут как раз POST подойдет. Он не идемпотентный и как раз означает создание. А вот PUT как раз идемпотентный и поэтому здесь не подходит)

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/image/RemoteImageService.java
> +    public ResponseEntity<byte[]> getUserProfileImageFromRemoteService() throws ImageGeneratorException {
Зачем throws ImageGeneratorException? Это же непроверяемое исключение. Если хочется поговорить подробнее о проверяемых и непроверяемых исключениях - задавай вопрос на дейлике, обсудим)

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +                Pattern pattern = Pattern.compile(FILE_NAME_PATTERN);
Можно прям весь  Pattern pattern сделать константой, только назвать понятнее

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +                    filename = matcher.group(1);
Они непростые, но очень эффективные) Советую подружиться!)

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        log.debug("registerUser() - end : user = {}", user);
Я бы info уровень оставила)

2024-09-25 19:36 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +      externalUrl: https://external.api #example how to add external url
Теперь поняла, зачем тебе это нужно. Но я неуверена, что нам надо это так обобщать. Нет гарантии, что для всех сторонних сервисов этот хэдер будет не нужен (а если ты будешь обращаться в один из наших микросервисов (тоже нужен будет клиент) и обязательно нужно будет прокинуть этот хэдер?). 
У меня такая идея (вроде бы должна работать): создать общий абстрактный класс для параметров к удаленным сервисам, там выделить два поля (может быть ещё какие-то придумаешь): url, acceptUserIdHeader (тут тоже может получше название придумаешь). Далее в FeignUserInterceptor добавляешь конструктор, в который принимаешь List<ТвойАбстрактныйКласс>, из этого списка делаешь список урлов, для которых нужен skip и этот список сохраняешь в соответствующее поле. Ну и потом в методе shouldSkipInterceptor пользуешься этим списком) По-моему красиво и нет никакой "магии" или скрытой логики в том, что для всех сторонних сервисов этот хэдер не передается. Если её оставить в таком виде, то для других разработчиков, которые будут добавлять новые интеграции, это логика будет неочевидна. Давай попробуем такое реализовать?)

2024-09-26 20:32 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        log.debug("createUserAccount() - start, suerRegistrationDto: {}", userRegistrationDto);
Я у взрослых дядь на проекте такое видел)
Чет до меня только сейчас дошло, что скорей всего эти все логи пишутся куда-нибудь в ELK. Ну да, нам пока такое не надо.

2024-09-26 20:38 UTC, GusevVrn commented
Про идемпотентность - опять.
Ты пишешь что создание пользователя не подойдет под Put - но у нас из-за ограничений в бд невозможно создать дубль такого пользователя. Почему put то не пройдет тут?

Я руководствуюсь логикой Delete - один раз удалили, все остальные разы получаем какую-нибудь 204 ошибку. Он идемпотентный.
Post - каждый раз мы дергаем и каждый раз на одно и тоже дто мы получаем нового пользователя с другим id.
Put - как и в delete на одно и тоже дто мы первый раз создали, все остальное вываливается с какой-нибудь ошибкой. В нашем случае по валидации.

2024-09-27 13:49 UTC, GusevVrn commented
@mysosnovskaya круто, до меня начинает доходить магия. Можешь сказать как такой паттерн называется?

Я только не могу разобраться с одним моментом, может я опять перекрутил. У нас же может быть много хедеров, вот я и решил сделать их списком.

Вообще я не могу сформулировать нормально вопрос) Попытаюсь нарисовать)
```
yml:
services:
  imagegenerator:
    endpoint: http://localhost:9000
  postService:
    endpoint: http://localhost:8081
    headers: x-user-id, x-post-id, x-comment-id
```
Ситуация 1 - Я для регистрации дергаю свой эндпоинт, где в хедерах ничего не передаю, в методе дергается сторонний imagegenerator, на FeignUserInterceptor проверяется что такому api не нужны никакие хедеры и запрос нормально проходит.

Ситуация 2 - Мне необходимо дернуть postService, я в хедерах изначально ничего не передаю, дергается метод вызывающий postService, доходит дело до фильтров и по структуре выше, нам необходимо передать 3 хедера ( но я же их не передавал). 
Для каждого хедера из списка идет:
```
template.header()
```
Если и название хедера я могу указать прям то которое в списке, то откуда брать значение.

А даже если и передал хедеры, мне как-то заранее надо узнать какие хедеры могут быть переданы и в UserContext написать методы для присваивания такого хедера и получения значения.

Короче непонятно. На фильтре который дергается еще до эндпоинта мы не можем знать что именно будет дергаться дальше в программе, хардкод - путь в никуда.

Ну как смог, объяснил.

2024-09-27 20:20 UTC, mysosnovskaya requested changes
Ещё небольшие правки и на следующем ревью судя по всему смержим) Мне понравилось, как ты поработал с интерцептором - круто получилось)

2024-09-27 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/client/FeignUserInterceptor.java
> +        return apiProperties.stream()
Лучше оптимизировать: вместо  List<ApiProperties> лучше сразу в поле хранить Map<String, ApiProperties>, где ключ - это url (endpoint)

2024-09-27 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/api/ApiProperties.java
> +public abstract class ApiProperties {
Хорошо получилось, мне нравится 👍

2024-09-27 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/api/ApiProperties.java
> +    private List<String> headers;
Может в название поля контекста добавить? "sentHeaders"? Или "headersToSend"? Или "requiredHeaders"?

2024-09-27 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@Slf4j
Аннотация лишняя

2024-09-27 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    private final String FILE_NAME_PATTERN = "filename=\"?([^\"]+)\"?";
Нужно добавить static (т.к. это константы) и переместить вверх класса. Обычно в классе идут сначала все константы, а потом остальные поля

2024-09-27 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    private final Pattern PATTERN_GET_IMAGE_NAME_FROM_HEADER = Pattern.compile(FILE_NAME_PATTERN);
Аналогично предыдущему комментарию

2024-09-27 20:20 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        userRepository.save(user);
Этот save уже не нужен же? Такая же строчка ниже, после проставления аватарки

2024-09-27 20:20 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/mapper/user/UserMapperTest.java
> +    class toEntity {
Имя класса с большой буквы? 
Я на самом деле не вижу большого смысла делить тесты на подклассы. Это бывает оправданно, когда тестов очень-очень много, но когда их 5 штук (как здесь), то это уже на мой взгляд переусложнение. Но я вижу, что вы все так пишите. Примем это за командный стиль)

2024-09-27 20:20 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/user/UserServiceTest.java
> +import static org.mockito.ArgumentMatchers.*;
Кстати, импорты лучше не сворачивать. Если к коду прикрутить чекстайл, то он на это будет ругаться) В IDEA есть такая настройка, рекомендую её найти и настроить так, чтобы эти звездочки (wildcard imports это называется) не появлялись.

2024-09-29 18:30 UTC, mysosnovskaya approved these changes
Аппрув ставлю, исправь последние мелочи и можешь сам смержить и закрыть задачу)

2024-09-29 18:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/client/FeignUserInterceptor.java
> +        if (endpointRequiredHeaders.containsKey(template.feignTarget().url()) &&
```
 List<String> headers = endpointRequiredHeaders.get(template.feignTarget().url());
if (headers != null && !headers.isEmpty()) {
    addHeaderToTemplate(template, headers);
}
```

2024-09-29 18:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    private final Pattern PATTERN_GET_IMAGE_NAME_FROM_HEADER = Pattern.compile(FILE_NAME_PATTERN);
static + переместить в начало класса

2024-09-29 20:29 UTC, merged