Получение пользователей : bjs2 26847
CorporationX/user_service pull request #1579
Opened 2024-09-22 15:40 UTC by GaribAghayev

2024-09-23 20:27 UTC, 20cognosce requested changes

2024-09-23 20:27 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping("/users-by-ids")
что за путь такой

2024-09-23 20:27 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{userId}/get-user")
и это что

2024-09-23 20:27 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        List<User> list = userRepository.findAllById(ids);
users, а не list

2024-09-23 20:27 UTC, 20cognosce commented on src/test/java/school/faang/user_service/controller/user/UserControllerTest.java
> +public class UserControllerTest {
На контроллер на надо писать юнит-тест, это бессмысленно
Только на классы с бизнес-логикой

Контроллеры будешь тестировать интеграционными тестами

2024-09-23 20:33 UTC, GaribAghayev commented on src/test/java/school/faang/user_service/controller/user/UserControllerTest.java
> +public class UserControllerTest {
удалил

2024-09-24 15:51 UTC, 20cognosce approved these changes

2024-09-24 15:51 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping()
Пустые скобки не нужны

2024-09-24 15:51 UTC, merged