Парсим файлы пользователей - сделал базовый функционал
CorporationX/user_service pull request #1586
Opened 2024-09-23 20:40 UTC by NurseyitTursunkulov

2024-09-23 21:04 UTC, ostermal7 reviewed
И еще там на многопоточку намек, тут в целом это прям параллельно делать можно как я понимаю

2024-09-23 21:04 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        var students = getPersonsFromFile(fileStream);
мне кажется, что юзать таким образом var'ы надо меньше. Она не уменьшают количество кода, который ты пишешь, но при этом ухудшают читаемость

2024-09-23 21:04 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        StreamSupport.stream(countryRepository.findAll().spliterator(), false)
поменяй у кантрирепозитори с jparepository на crudrepository и тогда не придется вот это стремное StremSupport писать

2024-09-23 21:04 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        StreamSupport.stream(countryRepository.findAll().spliterator(), false)
и еще метод у тебя не выполняет то, что у него описано в названии

2024-09-23 21:04 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        StreamSupport.stream(countryRepository.findAll().spliterator(), false)
Не проще было бы искать по конкретной стране? Если у тебя будет 500 стран в базе, то ты зачем-то тянешь их все. Это долгая работа будет, надо более легковесно

2024-09-23 21:04 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +                .filter(country -> country.getTitle().equals(user.getCountry().getTitle()))
у тебя новая страна потом точно сохранится в бд? А то по ревью не вижу какая там связь у таблиц

2024-09-24 08:08 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        StreamSupport.stream(countryRepository.findAll().spliterator(), false)
> и еще метод у тебя не выполняет то, что у него описано в названии

если так переименую то норм?
ifUserCountryExistsInDBOrElse

2024-09-24 13:32 UTC, smallfloppa1 commented on src/main/java/school/faang/user_service/entity/student/PreviousEducation.java
> +    private Integer completionYear;
private Integer graduationYear;

2024-09-24 13:36 UTC, DenysDovgan commented on src/main/java/school/faang/user_service/mapper/user/UserMapper.java
> +        return aboutMe.toString();
Вместо кучи ифов лучше сделай с помощью стрим апи. Это все можно уложить в один стрим и отфильтровать через Objects::nonNull и собрать через collect(Collectors.joining(", ")

2024-09-24 13:42 UTC, DenysDovgan commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }).toList();
Сделай отдельный приватный метод setUserCountry чтобы не местить две логики в одном методе. Да и зачем тебе его собирать в лист если ты его нигде не юзаешь

2024-09-24 18:07 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        }).toList();
Во-первых, у тебя тут еще обращается на каждого юзера с базу. т.е. если будет 1000 юзеров, то будет 1000 обращений, это не ок. Лучше их всех сохранить разом вместе одним обращением.
Во-вторых, Денис правильно сказал - зачем тебе тут в конце лист?

2024-09-24 18:11 UTC, ostermal7 commented on src/main/java/school/faang/user_service/mapper/user/UserMapper.java
> +        }
Зачем тебе целый интерфейс?

2024-09-24 18:12 UTC, ostermal7 reviewed
И еще - заем ты опять на самый верх тащишь IOException? почему бы не обработать сразу, где ловишь?

2024-09-24 19:10 UTC, ostermal7 commented
Также не заметил теста с использованием csv

2024-09-25 11:31 UTC, VitoS1C commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping("upload")
Слэш потерялся и возможно глагол заменить на существительное

2024-09-25 11:40 UTC, VitoS1C commented on src/main/java/school/faang/user_service/entity/student/Person.java
> +}
Я так полагаю это у тебя DTO, тогда почему эти классы у тебя в пакете entity находятся. Entity пакет для взаимодействия с БД.

2024-09-25 11:45 UTC, VitoS1C commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    public void addUsersFromFile(InputStream fileStream) throws IOException {
Исключение лучше обработать!

2024-09-25 11:51 UTC, VitoS1C commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +            throw new RuntimeException(e);
Нужно логировать исключение, чтоб потом понять, что не так у тебя с приложением.

2024-09-25 11:56 UTC, VitoS1C commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    Function<InputStream,List<Person>> parseFileToPersons = (this::getPersonsFromFile);
Зачем это здесь, если ты используешь это только в тесте?

2024-09-25 12:16 UTC, VitoS1C commented on src/main/java/school/faang/user_service/entity/student/Person.java
> +}
Пакет json/student думаю будет лучше

2024-09-25 19:18 UTC, NurseyitTursunkulov commented
> И еще там на многопоточку намек, тут в целом это прям параллельно делать можно как я понимаю

я пытался но в таком случае когда делаю запись в базу выходит ошибка

2024-09-25 19:40 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    public void addUsersFromFile(InputStream fileStream) throws IOException {
оно в глобал ексепшн хэндлере будет обрабатываться,

2024-09-25 19:45 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/mapper/user/UserMapper.java
> +        }
я тебя не понял, что ты имеешь ввиду?

2024-09-25 20:03 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    public void addUsersFromFile(InputStream fileStream) throws IOException {
Его не надо для этого прокидывать наверх

2024-09-25 20:08 UTC, NurseyitTursunkulov commented on src/main/java/school/faang/user_service/entity/student/PreviousEducation.java
> +    private Integer completionYear;
не могу поменять название, конвертация поломается

2024-09-27 07:31 UTC, mikhailov26 requested changes

2024-09-27 07:31 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
>  @Transactional(readOnly = true)
Убрать аннотацию, в чате писал по этому поводу

2024-09-27 07:31 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/util/CsvParserImpl.java
в пакете util сделать отдельный пакет под названием impl, и туда добавлять имплементации, данный подход применить ко всему

2024-09-27 07:31 UTC, mikhailov26 commented on src/test/java/school/faang/user_service/util/CsvParserTest.java
> +    }
Дублирование кода, это не допустимо, в одном из классов сделать методы public и сделать вызовы

2024-09-27 07:33 UTC, mikhailov26 commented
Разобраться с неймингом сущностей дто, не понятно что есть что. Entity подразумевает использование использование одноимённой аннотации над классом, а дто должно в имени класса иметь приписку дто

2024-09-27 13:14 UTC, NurseyitTursunkulov commented
> Разобраться с неймингом сущностей дто, не понятно что есть что. Entity подразумевает использование использование одноимённой аннотации над классом, а дто должно в имени класса иметь приписку дто

классы для парснига CSV не могут быть переименованы, в противном случае вылетает ошибка

2024-09-29 14:03 UTC, mikhailov26 approved these changes

2024-09-29 14:05 UTC, mikhailov26 approved these changes

2024-09-29 14:06 UTC, mikhailov26 commented
Решай конфликты и можешь мержить

2024-10-02 12:45 UTC, merged