BJS2-26859 - Default avatar for user during registration
CorporationX/user_service pull request #1595
Opened 2024-09-25 23:07 UTC by mrkorolev

2024-09-26 08:54 UTC, Alginin reviewed
Все супер! Можно добавить логирование для ключевых операций.

2024-09-26 08:54 UTC, Alginin commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    @Transactional
Стоит ли использовать эту аннотацию при работе с AmazonS3?

2024-09-26 08:54 UTC, Alginin commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    public String uploadFile(String fileName, InputStream data, ObjectMetadata metadata, Long userId) {
Проверку входных данных (на null например) здесь реализовывать не нужно?

2024-09-26 10:38 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/util/AvatarApiService.java
> +    private final String BASE_PARAMS = "scale=50&backgroundType=gradientLinear&radius=50";
Мб стоит положить эти значения в application.yaml?

2024-09-26 10:38 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/util/AvatarApiService.java
> +    public byte[] getDefaultAvatar(String username) {
А что происходит если сторонний сервис не возвращает тебе изображение после заданного тайм-аута?

2024-09-26 10:38 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +        return s3Client.putObject(request).getContentMd5();
1. Ты можешь передать в метод putObject, все аргументы, которые передаешь PutObjectRequest
2. @20cognosce Что мы в итоге должны сохранять в Postgres?

2024-09-26 10:38 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +    private String region;
@20cognosce Как лучше добавлять значения из yaml? Через поле или через конструктор?

2024-09-26 10:38 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public UserDto uploadFile(@PathVariable("user-id") Long userId,
Я бы назвал uploadProfileImage

2024-09-26 17:31 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    @Transactional
@20cognosce

2024-09-29 16:15 UTC, 20cognosce requested changes
Пахнёт это всё нерабочим кодом каким-то

Переделать на Minio, если не можешь в реальный Amazon S3 сохранить файл

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/UserServiceApplication.java
> +        return new RestTemplate();
?

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +    private String region;
Так через поле - вполне норм
Но вообще, чем больше у вас проверок на пустые значения - тем лучше, если на конструкторе из-за null в каком-то параметра бы падала сборка, то это было бы отлично

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    public S3ServiceImpl(@Value("${services.s3.bucketName}") String bucketName, AmazonS3 s3Client) {
О нет, никаких таких Autowired

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +        throw new UnsupportedOperationException("Not supported yet.");
Не понял, а как тогда получить аватарку

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    @Transactional
На сетевые запросы она работать конечно не будет, но для взаимодействия с базой - вполне уместна

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/util/AvatarApiService.java
> +                "scale=50&backgroundType=gradientLinear&radius=50&seed=" + username;
В application.yaml

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/util/AvatarApiService.java
> +            return Optional.ofNullable(data);
че, почему null? 
Сразу ошибку кидай
Не надо опшинал отдавать

И почему массив байт, мультипарта нет?

2024-09-29 16:15 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/user/UserServiceTest.java
> +package school.faang.user_service.service.user;
Где тесты, Лебовски?

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        String fileKey = s3Service.uploadFile(new ByteArrayInputStream(fileBytes), metadata, folder, toUpdate.getId());
ГДЕ ТЫ ЗАКРЫЛ ПОТОК?
будет утечка памяти

2024-09-29 16:15 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +        s3Client.putObject(bucketName, fileKey, data, metadata);
Так я не понял, у тебя Amazon или Minio?
Что это за амазон такой на локалхосте???

2024-10-06 19:47 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +        throw new UnsupportedOperationException("Not supported yet.");
@20cognosce Так написал потому, что это уже не моя задача. Мне нужно определить набор действий, который бы потом расширяли. В рамках текущей задачи мне этот метод не нужен - зато когда человек будет его писать он будет знать что и как ему возвращать. Это считается хорошей практикой если не хочешь писать имплементацию метода в текущий момент

2024-10-09 13:44 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/util/AvatarApiService.java
> +            return Optional.ofNullable(data);
@20cognosce Я искал как это сделать, но не нашел - кто то на stack overflow пишет имплементить MultipartFile, как по мне лучше кинуть массив байтов (для формирования metadata тоже подойдет)

2024-10-09 21:03 UTC, 20cognosce requested changes

2024-10-09 21:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/advice/ControllerAdvice.java
> +        }
Используй мапу

2024-10-09 21:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/avatar_api/AvatarApiService.java
> +    private final RestTemplate restTemplate;
Лучше бы в конструкторе проверку на null делать у проперти

2024-10-09 21:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        generateAndSaveDefaultAvatar(saved);
Это всё равно внутри транзакции

Не то что она вредна, она просто бесполезна
Ты тут делаешь только save у репозитория, нечего в транзакцию оборачивать

2024-10-09 21:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        generateAndSaveDefaultAvatar(saved);
Хотя не, ты два раза сейв делаешь
Нуууу, тогда вызывай generateAndSaveDefaultAvatar асинхронно, и в нем обновляй аватар у юзера

2024-10-09 21:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        generateAndSaveDefaultAvatar(saved);
Реально, а зачем ты два раза сохраняешь юзера, пока у него аватарки еще нет дефолтной

2024-10-09 21:03 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        generateAndSaveDefaultAvatar(saved);
В общем два стула
1. Если сохраняешь сначала без авы - то апдейт авы асинхронно делать
2. Сразу получать аву и сохранить один раз

2024-10-09 21:05 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        generateAndSaveDefaultAvatar(saved);
@20cognosce Я делал это для того, чтобы в fileKey присутствовал id юзера. Для уникального fileKey.

2024-10-10 11:38 UTC, 20cognosce approved these changes

2024-10-10 11:38 UTC, merged