Обработчик исключений в user_service
CorporationX/user_service pull request #1600
Opened 2024-09-27 12:44 UTC by vestmen

2024-09-27 18:16 UTC, evgenywork commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handleBadRequestException(BadRequestException ex) {
log.error не хватает

2024-09-27 18:16 UTC, evgenywork commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +        log.error("ResourceNotFoundException occurred: {}", ex.getMessage());
log.error("ResourceNotFoundException occurred: {}", ex.getMessage(), ex)
после видео про исключения , думаю надо добавить весть стек трейс (относится ко всем исключениям ниже), чтобы потом легче определить , где оно стрельнуло

2024-09-27 18:16 UTC, evgenywork commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
>                      log.error("Request with id {} not found", id);
А ты специально не логировал BadRequestException в GlobalExceptionHandler ? 
Не понял , почему там нельзя было сделать

2024-09-29 14:06 UTC, ilu23ilu23 reviewed
На мой взгляд всё здорово

2024-09-29 15:39 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestService.java
>                      log.error("Request with id {} not found", id);
пропустил, уже поправил

2024-09-29 15:39 UTC, vestmen commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    public ErrorResponse handleBadRequestException(BadRequestException ex) {
поправил, спасибо)

2024-09-29 15:42 UTC, vestmen commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +        log.error("ResourceNotFoundException occurred: {}", ex.getMessage());
не думаю, что целесообразно в логи записывать весь стэк трейс, да и в видео там записывалось только, что ошибка вылетела и само сообщение

2024-09-30 19:50 UTC, 20cognosce requested changes

2024-09-30 19:50 UTC, 20cognosce commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    }
У тебя это всё - дублирование кода
ты пишешь лог и делаешь return ErrorResponse, почему одно и то же повторяется 20 раз?

Выполнить рефакторинг, обобщающий это всё

2024-09-30 19:50 UTC, 20cognosce commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    }
Можешь по коду ошибок обобщить исключения

Или еще что придумать

2024-09-30 19:50 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +            throw new BadRequestException(REQUEST_TO_HIMSELF);
Нет, ошибка должна нести конкретику
Таким подходом любую ошибку можно назвать "SomeError" и везде её кидать, нет
Создавай кастомные ошибки тогда, если заготовленных нет

2024-09-30 19:50 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +            throw new BadRequestException(ONCE_EVERY_THREE_MONTHS);
Нет

2024-09-30 19:50 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +            throw new BadRequestException(ONCE_EVERY_THREE_MONTHS);
BadRequest - это вообще уровень http кода, почему это в бизнесовом коде фигурирует

2024-10-01 06:11 UTC, vestmen commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +    }
переделал

2024-10-01 06:42 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +            throw new BadRequestException(REQUEST_TO_HIMSELF);
переделал

2024-10-01 06:42 UTC, vestmen commented on src/main/java/school/faang/user_service/service/mentorship_request/MentorshipRequestParametersChecker.java
> +            throw new BadRequestException(ONCE_EVERY_THREE_MONTHS);
переделал

2024-10-02 10:44 UTC, 20cognosce approved these changes

2024-10-02 10:44 UTC, merged