BJS2 26121 - Парсим файлы пользователей
CorporationX/user_service pull request #1601
Opened 2024-09-27 20:50 UTC by GusevVrn

2024-09-29 04:06 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                    users.forEach(u -> response.add(userMapper.toDto(u)));
я бы полностью писала, а не просто буковку "u", слово user не такое уж и большое))

2024-09-29 04:07 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        users.forEach(u -> u.setPassword(u.getUsername()));
И тут тож самое с "u"

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +            //Жесткий костыль, я не понимаю откуда в начале строки появились символы ï»¿
Что-то на юникодском) Такс, но если в след таблице будет не 3 символа, а 4, то костыль не будет работать. Мб можно решить эту проблему через регулярное выражение, которое будет содержать ток буквы, цифры и символы, которые тебе нужны. Пока ничего больше в голову не пришло...

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +
лишний отступ

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +            throw new RuntimeException(e);
Мб вместо просто new RuntimeException(e) сделаем new RuntimeException("Тут напишем на каком этапе произошла ошибка", e.getCause() или гетмесадж)

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +            throw new RuntimeException(e);
Тут можно тоже сделать как выше написала

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/mapper/user/UserMapperTest.java
> +    private final static int SIZE_USER_DTO_LIST = 2;
Нужно поменять местами - сначала static, а потом final

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/mapper/user/UserMapperTest.java
> +        private final static String FIRST_NAME = "John";
Тут тоже как выше написала

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/service/country/CountryServiceTest.java
> +        @DisplayName("WhenEntityFoundThenNotThrownException")
Забыл откорректировать DisplayName

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/service/country/CountryServiceTest.java
> +        @DisplayName("WhenEntityIsCorrectThenNotThrownException")
Тут тоже

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/service/country/CountryServiceTest.java
> +        @DisplayName("WhenEntityNotFoundThenThrowEntityNotFoundException")
и тут

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/service/country/CountryServiceTest.java
> +        void whenEntityNotFoundThenThrowsEntityNotFoundException() {
В части названия метода - нам обязательно писать EntityNotFoundException? Мы же можем просто написать whenEntityNotFoundThenThrowsException - так букв меньше и читать проще. Думаю, что в названии метода нам не обязательно знать какая именно ошибка упадет при пустой энтити

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/service/country/CountryServiceTest.java
> +        void whenEntityFoundThenNotThrownException() {
Мб вместо ThenNotThrownException писать что-то типо ThenSuccess??

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/util/file/CsvUtilTest.java
> +    private final static String FIRST_NAME = "John";
Нужно поменять местами - сначала static, а потом final

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/util/file/CsvUtilTest.java
> +    void whenCorrectDataAfterParsingThenAllFieldsAreEqualsToExpected() {
Как по мне - оч много букв в названии и из-за этого сложно читать. + Лично у меня невольно мысли, что щас в методе будет ультра сложная логика и не хочется в него лезть)) Если из названия можно выкинуть пару слов, то я бы это сделала)

2024-09-29 06:13 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/pojo/student/Education.java
> +    @NotNull
Разве @NotNull может быть у примитивов? Тут должны быть @Min и @Max

2024-09-29 06:40 UTC, Silencemess1ah reviewed
Гут Джоб!

2024-09-29 06:40 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +        log.info("Start parseCsvMultipartFile() - {}", multipartFile.getOriginalFilename());
multipartFile.getOriginalFilename() - мож в переменную вынести в начале метода? а то много используется проще было бы String fileName - и  везде подставлять

2024-09-29 06:40 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +            //Жесткий костыль, я не понимаю откуда в начале строки появились символы ï»¿
https://www.baeldung.com/java-remove-byte-order-mask-chars-file  Паш это норма что они есть, это BOM, он содержит метки последовательности байтов по файлу как я понял он много где проявляется, тут несколько вариантов решений как со сторонними библиотеками так и без, не знаю поможет ли статья но короче вот тут несколько вариантов решений, если просто почитать про это то загугли BOM Utf-8

2024-09-29 06:40 UTC, Silencemess1ah commented on src/test/java/school/faang/user_service/mapper/user/UserMapperTest.java
> +    private final static int SIZE_USER_DTO_LIST = 2;
Разницы так то никакой) разве что **_принято_** да и в глаза бросается, но мне кажется это лишнее, лучше б вон про хедеры решить там вообще копать и копать походу

2024-09-29 10:29 UTC, GusevVrn commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +        log.info("Start parseCsvMultipartFile() - {}", multipartFile.getOriginalFilename());
Да, тоже думал об этом, но у тебя эта переменная уже лежит в объекте, зачем под нее лишнюю память выделять.

2024-09-29 19:10 UTC, mysosnovskaya requested changes

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +@Slf4j
Лишняя

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping("/parsing")
Может быть это upload? Загрузить пользователей из файла

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/user/UserMapper.java
> +        if (person.getContactInfo().getAddress().getState() != null &&
`person.getContactInfo().getAddress().getState()` в отдельную переменную. С остальным аналогично. Читаемость кода повысится значительно. А вот если ты за память переживаешь, то это зря. Даже +100 локальных переменных никак не скажутся на общем потреблении памяти, это пренебрежимо малый объем. Не нужно писать код, экономя каждую переменную, так ты сделаешь его только менее читаемым

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/user/UserMapper.java
> +        return sb.toString();
Вот это ты заморочился)

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/pojo/student/Address.java
> +    @JsonProperty("street")
А зачем ты подписываешь JsonProperty, если оно совпадает с названием поля?

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/pojo/student/PreviousEducation.java
> +    private Map<String, Object> additionalProperties = new LinkedHashMap<String, Object>();
А ты этим полем хоть где-то пользуешься? По-моему оно лишнее во всех классах

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        CompletableFuture.supplyAsync(() -> csvUtil.parseCsvMultipartFile(multipartFile, Person.class))
Расскажи в комментариях, почему ты здесь используешь CompletableFuture, чем это оправдано

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                                setDefaultPassword(users);
Тут что-то странное) Ты проходишь по users и на каждой итерации делаешь  setDefaultPassword(users) всем пользователям из списка, а не одному конкретному

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                    userRepository.saveAll(users);
Один saveAll на всех пользователей вместо save на каждого - это хорошо, молодец 👍

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                                    user.setCountry(country);
Дублирующаяся строчка, её можно вынести за пределы try-catch

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                                    Country country = countryService.findCountryByTitle(user.getCountry().getTitle());
Вообще тебе было бы лучше, если бы findCountryByTitle вернул Optional. Может быть тут лучше к репозиторию обратиться? Тогда через orElse можно сохранить страну

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                    users.parallelStream()
Что именно ты хочешь сделать быстрее, используя здесь parallelStream?

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +    private static final CsvMapper csvMapper = new CsvMapper();
На CsvMapper нужен отдельный бин

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +        log.info("Start parseCsvMultipartFile() - {}", multipartFile.getOriginalFilename());
Про использование памяти написала в другом комментарии)

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +                linesParsed++;
Это ещё не parsed, это мы только прочитали)

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +    public <T> List<T> parseCsvToPojo(MultipartFile multipartFile, @Valid Class<T> clazz) {
Здесь точно нужна Valid?

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +        List<CompletableFuture<T>> completableFuture = new ArrayList<>();
completableFutures (s в конце, т.к. множественное число)

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +        List<T> result = completableFuture.stream()
Вот тут completableFutures оправданно использовать)

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/resources/files/students.csv
> +Michael,Johnson,1988,Group A,246813,michaeljohnson@example.com,1112223333,Second Street,Miami,FL,Russia,67890,Law,2021,Corporate Law,3.7,Graduated,2019-01-01,2021-12-31,Bachelor,DEF University,2019,t
Почему Майами стало Россией? =))

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
В строке 79 вместо withHeader нужно написать withoutHeader и всё заработает)

2024-09-29 19:10 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +    private <T> T parseCsvLineToPojo(String line, Class<T> clazz, CsvSchema csvSchema) {
Хорошо с дженериками, молодец 👍

2024-09-30 21:20 UTC, GusevVrn commented on src/main/java/school/faang/user_service/pojo/student/Address.java
> +    @JsonProperty("street")
Проверял разные варианты работы парсинга, в момент отчаяния добавил и не удалил.

2024-09-30 21:21 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        CompletableFuture.supplyAsync(() -> csvUtil.parseCsvMultipartFile(multipartFile, Person.class))
Не знаю, я парсинг через него написал и потом все как в тумане)
Вообще да, я еще когда писал думал что сюда будут вопросы. Наверное если бы мы возвращали CompletableFuture то был бы резон.

2024-09-30 21:21 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                                    Country country = countryService.findCountryByTitle(user.getCountry().getTitle());
Я подумал что к findCountryByTitle будут чаще обращаться чтоб получить страну. И возвращать именно страну намного лучше. 
Ну и особо логику никакую в другой сервис не хотелось передавать.

2024-09-30 21:21 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +                    users.parallelStream()
Пройтись быстрее по списку в несколько потоков. 
Тут особо сложной логики нету где был бы точный блок для использования parallelStream, поэтому решил использовать.

2024-09-30 21:21 UTC, GusevVrn commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
Ну чем дальше, тем больше я сомневаюсь в своей адекватности)
Все спарсил, тест на доп строку написал, тесты проходят. 
Но новые приколы появились:
![image](https://github.com/user-attachments/assets/44c95323-70e6-484a-8719-b4da911fab77)

2024-09-30 21:26 UTC, GusevVrn commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
Нашел, я вот так делал
```
    private <T> T parseCsvLineToPojo(String line, Class<T> clazz, CsvSchema csvSchema) {
        try {
            return csvMapper.readerFor(clazz).with(CsvSchema.emptySchema().withHeader()).readValue(line);
        } catch (IOException e) {
            throw new ParseException(e.getMessage());
        }
    }
```
И тогда он мне ошибку вываливал. 
Я решил сегодняшний момент просто списать на невнимательность, т.к. проверял во время работы за 10 минут до ретро.

2024-09-30 21:26 UTC, GusevVrn commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
Откуда null появился не понимаю, в тесте выводил, он там John выводит.

2024-10-01 19:29 UTC, mysosnovskaya requested changes

2024-10-01 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/country/CountryService.java
> +            country = findCountryByTitle(title);
Странно генерировать исключение и тут же его отлавливать. Думаю, здесь тебе не нужно переиспользовать метод findCountryByTitle. Возьми Optional от countryRepository.findByTitle(title) и проверь его на пустоту. В зависимости от этого сделай разные действия. Так будет симпатичнее :) Ну и ещё аргумент: генерация и отлов исключения это более тяжелая операция, чем if. Нам это вряд ли будет заметно в коде, но ты же любишь думать о таком =) Ну а на самом деле если есть выбор между
- попробовать что-то сделать, ожидая, что если действие не удалось, то вернется исключение, и отловить это исключение
- заранее через if убедиться, что операция будет успешной
то предпочтение всегда отдают второму. У тебя ситуация немного другая, но тоже лучше обойтись без генерации и отлова исключения

2024-10-01 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/country/CountryService.java
> +    public Country findCountryAndSaveIfNotExists(String title) {
Страшненькое название, но я пока тоже лучше придумать не могу

2024-10-01 19:29 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/util/file/CsvUtil.java
> +            return csvMapper.readerFor(clazz).with(csvSchema).readValue(line);
То, что ты пишешь про null, очень бы хотелось понять и пофиксить. Посмотри ещё со свежей головой, может в дебаге заметишь какие-то странности с headerLine или line.
Я тоже посмотрела, как могла. Ошибок не нашла. Поэтому если тоже не найдешь, то смержим

2024-10-06 19:57 UTC, GusevVrn commented
zwnbsp- чтоб его

2024-10-06 22:35 UTC, mysosnovskaya approved these changes

2024-10-06 22:35 UTC, merged