task BJS2-27433 solution v1
CorporationX/user_service pull request #1602
Opened 2024-09-27 22:06 UTC by wmwmaks

2024-09-28 04:21 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +@Data
Посоветовал бы заменить аннотации @Component на @Configuration. Также аннотацию @Data на @Getter, так как в коде кто-то может поля этого класса через сеттер изменить, и если выйдет ошибка, то смотря на application.yaml мы будем думать что с конфигом всё в порядке)

2024-09-28 04:28 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
Может создавать только бин s3Client? Так тебе нужно будет инжектить только этот бин, а не весь конфиг)

2024-09-28 04:31 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    private static final double MAX_AVATAR_SIZE = 5_242_880L;
Порекомендовал бы также вынести все константы в отдельный класс или в application.yaml, так как если потом придётся изменять размеры файла или названия папок, не пришлось по всем классам искать и менять)

2024-09-28 04:42 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    private final S3ServiceImpl s3ServiceImpl;
Тут наверное лучше инжектить интерфейс S3Service?)

2024-09-28 04:45 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
Тут можно сразу юзера возвращать и выбрасывать исключение если он не найден, чтобы потом не писать user.get())

2024-09-28 04:55 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        String fileId = size.equals("small") ? userProfilePic.getSmallFileId() : userProfilePic.getFileId();
Может size переделать в enum, как думаешь? Просто сейчас, если я не ошибаюсь, в size могут передать любую строку и получить большое фото)

2024-09-28 05:00 UTC, ArstanSubanov commented on src/main/resources/application.yaml
> +    port: 8080
payment-service уже же есть, и мы находимся в user-service,  или ты где-то используешь их? Я просто не заметил)

2024-09-28 05:06 UTC, ArstanSubanov approved these changes
Круто) У меня задача не по s3, не могу сказать конкретно есть ли ошибки по нему, но в целом выглядит правильно)

2024-09-28 05:15 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
согласен с Арстаном

2024-09-28 07:45 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
В репозитории метод возвращает Optional<T> findById(ID id);. 
Юзера не даст вернуть

2024-09-28 07:46 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        String fileId = size.equals("small") ? userProfilePic.getSmallFileId() : userProfilePic.getFileId();
С одной стороны да, а с другой мне без разницы, если с любой другой строкой вернет большое фото. Главное, что при запросе маленького вернется маленькое. А что не маленькое - большое. Пока третьего варианта не дано, будто бы и нет смысла усложнять.

2024-09-28 07:47 UTC, wmwmaks commented on src/main/resources/application.yaml
> +    port: 8080
Я скопировал эти настройки из project-service. Там указано так. Может, это чуть-чуть забегает вперед, но будто бы почему и нет.

2024-09-28 07:47 UTC, wmwmaks commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
Не совсем понял, как вы предлагаете сделать. Распишите подробнее, пожалуйста

2024-09-28 07:48 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    private static final double MAX_AVATAR_SIZE = 5_242_880L;
Вообще это как-то можно вынести в настройки спринга в yaml файле, чтобы это сам tomcat ограничивал. Я хотел бы так сделать. Маша, что думаешь?

2024-09-28 07:48 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    private final S3ServiceImpl s3ServiceImpl;
Да, исправлю

2024-09-28 09:28 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
сейчас ты в коде имеешь зависимость в виде объекта конфигурации,а через него уже вызываешь методы s3Client, а, как по мне, лучше бы было иметь зависимость в виде уже сконфигурированного бина и вызывать методы сразу у него. вместо setUp(), можно написать метод, в котором будет все точно также, только он будет возвращать s3Client, и на нем будет висеть аннотация @Bean.

2024-09-28 09:28 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
что-то, типа такого 
```

2024-09-28 09:30 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
и потом в s3 service ты его также можешь инжектить и пользоваться уже сконфигурированным объектом!

2024-09-28 14:01 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
Сделай типо UserDto user = userRepository.findById(userdId).orElseThrow()

2024-09-28 14:05 UTC, SharkB38 approved these changes
Круто, единственное, что я может быть вынес логирование ошибок в ExceptionHandler, но это так

2024-09-28 15:33 UTC, wmwmaks commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
Понял, спасибо! Пока оставлю так. Дождемся мнения Маши есть ли смысл переделывать. Кроме эстетики есть ли в это практическая польза.

2024-09-28 15:59 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        String fileId = size.equals("small") ? userProfilePic.getSmallFileId() : userProfilePic.getFileId();
Не буду настаивать) Но учти, что юзер может передать small с ошибкой или с пробелом, или с верхним регистром. А потом он придёт к разработчику и будет утверждать, что ввёл всё правильно, но не получает маленькое фото)

2024-09-28 19:48 UTC, RuslanIovlev commented
Крутая и объемная работа, многого правда еще сам не понимаю))

2024-09-28 19:48 UTC, RuslanIovlev approved these changes

2024-09-29 07:04 UTC, wmwmaks commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +@Data
Подсматривал у наших более опытных коллег, у них так было. Звучит логично оставить только getter. Дождусь от Маши ревью. Частично согласен с тобой, но не уверен)

2024-09-29 07:08 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        String fileId = size.equals("small") ? userProfilePic.getSmallFileId() : userProfilePic.getFileId();
Может, это как-то на фронте отработать можно. Чтобы было 2 кнопки на выбор после нажатия "скачать", которые будут автоматически вставлять в url размер картинки. 
Или на весь экран написать красными буквами "для скачивания маленькой картинки пишите small и !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

2024-09-29 18:17 UTC, mysosnovskaya requested changes

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +@Data
Вообще ни Component, ни Configuration должна быть не нужна. ConfigurationProperties уже достаточно, чтобы спринг понял, что нам нужен этот бин. Аннотация ConfigurationPropertiesScan также должна быть не нужна

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +@Data
С Data тоже согласна

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        s3Client = AmazonS3ClientBuilder
Однозначно да. Это не эстетика, это разделение обязанностей. Данный класс предназначен только для хранения параметров, полученных из yaml файла. Бин AmazonS3 лучше создавать вообще в отдельном классе. Вот как написал Виталя, только в метод передать ещё и параметры:
`public AmazonS3 amazonS3(S3Params s3Params) {`

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +        log.info("Connected to AmazonS3 system.");
Это не надо =)

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    private static final double MAX_AVATAR_SIZE = 5_242_880L;
Однозначно да. Почитай про аннотацию Value

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/FileUploadException.java
> +public class FileUploadException extends RuntimeException {
А обработчик на эти три исключения будет? И если ты предполагаешь на все три исключения одинаковый статус код, то достаточно оставить одно исключение)

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    private final S3Config s3Config;
А сюда нужно внедрять клиента к AmazonS3

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +            log.error("Failed to upload file to S3 with key: {}", key, e);
Лучше такое сообщение написать в исключении, а логирование сделать в GlobalExceptionHandler

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3ServiceMock.java
> +public class S3ServiceMock {
Для чего?

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<byte[]> getUserAvatar(@PathVariable long userId, @RequestParam String size) {
Лучше ResponseEntity<Resource>
https://genuinecoder.com/downloading-a-file-from-spring-controller-with-spring-boot/

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        String fileId = size.equals("small") ? userProfilePic.getSmallFileId() : userProfilePic.getFileId();
Если варианта только два, то не лучше ли подойдет true/false? Но однозначно простое строчное "small" оставлять не нужно)

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    port: 8080
Согласна с Арстаном:
1. Настройки для payment-service уже есть в этом же yaml файле, только выше (строки 40-42)
2. user-service не нужен, т.к. мы уже находимся в нем и нам гарантированно не нужно обращаться из user-service в user-service

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/image/BufferedImagesHolder.java
> +public class BufferedImagesHolder {
Мне понравилась твоя идея с холдером 👍

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/image/BufferedImagesHolder.java
> +            setPics(originalPic, originalWidth);
А можно просто: `Math.max(originalWidth, originalHeight)`?

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    public UserDto uploadUserAvatar(Long userId, BufferedImage uploadedImage) {
Вот тут точно транзакция понадобится)

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
Лучше через .orElseThrow, как в предыдущем методе

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +        Optional<User> user = userRepository.findById(userId);
.orElseThrow

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +            log.error("User with id {} not found", userId);
Неверное сообщение. И повторю, логи здесь не нужны, т.к. логирование ошибок должно быть в exception handler

2024-09-29 18:17 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/image/ImageProcessor.java
> +    public static final String FORMAT_NAME = "jpeg";
Предложу тоже в настройки вынести

2024-09-30 08:17 UTC, wmwmaks commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +@Data
Только с @ConfigurationProperties(prefix = "services.s3") ошибку выдает.

2024-09-30 08:52 UTC, wmwmaks commented on src/main/resources/application.yaml
> +    port: 8080
До меня дошло о чем речь, согласен. Уберу

2024-09-30 20:43 UTC, mysosnovskaya requested changes

2024-09-30 20:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/s3/S3Params.java
> +    @Value("${services.s3.accessKey}")
Надо сделать так, чтобы работало через
@ConfigurationProperties(prefix = "services.s3")
Какая у тебя ошибка? Там не только она нужна, ещё сеттеры или конструктор понадобятся

2024-09-30 20:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +            FileOperationException.class
FileOperationException уже является дааальним родственником Throwable, так что он всё равно попадет сюда, можно не писать его дополнительно

2024-09-30 20:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<byte[]> getUserAvatar(@PathVariable long userId, @RequestParam AvatarSize size) {
Гитхаб съел часть моего предыдущего комментария здесь) Имела в виду, лучше `ResponseEntity<Resource>`, как в прикрепленной статье. Рекомендую заменить byte[] на Resource

2024-10-01 06:54 UTC, wmwmaks commented on src/main/java/school/faang/user_service/config/s3/S3Params.java
> +    @Value("${services.s3.accessKey}")
Теперь запустилось. Видимо, в предыдущем варианте, когда все в одном месте было, что-то мешало. 
Правильно, что в этот класс setter добавляю? Без этого spring не может поля заполнить и ошибку выдает при запуске приложения. Так должно быть?

2024-10-01 08:47 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/s3/S3Params.java
> +    @Value("${services.s3.accessKey}")
Да, всё верно

2024-10-01 08:47 UTC, mysosnovskaya approved these changes

2024-10-01 08:47 UTC, merged

2024-10-01 17:32 UTC, SharkB38 commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +@Data
``Вообще ни Component, ни Configuration должна быть не нужна. ConfigurationProperties уже достаточно, чтобы спринг понял, что нам нужен этот бин. Аннотация ConfigurationPropertiesScan также должна быть не нужна``
Все таки ConfigurationPropertiesScan нужна, , ConfigurationProperties сам по себе не является бином же