Feature bjs2 27423
CorporationX/user_service pull request #1604
Opened 2024-09-28 13:55 UTC by KarabbasBarabas

2024-09-28 14:42 UTC, SharkB38 approved these changes

2024-09-28 14:42 UTC, SharkB38 commented on src/main/java/school/faang/user_service/config/S3Config.java
> +    private String endpoint;
Я бы перед аннотациями строчку отступал

2024-09-28 14:42 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        }
А почему бы сразу ошибку не кидать через orElseThrow?

2024-09-28 14:42 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        log.info("Для пользователя с id = " + userId + "добавлен аватар по-умолчанию" + key);
C логами на русском бывают проблемы, мы пришли к решению писать их на англ

2024-09-28 14:43 UTC, SharkB38 commented
В целом круто выглядит, оставил пару своих предложений.

2024-09-28 16:18 UTC, ArstanSubanov approved these changes
👍Работа класс) Только проверь пожалуйста билд, там кажется какой-то тест валится

2024-09-28 20:12 UTC, RuslanIovlev approved these changes

2024-09-29 06:44 UTC, wmwmaks commented on src/main/java/school/faang/user_service/controller/avatar/AvatarController.java
> +
лишняя пустая строка

2024-09-29 06:45 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +    @Value("${services.s3.bucketName}")
Присоединюсь, перед аннотациями мы обычно отступ делаем. Не критично, но, вроде, к такому стилю пришли общими рассуждениями

2024-09-29 06:46 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/avatar/AvatarServiceTest.java
> +
несколько лишних пустых строк

2024-09-29 06:47 UTC, wmwmaks commented on src/test/java/school/faang/user_service/service/avatar/AvatarServiceTest.java
> +    @InjectMocks
а тут не хватает отступа. Но опять же не критично. Просто нас Маша так натренировала 😅

2024-09-29 06:48 UTC, wmwmaks approved these changes
Хорошая работа, пару комментариев оставил. С билдом что-то не так, CI ругается.

2024-09-30 17:01 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/config/S3Config.java
> +    private String endpoint;
мне так норм, в intellejIdea визуально отступ есть

2024-09-30 17:05 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        }
согласен, поправил

2024-09-30 17:05 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        log.info("Для пользователя с id = " + userId + "добавлен аватар по-умолчанию" + key);
ок, потом на англ буду писать

2024-09-30 17:06 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/controller/avatar/AvatarController.java
> +
поправил

2024-09-30 17:07 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +    @Value("${services.s3.bucketName}")
написал в предыдущем комментарии

2024-09-30 17:07 UTC, KarabbasBarabas commented on src/test/java/school/faang/user_service/service/avatar/AvatarServiceTest.java
> +
поправил

2024-09-30 17:11 UTC, KarabbasBarabas commented
тесты поправил, сейчас ошибок нет

2024-10-01 09:43 UTC, mysosnovskaya requested changes

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/S3Config.java
> +@Configuration
Лучше сделать через ConfigurationProperties, она как раз для таких классов с параметрами

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/S3Config.java
> +    public AmazonS3 s3Client() {
Я бы разделила на два класса: AwsS3Params (с параметрами из yaml) и AwsS3Config (с нужными бинами). Максим в своем ПР делал такое же, можешь посмотреть
https://github.com/CorporationX/user_service/pull/1602/files

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/avatar/AvatarController.java
> +    public void  createDefaultAvatarForUser(@PathVariable("userId") @Min(1) long userId) {
По условию задачи аватар нужно назначать сразу при регистрации. Нужно добавить эндпоинт по регистрации пользователя и сразу вместе с регистрацией генерировать ему аватарку

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +    @Value("${services.s3.bucketName}")
В IDEA действительно визуально эти поля отделяются, но мы часто смотрим код не в IDEA (вот например на ревью). Тем более если это общий стиль команды, о котором договорились. Нужно исправить. В других классах тоже

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        // получение аватара
Комментарии такого рода в коде говорят о том, что данный код можно выделить в отдельный приватный метод с понятным названием, которое заменит комментарий. Как правило, вот такие комментарии говорят о неверной декомпозии кода (а точнее об её отсутствии). Поэтому метод createDefaultAvatarForUser нужно переработать, выделив часть его логики в приватные методы и удалив все поясняющие комментарии

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +                    log.error(message);
Лог не нужен, т.к. логирование произойдет в GlobalExceptionHandler при перехвате этого исключения 
https://github.com/CorporationX/user_service/blob/hydra-master-stream6/src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java#L29

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +            log.error(message);
Аналогично

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        for (int j = 0; j < 6; j ++) {
Это ты классно придумал =)

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        String key = "default_avatar_for_user_" + userId + "_" + System.currentTimeMillis();
Вот это "default_avatar_for_user_" можно вынести в параметры в yaml или хотя бы в константы

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        log.info("Для пользователя с id = " + userId + "добавлен аватар по-умолчанию" + key);
Нужно исправить сейчас, т.к. на проекте уже принят такой стиль

2024-10-01 09:43 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        ObjectMetadata metadata = new ObjectMetadata();
В metadata нужно также сделать setContentLength и setContentType. Их ты можешь получить, если в DefaultAvatarClient будешь возвращать не byte[], а `ResponseEntity<byte[]>` - вот из ResponseEntity как раз и можно получить нужную информацию

2024-10-01 09:43 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/avatar/AvatarServiceTest.java
> +    @InjectMocks
Не критично, но я бы тоже добавила

2024-10-02 17:52 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/config/S3Config.java
> +@Configuration
понял, спасибо

2024-10-02 18:00 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/config/S3Config.java
> +    public AmazonS3 s3Client() {
поправил

2024-10-02 18:21 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/controller/avatar/AvatarController.java
> +    public void  createDefaultAvatarForUser(@PathVariable("userId") @Min(1) long userId) {
поправил

2024-10-02 18:28 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        // получение аватара
поправил, но я не понимаю, тогда в этом методе, если ещё вынести валидацию в отдельный метод, то будет просто вызов трёх других методов. Так и должно  быть?

2024-10-02 18:28 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +                    log.error(message);
не знал, спасибо!

2024-10-02 18:40 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +        String key = "default_avatar_for_user_" + userId + "_" + System.currentTimeMillis();
поправил

2024-10-02 18:41 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        ObjectMetadata metadata = new ObjectMetadata();
спасибо, не знал.
А как ты это поняла?

2024-10-02 18:52 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        ObjectMetadata metadata = new ObjectMetadata();
как лучше передать ContentLength и ContentType? - отдельными параметрами или через ResponseEntity<byte[]>?

2024-10-02 20:33 UTC, mysosnovskaya approved these changes
Аппрув поставила, осталось разрешить конфликты, с ними смержить не смогу

2024-10-02 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/avatar/AvatarService.java
> +    public void createDefaultAvatarForUser(long userId) {
Вот теперь хорошо. Валидацию я не стала бы никуда выносить, сейчас метод выглядит вполне понятно

2024-10-02 20:33 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        ObjectMetadata metadata = new ObjectMetadata();
Просто знала, что в ObjectMetadata есть такие методы)
Если параметра всего два, то можно и отдельными оставить, так выглядит логичнее.

2024-10-03 19:10 UTC, mysosnovskaya commented
CI не прошел, нужно поправить

2024-10-05 16:02 UTC, merged