Unicorn master stream6 feature bjs2 26118
CorporationX/user_service pull request #1607
Opened 2024-09-28 18:28 UTC by StepnovaVarvara

2024-09-29 12:06 UTC, segaTk commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +
Открытый вопрос: так как Паша уже реализовал класс s3 по генерации аватарок, может было бы удобно сделать интерфейс с методами и уже под конкретную нужду реализовывать интерфейс? Так как на данный момент там уже 100 строк кода

2024-09-29 12:06 UTC, segaTk commented on src/main/resources/application.yaml
> +    endpoint: http://localhost:9000
endpoints:
  - http://192.168.1.100:9000

2024-09-29 12:08 UTC, segaTk commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new SdkClientException("Failed to download picture", ex.getCause());
Почему уже тогда везде не использовать RuntimeException?

2024-09-29 18:41 UTC, mysosnovskaya requested changes

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PutMapping("/{userId}/avatar")
Почему решила использовать Put, а не Post?

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @ResponseStatus(HttpStatus.OK)
Это лишнее, по умолчанию будет OK

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<byte[]> downloadUserAvatar(@PathVariable Long userId) {
Решила не через ResponseEntity<Resource> делать? Почему?)

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return new ResponseEntity<>(img, HttpStatus.OK);
Лучше внутри try это сделать

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +
Хорошая идея, но ПР Паши ещё не смержен)

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new SdkClientException("Failed to download picture", ex.getCause());
Вообще не понимаю, зачем его перехватывать и посылать его же, но с другим сообщением. Тут можно либо вообще без catch обойтись, либо обернуть в какое-то другое (RuntimeException или своё собственное)

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new SdkClientException("Failed to delete picture", ex.getCause());
Аналогично

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserProfilePicService.java
> +        userService.saveUser(user);
А если у пользователя уже была аватарка и он её меняет, то нужно старую аватарку из s3 удалить

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +    @Value("${servlet.multipart.max-file-size}")
Молодец, что сделала это через отдельный параметр в yaml 👍

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +    public List<byte[]> changeFileScale(MultipartFile file) {
Это не ответственность валидатора. Валидатор только проверяет, но изменять он ничего не может. Эту логику по изменению масштаба нужно вынести в отдельный класс

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +        ByteArrayOutputStream stream = new ByteArrayOutputStream();
try-with-resources

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +        return stream.toByteArray();
Внутрь try

2024-09-29 18:41 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    endpoint: http://localhost:9000
Поясни, почему localhost не подойдет?

2024-09-29 18:41 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/validator/picture/PictureValidatorTest.java
> +        // TODO добавила setter в сущность, тк  иначе все время в тесте падала ошибка NullPointerException
Лучше добавить конструктор вместо сеттера, т.к. наличие сеттера влияет вообще на весь код =)

2024-09-29 19:23 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @ResponseStatus(HttpStatus.OK)
Учла

2024-09-29 19:27 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PutMapping("/{userId}/avatar")
Тк у нас Паша делает фичу с генерацией рандомной аватарки сразу при регистрации пользователя, то я подумала, что мы меняем, а не создаем

2024-09-29 19:28 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return new ResponseEntity<>(img, HttpStatus.OK);
А можешь объяснить почему так лучше, пожалуйста?

2024-09-29 19:30 UTC, segaTk commented on src/main/resources/application.yaml
> +    endpoint: http://localhost:9000
MinIO требуется IP-адрес, а не "localhost", он должен быть доступен с других устройств или сервисов в сетевом окружении. Использование IP-адреса гарантирует, что к MinIO смогут обращаться клиенты или приложения, работающие на разных машинах, в то время как "localhost" относится только к локальной машине. Это очень важно для распределенных приложений, где к MinIO могут обращаться несколько сервисов или пользователей по всей сети.

2024-09-29 19:38 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +    public List<byte[]> changeFileScale(MultipartFile file) {
Ожидала этот коммент)

2024-09-29 19:44 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/user/UserProfilePicService.java
> +        userService.saveUser(user);
В начале написания метода помнила об этом, а потом забыла))

2024-09-29 19:53 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new SdkClientException("Failed to download picture", ex.getCause());
Погодите, теперь я не понимаю!) Я вижу, что метод getObject может кинуть исключение SdkClientException, зачем кидать RuntimeException? Поменяла, но не понимаю почему так

2024-09-29 19:54 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new SdkClientException("Failed to delete picture", ex.getCause());
Поменяла, но не понимаю почему RuntimeException

2024-09-29 19:58 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +        ByteArrayOutputStream stream = new ByteArrayOutputStream();
Сделала

2024-09-29 19:59 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +        return stream.toByteArray();
Сделала

2024-09-29 20:02 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/validator/picture/PictureValidator.java
> +    @Value("${servlet.multipart.max-file-size}")
Сомневалась, что можно такое большое число писать в yaml. Дуамала, что нужно там указать 5МВ, а тут уже перемножать

2024-09-30 02:40 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +
Эмм.. Что-то я не оч поняла, что от меня требуется... Типо сделать интерфейс с методами Паши и моими, а в классе использовать уже только теметоды, что требуются мне по логике?

2024-09-30 02:48 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/validator/picture/PictureValidatorTest.java
> +        // TODO добавила setter в сущность, тк  иначе все время в тесте падала ошибка NullPointerException
Столько времени на это потратила... Спасибо!)

2024-09-30 02:55 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<byte[]> downloadUserAvatar(@PathVariable Long userId) {
Если ты про твою статью, то там было много кода и мне стало страшно))

2024-09-30 20:30 UTC, mysosnovskaya requested changes

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        byte[] img;
В идеале вот так)
```
        try {
            byte[] img = userProfilePicService.downloadUserAvatar(userId).readAllBytes();
            return new ResponseEntity<>(img, HttpStatus.OK);
        } catch (IOException ex) {
            throw new RuntimeException("Failed to download picture", ex.getCause());
        }
```
Просто так код компактнее и от этого его легче понять. Ну и это даже скорее стиля касается, обычно если есть код вида: объявить переменную, инициализировать её внутри try-блока, а за его переделами вернуть её, то всегда пишут всё сразу внутри этого try

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<byte[]> downloadUserAvatar(@PathVariable Long userId) {
Я выше не то немного написала)
Там предлагалось ResponseEntity<Resource> делать. Тебе это достаточно легко переделать: Resource это интерфейс, одна из его реализаций - это InputStreamResource, который легко создать, передав ему в конструктор InputStream, который как раз возвращает `userProfilePicService.downloadUserAvatar(userId)`

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            PutObjectRequest putObjectRequest =
Можно переиспользовать метод putObjectInS3

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    public String uploadAvatar(byte[] image, String folder, String contentType) {
Отвечаю про интерфейс: 
Можно было бы сделать интерфейс (а может быть даже абстрактный класс) S3Service с методами: upload, download, delete. Далее создать две реализации: одна для работы с аватарками, другая - для работы с файлами. 
Но вообще сейчас (когда ты подтянула изменения Паши к себе) видно, что одной реализации достаточно, только тебе нужно вместо uploadAvatar использовать метод uploadHttpData (или как-то объединить их), потому что сейчас они делают абсолютно то же самое, кроме проверки и создания бакета. Ну и deleteAvatar и downloadAvatar переименовать так, чтобы в них не было только про "аватар". Теоретически здесь могут быть вообще любые файлы.

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    private String bucketName;
А bucketDefaultAvatarsName не подойдет? Который ниже. Или наоборот - нижний удалить. Просто я не думаю, что нам нужно два бакета для хранения аватарок. Ну и что, что одни дефолтные, а другие загруженные пользователем самостоятельно. Пусть вместе хранятся)

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            s3Object = s3Client.getObject(bucketName, key);
```
        try {
            return s3Client.getObject(bucketName, key).getObjectContent();
        } catch (SdkClientException ex) {
            throw new RuntimeException("Failed to download picture", ex.getCause());
        }
```

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        return s3Client.doesBucketExistV2(bucketName);
Это не надо) Было правильно

2024-09-30 20:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new RuntimeException("Failed to upload picture", ex.getCause());
Про исключения: мы НЕ отлавливаем НЕпроверяемые исключения, т.к. в этом нет смысла. Мы ничего с ними сделать не можем, кроме того, чтобы обернуть их в другое исключение и кинуть дальше. Но если мы этого не сделаем, то оно (исходное исключение) всё равно прервет выполнение текущего метода и долетит до пользователя (он получит 500 статус). Мы, например, не отлавливаем в catch NullPointerException, потому что не знаем, что мы с ним делать будем, хотя теоретически putObject и его тоже может выкинуть. Здесь аналогично, SdkClientException - непроверяемое исключение и нам незачем его ловить и как-то обрабатывать. 
С проверяемыми ситуация практически такая же - ловить их смысла нет, НО компилятор нас обязывает, поэтому приходится делать для них catch и оборачивать во что-то непроверяемое (тот же RuntimeException). 

Просто задай себе вопросы: зачем мне здесь нужен catch? Что я этим хочу сделать? Что он изменит в ходе выполнения программы? Какой в нем смысл? 
Можешь написать в ответе, почему добавила, обсудим. Но в данном месте он ничего нового в программу не привносит)

2024-10-01 02:36 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        byte[] img;
Поняла, спасибо!)

2024-10-01 02:48 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new RuntimeException("Failed to upload picture", ex.getCause());
У меня была простая логика - я вижу, что putObject может кинуть мне ошибку. Значит мне нужно сказать, что программа будет делать если такая ошибка упадет. Убираю

2024-10-01 02:52 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            s3Object = s3Client.getObject(bucketName, key);
Давай без try-catch - все равно же я фигню написала! А без него все будет красивенько))

2024-10-01 03:06 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    public String uploadAvatar(byte[] image, String folder, String contentType) {
Поняла

2024-10-01 03:20 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        return s3Client.doesBucketExistV2(bucketName);
Не поняла, я тут ничего не трогала))

2024-10-01 04:00 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    private String bucketName;
хорошо

2024-10-01 04:01 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            PutObjectRequest putObjectRequest =
Переделала свой код под метод uploadHttpData

2024-10-01 14:30 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            s3Object = s3Client.getObject(bucketName, key);
@StepnovaVarvara ты все правильно написала просто немного надо допилить

2024-10-01 14:30 UTC, GusevVrn commented
Извиняюсь что влезаю, мне только спросить)

Ты тестировала загрузку, как у тебя выглядят файлы в облаке? Можешь скрин прислать?
Мне тут пришлось полазить по твоему коду немного, у меня появилось сомнение, что если зайти ручками на облако и теми же ручками скачать картинку, она просто так не откроется у тебя на компуктере.

2024-10-01 18:58 UTC, StepnovaVarvara commented
> Извиняюсь что влезаю, мне только спросить)
> 
> Ты тестировала загрузку, как у тебя выглядят файлы в облаке? Можешь скрин прислать? Мне тут пришлось полазить по твоему коду немного, у меня появилось сомнение, что если зайти ручками на облако и теми же ручками скачать картинку, она просто так не откроется у тебя на компуктере.

Да, я все тестила и скачивала картинку из облака. У меня все скачивается и открывается
<img width="1440" alt="Снимок экрана 2024-10-01 в 21 57 32" src="https://github.com/user-attachments/assets/b7c7efbb-5cc5-47db-a6fc-c1c20f9c012c">

2024-10-01 19:04 UTC, StepnovaVarvara commented
> > Извиняюсь что влезаю, мне только спросить)
> > Ты тестировала загрузку, как у тебя выглядят файлы в облаке? Можешь скрин прислать? Мне тут пришлось полазить по твоему коду немного, у меня появилось сомнение, что если зайти ручками на облако и теми же ручками скачать картинку, она просто так не откроется у тебя на компуктере.
> 
> Да, я все тестила и скачивала картинку из облака. У меня все скачивается и открывается <img alt="Снимок экрана 2024-10-01 в 21 57 32" width="1440" src="https://private-user-images.githubusercontent.com/141870649/372611142-b7c7efbb-5cc5-47db-a6fc-c1c20f9c012c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4MDk0MDIsIm5iZiI6MTcyNzgwOTEwMiwicGF0aCI6Ii8xNDE4NzA2NDkvMzcyNjExMTQyLWI3YzdlZmJiLTVjYzUtNDdkYi1hNmZjLWMxYzIwZjljMDEyYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxODU4MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjkyZDk1ZGQ3ZDhhZDgzNjM1Njg5YTMyMzczMmMyN2FkY2RiOWVlZjI0M2M4YWY1YTM3N2I0ZWE2MzIwZDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WH-WmSUOa9M9XlXKF4jzHAWsiwKUb1wphXT8WvTAhS8">

2024-10-01 19:05 UTC, GusevVrn commented
> Да, я все тестила и скачивала картинку из облака. У меня все скачивается и открывается 
Короче, как я вижу у тебя в облаке файлы без расширения, я когда такие файлы скачивал у меня комп не знал чем открыть и предлагал на выбор программы. Если не знать что это картинка, то ты и не будешь знать чем открыть. 
Возможно мак по другому как-то работает.

2024-10-01 19:13 UTC, StepnovaVarvara commented
> > Да, я все тестила и скачивала картинку из облака. У меня все скачивается и открывается
> 
> Короче, как я вижу у тебя в облаке файлы без расширения, я когда такие файлы скачивал у меня комп не знал чем открыть и предлагал на выбор программы. Если не знать что это картинка, то ты и не будешь знать чем открыть. Возможно мак по другому как-то работает.

Блин, не знаю. У меня нормально скачивает и открывает. Мб действительно дело в винде

2024-10-01 19:31 UTC, mysosnovskaya commented
> Блин, не знаю. У меня нормально скачивает и открывает. Мб действительно дело в винде

Да не должно быть, винда тоже не умеет файлы без расширения открывать. Если только у тебя не настроено, что для всех файлов без расширения использовать такую-то программу (просмотр картинок)

2024-10-01 19:41 UTC, mysosnovskaya approved these changes

2024-10-01 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public ResponseEntity<byte[]> downloadUserAvatar(@PathVariable Long userId) {
Только сейчас я поняла, что гитхаб съедает всё, что в треугольных скобках, поэтому мои комментарии к этой строке выглядели странно) Я повторю ещё раз уже с учетом этого, но исправлять не нужно, просто чтобы ты была в курсе:

Там предлагалось `ResponseEntity<Resource>` делать. Тебе это достаточно легко переделать: Resource это интерфейс, одна из его реализаций - это InputStreamResource, который легко создать, передав ему в конструктор InputStream, который как раз возвращает userProfilePicService.downloadUserAvatar(userId)

2024-10-01 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            s3Object = s3Client.getObject(bucketName, key);
Паша, мы в другом комментарии обсуждали про исключения, я там писала, что в таком виде отлавливать исключение смысла нет) Поэтому поддерживаю решение Вари

2024-10-01 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +        return s3Client.doesBucketExistV2(bucketName);
Форматирование поехало) Сейчас всё ок

2024-10-01 19:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +            throw new RuntimeException("Failed to upload picture", ex.getCause());
Это может понадобится, когда мы добавим Global Exception Handler, там в зависимости от исключения можно будет возвращать разные ответы. В целом ты права, по моей логике там сейчас тоже это не нужно, но меня там привлекло собственное исключение AmazonS3CustomException и я это интерпретировала так, что в будущем мы как раз в Global Exception Handler будем этим пользоваться)

2024-10-01 19:42 UTC, merged