BJS2-26074 [Experienced] Покупка премиум доступа
CorporationX/user_service pull request #1608
Opened 2024-09-29 12:10 UTC by badasscoding

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +@RequestMapping("/premuim")
версионирование

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    @ResponseStatus(HttpStatus.CREATED)
я бы accepted бросил

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public PremiumDto buyPremium(@RequestBody @NonNull @Positive Integer days) {
А что если принимать сразу ENUM, тогда и не надо будет пробегаться потом через fromDays

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/promotion/PromotionController.java
> +@RequestMapping("/promotion")
v1

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/promotion/PromotionController.java
> +    public PromotionDto buyPromotion(@RequestParam(required = true) PromotionType promotionType, @RequestParam(required = true) PromotionTarget promotionTarget) {
required = true он дефолтный,
вылез за 80 символов
так же я бы accepted возвращал

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping()
скобки

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/dto/premium/PremiumDto.java
> +@Data
а Data вообще используется? я только сеттер нашел в тестах, его бы через билдер запилить

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/dto/premium/PremiumPeriod.java
> +@Getter
для визуала, я бы пирамидкой аннотации проставил

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/dto/promotion/PromotionDto.java
> +@AllArgsConstructor
мож добавить билдер и тогда дата не нужна будет

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        if (filter == null) {
у тебя же в контроллере висит requestbody он до сюда никак null не должен дойти (не твое, но раз ты менял полностью логику)

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +    public void removeExpiredPromotions() {
вот этот метод я бы отдал джобе, 
2 раза бегаешь в базу и удаление хоть и списком идет но вроде оно все равно не как батч работает
пока наверное ок

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .flatMap(promotions -> promotions.stream().filter(promotion -> PromotionTarget.EVENTS.name().equals(promotion.getTarget())))
не уместился

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        long paymentNumber = promotionRepository.getPromotionPaymentNumber();
Имеет ли смысл разбивать платежки на разные категории, сделать один сиквенс на все платежки и весь этот метод куда-нибудь в PaymentService т.к. он не отличается от предыдущего.
От первого аргумента тебе нужно знать сколько стоит, так что весь объект можно и не передавать.
Если имеет значение можешь юзануть pattern matching через instance of, чтоб превьюхи в проект не тянуть.

2024-10-03 21:01 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +    private final school.faang.user_service.service.SkillOfferService skillOfferService;
криво импортнул

2024-10-03 21:01 UTC, GusevVrn commented on src/main/resources/db/changelog/changeset/user_V007__user_premium.sql
> +CREATE SEQUENCE premium_payment_number_sequence
если ты 007 один раз уже пролил, то эти изменения не подтянутся же, перенеси это в 008

2024-10-04 19:11 UTC, Silencemess1ah reviewed
Ничего не понятно но очень интересно) Паша там накидал, что увидел я и понимаю описал ниже

2024-10-04 19:11 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/mapper/premium/PremiumMapper.java
> +    }
Я конечно не спец но оно будет работать? Я правильно понимаю ты кладешь в энтити пустого свежесозданного юзера и присваиваешь ему айди из дто? Oo мне кажется надо за таким в базу идти и руками складывать честно, у тебя же просто болванки там будут с айдишниками

2024-10-04 19:11 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/mapper/promotion/PromotionMapper.java
> +    }
Тоже самое что и выше

2024-10-05 09:45 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public PremiumDto buyPremium(@RequestBody @NonNull @Positive Integer days) {
по заданию так:

Создать класс PremiumController. В нём будет содержаться метод buyPremium, который будет на том или ином этапе вызываться пользователем, желающим приобрести премиум подписку. Метод принимает int days — количество дней на которое юзер хочет приобрести премиум-доступ.

2024-10-05 09:48 UTC, badasscoding commented on src/main/java/school/faang/user_service/dto/premium/PremiumDto.java
> +@Data
в PremiumService есть

```
    private PremiumDto createPremium(Long userId, PremiumPeriod premiumPeriod) {
        LocalDateTime now = LocalDateTime.now();
        PremiumDto premium = new PremiumDto();
        premium.setUserId(userId);
        premium.setStartDate(now);
        premium.setEndDate(now.plusDays(premiumPeriod.getDays()));

        return premium;
    }
```

2024-10-05 09:50 UTC, badasscoding commented on src/main/java/school/faang/user_service/dto/premium/PremiumDto.java
> +@Data
переделал на builder

2024-10-05 09:53 UTC, badasscoding commented on src/main/java/school/faang/user_service/dto/premium/PremiumPeriod.java
> +@Getter
лайк за перфокционизм в коде

2024-10-05 09:56 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +    public void removeExpiredPromotions() {
у меня как раз следующая задача в scheduler вынести это

2024-10-05 10:25 UTC, badasscoding commented on src/main/java/school/faang/user_service/mapper/premium/PremiumMapper.java
> +    }
да, ты прав

я первую задачу делал и там так же сделал, никто не заметил (там тоже поправлю)

```
@Named("mapIdToUser")
    default User mapIdToUser(Long id, @Context UserService userService) {
        return userService.getUserById(id);
    }
```

2024-10-05 10:51 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        long paymentNumber = promotionRepository.getPromotionPaymentNumber();
Ты имеешь ввиду не разделять сущности на Premium и Promotion и сделать один платеж?

Мне кажется тут немного разные типы платежей:
1. Premium - это подписка
2. Promotion - это одноразовый платеж 

Подписка имеет разные сроки жизни, может быть автообновляемая и т.д., может восстанавливаться если юзер залогинится заново на новом девайсе

В одноразовом платеже такого нет

Или ты про другое?

2024-10-05 11:34 UTC, badasscoding commented on src/main/java/school/faang/user_service/mapper/premium/PremiumMapper.java
> +    }
Сделал @Mapping(target = "user", ignore = true)

2024-10-05 11:49 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        long paymentNumber = promotionRepository.getPromotionPaymentNumber();
Я к тому что по логике, как я увидел - платеж это просто отправляешь деньги на сторонний сервис и получаешь ответ.
Просто я сравниваю этот метод и другой который дергает сторонний сервис с платежами. Они одинаковые, разница только в paymentNumber - который сиквенс из бд, для премиума он один, для промота другой. 
Я не вижу большой разницы в них именно для платежа. Почему бы этот метод не вынести в отдельный сервис, но ты на вход вместо PremiumPeriod premiumPeriod и PromotionType price (а ты из них только price же достаешь) передаешь сразу стоимость (price) и если очень важно сделать 2 paymentNumber, то вынести их и тоже в метод передать, если они не важны, сделать один сиквенс на все платежки для этого сервиса.
Тогда у тебя этот метод который отвечает за оплату (по сути просто дергает feign другого сервиса) смогут дергать и PromotionService и PaymentService.

2024-10-05 11:49 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        long paymentNumber = promotionRepository.getPromotionPaymentNumber();
Надеюсь донес суть. Я сравниваю если что PromotionService.sendPayment() и PremiumService.sendPayment()

2024-10-05 11:56 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public PremiumDto buyPremium(@RequestBody @NonNull @Positive Integer days) {
Ну просто все равно потом идет проверка есть ли такое количество дней в enum. Почему бы сразу на входе не принять и все. Никто не запрещает же отойти от задания, если это логично

2024-10-05 12:06 UTC, badasscoding commented on src/main/java/school/faang/user_service/service/promotion/PromotionService.java
> +        long paymentNumber = promotionRepository.getPromotionPaymentNumber();
вынес общий код в отдельный сервис

2024-10-06 03:33 UTC, mysosnovskaya requested changes
Поправь конфликты, пожалуйста

2024-10-08 21:53 UTC, mysosnovskaya requested changes
Большая качественная работа 👍 И спецификации, и миграции, и FeignClient - классный опыт! Я отправлю на доработку, но в следующий раз посмотрю ещё раз внимательно на свежую голову. Всё-таки работа не из простых и ревьювить тоже не просто)

2024-10-08 21:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/client/PaymentServiceClient.java
> +            maxAttempts = 5,
Можем это в конфиг вынести?

2024-10-08 21:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public PremiumDto buyPremium(@RequestBody @NonNull @Positive Integer days) {
Не запрещает) Пусть Илья сам решит, меня и такой вариант устроит, т.к. он соответствует ТЗ и я не вижу здесь ничего страшного

2024-10-08 21:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/premium/PremiumPeriod.java
> +@Getter
Я тоже всегда так делаю =))) Но такого правила нет)

2024-10-08 21:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/filter/DtoFilter.java
> +    default Specification<Entity> toSpecification(FilterDto filters) {
Ого, ещё и спецификации подъехали) Круто 👍

2024-10-08 21:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/filter/DtoFilter.java
> +public interface DtoFilter<FilterDto, Entity> {
Может это EntityFilter?

2024-10-08 21:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/promotion/PromotionPurchaseService.java
> +        promotionRepository.save(promotion);
Лучше сначала сохранить в репозиторий, а потом послать запрос в paymentService. Тогда в случае, если paymentService вернет исключение, то благодаря транзакции изменения из базы данных также откатятся. А вот что будет, если paymentService данные сохранит, а база данных по какой-либо причине нет? Получим неконсистентность

2024-10-13 15:02 UTC, mysosnovskaya requested changes

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    public PremiumDto buyPremium(@RequestBody @NonNull @Positive Integer days) {
RequestBody это всегда json, мы не можем принять просто число. Поэтому обязательно придется добавить dto

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    @PostMapping()
Пустые круглые скобки можно не писать) Даже лучше не писать, чтобы не мешались)

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +    private final UserContext userContext;
Молодец, что используешь UserContext 👍

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +@RequestMapping("/v1/premuim")
И кстати, отдельно отмечу версионирование апи, это хорошо 👍

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/promotion/PromotionController.java
> +    @PostMapping()
Здесь тоже пустые скобки не нужны

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public List<UserDto> getFilteredUsers(@RequestBody @Valid UserFilterDto filter) {
А это точно к твоей задаче относится? Откуда это здесь?

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/client/PaymentRequest.java
> +        Long paymentNumber,
А это поле может быть null?

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/premium/PremiumPeriod.java
> +    public static PremiumPeriod fromDays(int days) {
Метод должен быть глаголом) Подумай, как это можно было бы красиво назвать

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/premium/PremiumPeriod.java
> +    ONE_MONTH(30, 10L),
На будущее: было бы классно периоды и их стоимость подтягивать из конфига. Но сейчас это переделывать не нужно, если не хочется тратить время.

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/promotion/PromotionType.java
> +    PromotionType(long price, int showCount, int priority) {
public?

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/premium/PremiumMapper.java
> +    PremiumDto toDto(Premium entity);
toPremiumDto, т.к. dto классов может быть много разных

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/promotion/PromotionMapper.java
> +    PromotionDto toDto(Promotion promotion);
toPromotionDto

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .collect(Collectors.toList());
Просто сразу toList()

2024-10-13 15:02 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/premium/PremiumPurchaseService.java
> +@AllArgsConstructor
Логов в сервисах не хватает

2024-10-13 16:13 UTC, badasscoding commented on src/main/java/school/faang/user_service/dto/promotion/PromotionType.java
> +    PromotionType(long price, int showCount, int priority) {
конструктор в enum не может быть public

2024-10-13 16:16 UTC, badasscoding commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public List<UserDto> getFilteredUsers(@RequestBody @Valid UserFilterDto filter) {
Это из этой части задания:

Если платеж прошел успешно, то профиль или событие (за что заплатил юзер) начинает попадать в результаты поиска пользователей или событий на первых позициях, а не просто среди всех прочих результатов. Высота появления в результатах поиска зависит от оплаченного тарифа.

Поиск юзеров GET /users

2024-10-13 16:17 UTC, badasscoding commented on src/main/java/school/faang/user_service/dto/client/PaymentRequest.java
> +        Long paymentNumber,
нет, добавил @NotNull

2024-10-14 20:31 UTC, mysosnovskaya approved these changes

2024-10-14 20:31 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/promotion/PromotionType.java
> +    PromotionType(long price, int showCount, int priority) {
Точно)

2024-10-14 20:33 UTC, merged