BJS2-27435: feat: parse csv file
CorporationX/user_service pull request #1609
Opened 2024-09-29 12:47 UTC by ArstanSubanov

2024-09-29 13:36 UTC, SharkB38 commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +    }
Это какой-то зарекомендовавший себя алгоритм или собственная так сказать разработка?

2024-09-29 13:44 UTC, SharkB38 commented on src/main/java/school/faang/user_service/mapper/user/UserMapperUtil.java
> +public class UserMapperUtil {
Емае вот это круто

2024-09-29 13:56 UTC, SharkB38 approved these changes
Братан, ну это очень жестко

2024-09-29 14:05 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +    }
Нееет, генерация пароля не может быть такой простой) Там по-моему есть специальные библиотеки для этого, а Base64 я сделал так как обычно в базе пароли в чистом виде не сохраняются, они обязательно должны быть зашифрованы)

2024-09-29 14:12 UTC, SharkB38 commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +    }
А я почему то подумал что ты типо генерируешь пароль, а потом переводишь в Base64 и новый пароль получаешь из этих символов, подумал прикольно, но не очень безопасно. И потом подумал, а вдруг это какой то хитрый способ и я чего то не знаю.

2024-09-29 14:47 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +    }
К сожалению, пока такого не умею(

2024-09-30 17:59 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/config/user/AsyncConfig.java
> +public class AsyncConfig {
мне кажется, лучше назвать этот класс ThreadPoolConfig или ExecutorConfig, потому что в нем ты конфигурируешь тред пул. на мой взгляд, ты слишком круто решил эту задачу, поэтому только до такого могу докопаться :)

2024-09-30 18:00 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/config/user/UserUploadConfig.java
> +public class UserUploadConfig {
тут тоже как будто лучше назвать класс CsvReaderConfig или что-то в этом духе, непонятно по названию за что этот класс отвечает

2024-10-01 03:18 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/config/user/AsyncConfig.java
> +public class AsyncConfig {
Да, думаю ты прав, я с туториала брал конфиг и название класса) После ревью от Маши переименую, спасибо)

2024-10-01 03:23 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/config/user/UserUploadConfig.java
> +public class UserUploadConfig {
Да, я ещё подумаю над названием, спасибо)

2024-10-01 18:41 UTC, mysosnovskaya requested changes
Очень классная работа, отлично применил асинхронность 👍 Молодец!

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +        String symbols = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" +
В константы?)

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +    }
Арстан, я не поняла, чего ты не умеешь?) Ты же сейчас генерируешь пароль на основе keyWord и недостающего числа символов, взятых рандомно из symbols.

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +        return Base64.getEncoder().encodeToString(password.toString().getBytes());
На мой взгляд, это уже не ответственность этого метода. Класс и метод отвечают только за генерацию пароля (судя по названию). Кодировать-декодировать лучше отдельно, тем более эта логика нужно для базы данных, а здесь (в этом методе) про базу данных вообще ничего неизвестно

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/user/AsyncConfig.java
> +public class AsyncConfig {
С Виталей согласна, но я бы ещё разделила параметры и бин. Отдельный класс TaskExecutorParams с аннотацией ConfigurationProperties и отдельный класс TaskExecutorConfig с созданием бина

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/user/UserUploadConfig.java
> +public class UserUploadConfig {
Согласна

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/user/UserUploadConfig.java
> +    public Random random() {
Не совсем понимаю, как random относится к UserUpload или CsvReader, может его вообще в отдельный класс?

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/mapper/user/UserMapperUtil.java
> +    public String getGeneratedPassword(String name) {
Маппер не должен заниматься генерацией. Он умеет только из одних данных сделать другие (но на основе первых), ничего нового изобретать он не должен. Это не ответственность маппера

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/pojo/ContactInfo.java
> +    @JsonUnwrapped
Молодец, что нашел эту аннотацию 👍

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    public void uploadUsers(MultipartFile file) {
Шикарно написано, асинхронность очень в тему 👍

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +                    throw new EntitySaveException("Users were not saved");
В EntitySaveException лучше передать исходное исключение, чтобы мы потом смогли понять изначальную ошибку (должен стектрейс залоггироваться).

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/upload/CsvLoader.java
> +            throw new FileUploadedException("Fail while uploading the file - " + file.getOriginalFilename());
Сюда тоже нужно прокинуть изначальную ошибку, иначе мы никак не разберемся, в чем именно проблема

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/upload/UserUploadServiceImpl.java
> +        savedCountries.forEach(country -> countries.computeIfAbsent(country.getTitle(), c -> country));
По-моему тут put достаточно, т.к. title уникальное и в countries не может быть второй страны с таким же названием

2024-10-01 18:41 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/upload/UserUploadServiceImpl.java
> +        List<User> unsavedUsers = users.stream()
Подсвечу такой момент: по идее вся эта логика уже есть в базе данных. Т.е. теоретически ты можешь попробовать сохранить всех пользователей и тех, кого не получилось, просто залоггировать. База данных сама проверит, нарушаются ли ограничения уникальности или нет. Но насколько я понимаю, с saveAll такое не получится (там логика другая будет), поэтому такой вариант придется делать другими способами:
1. Либо для каждого user делать save (такой вариант подойдет только тогда, когда мы уверены, что в файле будет очень мало пользователей). Хотя в целом вариант не очень
2. Самостоятельно писать запрос к базе данных, используя конструкцию on conflict do nothing - я бы предпочла такой вариант

На данный момент я не призываю переделывать текущее решение, но если интересно решить более сложную задачку, то можешь поразбираться со вторым вариантом. 
Объясню главный минус твоей текущей реализации: если в таблицу users в базе данных добавится ещё одна уникальная колонка, то мы 100% забудем здесь это добавить) Поэтому проверка уникальности в идеале должна быть только на стороне базы данных

2024-10-02 03:05 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/user/upload/UserUploadServiceImpl.java
> +        List<User> unsavedUsers = users.stream()
Да, я столкнулся с тем, что при вызове saveAll получал исключение по уникальному ключу в таблице, поэтому реализовал такой способ. Попробую сделать второй вариант, спасибо за совет, я об этом не подумал)

2024-10-02 03:10 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/common/PasswordGenerator.java
> +    }
Я имел ввиду генерировать пароль каким-нибудь хитрым способом, у меня всё топорно, что первое в голову пришло)

2024-10-03 18:30 UTC, mysosnovskaya approved these changes

2024-10-03 18:30 UTC, merged