Feature bjs2 26872 Добавление аватара пользователя
CorporationX/user_service pull request #1611
Opened 2024-09-29 15:10 UTC by Alginin

2024-09-29 16:13 UTC, mrkorolev reviewed
В целом ок, за исключением удаления файла - надо подумать, как будем обходить ситуацию с удалением файла (надо будет использовать дефолтную аву)

2024-09-29 16:13 UTC, mrkorolev commented on src/main/java/school/faang/user_service/config/s3/S3Config.java
> +                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endpoint, region))
👍

2024-09-29 16:13 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        }
Вот эту штуку лучше внутри сервиса делать.

2024-09-29 16:13 UTC, mrkorolev commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return new ResponseEntity<>(imageBytes, headers, HttpStatus.OK);
Тот же самый метод, что выше - отличается только url.

2024-09-29 16:13 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/s3/S3Service.java
> +    void deleteFile(String fileKey);
У меня такой же - надеюсь не будет конфликтов.

2024-09-29 16:13 UTC, mrkorolev commented on src/main/resources/application.yaml
> +reduce:
Продумай нейминг - image-limitations, или image

2024-09-29 16:13 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        userRepository.save(user);
Тут мне кажется ошибка - должна быть дефолтная ава, из моей задачи (вместе подумаем, как это сделать).

2024-10-07 19:38 UTC, 20cognosce requested changes
Давай по новой

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PutMapping("/{user-id}/profile-image")
DeleteMapping

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @GetMapping("/{user-id}/profile-image")
После id уже не делай subpath
используй query параметры или в теле запроса передавай
или перед айди путь поменяй

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return new ResponseEntity<>(imageBytes, headers, HttpStatus.OK);
Что это делает в контроллере
Почему байты отдаешь, отдавай Resource

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +        return new ResponseEntity<>(imageBytes, headers, HttpStatus.OK);
Дублирование кода

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    private String bucketName;
@Value

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    }
Убирай такой конструктор

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public void addProfileImage(Long userId, MultipartFile file) throws IOException {
Что это за трешачок
В три раза короче должны быть методы

IO операции вынеси из транзакции, они их не поддерживают

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            InputStream ImageStream = bufferedImageToInputStream(originalImage, "jpg");
Поток закрываем?

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        userRepository.save(user);
Переделать всю эту порнографию

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public InputStream getSmallImageFromProfile(Long userId) {
Как ты можешь отдавать из метода поток ввода...

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public InputStream getSmallImageFromProfile(Long userId) {
Класс создай свой и отдавай объект с контентом в байтах
Resource используй
Multipart может

Но не это

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public InputStream getSmallImageFromProfile(Long userId) {
Ну и транзакции не работают на IO

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        userRepository.save(user);
Дефолтная ава - да, это которую Никита генерирует из внешнего сервиса

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        ImageIO.write(image, format, os);
Потоки закрывать надо

2024-10-07 19:38 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private InputStream bufferedImageToInputStream(BufferedImage image, String format) throws IOException {
Не отдавать потоки, утечка памяти

2024-10-07 19:38 UTC, 20cognosce commented on src/main/resources/application.yaml
> +    small-image: 170
В какие ресурсы ты картинку положил
Не в тестовые нифига

2024-10-11 17:07 UTC, 20cognosce requested changes
Разберись с гитом

2024-10-11 17:07 UTC, 20cognosce commented on src/main/java/school/faang/user_service/config/redis/RedisConfig.java
> +    }
Что это всё делает в задаче добавления аватара?

2024-10-14 20:39 UTC, 20cognosce requested changes

2024-10-14 20:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/advice/ApiControllerAdvice.java
> +    // DTO (Jakarta) validation exceptions
Комментарии кому

2024-10-14 20:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/controller/advice/ApiControllerAdvice.java
> +//                "Something wrong on our end, contact IT support immediately."
?

2024-10-14 20:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    public InputStream downloadFile(String filePath) {
Не принимать и не отдавать потоки, нет
Работай с файлом

2024-10-14 20:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    public void uploadFile(InputStream data, ObjectMetadata metadata, String filePath, Long userId) {
data - не inputStream, нет

2024-10-14 20:39 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    private void uploadToS3(BufferedImage image, String format, ObjectMetadata metadata, String filePath, Long userId) throws IOException {
асинхронно это вызывать, вне транзакции
Почему ты в UserService работаешь с IO? Этому тут не место

2024-10-14 20:42 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    public InputStream downloadFile(String filePath) {
Погоди, я же определял интерфейс для этой темы, что там случилось?

2024-10-14 20:42 UTC, mrkorolev commented on src/main/java/school/faang/user_service/service/s3/S3ServiceImpl.java
> +    public void uploadFile(InputStream data, ObjectMetadata metadata, String filePath, Long userId) {
И тут, там вроде byte[] data

2024-10-22 12:15 UTC, closed without merging