BJS2-26891 Удаление прошедших событий
CorporationX/user_service pull request #1621
Opened 2024-10-01 12:50 UTC by Murzin34

2024-10-01 13:45 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .toList();
Я понимаю, что так указано в задании, но я достал эти события через sql запрос

2024-10-01 13:45 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    void deleteAllEventsById(List<Long> eventIds) {
1. нет модификатора доступа
2. Асинхронные методы должны вызываться из другого компонента. То есть, если мы вызываем метод с аннотацией `@Async` из того же класса, где он определен, то это не будет работать;

2024-10-01 16:58 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    void deleteAllEventsById(List<Long> eventIds) {
Отказался от использования данного метода и аннотации `@Async`

2024-10-01 16:59 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .toList();
Можно так, можно и так)

2024-10-03 11:08 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .toList();
Добавил кастомный `List<Event> findAllByEndDateBefore(LocalDateTime endDate);`

2024-10-03 11:11 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    void deleteAllEventsById(List<Long> eventIds) {
Вернул данный метод и аннотацию @Async), перенес в EventServiceHelper

2024-10-04 19:58 UTC, 20cognosce requested changes

2024-10-04 19:58 UTC, 20cognosce commented on src/main/java/school/faang/user_service/config/event/EventExecutorConfig.java
> +    }
Для кого он был создан???

2024-10-04 19:58 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .forEach(eventServiceHelper::deletePastEventsById);
Что это за метод? Ты разбиваешь типо айдишники на подсписки, чтобы запустить их асинхронно?
Это не будет работать в транзакции

2024-10-04 19:58 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .forEach(eventServiceHelper::deletePastEventsById);
Каждый подсписок должен иметь свою транзакцию

2024-10-05 07:58 UTC, Murzin34 commented on src/main/java/school/faang/user_service/config/event/EventExecutorConfig.java
> +    }
Без него код в сервисе выглядит примерно так: 
```
ListUtils.partition(pastEventsIds, eventProperties.getSublistSize()).forEach(longList -> {
            ExecutorService executor = Executors.newFixedThreadPool(eventProperties.getThreadsNum());

            try {
                executor.submit(() -> eventRepository.deleteAllById(longList));
            } finally {
                executor.shutdown();
                try {
                    if (!executor.awaitTermination(60, TimeUnit.SECONDS)) {
                        executor.shutdownNow();
                    }
                } catch (InterruptedException e) {
                    executor.shutdownNow();
                    Thread.currentThread().interrupt();
                }
            }
        });
```

2024-10-05 08:58 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +                .forEach(eventServiceHelper::deletePastEventsById);
Поправил. Высылаю лог в котором удаление 60 событий проходит в рамках 6 транзакций. Также задействуется 4 потока.

2024-10-05 17:14 UTC, 20cognosce requested changes
Покажи старт и коммит транзакций в логах в разрезе потока

2024-10-05 17:14 UTC, 20cognosce commented on src/main/java/school/faang/user_service/config/event/EventExecutorConfig.java
> +    }
Добавь квалифаер на него поясняющий что он к ивентам относится или javadoc на этот ListUtils

2024-10-05 17:14 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        sublist.forEach(eventServiceHelper::deletePastEventsById);
Ты не решил потенциальную проблему

Вызов @Async из @Transactional может создать проблемы, потому что каждый @Async работает в отдельном потоке, а @Transactional работает через ThreadLocal + TransactionManager, и каждый вызов deletePastEventsById уже не работает в изначальной транзакции от deletePastEvents, имея другой локальный контекст потока

Наоборот вызывай @Transactional из @Async

2024-10-05 17:14 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceHelper.java
> +    public void deletePastEventsById(List<Long> sublistPastEventsIds) {
Этот метод должен быть в транзакции

2024-10-05 17:14 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceHelper.java
> +    public void deletePastEventsById(List<Long> sublistPastEventsIds) {
А он не в транзакции работает

2024-10-05 17:14 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    @Transactional
Тут ты вызываешь асинхронный метод, в этом потоке ничего не обновляется, поэтому эта транзакция фактически рид онли

2024-10-05 17:28 UTC, Murzin34 commented on src/main/java/school/faang/user_service/config/event/EventExecutorConfig.java
> +    }
Добавил `name = "deletePastEventsThreadPool"` в аннотации `@Bean`

2024-10-06 10:39 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        sublist.forEach(eventServiceHelper::deletePastEventsById);
Действительно, косяк. Я почитал https://www.baeldung.com/spring-transactional-async-annotation, попробовал несколько вариантов как задействовать свои методы, в итоге прибился к небольшому изменению того что уже было т.к. поиск евентов и разбивку на подсписки в любом случае нужно делать в рамках метода `@Transactional(readOnly = true)`.

2024-10-06 10:40 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventServiceHelper.java
> +    public void deletePastEventsById(List<Long> sublistPastEventsIds) {
Повесил `@Transactional`

2024-10-06 10:40 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +    @Transactional
Поправил.

2024-10-06 10:47 UTC, Murzin34 commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        sublist.forEach(eventServiceHelper::deletePastEventsById);
Высылаю лог файл. 
[log-2024-10-06_0.log](https://github.com/user-attachments/files/17268979/log-2024-10-06_0.log)

2024-10-06 10:48 UTC, 20cognosce requested changes
закинь правку через git amend и force push, без нового коммита

2024-10-06 10:48 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceHelper.java
> +    @Transactional
Этот Transactional бесполезный
В рамках методов одного бина будет существовать только одна транзакция

2024-10-06 10:48 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/event/EventServiceHelper.java
> +    @Transactional
Тут же уже есть транзакция

2024-10-06 11:17 UTC, 20cognosce approved these changes

2024-10-06 11:17 UTC, merged