BJS2-27271 - реализована логика удаления просроченных премиум-подписок
CorporationX/user_service pull request #1631
Opened 2024-10-03 10:06 UTC by dmitridorje

2024-10-07 16:06 UTC, mikhailov26 requested changes
service: интерфейс + импл

2024-10-11 16:37 UTC, dmitridorje commented
> service: интерфейс + импл

Добавил интерфейс PremiumService + его реализацию в пакете /impl. Исправил возникшие конфликты путей и имён.

2024-10-13 12:32 UTC, mikhailov26 approved these changes

2024-10-13 12:33 UTC, mikhailov26 commented
решаем конфликты и мержим

2024-10-14 07:33 UTC, merged