Unicorn master stream6 feature bjs2 26115
CorporationX/user_service pull request #1633
Opened 2024-10-03 20:43 UTC by Killhimka

Обработчик исключений, не могу 1 тест написать, хелп ми

2024-10-04 18:32 UTC, Silencemess1ah reviewed
lgtm

2024-10-04 18:32 UTC, Silencemess1ah commented on src/test/java/school/faang/user_service/controller/GlobalExceptionHandlerTest.java
> +    }
```
 public void твоёИмяТеста() {
        MethodArgumentNotValidException exception = mock(MethodArgumentNotValidException.class);
        WebExchangeBindException bindingResult = mock(WebExchangeBindException.class);
        FieldError fieldError = new FieldError("object", "field", "message");

        when(bindingResult.getAllErrors()).thenReturn(List.of(fieldError));
        when(exception.getBindingResult()).thenReturn(bindingResult);

        ExceptionHandler handler = new ExceptionHandler();

        Map<String, String> result = handler.handleMethodArgumentNotValid(exception);

        assertEquals(1, result.size());
        assertEquals("defaultMessage", result.get("fieldName"));
    }
```

2024-10-06 10:58 UTC, Killhimka commented on src/test/java/school/faang/user_service/controller/GlobalExceptionHandlerTest.java
> +    }
тоже не пашет

2024-10-06 22:44 UTC, mysosnovskaya requested changes

2024-10-06 22:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/ErrorResponse.java
> +    private HttpStatus httpStatus;
Это поле не нужно. Оно приходит отдельно от респонса благодаря аннотации ResponseStatus

2024-10-06 22:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/GlobalExceptionHandler.java
> +        log.error(e.getMessage());
Залоггировать нужно полностью, чтобы ещё и стектрейс вывелся. А то как мы будем разбираться, в какой строчке ошибка произошла?)

2024-10-06 22:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/GlobalExceptionHandler.java
> +    public Map<String, String> handleMethodArgumentNotValid(MethodArgumentNotValidException e) {
Лучше возвращать список из dto, в котором два поля: field и error (или description/errorDescription)

2024-10-06 22:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/GlobalExceptionHandler.java
> +        log.error(e.getMessage(), HttpStatus.BAD_REQUEST);
BAD_REQUEST в лог не нужно, а вот стектрейс - нужен

2024-10-06 22:44 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/controller/GlobalExceptionHandlerTest.java
> +    }
А в чем ошибка?

2024-10-09 18:05 UTC, mysosnovskaya requested changes

2024-10-09 18:05 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/exception/ErrorResponse.java
> +    private String Description;
В чем отличие от первого поля? Ещё и названо с большой буквы)
По-моему оно не нужно

2024-10-09 18:05 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/GlobalExceptionHandler.java
> +        log.error(e.getMessage());
А здесь не вижу, чтобы ещё e прокидывалось (как ниже)

2024-10-09 18:05 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/GlobalExceptionHandler.java
> +    public List<ErrorResponse> handleMethodArgumentNotValid(MethodArgumentNotValidException e) {
Я предполагала, что здесь будет другой dto, специально для ошибок валидации. Как я писала ранее - в нем будет два поля: field и error

2024-12-21 21:15 UTC, closed without merging