Message subscribe done
CorporationX/user_service pull request #1640
Opened 2024-10-05 00:19 UTC by DenysDovgan

2024-10-07 20:45 UTC, mikhailov26 requested changes
Иерархия + комменты

2024-10-07 20:45 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/event/BanEvent.java
Слишком много аннотаций для одного Long id, используй record

2024-10-07 20:45 UTC, mikhailov26 commented on src/main/resources/db/changelog/changeset/user_V009__addcolumn_banned.sql
Для общего развития: попробуй написать миграцию через xml

2024-10-09 04:37 UTC, ostermal7 commented on src/main/java/school/faang/user_service/scheduler/Scheduler.java
> +    private final EventServiceImpl eventServiceImpl;
должно быть имя интерфейса, а не имплементация

2024-10-09 04:37 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +    @Async("fixedThreadPools")
по-моему от такой аннотации 0 смысла в интерфейсе, она должна быть в реализации

2024-10-09 04:37 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/impl/user/UserServiceImpl.java
> +    private final EventServiceImpl eventServiceImpl;
не импл, а интерфейс

2024-10-09 10:19 UTC, DenysDovgan commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +    @Async("fixedThreadPools")
Она и так есть в имплеееееейфцджуо ралгщшйфнуцкзж

2024-10-09 10:21 UTC, ostermal7 commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +    @Async("fixedThreadPools")
Ну я к тому, что ее тут не должно быть)

2024-10-10 18:00 UTC, mikhailov26 commented
Решай конфликты и можешь мержить

2024-10-10 21:55 UTC, merged