BJS2-27074 Add Spring Boot logging
CorporationX/user_service pull request #1643
Opened 2024-10-05 13:54 UTC by amilosh

2024-10-07 19:19 UTC, 20cognosce requested changes

2024-10-07 19:19 UTC, 20cognosce commented on extras/tutorials/Spring Boot logging.txt
> + - Логирование кода -
Хорошо, но почему это лежит в ПРе?

2024-10-07 19:19 UTC, 20cognosce commented on src/main/resources/logback-spring.xml
> +    <!-- QA environment -->
Не нужны три энва
Сделай один, но комплексный, с форматированием и разными цветами, прокачай стандартный

И сделай аппендер в файл

2024-10-07 19:19 UTC, 20cognosce commented on src/main/resources/logback-spring.xml
> +</configuration>
Сделай несколько ПРов в разные сервисы, чтобы во все занести изменения сразу
+ пришли скрин, какой лог пишется

Не надо его параметризировать, надо чтобы у всех одинаково работал

2024-10-08 11:10 UTC, amilosh commented on extras/tutorials/Spring Boot logging.txt
> + - Логирование кода -
Убрал.

2024-10-08 11:37 UTC, amilosh commented on src/main/resources/logback-spring.xml
> +    <!-- QA environment -->
Сделал.

2024-10-08 11:41 UTC, amilosh commented
![user_service_logs](https://github.com/user-attachments/assets/e979046e-b826-4984-b106-1d2a33dd3611)

2024-10-08 11:45 UTC, amilosh commented
![Uploading user_service_logs.JPG…]()

2024-10-08 11:50 UTC, amilosh commented on src/main/resources/logback-spring.xml
> +</configuration>
сделал

2024-10-08 11:51 UTC, amilosh commented
![user_service_logs](https://github.com/user-attachments/assets/14af76f7-eff8-46d4-a4a5-3a8852e5184d)

2024-10-08 12:27 UTC, 20cognosce requested changes

2024-10-08 12:27 UTC, 20cognosce commented on src/main/resources/logback-spring.xml
> +    <logger name="school.faang" level="debug" additivity="false">
Файл не треснет? Лучше так же info мне кажется

2024-10-08 12:27 UTC, 20cognosce commented on src/main/resources/logback-spring.xml
> +    <logger name="school.faang" level="debug" additivity="false">
А где rollingPolicy?
Выстави лимит на файл - 10 МБ

2024-10-08 12:31 UTC, amilosh commented on src/main/resources/logback-spring.xml
> +    <logger name="school.faang" level="debug" additivity="false">
сейчас доделаю

2024-10-08 13:47 UTC, amilosh commented on src/main/resources/logback-spring.xml
> +    </appender>
Я пробовал просто по размеру делать rolling, используя
SizeBasedTriggeringPolicy в связке с FixedWindowRollingPolicy но в документации написано, что это депрекейтед подход, они не рекомендуют
и сказали лучше использовать тот, что я заимплементил

тут <maxHistory>10</maxHistory> - это не количество файлов, а количество того, что в паттерне указано %d - то есть дней
![logs](https://github.com/user-attachments/assets/a93bb12e-3bf0-45dd-a228-450abe35b43a)

2024-10-08 13:59 UTC, amilosh commented on src/main/resources/logback-spring.xml
> +            <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
и убрал цвета из логирования в файл
а то там кракозябры были

2024-10-08 15:03 UTC, merged