BJS2-26143 Удаление просроченных премиум доступов
CorporationX/user_service pull request #1645
Opened 2024-10-05 16:12 UTC by badasscoding

2024-10-06 09:18 UTC, GusevVrn reviewed
Я не уверен что нам надо для каждого действия отдельно создавать свой ExecutorService - скорей всего он один на все задачи. Не могу найти ответ, как лучше.
Так в целом cr ok.

2024-10-08 01:28 UTC, mysosnovskaya requested changes

2024-10-08 01:28 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    daily: "0 0 0 * * *"
В названии параметра не нужно задавать частоту вызова. Параметр потому и параметр, что может измениться на любое значение и тогда "daily" будет неактуально

2024-10-08 01:28 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/premium/PremiumManagementService.java
> +            List<List<Premium>> expiredByBatches = ListUtils.partition(expiredPremiums, removerBatchSize);
ListUtils.partition - классно 👍

2024-10-08 01:28 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/premium/PremiumManagementService.java
> +    @Transactional
Транзакция здесь не поможет, т.к. удаление ты запускаешь асинхронно в отдельном потоке)

2024-10-08 01:28 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/premium/PremiumManagementService.java
> +    public void removeExpiredPremiums() {
Нужно логи добавить

2024-10-08 01:28 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/scheduler/PremiumRemover.java
> +        premiumManagementService.removeExpiredPremiums();
Нужно логи добавить

2024-10-08 01:28 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/threadPool/ThreadPoolConfig.java
> +    public ExecutorService premiumThreadPools(){
Лучше не конкретизировать тред пул именно под premium. Это будет общий тред пул на всё приложение

2024-10-08 21:10 UTC, mysosnovskaya approved these changes
Аппрув ставлю, но мержить пока рано, т.к. задача с премиум доступами ешё не поревьювлена)

2024-10-14 20:31 UTC, merged