BJS2-27456: Бан юзера за комменты
CorporationX/user_service pull request #1647
Opened 2024-10-05 17:55 UTC by ArstanSubanov

Этот ПР относится к задаче: https://faang-school.atlassian.net/jira/software/c/projects/BJS2/boards/63?selectedIssue=BJS2-27456

2024-10-06 05:28 UTC, soulasphyxia approved these changes
круто круто!!!

2024-10-06 23:06 UTC, SharkB38 approved these changes

2024-10-06 23:26 UTC, mysosnovskaya requested changes

2024-10-06 23:26 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/redis/RedisConfig.java
> +        return new ChannelTopic("user_ban");
user_ban вынести бы в конфиг)

2024-10-08 19:30 UTC, mysosnovskaya requested changes

2024-10-08 19:30 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/redis/RedisMessageSubscriber.java
> +        long userId = Long.parseLong(new String(message.getBody()));
Здесь тоже нужно подумать про обработку ошибок

2024-10-17 14:42 UTC, merged