BJS2-27453 initial commit
CorporationX/user_service pull request #1648
Opened 2024-10-06 05:22 UTC by soulasphyxia

2024-10-06 05:24 UTC, soulasphyxia commented
такой вопрос) если Арстан в своей задаче https://github.com/CorporationX/user_service/pull/1609 сделал TaskExecutor для распараллеливания, то как мне быть? мне можно написать свой тредпул, или нам нужно как-то договориться и сделать один большой? пока что написал еще один, интересно, что лучше)

2024-10-06 07:03 UTC, ArstanSubanov approved these changes
Отлично, мне даже нечего рекомендовать)👍

2024-10-06 23:08 UTC, SharkB38 commented on src/main/java/school/faang/user_service/scheduler/Scheduler.java
> +            ListUtils.partition(events, batchSize).forEach(
О блин, что оказывается есть

2024-10-06 23:08 UTC, SharkB38 approved these changes

2024-10-06 23:09 UTC, SharkB38 commented
> такой вопрос) если Арстан в своей задаче #1609 сделал TaskExecutor для распараллеливания, то как мне быть? мне можно написать свой тредпул, или нам нужно как-то договориться и сделать один большой? пока что написал еще один, интересно, что лучше)

Мне кажется можно договориться, и использовать один пул

2024-10-06 23:23 UTC, mysosnovskaya requested changes
Крутая работа 👍

2024-10-06 23:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/scheduler/Scheduler.java
> +@Slf4j
Аннотация есть, а логов нет)

2024-10-06 23:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/event/EventServiceImpl.java
> +        log.info("Удалены прошедшие события с идентификаторами: {}", ids);
Логи у нас на английском вроде) Можно ещё количество залоггировать

2024-10-06 23:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/scheduler/Scheduler.java
> +public class Scheduler {
Имя класса должно быть более конкретным

2024-10-06 23:23 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/scheduler/Scheduler.java
> +    public void clearEvents() {
Необходимо ещё подумать про обработку ошибок. Здесь GlobalExceptionHandler не поможет, он только для http вызовов. Поэтому ошибки нужно хотя бы залоггировать

2024-10-07 04:19 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/scheduler/Scheduler.java
> +public class Scheduler {
так попросили в таске назвать

2024-10-08 19:03 UTC, mysosnovskaya approved these changes

2024-10-08 19:03 UTC, merged