start solution BJS2-27505-Уведомление о достижении цели (publisher)
CorporationX/user_service pull request #1655
Opened 2024-10-08 22:06 UTC by wmwmaks

2024-10-09 03:45 UTC, SharkB38 approved these changes

2024-10-09 03:45 UTC, SharkB38 commented on src/main/java/school/faang/user_service/config/redis/RedisConfig.java
> +    private String host;
Тоже вынести?

2024-10-09 08:52 UTC, ArstanSubanov approved these changes

2024-10-10 22:17 UTC, wmwmaks commented
тесты на методы сервисов новых завтра пропишу

2024-10-11 07:19 UTC, wmwmaks commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    private void updateSkills(User user, long goalId) {
или это лучше в skillService?

2024-10-12 18:03 UTC, mysosnovskaya requested changes

2024-10-12 18:03 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/redis/RedisConfig.java
> +    RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory connectionFactory) {
Комментарии аналогичны тому, что писала в notification_service

2024-10-12 18:03 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    private final SkillServiceImpl skillService;
SkillService

2024-10-12 18:03 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    private void updateSkills(User user, long goalId) {
Да)

2024-10-12 18:03 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +          name: follower_channel
Таак, почему это изменилось? А изменилось ли это в других соответствующих местах? Название топика нельзя так просто менять, другие сервисы уже могут быть завязаны на старое имя

2024-10-12 21:52 UTC, wmwmaks commented on src/main/resources/application.yaml
> +          name: follower_channel
Хотел сделать, чтобы было в едином стиле. Не подумал, что кто-то уже мог использовать, а правда могли же. Верну

2024-10-16 13:33 UTC, mysosnovskaya approved these changes

2024-10-17 09:09 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/dto/event/GoalCompletedEventDto.java
> +        long eventId,
goalId разве нет?

2024-10-17 09:22 UTC, soulasphyxia commented on src/main/java/school/faang/user_service/config/redis/RedisConfig.java
> +            @Value("${spring.data.redis.channels.goal-event-channel.name") String topic) {
} в конце забыл)

2024-10-17 09:22 UTC, soulasphyxia requested changes
поправь пожалуйста опечатки!

2024-10-17 11:53 UTC, soulasphyxia approved these changes

2024-10-17 19:08 UTC, mysosnovskaya commented
Поправь конфликт и можешь сам оба ПРа смержить (во втором ещё маленькое исправление нужно)

2024-10-20 11:20 UTC, merged