Анализ подписок (pub)
CorporationX/user_service pull request #1665
Opened 2024-10-10 14:09 UTC by SharkB38

2024-10-11 03:42 UTC, ArstanSubanov approved these changes
Всё отлично, только тест какой-то валится) И почему-то в задаче про подписки на проект указано, хотя потом написано про просмотр профиля) возможно вчера с Машей этот момент обсудили)

2024-10-12 16:54 UTC, ArstanSubanov approved these changes

2024-10-15 17:52 UTC, mysosnovskaya requested changes

2024-10-15 17:52 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/service/subscription/SubscriptionServiceImplTest.java
> +    private FollowerEventPublisher followerEventPublisher;
Добавь verify на то, что publish вызывается тогда, когда нужно

2024-10-16 19:33 UTC, mysosnovskaya approved these changes

2024-10-16 19:34 UTC, merged