BJS2-26191 - Created GoalCompletedEventListener
CorporationX/user_service pull request #1668
Opened 2024-10-10 18:46 UTC by GusevVrn

2024-10-12 12:56 UTC, segaTk commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +    private String goalCompletedEvent;
Может вынесем конфиги в отдельный класс? Потом накопится достаточно полей с темой, не говоря уже о бинах для этих тем.

2024-10-12 15:34 UTC, segaTk commented on src/main/java/school/faang/user_service/client/FeignUserInterceptor.java
> +        headerMapping.put(HEADER_USER_ID, () -> String.valueOf(userContext.getUserId()));
грамотно

2024-10-12 19:31 UTC, GusevVrn commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +    private String goalCompletedEvent;
Да, действительно. Спасибо, переделал.

2024-10-13 16:31 UTC, segaTk commented
Всё окей, даже отлично)

2024-10-15 18:44 UTC, mysosnovskaya requested changes

2024-10-15 18:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +                    log.info("Sending notification to user - {}", user.getUsername());
debug подошел бы лучше скорее всего (если планируется, что это событие будет частым)

2024-10-15 18:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +                redisProperties.getHost(),
Про хост и порт писала в другом ПРе, что спринг может автоматически подтянуть это

2024-10-15 18:44 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, Object> redisTemplate() {
Писала Илье, напишу и тебе: Не хотим ли мы делать разные бины под разные типы ивентов? Сейчас у тебя `RedisTemplate<String, Object>` предполагает, что ты будешь передавать объект, который преобразуется в формат json. А если ты туда передаешь String или Long? Это ведь тоже объекты, но в json они преобразованы не будут. И на мой взгляд, это очень не очевидный момент)

2024-10-16 17:43 UTC, GusevVrn commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, Object> redisTemplate() {
А зачем для каждого темплейта делать кучу бинов? 
У нас по проекту же объекты будут кидаться. Если String или Long потребуется, значит наверное добавить еще один темплейт и его уже инжектить и для гарантии через @Qualifier.
Скажи как правильно и принято. Мне просто не нравится идея кучи бинов темплейтов.

2024-10-16 20:18 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +    public RedisTemplate<String, Object> redisTemplate() {
Общепринятого подхода нет, поэтому тут можно обсудить с командой и сделать единый подход. Я соглашусь на любой из них, просто хотела подсветить, что бывает и по-другому)

2024-10-17 18:12 UTC, mysosnovskaya approved these changes

2024-10-17 18:12 UTC, merged