BJS2-37850 Add configurations to run integration tests using testcont…
CorporationX/user_service pull request #1670
Opened 2024-10-10 20:38 UTC by amilosh

…ainers. Add integration tests for GoalController.

2024-10-11 16:46 UTC, 20cognosce requested changes

2024-10-11 16:46 UTC, 20cognosce commented on src/integrationTest/java/school/faang/user_service/CommonFactory.java
> +package school.faang.user_service;
В какой папке ты это создал

src/test/java/integration - такую сделай

2024-10-11 16:46 UTC, 20cognosce commented on src/integrationTest/java/school/faang/user_service/CommonIntegrationTest.java
> +        jdbcTemplate.execute(truncateTablesSql);
Удаляй jdbcTemplate
Используй @Sql аннотацию, в которой ты передаешь адрес в тестовых ресурсах до твоих скриптов
и выбираешь им фазу выполнения, в этой же аннотации

2024-10-11 16:46 UTC, 20cognosce commented on src/integrationTest/java/school/faang/user_service/CommonIntegrationTest.java
> +        jdbcTemplate.execute(truncateTablesSql);
Блин, это буквально следующий спринт, почему ты побежал впереди программы, взял бы еще редиса

2024-10-11 20:59 UTC, amilosh commented on src/integrationTest/java/school/faang/user_service/CommonFactory.java
> +package school.faang.user_service;
А я плагин 
id("org.unbroken-dome.test-sets") version "4.1.0"
использовал
И создал отдельный модуль для интеграционных тестов

Удобно, что логика юнит и интеграционых не пересекаются.
И можно вызывать разными командами
gradle test
gradle integrationTest
![Uploading user_serivce_integration_tests_folder.JPG…]()

2024-10-11 21:00 UTC, amilosh commented on src/integrationTest/java/school/faang/user_service/CommonFactory.java
> +package school.faang.user_service;
![user_serivce_integration_tests_folder](https://github.com/user-attachments/assets/b0bd0bd5-c5dc-4e75-bd74-413fb00a2183)

2024-10-11 21:10 UTC, amilosh commented on src/integrationTest/java/school/faang/user_service/CommonIntegrationTest.java
> +        jdbcTemplate.execute(truncateTablesSql);
Исправил.

2024-10-11 21:14 UTC, amilosh commented on src/integrationTest/java/school/faang/user_service/CommonFactory.java
> +package school.faang.user_service;
![it](https://github.com/user-attachments/assets/97fa896b-5158-4332-a5a6-ea9217607a04)

2024-10-13 19:45 UTC, 20cognosce commented on src/integrationTest/java/school/faang/user_service/CommonFactory.java
> +package school.faang.user_service;
Мне не нравится идея тащить в проект кучу левых плагинов
Потом в этом мусоре копаться и разбираться, что где с какими настройками там создаёт
Почему нельзя просто две папки выделить в тестах

2024-10-13 19:47 UTC, 20cognosce requested changes

2024-10-13 19:47 UTC, 20cognosce commented on build.gradle.kts
> +    id("org.unbroken-dome.test-sets") version "4.1.0"
Удалить это

2024-10-14 19:48 UTC, closed without merging