BJS2-27317 - Уведомление о принятии запроса на менторство
CorporationX/user_service pull request #1674
Opened 2024-10-11 14:29 UTC by dmitridorje

2024-10-13 11:43 UTC, Rashit86 commented on src/main/resources/application.yaml
> +    mentorship-channel: mentorship_channel
Предлагаю также как в notification-service назвать пути

2024-10-13 11:48 UTC, Rashit86 commented on src/main/resources/application.yaml
> +    mentorship-channel: mentorship_channel
redis:
  channels:
    mentorship: mentorship_channel
    project-follower: project_follower_channel
    mentorship-accepted: mentorship_accepted_channel

2024-10-13 12:41 UTC, mikhailov26 requested changes
Очень хорошо, но опять иерархия базовый пакет model, в нём ужt entity, dto и enums

2024-10-16 08:18 UTC, dmitridorje commented
> Очень хорошо, но опять иерархия базовый пакет model, в нём ужt entity, dto и enums

Привел все в соответствие с нужной иерархией.

2024-10-17 19:48 UTC, mikhailov26 approved these changes

2024-10-17 19:48 UTC, mikhailov26 commented
Ты знаешь что делать)

2024-10-17 23:06 UTC, merged