v1 task: Анализ запросов на менторство / feature-BJS2-26160 / UserService
CorporationX/user_service pull request #1693
Opened 2024-10-13 17:03 UTC by Varrankin

2024-10-13 21:50 UTC, Silencemess1ah reviewed
Всё ок, попробуй покидать запросы думаю много вылезет подводных что увидел указал!

2024-10-13 21:50 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/publisher/MentorshipRequestEventPublisher.java
> +public class MentorshipRequestEventPublisher {
Я так подозреваю хотел имплементировать сюда MessagePublisher ?

2024-10-13 21:50 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/config/redis/redisConfig.java
> +public class redisConfig {
название класса с большой буквы

2024-10-13 21:50 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/dto/message/MentorshipRequestMessage.java
> +public class MentorshipRequestMessage {
здесь не хватает имплементации интерфейса, если будешь тестить через постман запрос поймешь о чем я

2024-10-14 07:25 UTC, Varrankin commented on src/main/java/school/faang/user_service/publisher/MentorshipRequestEventPublisher.java
> +public class MentorshipRequestEventPublisher {
да, забыл

2024-10-16 20:24 UTC, mysosnovskaya requested changes

2024-10-16 20:24 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/publisher/MentorshipRequestEventPublisher.java
> +    private RedisTemplate<String, Object> redisTemplate;
final?

2024-10-16 20:24 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/publisher/MentorshipRequestEventPublisher.java
> +    private ObjectMapper objectMapper;
А это поле зачем здесь?

2024-10-17 09:48 UTC, Varrankin commented on src/main/java/school/faang/user_service/publisher/MentorshipRequestEventPublisher.java
> +    private ObjectMapper objectMapper;
забыл убрать

2024-10-17 18:17 UTC, mysosnovskaya commented
Поправь конфликт)

2024-10-18 18:06 UTC, Varrankin commented
@mysosnovskaya я тут немного напортачил, поэтому и хотел с тобой связаться, сделал 2 ребейса, потому что первый раз сделал и вспомнил что не обновил ветку мастер, потом обновил и еще раз, потом пришлось 2 раза конфликты решать, и по итогу я немого запутался что произошло, хотел посмотреть что тут в гите твориться, тоже не особо вышло. В общем обрати на это внимание, чтоб я ничего не подпортил

2024-10-18 18:29 UTC, mysosnovskaya requested changes

2024-10-18 18:29 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/mentorshiprequest/MentorshipRequestServiceTest.java
> +                    menReqRepository, menReqMapper, menReqValidator, filterRequests, publisher);
Надо где-то в тесте добавить verify на то, что паблишер вызывается

2024-10-18 18:29 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/redis/RedisConfig.java
> +public class RedisConfig {
У нас в мастер ветке уже есть настройка редиса, обрати внимание:
https://github.com/CorporationX/user_service/blob/unicorn-master-stream6/src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java

2024-10-21 18:34 UTC, mysosnovskaya approved these changes

2024-10-21 18:35 UTC, mysosnovskaya commented
пофикси конфликт и можешь сам смержить оба ПРа

2024-10-22 15:02 UTC, merged