BJS2-27138 Уведомление о подписке
CorporationX/user_service pull request #1697
Opened 2024-10-14 15:15 UTC by cemeh666

2024-10-15 11:45 UTC, kripersh27 commented on src/main/java/school/faang/user_service/config/redis/RedisTopicsFactory.java
> +    }
Тут такой же комментарий как и в прошлом пул реквесте, чтобы уменьшить дублирование кода и не изменять каждый раз класс

2024-10-16 07:25 UTC, sultan-inked commented on src/main/java/school/faang/user_service/entity/contact/PreferredContact.java
> +    EMAIL, SMS, TELEGRAM, PHONE;
Мне кажется плохая практика менять местами енумы, в уже существующем, и добавлять новый в центр, вдруг у кого то уже завязана на этом логика, имхо

2024-10-17 06:26 UTC, cemeh666 commented on src/main/java/school/faang/user_service/entity/contact/PreferredContact.java
> +    EMAIL, SMS, TELEGRAM, PHONE;
порядок никак не влияет на логику работы енума

2024-10-18 18:25 UTC, 20cognosce requested changes

2024-10-18 18:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        followEventPublisher.publish(new FollowerEvent(followerId, followeeId, follower.getUsername()));
Лучше свою аннотацию сделать

2024-10-18 18:25 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        followEventPublisher.publish(new FollowerEvent(followerId, followeeId, follower.getUsername()));
Через аспект

2024-10-18 18:25 UTC, 20cognosce commented on src/test/java/school/faang/user_service/service/subscription/SubscriptionServiceTest.java
>      public void testFollowUser_successSubscribe() {
Где тест, на то что мы пишем в брокер?

2024-10-20 12:01 UTC, cemeh666 commented on src/test/java/school/faang/user_service/service/subscription/SubscriptionServiceTest.java
>      public void testFollowUser_successSubscribe() {
вынес отправку в аспект. написал интеграционный тест

2024-10-22 19:54 UTC, 20cognosce requested changes

2024-10-22 19:54 UTC, 20cognosce commented on src/main/java/school/faang/user_service/redis/publisher/subscribe/SubscribeUserEventAspect.java
> +    @Around("publishEventPointcut() && args(followerId, followeeId)")
Не Around, а после успешного завершения метода нужно вызывать аспект

2024-10-22 19:54 UTC, 20cognosce commented on src/test/java/school/faang/user_service/integration/SubscriptionControllerTest.java
> +    }
В конфигурационный класс тестовый вынести

2024-10-22 19:54 UTC, 20cognosce commented on src/main/java/school/faang/user_service/redis/publisher/subscribe/SubscribeUserEventAspect.java
> +        Object result = joinPoint.proceed();
???

2024-10-22 19:54 UTC, 20cognosce commented on src/main/java/school/faang/user_service/redis/publisher/subscribe/SubscribeUserEventAspect.java
> +        Object result = joinPoint.proceed();
Допустим, proceed продолжит выполнение основного метода, но всё равно это выглядит криво

2024-10-24 20:33 UTC, 20cognosce approved these changes

2024-10-24 20:34 UTC, merged