task BC-3445 completed
CorporationX/user_service pull request #17
Opened 2023-07-11 21:13 UTC by tarrasoff

2023-07-12 17:13 UTC, Abramovnv reviewed
Я нашел только один момент, который можно написать короче)
Зато подсмотрел у тебя @Controller и @Service :)

2023-07-12 22:00 UTC, Abramovnv approved these changes

2023-07-13 10:56 UTC, Abramovnv approved these changes

2023-07-13 11:52 UTC, InnMish requested changes

2023-07-14 10:09 UTC, InnMish approved these changes

2023-07-14 10:09 UTC, merged