BJS2-26949 Уведомление о подписке
CorporationX/user_service pull request #1716
Opened 2024-10-16 15:52 UTC by Alginin

2024-10-16 16:08 UTC, Peregruzochka reviewed
ожидаю тесты

2024-10-16 16:08 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +                .build();
Я бы сделал отдельный класс/метод который уже внутри класса Publisher формирует dto (мы же решили что не работаем с ними в сервисе). Этот метод как будто не соответствует бизнес-логике

2024-10-16 16:10 UTC, Peregruzochka commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        User user = userRepository.findById(followeeId).orElseThrow();
видимо из-за этой строчки у тебя не билдится (нужно замокать поведение репозитория в тестах)

2024-10-18 18:46 UTC, 20cognosce requested changes

2024-10-18 18:46 UTC, 20cognosce commented on src/main/java/school/faang/user_service/publis/publisher/FollowerEventPublisher.java
> +        log.info("Send message to NotificationService: {}", message);
почему вне try блока

2024-10-18 18:46 UTC, 20cognosce commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        followerEventPublisher.publishFollower(follower, followeeId);
Через свою аннотацию и аспект лучше сделать все ивенты

2024-10-18 18:46 UTC, 20cognosce commented on src/test/java/school/faang/user_service/publis/publisher/FollowerEventPublisherTest.java
> +import static org.mockito.Mockito.*;
бан

2024-10-22 19:30 UTC, 20cognosce requested changes

2024-10-22 19:30 UTC, 20cognosce commented on src/main/java/school/faang/user_service/publis/aspect/FollowerEventAspect.java
> +        followerEventPublisher.publishFollower(follower, followeeId);
А это работает вообще? В какой момент срабатывает твой аспект?
не Around, а надо после успешного выполнения метода, и не надо в репозиторий никакой лезть

2024-10-24 09:23 UTC, Alginin commented on src/main/java/school/faang/user_service/publis/aspect/FollowerEventAspect.java
> +        followerEventPublisher.publishFollower(follower, followeeId);
Да это работает. 
Без получения followerId, не могу передать его в метод "publishFollower"
Исправил аннотацию.

2024-10-24 20:46 UTC, 20cognosce approved these changes

2024-10-24 20:46 UTC, merged