BJS2-27464 добавлено решение задачи
CorporationX/user_service pull request #1726
Opened 2024-10-17 19:44 UTC by KarabbasBarabas

2024-10-18 05:56 UTC, ArstanSubanov approved these changes
Отлично, оставил свои комментарии)

2024-10-18 05:56 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/config/redis/TopicRedisConfig.java
> +public class TopicRedisConfig {
Нужно ли отдельно создавать класс для топиков? Вроде все делают в RedisConfig, думаю стоит придерживаться общего стиля, иначе получится так, что часть людей будет использовать отдельный класс для топиков, а часть нет. И в этого топики и там и там будут, тяжелее будет разбираться где что находится)

2024-10-18 05:56 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    private final PremiumBoughtEventPublisher premiumBoughtEventPublisher;
Думаю, тут правильнее будет инжектить MessagePublisher<PremiumBoughtEvent>, а не конкретную реализацию. Так интерфейс даёт больше абстракции и можно будет в будущем, когда будет много паблишеров, просто списком их все инжектить, закинуть в Map и в зависимости от типа, использовать)

2024-10-20 11:36 UTC, wmwmaks commented on src/main/java/school/faang/user_service/dto/event/PremiumBoughtEvent.java
> +    @JsonIgnore
Про такую аннотацию не знал 👍

2024-10-20 11:40 UTC, wmwmaks reviewed
Нужно еще обратить внимание на то, что Checkstyle ругается в нескольких местах.

2024-10-21 15:27 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/config/redis/TopicRedisConfig.java
> +public class TopicRedisConfig {
ну сейчас видимо уже всё создавать в редисКонфиг, но я не согласен с тем, что всё нужно делать там, потому что когда будет топиков побольше, то параметров для метода с контейнером будет много

2024-10-21 15:28 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/dto/event/PremiumBoughtEvent.java
> +    @JsonIgnore
я тоже много про какие аннотации не знал

2024-10-21 15:31 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +    private final PremiumBoughtEventPublisher premiumBoughtEventPublisher;
согласен, видимо на тот момент было влом делать конструктор для класса

2024-10-21 15:33 UTC, KarabbasBarabas commented
да, чекстайл последним этапом сделаю

2024-10-21 19:42 UTC, mysosnovskaya requested changes

2024-10-21 19:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/config/redis/TopicRedisConfig.java
> +public class TopicRedisConfig {
Каких параметров? Здесь нет контейнера, он для слушателей. У нас либо классов станет много, либо методов в одном классе. Нет практической ценности в том, чтобы в данной ситуации выделять классы по 1-2 метода. Здесь подойдет один большой класс с однотипными методами. На практике чаще всего так. Один раз настроил и больше никогда не заглядываешь туда. Нужен новый топик - скопировал и добавил. Так что тут необходимости в новом классе не вижу

2024-10-21 19:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +         * Метод-пустышка, нужен для задачи сбора аналитики по покупки премиум доступа
Ок

2024-10-21 19:42 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +                           @Qualifier("premiumBoughtEventPublisher")
Лучше оставить через ломбок
https://discord.com/channels/1102662981743030334/1267555771944796171/1297874842082607207

2024-10-22 18:59 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/config/redis/TopicRedisConfig.java
> +public class TopicRedisConfig {
да, согласен

2024-10-22 19:24 UTC, KarabbasBarabas commented on src/main/java/school/faang/user_service/service/user/UserServiceImpl.java
> +                           @Qualifier("premiumBoughtEventPublisher")
не знал, спасибо

2024-10-22 20:50 UTC, mysosnovskaya approved these changes

2024-10-25 20:45 UTC, mysosnovskaya commented
Сборка упала, поправь, пожалуйста, и смержим)

2024-10-30 19:19 UTC, merged