BJS2-26890 -Бан юзера за плохой коммент
CorporationX/user_service pull request #1734
Opened 2024-10-19 19:54 UTC by mrkorolev

Мой код использует логику Андрея - banUser в userService. Мне нужно тут вообще какие либо тесты писать? 

Связанный PR в post_service:

2024-10-21 20:47 UTC, 20cognosce requested changes

2024-10-21 20:47 UTC, 20cognosce commented on src/main/java/school/faang/user_service/redis/listener/AuthorBanListener.java
> +        Long toBeBanned = Long.parseLong(messageBody);
Почему стринг и лонг, что за бред? Ты в REST API не сплошным текстом отдаешь ответы, ну и тут можно ДТОшки создать и objectMapper'ом их парсить?

2024-10-21 20:56 UTC, mrkorolev commented on src/main/java/school/faang/user_service/redis/listener/AuthorBanListener.java
> +        Long toBeBanned = Long.parseLong(messageBody);
@Peregruzochka 
![image](https://github.com/user-attachments/assets/3d7f023d-b8ac-487a-8b67-005b83a5ed48)

2024-10-26 12:29 UTC, 20cognosce approved these changes

2024-10-26 12:29 UTC, merged