BJS2-26189: Уведомление о подписке на проект
CorporationX/user_service pull request #1738
Opened 2024-10-20 10:45 UTC by lowerKamaCase

2024-10-20 18:30 UTC, Silencemess1ah reviewed
По мне ок, только не понятно откуда вызывается метод отправки, тобишь основная логика не выполнена, и не очень понятно откуда столько переделанных классов в ПРе

2024-10-20 18:30 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    }
А где ты его вызываешь чтобы отправить сообщение в редис? Все описал, а вызов метода то где?

2024-10-20 18:34 UTC, lowerKamaCase commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    }
а его нет - нет контроллера, нет сервиса.
ну либо, я не нашел. но я искал

2024-10-20 18:36 UTC, lowerKamaCase commented
> По мне ок, только не понятно откуда вызывается метод отправки, тобишь основная логика не выполнена, и не очень понятно откуда столько переделанных классов в ПРе

не понял тэйк про переделанные классы - я ничего не менял, лишь поправил импорты, потому что они были кривые и билд падал

2024-10-20 19:40 UTC, mysosnovskaya requested changes

2024-10-20 19:40 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    }
Да, действительно нет и задачи на это я тоже не нашла. У меня единственный вопрос - @lowerKamaCase как ты это тестировал?

2024-10-20 19:40 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +    data:
Почему переделаны отступы? С прошлым вариантом что-то не так?

2024-10-21 02:17 UTC, lowerKamaCase commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    }
есть тест ProjectFollowerEventPublisherTest. только в нем.

2024-10-21 02:19 UTC, lowerKamaCase commented on src/main/resources/application.yaml
> +    data:
хмм, случайно. вернул отступ

2024-10-22 19:37 UTC, mysosnovskaya approved these changes
Крайне рекомендую запускать проект и учиться тестировать через постман. Без этого в реальной работе не выжить) Т.е. поднять докер-контейнеры, запустить два сервиса, проверить, что один посылает сообщение в редис, а другой их принимает. Иначе откуда у тебя уверенность, что ты написал рабочий код? На ревью этой гарантии тоже получить нельзя.
Жду фикса конфликтов)

2024-10-24 05:38 UTC, lowerKamaCase commented
> Крайне рекомендую запускать проект и учиться тестировать через постман. Без этого в реальной работе не выжить) Т.е. поднять докер-контейнеры, запустить два сервиса, проверить, что один посылает сообщение в редис, а другой их принимает. Иначе откуда у тебя уверенность, что ты написал рабочий код? На ревью этой гарантии тоже получить нельзя. Жду фикса конфликтов)

![изображение](https://github.com/user-attachments/assets/495dd2a8-1f46-47ce-a439-a0069b0080c4)
проект не запускается, причем это наша ветка мастер

2024-10-24 05:44 UTC, lowerKamaCase commented
> Крайне рекомендую запускать проект и учиться тестировать через постман. Без этого в реальной работе не выжить) Т.е. поднять докер-контейнеры, запустить два сервиса, проверить, что один посылает сообщение в редис, а другой их принимает. Иначе откуда у тебя уверенность, что ты написал рабочий код? На ревью этой гарантии тоже получить нельзя. Жду фикса конфликтов)

конфлик пофиксил

2024-10-24 17:50 UTC, mysosnovskaya commented
> > Крайне рекомендую запускать проект и учиться тестировать через постман. Без этого в реальной работе не выжить) Т.е. поднять докер-контейнеры, запустить два сервиса, проверить, что один посылает сообщение в редис, а другой их принимает. Иначе откуда у тебя уверенность, что ты написал рабочий код? На ревью этой гарантии тоже получить нельзя. Жду фикса конфликтов)
> 
> ![изображение](https://private-user-images.githubusercontent.com/54374272/379629277-495dd2a8-1f46-47ce-a439-a0069b0080c4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk3ODIwNTQsIm5iZiI6MTcyOTc4MTc1NCwicGF0aCI6Ii81NDM3NDI3Mi8zNzk2MjkyNzctNDk1ZGQyYTgtMWY0Ni00N2NlLWE0MzktYTAwNjliMDA4MGM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI0VDE0NTU1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiZjc2NmZiNmMyNTMwZTI2Mjk4YjFhYTZlZjVkMWM2Y2E5MWJhN2ZjN2E1NjcwNmI3ZjI3YTZiZGE5Njk2ZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.agZh6p_a9VoqPxaaDKwiqKOtG_fPUjQNAGMQdkRghzk) проект не запускается, причем это наша ветка мастер

А у тебя точно свежий мастер? На дейлике проверили, запускается

2024-10-26 15:20 UTC, merged