BJS2-26209
CorporationX/user_service pull request #1744
Opened 2024-10-20 18:09 UTC by Silencemess1ah

- Publisher plus base logic on publishing to notification service in profile_view_channel
- Не знаю как лучше поступить с тем что паблишер по факту отправляется с метода который мы дергаем из всех углов нашего приложения, пока создал отдельный метод для проверки да и думаю самое оптимальное главное понять как его назвать и какой урл будет, если есть мысли буду очень ждать как поступить лучше

2024-10-22 04:04 UTC, StepnovaVarvara reviewed
Класс!)

2024-10-22 04:04 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    // А какой будет для чисто юзеров и как это лучше сделать, пока сделал так, работает но костыли...
Хмм... Я бы для пользователей оставила тот метод, который возвращает UserDto, а себе бы (для внутреннего использования) сделала с возвратом User, тк я его никому не отдаю. И тогда нам всем нужно переделывать!))

2024-10-22 04:04 UTC, StepnovaVarvara commented on src/test/java/school/faang/user_service/publisher/profile/ProfileViewEventPublisherTest.java
> +    @InjectMocks
Меня тут ругают, что я отступы не делаю между полями)) Но я бы и не делала, без них лучше!)

2024-10-22 18:53 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    // А какой будет для чисто юзеров и как это лучше сделать, пока сделал так, работает но костыли...
У тебя User хранит в себе пароли и прочую внутреннюю лабуду, а если его перехватит кто?

2024-10-22 19:21 UTC, GusevVrn requested changes

2024-10-22 19:21 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    // Не знаю как сделать так чтобы установить какой из методов будет дергать система из разных сервисов
ты че угараешь? (это я немного добавляю перчинки, а то сильно сладко в сумме от 2х PR после остальных комментаторов))) 
сделай проверку что контекст заполнен, если заполнен значит реальный человек, если не заполнен то сторонний сервис

2024-10-22 19:21 UTC, GusevVrn commented on src/test/java/school/faang/user_service/publisher/profile/ProfileViewEventPublisherTest.java
> +    @InjectMocks
короче, я в самом начале тоже отступы не делал, т.к. как мне казалось они сильно увеличивают код и на меня все ругались что МЫ решили что надо отделять)

2024-10-23 06:21 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    // Не знаю как сделать так чтобы установить какой из методов будет дергать система из разных сервисов
Блин это настолько просто и гениально что я пойду и сделаю, без хедера получается система веселиться с хедером юзер

2024-10-23 08:47 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    // Не знаю как сделать так чтобы установить какой из методов будет дергать система из разных сервисов
Короче Паш норм тема, НО допустим я щас делаю тесты из другой таски, например - из пост сервиса отсылаю в ачивмент что коммент новый оставил и ему поинтов закидываю, он в своей логике на этапе формирования коммента лезет в юзер с хедером, и получается опять отрабатывает просмотр(

2024-10-23 12:45 UTC, mysosnovskaya requested changes

2024-10-23 12:45 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/profile/NewProfileViewEventDto.java
> +    private Long viewedProfileId;
Здесь тоже напишу - предлагаю viewerId

2024-10-23 12:45 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        if(userContext.getUserId() > 0){
А если меньше или равно 0?

2024-10-23 12:45 UTC, mysosnovskaya commented on src/test/java/school/faang/user_service/service/user/UserServiceTest.java
> +    private UserContext userContext;
И проверить бы через verify, что он был вызван

2024-10-23 13:00 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        if(userContext.getUserId() > 0){
@mysosnovskaya у тебя же не может быть айдишник отрицательный и 0 под вопросом.
Вообще, тут надо бы созвониться. Реально по текущей архитектуре не клеится это уведомление вообще ни в какую

2024-10-23 14:14 UTC, Silencemess1ah commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        if(userContext.getUserId() > 0){
Да там бяда, пока это не мержить в любом случае, если в кратце: логика такая идем из поста сюда он дергает этот метод чтобы подтянуть User-а для своих нужд, и при вызове он предполагает хедер метод идет сюда отрабатывает с непустым хедером больше нуля и выходит так как будто тот человек который оставлял коммент - посмотрел профиль улетает нотификация, выяснил чисто случайно тестя свой ачивмент сервис

2024-10-23 15:48 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        if(userContext.getUserId() > 0){
Я к тому, что нужно либо залогировать ошибку, либо вообще изначально исключение бросить, что так нельзя. Ещё вариант - убрать if, и user-service сам разберется, есть у него пользователь с таким айди (меньше 0) или нет. То есть как-то этот случай нужно обработать.

По просмотру профилей - поняла, согласна. Может быть по downloadUserAvatar будем определять просмотр профиля? Как будто бы так логично - если запрашивали аватар, то просматривали профиль. А getUser у нас действительно много где в межсервисном взаимодействии используется.

Если ещё нужно созвониться - готова) Тэгайте меня в чате, найдем время

2024-10-26 18:22 UTC, mysosnovskaya approved these changes

2024-10-26 22:48 UTC, merged