v1 task: Уведомление о получении нового навыка / feature-BJS2-26192 / UserService
CorporationX/user_service pull request #1749
Opened 2024-10-21 11:15 UTC by Varrankin

2024-10-22 03:42 UTC, StepnovaVarvara reviewed
Красава!)

2024-10-22 03:42 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +    ChannelTopic mentorshipRequestTopic() {
Сделай все топики public, плиз. У Паши была ошибка из-за отсутствия этого модификатора

2024-10-22 03:42 UTC, StepnovaVarvara commented on src/main/java/school/faang/user_service/publisher/SkillAcquiredEventPublisher.java
> +@AllArgsConstructor
А почему не @RequiredArgsConstructor?

2024-10-22 03:42 UTC, StepnovaVarvara commented on src/main/resources/application.yaml
> +        skillAcquiredChannel: skill_acquired_channel
Погоди, а ты запускал и проверял что работает? Просто как он у тебя без поля "name" работает? Если все-таки все работает, то мб лучше добавить "name" по аналогии с другими топиками?

2024-10-22 14:24 UTC, Varrankin commented on src/main/java/school/faang/user_service/publisher/SkillAcquiredEventPublisher.java
> +@AllArgsConstructor
согласен, что он тут больше подходит

2024-10-22 14:27 UTC, Varrankin commented on src/main/resources/application.yaml
> +        skillAcquiredChannel: skill_acquired_channel
запускал, работает, в принципе в чем разница с name или без? я думаю тут главное нужен общий подход к неймингу

2024-10-22 14:29 UTC, Varrankin commented on src/main/resources/application.yaml
> +        skillAcquiredChannel: skill_acquired_channel
я просто видел что многие без name делают, решил подогнать по общему стилю при мерже

2024-10-22 19:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/config/redis/RedisConfiguration.java
> +    public ChannelTopic mentorshipRequestTopic() {
а что с названием? сильно ушло от getSkillAcquiredChannel

2024-10-22 19:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/controller/skill/SkillController.java
> +@RequestMapping("/v1/skill")
skills :)

2024-10-22 19:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/publisher/SkillAcquiredEventPublisher.java
> +@ToString
в чем прикол от ToString тут?

2024-10-22 19:35 UTC, GusevVrn commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        var message = SkillAcquiredEventMessage.builder()
собирать сообщение можно в отдельном методе или мапере, 

так же вот этот var, ну он тут совсем не к месту, мы ими в коде не пользуемся же 
не знаю короче, это чисто вкусовщина, можешь оставить
мне просто не нравятся видеть их в самой бизнес логике

2024-10-22 19:35 UTC, GusevVrn commented on src/main/resources/application.yaml
> -  profiles:
а это че куда делось?

2024-10-22 19:35 UTC, GusevVrn commented on src/main/resources/application.yaml
> +        skillAcquiredChannel: skill_acquired_channel
@Varrankin многие без name это в других сервисах, т.к. там не пользовались name изначально, тут же у тебя пример перед глазами, name есть так что надо добавить

2024-10-22 20:05 UTC, mysosnovskaya requested changes

2024-10-22 20:05 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        var message = SkillAcquiredEventMessage.builder()
Про маппинг согласна, нужен как минимум отдельный метод.
Про var соглашусь с тем, что это вкусовщина) Мне нормально, я понимаю, что message имеет тип SkillAcquiredEventMessage (это очевидно и легко читается), дальше мы этой переменной почти не пользуемся, поэтому для меня здесь var выглядит максимально уместно

2024-10-22 20:05 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> -  profiles:
Тоже вопрос

2024-10-22 20:05 UTC, mysosnovskaya commented on src/main/resources/application.yaml
> +        skillAcquiredChannel: skill_acquired_channel
Да, нужно сделать с name

2024-10-23 15:44 UTC, Varrankin commented on src/main/resources/application.yaml
> +        skillAcquiredChannel: skill_acquired_channel
принял, исправлю

2024-10-23 16:05 UTC, Varrankin commented on src/main/resources/application.yaml
> -  profiles:
интересный вопрос

2024-10-23 16:13 UTC, Varrankin commented on src/main/java/school/faang/user_service/service/skill/SkillService.java
> +        var message = SkillAcquiredEventMessage.builder()
согласен, на данный момент сделаю просто метод

2024-10-23 19:02 UTC, mysosnovskaya approved these changes

2024-10-25 11:35 UTC, merged