recommendation event
CorporationX/user_service pull request #1757
Opened 2024-10-24 10:53 UTC by aassylkhan

2024-10-24 12:44 UTC, SharkB38 approved these changes
Круто что логи поправил, осталось поправить чтобы чекстайл не ругался

2024-10-24 12:44 UTC, SharkB38 commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +        log.info("RecommendationReceivedEvent event published: {}", event);
Наверное можно было бы отдельный метод и не выделять, маппером рекомендацию в ивент перегнать, но по идее получилось SOLIDно?

2024-10-24 12:44 UTC, SharkB38 commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationServiceImplTest.java
> +import static org.mockito.Mockito.*;
Как и во втором пре чекстайл жалуется на звездочки

2024-10-24 12:51 UTC, soulasphyxia approved these changes

2024-10-24 15:59 UTC, ArstanSubanov approved these changes
Молодец, вижу большой прогресс)

2024-10-24 15:59 UTC, ArstanSubanov commented on src/main/java/school/faang/user_service/publisher/RecommendationReceivedEventPublisher.java
> +                                                @Qualifier("recommendationReceivedTopic") ChannelTopic topic) {
Может @Qualifier через lombok сделать? Как Максим показал, чтобы не писать конструктор)

2024-10-24 18:00 UTC, mysosnovskaya commented
Сборка завалилась, поправь)

2024-10-28 18:57 UTC, mysosnovskaya requested changes

2024-10-28 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/publisher/RecommendationReceivedEventPublisher.java
> +                                                @Qualifier("recommendationReceivedTopic") ChannelTopic topic) {
Да, лучше вынести

2024-10-28 18:57 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/service/recommendation/impl/RecommendationServiceImpl.java
> +        log.info("RecommendationReceivedEvent event published: {}", event);
Я тоже за маппер)

2024-10-30 19:23 UTC, mysosnovskaya approved these changes

2024-10-30 19:23 UTC, merged