Bjs2 26761 nice guy publisher
CorporationX/user_service pull request #1759
Opened 2024-10-24 14:18 UTC by alibaysarov

2024-10-24 17:01 UTC, ostermal7 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +    @PostMapping("/new")
это лишнее

2024-10-24 17:01 UTC, ostermal7 commented on src/test/java/school/faang/user_service/publisher/NiceGuyEventPublisherTest.java
> +//    @DisplayName("Send Event Test")
удали, если не нужно

2024-10-24 17:01 UTC, ostermal7 commented on src/test/java/school/faang/user_service/publisher/NiceGuyEventPublisherTest.java
> +    }
лучше reflectionutils

2024-10-26 14:22 UTC, mikhailov26 requested changes
Поправь пост маппинг

2024-10-26 14:22 UTC, mikhailov26 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +    @PostMapping("/new")
Согласен с Денисом, было же норм))

2024-12-21 21:15 UTC, closed without merging