Анализ запросов на менторство (pub)
CorporationX/user_service pull request #1774
Opened 2024-10-29 22:05 UTC by Suragany98

- Добавлен класс MentorshipRequestedEventDto в пакете dto.event.
- Настроены RedisTemplate и ChannelTopic для MentorshipRequestedEvent в RedisConfig.
- Создан MentorshipRequestedEventPublisher для отправки событий в Redis.
- Обновлён MentorshipRequestController для публикации события при создании запроса на менторство.
- Написаны unit-тесты для MentorshipRequestedEventPublisher

2024-10-30 12:31 UTC, SharkB38 requested changes

2024-10-30 12:31 UTC, SharkB38 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestedEventPublisher.publish(eventDto);
А почему здесь сделал, а не в сервисе?

2024-10-30 12:31 UTC, SharkB38 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestedEventPublisher.publish(eventDto);
Еще это бы через маппер делать, а не через билдер.

2024-10-30 12:32 UTC, SharkB38 commented on src/test/java/school/faang/user_service/publisher/MentorshipRequestedEventPublisherTest.java
> +        RuntimeException exception = assertThrows(RuntimeException.class, () -> mentorshipRequestedEventPublisher.publish(event));
Чекстайл наверное здесь ругается?

2024-10-31 03:07 UTC, ArstanSubanov approved these changes

2024-10-31 05:49 UTC, SharkB38 commented on src/main/java/school/faang/user_service/mapper/MentorshipRequestedEventMapper.java
> +    @Mapping(target = "requestedAt", expression = "java(java.time.LocalDateTime.now())")
Прикольная штука

2024-10-31 05:49 UTC, SharkB38 commented on src/main/java/school/faang/user_service/mapper/MentorshipRequestedEventMapper.java
> +    @Mapping(target = "requestedAt", expression = "java(java.time.LocalDateTime.now())")
Но зачем маппинги для полей с одинаковым именем?

2024-10-31 05:54 UTC, Suragany98 commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +        mentorshipRequestedEventPublisher.publish(eventDto);
перевел на сервис и создал Маппер

2024-10-31 05:54 UTC, Suragany98 commented on src/main/java/school/faang/user_service/mapper/MentorshipRequestedEventMapper.java
> +    @Mapping(target = "requestedAt", expression = "java(java.time.LocalDateTime.now())")
точно переделал

2024-10-31 05:56 UTC, SharkB38 approved these changes

2024-10-31 06:03 UTC, Suragany98 commented on src/test/java/school/faang/user_service/publisher/MentorshipRequestedEventPublisherTest.java
> +        RuntimeException exception = assertThrows(RuntimeException.class, () -> mentorshipRequestedEventPublisher.publish(event));
передвинул )

2024-10-31 19:53 UTC, mysosnovskaya reviewed
Поправь конфликты и будем мержить)

2024-10-31 19:53 UTC, mysosnovskaya commented on src/main/java/school/faang/user_service/dto/mentorship/request/MentorshipRequestDto.java
> +import lombok.Getter;
Это зачем? Не используется же)

2024-11-24 13:49 UTC, Suragany98 commented on src/main/java/school/faang/user_service/dto/mentorship/request/MentorshipRequestDto.java
> +import lombok.Getter;
Убрал

2024-11-24 18:54 UTC, mysosnovskaya commented
Сборка не прошла, не могу смержить (тесты не компилируются)

2024-11-25 16:35 UTC, merged