Выполнена задача BJS2-40434
CorporationX/user_service pull request #1776
Opened 2024-10-30 05:59 UTC by Memoreks

2024-10-30 10:37 UTC, VovaBuzivskyi commented
В целом код написан хорошо, особенно понравился вынос валидации в отдельные методы. Оставил некоторые замечания. По тестам не могу пока оставить комментарии ,так как только разбираюсь в них.

2024-10-30 14:47 UTC, mad1xx1dam reviewed
Всё круто, главное - было понятно, что и откуда по коду
По некоторым моментам написал предложения

 + возможно стоит почаще коммитить, описывая, что именно было добавлено, чтобы проще если что откатиться можно было

2024-10-30 14:47 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        validateSkill(skillDto);
возможно, стоит выделить класс для валидации 
https://faang-school.com/courses/4jnzmndg/32dnjg9d - второе видео 1:22:00 - про этот момент говорится, там кусочек небольшой

2024-10-30 14:47 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
могу быть не прав, но есть мысль, что не стоит в валидацию skillDto еще помещать проверку на уникальность

почему: как мне кажется, если придется добавить какой-то метод в сервис, в который будет снова передаваться дтошка, то не факт, что с помощью такого метода validateSkill по логике метода получится провалидировать полученную дто (вдруг логика метода не будет предполагать проверку на уникальность)

может, стоит выделить отдельный метод для проброса исключения на случай неуникального переданного скилла

p.s. еще раз: могу быть не прав

2024-10-30 14:47 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/controller/SkillControllerTest.java
> +    public void testCreateSkill() {
вроде договорились на немного другой формат именования тестов 
![image](https://github.com/user-attachments/assets/63b46fe4-ebe9-4cae-a146-51fe0d9468ab)

2024-10-30 14:47 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        validateUser(userId);
👍

2024-10-30 14:47 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/mapper/skill/SkillCandidateMapper.java
> +    }
можно чуть проще переписать через groupingBy, Collectors.counting и map, мне кажется, там строчки 4-6 получится

2024-10-30 14:47 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        }
может, стоит лучше выбрасывать исключение на случай, если у пользователя уже есть такой скилл или если рекомендаций меньше 3 штук (чтобы в контроллер не возвращать содержимое пустого optional)?

и + просто предложение: рассмотреть ifPresentOrElse, чтобы чуть нагляднее было

2024-10-30 14:47 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        verify(skillRepository, times(1)).findAllByUserId(userId);
можно такую же проверку и для метода findById вставить, наверное

2024-10-30 14:47 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        List<SkillDto> skills = skillService.getUserSkills(userId);
мб уже излишне тут пишу, но стоит, наверное, не skills, а skillDtos

2024-10-30 14:47 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        verify(skillRepository, times(1)).findSkillsOfferedToUser(userId);
тоже можно еще findById

2024-10-30 14:47 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    public void acquireSkillFromOffersSkillHasAlreadyBeenAdded() {
если бы выбрасывалось исключение изначально в методе, тут можно было бы просто проверить чисто исключение
но я не знаю, как лучше стоит сделать: исключение или возвращать то, что получили на входе

2024-10-30 14:47 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    public void acquireSkillFromOffersSkillWhenLessThan3Guarantors() {
и тут так же

2024-10-31 03:47 UTC, abdddev commented
Мне все гуд, только в SkillServiceTest я бы с неймингом нижних тестов поработал
а в SubscriptionServiceTest пробелы поубирал, чет кажется много их)
но могу ошибаться) а ну и по конвенции проекта, Test добавить ага
и еще получается UserMapper у тебя нет? те тебе надо ждать пока его зальют, чтобы мастер не ломать?

2024-10-31 04:51 UTC, Memoreks commented
> Мне все гуд, только в SkillServiceTest я бы с неймингом нижних тестов поработал а в SubscriptionServiceTest пробелы поубирал, чет кажется много их) но могу ошибаться) а ну и по конвенции проекта, Test добавить ага и еще получается UserMapper у тебя нет? те тебе надо ждать пока его зальют, чтобы мастер не ломать?

Тесты именовал, до того как договорились. Естественно сейчас переименую.
SubscriptionServiceTest  - уже был реализован при стягивании проекта
Да UserMapper я не использую, тоже тянется из SubscriptionServiceTest.
Вроде как у всех SubscriptionServiceTest был в первоначальном проекте

2024-10-31 04:52 UTC, Memoreks commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        validateSkill(skillDto);
Ага, перенесу отдельно валидаторы

2024-10-31 04:53 UTC, Memoreks commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    }
Тоже думал их разделить. Наверное так и поступлю

2024-10-31 04:53 UTC, Memoreks commented on src/test/java/school/faang/user_service/controller/SkillControllerTest.java
> +    public void testCreateSkill() {
В дискорде уже после отправки увидел. Естественно их переименую

2024-10-31 05:04 UTC, Memoreks commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        }
По ТЗ необходимо ничего не делать, поэтому записал в журнал и вернул навык. Исключение думаю тут излишне.
В контроллер не вернется пустой optional, т.к. сначала проверяем, что навык вообще существует в БД. А в случае, если рекомендации меньше 3, то возвращается сам навык без optional.
Если использовать ifPresentOrElse, то будет больше вложенности и код будет сложнее читаться.

2024-10-31 05:09 UTC, Memoreks commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        verify(skillRepository, times(1)).findAllByUserId(userId);
Думаю да, добавлю ее

2024-10-31 06:40 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    private Skill validateSkill(long skillId) {
Два метода с одинаковым названием , но с разными возвращаемыми значениями , может стоит сменить название чтобы было лучше понятно что какой метод делает? Например validateSkillIsExists , validateSkillIsBlank.

2024-10-31 06:40 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/dto/skill/SkillCandidateDto.java
> +@Data
Нужно ли здесь использовать Data ? На сколько я понимаю здесь будут нужны только сеттеры и гетеры. В SkillDto то же самое.

2024-10-31 08:34 UTC, abdddev commented
@Memoreks 
![image](https://github.com/user-attachments/assets/de8ab856-bc2c-46ce-9588-a276972e2384)
мб у меня просто глючит) но я дифом делаю твою ветку и master и такое)

2024-10-31 09:10 UTC, Memoreks commented
@abdddev 
https://github.com/CorporationX/user_service/commit/32c8874aeb9187a4db43c78ba1bb7185477f06c4#diff-04d1b0637e44eef6f9d2ff9b7ed46702abd07b3baf808719e0e491dc0e2876e0
5 дней назад из ветки dev убрали этот тест. Я значит до удаления успел стянуть репозиторий. Удалю этот файл, чтобы больше не путаться)

2024-10-31 10:40 UTC, VovaBuzivskyi approved these changes

2024-10-31 16:00 UTC, mad1xx1dam approved these changes

2024-10-31 17:22 UTC, BobrAll requested changes
Хороший код! Именование, тесты, логика - все хорошо. Да и ребята тщательно на ревью постарались, особо добавить нечего)

P.S. есть мердж конфликт, его нужно решить, чтобы подтянуть твои изменения в общую ветку

2024-10-31 17:22 UTC, BobrAll commented on src/test/java/school/faang/user_service/controller/SkillControllerTest.java
> +public class SkillControllerTest {
Обычно контроллеры не тестируются (это аргументируется тем, что они лишь посредники к сервисам), поэтому нужно тестировать именно сервисы (тем более что они могут быть вызваны не только из контроллеров, но и из других сервисов, например).
Но если уже есть - то ок

2024-10-31 17:22 UTC, BobrAll commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +        verify(skillOfferRepository, times(0)).findAllOffersOfSkill(skillId, userId);
Лайк

2024-11-01 11:52 UTC, merged