BJS2-40539 Участвовать в событии (без тестов)
CorporationX/user_service pull request #1779
Opened 2024-10-30 13:52 UTC by Alex15265

Как пользователь, я хочу иметь возможность стать участником события, чтобы совместно с другими пользователями работать над решением задачи.

Необходимо реализовать основные операции: зарегистрироваться на событие, отменить регистрацию на событие, получить список участников события и получить количество участников события.

2024-10-30 16:30 UTC, RuslanGabd approved these changes
Good job!

2024-10-30 16:30 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/repository/event/EventParticipationRepository.java
>  }
не уверен что разрешено менять *Repository. Можно сделать проверку используя имеющиеся методы.

2024-10-30 16:35 UTC, Alex15265 commented on src/main/java/school/faang/user_service/repository/event/EventParticipationRepository.java
>  }
ага, видел готовый метод - он мне не понравился для цели данной проверки)

2024-10-30 21:14 UTC, jibulani requested changes
в целом все супер, есть несколько небольших комментариев, а так можно приступать к написанию тестов

2024-10-30 21:14 UTC, jibulani commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +public class ExceptionApiHandler {
круто, что реализовал обработчик ошибок!

2024-10-30 21:14 UTC, jibulani commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
почему 500 ошибка?
на мой взгляд, тут 400, пользователь передал же запрос с невалидными данными, а не у нас на сервере логика разломалась

2024-10-30 21:14 UTC, jibulani commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
тут аналогичная ситуация

2024-10-30 21:14 UTC, jibulani commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    @Transactional
зачем  тут и далее Transactional?

2024-10-31 06:19 UTC, Alex15265 commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +                .status(HttpStatus.INTERNAL_SERVER_ERROR)
согласен, поправлю)

2024-10-31 06:25 UTC, Alex15265 commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    @Transactional
Много раз такое встречал, что все пост, пут, патч методы оборачиваются в транзакцию, вне зависимости от содержания метода)
Получается, что если логика метода простая с единичным вызовом, меняющим состоянии данных в БД, то нет смысла оборачивать в транзакцию?

2024-11-01 18:33 UTC, jibulani requested changes
хороший код, круто, что попробовал написать интеграционные тесты!
нужно добавить юнит-тесты на сервис

2024-11-01 18:33 UTC, jibulani commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    @Transactional
как говорится в ошибке, при изменении данных нужен @Transactional
думал, он уже установлен на уровне репозитория

2024-11-01 18:33 UTC, jibulani commented on src/test/java/school/faang/user_service/controller/event/EventParticipationControllerTest.java
> +@Testcontainers
мощно!
на самом деле пока что требовались только юнит тесты, но круто, что и интеграционными решил заняться!

2024-11-01 18:33 UTC, jibulani commented on src/test/resources/event/init.sql
> +CREATE TABLE country (
зачем? должно накатываться с помощью ликвибейза, если там сложности с настройкой, то пока что некритично

2024-11-01 18:33 UTC, jibulani commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +    private static final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:14-alpine");
на сервис нужно юнит-тесты написать, а не интеграционные, их ты уже через контроллер проверил

для юнит тестов можно замокать репозитории и создать сервис через new, в конструктор прокинуть замоканные зависимости

суть в том, чтобы проверить именно работу сервиса при заранее определенной работе зависимостей, а не проверять опять всю цепочку работы кода

2024-11-03 12:37 UTC, Alex15265 commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +public class EventParticipationController {
Поправил еще типы запросов и пути.
Как будто так правильнее)

2024-11-04 08:51 UTC, jibulani requested changes
есть несколько некритичных комментариев и замечания по поводу тестов
в целом все хорошо, еще чуть-чуть и будет аппрув :)

2024-11-04 08:51 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
>      public ResponseEntity<Void> registerParticipant(@PathVariable("id") @Min(1) Long eventId, @RequestParam("userId") @Min(1) Long userId) {
обычно в таких случаях userId прокидывают либо через PathVariable, либо через RequestBody, некритично сейчас

2024-11-04 08:51 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
>      public ResponseEntity<Void> unregisterParticipant(@PathVariable("id") @Min(1) Long eventId, @RequestParam("userId") @Min(1) Long userId) {
тут аналогичная ситуация с userId

2024-11-04 08:51 UTC, jibulani commented on src/test/java/school/faang/user_service/mapper/user/UserMapperTest.java
> +    public void userToUserDtoWithExpectedResultTest() {
я бы назвал mapUserToUserDtoSuccessTest
некритично

2024-11-04 08:51 UTC, jibulani commented on src/test/java/school/faang/user_service/mapper/user/UserMapperTest.java
> +    private static User john;
скорее всего через билдер можно было при объявлении сразу создать объект User с нужными полями
некритично

2024-11-04 08:51 UTC, jibulani commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        assertDoesNotThrow(() -> eventParticipationService.registerParticipant(1L,2L));
проверь еще через verify, что был вызван репозиторий eventParticipationRepository.register(eventId, userId);

2024-11-04 08:51 UTC, jibulani commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +    void registerParticipantWithoutExceptionTest() {
я бы назвал registerParticipantSuccessTest

2024-11-04 08:51 UTC, jibulani commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +    void registerParticipantWithIllegalArgumentExceptionForEventTest() {
лучше называть не по проверяемой ошибке, а по бизнес-сценарию, так будет понятнее другим людям, что тест проверяет - ты тут проверяешь ситуацию, что пришел запрос для несуществующего ивента, тогда так можно и назвать тест: registerParticipantForNonExistentEventFailTest

для других тестов с аналогичной проблемой тоже попробуй переименовать

2024-11-04 08:51 UTC, jibulani commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        assertDoesNotThrow(() -> eventParticipationService.registerParticipant(1L,2L));
для других тестов с аналогичной ситуацией тоже добавь проверки, что вызвался репозиторий с нужным методом и нужными аргументами

2024-11-04 11:07 UTC, Alex15265 commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
>      public ResponseEntity<Void> registerParticipant(@PathVariable("id") @Min(1) Long eventId, @RequestParam("userId") @Min(1) Long userId) {
переделал с requestbody

2024-11-05 21:32 UTC, jibulani approved these changes
супер, в прод!

2024-11-05 21:32 UTC, jibulani commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        verify(eventParticipationRepository, times(0)).checkUserRegistrationForEvent(100L, 1L);
вместо `times(0)` обычно используют метод `never()`
некритично

2024-11-05 21:32 UTC, jibulani commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        verify(eventParticipationRepository, times(1)).register(1L, 2L);
можно не указывать times(1), а просто проверить: `verify(eventParticipationRepository).register(1L, 2L);`

2024-11-05 21:32 UTC, merged