Создание скилла
CorporationX/user_service pull request #1780
Opened 2024-10-30 14:37 UTC by StanislawKO

2024-11-01 18:13 UTC, jibulani requested changes
отличный код, есть немного замечаний для правки
также можешь приступать к тестам

2024-11-01 18:13 UTC, jibulani commented on src/main/java/school/faang/user_service/web/controller/SkillController.java
> +    private final SkillServiceImpl skillService;
обычно переменные объявляют с типом интерфейса, чтобы зависеть от абстракции, а не от реализации

2024-11-01 18:13 UTC, jibulani commented on src/main/java/school/faang/user_service/web/controller/SkillController.java
> +        if (skill.getTitle() == null || skill.getTitle().trim().isEmpty()) {
у тебя это будет автоматически проверяться благодаря аннотации `@NotBlank`, которую ты поставил над этим полем, но чтобы проверка сработала нужна еще аннотация `@Validated` у аргумента
сейчас некритично, просто раз уж ты начал аннотациями пользоваться, решил подсветить :)

2024-11-01 18:13 UTC, jibulani commented on src/main/java/school/faang/user_service/web/controller/SkillController.java
> +        if (skill.getTitle() == null || skill.getTitle().trim().isEmpty()) {
вижу, что в задании требовалось с помощью такого метода сделать, тогда аннотацию `@NotBlank` можно пока убрать

2024-11-01 18:13 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillService.java
> +public interface SkillService {
круто, что создал отдельный интерфейс!

2024-11-01 18:13 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
> +        return Optional.ofNullable(skillDto)
идея подсвечивает, что лучше использовать of, а не ofNullable, если бы он был нулом, то сюда бы выполнение кода не дошло

2024-11-01 18:13 UTC, jibulani commented on src/main/java/school/faang/user_service/repository/SkillRepository.java
> +            INSERT INTO user_skill_guarantee (user_id, skill_id, guarantor_id)
данный интерфейс предназначен для работы с табличкой skills, для работы с user_skill_guarantee нужно найти более подходящий репозиторий

2024-11-01 18:13 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
> +                skillRepository
добавлять гарантию нужно через более подходящий репозиторий

2024-11-02 19:20 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/SkillService.java
> +public interface SkillService {
Комментариев по задаче нет, написано классно 👍 Я оставлю свои вопросы, чтобы по-возможности лично обсудить.

Я правильно понимаю, что интерфейс нужен для того, чтобы создавать разные имплементации этого сервиса, какждая из которых работает с разными базами данных например?

2024-11-02 19:30 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
> +                .map(skillRepository::saveAndFlush)
не пойму, как преобразовывается dto в entity, при условии, что в них разное количество полей

2024-11-02 19:36 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
> +    public Optional<List<SkillDto>> getUserSkills(Long userId) {
Почему из этого метода не вернуть, например, пустой лист, если skills будет null?

2024-11-03 11:45 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillService.java
> +public interface SkillService {
да, все правильно, но скорее не с разными базами, а для разной реализации бизнес-логики, различное использование баз можно спрятать под общим интерфейсом репозитория

2024-11-03 11:53 UTC, jibulani requested changes

2024-11-03 11:53 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
> +                .map(skillRepository::saveAndFlush)
разруливается параметрами аннотации `@Mapping(target = "users", ignore = true)`

2024-11-03 11:53 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
> +    public Optional<List<SkillDto>> getUserSkills(Long userId) {
согласен, так будет лучше

2024-11-03 11:53 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
>      public Optional<List<SkillCandidateDto>> getOfferedSkills(Long userId) {
давай тут тоже тогда пустой список просто возвращать вместо Optional

2024-11-03 17:05 UTC, StanislawKO commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
> +    public Optional<List<SkillDto>> getUserSkills(Long userId) {
в этом методе мы используем метод ofNullable из сласса Optional, который нам уже позволяет работать с NullPointerExсeption, вернее не допустить этого исключения. В контроллере видно как Optional помогает нам с этим справиться и если нам приходит пустой список мы отправляем это пользователю

2024-11-03 17:11 UTC, StanislawKO commented on src/main/java/school/faang/user_service/service/SkillServiceImpl.java
>      public Optional<List<SkillCandidateDto>> getOfferedSkills(Long userId) {
здесь тоже самое что и в предыдущем методе, Optional как раз для таких случаем и был создан, и если возращать пустой список вместо Optional и еще добавлять условие if, то мы получим на мой взгляд Code smell. Я не утверждаю что это лучшее решение, просто хотел обсудить этот момент, чтобы в дальнейшем улучшить свой код. Спасибо за обратную связь

2024-11-03 18:14 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/web/dto/skill/SkillDto.java
> +    private int userIds;
может здесь должен быть список айдишников юзеров, а не один айди?

2024-11-06 21:52 UTC, jibulani requested changes
есть вопрос и пара некритичных замечаний, а в целом хороший код и тесты, молодец!

2024-11-06 21:52 UTC, jibulani commented on src/main/java/school/faang/user_service/web/dto/skill/SkillDto.java
> +    private List<Long> userIds;
а зачем тут список userIds?
по заданию так должно быть:

> В пакете dto.skill cоздайте класс SkillDto, если его нет. Поля: Long id, String title.

2024-11-06 21:52 UTC, jibulani commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    private SkillServiceImpl skillService;
можно использовать просто SkillService

2024-11-06 21:52 UTC, jibulani commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    private SkillMapperImpl skillMapper;
а тут SkillMapper

2024-11-07 16:12 UTC, StanislawKO commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    private SkillMapperImpl skillMapper;
Здесь именно реализация нужна, об этом Влад в видео-уроках говорил

2024-11-07 16:17 UTC, StanislawKO commented on src/main/java/school/faang/user_service/web/dto/skill/SkillDto.java
> +    private List<Long> userIds;
сначала создал без поля userIds, но решил попробовать поэксперементировать, после того как посмотрел видео про маппер. Сделал, можно сказать для себя, так как учебный проект, но если нужно будет удалить, то без вопросов сделаю

2024-11-07 20:51 UTC, jibulani approved these changes
супер!

2024-11-07 20:51 UTC, jibulani commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    private SkillMapperImpl skillMapper;
именно для маппера?
для сервиса точно можно указать интерфейс
некритично

2024-11-07 20:51 UTC, merged

2024-11-08 18:37 UTC, StanislawKO commented on src/test/java/school/faang/user_service/service/SkillServiceTest.java
> +    private SkillMapperImpl skillMapper;
Да, потому что мы используем @Spy, сам маппер это интерфейс и в тестах у него не будет реализации, так как код генерится при компиляции, соответсвенно в тестах нам нужно будет самим приписывать что возвращает маппер или указать его реализацию, которая сгенерилась и имеет окнончание Impl, тогда будет браться реальная работа маппера. А для сервиса достаточно интерфейса, потому что ты сами указываем что ожидаем от него