Постановка целей
CorporationX/user_service pull request #1783
Opened 2024-10-31 05:56 UTC by allitov

2024-10-31 09:36 UTC, VovaBuzivskyi commented
Код написан лаконично, понятно что какой метод делает . Замечаний по коду нету. Молодец!

2024-10-31 09:43 UTC, Memoreks approved these changes
Отличный и понятный код
Оставил небольшой комментарий, по поводу повторяющейся инициализации объектов в тестах.

2024-10-31 09:43 UTC, Memoreks commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        Long userId = 1L;
Может быть вынести инициализацию повторяющихся объектов в метод setup?

2024-10-31 10:12 UTC, VovaBuzivskyi approved these changes

2024-10-31 10:32 UTC, allitov commented on src/test/java/school/faang/user_service/service/goal/GoalServiceImplTest.java
> +        Long userId = 1L;
Это, кстати, нужно будет обсудить на встрече и договориться, как в проекте делать. У кого-то принято выносить повторяющиеся тестовые данные в отдельный метод, у кого-то - писать все необходимые данные в тесте, чтобы они были перед глазами

2024-10-31 12:47 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/filter/goal/GoalTitleFilter.java
> +        return filter != null && filter.getTitlePattern() != null;
Может стоит проверить TitlePattern, и StatusPatern не передают ли в него пустую строку просто с пробелом?

2024-10-31 14:07 UTC, allitov commented on src/main/java/school/faang/user_service/filter/goal/GoalTitleFilter.java
> +        return filter != null && filter.getTitlePattern() != null;
Согласен, в заголовке сделал проверку на пустую строку. В статусе это делать не нужно, потому что там перечисление используется

2024-10-31 17:53 UTC, BobrAll requested changes
Хороший код, хорошие тесты)
Немного поправить и можно вливать в основную ветку

2024-10-31 17:53 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +        ).build();
Лайк

2024-10-31 17:53 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +                                           @Valid @RequestBody GoalDto goalDto) {
За Valid тоже)

2024-10-31 17:53 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @GetMapping("/user-goals/{userId}")
В целом норм, но для сравнения:

/goals/user-goals/1
/goals/user/1

Как лучше?

2024-10-31 17:53 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @GetMapping("/subtasks/{goalId}")
Обычно эндпоинты именуются по вложенности. Т.е. goal в себе содержит subtasks, значит сначала в пути идет все, что связано с goal, а потом subtasks.
Т.е. /goals/{goalId}/subtasks - так лучше воспринимается

2024-10-31 17:53 UTC, BobrAll commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +public interface GoalService {
Слабая связанность это, конечно, хорошо. Но есть ли смысл так отдалять goal от сервиса? Ведь они изначально друг с другом связаны логически - это вполне конкретный goal и вполне конкретный сервис под него. Маловероятно, что нужно будет как-то кардинально менять сервис.
Да и на практике я такого не встречал, если честно (конкретно для сервисов)

2024-10-31 17:53 UTC, BobrAll commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +    private int maxGoalsAmount;
Круть

2024-10-31 17:53 UTC, BobrAll commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +public class GoalServiceImpl implements GoalService {
Для визуального удобства можно все валидаторы вниз класса опустить, а то они немного перемешаны с основными методами.

Это не замечание, если что, просто чтобы до идеала уже довести)

2024-11-01 06:38 UTC, allitov commented on src/main/java/school/faang/user_service/service/goal/GoalServiceImpl.java
> +public class GoalServiceImpl implements GoalService {
Согласен, а то приходится по классу бегать, чтобы все валидаторы найти :)

2024-11-01 06:41 UTC, allitov commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @GetMapping("/user-goals/{userId}")
Твой вариант компактнее и элегантнее, поправил

2024-11-01 06:43 UTC, allitov commented on src/main/java/school/faang/user_service/controller/goal/GoalController.java
> +    @GetMapping("/subtasks/{goalId}")
Да, так действительно лучше, исправил

2024-11-01 07:24 UTC, allitov commented on src/main/java/school/faang/user_service/service/goal/GoalService.java
> +public interface GoalService {
Убрал интерфейс

2024-11-01 11:53 UTC, BobrAll commented
Супер, вливаю

2024-11-01 11:53 UTC, merged