Feature/bjs2 40452
CorporationX/user_service pull request #1798
Opened 2024-11-01 15:36 UTC by vifravl

2024-11-07 15:16 UTC, KandesQ approved these changes
норм

2024-11-07 15:16 UTC, KandesQ commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +                 .collect(Collectors.toList());
лучше сразу toList()

2024-11-07 15:16 UTC, KandesQ commented on src/test/java/school/faang/user_service/service/RecommendationServiceTest.java
> +        assertThrows(DataValidationException.class, () -> {
assertThrows возвращает ошибку, можно еще было проверить что текст совпадает)

2024-11-07 15:16 UTC, KandesQ commented on src/test/java/school/faang/user_service/service/RecommendationServiceTest.java
> +        Exception exception = assertThrows(IllegalArgumentException.class, () -> {
Вот тут как раз проверяешь текст ошибки, можно вызвать getMessage(), и дальше ассертнуть, чтобы гибкость проверки была

2024-11-07 15:16 UTC, KandesQ commented on src/test/java/school/faang/user_service/service/RecommendationServiceTest.java
> +        assertEquals("Validation failed", exception.getMessage());
Вот тут как раз, вместо константной строки

2024-11-07 15:16 UTC, KandesQ commented on src/test/java/school/faang/user_service/validator/ControllerRecommendationValidatorTest.java
> +public class ControllerRecommendationValidatorTest {
а тут поч без экстеншена мокито? По идее если будет жесткий контроллер, то инициализировать новый экземпляр перед каждым тестом будет затратно довольно

2024-11-07 15:16 UTC, KandesQ commented on src/test/java/school/faang/user_service/validator/ControllerRecommendationValidatorTest.java
> +        DataValidationException dataValidationException = assertThrows(DataValidationException.class, () -> {
про сообщения ошибок выше ^-^

2024-11-07 15:16 UTC, KandesQ commented on src/test/java/school/faang/user_service/validator/ServiceRecommendationValidatorTest.java
> +                createdAt(LocalDate.of(2022, 3, 22).atStartOfDay()).build();
советую, когда используешь билдеры, стримы или лямбды, писать каждый новый метод или вот как у тебя сеттеры с новой строки, улучшиться читабельность в разы

2024-11-07 16:13 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/validator/recommendation/ServiceRecommendationValidator.java
> +@Service
наверное тут надо @Component

2024-11-07 16:13 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/validator/recommendation/ServiceRecommendationValidator.java
> +@Service
и назвать просто recomendationValidator

2024-11-11 20:54 UTC, MiraGlaceon requested changes

2024-11-11 20:54 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +    private final RecommendationService recommendationService;
Доработай контроллер в рамках темы 7го спринта используя аннотацию RestController

2024-11-11 20:54 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +    @Transactional
Тут лучше подумать: тебе метод сервиса нужно запускать в транзакции или метод репозитория?
Я бы перенес аннотацию на репозиторий. Если она у тебя есть на методе сервиса, то и на репозитории она нужна - отсюда следует, что лучше оставить в репозитории

2024-11-11 20:54 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +    @Transactional
Тут тоже посмотри что важнее обернуть в транзакцию. Вообще во всех методах с транзакциями

2024-11-18 15:57 UTC, MiraGlaceon approved these changes

2024-11-20 17:29 UTC, merged