Запрос рекомендации
CorporationX/user_service pull request #1799
Opened 2024-11-01 15:43 UTC by 0Miha0

https://faang-school.atlassian.net/browse/BJS2-40432 
1.
create(RecommendationRequestDto recommendationRequestDto): Создает новый запрос на рекомендацию.
Валидирует входные данные с помощью RecommendationRequestValidator. Преобразует DTO в сущность и сохраняет её в репозитории. Сохраняет связанные навыки через SkillRequestService. 
2.
getRequest(RecommendationRequestFilterDto recommendationRequestFilterDto): Извлекает запросы на рекомендации, применяя фильтры. Валидирует доступность фильтров.
Применяет фильтры к списку запросов.

3.
getRequest(long id):
Извлекает запрос на рекомендацию по идентификатору. Если запрос не найден, выбрасывает исключение DataValidationException. 
4.
rejectRequest(long id, RejectionDto rejectionDto): Отклоняет запрос на рекомендацию по идентификатору. Валидирует существование запроса.
Устанавливает статус REJECTED и причину отклонения. Сохраняет изменения в репозитории.

2024-11-02 04:41 UTC, Memoreks reviewed
Хорошо написал код. По нему удобно ориентироваться и многие вещи понятны. Оставил несколько комментариев, которые повысят читабельность и понимание кода.

2024-11-02 04:41 UTC, Memoreks commented on src/main/java/school/faang/user_service/controller/recommendationRequest/RecommendationRequestController.java
> +    public final RecommendationRequestService recommendationRequestService;
public?

2024-11-02 04:41 UTC, Memoreks commented on src/main/java/school/faang/user_service/dto/recommendationRequest/RecommendationRequestDto.java
> +    private List<Long> skillList;
Может быть лучше назвать skills? Тогда и в маппере не надо будет через Mapping сопоставлять

2024-11-02 04:41 UTC, Memoreks commented on src/main/java/school/faang/user_service/validator/recommendationRequest/RecommendationRequestValidator.java
> +                               SkillRepository skillRepository) {
Может быть лучше создать внутри RecommendationRequestValidator все репозитории, чтобы каждый раз их не передавать в метод?

2024-11-02 04:41 UTC, Memoreks commented on src/test/java/school/faang/user_service/service/controller/SkillRequestService/SkillRequestServiceTest.java
> +    }
А зачем пустой метод? Туда бы добавить объекты, которые используются в тестах

2024-11-02 04:41 UTC, Memoreks commented on src/test/java/school/faang/user_service/service/controller/recommendationRequest/RecommendationRequestServiceTest.java
> +        receiver = User.builder()
Я бы добавил отступ, чтобы код не сливался

2024-11-02 04:41 UTC, Memoreks commented on src/test/java/school/faang/user_service/service/controller/recommendationRequest/RecommendationRequestServiceTest.java
> +        );
Лучше бы избавиться от дублирования кода

2024-11-02 04:41 UTC, Memoreks commented on src/test/java/school/faang/user_service/service/controller/validator/recommendationRequest/RecommendationRequestValidatorTest.java
> +
Лишние отступы

2024-11-02 04:41 UTC, Memoreks commented on src/test/java/school/faang/user_service/service/controller/validator/recommendationRequest/RecommendationRequestValidatorTest.java
> +        request.setCreatedAt(LocalDateTime.now().minusMonths(7));
Я бы вынес все "магические" цифры в коде в отдельные переменные, для улучшения читабельности и понимания кода

2024-11-02 12:50 UTC, VovaBuzivskyi commented
Код написан хорошо. Оставил мелкие замечания.

2024-11-02 12:50 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/dto/recommendationRequest/RecommendationRequestFilterDto.java
> +@Data
Нужно ли здесь ставить Data? Я так понимаю здесь тебе нужны геттеры сеттеры и ToString.

2024-11-02 12:50 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/dto/recommendationRequest/RejectionDto.java
> +@Data
Здесь тоже самое, только сетеры и гетеры нужны.

2024-11-02 12:50 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/service/SkillRequestService/SkillRequestService.java
> +                        .orElseThrow()))
Может здесь стоит выбросить сообщение о том что скилл с таким то Id не был найден.

2024-11-02 12:50 UTC, VovaBuzivskyi commented on src/test/java/school/faang/user_service/service/controller/validator/recommendationRequest/RecommendationRequestValidatorTest.java
> +    public void vValidateSkillsWithValidDataTest() {
Лишняя буква.

2024-11-04 16:41 UTC, BobrAll requested changes
Наверное этот модуль для тебя намного интереснее, сильно выросло качество кода, прям приятно смотреть! Оставил пару правок - они совсем незначительные. В любом есть конфликт, который нужно решить, заодно лучше и их поправить

2024-11-04 16:41 UTC, BobrAll commented on src/main/java/school/faang/user_service/dto/recommendationRequest/RejectionDto.java
> +public class RejectionDto {
Лучше бы RecommendationRejectionDto тогда

2024-11-04 16:41 UTC, BobrAll commented on src/main/java/school/faang/user_service/exception/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Круто

2024-11-04 16:41 UTC, BobrAll commented on src/main/java/school/faang/user_service/validator/recommendationRequest/RecommendationRequestValidator.java
> +    private static final int SIX_MONTHS_AGO = 6;
Хорошо, что в константу вынес, но название не совсем понятное, если увидеть его вне контекста. Как насчет MONTHS_TO_REPEAT_REQUEST?

2024-11-04 16:41 UTC, BobrAll commented on src/test/java/school/faang/user_service/service/controller/SkillRequestService/SkillRequestServiceTest.java
> +    public void checkForLackOfSkillsTest() {
Можно еще проверить, что у репозитория не вызывается метод save, чтобы точно убедиться, что мы перед вылетом исключения не сохранили ничего лишнего

2024-11-04 16:42 UTC, BobrAll commented
И отдельный лайк за @Valid

2024-11-09 17:35 UTC, BobrAll commented
Все супер, но merge-конфликт остался, он не позволяет влить изменения

2024-11-13 08:50 UTC, BobrAll commented
Тесты не проходят. Либо стоит подтянуть изменения актуальные, либо какие-то ошибки в коде

<img width="921" alt="image" src="https://github.com/user-attachments/assets/b53ae950-54e3-4179-9ebf-93c797dcbb83">

2024-11-16 14:29 UTC, BobrAll reviewed
Отлично, вливаю

2024-11-16 14:30 UTC, merged