Запрос рекомендации
CorporationX/user_service pull request #1803
Opened 2024-11-01 18:08 UTC by dimaevseenko

Реализация задания + тесты

2024-11-03 11:49 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +    private final SkillRepository skillRepository;
как будто слишком много репозиториев в одном сервисе

2024-11-03 11:49 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +                .filter(reqDto -> filter.getReceiverId() == null || reqDto.getRequesterId() == filter.getReceiverId())
программа не расширяемая в лекции говорилось так не делать , нужен отдельный интерфеис для фильтров и каждый отдельный фильтр бы имплементировал это интерфеис , а в классе у тебя был бы лист со всеми фильтрами которые заинжектил бы спринг . А потом ты бы с помощью дто проверял бы какие значения в нем !=null и только эти фильтры бы применял из листа

2024-11-03 11:49 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +        recommendationRequest.setRequester(userRepository.findById(request.getRequesterId()).orElseThrow(() -> new IllegalArgumentException("Requester id %s not exist".formatted(request.getRequesterI
как будто можно энтер добавить где то , плохо читаемый код

2024-11-03 12:41 UTC, dimaevseenko commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +                .filter(reqDto -> filter.getReceiverId() == null || reqDto.getRequesterId() == filter.getReceiverId())
Не совсем понял как бы это работало, если запрос с фильтрами передает пользователь в теле запроса

2024-11-03 15:31 UTC, m1rroxxx reviewed
оказывается надо было подтвердить окончание ревью)) 
а так вроде тоже самое что святослав оставил)

2024-11-03 15:31 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private LocalDateTime updatedAt;
мне кажется в DTO лучше преобразовывать LocalDateTime в string

2024-11-03 15:31 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestRejectionDto.java
> +    private String reason;
тут можно добавить id отклоненного запроса

2024-11-03 15:31 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +                .toList();
если тебе придётся добавить ещё одно поле для фильтрации, придётся здесь менять код, а это не соответствует принципу SOLID open/close, можно сделать интерфейс фильтрации, а от него наследовать каждый отдельный фильтр, а вообще очень подробно как это делать объясняется в предпоследнем видосе про DTO после 1 час 20 мин

2024-11-03 15:31 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private LocalDateTime updatedAt;
или в лонг

2024-11-04 15:03 UTC, dimaevseenko commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +                .toList();
Спасибо, щас поправлю)

2024-11-06 12:07 UTC, MiraGlaceon requested changes

2024-11-06 12:07 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private Long id;
В dto (Data Transfer Object - из самого названия) предназначено, чтобы скрывать нужные поля из передачи клиенту и упрощения объема переменных. Пересмотри в этом DTO поля id, createdAt, updatedAt

2024-11-06 12:07 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +        recommendationRequest.setRequester(userRepository.findById(request.getRequesterId()).orElseThrow(() -> new IllegalArgumentException("Requester id %s not exist".formatted(request.getRequesterI
Поддерживаю
Разделяй цепочку стримов переходами на новую строку
```
recommendationRequest
   .setRequester(userRepository
         .findById(request.getRequesterId())
   .orElseThrow
```
Типа такого

2024-11-06 12:07 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceImpl.java
> +    private final SkillRepository skillRepository;
Тут тоже согласен. У тебя один сервис предназначенный для работы с рекомендациями работает с несколькими репозиториями не связанными с этим сервисом. Каждый репозиторий должен быть в своем сервисе объединенный какой-то логикой, либо можно создать отдельный сервис, где выполнять особую логику в связке с несколькими репозиториями

2024-11-06 13:23 UTC, dimaevseenko commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private Long id;
Я создавал dto по условию задачи, там были указаны эти поля, мне их в любом случае переделать?

2024-11-06 20:43 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationRequestDto.java
> +    private Long id;
Оставь раз по условию

2024-11-06 20:53 UTC, MiraGlaceon approved these changes

2024-11-06 20:54 UTC, merged