Bjs2 40479
CorporationX/user_service pull request #1804
Opened 2024-11-01 19:44 UTC by RuslanGabd

2024-11-04 18:43 UTC, jibulani requested changes
хорошо, но есть что поправить :)

2024-11-04 18:43 UTC, jibulani commented on build.gradle.kts
> +    testImplementation("org.mockito:mockito-core:3.+")
![image](https://github.com/user-attachments/assets/bdebaa6d-5311-4db8-b4d5-8b3606b28d45)
излишне, уже тянется из другой зависимости, можно в идее с помощью dependency analyzer найти

2024-11-04 18:43 UTC, jibulani commented on gradle/wrapper/gradle-wrapper.properties
зачем потребовалось удалить?

2024-11-04 18:43 UTC, jibulani commented on gradlew.bat
и тут

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +@RequestMapping(UrlUtils.MAIN_URL + UrlUtils.REQUEST)
раз пошел по такому пути, то рекомендую сделать, как в пр у Леши: https://github.com/CorporationX/user_service/pull/1779

что-то такое должно получиться:
`@RequestMapping(UrlUtils.MAIN_URL + UrlUtils.V1 + UrlUtils.MENTORSHIP)`

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                && (idRequester != idReceiver)) {
лучше начать с этой проверки, чтобы лишний раз в базу не обращаться

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                    mentorshipRequestRepository.save(mentorshipRequestMapper.toEntity(mentorshipRequestDto));
лучше вызвать `MentorshipRequest create(long requesterId, long receiverId, String description);`
потому что заполнять данные о создании и обновлении с фронта неправильно, извне может что угодно прилететь

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/MentorshipRequestDto.java
> +public record MentorshipRequestDto(long id,
идентификатор создается базой, получать его извне плохая идея, может быть уже созданный реквест с таким же id

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/MentorshipRequestDto.java
> +                                   RequestStatus status,
это и ниже поля по идее тоже не нужны, для создания запроса необходимы только:
long requesterId, long receiverId, String description
старайся брать извне минимально необходимый набор данных, остальные данные уже образуются в процессе внутренней работы сервиса

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/entity/MentorshipRequest.java
> +@Mapper
это разве тут нужно?

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                    log.error("Last request has date less 3 months: " + lastRequest.get().getCreatedAt());
на мой взгляд будет удобнее, если везде будет только выкидывание исключений, а логирование ошибок будет в ExceptionApiHandler, так точно не забудешь залоггировать

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +            } else {
довольно запутанная цепочка вложенных if-else, подумай, возможно получится ее упростить
например, сначала отдельными ифами проверить невалидные ситуации и в их случае выкидывать ошибки
или можно без ифов сделать отдельные приватные методы для валидации и по очереди их тут вызывать:
```
validateRequesterReceiver(...);
validateRequestDate(...);
mentorshipRequestRepository.create(...);
```

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/MentorshipRequestMapper.java
> +package school.faang.user_service.dto;
предлагаю мапперы в  отдельный пакет выносить

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    @GetMapping( UrlUtils.REQUESTS_FILTER)
тут можно просто GetMapping сделать без доп пути

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/RequestFilterDto.java
> +                               RequestStatus status) {
лучше сделать отдельный енам для статуса извне RequestStatusDto, чтобы клиенты не зависели от внутренней реализации статусной модели

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +@RestControllerAdvice
круто!

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                            User requester = mentorshipRequest.getRequester();
рекомендую вынести в приватный метод

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                                mentorshipRequest.setStatus(RequestStatus.ACCEPTED);
тут статус еще и в базе надо обновить

2024-11-04 18:43 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                            mentorshipRequest.setStatus(RequestStatus.REJECTED);
тоже рекомендую вынести в отдельный метод и сохранить изменения в базе

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +    private UserContext userContext;
нужен?

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +        MockitoAnnotations.openMocks(this);
для чего?

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +        faker = new Faker();
нужно вызывать перед каждым тестом?

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +        this.objectMapper = new ObjectMapper().registerModule(new JavaTimeModule());
почему не проинициализировать сразу при объявлении?

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +    private MentorshipRequestDto generateMentorshipRequestDto() {
обычно приватные методы располагают в конце класса или после public-класса, в котором приватный метод используется

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +    public void testRequestMentorship_Success() throws Exception {
давай именовать в стиле requestMentorshipSuccessTest, чтобы во всем проекте в одном стиле нейминг был

для чего тут throws Exception?

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +    public void testRequestMentorship_BadRequest() throws Exception {
лучше в названии теста отражать, почему запрос зафейлится, так проще будет найти тест на нужный сценарий
сейчас непонятно, почему он должен быть BadRequest

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +package school.faang.user_service.service;
давай располагать тесты в тех же пакетах, в которых лежат тестируемые классы, то есть этот тест нужно переместить в пакет school.faang.user_service.controller

так будет проще найти нужный тест

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        MockitoAnnotations.openMocks(this);
точно надо? ни разу не приходилось так делать :D

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        MockitoAnnotations.openMocks(this);
видимо вместо этого можно над классом добавить аннотацию `@ExtendWith(MockitoExtension.class)`

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +    public MentorshipRequest generateMentorshipRequest() {
если он нужен только в этом классе, то лучше сделать приватным и разместить в низу класса
если нужен в других классах, то лучше вынести в утилитный класс

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +package school.faang.user_service.service;
в других тестах аналогичная ситуация с пакетами

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +    void testRequestMentorship_RequestWithinThreeMonths_ThrowsException() {
тут и ниже ситуация с неймингом нужно исправить, как писал в другом тесте

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +    void testRequestMentorship_InvalidUser_ThrowsException() {
лучше переименовать как requestMentorshipForNonExistantRequesterIdShouldFail

и добавить тесты на не существующего получателя и совпадающего отправителя и получателя

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        assertEquals(RequestStatus.ACCEPTED, mentorshipRequest.getStatus());
еще нужна проверка, что вызвался метод обновления MentorshipRequest в репозитории

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +        assertTrue(exception.getMessage().contains("Request with id: 1 does not exist"));
еще нужна проверка, что НЕ вызвался метод обновления MentorshipRequest в репозитории

2024-11-04 18:43 UTC, jibulani commented on src/test/java/school/faang/user_service/service/MentorshipRequestServiceTest.java
> +    void testRejectRequest_RequestExists_Success() {
в этом и следующем тестах аналогичная ситуация с проверками обновления MentorshipRequest в репозитории

2024-11-04 19:03 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                                mentorshipRequest.setStatus(RequestStatus.ACCEPTED);
Не совсем понял, здесь же JPA и Transactional они должны автоматом менять в базе если сущность меняется.

2024-11-04 19:04 UTC, RuslanGabd commented on gradle/wrapper/gradle-wrapper.properties
не знаю как так получилось, намерено такое не удалял

2024-11-06 13:51 UTC, RuslanGabd commented on src/test/java/school/faang/user_service/service/MentorshipRequestControllerTest.java
> +    private UserContext userContext;
да без него, никак

2024-11-10 09:55 UTC, jibulani requested changes
осталось немного поправить :)

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/utilities/UrlUtils.java
> +    public static final String MENTORSHIP = "/MENTORSHIP";
почему капсом?
"/MENTORSHIP"

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
>      @PostMapping(UrlUtils.CREATE)
тут обычно не делают дополнительных частей урлов, сам post-запрос говорит о том, что что-то будет создаваться в нем

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +        if (mentorshipRequestDto.description().length() > 35) {
некритично, но лучше вынести число в константу, еще лучше вынести проверку в отдельный приватный метод, который выкинет ошибку при валидации, которая будет обработана в exceptionHandler, тогда метод контроллера сократиться до двух строк:
```
validateDescription(...);
return ResponseEntity.ok(mentorshipRequestService.requestMentorship(mentorshipRequestDto)).build();
```

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
>      public ResponseEntity<List<MentorshipRequestDto>> getRequests(@RequestBody RequestFilterDto filter) {
понимаю, что еще не проходили, но у get-запроса не используется тело запроса, тут правильнее использовать `@RequestParam` - он отвечает за считывание параметров запроса в урле вида `host.com/path?param1=val1&param2=val2`

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +            throw new IllegalArgumentException(String.format("Requester or Receiver not found or the both is the same person", idRequester + idReceiver));
чтобы format отработал, нужно, чтобы в строке были спец-символы:
`String.format("Requester with id %s or Receiver with id %s not found or the both is the same person", idRequester, idReceiver)`
ну и сами ошибки рекомендую разные сделать, чтобы было понятно, что именно не так, но это уже некритично

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                throw new IllegalArgumentException(String.format("Last request has date less 3 months", lastRequest.get().getCreatedAt()));
тоже format не сработает

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +                    String.format(receiver
зачем тут format, если просто складываешь строки?

2024-11-10 09:55 UTC, jibulani commented on src/test/java/school/faang/user_service/controller/event/MentorshipRequestControllerTest.java
> +    public void testRequestMentorshipBadRequestFieldDescriptionLess25Symbols() throws Exception {
я бы назвал попроще, например: requestMentrorshipWithInvalidDescriptionFailTest

2024-11-10 09:55 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +        if (mentorshipRequestDto.description().length() > 35) {
а само поле лучше проверять через notBlank сначала, чтобы не вылетел NPE, если оно окажется null

2024-11-10 09:55 UTC, jibulani commented on src/test/java/school/faang/user_service/controller/event/MentorshipRequestControllerTest.java
> +    public void testRequestMentorshipBadRequestFieldDescriptionLess25Symbols() throws Exception {
и в целом по формату именования методов в тесте рекомендую посмотреть в тестах Алексея, например, в EventParticipationControllerTest, чтобы по проекту в одном стиле был нейминг

2024-11-10 09:55 UTC, jibulani commented on src/test/java/school/faang/user_service/controller/event/MentorshipRequestControllerTest.java
> +package school.faang.user_service.controller.event;
почему в пакете event тест?
нужно тогда по аналогии отдельный пакет mentorship для теста или просто в пакете school.faang.user_service.controller размести

2024-11-10 09:55 UTC, jibulani commented on src/test/java/school/faang/user_service/mapper/user/MentorshipRequestMapperTest.java
> +package school.faang.user_service.mapper.user;
тоже неподходящий пакет

2024-11-10 21:37 UTC, jibulani approved these changes
супер!

2024-11-10 21:37 UTC, merged