BJS2-40532 Организация события
CorporationX/user_service pull request #1805
Opened 2024-11-01 19:48 UTC by GasDa

2024-11-05 19:20 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +    private final UserRepository userRepository;
много репозиториев в одном класс как будто нужно перенести парочку в свои сервисы

2024-11-05 19:20 UTC, 24slavaK commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +        return null;
почему null ?

2024-11-05 19:20 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +        Event event = eventRepository.findById(id).orElse(null);
Как будто лучше orElseThrow

2024-11-05 19:20 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +        List<Event> events = eventRepository.findAllByUserId(userId);
валидация на аидишник не помешала бы

2024-11-05 22:53 UTC, m1rroxxx reviewed
немнго не понял зачем дженерики в валидации и там же ещё создаешь интерфейс который наследуешь от интерфейса и его имплементируешь
если юзать дженерики то нужно делать так что бы твой интерфейс можно было реализовать для любой dto в мире, просто заимплементив его, а вообще там вроде топовые анатации валидации есть про которые нам потом расскажут, так что с этим можно не заморачиваться

2024-11-05 22:53 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +@Data
в @Data входят геттеры и сетторы, а в серивсе их не должно быть, так теряется весь смысл сервиса, потому что любой человек возьмёт поле через геттер, поменяет его как хочет, и запишет через сеттер
можешь просто добавить @RequiredArgsConstructor

2024-11-05 22:53 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +    private List<EventFilter> eventFilters;
вот тут ты можешь вместо @Autowired сделать поля final и они добавятся через @RequiredArgsConstructor

2024-11-05 22:53 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/validator/event/EventValidator.java
> +}
как будто это лишнее
![image](https://github.com/user-attachments/assets/dc6efe31-f61a-4123-8b0d-be771316582b)
![image](https://github.com/user-attachments/assets/a8a420fe-2433-476e-ada2-99d33d2b21cf)
наверное можно сделать вот так (если это вообще нужно), просто я ещё не очень понимаю зачем тут дженерики
сделай просто интерфейс и имплементируй его каждым валидатором как с фильтрами

2024-11-06 13:11 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +    private final UserRepository userRepository;
кажется, если от репозитория не нужна никакая бизнес логика, а только доступ к данным, то считается хорошей практикой инжектить именно репозитории, а не сервисы

2024-11-06 13:12 UTC, GasDa commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +        return null;
Поправил, спасибо!

2024-11-06 13:13 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +        Event event = eventRepository.findById(id).orElse(null);
кажется, зависит от бизнес логики, но поменял, тоже норм. Спасибо!

2024-11-06 14:23 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +        List<Event> events = eventRepository.findAllByUserId(userId);
так это же примитивная переменная, не очень понятно, что там валидировать

2024-11-06 14:25 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +@Data
я специально убрал @requiredargsconstructor и поставил data, по совету Влада, вручную заинжектить списки фильтров и валидаторов в сервис для теста.

2024-11-06 14:26 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +    private List<EventFilter> eventFilters;
отписал выше, специально для тестов сделал, попробую тесты переписать

2024-11-06 14:27 UTC, GasDa commented on src/main/java/school/faang/user_service/validator/event/EventValidator.java
> +}
я это сделал специально, общий механизм валидации, и конкретный интерфейс для спринга EventValidator, который собирает в список только EventValidator, а не все валидаторы проекта

2024-11-07 12:28 UTC, MiraGlaceon requested changes

2024-11-07 12:28 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +//@RequestMapping("/events")
Почему решил не оставлять RestController? Понимаю, что пригодиться в будущем, но можно сразу оставить. Было все верно. Только возвращаемый результат из методов через ResponseEntity бы доработали

2024-11-07 12:28 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        System.out.println("Number of EventValidators injected: " + eventValidators.size());
Давай вместо system out будем использовать логирование. Этого можно добиться с помощью аннотации Slf4j

2024-11-07 12:28 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/validator/event/EventOwnerValidator.java
> +public class EventOwnerValidator implements EventValidator {
Давай уберем всю логику связанную с Validator<>. Я понял твои намерения, но есть лучший способ это сделать.
Например в EventDto над полями можно повесить нужную аннотацию с условием "значение больше нуля" или "не может быть null", типа NotNull. Для этого нужно изучить ConstraintValidator.
Как ты настроишь Dto, можно будет в параметрах метода контроллера, рядом с параметром DTO вешать аннотацию Valid.
Spring автоматом провалидирует нужные поля и бросит ошибку. Ошибку можно поймать и обработать, если в том же контроллере создать метод с аннотацией @ExceptionHandler. Посмотри и изучи эти вещи. Полезная штука очень

2024-11-07 12:30 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +    private final UserRepository userRepository;
Тут оба правы, лишняя декомпозиция тоже не нужна. Но есть нюанс, обсудим на созвоне его

2024-11-07 19:24 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +    private final UserRepository userRepository;
жду субботы, чтобы обсудить на ретро

2024-11-13 07:39 UTC, GasDa commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +//@RequestMapping("/events")
еще лекции не просмотрел, не было Spring-web, сейчас добавлю

2024-11-13 07:43 UTC, GasDa commented on src/main/java/school/faang/user_service/validator/event/EventOwnerValidator.java
> +public class EventOwnerValidator implements EventValidator {
но была просьба в задаче именно сделать валидаторы, когда пройдем лекции по аннотациям валидации, я конечно переделаю

2024-11-13 07:45 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventServiceImplementation.java
> +    private final UserRepository userRepository;
обсудили на ретро

2024-11-22 18:19 UTC, GasDa commented on src/main/java/school/faang/user_service/service/event/EventService.java
> +        System.out.println("Number of EventValidators injected: " + eventValidators.size());
OK

2024-11-25 14:48 UTC, MiraGlaceon approved these changes

2024-11-25 16:08 UTC, merged