Minotaur master stream7 feature bjs2 40451
CorporationX/user_service pull request #1806
Opened 2024-11-01 19:57 UTC by GadzhiGadzhiev

Создание и настройка скиллов

2024-11-01 21:42 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        if (!skillRepository.findUserSkill(skillId, userId).isPresent()) {
Насколько я понимаю еще для методов принимающих айдишники должна быть валидация на не отрицательные id но такое so so  я не уверен

2024-11-01 21:42 UTC, 24slavaK commented on src/test/java/school/faang/user_service/controller/SkillControllerTest.java
> +        skillDto.setTitle("title");
Как будто создание объекта можно вынести и не засорять память каждый раз создавая новый объект

2024-11-01 21:42 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/SkillService.java
> +
плохая практика закидывать два репозитория в 1 сервис (так в лекции говорилось) лучше например создать SkillOfferService и в него внедрить SkillOfferRepository

2024-11-03 15:28 UTC, m1rroxxx reviewed
из значительного -> лучше валидацию вынести в отдельный класс, или во первый соответствует принципу единственной ответственности и во вторых у тебя половина валидации в контроллере, а половина в сервисе

2024-11-03 15:28 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    private void validateSkill(SkillDto skillDto) {
валидацию лучше вынести в отдельный класс, а то нарушается принцип единственной ответственности

2024-11-03 15:28 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +    SkillDto toDto(Skill skill);
назови или оба метода dtoToEntity entityToDto или просто toDto и toEntity

2024-11-03 15:28 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        if (skillRepository.existsByTitle(skillDto.getTitle())) {
вот эта проверка тоже относиться к валидации, лучше всё валидировать в одном месте

2024-11-03 15:28 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        if (offers.size() >= MIN_SKILL_OFFERS) {
это тоже валидация

2024-11-05 12:05 UTC, MiraGlaceon commented on src/test/java/school/faang/user_service/controller/SkillControllerTest.java
> +        skillDto.setTitle("title");
В тестовом контексте допускается такое, главное не допускать такое в рабочем проекте

2024-11-05 12:06 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/SkillService.java
> +
Вполне допускается, если сервис удовлетворяет логике по работе со скиллами. Можно разделить на два сервиса, в целом, так лучше и сделать, потому что по сущности Skill может быть много методов и логики, что по сущности SkillOffer может быть много кода.

2024-11-05 12:08 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    private void validateSkill(SkillDto skillDto) {
Добавлю что в контроллере не должно быть лишней логики кроме как принять запрос -> отдать сервису -> вернуть ответ, за исключением редких случаев

2024-11-05 12:08 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/mapper/SkillMapper.java
> +    SkillDto toDto(Skill skill);
Поддерживаю

2024-11-05 12:32 UTC, MiraGlaceon requested changes

2024-11-05 12:32 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/dto/skill/SkillCandidateDto.java
> +    private SkillDto sKillDto;
Буквы поехали в названии

2024-11-05 12:32 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        skillValidator.validateExistTitle(skillDto.getTitle());
25 и 27 строчку можно поменять местами. Всегда лучше сначала валидовать данные, а потом идти дальше по коду. Тут у тебя создается skill, тратятся на него память и время, а если валидация не прошла, то он был создан попусту

2024-11-05 12:32 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillMapper.entityToDto(skill);
Тут ты возвращаешь из метода тот же skillDto, ничего не изменилось, но ты запрашиваешь ресурсы маппера на создание нового объекта dto

2024-11-05 12:32 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/validator/SkillValidator.java
> +        if (skillDto.getTitle() == null) {
Можно одной строкой две проверки сделать. Strings.isBlank(skillDto.getTitle())

2024-11-06 11:55 UTC, MiraGlaceon approved these changes

2024-11-06 12:23 UTC, merged