feature-BJS2-40527
CorporationX/user_service pull request #1810
Opened 2024-11-02 10:14 UTC by abzalkhan00

added 4 methods and wrote tests for all cases

2024-11-03 03:59 UTC, mad1xx1dam reviewed
Всё максимально аккуратно и понятно написано!

Есть некоторые мелкие моменты, которые можно подправить, но самое главное - маппинг из сущности в dto, как мне кажется

2024-11-03 03:59 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +    private boolean checkRegistration(long eventId, long userId) {
все приватные методы стоит помещать после всех публичных методов

2024-11-03 03:59 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +        if (repository.findAllParticipantsByEventId(eventId) == null) {
по идее репозиторий вернет не null, а пустой список в случае, если нет записей, удовлетворяющих условию

поэтому проверку на Empty по идее надо, а не на null

2024-11-03 03:59 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +    public List<User> getParticipant(long eventId) {
Не стоит отдавать список целых сущностей. Сначала стоит создать mapper, с помощью которого будешь создавать dto из сущностей (UserDto уже есть)

2024-11-03 03:59 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public List<User> getParticipant(@PathVariable @Min(1) long eventId) {
здесь тогда тоже List<UserDto>

2024-11-03 03:59 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public void unregisterParticipant(@PathVariable @Min(1) long eventId,
Можно, наверное, попробовать возвращать ResponseEntity<Void>: return ResponseEntity.ok().build();

по идее как-то так делается

2024-11-03 03:59 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public int getParticipantsCount(@PathVariable @Min(1) long eventId) {
а здесь ResponseEntity<Integer>

2024-11-03 03:59 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +        service.registerParticipant(eventId, userId);
тут можно перед этим явно указать when(repository.findAllParticipantsByEventId(eventId)).thenReturn(Collections.emptyList()), чтобы явно указать, что нет еще такой регистрации

просто для явного воссоздания ситуации, как мне кажется

2024-11-03 03:59 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +    void isParticipantRegisteredTest() {
в названии, наверное, стоит явно указать, какой метод тестишь + что за ситуация в этом тесте

2024-11-03 03:59 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +    void emptyEventTest() {
тут тоже стоит явно указать, что за метод тестишь

2024-11-03 03:59 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +        when(repository.findAllParticipantsByEventId(eventId)).thenReturn(null);
thenReturn(Collections.emptyList()) тогда: репозиторий должен вернуть пустой список

2024-11-03 03:59 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +        assertEquals(mockUsers, service.getParticipant(eventId));
тут тогда поменяется, если сделаешь возвращаемым значением список Dto, а не конкретно User

2024-11-03 10:55 UTC, abzalkhan00 commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +        if (repository.findAllParticipantsByEventId(eventId) == null) {
А вдруг там просто выведется event у которого просто никто еще не зарегистрировался? Проверка на null не будет правильней?

2024-11-03 12:36 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +        if (repository.findAllParticipantsByEventId(eventId) == null) {
Я просто глянул, как работает подобный метод из репозитория JPA. Если вызываешь такой метод, он должен вернуть список пользователей, зарегистрированных на это событие, то есть не может быть такого, что попадется событие, которое как бы существует в таблице, на на него никто не зарегистрирован. 

Там таблица по идее имеет два основных поля: event_id, user_id. Если что-то нашлось, он положит в список и вернет. Если ничего не нашлось, то вернет просто пустой список, но не null. 

Поэтому написал, что проверять не на null стоит, которого в принципе не может быть, насколько я понимаю

2024-11-03 13:18 UTC, abzalkhan00 commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +        if (repository.findAllParticipantsByEventId(eventId) == null) {
Как правильно проверить, что при запросе введён правильный eventId, то есть существующий?

2024-11-03 15:41 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring")
по идее unmappedTargetPolicy надо еще

2024-11-03 15:41 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +                .toList();
👍

2024-11-03 15:41 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public ResponseEntity<Void> registerParticipant(@PathVariable @Min(1) long eventId,
👍

2024-11-03 15:41 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +        when(repository.findAllParticipantsByEventId(eventId)).thenReturn(null);
пустой список вместо null

2024-11-03 15:41 UTC, mad1xx1dam commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +        assertEquals(List.of(mockUserDto), service.getParticipant(eventId));
здорово, но если что можно попробовать mapper не мокать полноценно, а spy на него повесить (функционал сохранить), тогда можно в тесте будет еще поля проверить

вообще и без этого супер, мне кажется

p.s. насчет spy: тест чуть более глубокий по проверкам можно будет сделать, я думаю

2024-11-03 16:03 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +        if (repository.findAllParticipantsByEventId(eventId) == null) {
вообще можно использовать eventRepository, чтобы явно проверить существование такого event

но, как я понимаю, тогда надо будет создать eventService, чтобы обращаться через него к этому репозиторию

в этой задаче, я так понимаю, достаточно проверить, что на указанный id ивента нет зареганных пользователей

2024-11-03 21:20 UTC, VovaBuzivskyi commented
Посмотрел код, после ревью Максима не осталось на что и замечания делать)) .

2024-11-03 21:20 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +                .anyMatch(user -> user.getId() == userId);
Если я не ошибаюсь ,то у юзеров там Id это обертка , а не примитив .По этому лучше сравнивать по equals.

2024-11-04 08:52 UTC, mad1xx1dam commented on src/main/java/school/faang/user_service/service/EventParticipationService.java
> +                .anyMatch(user -> user.getId() == userId);
там по идее, когда сравниваешь Long и long, unboxing из Long в long произойдет автоматически, поэтому == нормально сработает

2024-11-04 17:18 UTC, BobrAll reviewed
Отлично, хороший код! Немного фиксов и можно вливать.

P.S. глянь еще на организацию папок в мастер ветке (для всех классов нужно свои папки создать еще)

2024-11-04 17:18 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @GetMapping("/{eventId}/getAllParicipant")
По REST принято путь в таких эндпоинтах делать /{eventId}/participants, GET у нас в качестве метода, поэтому в пути его можно не писать, а participants и allParticipants тождественны, но первый вариант лаконичнее.

Вот хорошая [статья](https://restfulapi.net/resource-naming/) по этому поводу, там в пункте 1.2 можно это найти

2024-11-04 17:18 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @GetMapping("/{eventId}/getParticipantsCount")
а тут можно /{eventId}/participants/count

2024-11-04 17:18 UTC, BobrAll commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.ERROR)
А нам нужно тут ERROR?

2024-11-04 17:18 UTC, BobrAll commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +        prepareData();
На последнем Retro договорились всю подготовку метода делать в самом методе (может быть немного дублирования, но тесты - единственное место, где оно допустимо). При этом мы получаем большое преимущество - не начнут падать другие тесты, если поменять что-то в общем методе + весь контекст теста виден сразу и легко удостовериться, что он корректен

2024-11-04 17:18 UTC, BobrAll commented on src/test/java/school/faang/user_service/service/EventParticipationServiceTest.java
> +    private UserMapper mapper;
Маппер можно через Spy, вместо Mock. Тогда он будет вести себя как настоящий (нам это подходит, т.к. в нем нет обращения к бд или к чему-либо еще), поэтому мы его можем использовать так, как есть.
Плюс, используя Spy в данном случае - мы не делаем лишнюю работу, что соответствует принципу KISS

2024-11-05 10:58 UTC, abzalkhan00 commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @GetMapping("/{eventId}/getAllParicipant")
Немного не понял про это "P.S. глянь еще на организацию папок в мастер ветке (для всех классов нужно свои папки создать еще)"

2024-11-05 13:39 UTC, abzalkhan00 commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    @GetMapping("/{eventId}/getAllParicipant")
Ааа, нужно было создать отдельные папки для сервисов, контроллеров и т.д.

2024-11-05 16:42 UTC, BobrAll requested changes
Все гуд, только есть пару моментов:э
1) UserDto.java должен лежать в dto/user/ 
2) В мастер ветке там уже есть UserDto, тогда тебе получается нужно использовать его, второй такой же класс ни к чему

2024-11-05 16:43 UTC, BobrAll commented
И еще странно, что UserMapper лежит в mapper/event, а не в mapper/user

2024-11-07 14:29 UTC, BobrAll commented
Отлично, вливаю

2024-11-07 14:29 UTC, merged