feat(mentorship): имплементировал базовую логику для системы менторства
CorporationX/user_service pull request #1813
Opened 2024-11-02 11:46 UTC by Sanasar1

- Создал MentorshipService с методами для получения списка менти/менторов, а также для удаления менти/ментора у пользователя
- Создал MentorshipController с методами для получения списка менти/менторов, а также для удаления менти/ментора у пользователя 
- Создал базовый UserDto
- Создал UserMapper для мапинга списка сущностей пользователей в список дто
- Создал UserValidator для проверки, что поданный id пользователя является положительным числом
- Покрыл MentorshipController, MentorshipService и UserValidator тестами

2024-11-03 06:54 UTC, YaKokin requested changes

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
> +        userValidator.validateUserId(userId);
какой смысл проводить эту валидацию, если у нас на параметре стоит @Positive

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
> +        userValidator.validateUserId(userId);
Тоже самое.
К остальным методам такое же замечание

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/validator/UserValidator.java
> +public class UserValidator {
если ты делаешь проверку id с помощью аннотации, то этот валидатор не нужен. давай лучше уберем его и оставим проверку с помощью аннотаций

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        return userMapper.toDto(getUserRelations(userId,
я думаю, что это пере усложнение. код выносят в отдельные методы с целью сократить общий объем дублируемого кода или улучшить читабельность.
код который ты внес в метод getUserRelations (стр. 58) и так отлично читается. объем кода также не сократился, а даже вырос.
когда хочешь вынести какой-то код в метод задай себе пару вопросов:
- уменьшает ли это объем дублируемого кода
- улучшает ли это читабельность

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +                .orElseThrow(() -> new EntityNotFoundException(errorMessage));
хороший выбор. можно еще создать свой ResourceNotFoundException который будет явно говорить о том, что не был найден конкретный ресурс

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        return userMapper.toDto(getUserRelations(userId,
аналогичное замечание как в строках 43-45

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    private void deleteUserRelation(List<User> users, long userIdToDelete, String errorMessage) {
опять же из-за того, что ты пытаешься сделать универсальный метод, название вообще не говорит о том, что конкретно ты хочешь сделать при его вызове в разных ситуациях.
метод должен быть говорящим, чтобы при его чтении сразу был понятен шаг твоего алгоритма

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        boolean exists = users.stream().anyMatch(user -> user.getId() == userIdToDelete);
эта строчка лишняя на мой взгляд, так же, как и пробрасывание исключения на строчке 54 если ментора, которого нужно удалить, не оказался в списке.
1. метод removeIf вернет тебе false если ни один элемент не был из него удален, и это же значение можно будет проверить в if и как-то это обработать.
2. задача твоего метода произвести удаление. если пользователя и так нет в списке менторов, то по сути твой метод был выполнен корректно. зачем тогда кидать исключения, если цель с которой ты вызывал этот метод достигнута?
Лучшей практикой будет действовать по принципу устойчивости  - "Be liberal in what you accept". API который ты делаешь не должен стараться ограничить юзера во всем. Если мы можем позволить передать ему несуществующий id ментора и не нарушить корректность результата, которого нужно было удалить, то давай так и сделаем.

2024-11-03 06:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        deleteUserRelation(mentors, mentorId, "Mentee has no such mentor");
ты удаляешь ментора только из списка, но в базу эти изменения не сохраняются. подумай, как можно сохранить эти изменения.
можно использовать MentorshipRepository для этого или же можешь разобраться с Hibernate и persistent сущностями, если хочешь, чтобы изменения сохранялись автоматически.

также обрати внимание на то, что ты удаляешь ментора из списка юзера, но у самого ментора в его списке менти ты юзера не удаляешь. в итоге у тебя не соблюдается ACID потому что данные остаются несогласованными

2024-11-03 09:55 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
> +        userValidator.validateUserId(userId);
Валидация через аннотации в параметрах метода не работают, я оставил `@Positive` просто чтобы лишний раз подчеркнуть, что userId может принимать только позитивные значения. Сама по себе аннотация тут ничего не делает

2024-11-03 09:59 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        deleteUserRelation(mentors, mentorId, "Mentee has no such mentor");
Я читал, что если мы получаем сущность из репозитория, то она у нас в состоянии managed, и хибер автоматически следит за ее изменениями и обновляет сам в базе. Я сильно глубоко не вникал, поэтому, если что, поправь меня тут
С ACID классное замечание, вроде очевидное, а я совсем забыл про это)

2024-11-03 12:45 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
> +        userValidator.validateUserId(userId);
запускал у себя код с этой аннотацией (даже сам взял ее на вооружение). все работало. нужно будет потом подразобраться.
если аннотация уже ничего не делает, то мне кажется, ее лучше убрать. даже если ты хочешь просто подчеркнуть, что айди должен быть положительным.
человеку, которому будут интересны требования к id, просто посмотрит код метода validateUserId

в целом, не критично, что ты оставил аннотацию. так что если не согласен со мной, можешь оставить.

2024-11-03 12:54 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        deleteUserRelation(mentors, mentorId, "Mentee has no such mentor");
да, все так. в целом этого достаточно. еще посоветовал бы почитать про отношения между сущностями:
многие ко многим, один к одному, один ко многим
пригодится, если дальше будешь активно пользоваться возможностями хибера

2024-11-03 12:54 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
> +        userValidator.validateUserId(userId);
Ну у меня в первой реализации код и был только с аннотацией. Потом тесты начали падать, и я добавил отдельную валидацию. Реально нужно разобраться
Но если так подумать, то действительно кажется, что знать как конкретно входные параметры валидируются необязательно знать с точки зрения абстракции, поэтому я скорее соглашусь с тобой тут. Плюс код хоть и немного, но станет чище

2024-11-03 12:57 UTC, YaKokin commented
Сано, посмотри, пожалуйста, коммент про выбрасывание исключения во время удаления
@Sanasar1

2024-11-03 12:59 UTC, YaKokin commented
В целом молодец. Код чистый и приятно читается. Жду твое мнения насчет коммента про удаление.

2024-11-03 14:11 UTC, Sanasar1 commented
Так я поправил. Сейчас исключение кидается только когда не существует юзера, у которого хотим удалить ментора/менти. А в случае если он есть, но у него нет конкретного ментора/менти, мы ничего не делаем

2024-11-03 14:52 UTC, Sanasar1 commented
Хотя, я сейчас подумал, и не до конца уверен, нужно ли нам кидать исключение даже в случае, если юзера, у которого хотим удалить ментора/менти не существует. Юзер же не просит в явном виде вернуть ему список менторов/менти, поэтому кажется, что и это исключение тут излишне. Что думаешь?

2024-11-03 16:54 UTC, YaKokin commented
Да, давай наверное оставим, как есть. Возможно есть смысл сообщить клиенту, что юзера, у которого хотим удалять ментора нет в базе, чтобы он хотя бы в курсе был и мог как это это обработать.

2024-11-06 06:21 UTC, ipasynkov-epam approved these changes

2024-11-06 06:21 UTC, merged