Участвовать в событии BJS2-40531
CorporationX/user_service pull request #1816
Opened 2024-11-02 14:12 UTC by lomuserg

2024-11-03 12:26 UTC, 24slavaK commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +
а где методы вызывающие нужные методы класса Service у тебя контроллер как будто в абстракции какой то существует

2024-11-03 12:26 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +
насколько я знаю нужна еще валидация на неотрицательные Id но не уверен

2024-11-03 16:19 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +
надо бы сделать полное dto юзера, что бы потом к нему не вовращаться
ведь потом ещё будем юзать его

2024-11-03 16:19 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +            log.warn("User already registered: eventId={}, userId={}", eventId, userId);
то что пользователь зарегистрирован это скорее error чем warn

2024-11-04 10:41 UTC, lomuserg commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +
Я не нашел у других в заданиях каких-то других полей, да и не выходит прикинуть, какие еще нужно добавить.

2024-11-07 12:09 UTC, MiraGlaceon requested changes

2024-11-07 12:09 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +@Controller
Почему ты решил использовать аннотацию Controller вместо Component ?

2024-11-07 12:09 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/validation/EventParticipationServiceValidator.java
> +    public static void validateUserId(long userId) {
У тебя проверки на отрицательный айдишник можно вынести в DTO. Например в UserDto над полей айди повесить нужную аннотацию с условием "значение больше нуля". Для этого нужно изучить ConstraintValidator. 
Как ты настроишь Dto, можно будет в параметрах метода контроллера, рядом с параметром DTO вешать аннотацию Valid. 
Spring автоматом провалидирует нужные поля и бросит ошибку. Ошибку можно поймать и обработать, если в том же контроллере создать метод с аннотацией @ExceptionHandler. Посмотри и изучи эти вещи. Полезная штука очень

2024-11-07 18:58 UTC, lomuserg commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +@Controller
@Controller вешается на классы, которые формируют слой контроллеров. Как я по лекциям понял, отличия от Component только в лучшей читаемости кода.

2024-11-22 14:14 UTC, MiraGlaceon approved these changes

2024-11-24 13:24 UTC, merged