BJS2-40483 - Стать ментором
CorporationX/user_service pull request #1817
Opened 2024-11-02 14:32 UTC by Shakhaev

Реализованна логика в MentorshipService:
- getMentors,
- getMentees,
- deleteMentor,
- deleteMentee.

2024-11-02 15:27 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public boolean deleteMentee(long menteeId, long mentorId) {
В этом методе ты удаляешь менти из списка, но не удаляешь менти из базы.
И что будет если ментор хочет получить все его менти, тогда все равно вернется все менти включаю менти который ментор удалил

2024-11-02 15:28 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public boolean deleteMentor(long menteeId, long mentorId) {
Здесь тоже

2024-11-02 15:34 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public boolean deleteMentee(long menteeId, long mentorId) {
@ZhubanyshZh метод removeIf в случае true совершает удаление и на уровне БД. Сегодня Влад указал мне на этот неочевидный факт.

2024-11-02 15:36 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public boolean deleteMentee(long menteeId, long mentorId) {
Ок

2024-11-02 18:55 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public boolean deleteMentee(long menteeId, long mentorId) {
@ZhubanyshZh подробнее изучил этот вопрос, задав его в ChatGPT, он мне сказал, что автоматического обновления при использовании removeIf не происходит, поэтому, мне следует дополнительно подсохранить обновленную сущность после удаления менти и ментора.

2024-11-03 09:33 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public boolean deleteMentee(long menteeId, long mentorId) {
@ZhubanyshZh Жубаныш, логику доработал - сохранение внес, тесты изменил под эту логику, добавив verify на метод save для репозитория. Если у тебя есть еще какие-то вопросы по логике, оставь комментарий, а если нет, то можешь пожалуйста сделать approve со своей стороны?

2024-11-03 15:34 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public void deleteMentor(long menteeId, long mentorId) {
правильно сделал удалив из базы.
Но этот метод нечего не возвращает, я думаю что правильней будет возвращать ответ об успешным удаление ментора, чтобы фронту было понятно когда дергал этот метод.
Например можно отправить boolean или обновленный список или сам удаленный сущность, Здесь уже по договоренности.

2024-11-03 15:34 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public void deleteMentor(long menteeId, long mentorId) {
После это сделаю approve

2024-11-03 15:42 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public void deleteMentor(long menteeId, long mentorId) {
Согласен! Зачем-то убрал возврат boolean поставил void, сейчас буду исправлять!

2024-11-03 16:37 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +    public void deleteMentor(long menteeId, long mentorId) {
@ZhubanyshZh доработал!

2024-11-03 16:46 UTC, ZhubanyshZh approved these changes

2024-11-05 13:54 UTC, MiraGlaceon requested changes

2024-11-05 13:54 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +@Controller
Почему ты решил использовать аннотацию Controller здесь? Сможет ли пользователь получить твой ответ от контроллера?

2024-11-05 14:22 UTC, Shakhaev commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipController.java
> +@Controller
Здесь я решил использовать аннотацию Controller , чтобы облегчить читаемость кода, а именно - понимание назначения самого класса (контроллера, в данном случае). В будущем, при работе с данным классом-бином (аннотация Controller такая же, как и Component, - просто показывает спрингу, что здесь нужно создать бин, но от этого контроллер не получает какую-то дополнительную логику, это все тот же бин, просто название аннотации дает нам общее понимание, какие у данного класса обязанности). Исходя из моего понимания, в моей реализации контроллера пользователь получить ответ не сможет, так как не использует RestTemplate.

2024-11-06 20:18 UTC, MiraGlaceon approved these changes

2024-11-06 20:32 UTC, merged