Feature/bjs2 40530 event organization
CorporationX/user_service pull request #1818
Opened 2024-11-02 15:06 UTC by ZhubanyshZh

added functionals:
-create event
-get event by event id
-delete event by event id
-get events by filter
-update event
-get owned events by user id
-get participated events by user id

2024-11-03 09:25 UTC, frs717 commented on src/main/java/school/faang/user_service/config/event/EventFilterConfig.java
> +        eventService.setEventFilters(filters);
Можно самостоятельно не set'ать список в бин сервиса. Спринг сам подставит его
`@Bean(value = "eventFilters")`

2024-11-03 09:25 UTC, frs717 commented on src/main/java/school/faang/user_service/config/event/EventFilterConfig.java
> +    public List<EventFilter> getEventFilters(EventTitleFilter eventTitleFilter, EventUserIdFilter eventUserIdFilter) {
Достаточно в сервисе объявить List<EventFilter>. И спринг сам подтянет все бины типа EventFilter в этот список

2024-11-05 14:10 UTC, MiraGlaceon requested changes

2024-11-05 14:10 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public EventDto create(@Valid EventDto eventDto) {
Ты, Жубаныш, достаточно опытный в спринге. Давай попробуем сделать все по красоте и добавить ResponceEntity и мапперы к эндпоинтам.

2024-11-05 15:35 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public EventDto create(@Valid EventDto eventDto) {
я кажется не понял что мапперы к эндпойнтам, Ты подразумеваешь что в параметры методов сервиса класть не сам энтити а дто или вешать эндпойнтам аннотаций как @GetMapping, @DeleteMapping? я не понял

2024-11-06 03:07 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public EventDto create(@Valid EventDto eventDto) {
@MiraGlaceon  можешь после ревью назначить другую задачу

2024-11-06 20:22 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    public EventDto create(@Valid EventDto eventDto) {
Да, я имел ввиду аннотации GetMapping, PostMapping и тд

2024-11-06 20:23 UTC, MiraGlaceon approved these changes

2024-11-08 04:07 UTC, merged