Feature/bjs2 40448 Написание рекомендации
CorporationX/user_service pull request #1819
Opened 2024-11-02 15:18 UTC by aplavina

2024-11-03 09:07 UTC, frs717 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +        User receiver = userService.findById(recommendationDto.getReceiverId())
Если у таблицы в БД заданы внешние ключи, то при попытке сохранения с неверным ключом произойдет ошибка.

И по идее вот эту проверку (дополнительный запрос к БД) можно не делать

2024-11-03 09:40 UTC, frs717 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +public class RecommendationRequestService {
Если это не нужно, то стоит удалить

2024-11-03 09:43 UTC, frs717 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +        return id;
На мой взгляд, возвращать id из параметров метода особого смысла нет. 
Аналогично в контроллере. На вызывающей стороне этот id уже есть

2024-11-03 09:53 UTC, frs717 commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +    @NotNull
Этому NotNull стоит тогда тоже добавить подобный message, как у других

2024-11-03 09:58 UTC, frs717 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +            String errorMessage = String.join("\n", errorMessages);
Лучше стоит другой разделить использовать. 
В логе и в ответе (в json) перенос строк будет не очень выглядеть и занимать лишнее место

2024-11-04 03:59 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +        validateRecommendation(bindingResult);
Здесь можно не вызывать метод валидаций и принимать bindingResults если у тебя есть @Valid 
Спринг сам сделает это. Нужно просто в метод валидаций вешать нужную аннотацию(@ExceptionHandler(MethodArgumentNotValidException.class))

2024-11-04 04:01 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationController.java
> +        validateRecommendation(bindingResult);
И когда dto пришел не валидным тогда автоматом вызывается метод validateRecommendation

2024-11-05 09:45 UTC, ZhubanyshZh approved these changes

2024-11-05 09:46 UTC, aplavina commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +        User receiver = userService.findById(recommendationDto.getReceiverId())
User к сожалению приходится из бд вытаскивать, для сохранения скилл офферов

2024-11-05 09:47 UTC, aplavina commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationService.java
> +        User receiver = userService.findById(recommendationDto.getReceiverId())
переместила эту логике в метод, где скилл офферы сохраняются

2024-11-05 13:40 UTC, MiraGlaceon requested changes

2024-11-05 13:40 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +@Builder
То что делает эта аннотация ты знаешь, это я увидел. В чем преимущества такого подхода и использование паттерна? Ты понимаешь внутреннее строение паттерна, сможешь описать словами вкратце ?

2024-11-05 16:10 UTC, aplavina commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +@Builder
Builder решает проблему связанную с большим количеством параметров и кучей разных конструкторов со всеми комбинациями этих параметров или разрастающейся иерархией классов (когда вместо добавления новых полей в класс создают наследников с новыми полями). У билдера есть методы для задания параметров, билдер сетает их в конструируемый объяект. В конце можно вызвать build чтобы получить построенный объект. Такой подход позволяет строить объекты только с нужными полями без кучи конструкторов для всех комбинаций параметров.

2024-11-06 20:29 UTC, MiraGlaceon approved these changes

2024-11-08 08:13 UTC, merged