BJS2-40529 Участвовать в событии
CorporationX/user_service pull request #1820
Opened 2024-11-02 16:15 UTC by waylaytessX

2024-11-03 15:25 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +                .stream().anyMatch(user -> user.getId() == userId);
Егор, привет! Длинные цепочки методов при использовании Stream API ухудшают читаемость, если писать их слитно, в одну строку. Со своей стороны предлагаю переместить каждый метод, начинающийся с точки, на новую строчку. Классно, что ты вынес логику проверки, зарегестрирован ли пользователь, в отдельный метод!

2024-11-03 15:25 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +        return eventParticipationRepository.findAllParticipantsByEventId(eventId).stream().map(userMapper::toDto).toList();
Здесь тоже можно переместить каждый метод цепочки Stream API на новую строку.

2024-11-03 15:25 UTC, Shakhaev commented on src/test/java/school/faang/user_service/controller/event/EventParticipationControllerTest.java
> +        Mockito.verify(eventParticipationService, Mockito.times(1)).registerParticipant(EVENT_ID, USER_ID);
Предлагаю вынести класс Mockito в статический импорт, чтобы также улучшить читаемость.

2024-11-03 15:25 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public void registerParticipant(long eventId, long userId) {
Я бы еще добавил валидацию на отрицательные ID евента и юзера.

2024-11-03 15:25 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        Mockito.when(user.getId()).thenReturn(USER_ID);
Считаю, что здесь нет необходимости в методах mock() и when() для User, поскольку мы можем подготовить сущность User для теста, просто создав её через new и применив setter для id - user.setId().

2024-11-03 15:25 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        Assertions.assertThrows(IllegalArgumentException.class, () -> eventParticipationService.registerParticipant(EVENT_ID, USER_ID));
Для большей уверенности в правильном исключении, можно проициниализировать IllegalArgumentException exeption = assertThrows, чтобы ниже заюзать assertEquals для сверки ожидаемого сообщения при исключении с тем сообщением, которое получили из assertThrows.

2024-11-03 15:25 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/event/EventParticipationServiceTest.java
> +        Mockito.when(eventParticipationRepository.findAllParticipantsByEventId(Mockito.anyLong())).thenReturn(new ArrayList<>());
Достаточно длинная конструкция. Попробуй применить статический импорт на Mockito, как я предложил выше, а еще переносить длинные цепочки методов, в том числе для .thenReturn

2024-11-03 17:13 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public void registerParticipant(long eventId, long userId) {
Думаю лучше будет возвращать какой то ответ, а не void

2024-11-03 17:14 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/event/EventParticipationService.java
> +    public void unregisterParticipant(long eventId, long userId) {
Здесь тоже

2024-11-05 10:39 UTC, aplavina requested changes

2024-11-05 10:39 UTC, aplavina commented on src/main/java/school/faang/user_service/dto/UserDto.java
Привет :) По заданию в UserDto просили добавить только id, username и email, думаю лучше убрать лишние данные. Все остальное вроде ок)

2024-11-05 14:00 UTC, MiraGlaceon requested changes

2024-11-05 14:00 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +@Controller
Что делает эта аннотация и почему ты решил ее использовать?

2024-11-05 14:00 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +    public void registerParticipant(long eventId, long userId) {
У тебя контроллер предназначен для общения с пользователем. Попробуй переписать и возвращать результат из методов

2024-11-05 14:37 UTC, waylaytessX commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +@Controller
Поставил эту аннотацию, чтобы явно показать, что это класс контроллера. Насколько знаю, она расширяет аннотацию @Component, поставил именно ее с заделом на будущее

2024-11-06 20:32 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +@Controller
Обсудили на статусе. Такой ответ принимается

2024-11-06 20:35 UTC, MiraGlaceon approved these changes

2024-11-06 20:35 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/event/EventParticipationController.java
> +        try {
В будущем будем писать ExceptionHandler и ControllerAdvice. Там для обработки ошибок будут другие механики. На данный момент для имитации негативного ответа сохраним. Будем править дальше по спринту

2024-11-08 14:46 UTC, flornana approved these changes
все ок

2024-11-25 17:19 UTC, merged