Feature bjs2 40540 Организация события
CorporationX/user_service pull request #1822
Opened 2024-11-02 21:47 UTC by The-Naku

2024-11-03 13:42 UTC, YaKokin requested changes

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +        log.info("Creating event: {}", eventDto);
молодец, что подумала о логировании

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +        log.info("Creating event: {}", eventDto);
логирование полного объекта может раскрыть конфиденциальную информацию, поэтому логировать стоит только идентификаторы и ключевые поля.
Эту строчку можно заменить на:
`log.debug("Creating event. Title: {}", eventDto.getTitle());`
или
`log.debug("Creating event. Title: {}, Date: {}", 
        eventDto.getTitle(), 
        eventDto.getCreatedAt()
    );`
Можно также создать отдельный метод у Entity или DTO для логирования, который будет содержать строку без конфиденциальной информации:
пример, как можно сделать:
`public class UserDto {
    public String toLogString() {
        return String.format("UserDto(id=%d, email=%s)",
            id,
            email
        );
    }
}`

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +        log.info("Event created successfully: {}", createdEvent);
логи лучше делать в сервисе:
 - контроллер должен быть простым
 - более детальное отслеживание бизнес логики
 - если вызов метода сервиса будет производится где-то внутри сервиса, а не со стороны запроса, то логи, которые ты оставила в сервисе, пере используются

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +    public EventDto updateEvent(@RequestBody @Valid EventDto eventDto) {
когда ты предоставляешь ендпоинт для обновления объекта, лучше использовать PATCH или PUT.
Таким образом клиент сразу поймет, для чего нужен этот ендпоинт.
Также учти разницу между PATCH и PUT (здесь идет речь о разнице в семантике этих методов)
PUT используем, когда хотим положить вместо какого-то объекта полностью новый (по сути сделать перезапись как в хэшмапе)
PATCH используем, когда хотим только частично изменить состояние нашего ресурса (представь, что мы вытаскиваем объект из хэшмапы по id и сетим в него что-нибудь, после чего складываем обратно)

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +    @PostMapping("/update")
если учесть комментарий про PATCH, то можно убрать update из пути и просто оставить "/{id}"
так твой REST API станет чище.
метод  PATCH и так скажет клиенту, что это ендпоинт для обновления, поэтому "update" избыточно

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +    @DeleteMapping("/event/delete/{eventId}")
такое же замечание, как и на строке 56. delete избыточно, можно оставить только {eventId}

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +    public List<EventDto> getEventsByFilter(@RequestBody @NotNull EventFilterDto filters) {
По спецификации HTTP Get запросы не должны содержать тело запроса.

лучше передавать поля дто через параметры запроса прямо в url
если дто включает в себя много полей, то лучше присмотреться к PostMapping

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +    public List<EventDto> getEventsByFilter(@RequestBody @NotNull EventFilterDto filters) {
метод принимает один фильтр, поэтому имя параметра должно быть не в множественном числе. лучше сделать просто filter

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/dto/EventFilterDto.java
> +public record EventFilterDto(String title, User owner, String location) {
зачем тебе дто если у тебя одно из его полей - это сущность User?
из-за этого теряется весь смысл создания дто - обезопасить себя и пользователя от изменения сущности.
Если тебе очень нужен пользователь в дто, то лучше создать под него отдельный дто или же просто передавать id овнера

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/filter/event/EventOwnerFilter.java
> +        allEvents.filter(event -> event.getOwner().equals(filters.owner()));
event -> event.getOwner().equals(filters.owner()) нарушает инкапсуляцию.
куда элегантнее будет добавить в Event метод isOwner и передавать ему юзера из фильтра

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/filter/event/EventLocationFilter.java
> +        allEvents.filter(event -> event.getLocation().equals(filters.location()));
такое же замечание как в EventOwnerFilter 
лучше в ивент добавить метод isSameLocation который будет принимать локацию

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/filter/event/EventTittleFilter.java
> +       allEvents.filter(event -> event.getTitle().equals(filters.title()));
аналогично.
сделай через метод isSameTitle

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/filter/event/EventFilter.java
> +public interface EventFilter {
реализации этого интерфейса лучше вынести в папку impl в event

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/EventService.java
> +        eventFilters.stream()
задумка интересная, но этот код не будет работать, как ты ожидаешь.
ты хочешь пробежаться по всем стримам и применить их в списку ивентов. при этом ты хочешь, чтобы каждый фильтр учитывал результат работы другого фильтра.

теперь посмотри на код в реализация фильтра. когда ты пишешь 
`allEvents.filter(event -> event.getLocation().equals(filters.location()));`
ты не применяешь фильтр к стриму, на котором вызываешь filter, а просто создаешь новый стрим, который пропускает элементы из стрима AllEvents через условие, которое ты передаешь в метод filter.

представь, что в этой строке
`Stream<Event> allEvents = eventRepository.findAll().stream();`
 ты создала объект, который просто умеет гонять все элементы из набора ивентов.
 
 когда ты пишешь `allEvents.filter(event -> event.getLocation().equals(filters.location()));`
 ты создаешь **новый** объект, который в добавок к возможности просто гонять элементы из источника умеет еще и применять к ним фильтр и пропускать только те, которые проходят через условие фильтра.
 если ты теперь к полученному объекту снова применишь подобную строчку, например
` allEvents.filter(event -> event.getTitle().equals(filters.title()))`
 то ты снова создашь объект который умеет:
 1. гонять элементы из источника
 2. фильтровать эти элементы по условию `event -> event.getLocation().equals(filters.location())`
 3. фильтровать эти элементы по условию `event -> event.getTitle().equals(filters.title())`
 и эту цепочку можно продолжать бесконечно. в конечном счете тебя тебя интересует самый последний объект в этой цепочке
 
то есть если ты хочешь, чтобы при вызове `allEvents.toList()` ты загоняла все элементы из источника с применением всех фильтров, ты должна каждый раз после создания объекта стрима, который фильтрует элементы, переприсваивать его allEvents, к которому в дальнейшем будут применяться другие филльтры.

подумай над этим.
предлагаю:
1. все также получить стрим allEvents
2. бежать в цикле по списку твоих фильтров
3. проверять для каждого текущего фильтра, можем ли мы его применить.
4. если можем, то вызвать на фильтре apply и результат вызова метода присвоить allEvents

Соответственно, ты также должна учесть, что метод apply теперь должен возвращать Stream<Event>

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/EventService.java
> +                .filter(filter -> filter.isApplicable(filters))
понимаю, что создание фильтров - это часть условие, но у этого есть несколько недостатков.
1. производительность - выполнение фильтрации в памяти требует загрузки всех ивентов из базы в память, что может ухудшить производительность.
2. под каждое поле мы делаем отдельный класс фильтра, который умеет фильтровать набор данных только по этому признаку. да - это расширяемо, но чем больше у нас будет критериев для фильтра, тем больше будет кодовая база и тем тяжелее ее поддерживать.
3. очень много кода дублируется.
 я могу предложить более эффективное решение, которое решает эти недостатки.
 можно выполнять фильтрацию на уровне бд с помощью спецификаций вместе с Spring Data JPA.
 Итого:
 - мы выиграем в производительности
 - код будет легче поддерживать
 - фильтры будет проще комбинировать
 
 если в добавок к этому грамотно применить паттерны проектирования, то можно получить красивый декларативный код с отличной читаемостью.
 я сделал такую реализацию. если хочешь, можем побрейнштормить над ней в войсе

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/EventService.java
> +        Event event = eventRepository.findById(eventId).orElseThrow(() -> new DataValidationException("Event do not found"));
чуть подскажу по код стайлу.
читабельнее будет вот так
` Event event = eventRepository.findById(eventId)
.orElseThrow(() -> new DataValidationException("Event do not found"));`

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/EventService.java
> +            throw new DataValidationException("Event not found");
эта строчка лишняя на мой взгляд

задача твоего метода произвести удаление. если ивента и так нет в базе, то по сути твой метод был выполнен корректно. зачем тогда кидать исключения, если цель с которой ты вызывала этот метод достигнута?
Лучшей практикой будет действовать по принципу устойчивости - "Be liberal in what you accept". API который ты делаешь не должен стараться ограничить юзера во всем. Если мы можем позволить передать ему несуществующий id несуществующего ивента и не нарушить корректность результата, то давай так и сделаем.

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/EventService.java
> +        return eventRepository.existsByTitleAndStartDateAndEndDateAndOwnerAndLocationAndMaxAttendees(
название метода громоздкое и трудно читаемое. если логика метода для репы сложная, то лучше написать свой SQL запрос через аннотацию Query

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/EventService.java
> +        eventRepository.deleteById(eventId);
удаляя ивент из базы мы должны подумать о том, что данный ивент остается еще в списке событий у овнера (у него есть список событий, которыми он владеет ownedEvents)
удаляя ивент из базы также стоит подумать о том, чтобы удалить этот ивент у юзеров, которые являются его участникми.

если не думать про это, то у нас возникнут проблемы с согласованностью данных и нарушится ACID.
к примеру у юзеров в списке ивентов будет содержаться не существующий ивент.

продумай, пожалуйста, эти кейсы и убедись, что после удаления сохраняется согласованность данных

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/EventService.java
> +        Event updatedSavedEvent = eventRepository.save(event);
когда мы обновляем состояние объекта, мы должны изменить уже существующую запись в бд с каким-то определенным id. eventDto не гарантирует нам, что id внутри него не пустой. если ты просто смапишь дто в сущность и при этом не засетишь в сущность id записи в бд, которую нужно обновить, то у тебя просто запишется новая строка. так работать не должно.

в большинстве случаев алгоритм обновления должен выглядеть вот так:
1. достать по айди сущность из базы, которую хотим удалить
2. засетить в нее новые значения
3. положить обратно в базу

насчет id ивента, который мы апдейтим. чтобы не менять дто, лучше принимать его в качестве параметра

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +    public List<EventDto> getEventsByFilter(@RequestBody @NotNull EventFilterDto filters) {
`@GetMapping("/filteredEvents")
public List<EventDto> getEventsByFilter(
        @RequestParam(required = false) String location,
        @RequestParam(required = false) LocalDate startDate,
        @RequestParam(required = false) LocalDate endDate) {
    EventFilterDto filters = new EventFilterDto();
    filters.setLocation(location);
    filters.setStartDate(startDate);
    filters.setEndDate(endDate);`
    
    пример как можно сделать с параметрами через урл

2024-11-03 13:42 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/EventController.java
> +    @GetMapping("/event/{eventId}")
event в урле здесь ни к чему. лучше просто оставить {eventId}
если используешь аннотации мапинга запросов, то советую поверхностно подразобраться с принципами RESTful

2024-11-03 13:47 UTC, YaKokin commented
В целом по коду:
- Пишешь чисто
- читается приятно
- Отличный нейминг
- молодец, что начала разбираться с аннотациями маппинга

по замечанием:
- есть серьезные замечания по логике работы
- хромает проектирование REST API (это норма, т.к. еще не проходили)
- не везде соблюдена инкапсуляция
- внимательнее проектируй дто . в дто не должно быть вложенных сущностей

2024-11-03 15:16 UTC, The-Naku commented on src/main/java/school/faang/user_service/service/EventService.java
> +        Event updatedSavedEvent = eventRepository.save(event);
юзер выбирает event, который хочет изменить, он уже существует и у него есть все поля, и поэтому метод save просто обновляет существующий в бд event

2024-11-03 15:20 UTC, The-Naku commented on src/main/java/school/faang/user_service/service/EventService.java
> +            throw new DataValidationException("Event not found");
исправлено

2024-11-03 15:34 UTC, The-Naku commented on src/main/java/school/faang/user_service/filter/event/EventLocationFilter.java
> +        allEvents.filter(event -> event.getLocation().equals(filters.location()));
в сущности event создать такие методы? а разве будет хорошо, если мы будем в класс с определенным назначением добавлять методы на проверку?

2024-11-03 17:26 UTC, The-Naku commented on src/main/java/school/faang/user_service/service/EventService.java
> +                .filter(filter -> filter.isApplicable(filters))
стоит ли сейчас мне переделывать под spring data jpa, если я только со спрингом познакомилась неделю назад

2024-11-03 17:27 UTC, The-Naku commented on src/main/java/school/faang/user_service/service/EventService.java
> +        return eventRepository.existsByTitleAndStartDateAndEndDateAndOwnerAndLocationAndMaxAttendees(
пп

2024-11-03 23:56 UTC, The-Naku commented on src/main/java/school/faang/user_service/service/EventService.java
> +        Event updatedSavedEvent = eventRepository.save(event);
обсудили, потестили через postman и в бд. если делать просто save dto, которую передает пользователь, то значения которые уже были в сущности перетираются

2024-11-06 06:54 UTC, ipasynkov-epam reviewed
Все хорошо. Теперь - тесты

2024-11-06 06:54 UTC, ipasynkov-epam commented on src/main/java/school/faang/user_service/entity/event/Event.java
> +    public boolean isSameOwnerById(Long id){
не забывай проверять входные значения в паблик методах). Даже если ты точно знаешь что твой код передает валидные значения, этот метод может быть вызван извне, а значит может прийти нулл. И здесь даже не нужно будет бросать исключений: если пришло что то невалидное, значит точно не sameOwner(Title, Location) - и спокойно возвращаешь false :)

2024-11-13 07:42 UTC, ipasynkov-epam approved these changes

2024-11-14 13:30 UTC, merged