Feature/bjs2 40504 Подписка на других пользователей
CorporationX/user_service pull request #1823
Opened 2024-11-03 09:36 UTC by frs717

2024-11-03 17:03 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void followUser(long followerId, long followeeId) {
Привет @frs717
Я думаю что здесь правильней будет возвращать ответ об успешном подписке, чтобы был понятно фронту что подписка удалось успешно

2024-11-03 17:03 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void unfollowUser(long followerId, long followeeId) {
Здесь тоже

2024-11-03 17:09 UTC, ZhubanyshZh commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void unfollowUser(long followerId, long followeeId) {
Думаю что остальное все сделано хорошо

2024-11-05 10:44 UTC, aplavina commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void followUser(long followerId, long followeeId) {
может просто потом статус ответа поставить 200

2024-11-05 14:18 UTC, MiraGlaceon requested changes

2024-11-05 14:18 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RestController
Код хороший
Но почему решил использовать RestController? Вообще в чем смысл контроллера и какая у него связь с HTTP? 
Каким образом контроллер общается с клиентом?

2024-11-05 16:22 UTC, frs717 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RestController
RestController объединяет в себе две аннотации - Controller (по сути просто создает бин) и ResponseBody (ответ преобразовывается в json)

Контроллер обрабатывает http запрос
Запрос состоит из хэдеров и тела запроса
Ответ состоит из - статуса ответа (http code), хэдеров и тела ответа.

Возвращающим типом метода контроллера можно сделать явно **ResponseEntity**<>
Без указания - по дефолту (если запрос отработал на ОК) вернется http 200, тело - json типа возвр. метода и дефолтные системные хэдеры.

В моем случае нет аннотации **RequestMapping**(""), которая позволяет контроллеру принимать запросы. Сейчас это получается просто бин.
Также у методов нет аннотаций **GetMapping**/**PostMapping**/... 

Все параметры методы либо передается как атрибуты в url запроса, либо можно в теле в json.
В нашем случае как понимаю будет через url.

2024-11-05 16:23 UTC, frs717 commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void followUser(long followerId, long followeeId) {
Да, думаю лучше через статус

2024-11-05 16:36 UTC, frs717 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RestController
Добавил возвращаемый тип у методов контроллера

2024-11-06 20:31 UTC, MiraGlaceon approved these changes

2024-11-09 12:51 UTC, merged