BJS2-40441 логика создания рекомендации
CorporationX/user_service pull request #1824
Opened 2024-11-03 09:40 UTC by evgen-backend-rostov

2024-11-04 19:10 UTC, AlexLogino commented on src/main/java/school/faang/user_service/dto/mapper/RecommendationMapper.java
> +public interface RecommendationMapper {
пакет Mapper должен быть на уровень выше (со всеми вместе), а не внутри dto

2024-11-04 19:10 UTC, AlexLogino commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private final UserSkillGuaranteeRepository userSkillGuaranteeRepository;
в условии сказано про "RecommendationRepository и SkillOfferRepository"
точно ли здесь использовано то что нужно?

2024-11-04 19:10 UTC, AlexLogino commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +public record RecommendationDto(
не знаю насчет целесообразности использования record, а не class...
Но точно могу сказать, что лучше делать однотипную логику создания для всех схожих сущностей, в данном случае dto. А то сейчас 2 record, а SkillDto class

2024-11-04 19:10 UTC, AlexLogino commented on .gitignore
> +amplicode.xml
собрался фронт писать для нашей соцсети?)

2024-11-04 20:35 UTC, jibulani requested changes

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    private void recommendationValidator(RecommendationDto recommendation) {
лучше назвать метод validateRecommendation, а то выглядит как название какого-то объекта, а не метода

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +    public RecommendationDto(@Nullable Long id, @NotNull Long authorId, @NotNull Long receiverId, @NotNull String content,
у тебя же в рекорде уже есть описание этих же полей, что приводит к определению конструктора, зачем нужен этот?
чтобы работали валидации, нужна аннотация @Validated, но это пройдем позже

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +    public RecommendationDto(@Nullable Long id, @NotNull Long authorId, @NotNull Long receiverId, @NotNull String content,
в остальных дто аналогичная ситуация

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void checkPresenceUserSkills(RecommendationDto recommendation) {
обычно приватные методы располагают в конце класса или после метода, в котором они вызываются

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        if (recommendation.skillOffers() != null && !recommendation.skillOffers().isEmpty()) {
лучше сначала проверить, что навыки в рекомендации существуют, прежде чем создавать рекомендацию в базе

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        if (userSkills != null && !userSkills.isEmpty()) {
он там и не вернет null, максимум пустой список, поэтому можно сразу маппить на список id, если это действительно нужно

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +            skillIdsFromOffer.forEach(skillId -> {
проще будет отфильтровать userSkills так, чтобы оставить только те, которые есть в recommendation.skillOffers()

дальше по отфильрованным userSkills кажется будет достаточно сохранять UserSkillGuarantee

2024-11-04 20:35 UTC, jibulani commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        return new RecommendationDto(recommendId, recommendation.authorId(), recommendation.receiverId(),
раз тут такое многоэтапное создание рекомендации, будет надежнее из базы ее достать и смаппить на dto

2024-11-05 20:05 UTC, evgen-backend-rostov commented on .gitignore
> +amplicode.xml
😄 не планировал) Это расширешие для Idea Community, которая помогает работать синтаксисом спринга. Без неё в Community нет навигации по бинам

2024-11-05 20:07 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/dto/mapper/RecommendationMapper.java
> +public interface RecommendationMapper {
подсмотрел такое расположение у Стаса в коде. По сути, маппер нужен для работы именно с дто, подумал, такое расположение логично

2024-11-05 20:21 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +    public RecommendationDto(@Nullable Long id, @NotNull Long authorId, @NotNull Long receiverId, @NotNull String content,
Видел в своём проекте на работе при реализации дто вот такую валидацию в конструкторе

this.authorId = Objects.requireNonNull(authorId, "authorId is null");
this.receiverId = Objects.requireNonNull(receiverId, "receiverId is null");
this.content = Objects.requireNonNull(content, "content is null");

Подумал, что так нужно сделать, чтобы ещё на этапе создания дто выбросить ошибку. Значит пока не буду мудрить, уберу это до разъяснений 👌

2024-11-05 20:39 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        if (recommendation.skillOffers() != null && !recommendation.skillOffers().isEmpty()) {
я тоже об этом пудумал, но сбивает с толку условие, что предложений скилов в рекомендации может не быть, поэтому пояляются дублирующиеся блоки if, а мне так не понравилось). Короче, замудрённая задача оказалась, много взаимосвязной логики...

2024-11-09 11:50 UTC, StanislawKO commented on src/main/java/school/faang/user_service/dto/mapper/RecommendationMapper.java
> +public interface RecommendationMapper {
я объединил в папку web все что связанно с сетью - контроллер, дто, мапперы. И я также рассуждал, что мапперы нужны для дто, поэтому должны быть вместе, ну и контроллер гоняет дто наружу и обратно, поэтому его в эту же компанию поместил

2024-11-09 11:58 UTC, StanislawKO commented on src/main/java/school/faang/user_service/dto/mapper/RecommendationMapper.java
> +public interface RecommendationMapper {
и в проектах совершенно разная бывает структура, мне попадался где контроллер помещают в api, entity в persistence, dto и mapper в usecasses

2024-11-09 12:08 UTC, StanislawKO commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +public record RecommendationDto(
у record тоже есть свои преимущества, он неизменяемый, а это очень важно, если используем многопоточное приложение. Если сейчас его использовать, то в дальнейшем будет проще, когда будем внедрять многопоточку. Возможно в record есть еще что то ценное, думаю Евгений более подробно об этом может рассказать

2024-11-09 12:50 UTC, StanislawKO commented on src/main/java/school/faang/user_service/dto/mapper/RecommendationMapper.java
> +    default List<SkillOfferDto> skillOffersToDto(List<SkillOffer> skillOfferList) {
этот метод без аннотации Named работает?

2024-11-09 12:50 UTC, StanislawKO commented on src/main/java/school/faang/user_service/service/SkillOfferService.java
> +@Component
замени аннотацие @Service, в целом это тот же компонент, но так код лучше выглядит и дает больше понимания

2024-11-09 12:50 UTC, StanislawKO commented on src/main/java/school/faang/user_service/service/SkillOfferService.java
> +        skillOfferList.forEach(skillOffer -> skillOfferIds.add(skillOfferRepository.create(skillOffer.skillId(), recommendId)));
здесь я бы сначала проверил действительно ли возвращается id и только после этого добавлял в skillOfferIds

2024-11-09 14:35 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private final UserSkillGuaranteeRepository userSkillGuaranteeRepository;
Да, оказалось, что в условии задачи не всё явно прописано. Этот репозиторий понадобился для сохранения пользователя гарантом к существующему скилу пользователя

2024-11-09 14:46 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/dto/mapper/RecommendationMapper.java
> +    default List<SkillOfferDto> skillOffersToDto(List<SkillOffer> skillOfferList) {
не работает( Исправил, спасибо!

2024-11-09 14:49 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/SkillOfferService.java
> +@Component
Узнал этот момент только в текущем спринте. Начну так писать уже с новой задачи

2024-11-09 14:54 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/SkillOfferService.java
> +        skillOfferList.forEach(skillOffer -> skillOfferIds.add(skillOfferRepository.create(skillOffer.skillId(), recommendId)));
Хорошая идея, спасибо! Поправил)

2024-11-09 21:51 UTC, jibulani approved these changes
хороший код, молодец!
есть несколько замечаний на будущее

2024-11-09 21:51 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +public record RecommendationDto(
ага, еще автоматическое переопределение equals, hashcode, toString, например

2024-11-09 21:51 UTC, jibulani commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public static final int MIN_RECOMMEND_PERIOD = 6;
в java есть Duration для обозначения какого-то интервала времени, но если используешь просто int, то лучше в названии переменной отразить, какой она размерности (месяцы/дни/секунды)
некритично, на будущее

2024-11-09 21:51 UTC, jibulani commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public RecommendationService(RecommendationRepository recommendationRepository,
можно не писать конструкторы, а воспользоваться аннотацией из ломбок RequiredArgsConstructor
некритично

2024-11-09 21:51 UTC, jibulani commented on src/test/java/school/faang/user_service/service/RecommendationServiceTest.java
> +        Assert.assertThrows(DataValidationException.class, () -> recommendationService.create(recommendationDto));
можно еще проверять, что не вызывались репозитории и текст ошибки
некритично, на будущее

2024-11-09 21:51 UTC, merged