Manticore master stream7 bjs2 40433
CorporationX/user_service pull request #1834
Opened 2024-11-04 06:28 UTC by Kitamuro

2024-11-04 19:30 UTC, VovaBuzivskyi commented
Код написан хорошо, валидация вынесена в отдельные методы. Оставил мелкие замечания . Коммиты лучше писать на английском. Нету тестов.

2024-11-04 19:30 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +public class RecommendationDto {
Здесь еще нужны конструкторы, @Builder не плохо бы навесить , с ним будет проще создавать экземпляры для тестов.

2024-11-04 19:30 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/dto/recommendation/RecommendationDto.java
> +    @NotNull
Между полями с аннотациями стоит ставить пустую строку.

2024-11-04 19:30 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/dto/recommendation/SkillOfferDto.java
> +@Data
Думаю Data здесь лишняя ,так как нужны только сеттеры и геттеры.

2024-11-04 19:30 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/dto/recommendation/SkillOfferDto.java
> +public class SkillOfferDto {
Здесь тоже.

2024-11-04 19:30 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    @Mapping(source = "author.id", target = "authorId")
Здесь тоже лучше отступить.

2024-11-04 19:30 UTC, VovaBuzivskyi commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
А смапится ли здесь все само? Или тоже нужно указать явно ,что к чему относится.

2024-11-05 01:10 UTC, abdddev reviewed
Все четенько, но есть пару мест где можно сделать лучше)) по моему мнению
Ждем тесты, я думаю там всплывет пару моментов по коду, когда будешь писать)

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/exception/ErrorMessage.java
о лайк, я похожее сделал на project-service

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    private void validateRecommendation(RecommendationDto recommendationDto) throws DataValidationException {
как то не оч смотрится метод приватный на контроллере, мб на дто лучше сделать валидацию или в отдельном классе?

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/controller/RecommendationController.java
> +    private void validateRecommendation(RecommendationDto recommendationDto) throws DataValidationException {
а у тебя же есть NotNull + Valid для RecommendationDto, получается дублирование
не дойдет даже до этого метода

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +    Recommendation toEntity(RecommendationDto recommendationDto);
как раз на тестах можно будет проверить)

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        Page<Recommendation> recommendations = recRepository.findAllByReceiverId(receiverId, Pageable.unpaged());
попробуй сделать свой метод в RecommendationRepository, который лист вернет, если не используешь пагинацию

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        log.info("Recommendation with id - " + result.getId() + "successfully saved");
Попробуй через {} писать и далее после запятой что туда закидываешь, лучше читается)

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public List<RecommendationDto> getAllGivenRecommendations(long authorId) {
а почему тут нет Transactional?)

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        if (skill.getGuarantees().stream()
я не осилил) какое условие для if
есть пожелание отрефакторить метод и сделать более френдли для ревью)

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +        if (skill.getGuarantees().stream()
а может и норм, но в if такого лучше не делать)

2024-11-05 01:10 UTC, abdddev commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    private void isSkillOfferExists(RecommendationDto recDto) {
как мне писали ранее is/has больше для boolean
а здесь мб validate?

2024-11-05 08:22 UTC, Kitamuro commented on src/main/java/school/faang/user_service/service/RecommendationService.java
> +    public List<RecommendationDto> getAllGivenRecommendations(long authorId) {
я подумал что для вывода данных не требуется транзакционная операция. Их рекомендуют использовать в случае добавления, обновления и удаления данных чтобы не потерять целостность. Но если что я открыт к новому) вдруг что-то напутал.

2024-11-07 15:52 UTC, BobrAll requested changes
Много комментариев, конечно, оставил, но они больше по структурным моментам, сам код очень хороший!

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/Recommendation/RecommendationController.java
> +public class RecommendationController {
У rest есть свои правила по именованию эндпоинтов
Например:
1) В RequestMapping нужно указать множественное число - recommendations (и во всех сущностях, которые указаны в url
2) В названиях не должно быть глаголов эту роль выполняют методы запроса GET - для получения, POST - для добавления чего-либо, PUT - для обновления и т.д., поэтому делать PUT-запрос и добавлять в url слово update - это масло масляное

Таким образом, для обновления и удаления рекомендации мы можем указывать один и тот же путь: /recommendations/{recommendationId}, но с разными методами

Для добавления рекомендации нам достаточно сделать POST на /recommendations. Так как мы знаем, что метод POST что-то добавляет, а глядя на /recommendations - понимаем, что именно
Оставлю тебе на самостоятельный рефакторинг путей для получения списка рекомендаций по автору и по получателю, а то я тут уже все почти расписал)

Есть очень классная статья по правилам написания rest: https://habr.com/ru/articles/351890/

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/service/Recommendation/RecommendationService.java
> +//        skillOfferRepository.deleteAllByRecommendationId(recDto.getId());
Строчки с комментариями пушить не надо

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/mapper/Recommendation/RecommendationMapper.java
> +public interface RecommendationMapper {
Папки именуются в нижнем регистре

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/controller/Recommendation/RecommendationController.java
> +public class RecommendationController {
Тут тоже папка с большой буквы

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/service/Recommendation/RecommendationService.java
> +public class RecommendationService {
И тут

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/validator/Recommendation/RecommendationDtoValidator.java
> +public class RecommendationDtoValidator {
И тут

2024-11-07 15:52 UTC, BobrAll commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationDtoValidatorTest.java
> +public class RecommendationDtoValidatorTest {
Тест лежит не по тому же пути, что и сам класс

2024-11-07 15:52 UTC, BobrAll commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationDtoValidatorTest.java
> +    public void whenSkillOffersIsNullThenThrowException() {
У нас есть правило для именования тестов (в чате дискорда можно их все глянуть) - в конце каждого теста должно быть слово Test

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/service/Recommendation/RecommendationService.java
> +    private final RecommendationDtoValidator recDtoValidator;
Без сокращений намного легче и быстрее читается код. Когда долго сидишь на одном классе - да, это не проблема. Но если человек решает задачу и ему нужно для этого заглядывать в разные классы - постоянно придется прыгать вверх, чтобы глянуть объявление

2024-11-07 15:52 UTC, BobrAll commented on src/main/java/school/faang/user_service/validator/Recommendation/RecommendationDtoValidator.java
> +    private static final int DIFFERENCE_BETWEEN_DATE_IN_MONTH = 6;
Хорошо, что в константу выделил, но она без контекста выглядит не до конца понятной. Как насчет MONTH_DELAY_BETWEEN_RECOMMENDATIONS?

2024-11-09 17:39 UTC, BobrAll commented
Круто rest исправил, по остальным моментам тоже все хорошо, вливаю

2024-11-09 17:39 UTC, merged