BJS2-40519
CorporationX/user_service pull request #1843
Opened 2024-11-05 19:00 UTC by davidx5x5

2024-11-06 19:27 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    private void validation(@NotNull EventDto event) {
наименование лучше поменять на что-то более конкретное, типа validationEventDto. У тебя может быть несколько валидирующих методов, лучше по названию сразу понимать, что они проверяют

2024-11-06 19:35 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +        if (event.getTitle() == null || event.getTitle().isEmpty() || event.getStartDate() == null || event.getOwnerId() == null || event.getId() == null) {
у тебя срабатывает NullPointerException, потому что, когда event.getTitle() равен null, у тебя на нём вызывается метод .isEmpty()

В этом методе логику валидации лучше разделить на разные блоки if, каждый из которых проверяет своё поле (title, startDate и т.д.). У каждого блока будет свой набор проверок и своё исключение с контретным текстом, типа "Не заполнено описание события".

2024-11-06 19:43 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +
по коду много лишних пробелов, глянь плиз)

2024-11-06 20:01 UTC, evgen-backend-rostov commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +    private User validation(@NotNull EventDto eventDto){
на мой взгляд, сильно напутана логика: метод называется validation и принимает объект EventDto. По идее, он должен провалидировать поля конкретно eventDto и выбросить исключение, если что-то не так. А метод оказыватся идёт в базу за юзером и возвращает его. Метод нужно переименовать

2024-11-07 17:31 UTC, davidx5x5 commented on src/main/java/school/faang/user_service/controller/event/EventController.java
> +    private void validation(@NotNull EventDto event) {
Ок спасибо

2024-11-12 22:14 UTC, jibulani requested changes
в целом все хорошо, молодец!
есть пара небольших комментариев + надо исправить конфликт

2024-11-12 22:14 UTC, jibulani commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +            System.out.println("Событие с id " + id + " удалено.");
в сервисах лучше использовать логгер для сохранения лога его работы
его можно получить, поставив аннотацию `@Slf4j` над классом

2024-11-12 22:14 UTC, jibulani commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +        List<Long> userSkills = user.getSkills().stream()
кажется, дублируется с кодом в create, дублирующийся код лучше вынести в отдельный приватный метод

2024-11-12 22:14 UTC, jibulani commented on src/test/java/school/faang/user_service/service/impl/event/EventServiceTest.java
> +    @InjectMocks
по идее эта аннотация не нужна, раз ты создаешь объект в сетапе

2024-11-12 22:14 UTC, jibulani commented on src/test/java/school/faang/user_service/service/impl/event/EventServiceTest.java
> +    public void testDeleToIdEvent() {
опечатка в названии теста

2024-11-13 17:33 UTC, davidx5x5 commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +        List<Long> userSkills = user.getSkills().stream()
спасибо исправил

2024-11-13 17:44 UTC, davidx5x5 commented on src/test/java/school/faang/user_service/service/impl/event/EventServiceTest.java
> +    public void testDeleToIdEvent() {
исправил, спасибо

2024-11-14 21:18 UTC, jibulani requested changes
есть пара замечаний по сервису, а в остальном все хорошо

2024-11-14 21:18 UTC, jibulani commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +            boolean rezult = true;
зачем нужна эта переменная? просто сделай тип void у метода и кидай из него ошибку при необходимости
сам метод лучше назвать validateOwnerAndEventSkills, например

2024-11-14 21:18 UTC, jibulani commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +            logger.info("Событие с id {} удалено.", id);
ты же добавил аннотацию @Slf4j, она сразу дает log для логгирования, свою переменную не надо создавать

2024-11-14 21:18 UTC, jibulani commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +
лишняя пустая строка

2024-11-14 21:47 UTC, davidx5x5 commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +
jr

2024-11-14 21:49 UTC, davidx5x5 commented on src/main/java/school/faang/user_service/service/impl/event/EventServiceImpl.java
> +            logger.info("Событие с id {} удалено.", id);
не знал, а то она красной выделяло))

2024-11-14 22:20 UTC, jibulani approved these changes
супер!

2024-11-14 22:20 UTC, merged