Feature bc 40480 Mentors/Mentees (without test)
CorporationX/user_service pull request #1846
Opened 2024-11-05 21:17 UTC by Galay007

2024-11-06 06:14 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +@RequiredArgsConstructor
Почему аннотация Component a не Service ?

2024-11-06 06:14 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +@RequiredArgsConstructor
Не вижу логирования

2024-11-06 06:15 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
> +@RequiredArgsConstructor
Почему аннотация не Controller?

2024-11-06 06:18 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +            throw new RuntimeException(userId + " has no mentees");
по условию задачи если список пуст то возвращаем пустой список у тебя же завершается ошибкой

2024-11-06 06:19 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    List<User> findByUsernameLike(String username);
A SQL запрос не нужен для этого метода?

2024-11-06 16:14 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +@RequiredArgsConstructor
upd: Можно оставить Component.

2024-11-06 17:10 UTC, Galay007 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +@RequiredArgsConstructor
Отлично!

2024-11-06 20:47 UTC, Galay007 commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    List<User> findByUsernameLike(String username);
Сам не понял, как он мне его предложил. Но я учел твое замечание и добавил метод-запрос. Спасибо!

2024-11-06 20:48 UTC, Galay007 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +@RequiredArgsConstructor
Логи добавил.

2024-11-06 20:48 UTC, Galay007 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +            throw new RuntimeException(userId + " has no mentees");
Исправил.

2024-11-07 10:12 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipService.java
>          }
К сожалению не то, ты уверен что после  throw new RuntimeException(userId + " has no mentees") работа программы продолжиться?
И даже если продолжиться то получается если пользователь не существует то вернется пустой array list
Я бы сделал два if
 if (user.isPresent){
        if (user.get().getMentees().isEmpty())){
                       return new ArrayList<>();
         } 
       return menteesMapper.toDto(user.get().getMentees());
} else { 
 throw new RuntimeException(userId + " has no mentees");
}

2024-11-07 10:16 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +@RequiredArgsConstructor
> Логи добавил.

не увидел)
поставь аннотацию над классом @Log4j2
и замени System.out.println (-//-); на log.error(-//-) или log.info в зависимости от типа нотификации.
В требованиях к задаче нету про логирование, но так будет красивее и привальней)

2024-11-07 12:19 UTC, Galay007 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
>          }
Руслан, у меня метод getUser возвращает найденного юзера (непустого). Сейчас только добавлю туда, что если нет такого юзера в БД, то кидай runTimeException.

2024-11-07 18:15 UTC, RuslanGabd commented on src/main/java/school/faang/user_service/service/MentorshipService.java
>          }
Анатолий, у тебя же условие (user.isPresent() && !user.get().getMentees().isEmpty()). Получается else может быть в двух случаях"
 1) юзера нету
2) юзер есть, список пуст
но с одним циклом if мы не можем понять, какой именно случай вызвал else.
поэтому я предложил два if (){}

2024-11-07 18:22 UTC, RuslanGabd approved these changes

2024-11-08 21:12 UTC, jibulani requested changes
нормуль, нужно немного подправить и написать unit-тесты

2024-11-08 21:12 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +                return userRepository.findUserById(userId);
получается, ты дважды ходишь в базу за пользователем, не надо так

2024-11-08 21:12 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/MenteesDto.java
> +@Component
зачем тут компонент?

2024-11-08 21:12 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/MentorsDto.java
> +@Component
зачем тут компонент?

2024-11-08 21:12 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/MentorshipController.java
> +@RequiredArgsConstructor
на данном этапе изучения достаточно компонента, потому что контроллеры еще не прошли

2024-11-08 21:12 UTC, jibulani commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    Optional<User> findUserById(long userId);
у тебя же уже есть `userRepository.findById(userId)`, который ты даже использовал, зачем еще этот метод?

2024-11-08 21:12 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +            mentor.get().getMentees().removeIf(user -> user.getId().equals(menteeId));
после удаления надо сохранить изменения в базе через метод save у репозитория

2024-11-08 21:12 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +            mentee.get().getMentees().removeIf(user -> user.getId().equals(mentorId));
и тут save нужен

2024-11-09 08:07 UTC, Galay007 commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    Optional<User> findUserById(long userId);
![image](https://github.com/user-attachments/assets/454c4e8d-7287-4dfd-933c-ae12d0d6ccc3)
Женя, а как увидеть реализацию findUserById? или она спрятана под капотом спринга?

2024-11-14 21:19 UTC, jibulani commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    Optional<User> findUserById(long userId);
да, запрос выглядит правильно :)

2024-11-14 21:29 UTC, jibulani requested changes
в целом ок, но нужно поправить несколько замечаний

2024-11-14 21:29 UTC, jibulani commented on src/main/java/school/faang/user_service/repository/UserRepository.java
> +    List<User> findByUsernameLike(String username);
раз не используешь, значит надо удалить

2024-11-14 21:29 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        if (!user.getMentees().isEmpty()) {
это точно надо проверять, пустой список он не смаппит на другой пустой список просто?

2024-11-14 21:29 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +            log.error("SaveUser exception {}", e.getMessage());
если при сохранении произошла ошибка, то нужно, чтобы клиент об этом знал, то есть ее нужно выкинуть (можно смаппить на другую ошибку, но просто игнорировать не надо)

2024-11-19 18:00 UTC, Galay007 commented on src/main/java/school/faang/user_service/service/MentorshipService.java
> +        if (!user.getMentees().isEmpty()) {
Идея была в логировании пустого списка. Но проще согласиться)

2024-11-19 20:02 UTC, jibulani approved these changes
все хорошо, в прод!

2024-11-19 20:03 UTC, merged