Создание и настройка скиллов
CorporationX/user_service pull request #1865
Opened 2024-11-07 07:59 UTC by bozhedar

2024-11-07 10:59 UTC, Shakhaev commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    public boolean validateSkill(SkillDto skill) {
Богдан, привет! Поскольку метод, валидирующий скиллы, является внутренней логикой контроллера, его можно объявить private и, следуя правилам чистого кода, его можно поместить в самоме низу, после методов public.

2024-11-07 10:59 UTC, Shakhaev commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +        } else throw new IllegalArgumentException("Имя не должно быть пустым.");
Предлагаю выбрасывать исключение  с данным сообщением внутри метода валидации именно для ситуации с пустым именем, а для null-объекта можно выбросить другое исключение с сообщением о недопустимости null (в том же методе с валидацией). В твоей ситуации, если скилл валидацию не прошел, например, потому что кто-то в параметры метода передал объект null, выбросится исключение с текстом "Имя не должно быть пустым", но оно ведь не пустое, а null.

2024-11-07 10:59 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/SkillControllerTest.java
> +public class SkillControllerTest {
В данном тесте ты проверяешь работоспособность валидации, но раз ты обозначил тест как проверку именно контроллера, предлагаю протестировать и остальные методы контроллера

2024-11-07 11:17 UTC, bozhedar commented on src/test/java/school/faang/user_service/service/SkillControllerTest.java
> +public class SkillControllerTest {
на последнем созвоне обсуждали с Денисом что стоит тестировать методы в которых описана какая-то логика. В классе контроллера толком логики нет кроме метода валидирования, по этому я не стал писать для них тесты

2024-11-08 07:50 UTC, Shakhaev approved these changes

2024-11-08 11:54 UTC, MiraGlaceon requested changes

2024-11-08 11:54 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    private void validateSkill(SkillDto skill) {
Давай валидацию вынесем в сервис по работе со скиллами. Тогда у тебя по скиллам будет отведенное место, в котором можно работать с ними. А в контроллере оставим место для того чтобы принять запрос и отдать ответ. Дальше по программе буткемпа контроллер обзаведется новой логикой

2024-11-08 11:54 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +        if (skill.getTitle().isEmpty()){
Обе проверки можно объединить в одну методом Strings.isBlank(skill.getTitle())

2024-11-08 11:54 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/mapper/SkillCandidateMapper.java
> +    public List<SkillCandidateDto> toCandidateDto(List<Skill> skills){
Для SkillCandidateDto так же можно написать mapper, по аналогии со SkillMapper. Не забывай, что в маппере можно добавлять аннотации для полей, чтобы указать, как маппер должен поступить с полем в той или иной ситуации. 
Вот эта статья с хабра прям хорошая https://habr.com/ru/articles/818489/
Там есть темы, которые будем изучать впереди, но с MapStruct тут можно ознакомиться поближе

2024-11-09 08:19 UTC, bozhedar commented on src/main/java/school/faang/user_service/mapper/SkillCandidateMapper.java
> +    public List<SkillCandidateDto> toCandidateDto(List<Skill> skills){
со статьей ознакомился, всё понятно до момента где начинается POST метод. Свой маппер написал потому что здесь для меня сложный маппинг, нужно смапить из скилл в поле скилл дто и добавить в поле количество сколько раз этот скилл встречается. Не хотелось в дебри на день-два уходить, потому что и так по задаче опаздываю. Нужно ли мне сделать этот мапер при помощи мапстракт или же лучше перейти к следующей задаче?

2024-11-11 21:09 UTC, MiraGlaceon requested changes

2024-11-11 21:09 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +public class SkillController {
Здесь все хорошо, теперь давай доработаем контроллер по теме 7го спринта. Добавим RestController и ответы будем возвращать через класс ResponseEntity

2024-11-11 21:09 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/mapper/SkillCandidateMapper.java
> +    public List<SkillCandidateDto> toCandidateDto(List<Skill> skills){
Этот маппер оставь. Еще будет время попрактиковаться с ними. Луше удели время контроллеру, он по теме 7го спринта и важно разобраться

2024-11-18 15:22 UTC, MiraGlaceon approved these changes

2024-11-22 15:05 UTC, merged