Feature/pipeline bc bjs2 40777
CorporationX/user_service pull request #1867
Opened 2024-11-07 10:01 UTC by RuslanGabd

2024-11-07 20:46 UTC, jibulani requested changes
в целом хорошо, но нужно поправить немного

2024-11-07 20:46 UTC, jibulani commented on .github/workflows/ci.yml
> +on: [ pull_request ]
лучше настроить в привязке к ветке команды:
```
on:
  push:
    branches:
      - Murloc-master-stream7
  pull_request:
    branches:
      - Murloc-master-stream7
```

2024-11-07 20:46 UTC, jibulani commented on .github/workflows/ci.yml
> +      - name: Cache Gradle packages
для чего этот шаг?

2024-11-07 20:46 UTC, jibulani commented on .github/workflows/ci.yml
> +
еще нужно добавить запуск тестов:

```
      - name: Unit Tests
        run: ./gradlew test
```

2024-11-08 13:36 UTC, RuslanGabd commented on .github/workflows/ci.yml
> +on: [ pull_request ]
ок, исправил

2024-11-08 13:37 UTC, RuslanGabd commented on .github/workflows/ci.yml
> +      - name: Cache Gradle packages
Кэширование зависимостей Gradle ускоряет процесс сборки, избегая необходимости загружать зависимости при каждом запуске. Это особенно полезно в рабочих процессах CI/CD, где зависимости в противном случае пришлось бы загружать каждый раз при запуске конвейера.

2024-11-08 13:38 UTC, RuslanGabd commented on .github/workflows/ci.yml
> +
Gradle же когда делает build запускает все тесты в проекте. Могу добавить но не будет ли это излишним?

2024-11-08 18:49 UTC, jibulani commented on .github/workflows/ci.yml
> +
можно сначала запустить тесты, если все ок, то уже полный билд

2024-11-08 18:50 UTC, jibulani requested changes
давай все-таки добавим шаг с тестами
+ видимо придется в этом коммите поправить тесты, чтобы все проверки проходили

2024-11-08 20:31 UTC, RuslanGabd commented
> давай все-таки добавим шаг с тестами и еще видимо придется в этом пул-реквесте поправить тесты, чтобы все проверки проходили

2024-11-08 20:31 UTC, closed without merging

2024-11-08 20:33 UTC, RuslanGabd commented
Так тесты падают которые  Алексей писал, он явно быстрее исправит)