Подписка на других пользователей
CorporationX/user_service pull request #1870
Opened 2024-11-07 13:25 UTC by KandesQ

В некоторых тестах писал очень неструктурированно, в след раз постараюсь получше.
Захардкодил фильтр пользователей. Нет идей как можно это сделать, перепробовал все начиная с reflection,
но не получилось.

2024-11-07 16:42 UTC, m1rroxxx reviewed
по моему валидацию сильно захардкодил, мб можно в отдельный класс хотя бы))

2024-11-07 16:42 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/controller/subscription/SubscriptionController.java
> +    @PostMapping("/unfollow")
как будто сдесть надо @DeleteMapping там у тебя из таблицы удаляются значения

2024-11-07 16:42 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/controller/subscription/SubscriptionController.java
> +    public ResponseEntity<?> followUser(Long followerId, Long followeeId) throws DataValidationException {
![image](https://github.com/user-attachments/assets/4e48fdac-87e2-4521-b034-b082d20f96d6)
возвращай просто DTO)

2024-11-07 16:42 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    public void followUser(Long followerId, Long followeeId) throws DataValidationException {
ты везде после метода пишешь throws DataValidationException
но DataValidationException наследует RuntimeException, а значит это писать по сути не нужно, ты этой записью говоришь типо "проверь я могу выбросить исключение" но оно специально сделано не проверяемый исключением, что бы его не проверять))

2024-11-07 16:42 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    private Boolean filterUser(UserFilterDto filter, User user) {
можно сделать интерфейс UserFilter и имплементировать его каждыйм фильтром, там уже в main ветке есть примеры ( я так делал)) 
просто если когда нужно будет добавить новый фильтр тебе придётся менять код (не соответсвует SOLID open/closed ) + могут упасть тесты сервиса и ещё их придётся менять

2024-11-07 18:29 UTC, KandesQ commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    public void followUser(Long followerId, Long followeeId) throws DataValidationException {
Я когда конфликт решал, пришлось наследовать от RuntimeException, было просто от Exception

2024-11-07 18:31 UTC, KandesQ commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    private Boolean filterUser(UserFilterDto filter, User user) {
Да с SOLID проблема, попробую решить

2024-11-07 18:44 UTC, KandesQ commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    private Boolean filterUser(UserFilterDto filter, User user) {
Но ведь если удалять придется, то это тоже нарушение солид)

2024-11-07 19:40 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +    private Boolean filterUser(UserFilterDto filter, User user) {
если захочешь убрать какой то фильтр, уберешь его из списка фильтров, но функционал как будто не нужно урезать)

2024-11-12 19:09 UTC, MiraGlaceon requested changes

2024-11-12 19:09 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        /**
Что происходит в этом фильтре вкратце сможешь объяснить ?

2024-11-12 19:49 UTC, KandesQ commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        /**
Так тут написано же даже) Проходимся по списку всех фильтров и если хоть один применен, то возвращаем true, чтобы пользователь прошел фильтрацию

2024-11-13 05:48 UTC, KandesQ commented on src/main/java/school/faang/user_service/service/subscription/SubscriptionService.java
> +        /**
Если поподробнее, есть инерфейс UserFilter по моему, у него два метода, первый проверяет указано ли в дтошке поле, по которому проходит фильтрация в имплементации этого интерфейса, второй метод применяет этот фильтр и возвращает boolean в зависимости от результата применения фильтра. False - юзер фильтр не прошел,  true - прошел. Соответственно в реализациях конкретных фильтрах просто пишем фильтр для конкретного поля UserFilterDto. В методе getFilters() проходимся по списку фильтров и если выполнились оба условия (применим и дал положительный результат при применении), то возвращаем true чтобы прошел фильтр. Увидел в след спринте что Влад делает так же, но полностью через стримы и фильтр тоже стрим возвращает, мне понравилось, буду так делать)

2024-11-13 15:21 UTC, MiraGlaceon approved these changes

2024-11-13 18:31 UTC, merged