Feature/bjs2 40611
CorporationX/user_service pull request #1890
Opened 2024-11-08 13:38 UTC by m1rroxxx

Покупка премиум доступа

2024-11-15 15:10 UTC, MiraGlaceon requested changes

2024-11-15 15:10 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/client/PaymentServiceClient.java
> +public interface PaymentServiceClient {
Этот интерфейс сам добавлял? Расскажи как общение между микросервисами происходит

2024-11-15 15:10 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/dto/client/PaymentStatus.java
> +    SUCCESS
А если не успех? Ты вероятно пробрасываешь ошибку в таком случае, но статус создан для того, чтобы обработать запрос штатно с негативным исходом так же

2024-11-15 15:10 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/mapper/DateFormatter.java
> +public class DateFormatter {
Мы с тобой обсуждали эту тему. Не нужно парсить строку в дату. Посмотри, есть ли возможность работать только с классами дат. Изучи вопрос как работает Jackson с датами при оборачивании объекта ответа в контроллере, жду от тебя так же ответ по этому вопросу

2024-11-15 15:47 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/client/PaymentServiceClient.java
> +public interface PaymentServiceClient {
feighclient - это библиотека что бы отправлять http запросы, в скобочках мы указываем данные из application.ymal
Интерфейс представляет собой набор эндпоинтов сервиса к котому мы хотим получить доступ
еще есть анотация @EnableFeignClients в main классе, скорее всего она уже реализует все интерфейсы и всё работает
Этого в лекция ещё не было, я понимаю это примерно вот так)

2024-11-15 15:51 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/dto/client/PaymentStatus.java
> +    SUCCESS
в payment service заглушка где есть только успех, и я не стал ничего менять

2024-11-15 15:51 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/mapper/DateFormatter.java
> +public class DateFormatter {
извеняюсь, забыл убрать)

2024-11-15 15:56 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/dto/client/PaymentStatus.java
> +    SUCCESS
если только будет ошибка соединения какая то то будет исключение feighclient

2024-11-18 15:07 UTC, MiraGlaceon approved these changes

2024-11-18 15:24 UTC, merged

2024-11-18 15:50 UTC, 24slavaK commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        if (premiumRepository.existsByUserId(userId)) {
вот тут надо будет переделать раз у нас будут храниться старые версии покупок