Goal invitation functional
CorporationX/user_service pull request #1904
Opened 2024-11-09 21:44 UTC by SergeyZhitenev

2024-11-15 06:57 UTC, Macacin requested changes

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public GoalInvitationDto acceptInvitation(@PathVariable @NotNull @Positive long id) {
У тебя и так примитивный long, поэтому писать @NotNull необязательно. На самом деле даже если бы у тебя тут был ссылочный Long, писать @NotNull тоже не имело бы смысла, тк @Positive уже подразумевает это в себе

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/controller/goal/GoalInvitationController.java
> +    public GoalInvitationDto acceptInvitation(@PathVariable @NotNull @Positive long id) {
Аналогично для метода ниже

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/dto/goal/GoalInvitationDto.java
> +        @NotNull @Positive Long inviterId,
Тоже самое с  @NotNull

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        log.info("Created goal invitation with id: {}", goalInvitation.getId());
Вроде как Илья вчера на созвоне говорил, что подобное логирование (где просто записывается информация о том, что что-то создалось) неинформативно, и его лучше не делать. Оно не особо помогает при отладке

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/validator/GoalInvitationValidator.java
> +            throw new DataValidationException("The same user cannot be an invited and an inviter");
сори если прям супер сильно душу, но invited это "приглашен" и это не существительное, поэтому частичка an не нужна. Просто для красоты поправить

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/validator/GoalInvitationValidator.java
> +    public void validateInvitation(GoalInvitationDto goalInvitationDto) {
мне кажется вот в этом методе лучше как раз добавить логирование какое-нибудь

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +                .orElseThrow(() -> new EntityNotFoundException("Invitation not found for id: " + id));
Конкатенацию строк лучше не использовать, она ухудшает производительность, форматирование удобнее дополнять, и там еще есть нюансы некоторые, в общем лучше использовать форматирование

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        if (validateWhetherTheUserHasProposedGoal(goalInvitation.getInvited().getId(), goalInvitation.getInviter().getId())) {
честно говоря эти if'ы тяжеловато читаются, но может это мой затуп просто. Может было бы удобнее вынести например goalInvitation.getInvited().getId() в переменную перед условиями, эта конструкция же в любом случае используется в обоих условиях

2024-11-15 06:57 UTC, Macacin commented on src/main/java/school/faang/user_service/service/UserService.java
> +    public User saveUser(User user) {
Тут вроде даже Идея предлагает сделать метод void, тебе же не понадобится возвращаемое значение сущности тут

2024-11-15 07:21 UTC, Macacin commented on src/main/java/school/faang/user_service/service/GoalInvitationService.java
> +        invitedUser.getGoals().add(goalInvitation.getGoal());
Лучше используй тут метод addGoal() из сущности, так инкапсуляция будет получше

2024-11-15 07:21 UTC, Macacin commented on src/test/java/school/faang/user_service/service/GoalInvitationServiceTest.java
> +    private void prepareData() {
вот такое лучше переносить в метод вначале с аннотацией @BeforeEach или @BeforeAll

2024-11-17 15:45 UTC, Macacin approved these changes

2024-11-20 07:20 UTC, ipasynkov-epam approved these changes

2024-11-20 16:04 UTC, closed without merging