Murloc7 s5 b alex subscribtion to users bjs2 40508
CorporationX/user_service pull request #1913
Opened 2024-11-10 15:35 UTC by alexFromAC143937

Task BJS2-40508 + тесты
Как пользователь, я хочу иметь возможность подписываться на других пользователей, чтобы сохранить их контакт для дальнейшей совместной работы.

Необходимо реализовать основные операции: подписаться на пользователя, отписаться от пользователя, получить всех подписчиков, получить количество подписчиков, просмотреть свои подписки и получить количество своих подписок. 

Ниже условия для реализации каждой операции. Делаем их поочередно. Можно делать их разными коммитами и отправлять на ревью каждую операцию отдельно, а можно все сразу.

2024-11-11 12:16 UTC, Alex15265 approved these changes

2024-11-11 12:16 UTC, Alex15265 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @Transactional
Использование аннотации `@Transactional` на контроллере в некоторых случаях может быть оправданным, но обычно это не считается хорошей практикой.

Аннотация `@Transactional` используется для обозначения методов, которые должны выполняться в рамках транзакции базы данных. В контексте контроллера она может привести к неожиданным результатам, особенно если вы используете несколько методов в одном запросе.

Контроллер обычно отвечает за обработку запросов и передачу их на уровень бизнес-логики. Если вы поместите `@Transactional` на контроллер, то все методы в этом контроллере будут выполняться в одной транзакции. Это может вызвать проблемы с производительностью и масштабируемостью, а также усложнить отладку и тестирование.

Вместо этого рекомендуется использовать `@Transactional` на уровне бизнес-логики (сервисах или репозиториях), где это имеет больше смысла. Контроллер же должен просто вызывать эти методы и передавать данные между клиентом и сервером.

2024-11-11 12:16 UTC, Alex15265 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @ResponseStatus(HttpStatus.OK)
как будто лишняя
спринг и так в случае успешного запроса вернет ResponseEntity с 200 статусом

2024-11-11 12:16 UTC, Alex15265 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RequestMapping(UrlServiceParameters.FOLLOWING_SERVICE_URL)
Я уже заливал класс UrlUtils.  Лучше в одном месте все константы держать для urlов. 
Ну и к одному виду привести их.
Вроде как приняли такой: api/user-service/v1/.... итд

2024-11-11 12:16 UTC, Alex15265 commented on src/main/java/school/faang/user_service/extention/DataValidationException.java
> +public class DataValidationException extends RuntimeException {
Уже существует готовая ValidationException, можно было ее использовать)
ну эт такое, субъективное мнение)

2024-11-11 12:16 UTC, Alex15265 commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +public interface SubscriptionService {
тут интересно бы Женю послушать)
много раз видел такие промежуточные интерфейсы для сервисов, репо, контроллеров даже
всегда был такой вопрос, нужны ли они вообще, если по факту у них всегда одна имплементация будет
как в данном случае: вряд ли будет несколько SubscriptionServiceImpl

2024-11-11 12:16 UTC, Alex15265 commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @Transactional
СhatGpt не рекомендует)

2024-11-13 20:58 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +public interface SubscriptionService {
да, тоже часто такое встречал, на мой взгляд полезно делать так по нескольким причинам:
1. соблюдаем D из SOLID - dependency inversion - с наличием интерфейса можем делать зависимости от абстракции, а не от реализации
2. если вдруг все-таки понадобится иметь несколько реализаций, то с готовым интерфейсом это проще сделать
3. при наличии интерфейса спринг скорее всего будет использовать dynamic proxy для работы всяких штук типа `@Transactional`, а это немного производительнее, чем cglib

2024-11-13 21:41 UTC, jibulani requested changes
есть, что исправить + надо исправить конфликты, а то не получится смержить
хорошо покрыл код тестами, молодец!

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +@RequestMapping(UrlUtils.FOLLOWING_SERVICE_URL)
давай приведем к такому же виду, как в других частях проекта: UrlUtils.MAIN_URL + UrlUtils.V1 + UrlUtils.FOLLOWING

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @PostMapping(UrlUtils.FOLLOWING_ADD + UrlUtils.FOLLOWING_PARAMETERS)
UrlUtils.FOLLOWING_ADD  не нужен, сам метод Post уже говорит, что будет что-то создаваться

если ты хочешь, чтобы followerId и followeeId были `@PathVariable`, то FOLLOWING_PARAMETERS должен быть таким: "follower/{followerId}/followee/{followeeId}"
твой текущий FOLLOWING_PARAMETERS больше похож на `@RequestParam`, но тогда для него вообще не нужен FOLLOWING_PARAMETERS

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        if (followerId != followeeId) {
эта проверка дважды используется, лучше вынеси ее в отдельный метод валидации, в котором будешь кидать ошибку при совпадении followerId и followeeId, это позволит переиспользовать данный метод, а код станет выглядеть проще, примерно так:
```
validateFollowerAndFallowee(...)
subscriptionService,followUser(...)
```

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/extention/DataValidationException.java
> +package school.faang.user_service.extention;
почему пакет extention называется? имелось в виду exception?

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @PostMapping(UrlUtils.FOLLOWING_DELETE + UrlUtils.FOLLOWING_PARAMETERS)
UrlUtils.FOLLOWING_DELETE лишний, чтобы указать, что что-то удаляется лучше использовать `@DeleteMapping`

аналогичная ситуация с FOLLOWING_PARAMETERS, что и в followUser

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @GetMapping(UrlUtils.FOLLOWING_FILTER + "{followeeId}")
та же проблема с FOLLOWING_FILTER
лучше дать ему значение "/followers/{followeeId}"

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +    @GetMapping(UrlUtils.FOLLOWING_COUNT + "{followerId}")
та же проблема с FOLLOWING_COUNT 
можно дать ему значение "/followers/{followerId}/count"

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/utilities/ServiceMethods.java
> +public class ServiceMethods {
лучше назвать класс TimeUtils - тогда будет понятно, в чем именно помогает класс и какими методами его логично расширять, а с текущим названием класс со временем рискует разрастись до огромных размеров, потому что в него будут добавлять все подряд

2024-11-13 21:41 UTC, jibulani commented on src/main/java/school/faang/user_service/utilities/UrlUtils.java
> +    public static final String SYSTEM_ID = "001-UserService";
что за SYSTEM_ID? где используется и зачем?

2024-11-13 21:41 UTC, jibulani commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +        MockitoAnnotations.openMocks(this);
обычно вместо этого над классом добавляют аннотацию `@ExtendWith(MockitoExtension.class)`

2024-11-13 21:41 UTC, jibulani commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +        System.out.println(UrlUtils.FOLLOWING_SERVICE_URL +
не надо в тестах ничего печатать дополнительно
.andDo(print()) должно быть достаточно

2024-11-13 21:41 UTC, jibulani commented on src/test/java/school/faang/user_service/handler/ResponseExceptionHandlerTest.java
> +class ResponseExceptionHandlerTest {
не надо такие тесты отдельно выносить, правильная обработка ошибочных сценариев должна быть в тестах на контроллер

2024-11-13 21:41 UTC, jibulani commented on src/test/java/school/faang/user_service/service/impl/SubscriptionServiceImplTest.java
> +    void getFollowersSetAllFilterValueSuccessTest() {
можно подобные тесты объединить в один с помощью `@ParametrizedTest`

2024-11-13 21:41 UTC, jibulani commented on src/test/java/school/faang/user_service/utilities/ServiceMethodsTest.java
> +        assertNotNull(ServiceMethods.getTimeIsoOffsetDateTime(), "ESM001 - Expected a String.");
можно еще формат результата работы метода проверить с помощью регулярки, например

2024-12-04 21:22 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/56d7d57a-705f-4263-bfcf-19ae8f43f8f4)

2024-12-04 21:23 UTC, alexFromAC143937 commented
![image](https://github.com/user-attachments/assets/640f1ec9-5f5a-4a04-a51a-29be9b9e83b7)

2024-12-05 16:35 UTC, jibulani approved these changes
все хорошо, осталось поправить конфликты и можно мержить

2024-12-17 00:49 UTC, merged