Запрос на менторство.
CorporationX/user_service pull request #1919
Opened 2024-11-11 13:44 UTC by DaniyarDostiev

Запрос на менторство.

2024-11-12 14:08 UTC, flornana commented on src/main/java/school/faang/user_service/dto/mentorshiprequest/MentorshipRequestDto.java
> +    @NotNull()
Тут можно указывать сообщение, которое будет пояснять ошибку, например, @NotNull(message = "Requester ID must not be null")

2024-11-12 14:08 UTC, flornana commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    public MentorshipRequestDto acceptRequest(Long requestId) {
Стоит поменитить requestId @NotNull либо поменять на маленький long

2024-11-12 15:05 UTC, DaniyarDostiev commented on src/main/java/school/faang/user_service/dto/mentorshiprequest/MentorshipRequestDto.java
> +    @NotNull()
более информативные ошибки я сделал через обработчик улавливающий DataValidationException.
выглядит примерно так, там берется поле и сообщение по умолчанию.
![image](https://github.com/user-attachments/assets/9f1e2db4-b2f9-473f-9e5d-71d209f01d04)

2024-11-15 11:29 UTC, aplavina commented on src/main/java/school/faang/user_service/dto/mentorshiprequest/MentorshipRequestDto.java
> +    @NotNull()
Круто, я также у себя сделала)

2024-11-15 15:50 UTC, MiraGlaceon requested changes

2024-11-15 15:50 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    public MentorshipRequestDto requestMentorship(@Valid MentorshipRequestDto mentorshipRequestDto) {
Давай на методы контроллера навешаем аннотаций GetMapping, PostMapping и др. Разберись для чего они нужны и дай краткий комментарий

2024-11-15 15:50 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/exception/ValidationExceptionHandler.java
> +public class ValidationExceptionHandler {
За адвайсер большое уважение

2024-11-18 13:27 UTC, DaniyarDostiev commented on src/main/java/school/faang/user_service/controller/MentorshipRequestController.java
> +    public MentorshipRequestDto requestMentorship(@Valid MentorshipRequestDto mentorshipRequestDto) {
В http метод запроса это набор зарезервированных слов, которыми клиент дополнительно поясняет что он хочет сделать по отношению к определенному ресурсу.

Принято использовать следующее соответствие между методами и операциями:
POST - Добавление 
PUT - Полное обновление 
PATCH - Частичное обновление 
DELETE - Удаление 
GET - Получение 

При этом реакция на метод прописывается на стороне серверной части, сам http метод ничего не делает а лишь дает понять намерение.

В Spring web есть набор аннотаций, представляющие http методы, которыми мы можем помечать соответствующие методы контроллера.

2024-11-18 13:47 UTC, DaniyarDostiev commented on src/main/java/school/faang/user_service/exception/ValidationExceptionHandler.java
> +public class ValidationExceptionHandler {
Большое спасибо
Правда пока не совсем уверенно им пользуюсь
В основном для того чтобы в postman в случае ошибок было более красивое сообщение

2024-11-22 14:49 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/exception/ValidationExceptionHandler.java
> +public class ValidationExceptionHandler {
Это отчасти и ответ: обработка ошибок и отдать клиенту в понятной/доступной форме фидбек

2024-11-22 14:49 UTC, MiraGlaceon approved these changes

2024-11-25 16:19 UTC, merged