Покупка премиум доступа (non-experienced part)
CorporationX/user_service pull request #1934
Opened 2024-11-13 13:05 UTC by Macacin

2024-11-14 12:28 UTC, YaKokin requested changes

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +@RestController
давай укажем путь маппинга для всего контроллера. предлагаю "/api/v1/premium/"
v1 - здесь версионирование

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +    @PostMapping("/premium/buy")
тогда здесь достаточно будет указать buy, так как предшествующая часть подставиться автоматически

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +                                 @Positive @RequestBody long id) {
давай укажем, какой конкретно id мы здесь ждем. когда первый раз читаешь, совсем непонятно.
предлагаю написать userId

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClientImpl.java
> +    private final RestTemplate restTemplate;
ты уверен, что оно скомпилируется?
![image](https://github.com/user-attachments/assets/4c2df4ac-9630-4f8d-87b1-5704b7efe55a)

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClient.java
> +public interface PaymentServiceClient {
ни в коем случае не говорю, что так плохо делать. строить приложение на интерфейсах - это хорошая практика, но мне интересно услышать от тебя, какая мотивация была при написании этого интерфейса?

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClientImpl.java
> +public class PaymentServiceClientImpl implements PaymentServiceClient {
предлагаю для межсервисного взаимодействия использовать FeignClient. Он как раз есть в зависимостях проекта.
это более декларативный подход с межсервисному взаимодействию, плюс тебе не нужно будет явно прописывать логику формирования и отправки http запроса. и это я еще не говорю, про поддержку fallback механизмов, кастомных перехватчиков и обработчиков ошибок и поддержку балансировки нагрузки

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/entity/PremiumPeriod.java
> +        throw new DataValidationException("No premium period found for " + days + " days");
лучше не использовать конкатенацию строк при формировании сообщение:
1. у тебя появляются излишние расходы памяти и ресурсов, по скольку при каждой операции конкатенации у тебя создается новый объект строки. + мы создаем излишнюю нагрузку на сборщик мусора.
3. Нам проще добавлять переменные в строку если мы используем форматирование
4. конкатенацию тяжелее поддерживать. к примеру мы захотим ввести поддержку интернационализации (хотя на бэке мы вряд ли будем встраивать эту поддержку для сообщений исключений, но это просто пример). для облегчения поддержки локализации строки выносятся в отдельные файлы. если мы будем использовать конкатенацию, то нам нужно будет думать постоянно про порядок слов (в разных языках он разный) и в какое место правильно впихнуть нужный параметр.

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +            throw new DataValidationException("Payment failed");
если у нас не получилось провести транзакцию в PaymentService это еще не значит, что проблема в валидации. Может сервис просто упал и проблема не в валидации. Подумай, как лучше обработать такую ситуацию.

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        if (premRepo.existsById(userId)) {
давай вынесем этот код в отдельный метод прямо в сервисе.

2024-11-14 12:28 UTC, YaKokin commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +                                 @Positive @RequestBody long id) {
id юзера лучше вынести в параметры урла как ты сделал это с днями

2024-11-15 05:57 UTC, Macacin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClient.java
> +public interface PaymentServiceClient {
насколько я понимаю, вот такие вот клиенты всегда прописываются как интерфейсы, но может я ошибаюсь

2024-11-15 05:58 UTC, Macacin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClientImpl.java
> +    private final RestTemplate restTemplate;
у меня компилилось, но энивей это кусок, я когда делал не до конца понимал как работает межсервисное взаимодействие, сейчас поправлю

2024-11-15 06:18 UTC, Macacin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClientImpl.java
> +public class PaymentServiceClientImpl implements PaymentServiceClient {
Спасибо что подсказал!

2024-11-15 08:01 UTC, YaKokin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClient.java
> +public interface PaymentServiceClient {
да, все так. но реализацию тогда, кажется, не нужно создавать. она сгенерится автоматически

2024-11-15 08:03 UTC, YaKokin commented on src/main/java/school/faang/user_service/client/payment/PaymentServiceClientImpl.java
> +    private final RestTemplate restTemplate;
да, по идее, эта реализация здесь в принципе не нужна. она сама сгенерится на основе интерфейса, если ты пометишь его аннотацией @FeignClient

2024-11-15 08:14 UTC, YaKokin commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +            throw new PaymentException("Payment service is unavailable", e);
зачем здесь блок try catch?
не лучше ли просто выкинуть исключение и обработать его в GlobalExceptionHandler (он уже создан в User Service)

2024-11-15 08:58 UTC, Macacin commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +            throw new PaymentException("Payment service is unavailable", e);
Может немного не так понял, но вроде подравил

2024-11-15 09:31 UTC, YaKokin commented
Молодец, хорошая работа

2024-11-17 05:55 UTC, ipasynkov-epam approved these changes

2024-11-17 15:47 UTC, YaKokin approved these changes

2024-11-20 06:37 UTC, ipasynkov-epam approved these changes

2024-11-20 06:37 UTC, merged