Feature/bjs2 40449 Запрос рекомендации
CorporationX/user_service pull request #1941
Opened 2024-11-15 02:10 UTC by MikhailShap

2024-11-15 09:44 UTC, Shakhaev requested changes

2024-11-15 09:44 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        recommendationRequestService.create(recommendationRequestDto);
В данной строчке ты производишь создание запроса на рекомендацию, но, из-за того, что метод create в сервисе ничего не возвращает, поведение может быть непредсказуемым (а что, если ничего не создалось, или любая другая операция внутри метода create прошла неудачно). Возвращая в методе create саму DTO, с помощью которой ты создаешь запрос, в данном тесте ты можешь просто проиницилизировать объект: RecommendationRequestDto actualDto = recommendationRequestService.create(recommendationRequestDto); 
С какой целью это делать? А можно просто через assertEquals уже сравнить ожидаемую тобой DTO, которую ты отправляешь на создание и ту самую actualDto, которая тебе вернулась из метода create. Я сам таким образом делаю и выявляю в сервисе ошибочную логику (например, в своем сервисе я ожидал нормальную DTO, а на выходе из метода create получал объект null, что позволило мне исправить логику).

2024-11-15 09:44 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public void create(RecommendationRequestDto recommendationRequestDto) {
Привет! Я предполагаю, что в данном методе тоже нужно вернуть DTO, поскольку в контроллере данный метод возвращает ответ клиенту  в виде RecommendationRequestDto. И еще будет удобно тестировать данный метод, чтобы возвращать ожидаемый объект для обеспечения большей прозрачности.

2024-11-15 09:44 UTC, Shakhaev commented on src/main/java/school/faang/user_service/filters/recommendation_request/StatusFilterRecommendation.java
> +public class StatusFilterRecommendation implements RecommendationRequestFilter {
Думаю, стоит подумать над наименованием фильтров. Например, можно назвать как RecomendationStatusFilter.

2024-11-15 09:44 UTC, Shakhaev commented on src/test/java/school/faang/user_service/mapper/RecommendationRequestMapperTest.java
> +    void toDTO() {
В тестах лучше всегда использовать глагол test в начале названия тестового метода.

2024-11-15 09:44 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +    void createWithValidData() {
Здесь тоже лучше приписать глагол test в начале.

2024-11-15 12:04 UTC, MikhailShap commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public void create(RecommendationRequestDto recommendationRequestDto) {
Я просто не знаю , на сколько это здесь нужно , у меня контроллер в принципе уже возвращает дто, или же нам надо после сохранения энтити получить объект, заммапить его в дто и уже его вернуть , это не уточнялось.
А по поводу тестов , ну мы же сами передаем объект и у нас изначально в тестах есть к нему доступ. ну и плюс вроде как главная цель метода , не обработать объект и вернуть его , а просто сохранить в бд.

2024-11-15 12:05 UTC, MikhailShap commented on src/test/java/school/faang/user_service/mapper/RecommendationRequestMapperTest.java
> +    void toDTO() {
Согласен , что то пропустил

2024-11-15 12:13 UTC, MikhailShap commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        recommendationRequestService.create(recommendationRequestDto);
Нам же тут важно проверить , что вызывается метод save с нужным нам аргументом ,в данном случае это отправленная нами дто заммапленная в энтити , в принципе я это и проверяю в следующих строках,
        verify(recommendationRequestRepository).save(captor.capture());
        RecommendationRequest recommendationRequest = captor.getValue();
        assertEquals(recommendationRequestDto.getId(), recommendationRequest.getId());

2024-11-15 12:25 UTC, MikhailShap commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        recommendationRequestService.create(recommendationRequestDto);
(а что, если ничего не создалось, или любая другая операция внутри метода create прошла неудачно)
Если ты это про обычную работу, а не тесты , то мне кажется должна какая то ошибка выбрасываться , в этом моменте я не уверен , предполагаю.

2024-11-15 12:26 UTC, MikhailShap commented on src/main/java/school/faang/user_service/filters/recommendation_request/StatusFilterRecommendation.java
> +public class StatusFilterRecommendation implements RecommendationRequestFilter {
Я переименовал вроде один класс интерфейс и мне автоматом IDEA переименовала реализации , я просто торопился и не стал исправлять , так оставил

2024-11-15 14:12 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        recommendationRequestService.create(recommendationRequestDto);
Да, не заметил, что ты ниже проверяешь айдишники. Впринципе, для большей уверенности в совпадении, можно прям оба объекта дополнительно сравнить: assertEquals(recommendationRequestDto, recommendationRequest;

2024-11-15 14:17 UTC, Shakhaev commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +        recommendationRequestService.create(recommendationRequestDto);
Да, действительно, ты уже сравниваешь ниже айдишники, не заметил. Что касаемо обычной работы метода, то тут тесты мне помогли выявить неправильную логику как раз за счет сравнения не отдельных полей, а целых объектов. Я ожидал получить в ту DTO, которую я отправил в свой метод сервиса, а на выходе получил объект null. Не ошибку, а именно null. Тест и сравнение ожидаемый/реальный результатов помогли мне выявить дыры и неровности в бизнес-логике. Поэтому, я стараюсь избегать void и возвращать DTO, чтобы тестировать, как минимум, было удобно.

2024-11-15 14:21 UTC, Shakhaev commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +    public void create(RecommendationRequestDto recommendationRequestDto) {
Да, цель метода - сохранить сущность, полностью согласен. По сути, в тестах можно и каптором ловить нужный объект, классно, что ты его используешь. По моему мнению, можно иногда подзабыть заиспользовать каптор или запутаться в его применении, поэтому я лично особо с ним не парюсь и , как ты правильно написал, после сохранения энтити получить объект, заммапить его в дто и уже его вернуть.

2024-11-16 10:45 UTC, aplavina commented on src/main/java/school/faang/user_service/dto/filter/RequestFilterDto.java
> +    private RequestStatus status;
Тут тоже можно message добавить

2024-11-18 15:27 UTC, MiraGlaceon requested changes

2024-11-18 15:27 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +public class RecommendationRequestController {
Нужно переписать на RestController

2024-11-19 21:52 UTC, MikhailShap commented on src/main/java/school/faang/user_service/dto/filter/RequestFilterDto.java
> +    private RequestStatus status;
Чуть переписал логику , сделал ее более корректной , поэтому эта аннотация там ни к чему , убрал ее

2024-11-20 12:15 UTC, Shakhaev approved these changes

2024-11-22 14:45 UTC, MiraGlaceon approved these changes

2024-11-22 16:58 UTC, merged