Поиск премиум юзеров
CorporationX/user_service pull request #1964
Opened 2024-11-17 14:04 UTC by SergeyZhitenev

2024-11-22 12:51 UTC, Sanasar1 requested changes

2024-11-22 12:51 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/controller/UserController.java
> +    }
Несколько моментов:
- В эндпойнте не должно быть глаголов
- В эндпойнте не должно быть заглавных букв
- premiumusers в эндпойнте кажется излишним. Я бы оставил api/users/premium
- userFilterDto никуда не передается. Видимо забыл указать `@RequestBody`
- В UserFilterDto есть валидация на входные параметры. Если ты хочешь, чтобы они отвалидировались, то к userFilterDto нужно еще `@Valid` добавить. Но в UserFilterDto стоит `@NotBlank` на некоторых полях, который проверяет, что строка не пустая и не равна null. Если подразумевается, что фильтр по какому-то из параметров может отсутствовать, то лучше убрать аннотацию

2024-11-22 12:51 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserService.java
> +        return userMapper.toDto(filtered_users);
Я бы отсюда возвращал не список дтошек, а список сущностей. Таким образом с методом будет намного проще работать в будущем, если он нам понадобится. Может мы где-то заходим получить список отфильтрованных сущностей пользователей. И было бы удобнее, если бы нам возвращался именно список сущностей, чтобы не делать лишние маппинги. Ну а смаппить в getPremiumUsers не составит труда

2024-11-22 12:51 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserService.java
> +        return userMapper.toDto(filtered_users);
А еще форматирование пострадало)

2024-11-22 12:51 UTC, Sanasar1 commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +    private List<UserFilter> filters;
- Тут мокается не список из фильтров, а просто обычный список с его методами .get(), remove() и т.д. Если хочешь мок на фильтры, то нужно в setUp() написать мок на каждую зависимость через Mockito.mock(UserMapper.class) (как пример) и создать объект класса, который тестируем, через конструктор, в который передаем все моки. Возможно есть другие способы, но я так делаю. Влад об этом на пятом или шестом спринте говорил, прям показывал как мокать список фильтров, можешь поискать
- А еще объект твоего тестируемоего класса находится посреди всех его зависимостей. Я бы вынес его в начало, либо в конец для организованности. Лично я выношу в начало, потому что это самая главная часть всего модуля, но некоторые выносят в конец)

2024-11-27 09:30 UTC, ipasynkov-epam reviewed
Вопрос по тестированию.
+ необходимо решить мерж-конфликты и тогда можно аппрувить)

2024-11-27 09:30 UTC, ipasynkov-epam commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +    private UserMapper userMapper;
не смог найти использование userMapper и filters. Ты создаешь на них моки, -- подскажи, пожалуйста, где они потом используются?

2024-11-27 12:35 UTC, SergeyZhitenev commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +    private UserMapper userMapper;
![image](https://github.com/user-attachments/assets/5521092e-e462-4dcd-be18-e6307efffeb5)
я сделал их моками, чтобы использовать как заглушку во избежании NPE

2024-11-28 16:08 UTC, ipasynkov-epam commented
![image](https://github.com/user-attachments/assets/54a31285-15a0-4089-b248-70fa76b72aa7)

Сергей, есть конфликт в одном файле. Исправь его, пожалуйста, и тогда смержим задачу

2024-11-29 08:53 UTC, Sanasar1 approved these changes

2024-11-29 08:54 UTC, merged