Запрос рекомендации / no tests yet
CorporationX/user_service pull request #1967
Opened 2024-11-17 16:53 UTC by roship

2024-11-17 21:40 UTC, alexFromAC143937 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @Autowired
Можно не писать @Autowired , если 
private final RecommendationRequestService recommendationRequestService;

2024-11-17 21:40 UTC, alexFromAC143937 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    public ResponseEntity<RecommendationRequestDto> requestRecommendation(@Valid @RequestBody RecommendationRequestDto recommendationRequest) {
public ResponseEntity<RecommendationRequestDto> requestRecommendation
можно просто 
public RecommendationRequestDto requestRecommendation
ResponseEntity - это устаревшее

2024-11-17 21:40 UTC, alexFromAC143937 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +    @PostMapping("/request")
@RequestMapping(UrlUtils.MAIN_URL + UrlUtils.V1 + UrlUtils.RECOMMENDATION) - вынесено в переменные
 @PostMapping("/request") -здесь тоже имеет смысл это сделать
 а так как это создание сущьности, можно просто указать
 @PostMapping()
 глобально ты указал ужеранее UrlUtils.RECOMMENDATION

2024-11-17 21:40 UTC, alexFromAC143937 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        if (recommendationRequest.getMessage() == null || recommendationRequest.getMessage().isEmpty()) {
Не критично. Так как это проверка уже содержания ДТО, его можно выполнить в сервисе

2024-11-17 21:40 UTC, alexFromAC143937 commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        RecommendationRequestDto savedDto = recommendationRequestService.create(recommendationRequest);
RecommendationRequestDto savedDto = recommendationRequestService.create(recommendationRequest);
return ResponseEntity.ok().body(savedDto);

так как не нужно ( писал выше), можно написать проще:

return recommendationRequestService.create(recommendationRequest);
- обертка не нужна, 
- статус 200 будет проставлен Спрингом.
        return ResponseEntity.ok().body(savedDto);

2024-11-17 21:40 UTC, alexFromAC143937 commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        //todo какие рода проверки правильно делать в Controller / Service ?
Я так понимаю, что вопрос больше Евгению.
Я для себя сделал вывод, что все такие проверки нужно делать в Сервисе, так как 
- проверить параметры на @NotNull или если это это пе обьект, то @Min(1) - это можно описать еще в строке вызова метода в контролире
- а отальное в сервисе, чтоб не перегружать контроллер, как видится - это не его функция. 
- дополнительно: не нужно один и тот де метод по проверкам писать как в контроллере так и сервисе.
....
Возможно Евгений поправит

2024-11-18 10:49 UTC, roship commented
@alexFromAC143937 Спасибо!

2024-11-20 21:00 UTC, jibulani commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        //todo какие рода проверки правильно делать в Controller / Service ?
пока что в контроллерах проверяем валидность пришедших в запросе данных (не null, значения не выходят за допустимый диапазон и т.д) - то, что позже будем валидировать через аннотации, просто пока еще не изучили это
в сервисах уже проверки связанные с бизнес логикой (наличие юзера в базе, наличие скилла у юзера и т.д.) - то, что обычно требует обращения к другим сервисам или к базе

2024-11-20 21:33 UTC, jibulani requested changes
все хорошо, продолжай работать над задачей и не забудь покрыть код тестами

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/recommendation/RecommendationRequestController.java
> +        if (recommendationRequest.getMessage() == null || recommendationRequest.getMessage().isEmpty()) {
не согласен, логично, что эта проверка здесь, в сервисе проверяем более связанные с бизнес-логикой вещи

предложение по улучшению - вынести валидацию в приватный метод для упрощения кода

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/entity/recommendation/RecommendationRequest.java
> +    // Потому, кажется, самое простое создавать List в методе addSkillRequest
ок, но проверь, что при таком подходе не будут затираться скиллы, если они есть

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +    //todo видимо правильно тут проигнорировать skills, так как SkillRequest из skills создаются в Service после создания RecommendationRequest
почему игнорируешь? у тебя же в дто есть List<Long> skills

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +    //todo правильно ли игнорировать id, createdAt, updatedAt? Так как они создадутся в БД автоматически.
ну вот получаешь entity из БД и маппишь на дто

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +                Но для skillRequest нужно указывать request_id, потому сначала создавать savedRequest, после делать UPDATE savedRequest с добавлением skillRequests.
ну по сути так и сказано сделать в задании - вызвать create - чтобы не создавать сущность самому руками
после этого получить из базы созданный RecommendationRequest и для него создавать SkillRequest-ы

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        /*todo: Приходится создавать пустой список, так как в RecommendationRequest не инициализируется список skills
чтобы этим не заниматься, в задании сказано использовать SkillRequestRepository.create

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        Метод create реализован не корректно?
да, некорректно реализован, можно поправить, как тебе говорит сообщение об ошибке

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        recommendationRequestRepository.save(savedRequest);
для надежности лучше результат вызова save преобразовывать в dto

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        return recommendationRequestMapper.toDto(savedRequest);
здорово, что ты критично смотришь на задание и ищешь свои варианты решения!
если твой вариант работает правильно, можешь использовать его, ничего плохого в этом не вижу

2024-11-20 21:33 UTC, jibulani commented on src/main/java/school/faang/user_service/service/recommendation/RecommendationRequestService.java
> +        return recommendationRequestMapper.toDto(savedRequest);
не забудь потом удалить комментарии, они в итоговом коде не нужны

2024-12-02 20:34 UTC, jibulani requested changes
оставил небольшие замечания, не забывай удалять комментарии в коде
тесты хорошие, молодец!

2024-12-02 20:34 UTC, jibulani commented on src/main/java/school/faang/user_service/entity/recommendation/RecommendationRequest.java
> +    // Потому, кажется, самое простое создавать List в методе addSkillRequest
не надо оставлять в коде комментарии, если это уже финальная версия для мержа

2024-12-02 20:34 UTC, jibulani commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValidException(MethodArgumentNotValidException exception) {
а чем предыдущий вариант не устроил?

2024-12-02 20:34 UTC, jibulani commented on src/test/java/school/faang/user_service/service/recommendation/RecommendationRequestServiceTest.java
> +//    @BeforeEach
лишние комментарии

2024-12-04 19:24 UTC, roshipi commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValidException(MethodArgumentNotValidException exception) {
![Screenshot 2024-12-04 at 22 21 36](https://github.com/user-attachments/assets/8adbfde5-09f1-4044-b148-2006d88b5779)
![Screenshot 2024-12-04 at 22 17 01](https://github.com/user-attachments/assets/e184fa11-cfb4-455a-87e6-aab5607271a3)

На скринах видна разница в теле ответа.
Если собирать ошибки валидации в Map, то красивее.

2024-12-04 19:29 UTC, roship commented on src/main/java/school/faang/user_service/handler/ExceptionApiHandler.java
> +    public ResponseEntity<Object> handleMethodArgumentNotValidException(MethodArgumentNotValidException exception) {
![Screenshot 2024-12-04 at 22 21 36](https://github.com/user-attachments/assets/75311c39-7271-41fc-8318-1dcb0afbc059)
![Screenshot 2024-12-04 at 22 17 01](https://github.com/user-attachments/assets/3fdc58c4-41b6-4f61-b637-1bf97d673ba9)

Если собирать ошибки валидации DTO в Map, то Response body красивее.

2024-12-07 21:29 UTC, roship commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +    //todo видимо правильно тут проигнорировать skills, так как SkillRequest из skills создаются в Service после создания RecommendationRequest
Да, но,  skills это List<SkillRequest>.
А SkillRequest содержит RecommendationRequest request - т.е. обратная ссылка на entity, создаваемую маппером, а ее еще нет в БД.

И я:
1. Cначала вызываю recommendationRequestMapper.toEntity(dto) для формирования Entity
2. recommendationRequestRepository.save(entity) - получаю id
3. Создаю skills, с созданным id
4. Добавляю созданные skills в Entity
5. Повторно делаю save с сформированным списком skills, которые содержат id Entity

Мне кажется нельзя такое сделать через Mapper, такую вложенность.

2025-01-29 19:56 UTC, jibulani approved these changes
супер!

2025-01-29 19:57 UTC, merged