added premium end-point for promotion service
CorporationX/user_service pull request #1975
Opened 2024-11-18 16:16 UTC by 24slavaK

2024-11-19 04:23 UTC, m1rroxxx reviewed
по бизнес логике всё классно, есть замечание по исключениям и логированию)

2024-11-19 04:23 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/controller/premium/PremiumController.java
> +public class PremiumController {
сделай тут по рест что бы везде одинаково было /api/v1/
возможно можно сделать /api/v1/users/buy-premium (тут уже на усмотрение)

2024-11-19 04:23 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        log.warn("trying to get entity from db, might be thrown an exception");
мне кажется это выглядит как описание, здесь если хочешь сделать log надо log.info(получение премиум...)
ну или если такой лог нужна альтернатива, типа "попытка получить из базы может привести к исключению, возьми эту сущность 'вот тут....' "

2024-11-19 04:23 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +                .orElseThrow(() -> new IllegalArgumentException("Пользователь не найден"));
тут лучше EntityNotFoundException

2024-11-19 04:23 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/premium/PremiumService.java
> +        log.info("validate argument for null exception");
я не экспер в английском)) но вроде тут написано "валидируй аргумент потому что может быть null"
нужно слово check, у тебя даже снизу метод называется check, что то типо checking for null

2024-11-19 04:23 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/validator/PremiumServiceValidator.java
> +            throw new NullPointerException("Пустой объект premium");
тут скорее IllegalArgumentException потому что тебе пользователь прислал null -> значит неправильный аргумент
мне кажется NullPointerException это для разраба, если ты какую нибудь либу пишешь
+ NullPointerException не обрабатывается в GlobalHandler, и пользователь не поймёт что он что то сделал не так

2024-11-20 05:03 UTC, vifravl commented on src/test/java/school/faang/user_service/service/premium/PremiumServiceTest.java
> +        secondPremium.setEndDate(LocalDateTime.of(2024, 11, 20, 15, 30));
На dto можно повесить аннотацию @Builder, чтобы не прописывать set несколько раз

2024-11-21 21:39 UTC, m1rroxxx commented on src/main/resources/db/changelog/changeset/user_V008__user_premium_add_column_is_active.sql
> +ADD COLUMN isActive boolean NOT NULL DEFAULT true;
верблюжий стиль (вроде так называется) не работает в бд и там будет столбец isactive, в бд принято писать is_active

2024-11-22 14:20 UTC, MiraGlaceon requested changes

2024-11-22 14:20 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/repository/premium/PremiumRepository.java
> +    @Query(nativeQuery = true, value = "SELECT * FROM user_premium WHERE isactive = true")
Никита уже писал, поле isactive надо переписать на snake_case (underscore) - типа is_active

2024-11-23 18:03 UTC, 24slavaK commented on src/test/java/school/faang/user_service/service/premium/PremiumServiceTest.java
> +        secondPremium.setEndDate(LocalDateTime.of(2024, 11, 20, 15, 30));
только с билдером не работает маппер 
![mapper1](https://github.com/user-attachments/assets/cb2be6be-88b2-4c9f-b22b-43fbf4a7efac)
![image](https://github.com/user-attachments/assets/c5a09aa6-3943-45f9-8dc6-c651ba23dd30)
он просто перестает таргетить примитивные типы

2024-11-23 18:04 UTC, 24slavaK commented on src/test/java/school/faang/user_service/service/premium/PremiumServiceTest.java
> +        secondPremium.setEndDate(LocalDateTime.of(2024, 11, 20, 15, 30));
это класс PremiumMapperImpl  который генерируется на основе интерфеиса и он перестает таргетить примитивы

2024-11-25 13:26 UTC, MiraGlaceon approved these changes

2024-11-29 22:41 UTC, merged