Парсим файлы пользователей
CorporationX/user_service pull request #1983
Opened 2024-11-19 16:52 UTC by dimaevseenko

Реализация + тесты

2024-11-20 20:10 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/controller/UserController.java
> +    @ResponseStatus(HttpStatus.OK)
код 200 по дефолту вернётся, но для  ясности можно писать

2024-11-20 20:10 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/model/person/Person.java
> +}
я смотрю много вот таких классов очень похожих, расскажи что это)
просто интересно))

2024-11-22 14:43 UTC, MiraGlaceon requested changes

2024-11-22 14:43 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/model/person/Person.java
> +}
Расскажи для чего используешь JsonProperty и JsonUnwrapped и с чем связь, что за индексы?

2024-11-22 15:00 UTC, dimaevseenko commented on src/main/java/school/faang/user_service/model/person/Person.java
> +}
Unwrapped использовал чтобы поля pojo классов были на одном уровне при сериализации в json, так как в файле все поля находятся на одном уровне. JsonProperty использовал чтобы установить порядковый номер для расположения полей в json, так как в файле все поля указаны по порядку, CsvMapper их маппит в обьект по порядку.

2024-11-25 15:38 UTC, MiraGlaceon approved these changes

2024-11-25 15:39 UTC, merged