Feature/bjs2 40606
CorporationX/user_service pull request #1996
Opened 2024-11-21 12:42 UTC by m1rroxxx

2024-11-25 13:24 UTC, MiraGlaceon requested changes

2024-11-25 13:24 UTC, MiraGlaceon commented on build.gradle.kts
> +//tasks.build {
Поправь градл, это не должно попасть в проект

2024-11-25 13:24 UTC, MiraGlaceon commented on build.gradle.kts
> +                minimum = 0.0.toBigDecimal()
Тут

2024-11-25 13:24 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/entity/contact/ContactPreference.java
> +//import org.springframework.data.relational.core.mapping.Table;
Подчисти, если не надо

2024-11-25 13:24 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +    @Retryable(
Раз добавил Retryable, добавь и Recover для оповещения клиента

2024-11-25 13:24 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/elasticsearch/DataSyncService.java
> +    @Scheduled(cron = "${spring.task.scheduling.cron-elastic-search-data-sync}")
Не критично, но Scheduled можно описать как простой component и вынести в отдельный пакет сшедьюлд классами, чтобы под рукой были все

2024-11-25 13:24 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/elasticsearch/DataSyncService.java
> +    @Transactional
Объясни что ты собрался в эту транзакцию заворачивать, помимо вызова метода репозитория saveAll?

2024-11-25 13:36 UTC, m1rroxxx commented on src/main/java/school/faang/user_service/service/elasticsearch/DataSyncService.java
> +    @Transactional
изначально была проблема что я скиллы юзеров получать чуть позже, и я добавил транзакцию что бы держать сессию открытой
потом я добавил параллельность и оказалось что транзакция работает только на 1 поток, и я сделал EntityGraph, все что я об этом знаю, что если по какой то причине половина данных не записались в базу, 
другая половина откатится, т к я тут ничего не записываю подозреваю что она транзакция тут не нужна

2024-11-29 16:58 UTC, MiraGlaceon approved these changes

2024-12-08 08:30 UTC, merged