sprint 5
CorporationX/user_service pull request #2002
Opened 2024-11-22 10:14 UTC by Andrey-O-Kotlyarov

I have done da task from fifth sprint, however without any testes. Killa crew, here we go!

2024-11-22 20:56 UTC, jibulani requested changes
в целом ок, есть несколько замечаний для исправления, также не забудь написать тесты

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    @Autowired
необязательно, автоматом подтянется благодаря наличию конструктора, чтобы он сработал, сделай переменную skillService финальной

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +            return false;
можно сразу кидать ошибку, если невалидно

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    private boolean validateSkill(SkillDto skill) {
обычно приватные методы располагают после всех публичных

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    @GetMapping("/any")
зачем тут эти пустые методы?

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +            throw new ControllerNotValidatesSkillException("the skill has not a title") ;
по заданию должна быть DataValidationException

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    private SkillRepository skillRepository;
тоже сделай переменные финальными и можно будет убрать аннотацию `@Autowired`

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        if (op.isEmpty()) {
чтобы вложенность кода была меньше и он выглядел проще, лучше выполнить обратную проверку:
if (!optionalSkill.isPresent()) {
    return null;
}
// дальше код на случай, если скилл есть

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        Optional<Skill> op = skillRepository.findUserSkill(skillId, userId);
старайся давать переменным более содержательные имена, например, optionalSkill

2024-11-22 20:56 UTC, jibulani commented on src/main/java/school/faang/user_service/service/SkillService.java
> +                for (SkillOffer s : skillOffers) {
тут тоже вместо s лучше использовать skillOffer

2024-11-22 20:56 UTC, jibulani commented on src/main/resources/application.yaml
> +    username: postgres
не надо коммитить свои локальные настройки в общую ветку

2024-11-26 15:39 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    private SkillRepository skillRepository;
Я попробовал так сделать, но тогда перестают работать тесты.

2024-11-28 00:16 UTC, Andrey-O-Kotlyarov commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    @Autowired
попробовал так сделать, но тогда в тестовом классе не попадают моки в ИнджектМокс

2024-11-28 20:23 UTC, jibulani requested changes
хорошо!
есть немного небольших комментариев и надо поправить мерж-конфликты

2024-11-28 20:23 UTC, jibulani commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +    @Autowired
странно, у других ребят в команде такой проблемы не было, можешь с их кодом сравнить, некритично

2024-11-28 20:23 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/skill/SkillCandidateDto.java
> +//@RequiredArgsConstructor
зачем комменты?

2024-11-28 20:23 UTC, jibulani commented on src/main/java/school/faang/user_service/dto/skill/SkillCandidateDto.java
> +    //public SkillCandidateDto(SkillDto skillDto) {
зачем?

2024-11-28 20:23 UTC, jibulani commented on src/test/java/school/faang/user_service/controller/SkillControllerTest.java
> +@ExtendWith(SpringExtension.class)
не нужен, достаточно `@ExtendWith(MockitoExtension.class)`

2024-12-02 20:36 UTC, jibulani approved these changes
ура, в прод!

2024-12-02 20:36 UTC, merged