Добавление аватара пользователя
CorporationX/user_service pull request #2041
Opened 2024-11-27 11:49 UTC by SergeyZhitenev

https://miro.com/app/board/uXjVL_X1hQg=/ скрины работы

2024-11-30 18:36 UTC, Sanasar1 requested changes
В целом норм, просто очень много маленьких моментов. При чем на некоторые я смотрю, и понимаю, что в моем коде они тоже есть, так что это все нормально, и такое во время написания кода не сразу замечаешь, а во время его чтения бросается в глаза)
По читаемости кода все кайф. Единственное, в паре методов было самую малость неудобно читать потому что логические куски не были разделены пустыми строчками (но в большинстве все кайф) + мой комментарий про методы с валидацией
Если где-то не согласен, есть комментарии и т.п., как обычно, пиши)

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/controller/UserProfileV1Controller.java
> +@RequestMapping("/api/v1/userProfile")
По хорошему в эндпоинтах не должно быть заглавных букв. Если у тебя какая-то сущность, к которой ты хочешь обратиться, состоит из нескольких слов, то лучше писать через тире. Типа user-profile

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/controller/UserProfileV1Controller.java
> +public class UserProfileV1Controller {
Мне кажется, что UserProfileController лишний. Лучше в UserController все это сделать. А так мы получается создаем контроллер под атрибуту юзера, которая сама по себе сущностью не является
Так у тебя еще и эндпоинты более понятными станут, вместо /api/v1/userProfile, будет /api/v1/user

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/controller/UserProfileV1Controller.java
> +                                          @RequestParam MultipartFile file) {
Вместо `@RequestParam` можно использовать `@RequestPart`. Это не замечание, просто на будущее. Разница, насколько я понял, лишь в том, что `@RequestPart` больше под работу с файлами заточен

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +        user.addUserProfilePic(fileId, smallFileId);
Я бы тут просто создавал новый объект UserProfilePic и сохранял его юзеру через сеттер. От лишнего метода в User избавимся, и ниже код чуть красивее станет

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +public class UserProfilePicService {
Я бы перенес все в UserService. Опять же, UserProfilePic это именно часть юзера, а не отдельная сущность, которая просто связана с юзером неким образом, и мне кажется лишним дробить кусочки юзера и на каждого писать свою логику

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +    private static final String FOLDER_NAME = "user_profile_avatar";
В идеале такая история должна доставаться из конфигурации. Можешь оставить, если не хочешь выносить. У меня самого пока в локальных переменных вся эта история. Нужно будет как-нибудь самому вынести)

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +        log.info("Changed user profile picture for user {}", user.toStringProfilePicInfo());
Нам Илья рассказывал, что логи на успешное завершение операции излишние. Тут я согласен с ним. Операцию можно считать успешной, если никаких сообщений об ошибке не было. Просто хотел подчеркнуть, можешь оставить, если считаешь иначе

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +        }
Я бы кидал исключение, если у юзера нет фотки. Я так полагаю, под получением фото пользователя, имеется ввиду скинуть его пользователю, чтобы он ее у себя скачал (поправь меня тут, может я не прав). И мы получается тут кидаем непонятно что. Будет ли это пустой файл или что-то совсем другое мне не до конца понятно
Лучше просто поругаться ему, кинуть 400, и сказать, что фотки нет

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +    }
Где-то есть логи об успешной операции, а где-то нету. Лучше привести к одному виду для консистентности

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +    }
Я бы перенес этот метод под validateAvatarSize, чтобы вся валидация, как отдельный логический кусок, в одном месте была

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/util/ImageUtils.java
> +            log.error(ex.getMessage());
Будто бы лишнее логирование. У нас же GlobalExceptionHandler сам должен залогировать ImageProcessingException дальше

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/util/ImageUtils.java
> +        String extension = fileName.substring(fileName.lastIndexOf(".") + 1);
Наверное, стоит добавить лог о промежуточном состоянии. То же самое в остальных методах этого класса

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/service/S3Service.java
> +        ObjectMetadata objectMetadata = new ObjectMetadata();
Я бы добавил логи о промежуточном состоянии на уровне debug. То же самое с остальными методами

2024-11-30 18:36 UTC, Sanasar1 commented on src/main/java/school/faang/user_service/exceptions/GlobalExceptionHandler.java
Надо добавить обработку новых исключений

2024-12-01 08:55 UTC, SergeyZhitenev commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +        user.addUserProfilePic(fileId, smallFileId);
Ну я решил так сделать, показалось, что лучше отдать это логику самому юзеру + избавимся от 4 строк кода, которые по сути просто сеттят поля в объект) В общем не захотелось лишние сеттеры лепить в этом методе)

2024-12-01 09:34 UTC, SergeyZhitenev commented on src/main/java/school/faang/user_service/service/UserProfilePicService.java
> +        }
Меня смущает, что пользователь может не знать, что у кого-то нет аватарки, а мы в него сразу ошибкой кидаемся

2024-12-04 13:29 UTC, ipasynkov-epam approved these changes
есть небольшие комментарии)

2024-12-04 13:29 UTC, ipasynkov-epam commented on src/main/java/school/faang/user_service/controller/UserController.java
> +        return new ResponseEntity<>(file, headers, HttpStatus.OK);
такие вещи типа статуса можно тоже делать с помощью аннотаций:
@ResponseStatus(HttpStatus.OK)
и также посмотри насчет ResponseEntity<> -- нужно ли ее указывать в ответе. Возможно достаточно указать просто InputStreamResource

2024-12-04 13:31 UTC, ipasynkov-epam commented
Кроме того, не получится смержить в ветку содержащую слово master)

2024-12-04 14:17 UTC, SergeyZhitenev commented
> Кроме того, не получится смержить в ветку содержащую слово master)

Почему?

2024-12-04 14:24 UTC, Sanasar1 approved these changes

2024-12-04 14:47 UTC, merged