- Добавлен AvatarService для генерации случайных аватаров
CorporationX/user_service pull request #2080
Opened 2024-12-04 08:07 UTC by Pizdja

- Обновлен User для поддержки URL аватара
- Обновлены настройки в application.yaml
- Добавил тесты

2024-12-17 08:29 UTC, Macacin commented
Подмержи мастер ветку, там некоторые эндпоинты не работают, мы их фиксили видимо пока твоя задачка в кросс ревью висела)

2024-12-17 08:45 UTC, Macacin requested changes

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/controller/UserV1Controller.java
> +    public ResponseEntity<UserSubResponseDto> registerUser(@RequestBody UserRegistrationDto userDto) {
Тут лучше возвращать результат выполнения метода сервиса вместо ResponseEntity, и навесить аннотацию @ResponseStatus(HttpStatus.OK), по сути будет тоже самое, но насколько я знаю так грамотнее, + так будет соблюдаться наша архитектура контроллеров

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/controller/UserV1Controller.java
> +    public ResponseEntity<UserSubResponseDto> registerUser(@RequestBody UserRegistrationDto userDto) {
Перед UserRegistrationDto еще лучше повесить аннотацию @Valid чтобы при запросе автоматически проверялась передаваемая дтошка

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/service/CountryService.java
> +                () -> new EntityNotFoundException("Страна не найдена")
Кириллицу лучше не использовать в ошибках, у нас же сейчас архитектура предполагает, что пользователи могут быть из разных стран. Лучше на английском просто писать.

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/service/CountryService.java
> +                () -> new EntityNotFoundException("Страна не найдена")
Еще я бы предложил добавить тут какое-нибудь логирование, где будет что-то вроде "Country with id {} not found", но это скорее опционально

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/service/Integrations/avatar/AvatarService.java
> +        int size = isSmall ? 170 : 1080;
вот эти числа лучше вынести в константы

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/service/Integrations/avatar/AvatarService.java
> +                throw new RuntimeException("Failed to load avatar image from URL: " + avatarUrl);
конкатенацию строк лучше не использовать, она жрет много памяти и ухудшает производительность. Вместо этого лучше использовать String.format() или использовать другой вид ошибки, в котором предусмотрено форматирование строк

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            throw new DataValidationException("Пользователь с почтой " + userRegistrationDto.email() + " уже зарегистрирован.");
Тоже самое про конкатенацию и форматирование что и в AvatarService

2024-12-17 08:45 UTC, Macacin commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +            log.warn("Ошибка генерации аватара для пользователя {}", user.getId(), e);
вот в логировании в теории уже можно и на русском писать, мы же это для себя пишем, но мне кажется лучше все равно вести все в одном стиле и писать на английском

2024-12-17 08:45 UTC, Macacin commented on src/test/java/school/faang/user_service/service/AvatarServiceTest.java
> +class AvatarServiceTest {
<img width="1440" alt="Снимок экрана 2024-12-17 в 11 43 42" src="https://github.com/user-attachments/assets/df8d1f8c-1d02-4ff5-98e3-d8c0edfcaad9" />
У меня 3 из 4 тестов не взлетают, честно говоря сидеть разбираться сам не очень хочу, глянешь? Может у тебя уже было что-то такое

2024-12-19 10:09 UTC, Macacin approved these changes

2024-12-21 15:18 UTC, ipasynkov-epam approved these changes
есть пара некритичных комментариев. Можно потом почистить

2024-12-21 15:18 UTC, ipasynkov-epam commented on src/main/java/school/faang/user_service/dto/UserRegistrationDto.java
> +        @NotNull Long countryId
в других ДТО и сервисах еще добавляли @positive, если вдруг id у страны не может быть отрицательным. И возможно, что он включает в себя @notNull

2024-12-21 15:18 UTC, ipasynkov-epam commented on src/main/java/school/faang/user_service/service/Integrations/avatar/CustomMultipartFile.java
> +    public void transferTo(java.io.File dest) throws IOException, IllegalStateException {
а почему java.io.File не вынести в импорты и здесь использовать только File ? Вроде этот класс в импортах еще не занят)

2024-12-21 15:19 UTC, merged