BJS2-41844 - Уведомление о получении рекомендации
CorporationX/user_service pull request #2093
Opened 2024-12-05 13:25 UTC by Shakhaev

completed task "Notification of recommendation received"

2024-12-10 19:53 UTC, MiraGlaceon requested changes

2024-12-10 19:53 UTC, MiraGlaceon commented on src/main/resources/application.yaml
>            name: mentorship_channel
тут бы желательно поменять местами name и имена channel, но не критично

2024-12-10 19:53 UTC, MiraGlaceon commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
> +    @Disabled
Вот это объясни почему тесты должны быть отключены

2024-12-10 21:26 UTC, Shakhaev commented on src/test/java/school/faang/user_service/controller/recommendation/RecommendationRequestControllerTest.java
> +    @Disabled
@MiraGlaceon 3 теста установил как @Disabled, поскольку не заводятся. Тесты Миши, я его тегнул в дискорде и осветил проблему, но потом выяснилось, что он сейчас не сможет быстро исправить это. Я долго сидел над ними, сам пытался починить, но сдался и повесил @Disabled.

2024-12-13 19:49 UTC, MiraGlaceon approved these changes

2024-12-14 11:54 UTC, merged