Bjs2 41896
CorporationX/user_service pull request #2175
Opened 2024-12-19 11:41 UTC by RuslanGabd

2024-12-19 11:42 UTC, RuslanGabd commented
![image](https://github.com/user-attachments/assets/26f32e74-30e7-47e6-8a78-37852133c88e)

2024-12-19 11:55 UTC, RuslanGabd commented
![image](https://github.com/user-attachments/assets/95736f86-f857-4ab1-a0ef-34d181dbf0db)

2024-12-19 16:26 UTC, jibulani requested changes
хорошо, есть пара некритичных комментариев и жду тестов

2024-12-19 16:26 UTC, jibulani commented on src/main/java/school/faang/user_service/event/ban/MentorshipOfferedEvent.java
> +package school.faang.user_service.event.ban;
я бы внутрь пакета dto положил, можно там подпакет event или redis сделать

2024-12-19 16:26 UTC, jibulani commented on src/main/java/school/faang/user_service/service/MentorshipRequestService.java
> +        mentorshipOfferedPublisher.publish(new MentorshipOfferedEvent(request.getId(), idRequester, idReceiver));
можно сделать отдельный маппер из MentorshipRequest в MentorshipOfferedEvent
некритично

2024-12-19 16:26 UTC, jibulani commented on src/main/java/school/faang/user_service/event/ban/MentorshipOfferedEvent.java
> +package school.faang.user_service.event.ban;
или хотя бы из пакета ban вытащи

2024-12-20 21:55 UTC, jibulani approved these changes
хорошо, осталось поправить конфликт

2024-12-20 21:55 UTC, jibulani commented on src/test/java/school/faang/user_service/publisher/MentorshipOfferedMessagePublisherTest.java
> +    private static final String TOPIC_NAME = "user-ban-topic";
некритично, но имя топика кажется не то :)

2024-12-21 14:32 UTC, merged