BJS2-40607 - Деактивация пользователя
CorporationX/user_service pull request #2183
Opened 2024-12-21 14:00 UTC by frs717

2024-12-21 14:01 UTC, frs717 commented
В таске еще необходимо приостановить работу над целями. Но у нас пока что задачи с целями не начаты

2024-12-21 14:02 UTC, frs717 commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping("/deactivate/{userId}")
Не уверен, что выбрал лучший url + method..

2025-01-08 15:18 UTC, MiraGlaceon requested changes

2025-01-08 15:18 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping("/deactivate/{userId}")
Поставь {userId} впереди, так лучше будет. Сначала нашел нужного, потом его деактивировал

2025-01-08 15:18 UTC, MiraGlaceon commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public void deactivateUser(long userId) {
Метод хороший, делает все проверки. Лично я бы сократил до одного обращения к БД. Сразу одним sql-апдейтом выставлял нужный статус пользователю. Потом смотрел бы сколько строк обновлено: если ноль, то бросать ошибку, что пользователь не найден. Ошибку "пользователь уже не активен" я бы вообще опустил, это даже не ошибка, информирование. Подправлять не нужно, просто пища для размышления

2025-01-12 06:21 UTC, frs717 commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    public void deactivateUser(long userId) {
Да, с одним обращением в БД лучше) Не подумал даже об этом, буду теперь знать

2025-01-17 05:21 UTC, MiraGlaceon approved these changes

2025-01-19 07:27 UTC, merged