followUser feature without test
CorporationX/user_service pull request #2197
Opened 2024-12-29 20:55 UTC by az3l1t

2025-01-08 13:36 UTC, therealadik requested changes

2025-01-08 13:36 UTC, therealadik commented on src/main/java/school/faang/user_service/controller/SubscriptonController.java
> +    public CompletableFuture<List<UserDto>> getFollowees(long followeeId, UserFilterDto userFilterDto) {
Откуда приходят параметры запроса? Автоматически они не извлекаются

2025-01-08 13:36 UTC, therealadik commented on src/main/java/school/faang/user_service/controller/SubscriptonController.java
> +public class SubscriptonController {
Я бы добавил еще аннотацию, чтобы все endпоинты шли через маршрут /subsription. Архитектектурно лучше будет, чем если они все через корень будут идти

2025-01-08 13:36 UTC, therealadik commented on src/main/java/school/faang/user_service/controller/SubscriptonController.java
> +    public CompletableFuture<List<UserDto>> getFollowers(long followeeId, UserFilterDto userFilterDto) {
Зачем возвращать CompletableFuture?

2025-01-08 13:36 UTC, therealadik commented on src/main/java/school/faang/user_service/dto/UserFilterDto.java
> +public final class UserFilterDto {
почему не record?

2025-01-08 13:36 UTC, fladx commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        });
Используй лучше parallelStream. Эффективнее и чище код будет + не надо возвращать CompletableFuture

2025-01-08 13:36 UTC, fladx commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +            logger.error("The followerId is not following followeeId : {} -> {}", followerId, followeeId);
не логичнее логирование ошибок вписывать внутрь класса исключения?

2025-01-08 17:01 UTC, fladx commented on src/main/java/school/faang/user_service/controller/SubscriptonController.java
> +    }
тело запроса (RequestBody) не передаётся в GET-запросах
 PathVariable отсутствует в пути аннотации @GetMapping("/followers")
 тебе нужно в пути указывать переменные так, чтобы они совпадали с PathVariable. Например так:
 @GetMapping("/followers/{followeeId}")

2025-01-08 17:01 UTC, therealadik commented on src/main/java/school/faang/user_service/controller/SubscriptonController.java
> +    }
где проверка Dto на валидность?

2025-01-08 17:16 UTC, therealadik approved these changes
отлично 🥇

2025-01-09 12:18 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/UserServiceApplication.java
> +@EnableAsync
Подскажи пожалуйста, зачем здесь добавлена это аннотация?

2025-01-09 12:30 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/controller/SubscriptonController.java
> +    @GetMapping("/followees/{followeeId}")
Не уверен, что такое слово вообще существует - Followees".
Может без какого-либо url оставим? Например хочешь посмотреть свои подписки, делаешь запрос к url = /subscription/{followeeId}? Вроде логично - посмотреть свои подписки.
Что думаешь?

2025-01-09 12:31 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public void checkIfOneUser(long followerId, long followeeId) {
Можно сделать приватным т.к. только в этом классе используется.

2025-01-09 12:35 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public boolean ifFollowingUserNotFollower(long followerId, long followeeId) {
ifFollowingUserNotFollower -> isFollowingUserNotFollower т.к. возвращаем bool, который говорит нам да или нет. Соответственно сам вопрос начинается с is.

2025-01-09 13:19 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        return followersOfUser
А попробуй переписать фильтры как здесь ребята делали:
[https://github.com/CorporationX/user_service/blob/hydra-master-stream6/src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestServiceImpl.java#L91-L95](https://faang-school.com/courses/mxjz76d2/67zyrekd#L91-L95)

https://github.com/CorporationX/user_service/blob/hydra-master-stream6/src/main/java/school/faang/user_service/service/mentorship/filter/RequestFilter.java

Таким образом:
1) Мы уменьшим код в самом сервисе
2) сможем легко удалять и добавлять фильтры не меняя кода в сервисе. А это отвечает букве O в SOLID. Код бужет расширяем без его изменения.
3) Выучим новый паттерн

2025-01-10 12:33 UTC, az3l1t commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    @Async
я немного так и не понял насчет аннотации @Async. Как я понял она заменяет нам ручное supplyAsync и указывает спрингу, что метод должен выполняться в отдельном потоке.
Но у меня три метода для работы с этим, при чем они вложенные. На какие надо вешать, а на какие нет?

и + вопрос ментору -> можно ли использовать WebFlux, чтобы легче работать с потоками в спринг на этом этапе?

2025-01-10 12:33 UTC, az3l1t commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +            logger.error("The followerId is not following followeeId : {} -> {}", followerId, followeeId);
SOLID

2025-01-10 12:33 UTC, az3l1t commented on src/main/java/school/faang/user_service/mapper/UserFollowingMapper.java
> +@Mapper(componentModel = "spring")
почему?

2025-01-10 12:33 UTC, az3l1t commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        Mockito.when(subscriptionService.existsByFollowerIdAndFolloweeId(followerId, followeeId)).thenReturn(true);
вот тут ступор. он не дает вернуть булеву переменную из метода

2025-01-11 06:32 UTC, az3l1t commented
готово к ревью. тесты исправил

2025-01-11 13:10 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/UserServiceApplication.java
> +import org.springframework.scheduling.annotation.EnableAsync;
Забыл удалить import

2025-01-11 13:21 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    User findUserById(long id) {
Почему не приватный?

2025-01-11 13:24 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    User findUserById(long id) {
Понял, в тесте описал

2025-01-11 13:25 UTC, az3l1t commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    User findUserById(long id) {
я использую его в тестах, чтобы мокать вызов поиска по бд.

2025-01-11 13:27 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        Exception exception = assertThrows(UserWasNotFoundException.class, () -> subscriptionService.findUserById(1L));
Делать метод публичным по причине того, что хочешь проверить в тесте - плохо.
Советую проверять работоспособность метода findUserById в контексте методов где он используется. 
Например в методе followUser можно сыметировать ситуацию, когда юзер не найден и выпадет ошибка.

2025-01-11 13:32 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +    @BeforeEach
Лучше задействовать эту аннотацию 
`@ExtendWith(MockitoExtension.class)`
вместо `MockitoAnnotations.openMocks(this);`

Аннотация короче.

2025-01-11 13:56 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(subscriptionRepository.findFollowersAmountByFolloweeId(followeeId)).thenReturn(5);
Лучше использовать единую переменную для 5 и для 5 с строчки 55

2025-01-11 14:00 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public ResponseEntity<Void> followUser(FollowingFeatureDto followingFeatureDTO) {
Методы сервиса не должны возвращать ResponseEntity и какие либо статусы. ResponseEntity это объекты самого контроллера. 
Методы сервиса должны возвращать Коллекции, примитивные типы... Например здесь надо вернуть void.
Эти методы банально могут быть использованными другими сервисами. И уже в них излишне оперировать ResponseEntity и статусами

2025-01-11 14:04 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +class SubscriptionServiceTest {
Не нашел тесты для getFollowers, которой по фильтру отдает данные. Добавь парочку тестов на него

2025-01-11 14:14 UTC, SnurnicynKonstantin requested changes
Все супер. Осталось доделать мелкие замечания.

2025-01-13 13:38 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(subscriptionRepository.findByFollowerId(followerId)).thenReturn(Stream.of(user));
Здесь не надо мокать маппер. Маппер должен без проблем обработать объекты. Вот только эти объекты должны вернуться из `subscriptionRepository.findByFollowerId(followerId)`. 
Тем самым мы и работу маппера прверим замокав лишь репозиторий, который с базой работает.

Т.е.:
1. Замокать `subscriptionRepository.findByFollowerId(followerId)`, он должен вернуть список пользователей. Список подготовить надо.
2. Мокать маппер не надо (удалить 53ю строчку). Он сам прекрасно обработает результат метода findByFollowerId и вернет лист.

2025-01-13 14:41 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(userFollowingMapper.toDto(user)).thenReturn(new UserDto(1L, "username", "email@example.com"));
Маппер не надо мокать. Он должен отрабатывать свой функционал. мокаются только те вещи, которые не реально при юнит тестировании поднимать. Например работа с БД или rest запросы куда-то.

Здесь надо удалить 53ю стройчку, да и 39 то же. Я понимаю почему ты так сделал. Потому что объект надо составлять, а короткий объект еще и nullPointer отдает...

1. Мок метода `findByFollowerId(followerId)` должен возвращать `Stream.of(user)` это корректно. Только юзер должен быть настоящим объектом.
2. Создать метод, который генерирует юзера. Этот метод для второго теста то же подойти должен.

Что-то подобное:
<img width="898" alt="image" src="https://github.com/user-attachments/assets/afe0d4c1-7cdc-4dcb-b3ba-e1d0d0d6361f" />

2025-01-13 14:41 UTC, SnurnicynKonstantin requested changes
Единственное замечание осталось

2025-01-13 15:00 UTC, az3l1t commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(userFollowingMapper.toDto(user)).thenReturn(new UserDto(1L, "username", "email@example.com"));
сойдет использование @Spy?

2025-01-14 05:50 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(userFollowingMapper.toDto(user)).thenReturn(new UserDto(1L, "username", "email@example.com"));
Нет, маппер не нужно мокать. От должен по честному через себя пропускать объекты и трансформировать.

2025-01-14 05:55 UTC, SnurnicynKonstantin commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        when(userFollowingMapper.toDto(user)).thenReturn(new UserDto(user.getId(), user.getUsername(), user.getEmail()));
Маппер не нужно мокать. От должен по честному через себя пропускать объекты и трансформировать.

В юнит-тестах моки используются для замены реальных зависимостей тестируемого класса или метода на их "поддельные" реализации. Это позволяет изолировать тестируемый код и исключить влияние внешних факторов, таких как базы данных, сторонние API, файловая система или сложные вычисления.

Мокирование мапперов приводит к замене их поведения заглушками `(when(...).thenReturn(...))`, что скрывает ошибки в самой логике маппинга. Например, если в маппере произошла ошибка (добавилось поле или удалилось), тесты не обнаружат её, так как мок полностью игнорирует оригинальную реализацию.

2025-01-14 05:56 UTC, SnurnicynKonstantin requested changes
Осталось мок маппера убрать. Основной коммент был про это.

2025-01-14 07:44 UTC, SnurnicynKonstantin commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        List<User> filteredUsers = followers
А почему здесь сразу так не сделать?
```
return followers
            .skip((long) userFilterDto.page() * userFilterDto.pageSize())
            .limit(userFilterDto.pageSize())
            .map(userFollowingMapper::toDto)
            .filter(Objects::nonNull)
            .toList();
```

2025-01-14 08:05 UTC, az3l1t commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +        List<User> filteredUsers = followers
согласен. изменял код, чтобы понять где ошибка. забыл вернуть.
уно моменто

2025-01-14 08:14 UTC, SnurnicynKonstantin approved these changes
Теперь все красиво, молодец)

2025-01-14 08:14 UTC, merged