Werewolf master bc 4509 csv file
CorporationX/user_service pull request #502
Opened 2023-08-18 00:05 UTC by M437A

2023-09-02 17:46 UTC, InnMish requested changes

2023-09-04 04:21 UTC, M437A commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    public List<UserDto> createCSV(@RequestParam MultipartFile file) {
Да, все добавил аннотацию в валидаторе, все заработало, через постман проверил

2023-09-04 04:23 UTC, M437A commented on src/main/java/school/faang/user_service/validator/user/UserValidator.java
> +}
Я гуглил и мне не красивые способы выдавало, я решил этот оставить, если так не принято писать, я могу исправить

2023-09-08 09:28 UTC, InnMish approved these changes

2023-09-08 09:30 UTC, merged