Werewolf master bc 4870 new user
CorporationX/user_service pull request #517
Opened 2023-08-20 00:25 UTC by M437A

2023-09-04 10:51 UTC, czar777 commented on src/main/java/school/faang/user_service/service/amazon/AvatarService.java
> +            throw new RuntimeException("Wrong file saved in amazon s3: " + e.getMessage());
я бы тут выкинул кастомное исключение

2023-09-06 10:14 UTC, InnMish requested changes

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/config/threads/AsyncConfig.java
> +    @Bean(name = "avatar")
Точно бин так хочешь назвать? Это же у нас ThreadPoolTaskExecutor, он вообще сам по себе к аватару не имеет отношения) 
Всегда лучше бин называть соответственно тому, что он делает - вот этот создает экзекьютор)

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    private CountryDto country;
Может быть будем страну сюда просто строкой передавать? Думаю, что id здесь не особо нужен, раз дальше логика именно на названии завязана 
К тому же это сократит количество операций. Ведь пользователь не знает id страны, он все равно будет заполнять только title, а id, получается, наша забота

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    }
Конструктор точно нужен? Билдером можно воспользоваться почти везде и собрать то, что нужно)

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/exception/DiceBearConnect.java
> +public class DiceBearConnect extends RuntimeException{
DiceBearConnectException  

Если класс представляет исключение, его название должно об этом говорить 
Иначе можно подумать, что мы в этом классе строим коннекшен)

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +import org.mapstruct.Mapping;
Это не нужно здесь, удаляем

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        user.setCreatedAt(LocalDateTime.now());
Это поле должно проставляться на уровне базы, и скорее всего проставляется автоматически, проверь в миграции.
Чем меньше контроля за временем от нас, тем лучше

2023-09-06 10:14 UTC, InnMish commented on src/main/resources/application.yaml
> +    bucket-name-for-avatars: avatar
ключи в ямл-файле лучше указывать через нижнее подчеркивание, а значения через дефис, если нужно 
тут давай поправим на  bucket_name_for_avatars

2023-09-06 10:14 UTC, InnMish commented on src/main/resources/application.yaml
> +  dice-bear:
Тут тоже можно поправить

2023-09-06 10:14 UTC, InnMish commented on src/main/resources/db/changelog/changeset/user_V002__update_user_add_profile_pic.sql
> +ADD COLUMN if not exists profile_pic_name text;
Если что-то добавляешь, лучше это делать в новом файле миграции

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/CountryDto.java
> +}
Думается мне, можно сделать без этого класса вообще 
Преобразование из строки в класс страны можно прям в userMapper'e сделать

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/repository/CountryRepository.java
> +    Optional<Long> findIdByTitle(@Param("title") String title);
Давай будем не id искать здесь, а в целом просто достанем entity  
Если есть, то будем работать с ней, а если нет, то создадим новую

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/service/amazon/AvatarService.java
> +                throw new IOException("Failed to read full content from URL");
Вот тут вылетает ошибка, которую мы потом ловим в другом методе
Может быть можем прямо здесь выкинуть DiceBearConnectException?  Непонятно, зачем это промежуточное действие

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/service/amazon/AvatarService.java
> +            new DiceBearConnect("Can't upload file: " + e.getMessage());
пропустил throw

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/config/S3Config.java
> +        return clientAmazonS3;
Можно сразу return написать на 30 и не создавать поле

2023-09-06 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +    }
Весь этот этап можно сделать, когда у тебя уже будет преобразованная сущность User из UserDto  
Просто там пока что не будет заполнена страна 
Ты тогда пойдешь, достанешь или создашь страну и положишь ее в сущность User, так как она тебе из базы сама уже сущность Country вернется 

Тогда нам не понадобится вообще CountryDto

2023-09-08 18:39 UTC, M437A commented on src/main/java/school/faang/user_service/config/threads/AsyncConfig.java
> +    @Bean(name = "avatar")
Я когда придумывал, ориентировался на то, что создаю пул потоков, который отвечает только за создание аватаров, ну то есть что он делает понятно, нужно либо существительное, либо прилагательное, которое описывает его зону ответственности
(ну это мои мысли, как создателя, то что непонятно для чтения я не подумал)

2023-09-08 18:49 UTC, M437A commented on src/main/java/school/faang/user_service/dto/UserDto.java
> +    }
Это для избежания ошибок в старом коде, не исправлял, чтобы PR не засорять

2023-09-14 06:21 UTC, InnMish approved these changes

2023-09-14 07:09 UTC, InnMish requested changes

2023-09-14 07:09 UTC, InnMish commented on src/main/resources/db/changelog/changeset/user_V009_alter_user_pic_name.sql
> +ADD COLUMN if not exists profile_pic_name text;
Файл миграции надо добавить в changelog, иначе эта колонка не появится в бд

2023-09-14 07:09 UTC, InnMish commented on src/main/resources/db/changelog/changeset/user_V009_alter_user_pic_name.sql
> +ADD COLUMN if not exists profile_pic_name text;
Сейчас тесты падают из-за этого - при гет-запросе не получается найти эту колонку

2024-12-21 21:06 UTC, closed without merging