5878-1 user_service - created All necessary classes
CorporationX/user_service pull request #575
Opened 2023-09-03 20:19 UTC by schonpink

2023-09-04 08:22 UTC, tarrasoff approved these changes

2023-09-04 08:22 UTC, tarrasoff commented on src/test/java/school/faang/user_service/service/SkillOfferServiceTest.java
> +        EventSkillOfferedDto eventDto = new EventSkillOfferedDto();
повторяющиеся переменные можно вынести в сетап

2023-09-04 08:22 UTC, tarrasoff commented on src/test/java/school/faang/user_service/service/SkillOfferServiceTest.java
> +        long userId = 1L;
тоже самое

2023-09-04 08:22 UTC, tarrasoff commented on src/test/java/school/faang/user_service/validator/SkillOfferedEventValidatorTest.java
> +        EventSkillOfferedDto skillDoesNotExistDto = new EventSkillOfferedDto();
переменная повторяется 6 раз, лучше вынести в сетап

2023-09-04 08:25 UTC, schonpink commented on src/test/java/school/faang/user_service/service/SkillOfferServiceTest.java
> +        EventSkillOfferedDto eventDto = new EventSkillOfferedDto();
согласна, но в данном контексте было удобно так работать

2023-09-05 09:27 UTC, InnMish requested changes

2023-09-05 09:27 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/EventSkillOfferedController.java
> +        return skillOfferService.findAllOffersOfSkill(skillId, userId);
Давай вот эти методы перенесем в SkillController, он теперь есть в мастере) 
Для событий предлагаю использовать уже готовые сервисы и контроллеры, чтобы когда пользователь, например, создает новый скилл, событие об этом сразу же летело в редис 
Чтобы ему не надо было для этого какой-то отдельный метод дергать)

2023-09-05 09:27 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/event/EventSkillOfferedDto.java
> +package school.faang.user_service.dto.event;
пакет event у нас для сущности Событие 
Которая прям в пакете entity - Event 

А этот класс относится скорее к скиллам, чем к эвентам) 
Тоже надо посмотреть, может, в пакете skill есть подходящее что-нибудь. А если нет, то просто этот класс перенести в тот пакет)

2023-09-05 09:27 UTC, InnMish commented on src/main/java/school/faang/user_service/entity/recommendation/SkillOffer.java
> +    private User receiver;
У поля recommendation уже есть ссылки на автора и получателя, можно ими прям пользоваться) А так получается дублирование: обе таблицы ссылаются на эти поля

2023-09-05 09:27 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/EventSkillOfferedPublisher.java
> +        if (channel == null || channel.isEmpty() || !"skill-offered-channel".equals(channel)) {
А в какой ситуации это условие выполнится?

2023-09-05 09:27 UTC, InnMish commented on src/main/java/school/faang/user_service/service/SkillOfferService.java
> +    }
Это тоже надо попробовать перетащить в SkillService

2023-09-06 11:31 UTC, schonpink commented on src/main/java/school/faang/user_service/publisher/EventSkillOfferedPublisher.java
> +        if (channel == null || channel.isEmpty() || !"skill-offered-channel".equals(channel)) {
наверное я слишком увлеклась проверками

2023-09-06 11:48 UTC, schonpink commented on src/main/java/school/faang/user_service/dto/event/EventSkillOfferedDto.java
> +package school.faang.user_service.dto.event;
да была дилема, куда определить этот класс

2023-09-06 11:50 UTC, schonpink commented on src/main/java/school/faang/user_service/entity/recommendation/SkillOffer.java
> +    private User receiver;
тут получается вообще сущность SkillOffer не подходит для маппинга ,а вот Recommendation - да, и все необходимые поля есть, ок, спасибо, не заметила сразу

2023-09-13 14:10 UTC, merged