add publisher
CorporationX/user_service pull request #576
Opened 2023-09-04 11:53 UTC by TowBoat39

2023-09-06 11:39 UTC, czar777 approved these changes

2023-09-12 13:06 UTC, InnMish requested changes

2023-09-12 13:06 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/RecommendationEvent.java
> +        publishInTopic(topicRecommendation, event);
Мы с Энжи порефакторили код в мастере чуть-чуть, посмотри) 
Сделали так, что теперь в publishInTopic можно не передавать топик, а прям в конструктор абстрактного класса класса его прокидывать. Давай тоже так сделаем)

2023-09-12 13:06 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/RecommendationEvent.java
> +    public RecommendationEvent(RedisTemplate<String, Object> redisTemplate, ObjectMapper objectMapper, ChannelTopic topicRecommendation, RecommendationMapper recommendationMapper) {
Тут просто для красоты давай перенесем длинную строчку на новую

2023-09-12 13:06 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/RecommendationEvent.java
> +    public RecommendationEvent(RedisTemplate<String, Object> redisTemplate, ObjectMapper objectMapper, ChannelTopic topicRecommendation, RecommendationMapper recommendationMapper) {
Соответственно, тут в конструктор можно будет вообще топик не сетить, и в целом конструктор будет только супер

2023-09-13 15:34 UTC, merged