BC-5900. Fundraised event publisher
CorporationX/user_service pull request #577
Opened 2023-09-04 14:32 UTC by Dlakares

Отправка донатов еще не готова, так что внедрять пока некуда

2023-09-04 17:28 UTC, kkkooolllyyyaaa requested changes
Один вопрос)

2023-09-04 17:28 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/dto/fundraising/FundRaisedEvent.java
> +    private int amount;
Точно int?)

2023-09-04 17:28 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/dto/fundraising/FundRaisedEvent.java
> +    private int amount;
double тоже не надёжный, потому что там плавающая точка. Обычно через string с валидацией (pattern)

2023-09-08 07:16 UTC, Rvze commented on src/main/java/school/faang/user_service/dto/fundraising/FundRaisedEvent.java
> +    @Pattern(regexp = "[0-9]+")
эта регулярка подойдет только для целых чисел. Если мы говорим о деньгах, то там не всегда целое число.

2023-09-08 07:16 UTC, Rvze commented on src/main/java/school/faang/user_service/dto/fundraising/FundRaisedEvent.java
> +    @Pattern(regexp = "[0-9]+")
можешь не заморачиваться и использовать `BigDecimal`

2023-09-10 11:11 UTC, merged