Analysis of user subscriptions 1
CorporationX/user_service pull request #582
Opened 2023-09-05 17:15 UTC by Monono7

2023-09-06 08:03 UTC, czar777 approved these changes

2023-09-06 08:03 UTC, czar777 commented on src/main/java/school/faang/user_service/exception/DeserializeJSONException.java
> +}
Он тут не нужен, ты его нигде не используешь

2023-09-08 07:42 UTC, InnMish requested changes

2023-09-08 07:42 UTC, InnMish commented on src/main/java/school/faang/user_service/config/RedisConfig.java
> +    }
Сейчас будем наводить порядок в общем коде) 

Смотри: бины ChannelTopic не используются здесь, верно? Мы их используем только в паблишере. Что, если нам здесь такие бины не создавать, а прямо в паблишере работать с конкретной строкой - названием канала? В твоем случае - это followerChannelName. 
Коммент сейчас еще в паблишере оставлю, как я это вижу

2023-09-08 07:42 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/FollowerEventPublisher.java
> +public class FollowerEventPublisher extends AbstractEventPublisher<FollowerEventDto>{
Здесь мы наследуемся от абстрактного класса AbstractEventPublisher, который в свою очередь в метод publishInTopic ждет топик (topicFollower). Все, что делает этот метод абстрактного класса с бином топика - достает стрингу-название из него.
Получается, мы можем вообще не создавать бин, раз на нужна только строка, верно? 
Таким образом, что, если нам в абстрактный класс прям передавать эту строку?

2023-09-08 07:42 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/FollowerEventPublisher.java
> +                                  ChannelTopic topicFollower) {
То есть вот тут, вместо ChannelTopic topicFollower мы будем передавать именно строку из конфигов с названием канала. 
А в абстрактном классе сделать поле private final String channel, которое будет этой строкой переданной инициализироваться. Ну и аннотацию RequiredArgsConstructor на абстрактный повесить, чтобы инициализировалось там все само)

2023-09-08 07:42 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/FollowerEventPublisher.java
> +        this.topicFollower = topicFollower;
тогда вот тут внутри останется только супер

2023-09-08 07:42 UTC, InnMish commented on src/main/java/school/faang/user_service/publisher/FollowerEventPublisher.java
> +        publishInTopic(topicFollower, followerEventDto);
и тут тогда мы уже не будем в метод передавать topicFollower - это произойдет еще на этапе конструктора. Тогда в метод надо будет положить только dto. Соответсвтенно, в абстрактном классе это тоже надо будет поправить.

2023-09-08 07:42 UTC, InnMish commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +    FollowerEventPublisher followerEventPublisher;
И тут еще надо дописать проверку, что дто сформировалась и улетела 
Посмотри по тестам, Сережа, кажется, делал такое

2023-09-12 13:01 UTC, InnMish approved these changes

2023-09-12 13:02 UTC, merged