Created parsing csv users file endpoint with integration test
CorporationX/user_service pull request #606
Opened 2023-09-17 12:48 UTC by zhugalcf

2023-10-02 23:00 UTC, kkkooolllyyyaaa requested changes
👍 оставил пару минорных комментов

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on build.gradle.kts
А что тут отступы везде поменялись? Вроде раньше норм было. Лучше просто так такие изменения не заливать

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/exception_handler/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.SC_BAD_REQUEST).body(body);
А что за код SC_BAD_REQUEST?

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/mapper/PersonMapper.java
> +        if (Objects.nonNull(person.getContactInfo())
Почему просто не !=null?

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/mapper/PersonMapper.java
> +        if (Objects.nonNull(person.getContactInfo())
Снизу тоже. Так будто бы короче. Ну и всё это условие можно вынести в булевую переменную, так лучше будет читаться

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/mapper/PersonMapper.java
> +        return aboutMe.toString().trim();
Мне кажется лучше json'ом отдавать. Потом на фронте уже можно же рисовать как нужно

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/parser/PersonParser.java
> +        CsvSchema schema = mapper.schemaFor(Person.class).withHeader().withColumnReordering(true);
👍

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/util/PasswordGenerator.java
> +}
😄 👍

2023-10-02 23:00 UTC, kkkooolllyyyaaa commented on src/test/java/school/faang/user_service/controller/UserControllerIntegrationTest.java
> +    }
🔥

2023-10-03 09:59 UTC, zhugalcf commented on src/main/java/school/faang/user_service/mapper/PersonMapper.java
> +        return aboutMe.toString().trim();
У нас же в энтити string about me, я этот метод сделал для преобразования к стринге, чтобы в поле about me  записывать, или я не понял тебя может

2023-10-08 15:40 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/mapper/PersonMapper.java
> +        return aboutMe.toString().trim();
Аа, сори, я не так понял)

2023-10-08 15:41 UTC, merged