Добавил покупку премиум доступа.
CorporationX/user_service pull request #607
Opened 2023-09-18 14:27 UTC by Fxsh-pro

2023-09-18 16:12 UTC, kkkooolllyyyaaa requested changes
Замечания + Тесты бы ещё)

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +    public PremiumDto buyPremium(@RequestHeader(value = "x-user-id") long userId, @PathVariable int days) {
Лучше принимать в Body конечно. Это можно легко валидировать + мб сможем обновлять api разными возможными конфигурацими покупки премиум доступа)

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +    public PremiumDto buyPremium(@RequestHeader(value = "x-user-id") long userId, @PathVariable int days) {
Ну и в пути обычно указывают РЕСУРС, к которому обращаются. Дни в премиуме это не совсем отдельный ресурс

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +    public PremiumDto buyPremium(@RequestHeader(value = "x-user-id") long userId, @PathVariable int days) {
\+ можно лог добавить)

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriod.java
> +    private final double price;
Жалко, что это хардкод, но можно пока так оставить) Это лучше наверное вообще в БД хранить или хотя бы в конфиге)

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriod.java
> +    }
Чёт сложно, будто можно принимать сразу енам в эндпоинте тогда)

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriod.java
> +    private final double price;
Ну и тут не обязательно прайс зависит от кол-ва дней по идее) Могут быть всякие персональные скидки например)

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        Premium premium = new Premium(-1, user, LocalDateTime.now(), LocalDateTime.now().plusDays(period.getDays()));
now() лучше зафиксировать, ну и можно наверное создать отдельный конструктор, в который нужно передать просто user и period, он сам всё остальное подставит

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        user.setPremium(premium);
это строка точно нужна?

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        long paymentNumber = new Random().nextInt(900000) + 100000;
можно так наверное
`new Random().nextInt(100000, 1000000)`

2023-09-18 16:12 UTC, kkkooolllyyyaaa commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
В соседнем методе стоит вызвать этот метод, потом вернуть дто, что бы не повторять код

2023-09-18 16:53 UTC, Fxsh-pro commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriod.java
> +    }
А по условию нужно кол-ва дней принимать. Хотя это реально странно

2023-09-25 11:40 UTC, Fxsh-pro commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        user.setPremium(premium);
Иначе не сохранится

2023-09-25 11:47 UTC, Fxsh-pro commented on src/main/java/school/faang/user_service/entity/premium/PremiumPeriod.java
> +    private final double price;
Я бы пока так оставил, лучше на новые фичи сейчас сяду🫣

2024-12-21 21:06 UTC, closed without merging