BJS2-1491 Receive all requests for mentorship
CorporationX/user_service pull request #677
Opened 2024-01-14 05:52 UTC by javaDevArtem

2024-01-14 05:53 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/mapper/MentorshipRequestMapper.java
> +//        return userRepository.findById(id).orElse(null);
Вот здесь не понял как из маппера получить доступ к базе.
Поставил ignore = true для toEntity

2024-01-14 06:35 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +package school.faang.user_service.mentorship.controller;
По моему надо сделать пакет controller, в котором уже будет mentorship. И так для Service и т д. Например, как с entity.
Если раскроешь пакет entity, то там будет уже деление на user, mentorship и т д. Вроде так принято.

2024-01-14 06:39 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +                .collect(Collectors.toList());
Просто .toList()

2024-01-14 06:57 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +        mentorshipRequestFilters.stream()
Круто!

2024-01-14 07:01 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/filter/MentorshipDescriptionFilter.java
> +        mentorshipRequests.removeIf(mentorshipRequest -> !mentorshipRequest.getDescription().contains(filterDto.getDescriptionFilter()));
Тут я не уверен, но по ощущениям удаление будет работать дольше, чем, например, Stream.filter. Во всех фильрах
Это уже Инна скажет точно)

2024-01-14 07:27 UTC, vladmeniailov approved these changes
Код очень аккуратный, на мой взгляд всё по условию. К сожалению тоже не знаю как в том Маппере, тебе обратиться к базе.

2024-01-14 07:44 UTC, Edisolt5498 requested changes
Я старался :)

2024-01-14 07:44 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +    private MentorshipRequestMapper mentorshipRequestMapper;
final

2024-01-14 07:44 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +                .collect(Collectors.toList());
Просто .toList()

2024-01-14 07:44 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/filter/MentorshipDescriptionFilter.java
> +        mentorshipRequests.removeIf(mentorshipRequest -> !mentorshipRequest.getDescription().contains(filterDto.getDescriptionFilter()));
Тут я не уверен, но по ощущениям удаление будет работать дольше, чем, например, Stream.filter. Во всех фильрах Это уже Инна скажет точно)

2024-01-14 07:44 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +package school.faang.user_service.mentorship.controller;
По моему надо сделать пакет controller, в котором уже будет mentorship. И так для Service и т д. Например, как с entity. Если раскроешь пакет entity, то там будет уже деление на user, mentorship и т д. Вроде так принято.

2024-01-14 07:44 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/mapper/MentorshipRequestMapper.java
> +//        return userRepository.findById(id).orElse(null);
Мне кажется надо в сервисе достраивать dto с помощью setter'ов, а тут их игнорить

2024-01-14 07:44 UTC, Edisolt5498 commented on src/test/java/school/faang/user_service/mentorship/service/MentorshipRequestServiceTest.java
> +    @InjectMocks
Возможно я ошибаюсь, но разве нужно Dto инжектить? Зачем эта аннотация тут?

2024-01-14 07:44 UTC, Edisolt5498 commented on src/test/java/school/faang/user_service/mentorship/service/MentorshipRequestServiceTest.java
> +    @InjectMocks
Тоже самое, зачем аннотация

2024-01-14 07:44 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +        List<MentorshipRequest> mentorshipRequestList = StreamSupport.stream(mentorshipRequestRepository.findAll().spliterator(), false)
List я думаю в названии лишнее. (Я у Инны набрался этих штук))

2024-01-14 07:44 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +                .forEach(filter -> filter.apply(mentorshipRequestList, filters));
А что, если mentorshipRequestList = null? Вдргу в базе нет ничего по запросу

2024-01-14 07:44 UTC, Edisolt5498 commented on src/test/java/school/faang/user_service/mentorship/service/MentorshipRequestServiceTest.java
> +    @Test
В целом вроде правильный тест, но нет сценария, когда нет ничего в базе по запросу .findAll()

2024-01-14 07:55 UTC, Edisolt5498 requested changes

2024-01-14 07:55 UTC, Edisolt5498 commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +    private MentorshipRequestFilter mentorshipRequestFilter = new MentorshipDescriptionFilter();
Не используется. Вроде удалить можно переменную

2024-01-14 07:55 UTC, Edisolt5498 commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +    List<MentorshipRequest> mentorshipRequests = new ArrayList<>();
private?

2024-01-14 07:55 UTC, Edisolt5498 commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +        mentorshipRequest.setDescription("One TWO THREE FOUR");
Я думаю можно было бы все setter'ы для mentorshipRequest сделать в init методе, может и фильтры тоже.
В общем, сделать код в этом плане менее повторяющимся

2024-01-18 14:12 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +    private MentorshipRequestService mentorshipRequestService;
final

2024-01-18 14:12 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/exception/MentorshipRequestException.java
> +    public MentorshipRequestException(String message) {
Как и в остальных задачах - такое исключение слишком узкое 
Лучше создать такое, которое подойдет для всех сущностей

2024-01-18 14:12 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/filter/RequestFilterDto.java
> +package school.faang.user_service.mentorship.filter;
этот класс в пакетик dto вынеси

2024-01-18 14:12 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +                .forEach(filter -> filter.apply(mentorshipRequestList, filters));
Он будет не налл, а пустой, скорее всего

2024-01-26 04:08 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +                .forEach(filter -> filter.apply(mentorshipRequestList, filters));
Это то что я нашел в документации:
Repository methods returning collections, collection alternatives, wrappers, and streams are **guaranteed never to return null**

2024-01-26 04:31 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/filter/RequestFilterDto.java
> +package school.faang.user_service.mentorship.filter;
Готово

2024-01-26 04:31 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/exception/MentorshipRequestException.java
> +    public MentorshipRequestException(String message) {
Расширил и дополнил исключения

2024-01-26 04:31 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +    private MentorshipRequestService mentorshipRequestService;
Готово

2024-01-26 04:32 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +        mentorshipRequest.setDescription("One TWO THREE FOUR");
Вынес общие для методов сеттеры в init

2024-01-26 04:33 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +        mentorshipRequest.setDescription("One TWO THREE FOUR");
Частные сеттеры для проверок оставил в методах, тк по ним идут тесты, разные от кейса к кейсу.

2024-01-26 04:34 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +    List<MentorshipRequest> mentorshipRequests = new ArrayList<>();
Готово

2024-01-26 04:34 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +    private MentorshipRequestFilter mentorshipRequestFilter = new MentorshipDescriptionFilter();
Подправил, да она используется, показывалась потому что не корректно инициализировал.

2024-01-26 04:34 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/service/MentorshipRequestServiceTest.java
> +    @Test
Добавил необходимые проверки

2024-01-26 04:35 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +        List<MentorshipRequest> mentorshipRequestList = StreamSupport.stream(mentorshipRequestRepository.findAll().spliterator(), false)
Готово, переименовал

2024-01-26 04:38 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/service/MentorshipRequestServiceTest.java
> +    @InjectMocks
Подправил.
Аннотацией удобнее, когда не важны данные внутри.

2024-01-26 04:38 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/service/MentorshipRequestServiceTest.java
> +    @InjectMocks
Убрал.

2024-01-26 04:39 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +package school.faang.user_service.mentorship.controller;
Отрефакторил местоположение всех пакетов

2024-01-26 04:40 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/filter/MentorshipDescriptionFilter.java
> +        mentorshipRequests.removeIf(mentorshipRequest -> !mentorshipRequest.getDescription().contains(filterDto.getDescriptionFilter()));
У меня через Stream.filter не сработало, этот вариант подошёл.

2024-01-26 04:40 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +                .collect(Collectors.toList());
Готово.

2024-01-26 04:40 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +    private MentorshipRequestMapper mentorshipRequestMapper;
Готово

2024-01-26 04:41 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/mapper/MentorshipRequestMapper.java
> +//        return userRepository.findById(id).orElse(null);
Удалил этот код.

2024-01-26 08:57 UTC, InnMish commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +    }
Кажется, нет теста такого, где в фильтре сразу несколько параметров 
Например, статус и реквестер 
И также нужен тест, когда все возможные фильтры переданы

2024-01-27 02:48 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/filter/MentorshipRequestFilterTest.java
> +    }
Добавил несколько проверок с мультипл парамектрами для фильтра.
Обновил тесты

2024-01-29 08:42 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    private void getRequests(RequestFilterDto filter) {
а почему void? Мы же должны вернуть результаты поиска здесь

2024-01-30 03:21 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    private void getRequests(RequestFilterDto filter) {
Готово, возвращаем List<MentorshipRequestDto>

2024-01-31 10:09 UTC, InnMish approved these changes

2024-02-04 15:58 UTC, merged