BJS2-1488 Send a request for mentorship
CorporationX/user_service pull request #678
Opened 2024-01-14 05:55 UTC by javaDevArtem

2024-01-14 06:00 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/mapper/MentorshipRequestMapper.java
> +//        return userRepository.findById(id).orElse(null);
Вот здесь не понял как из маппера получить доступ к базе.
Поставил ignore = true для toEntity

2024-01-14 07:26 UTC, vladmeniailov approved these changes
Код очень аккуратный, на мой взгляд всё по условию. К сожалению тоже не знаю как в том Маппере, тебе обратиться к базе.

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +package school.faang.user_service.mentorship.controller;
по структуре папочек наоборот 
На внешнем уровне у нас контроллеры, сервисы и тд, а на внутреннем уже конкретные сущности, как mentorship у тебя

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +    private MentorshipRequestService mentorshipRequestService;
Если ты инжектишь бин, он должен быть final  
Один раз спринг его создал и все время использует только его, мы должны это гарантировать

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +        mentorshipRequestService.requestMentorship(mentorshipRequestDto);
перед вызовом метода сервиса нужно провести первичную валидацию запроса 
Ведь бессмысленно передавать данные дальше, если они неправильно заполнены 

Тут проверяем, что заполнено поле description, requester и receiver

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/mapper/MentorshipRequestMapper.java
> +//        return userRepository.findById(id).orElse(null);
Я не очень поняла, зачем тебе именно тут это делать) 
Ты здесь с игнором оставь, а потом в сервисе уже получи пользователя и положи в MentorshipRequest, который отсюда вернешь

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +
final

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +        mentorshipRequestValidator.mainMentorshipRequestValidation(mentorshipRequestDto);
название метода такое, как будто бы есть основной валидатор, а есть неосновной) 
я бы убрала main из названия)

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +        MentorshipRequest mentorshipRequest = mentorshipRequestMapper.toEntity(mentorshipRequestDto);
вот тут ты еще достанешь из dto айдишники юзеров, через userService получишь пользователей и запихнешь их в mentorshipRequest

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/validator/MentorshipRequestValidator.java
> +        Optional<User> requester = userRepository.findById(mentorshipRequestDto.getRequester());
У нас в приложении вот это действие по получению пользователя одно из самых частых вообще 
И все будут всегда писать один и тот же код 

Нужно этот метод написать в UserSerive 
На вход уже передавать уже конкретный айдишник 

Далее
Мы не должны получать Optional 
В UserSerive методе сделай так, что если пользователь не найден, нужно сразу там кинуть ошибку, что такого пользователя в нашей системе нет 

В этот метод валидатора лучше всего передать пользователей извне, так как в сервисе ты их тоже будешь использовать 
И чтобы два раза не доставать, получи их в сервисе, а сюда просто передай параметрами метода

2024-01-17 10:14 UTC, InnMish commented on src/main/java/school/faang/user_service/mentorship/validator/MentorshipRequestValidator.java
> +        }
Я бы предложила эту валидацию большую разделить на подметоды 
Чтобы каждый из них в отдельности можно было переиспользовать

2024-01-17 10:14 UTC, InnMish commented on src/test/java/school/faang/user_service/mentorship/validator/MentorshipRequestValidatorTest.java
> +    }
И тестики дописать тогда в соответствии с исправлениями

+ нужен тест на маппер

2024-01-25 13:34 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/mapper/MentorshipRequestMapper.java
> +//        return userRepository.findById(id).orElse(null);
Удалил отсюда.
Добавил логику в сервис по получения пользователей.

2024-01-25 13:34 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +package school.faang.user_service.mentorship.controller;
Структуру изменил

2024-01-25 13:35 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +    private MentorshipRequestService mentorshipRequestService;
Принял, везде добавил final

2024-01-25 13:39 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/controller/MentorshipRequestController.java
> +        mentorshipRequestService.requestMentorship(mentorshipRequestDto);
Добавил первичную проверку на наличие обязательных полей

2024-01-25 13:39 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +
Добавил

2024-01-25 13:39 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +        mentorshipRequestValidator.mainMentorshipRequestValidation(mentorshipRequestDto);
Да, переименовал метод

2024-01-25 13:40 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/service/MentorshipRequestService.java
> +        MentorshipRequest mentorshipRequest = mentorshipRequestMapper.toEntity(mentorshipRequestDto);
Добавил логику по получения юзеров и добавления их в mentorshipRequest

2024-01-25 13:41 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/validator/MentorshipRequestValidator.java
> +        Optional<User> requester = userRepository.findById(mentorshipRequestDto.getRequester());
Готово.
Создал UserService с методом findUserById.
Обработка Optional там же.
Поменял входные параметра валидатора чтобы два раза не искать юзеров.

2024-01-25 13:41 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/mentorship/validator/MentorshipRequestValidator.java
> +        }
Да, принял.
Разделил и сделал два отдельных метода на проверку данных юзера.

2024-01-25 13:42 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mentorship/validator/MentorshipRequestValidatorTest.java
> +    }
Дополнил тесты по последним изменениям и добавил тест маппера

2024-01-26 08:54 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +            throw new DataValidationException("Incorrect data");
Это вынести в класс-валидатор отдельным методом вместе с киданием ошибки

2024-01-26 08:54 UTC, InnMish commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        mentorshipRequestValidator.dateCheckValidation(receiver, requester);
в валидаторе объедини эти два метода в один, может? Тут просто дернешь метод validate, а там внутри уже будет конкретно видно, какие поля валидируются

2024-01-27 02:29 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/service/mentorship/MentorshipRequestService.java
> +        mentorshipRequestValidator.dateCheckValidation(receiver, requester);
Объединил в общий метод validateUserData, поправил тесты.

2024-01-27 02:29 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +            throw new DataValidationException("Incorrect data");
Сделал доп метод в валидаторе commonCheck, обновил.

2024-01-29 08:47 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    private void requestMentorship(MentorshipRequestDto mentorshipRequestDto) {
вернуть MentorshipRequestDto , которую отправили пользователю 
Всегда стоит возвращать сущности, которые пользователь передал в приложение для сохранения/изменения 
Так потом он сможет посмотреть все ли окей

2024-01-30 03:17 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    private void requestMentorship(MentorshipRequestDto mentorshipRequestDto) {
Принял.

2024-01-30 03:17 UTC, javaDevArtem commented on src/main/java/school/faang/user_service/controller/mentorship/MentorshipRequestController.java
> +    private void requestMentorship(MentorshipRequestDto mentorshipRequestDto) {
Добавил возвращение MentorshipRequestDto

2024-01-31 10:05 UTC, InnMish requested changes

2024-01-31 10:05 UTC, InnMish commented on src/test/java/school/faang/user_service/mapper/mentorship/MentorshipRequestMapperTest.java
> +    private MentorshipRequestMapper mentorshipRequestMapper;
У меня этот тест не работает без new MentorshipRequestMapperImpl();

2024-01-31 10:05 UTC, InnMish commented on src/test/java/school/faang/user_service/mapper/mentorship/MentorshipRequestMapperTest.java
> +        mentorshipRequestDto = MentorshipRequestDto.builder()
Фактический результат один, ожидаемый другой 
не проставлены поля RequestStatus и Reason

2024-02-04 16:49 UTC, merged

2024-02-08 01:21 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mapper/mentorship/MentorshipRequestMapperTest.java
> +    private MentorshipRequestMapper mentorshipRequestMapper;
Да, обновил

2024-02-08 01:22 UTC, javaDevArtem commented on src/test/java/school/faang/user_service/mapper/mentorship/MentorshipRequestMapperTest.java
> +        mentorshipRequestDto = MentorshipRequestDto.builder()
Сделал, добавил недостающие поля.