added function buy premium
CorporationX/user_service pull request #679
Opened 2024-01-14 08:39 UTC by kamil516

2024-01-21 07:31 UTC, InnMish commented on src/main/java/school/faang/user_service/client/PaymentServiceClient.java
> +    @PostMapping("/api/payment")
апи перенести в конфиг

2024-01-21 07:31 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +@RequestMapping("/api/premium")
Апи в конфиг

2024-01-21 07:31 UTC, InnMish commented on src/main/java/school/faang/user_service/service/PremiumService.java
> +        PaymentRequest paymentRequest = new PaymentRequest(++paymentNumber, BigDecimal.valueOf(premiumPeriod.getPrice()), Currency.USD);
Вот здесь рекомендую вынести этот кусок в отдельный метод
А потом доработаем именно его 
Чтобы потом по всему коду не лазить и не искать

2024-01-21 07:31 UTC, InnMish commented on src/main/java/school/faang/user_service/service/UserService.java
> +    }
Вот это через стрим апи напиши так, чтобы не нужно было 2 раза делать userRepository.findById(id) 
Один раз вызываешь, и там же в стриме обрабатываешь ошибку

2024-01-21 07:31 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/premium/PremiumDto.java
> +    Long userId;
Тут еще можно добавить поля на сколько дней эта подписка и сколько он заплатил

2024-01-21 07:31 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/payment/ErrorResponse.java
> +}
Откуда это и зачем?

2024-01-21 07:31 UTC, InnMish commented on src/test/java/school/faang/user_service/service/UserServiceTest.java
> +}
Тесты на оба маппера добавить

2024-01-21 07:57 UTC, kamil516 commented on src/main/java/school/faang/user_service/dto/payment/ErrorResponse.java
> +}
это из payment сервиса, подумал может пригодится когда payment допилим

2024-01-23 08:14 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/payment/ErrorResponse.java
> +}
Значит, тогда и добавим 
Сейчас это просто лишний класс)

2024-01-23 08:15 UTC, InnMish requested changes

2024-01-23 08:15 UTC, InnMish commented on src/main/java/school/faang/user_service/client/PaymentServiceClient.java
> +    @PostMapping("/api/payment")
Почему resolved? Не перенесено

2024-01-23 08:15 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/PremiumController.java
> +@RequestMapping("/api/premium")
Не исправлено

2024-01-25 06:53 UTC, closed without merging