Интеграция с генератором случайных аватаров юзера
CorporationX/user_service pull request #789
Opened 2024-01-30 22:40 UTC by Edisolt5498

2024-02-04 12:27 UTC, ruslanator approved these changes

2024-02-13 07:29 UTC, InnMish requested changes

2024-02-13 07:29 UTC, InnMish commented on src/main/java/school/faang/user_service/controller/user/UserController.java
> +    @PostMapping()
Можно без скобок писать, если ничего не дописываем

2024-02-13 07:29 UTC, InnMish commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        //some actions
Знаешь же, что я такое не пропущу и придется переделывать - давай с первого раза хорошо все писать 
Если ты такой код кому-нибудь покажешь, они увидят в нем какую-то ценность? Я думаю, нет 
someActions это просто сохранение в бд - это же базовый метод вообще, напиши тут как следует

2024-02-13 07:29 UTC, InnMish commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        //some actions
Когда выполняешь задачу, ты добавляешь новый логический участок 
Кто будет в приложении пользоваться твоим сервисом рандомных аватарок, если этот человек даже создать профиль не может?)

2024-02-13 07:29 UTC, InnMish commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        return userDto;
А как мне убедиться, что у пользователя здесь аватарка добавилась? Что тут вообще возвращается? То же самое, что пользователь в дто отправил

2024-02-13 07:29 UTC, InnMish commented on src/main/java/school/faang/user_service/service/user/UserService.java
> +        return userMapper.toDto(getExistingUserById(id));
У тебя аватарка в бд не сохранятся) и вообще пользователь не сохраняется 
А что тогда ты там ищешь?

2024-02-20 10:29 UTC, merged