Werewolf bc2 bjs2 1894
CorporationX/user_service pull request #810
Opened 2024-02-07 21:27 UTC by ruslanator

2024-02-08 16:02 UTC, Edisolt5498 requested changes

2024-02-08 16:02 UTC, Edisolt5498 commented on src/main/java/school/faang/user_service/mapper/event/EventMapper.java
> +    default List<Event> toListEntity(List<EventDto> events) {
Если не ошибаюсь, можно вот так:  List<Event> toListEntity(List<EventDto> events); и MapStruct всё сам сгенерирует

2024-02-08 16:02 UTC, Edisolt5498 commented on src/main/resources/application.yaml
> +  port: 8085
Это наверное временно менял?

2024-02-13 09:55 UTC, InnMish commented on src/main/java/school/faang/user_service/mapper/RecommendationMapper.java
> +}
а это зачем?

2024-02-13 09:55 UTC, InnMish commented on src/main/java/school/faang/user_service/scheduler/EventScheduler.java
> +    @Scheduled(cron = "0 0 * * * *")
надо разобраться как сделать так, чтобы не выдавал ошибку)

2024-02-13 09:55 UTC, InnMish commented on src/main/java/school/faang/user_service/config/async/AsyncConfig.java
> +        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
А специально с какой-то целью так делаешь? Можно через EnableAcync еще 
Но так хорошо

2024-02-13 09:55 UTC, InnMish commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +public interface RecommendationRequestMapper {
и это тоже зачем...

2024-02-13 09:55 UTC, InnMish commented on src/main/java/school/faang/user_service/mapper/RecommendationRequestMapper.java
> +public interface RecommendationRequestMapper {
если без них что-то не работает, значит в мастере были ошибки 
Не нужно их голыми добавлять, нужно решать проблему глобально в мастере - лучше всего через меня

2024-02-15 20:33 UTC, ruslanator commented on src/main/java/school/faang/user_service/config/async/AsyncConfig.java
> +        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
прочитал в туторе, что best practice это переопределять свой executor через реализацию интерфейса asynConfigurer, но для этой задачи наверное бессмысленно и можно просто через enableAsync

2024-02-18 14:45 UTC, merged