BJS2-6276 (Подписка на других пользователей)
CorporationX/user_service pull request #984
Opened 2024-04-29 15:17 UTC by NadirCianid

Действия "Просмотреть свои подписки" и "Получить количество своих подписок" полностью совпадают с действиями "Получить всех подписчиков" и "Получить количество подписчиков". Меняется лишь входной параметр (id пользователя).

2024-05-02 13:43 UTC, nn1ck0 approved these changes

2024-05-02 22:54 UTC, Sabina-Vishnya requested changes

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/dto/UserFilterDto.java
> +    public boolean matches(User user) {
метод длинный, читать его будет не очень удобно, давай подрефачим
самый простой вариант это разделить логику по отдельным приватным методам для каждой проверки, а в методе matches потом просто использовать их

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    @Test
тесты это супер, но комменты тут ни к чему эти с шагами, можно просто оставить отступы на месте, чтобы визуально было логическое разделение, а вот что было бы еще круто добавить, так это аннотацию @DisplayName для каждого тестируемого метода + негативные кейсы, помимо позитивных
это ко всем твоим тестам если что коммент относится

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/dto/UserFilterDtoTest.java
> +    void nonmatchingArgTest() {
nonmatchingArgTest -> nonMatchingArgTest

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/controller/SubscriptionController.java
> +        if (followerId == followeeId) {
вот тут небольшое дублирование для валидации тоже можно вынести в приватный метод, хоть у тебя тут и разные сообщения, но можно, например, для этого сообщения добавить 3-й параметр в общий приватный метод, затем в этот метод подставлять нужное тебе сообщение

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +    public List<UserDto> filterUsers(Stream<User> users, UserFilterDto filter) {
filterUsers публичный для тестов только? Судя по коду-да
Тесты подправь, а метод запривать, он же вспомогательный тут судя по всему?
Ради тестов метод точно не надо делать доступным, если этого не требуется
либо тесты правятся, либо декомпозируется логика. В нашем случаем можем обойтисьь тем, чтобы тесты в порядок привести просто

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    ArgumentCaptor<Long> followerArgumentCaptor;
почти во всех тестах зачем-то дефолтный модификатор у полей, инкапсулируй, так как это данные, которые используются лишь в тестовом классе, а если же это не так, то лучше делать тестовый класс утилит с общими тестовыми данными
тесты всё же попробуй более менее подправить

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        var followingCount = subscriptionService.getFollowingCount(followerId);
тут переменная не используется

2024-05-02 22:54 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        verify(subscriptionRepo, times(1)).findFolloweesAmountByFollowerId(followerArgumentCaptor.capture());
verify по дефолту times(1), поэтому можно не указывать явно times(1) там где вызов 1 раз происходит

2024-05-02 23:03 UTC, Sabina-Vishnya requested changes

2024-05-02 23:03 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/service/SubscriptionServiceTest.java
> +        Stream<User> allFollowers = new ArrayList<User>().stream();
allFollowers нигде не используется и пустой всегда, можно, например, вернуть сразу в thenReturn Stream.Builder

2024-05-03 07:13 UTC, NadirCianid commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    @Test
я и так негативные тесты пишу. И проверяю покрытие кода. Какие негативные тесты я пропустил?

2024-05-03 14:00 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    @Test
хорошо, если так) это скорее общая рекомендация про позитивные и негативные тесты, также есть стиль именования юнит-тестов, тут кто как делает в командах, например, тут можно посмотреть https://dzone.com/articles/7-popular-unit-test-naming 
это позволяет понять суть проверки и даже увидеть негативный или позитивный тест 
в нашем случае, можно разделить негативные и позитивные, вложенными классами хотя бы @Nested, поскольку сразу так увидеть сложно, где позитивный, а где негативный, т.е. нужно прям в бизнес-логику скорее всего еще сильнее погружаться, а ревью кода часто проводят еще и чисто техническое, и чем твой код очевиднее, понятнее, читается просто, тем проще сразу будет коллегам провести хорошее ревью, а если даже коллега за бизнес-логику еще проверяет, то тем более сориентируется быстро, что учтено, что нет и тд. 
Так что, очевидно, стоит повысить читаемость кода, обозначить хотя бы, где негативные, а где позитивные тесты

2024-05-03 14:29 UTC, InnMish commented on src/main/java/school/faang/user_service/dto/UserFilterDto.java
> +    private int pageSize;       //непонятный фильтр
Убирай 
Это мы в условии оставили, когда только писали задачу 
Удаляй их, если не используешь - тебе они сейчас не нужны

2024-05-03 14:29 UTC, InnMish commented on src/main/java/school/faang/user_service/service/SubscriptionService.java
> +                .filter(filter::matches)
посмотри видео на платформе, https://faang-school.com/courses/mbvd6kz9/63zkb48d 
Там Влад показывает, как фильтры написать красиво и расширяемо через паттерн 

Попробуй сделать так 
Будет красивее и более расширяемо

2024-05-04 13:43 UTC, Sabina-Vishnya requested changes

2024-05-04 13:43 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/filter/UserCityFilter.java
> +package school.faang.user_service.service.user.filter;
лучше пакет наоборот назвать filter.user, вдруг у нас будут еще фильтры для других дто + форматирование поправь и на всякий случай места, если есть неиспользуемые импорты
1. Форматирование: ⌘⌥L (macOS) / Ctrl+Alt+L (Windows/Linux) в каждом классе. Или перед коммитом можно в idea настроить Reformat Code добавив галочку 
2. Для импортов: Ctrl + Alt + O (Windows/Linux) или ⌘ + Option + O (macOS). Или Optimize imports при коммите

2024-05-04 13:43 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +    @Test
@NadirCianid коммент про аннотации и ссылки с примерами нейминга используй везде, а не только в этом классе, писала же "ко всем твоим тестам если что коммент относится")) 
и про дефолтный модификатор у полей тоже коммент писала, относится ко всем тестам и еще попробуй тесты упростить и по возможности используй параметризованные тесты, посмотри и поправь, там где это можно

2024-05-04 13:43 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
в двух тестовых классах увидела эту аннотацию, сможешь объяснить зачем она и почему где-то есть, а где-то нет?

2024-05-04 13:43 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
unmappedTargetPolicy = ReportingPolicy.IGNORE для чего?

2024-05-04 13:51 UTC, Sabina-Vishnya requested changes

2024-05-04 13:51 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/filter/UserSkillFilter.java
> +public class UserSkillFilter implements UserFilter{
точно все фильтры должны быть публичными? почему?
а если это только для тестов, то пересмотри тесты, но логику инкапсулируй 
скорее всего импорты ругнуться для SubscriptionServiceTest, тогда подумай лучше как организовать тесты

2024-05-04 14:09 UTC, NadirCianid commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
Писал ее там, где много полей нужно сделать приватными. Чтобы не писать каждый раз private. А в тестах, где полей не так много прописывал уровень доступа вручную. 

Проблема в том, что нет общего подхода?

2024-05-04 14:09 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
Влад в лекции так показывал...

2024-05-04 14:14 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/user/filter/UserSkillFilter.java
> +public class UserSkillFilter implements UserFilter{
Я думаю, что все фильтры должны быть публичными. (В видео на платформе Влад фильтры делал публичными и не упоминал, в каких случаях стоит их делать приватными)

Почему им (или некоторым из них) надо быть приватными?

2024-05-05 14:49 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
1). общий подход, да
2). на мой взгляд это не слишком очевидно может быть для остальных
3). ломбок конеечно хорош, но и проблем может привнести в каких-то случаях, а модификаторы как-будто бы не такой уж бойлерплейт
в целом, это вкусовщина, если решил аннотацию использовать, то используй, но тогда какой-то общий стиль стоит держать всем в команде

2024-05-05 14:49 UTC, Sabina-Vishnya commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
1). общий подход, да
2). на мой взгляд это не слишком очевидно может быть для остальных
3). ломбок конеечно хорош, но и проблем может привнести в каких-то случаях, а модификаторы как-будто бы не такой уж бойлерплейт
в целом, это вкусовщина, если решил аннотацию использовать, то используй, но тогда какой-то общий стиль стоит держать всем в команде

2024-05-05 14:49 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
ну а ты разобрался для чего она?

2024-05-05 15:28 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/filter/UserSkillFilter.java
> +public class UserSkillFilter implements UserFilter{
Влад показывал пример применения паттерна, чтобы писать код гибче и профессиональнее, какие-то вещи мог не объяснять и не затрагивать, тк задача видео в другом состояла и в видео наглядно показано, как можно сделать лучше с помощью паттерна. 
Ты это сделал, но мы же сейчас говорим об инкапсуляции фильтров в контексте задачки. И используем хороший подход не просто гляда на видео, а вдумчиво, стараясь объяснить себе, зачем и почему это всё так организовано, когда можем применить и как.

Зачем нам вообще SOLID? Зачем мы инкапсулируем логику? Почему в данном случае фильтры должны быть публичными? Потому что в видео так? Это не ответ, нужен аргумент пожирнее. Ты как разработчик выбираешь подход и организацию своего кода исходя от бизнес логики ведь еще. 

Сейчас фильтры где-то используются? (помимо тестов) - Нет. 
Если кому-то и понадобятся, тогда этот кто-то сам разберется в реализации, если надо - поменяет модификатор, а может и не только модификаторы, вдруг там совсем другая история начнется и будет рефакторинг. Это уже задача другая совсем и какая-то фантомная, мы не знаем будет ли она вообще. Если знаешь, то что за задача?

Хорошая практика начинать с самого недоступного и расширять по необходимости. 
Ты переделал реализацию фильтров и теперь используешь интерфейс, в данный момент делать публичными все фильтры нет смысла.

2024-05-05 15:28 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/service/user/filter/UserSkillFilter.java
> +public class UserSkillFilter implements UserFilter{
+ форматирование не поправлено

2024-05-05 20:20 UTC, NadirCianid commented on src/test/java/school/faang/user_service/controller/SubscriptionControllerTest.java
> +@FieldDefaults(level = AccessLevel.PRIVATE)
хорошо, пока вернусь к явному указанию типа доступа

2024-05-05 20:42 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/user/filter/UserSkillFilter.java
> +public class UserSkillFilter implements UserFilter{
честно говоря я не понимаю, как в данном случае инкапсулировать логику фильтров. Сделать методы приватными просто не получится, так как я не смогу в сервисе к ним обратиться. 
 
 А, как иначе, я пока не понимаю

2024-05-06 05:54 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
Да. Для того, чтобы игнорировать поля, не указанные для маппинга.

2024-05-06 21:48 UTC, Sabina-Vishnya commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
хорошо, что разобрался) но тут какой в ней смысл то? без игнора чем не нравится, что-то не так будет? 
+ у тебя полетело местами форматирование еще
+ почему-то я сразу это не заметила, но у тебя UserDto с публичными полями, зачем?

Можно было бы влить и поправить эти мелкие штуки в других ПР-ах, но если бы не эти публичные поля
причем они у тебя были приватными

2024-05-06 21:56 UTC, NadirCianid commented on src/main/java/school/faang/user_service/service/user/filter/UserSkillFilter.java
> +public class UserSkillFilter implements UserFilter{
инкапсулировал фильтры

2024-05-06 22:02 UTC, NadirCianid commented on src/main/java/school/faang/user_service/mapper/UserMapper.java
> +@Mapper(componentModel = "spring", unmappedTargetPolicy = ReportingPolicy.IGNORE)
исправил поля в UserDto

2024-05-07 18:54 UTC, Sabina-Vishnya approved these changes

2024-05-07 18:57 UTC, Sabina-Vishnya approved these changes

2024-05-07 19:13 UTC, merged