basilisk-master-bc4-get-skills-user
CorporationX/user_service pull request #997
Opened 2024-05-02 18:25 UTC by AVishevsky

2024-05-05 19:10 UTC, Makaksik13 requested changes

2024-05-05 19:10 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +@RequiredArgsConstructor
Не очень понял, зачем тебе нужна аннотация @Component, если у тебя уже есть @Controller. В неё она(т.е. @Component) уже встроена.

2024-05-05 19:10 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +@Component
@service тоже содержит @component.

2024-05-05 19:10 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillRepository.findAllByUserId(userId).stream().map(skillMapper::toDto).toList();
А что будет, если userId null? Нужна проверка.

2024-05-05 19:10 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +}
Лишний отступ. Не забывай прожимать сочетание клавиш для форматирования.

2024-05-05 19:10 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +@Slf4j
Логи не использовал, а аннотация есть.

2024-05-05 19:10 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +    public SkillDto create(SkillDto skill) {
Перед методом должен быть пробел.

2024-05-06 06:41 UTC, daniel-tomberg reviewed
осталось внести финальные штрихи и готово)

2024-05-06 06:41 UTC, daniel-tomberg commented on src/main/java/school/faang/user_service/service/SkillService.java
> +@RequiredArgsConstructor
Service уже содержит в себе аннотацию @component, поэтому писать компонент не обязательно

2024-05-06 06:41 UTC, daniel-tomberg commented on src/main/java/school/faang/user_service/service/SkillService.java
>      }
Я бы разделил объявление переменных и метод create отступом и в самом create тоже поставил отступы между валидацией и  превращением в entity, лучше читается

2024-05-06 06:41 UTC, Ethiqque commented on src/main/java/school/faang/user_service/controller/SkillController.java
> +@Slf4j
согласен с ним

2024-05-06 18:36 UTC, AVishneskiy commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillRepository.findAllByUserId(userId).stream().map(skillMapper::toDto).toList();
примитивные типы данных не могут быть null)

2024-05-09 18:42 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillRepository.findAllByUserId(userId).stream().map(skillMapper::toDto).toList();
Извини, затупил.

2024-05-09 18:52 UTC, Makaksik13 requested changes

2024-05-09 18:52 UTC, Makaksik13 commented on src/main/java/school/faang/user_service/service/SkillService.java
> +        return skillRepository.findAllByUserId(userId).stream().map(skillMapper::toDto).toList();
Все терминальные/промежуточные операции должны начинать с новой строки. Исправишь, можешь отправлять сразу на ревью.

2024-05-12 06:35 UTC, merged